"""B2.1 Unit 1 - Forty Minutes Behind - ten figures, as data."""
FIGURES = {
"fig_b21_u01_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The newsroom at 15.40',
 sub='Twelve things to find. Four of them are counting down to the same moment.',
 alt='An open-plan newsroom at twenty to four in the afternoon, with a wall clock, a market '
     'ticker, a draft headline on a screen, a telephone on speaker and an editor standing over a '
     'seated reporter.',
 sky='#D3DADE', ground='#938C80', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#AFB6B4', cutaway=True,
     floor_labels=['the lawyers, one floor up', 'the business desk', 'the news desk'],
     label='the Herald newsroom'),
   dict(x=560, w=480, storeys=3, colour='#B9BDB6', cutaway=True,
     floor_labels=['the ticker on the wall', 'the screens - one of them is a rival\'s site',
                   'the editor and the reporter'],
     label='the pod where this is being decided'),
   dict(x=1120, w=460, storeys=3, colour='#A8AFAE', cutaway=True,
     floor_labels=['the window on to King Street', 'the empty subs desk',
                   'the conference room - 16.30'],
     label='the rest of the floor')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='15:40'),
   dict(kind='table', x=700, y=700, s=1.6), dict(kind='chair', x=660, y=700, s=1.1),
   dict(kind='cup', x=780, y=654, s=1.4),
   dict(kind='doc', x=0, y=0, s=1) if False else dict(kind='box', x=1180, y=700, s=1.0),
   dict(kind='crate', x=1280, y=700, s=1.0),
   dict(kind='hoarding', x=120, y=700, s=.7, w=150, notice=True),
   dict(kind='sign', x=1480, y=700, s=.8, text='TSX')],
 people=[dict(x=880, y=700, h=92, skin=3, cloth=2, hair='bun', arm='point'),
   dict(x=960, y=700, h=86, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=300, y=700, h=88, skin=1, cloth=0, hair='grey', arm='folded'),
   dict(x=1380, y=700, h=88, skin=2, cloth=4, hair='long', arm='down'),
   dict(x=1040, y=700, h=86, skin=0, cloth=1, hair='cap', arm='hold')],
 names=[dict(x=880, t='Priya Raghavan - news editor, standing'),
   dict(x=960, t='Laran Bakare - business, and he filed it'),
   dict(x=300, t='Marta Kowal - standards, one floor down'),
   dict(x=1380, t='Dennis Hoy - subeditor, 31 years, waiting'),
   dict(x=1040, t='the phone on speaker - the second plant'),
   dict(x=520, t='the wall clock: 15.40'),
   dict(x=1480, t='the ticker - twenty minutes of trading left'),
   dict(x=120, t='the standards policy, pinned up in 2016')],
 markers=[dict(x=880, y=570), dict(x=960, y=578), dict(x=300, y=574), dict(x=1380, y=574),
   dict(x=1040, y=578), dict(x=520, y=630), dict(x=1480, y=630), dict(x=120, y=640),
   dict(x=700, y=652), dict(x=780, y=610), dict(x=1180, y=650), dict(x=1280, y=656)]),

"fig_b21_u01_p01_v02": dict(type='V2', height=820,
 title='One claim, in section',
 sub='Twelve words, and each of them lives on exactly one layer.',
 alt='A cutaway of a single news claim in four layers, from the person who said it, through '
     'corroboration and verification, to publication and what happens afterwards.',
 floors=[dict(was='the layer of the claim', now='claim · source · stringer · dateline',
     year='', fill='#F3EADA'),
   dict(was='the layer of the check', now='evidence · corroboration · verification · provenance',
     year='', fill='#E8EEF0'),
   dict(was='the layer of the sentence', now='attribution · embargo · the published wording',
     year='', fill='#EFE6DC'),
   dict(was='the layer underneath', now='correction · retraction · and the archive, '
     'which is permanent', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Everything here is somebody saying something'),
   dict(at=0.38, text='The only layer where anything is tested'),
   dict(at=0.62, text='The layer the reader actually sees, and it is one sentence thick'),
   dict(at=0.88, text='This layer outlives the story and is read by search engines')]),

"fig_b21_u01_p02_v07": dict(type='V7', height=840,
 title='Fifteen forty',
 sub='She is standing. He has filed it. Neither of them has twenty minutes.',
 alt='A news editor standing over a seated business reporter in a newsroom with a phone on '
     'speaker between them, each with two speech balloons and a thought balloon.',
 bg='#E3E6E4',
 set=[dict(kind='table', x=760, y=680, s=2.0), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='chair', x=1400, y=680, s=1.1)],
 people=[dict(x=520, h=250, skin=3, cloth=2, hair='bun', arm='point', facing='right',
   label='Priya', role='news editor, fourteen years',
   says=['Who else has it?', 'We can\'t stand it up with one caller.'],
   thinks=['If I hold and they run it, I own that too.']),
  dict(x=1080, h=240, skin=4, cloth=3, hair='short', arm='hold', facing='left',
   label='Laran', role='business desk, and the stringer called him',
   says=['She has never been wrong in eleven years.',
         'The company is cutting four hundred jobs.'],
   thinks=['Never wrong is not the same as corroborated.'])]),

"fig_b21_u01_p03_v09": dict(type='V9', kind='timeline', height=800,
 title='Aspect is a claim about shape, not about time',
 sub='The same event, drawn four ways. Time is the horizontal axis and aspect is the shape.',
 alt='A timeline showing the same event rendered four ways: as a closed point, as an open band, '
     'as a point seen from a later vantage, and as a band running up to a later vantage.',
 now=0.86,
 bands=[dict(**{'from': 0.30, 'to': 0.30}, type='event', lane=1, label='SIMPLE - closed',
     example='The company cut 400 jobs. -- complete, countable, final'),
   dict(**{'from': 0.22, 'to': 0.52}, type='span', lane=2, label='CONTINUOUS - open',
     example='The company is cutting jobs. -- in progress, and the number may still move'),
   dict(**{'from': 0.30, 'to': 0.86}, type='reach', lane=4, label='PERFECT - seen from now',
     example='The company has cut 400 jobs. -- closed, and it matters because of now'),
   dict(**{'from': 0.14, 'to': 0.86}, type='before', lane=6,
     label='PERFECT CONTINUOUS - duration up to now',
     example='The company has been cutting jobs since March.')]),

"fig_b21_u01_p04_v04": dict(type='V4', height=740,
 title='Two sentences, one source',
 sub='The same information, published forty minutes apart by two newspapers.',
 alt='Two published sentences about the same story set side by side, one unhedged and published '
     'before the market closed, the other hedged and published the next morning.',
 differences=6, prompt='Find the six. One of the two required a correction. Which, and which '
                       'single word made the difference?',
 left=dict(label='15.52, the rival', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#A8372E'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='"is cutting 400 jobs" · 0 hedges · 4% move · correction Friday',
        colour='#A8372E')]),
 right=dict(label='09.10, the Herald', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=200, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=72, w=160, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='"is understood to be considering" · 2 hedges · 0 correction',
        colour='#2E6F5E')])),

"fig_b21_u01_p05_v05": dict(type='V5', height=1060,
 title='The claim and the correction',
 sub='The original ran at 15.52 on Tuesday. The correction ran on Friday, on page eleven.',
 alt='The rival newspaper\'s original claim and its subsequent correction set out with their '
     'word counts, placement, aspect and what each one does and does not say.',
 rows=[dict(t='org', text='THE ORIGINAL  -  TUESDAY 15.52  -  HOME PAGE, LEAD'),
   dict(t='para', text='"The company is cutting four hundred jobs at its Thunder Bay plant, '
     'with an announcement expected on Thursday."'),
   dict(t='grid', cols=['FEATURE', 'ORIGINAL', 'CORRECTION'],
     data=[['WORDS', '21', '34'],
           ['PLACEMENT', 'HOME PAGE LEAD', 'PAGE 11'],
           ['ASPECT', 'IS CUTTING', 'HAS CONFIRMED'],
           ['HEDGES', '0', '0'],
           ['NUMBER', '400', '310'],
           ['TIMING CLAIM', 'THURSDAY', 'NONE'],
           ['SOURCES NAMED', '0', '1 (THE COMPANY)'],
           ['TIME ON SITE', '3 DAYS', 'PERMANENT']]),
   dict(t='rule'),
   dict(t='head', text='THE CORRECTION, FRIDAY, IN FULL'),
   dict(t='para', text='"On Tuesday we reported that the company was cutting four hundred jobs '
     'at its Thunder Bay plant. The company has confirmed three hundred and ten. We are happy '
     'to clarify."'),
   dict(t='rule'),
   dict(t='head', text='WHAT THE CORRECTION DOES NOT SAY'),
   dict(t='kv', k='That the timing claim was wrong', v='not mentioned', mono=False),
   dict(t='kv', k='Where the 400 came from', v='not mentioned', mono=False),
   dict(t='kv', k='That the share price moved', v='not mentioned', mono=False),
   dict(t='kv', k='Who wrote it', v='no byline', mono=False)],
 callouts=[dict(at=0.10, text='Twenty-one words, and three separate claims in them'),
   dict(at=0.28, text='Is cutting against has confirmed - the whole unit is in those two'),
   dict(at=0.36, text='Four hundred against three hundred and ten'),
   dict(at=0.46, text='The timing claim is simply dropped rather than corrected'),
   dict(at=0.86, text='Happy to clarify is doing a great deal of work')]),

"fig_b21_u01_p07_v10": dict(type='V10', kind='stress', height=820,
 title='Prominence falls on what is new',
 sub='The same seven words, five times. Each version answers a different unasked question.',
 alt='One sentence drawn five times as beats with a different syllable enlarged in each, with '
     'the implied question beside it.',
 items=[
  dict(syllables=['we', "can't", 'stand', 'it', 'UP'], strong=[4],
       note='the problem is the verification itself'),
  dict(syllables=['WE', "can't", 'stand', 'it', 'up'], strong=[0],
       note='somebody else could - we cannot'),
  dict(syllables=['we', "CAN'T", 'stand', 'it', 'up'], strong=[1],
       note='it has been tried and it failed'),
  dict(syllables=['we', "can't", 'stand', 'IT', 'up'], strong=[3],
       note='this one. The other one we could'),
  dict(syllables=['the', 'com-pa-ny', 'IS', 'cut-ting'], strong=[2],
       note='somebody has denied it'),
  dict(syllables=['the', 'com-pa-ny', 'is', 'CUT-ting'], strong=[3],
       note='somebody expected something else')]),

"fig_b21_u01_p09_v05": dict(type='V5', height=980,
 title='Four claims a learner makes, and the evidence behind them',
 sub='Each claim was made this term. Each has been acted on for years.',
 alt='A table of four claims learners commonly make about their own English with the evidence, '
     'corroboration, date of last test and the cost of each.',
 rows=[dict(t='org', text='CLAIMS ABOUT MY OWN ENGLISH  -  AN AUDIT'),
   dict(t='grid', cols=['CLAIM', 'EVIDENCE', 'LAST TESTED'],
     data=[['"MY GRAMMAR IS BAD"', 'ONE MARKED ESSAY', '2021'],
           ['"I CAN\'T UNDERSTAND FILMS"', 'ONE FILM, SOUND LOW', '2022'],
           ['"MY ACCENT IS THE PROBLEM"', 'ONE COMMENT, 2019', '2019'],
           ['"I HAVE A BAD MEMORY"', 'NONE', 'NEVER']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH ONE HAS COST'),
   dict(t='kv', k='"My grammar is bad"', v='four years of avoiding writing', mono=False),
   dict(t='kv', k='"I can\'t understand films"', v='no unscripted input at all', mono=False),
   dict(t='kv', k='"My accent is the problem"', v='reduced speaking, raised anxiety',
     mono=False),
   dict(t='kv', k='"I have a bad memory"', v='no system, because systems are for other people',
     mono=False),
   dict(t='rule'),
   dict(t='head', text='CORROBORATION'),
   dict(t='kv', k='Claims with a second source', v='0 of 4', mono=True),
   dict(t='kv', k='Claims with a date', v='3 of 4', mono=True),
   dict(t='kv', k='Claims tested in the last year', v='0 of 4', mono=True),
   dict(t='rule'),
   dict(t='para', text='Every one of these would be held by a standards editor. All four have '
     'been running as settled fact for between two and six years, and each of them is doing '
     'more damage than the deficiency it describes.')],
 callouts=[dict(at=0.14, text='One essay, four years ago, marked by one person'),
   dict(at=0.22, text='One film, and the sound was low'),
   dict(at=0.34, text='No evidence at all, and the longest-running of the four'),
   dict(at=0.60, text='The cost is never the belief. It is the behaviour it licenses'),
   dict(at=0.90, text='None of the four would survive the questions in 9C')]),

"fig_b21_u01_p10_v12": dict(type='V12',
 title='Twenty minutes, two newspapers, one correction',
 sub='The three bands the newsroom argued about, and the fourth it never measured.',
 alt='An infographic of the twenty minutes before the market close showing what each paper knew, '
     'what each published, the traffic each received, and the permanence of each piece of text.',
 span=['15.40', '09.10 next day'], ticks=5,
 tick_labels=['15.40', '15.52', '16.00', '21.00', '09.10'],
 bands=[dict(name='What was known', type='events', items=[
   dict(at=0.04, label='one source, one screenshot', colour='#C86B2B'),
   dict(at=0.30, label='still one source', colour='#C86B2B'),
   dict(at=0.62, label='second plant has not called back', colour='#9AA7AE'),
   dict(at=0.92, label='a second account, partial', colour='#2E6F5E')]),
  dict(name='The rival', type='bars', items=[
   dict(**{'from': 0.18, 'to': 1.0}, label='published 15.52 · "is cutting 400"',
        colour='#A8372E')]),
  dict(name='The Herald', type='bars', items=[
   dict(**{'from': 0.92, 'to': 1.0}, label='published 09.10 · "is understood to be considering"',
        colour='#2E6F5E')]),
  dict(name='Page views, thousands', type='line',
   points=[(0, 0), (0.3, 41), (0.6, 96), (0.8, 54), (1.0, 12)], end_label='12k'),
  dict(name='What nobody measured', type='flags', items=[
   dict(at=0.10, label='the correction was shared 40,000 times and is permanent'),
   dict(at=0.52, label='no figure exists for what a correction costs six months later')])]),

"fig_b21_u01_p11_v06": dict(type='V6', kind='line', height=820,
 title='Corrections, trust and the cost nobody can price',
 sub='Six years of one newspaper, with the trust survey plotted against the correction count.',
 alt='A line chart of corrections published per year against the proportion of readers saying '
     'they trust the paper, over six years, with a note about the lag between the two.',
 labels=['2019', '2020', '2021', '2022', '2023', 'now'],
 fmt='{:,.0f}',
 ymin=0, ymax=200,
 series=[dict(name='corrections (2019=100)',
              values=[100, 125, 155, 164, 181, 187], colour='#A8372E'),
   dict(name='stated trust (2019=100)', values=[100, 98, 95, 87, 80, 77],
        colour='#2E6F5E')],
 note='Corrections have risen 87 per cent in six years. Stated trust has fallen fourteen points '
      'over the same period, which is not the same as being caused by it.',
 warning='The trust line moves about eighteen months after the correction line, every time. '
         'Nobody at the paper has ever put the two series on one chart before, because they are '
         'owned by two departments and reported in different quarters.'),
}
