"""B2.1 Unit 2 - We Have Always Said - ten figures, as data."""
FIGURES = {
"fig_b21_u02_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The leader floor, Thursday afternoon',
 sub='Twelve things to find. Three carry a name and two deliberately do not.',
 alt='The editorial floor of a newspaper with the paper\'s name on the wall, a bound archive volume, a '
     'framed first column, an unsigned leader proof on a screen and an empty chair at the '
     'conference table.',
 sky='#D6D9D4', ground='#8E877B', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B2ADA0', cutaway=True,
     floor_labels=['the paper\'s name on the wall', 'the 1974 staff photograph',
                   'the bound archive, 1911 onwards'],
     label='the corridor'),
   dict(x=560, w=480, storeys=3, colour='#BAB6AA', cutaway=True,
     floor_labels=['the leader-page proof - no byline', 'the conference table',
                   'the empty chair'],
     label='the leader conference'),
   dict(x=1120, w=460, storeys=3, colour='#AFAB9F', cutaway=True,
     floor_labels=['the style guide, open at page 9', 'this week\'s op-eds',
                   'a reader\'s letter, and a map with one ward circled'],
     label='the columnists')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='16:00'),
   dict(kind='table', x=720, y=700, s=1.8), dict(kind='chair', x=680, y=700, s=1.1),
   dict(kind='chair', x=900, y=700, s=1.1),
   dict(kind='box', x=200, y=700, s=1.0), dict(kind='crate', x=1200, y=700, s=1.0),
   dict(kind='hoarding', x=1320, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=800, y=700, h=92, skin=3, cloth=2, hair='bun', arm='point'),
   dict(x=1000, y=700, h=86, skin=1, cloth=0, hair='grey', arm='folded'),
   dict(x=320, y=700, h=88, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=1420, y=700, h=88, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=1080, y=700, h=86, skin=0, cloth=1, hair='cap', arm='down')],
 names=[dict(x=800, t='Priya - chairing the leader conference'),
   dict(x=1000, t='the researcher, with the 2017 volume'),
   dict(x=320, t='the archive - every leader since 1911'),
   dict(x=1420, t='the columnist - nineteen years under her own name'),
   dict(x=1080, t='the empty chair - the writer of tomorrow\'s leader'),
   dict(x=520, t='the clock: four o\'clock'),
   dict(x=1320, t='the map, with Ward 7 circled'),
   dict(x=200, t='the style guide, open at page 9')],
 markers=[dict(x=800, y=570), dict(x=1000, y=574), dict(x=320, y=574), dict(x=1420, y=574),
   dict(x=1080, y=578), dict(x=520, y=630), dict(x=1320, y=644), dict(x=200, y=650),
   dict(x=720, y=652), dict(x=680, y=662), dict(x=1200, y=656), dict(x=300, y=444)]),

"fig_b21_u02_p01_v02": dict(type='V2', height=820,
 title='One voice, in section',
 sub='Twelve words, and the layer each one speaks from.',
 alt='A cutaway of a newspaper\'s voice in four layers, from the named individual through the '
     'institution to the group it counts and the group it claims to speak for.',
 floors=[dict(was='the people who speak', now='byline · columnist · correspondent · spokesperson',
     year='', fill='#F3EADA'),
   dict(was='the institution that speaks', now='editorial · outlet · voice',
     year='', fill='#E8EEF0'),
   dict(was='the group you count', now='readership · audience · membership',
     year='', fill='#EFE6DC'),
   dict(was='the group you claim', now='constituency · following',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The only layer with a person who can be argued with'),
   dict(at=0.38, text='Three words, and not one of them has a mouth'),
   dict(at=0.62, text='Counted, invoiced, and known to the nearest thousand'),
   dict(at=0.88, text='Invoked daily, counted never - and these two are not the same people')]),

"fig_b21_u02_p02_v07": dict(type='V7', height=840,
 title='The leader conference',
 sub='She has a draft that says always. He has the volume for 2017.',
 alt='A news editor and a researcher at a conference table with a bound archive volume open '
     'between them, each with two speech balloons and a thought balloon.',
 bg='#E6E6E0',
 set=[dict(kind='table', x=740, y=680, s=2.2), dict(kind='box', x=1360, y=680, s=1.0),
   dict(kind='cup', x=820, y=634, s=1.4)],
 people=[dict(x=520, h=250, skin=3, cloth=2, hair='bun', arm='point', facing='right',
   label='Priya', role='chairing, and the leader runs tomorrow',
   says=['We have always said this.', 'Find me a form of words.'],
   thinks=['Nobody in this room was here in 2017.']),
  dict(x=1080, h=240, skin=1, cloth=0, hair='grey', arm='hold', facing='left',
   label='the researcher', role='she has read every leader since 2011',
   says=['We said the opposite in 2017.',
         'We had said the opposite, until 2019.'],
   thinks=['Always is doing all the work in that sentence.'])]),

"fig_b21_u02_p03_v09": dict(type='V9', kind='timeline', height=820,
 title='Three perfects, three vantage points',
 sub='Each perfect imports a past event into a different present.',
 alt='A timeline showing a present perfect reaching to now, a past perfect reaching to an '
     'earlier point, and a future perfect reaching to a point ahead of now.',
 now=0.70,
 bands=[dict(**{'from': 0.12, 'to': 0.12}, type='event', lane=1,
     label='the event, 2017', example='We said the opposite. -- a dated point'),
   dict(**{'from': 0.30, 'to': 0.70}, type='reach', lane=3,
     label='PRESENT PERFECT - relevant now',
     example='We have said this since 2019.'),
   dict(**{'from': 0.12, 'to': 0.40}, type='before', lane=5,
     label='PAST PERFECT - relevant to a past point',
     example='We had said the opposite, until 2019.'),
   dict(**{'from': 0.70, 'to': 0.94}, type='future', lane=7,
     label='FUTURE PERFECT - complete by a point ahead',
     example='By March we will have held it for six years.')]),

"fig_b21_u02_p04_v04": dict(type='V4', height=740,
 title='Two editorials, six years apart',
 sub='The same page, the same institution, and no name on either of them.',
 alt='Two newspaper editorials set side by side, one from 2017 supporting a plan and one from '
     'today claiming the paper has always opposed it.',
 differences=6, prompt='Find the six. One sentence in the right-hand piece could not be written '
                       'if the left-hand one carried a date. Which?',
 left=dict(label='2017', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#9AA7AE'),
   dict(kind='block', x=150, y=106, w=200, bh=24, colour='#9AA7AE'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='"deserves a hearing" · 0 perfects · 1 date · no byline',
        colour='#9AA7AE')]),
 right=dict(label='today', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=72, w=180, bh=24, colour='#A8372E'),
   dict(kind='label', x=300, y=218,
        text='"we have always opposed it" · 4 perfects · 0 dates · no byline',
        colour='#A8372E')])),

"fig_b21_u02_p05_v05": dict(type='V5', height=1180,
 title='Two leaders, every pronoun marked',
 sub='Six years apart, on the same page, about the same plan.',
 alt='Two editorials set out with every first-person plural pronoun marked and the set each one '
     'claims, together with the perfects in each and what they import.',
 rows=[dict(t='org', text='LEADER PAGE  -  14 MARCH 2017'),
   dict(t='para', text='"The plan deserves a hearing. Our readers in the east end will want to '
     'know what it costs, and we will be asking."'),
   dict(t='rule'),
   dict(t='org', text='LEADER PAGE  -  TODAY'),
   dict(t='para', text='"We have always opposed this plan. This paper believes the community '
     'affected has been neglected, and we have said so throughout."'),
   dict(t='rule'),
   dict(t='grid', cols=['FEATURE', '2017', 'TODAY'],
     data=[['WE / OUR', '3', '4'],
           ['PERFECTS', '0', '4'],
           ['DATES', '1', '0'],
           ['NAMED PEOPLE', '0', '0'],
           ['BYLINE', 'NONE', 'NONE'],
           ['POSITION', 'DESERVES A HEARING', 'ALWAYS OPPOSED'],
           ['BOARD MEMBERS THEN', '9', '9'],
           ['SAME PEOPLE', '--', '2 OF 9']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH WE CLAIMS'),
   dict(t='kv', k='"our readers in the east end"', v='a set that can be counted', mono=False),
   dict(t='kv', k='"we will be asking"', v='the newsroom, about nine people', mono=False),
   dict(t='kv', k='"we have always opposed"', v='the institution, since 1911', mono=False),
   dict(t='kv', k='"we have said so throughout"', v='unspecifiable', mono=False),
   dict(t='rule'),
   dict(t='para', text='Two of the nine board members are the same people. The word *always* '
     'covers a hundred and fourteen years and seven of the nine have changed.')],
 callouts=[dict(at=0.08, text='A date, a place, and a promise that can be checked'),
   dict(at=0.22, text='Four perfects and no dates at all'),
   dict(at=0.46, text='The perfect count is the whole difference between the two pieces'),
   dict(at=0.70, text='The first we can be counted. The last cannot'),
   dict(at=0.94, text='Always is covering a change of seven people out of nine')]),

"fig_b21_u02_p07_v10": dict(type='V10', kind='stress', height=820,
 title='A stressed pronoun is a contrast',
 sub='The same sentence, four times, and each stress names somebody who is not in the room.',
 alt='One editorial sentence drawn four times as beats with a different word stressed in each, '
     'and the implied contrast beside it.',
 items=[
  dict(syllables=['WE', 'have', 'al-ways', 'said', 'this'], strong=[0],
       note='and somebody else has not'),
  dict(syllables=['we', 'HAVE', 'al-ways', 'said', 'this'], strong=[1],
       note='somebody has denied that we did'),
  dict(syllables=['we', 'have', 'AL-ways', 'said', 'this'], strong=[2],
       note='the continuity is the claim being made'),
  dict(syllables=['we', 'have', 'al-ways', 'said', 'THIS'], strong=[4],
       note='not the other thing you are accusing us of'),
  dict(syllables=['I', "didn't", 'say', 'it'], strong=[0], note='a person stepping out'),
  dict(syllables=['WE', 'said', 'it'], strong=[0], note='and a body stepping in')]),

"fig_b21_u02_p09_v05": dict(type='V5', height=980,
 title='Four sentences a learner says with we',
 sub='Each imports a group. Each borrows that group\'s excuse.',
 alt='A table of four first-person-plural claims learners make about their own English with the '
     'set each one imports, the evidence behind it, and what it licenses.',
 rows=[dict(t='org', text='THE WE IN YOUR OWN ACCOUNT  -  AN AUDIT'),
   dict(t='grid', cols=['THE SENTENCE', 'THE SET', 'EVIDENCE'],
     data=[['"IN MY COUNTRY WE DON\'T SPEAK"', '~40 MILLION', 'ONE SCHOOL'],
           ['"WE WERE NEVER TAUGHT THIS"', 'ONE CLASS, 2009-15', 'MEMORY'],
           ['"WE ALL HAVE THIS PROBLEM"', 'UNSPECIFIED', 'NONE'],
           ['"WE LEARN DIFFERENTLY"', 'UNSPECIFIED', 'NONE']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH ONE LICENSES'),
   dict(t='kv', k='"we don\'t speak"', v='not speaking, indefinitely', mono=False),
   dict(t='kv', k='"we were never taught"', v='not learning it now', mono=False),
   dict(t='kv', k='"we all have this problem"', v='no action, because it is general', mono=False),
   dict(t='kv', k='"we learn differently"', v='rejecting any method that is uncomfortable',
     mono=False),
   dict(t='rule'),
   dict(t='head', text='THE SAME CLAIMS, NARROWED'),
   dict(t='kv', k='Set of one', v='"I did not speak in class between 2009 and 2015."',
     mono=False),
   dict(t='kv', k='With a date', v='"I have not had a conversation in English since March."',
     mono=False),
   dict(t='rule'),
   dict(t='para', text='Narrowing does not make the sentence less true. It makes it a '
     'description of a situation rather than a description of a people, and a situation is a '
     'thing that can be changed this week.')],
 callouts=[dict(at=0.14, text='Forty million people, one school, and one person affected'),
   dict(at=0.26, text='A class that finished a decade ago'),
   dict(at=0.34, text='No set and no evidence, and the hardest one to argue with'),
   dict(at=0.56, text='Every one of these is a licence, not a complaint'),
   dict(at=0.90, text='The narrowed versions are all actionable this week')]),

"fig_b21_u02_p10_v12": dict(type='V12',
 title='Ward 7, two years, eighty-one pieces',
 sub='Who is quoted, who writes, and who the editorials say the paper speaks for.',
 alt='An infographic of two years of coverage of one ward showing who was quoted, where the '
     'reporters were based, the readership of each kind of piece, and what the editorials '
     'claimed.',
 span=['0', '81 pieces'], ticks=4,
 tick_labels=['0', '27', '54', '81'],
 bands=[dict(name='Who is quoted', type='events', items=[
   dict(at=0.11, label='a resident: 9', colour='#A8372E'),
   dict(at=0.51, label='a city councillor: 41', colour='#C86B2B'),
   dict(at=0.77, label='a police source: 62', colour='#1F4E5F')]),
  dict(name='Where it was written', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.89}, label='from the bureau, 4 km away - 72', colour='#9AA7AE'),
   dict(**{'from': 0.90, 'to': 1.0}, label='in the ward - 9', colour='#2E6F5E')]),
  dict(name='Readership', type='events', items=[
   dict(at=0.24, label='bureau pieces: median 18,400', colour='#9AA7AE'),
   dict(at=0.72, label='the six-day piece: 4,100 - the month\'s lowest', colour='#A8372E')]),
  dict(name='What the editorials said', type='events', items=[
   dict(at=0.34, label='"the ward has been neglected" - 4 times, nobody named',
        colour='#D9A441')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='nine residents quoted in two years, two of them the same person'),
   dict(at=0.46, label='the only piece written in the ward did worst, and will be cited')])]),

"fig_b21_u02_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Signed and unsigned, and what happens afterwards',
 sub='Five years of the Herald, comparing signed columns with unsigned leaders on the same four '
     'measures.',
 alt='A bar chart comparing signed columns and unsigned leaders on corrections issued, '
     'corrections unprompted, replies to readers and position reversals acknowledged.',
 labels=['corrections', 'unprompted', 'replies to readers', 'reversals admitted'],
 ymin=0, ymax=100, fmt='{:,.0f}',
 series=[dict(name='signed columns, per 100 pieces', values=[31, 19, 64, 11],
              colour='#2E6F5E'),
   dict(name='unsigned leaders, per 100 pieces', values=[9, 1, 4, 0], colour='#A8372E')],
 note='Signed columns are corrected three times as often. That is not a measure of accuracy; it '
      'is a measure of who there is to correct.',
 warning='Unsigned leaders have acknowledged a reversal of position nought times in five years, '
         'across at least fourteen reversals identified by the archive. There is nobody to '
         'acknowledge it, and no mechanism that requires it.'),
}
