"""B2.1 Unit 3 - A Doubling of Risk - ten figures, as data."""
FIGURES = {
"fig_b21_u03_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The health desk, twenty past four',
 sub='Twelve things to find. Two of them carry the same number and one says what it is out of.',
 alt='The health desk of a newspaper with a printed press release, a preprint on screen, a '
     'whiteboard carrying a base rate, a phone on speaker and a headline draft on a sticky note.',
 sky='#D9DCD8', ground='#8B8477', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B4AFA2', cutaway=True,
     floor_labels=['the style guide, open at RISK', 'the correction log',
                   'the deadlines'],
     label='the standards corner'),
   dict(x=560, w=480, storeys=3, colour='#BCB8AC', cutaway=True,
     floor_labels=['the preprint, on screen', 'the whiteboard: 4 in 10,000',
                   'the release'],
     label='the health desk'),
   dict(x=1120, w=460, storeys=3, colour='#B1ADA1', cutaway=True,
     floor_labels=['the chart with the shaded band', 'the headline draft',
                   'the calculator'],
     label='the back bench')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='16:40'),
   dict(kind='table', x=760, y=700, s=1.8), dict(kind='chair', x=700, y=700, s=1.1),
   dict(kind='cup', x=860, y=662, s=1.3),
   dict(kind='box', x=220, y=700, s=1.0), dict(kind='crate', x=1290, y=700, s=1.0),
   dict(kind='hoarding', x=1340, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=820, y=700, h=92, skin=4, cloth=2, hair='long', arm='hold'),
   dict(x=1075, y=700, h=86, skin=3, cloth=0, hair='bun', arm='point'),
   dict(x=340, y=700, h=88, skin=1, cloth=3, hair='grey', arm='folded'),
   dict(x=1440, y=700, h=88, skin=2, cloth=4, hair='short', arm='hold'),
   dict(x=1200, y=700, h=86, skin=0, cloth=1, hair='cap', arm='down')],
 names=[dict(x=820, t='Hana - she has read the preprint'),
   dict(x=1075, t='Priya - the first edition closes at six'),
   dict(x=340, t='the correction log, four years of it'),
   dict(x=1440, t='the phone, on speaker to an epidemiologist'),
   dict(x=1200, t='the headline draft, on a sticky note'),
   dict(x=520, t='the clock: twenty past four'),
   dict(x=1340, t='the chart, with its shaded band'),
   dict(x=220, t='the style guide, open at RISK')],
 markers=[dict(x=820, y=570), dict(x=1075, y=574), dict(x=340, y=574), dict(x=1440, y=574),
   dict(x=1200, y=578), dict(x=520, y=630), dict(x=1340, y=644), dict(x=220, y=650),
   dict(x=760, y=652), dict(x=860, y=640), dict(x=1290, y=656), dict(x=300, y=444)]),

"fig_b21_u03_p01_v02": dict(type='V2', height=820,
 title='One number, in section',
 sub='Twelve words, and the layer each one lives on. Count how many reach the top.',
 alt='A cutaway of a risk claim in four layers, from the data through the analysis and the '
     'statement of uncertainty to the headline, where none of the technical words survives.',
 floors=[dict(was='the data layer', now='cohort · exposure · incidence · prevalence · baseline',
     year='', fill='#EDF1EC'),
   dict(was='the analysis layer', now='risk · hazard · correlation · causation',
     year='', fill='#E8EEF0'),
   dict(was='the uncertainty layer', now='confidence · interval · significance',
     year='', fill='#F3EADA'),
   dict(was='the headline layer', now='doubles',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Counted in people, over a stated number of years'),
   dict(at=0.38, text='Two of these four are swapped for each other daily'),
   dict(at=0.62, text='The layer that says how much to trust the layer below'),
   dict(at=0.88, text='One word, eight characters, and none of the eleven below it')]),

"fig_b21_u03_p02_v07": dict(type='V7', height=840,
 title='The four o\'clock conference',
 sub='She has the preprint. He has a release, a deadline and a space for six words.',
 alt='A health reporter and a news editor at a desk with a printed press release between them, '
     'each with two speech balloons and a thought balloon.',
 bg='#E4E7E3',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=4, cloth=2, hair='long', arm='hold', facing='right',
   label='Hana', role='health desk, and she has read all forty pages',
   says=['It is four in ten thousand, not four in ten.',
         'That is overstating it.'],
   thinks=['The interval runs from 1.2 to 3.3.']),
  dict(x=1080, h=240, skin=3, cloth=0, hair='bun', arm='folded', facing='left',
   label='Priya', role='the first edition closes at six',
   says=['So it may well be real.',
         'We cannot rule it out, then.'],
   thinks=['Nobody clicks on four in ten thousand.'])]),

"fig_b21_u03_p03_v09": dict(type='V9', kind='ladder', height=760,
 title='The certainty ladder',
 sub='Six settings, one finding. Add a perfect to any rung and the deduction moves to the past: '
     'must have been, might well have been, could hardly have been.',
 alt='A vertical ladder of epistemic modals from must and is bound to at the top, through will, '
     'should, may and might, to cannot at the bottom, each with the commitment it makes.',
 top_label='it is so', bottom_label='it is not so',
 steps=[dict(form='must · is bound to', meaning='the strongest inference short of proof'),
   dict(form='will · is likely to', meaning='confident; the ordinary language of a forecast'),
   dict(form='should', meaning='expected, with room to be wrong'),
   dict(form='may · might · could', meaning='possible; no commitment of any kind'),
   dict(form='may or may not', meaning='explicitly balanced: a refusal to place the claim'),
   dict(form='cannot · could not', meaning='excluded by the evidence you actually have')]),

"fig_b21_u03_p04_v04": dict(type='V4', height=740,
 title='The same study, written twice',
 sub='One release, one abstract, one figure between them.',
 alt='Two accounts of the same finding side by side, one from a university press release and '
     'one from the preprint it describes.',
 differences=6, prompt='Find the six. One of the two documents contains a number a reader could '
                       'act on. Which, and where in the text does it come?',
 left=dict(label='the release', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=230, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=72, w=180, bh=24, colour='#A8372E'),
   dict(kind='label', x=300, y=218,
        text='"doubles" x3 · base rate 0 · interval 0 · 310 words',
        colour='#A8372E')]),
 right=dict(label='the preprint', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=106, w=200, bh=24),
   dict(kind='block', x=150, y=72, w=250, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='"4 to 8 per 10,000" · interval 1.2-3.3 · no causal claim',
        colour='#2E6F5E')])),

"fig_b21_u03_p05_v05": dict(type='V5', height=1200,
 title='The release, every certainty word marked',
 sub='Three hundred and ten words, and the only number in it is a ratio.',
 alt='A university press release annotated to show every word that sets a level of certainty, '
     'what each one claims, and the figures the release does not contain.',
 rows=[dict(t='org', text='UNIVERSITY PRESS OFFICE  -  EMBARGOED 09:00'),
   dict(t='head', text='NIGHT WORK DOUBLES HEART-RHYTHM RISK'),
   dict(t='para', text='"A major new study demonstrably links night-shift work to a doubling of '
     'risk of a rare heart-rhythm condition. The findings are highly significant and are said to '
     'be the largest of their kind."'),
   dict(t='para', text='"Lead author Dr Sollis said the result is bound to prompt a review of '
     'shift patterns. The research has yet to be peer reviewed."'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT IS IN IT', 'COUNT', 'WHERE'],
     data=[['THE WORD DOUBLES', '3', 'HEADLINE, PARA 1, PARA 4'],
           ['THE BASE RATE', '0', '--'],
           ['ABSOLUTE FIGURES', '0', '--'],
           ['THE INTERVAL', '0', '--'],
           ['WORDS IN TOTAL', '310', '--'],
           ['PEER REVIEW NOTED', '1', 'LAST LINE'],
           ['CAUSAL CLAIM IN PREPRINT', '0', '--'],
           ['CAUSAL CLAIM HERE', '1', 'PARA 1']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH CERTAINTY WORD CLAIMS'),
   dict(t='kv', k='"demonstrably links"', v='a causal link, which the authors refuse', mono=False),
   dict(t='kv', k='"highly significant"', v='large - which is not what it means', mono=False),
   dict(t='kv', k='"is said to be"', v='somebody else said it, unnamed', mono=False),
   dict(t='kv', k='"is bound to prompt"', v='a forecast at the top of the scale', mono=False),
   dict(t='kv', k='"has yet to be"', v='true, accurate, and in the last line', mono=False),
   dict(t='rule'),
   dict(t='para', text='The press office is measured on coverage obtained. Nobody in the building '
     'is measured on whether a reader could act on the number.')],
 callouts=[dict(at=0.08, text='A ratio in the headline and nothing to divide it by'),
   dict(at=0.20, text='Two certainty words above the scale the data supports'),
   dict(at=0.44, text='Four rows of nothing, and that is the finding'),
   dict(at=0.72, text='Significant means unlikely to be chance, not large'),
   dict(at=0.94, text='The incentive, stated plainly, explains the whole sheet')]),

"fig_b21_u03_p07_v10": dict(type='V10', kind='elision', height=660,
 title='The modal keeps its stress and loses its have',
 sub='Written in full above, said at half the length below. The shaded letters are not heard.',
 alt='Five perfect modals written out and then transcribed as they are said, with have reduced '
     'to a schwa and a v in each one.',
 pairs=[
  dict(written='must have been', spoken='ˈmʌstəv bɪn', dropped='',
       note='have survives as two sounds'),
  dict(written='might have read it', spoken='ˈmaɪtəv red ɪt', dropped='',
       note='same reduction, lower certainty'),
  dict(written='should have asked', spoken='ˈʃʊdəv ɑːskt', dropped='',
       note='never "should of" in writing'),
  dict(written='could hardly have been', spoken='kəd ˈhɑːdli əv bɪn', dropped='',
       note='could is weak, hardly carries the stress'),
  dict(written='it MIGHT be real', spoken='ɪt ˈmaɪt bi ˈrɪəl', dropped='',
       note='stressed: and somebody just said it is')]),

"fig_b21_u03_p09_v05": dict(type='V5', height=940,
 title='Four claims a learner makes about themselves',
 sub='Each one is a hypothesis stated as a result, and a result is not tested again.',
 alt='A study sheet setting out four claims learners make about their own English, the evidence '
     'behind each, the setting the evidence supports and what the strong form licenses.',
 rows=[dict(t='org', text='STUDY FILE  -  THE CERTAINTY IN YOUR OWN ACCOUNT'),
   dict(t='para', text='Learners place claims about themselves at the top of the scale and almost '
     'never in the middle. The top of the scale ends the inquiry.'),
   dict(t='rule'),
   dict(t='grid', cols=['THE CLAIM', 'THE EVIDENCE', 'THE HONEST SETTING'],
     data=[['I CANNOT HEAR IT', '4 TRIES, WEEK 1', 'I COULD NOT IN OCTOBER'],
           ['I WILL NEVER SAY IT', '0 RECORDINGS', 'I HAVE YET TO SAY IT'],
           ['MY GRAMMAR IS TERRIBLE', '1 TEST, 2019', 'IT WAS WEAK IN 2019'],
           ['WE WERE NEVER TAUGHT', '1 SCHOOL', 'MY SCHOOL DID NOT'],
           ['I AM BAD AT LISTENING', 'NO BASELINE', 'I HAVE NOT MEASURED IT']]),
   dict(t='rule'),
   dict(t='head', text='WHAT THE STRONG FORM LICENSES'),
   dict(t='kv', k='cannot', v='never trying it again', mono=False),
   dict(t='kv', k='will never', v='a decision disguised as a fact', mono=False),
   dict(t='kv', k='always', v='a sample of one, extended for life', mono=False),
   dict(t='kv', k='could not, in October', v='a test, with a date on it', mono=False),
   dict(t='rule'),
   dict(t='para', text='Lower the setting and the claim becomes checkable. A checkable claim '
     'about yourself is the only kind that can ever be disproved in your favour.')],
 callouts=[dict(at=0.10, text='The sentence that stops the testing'),
   dict(at=0.40, text='Five claims, and not one baseline among them'),
   dict(at=0.70, text='The strong form is doing work the evidence cannot'),
   dict(at=0.94, text='A dated claim can be beaten. An absolute one cannot')]),

"fig_b21_u03_p10_v12": dict(type='V12',
 title='Four in ten thousand, and what became of it',
 sub='The whole study on one scale: cases per ten thousand people per year.',
 alt='An infographic showing the baseline incidence, the incidence among night workers, the '
     'confidence interval the study cannot exclude, and what the press release printed.',
 span=['0', '14 per 10,000'], ticks=8,
 tick_labels=['0', '2', '4', '6', '8', '10', '12', '14'],
 bands=[dict(name='The baseline', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.286}, label='no night shifts - 4 in 10,000',
        colour='#2E6F5E')]),
  dict(name='With exposure', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.571}, label='four or more nights a week - 8 in 10,000',
        colour='#A8372E')]),
  dict(name='What cannot be excluded', type='bars', items=[
   dict(**{'from': 0.343, 'to': 0.943}, label='the interval: 4.8 to 13.2', colour='#9AA7AE')]),
  dict(name='What the release printed', type='events', items=[
   dict(at=0.286, label='the base rate: nowhere', colour='#9AA7AE'),
   dict(at=0.571, label='"doubles": three times', colour='#D9A441')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.14, label='the whole difference is four people in ten thousand'),
   dict(at=0.58, label='the interval is consistent with almost no effect at all')])]),

"fig_b21_u03_p11_v06": dict(type='V6', kind='bar', height=820,
 title='What two hundred readers understood, by headline style',
 sub='One year of the Herald, a hundred and forty risk stories, four ways of writing the number.',
 alt='A bar chart comparing four headline styles on the share of readers who estimated the '
     'absolute risk correctly and the share who opened the story.',
 labels=['ratio only', 'ratio + base rate', 'absolute only', 'both, one sentence'],
 ymin=0, ymax=100, fmt='{:,.0f}',
 series=[dict(name='got the size right (%)',
              values=[11, 58, 71, 64], colour='#2E6F5E'),
   dict(name='opened the story (%)', values=[62, 57, 24, 55], colour='#C86B2B')],
 note='The ratio alone is read correctly by about one reader in nine. Adding the base rate costs '
      'five points of readership and gains forty-seven points of comprehension.',
 warning='The absolute figure alone is understood best and read least, which is why a rule that '
         'requires both in one sentence is the only version a newsroom will actually keep.'),
}
