"""B2.1 Unit 4 - It Was Going to Open in 2019 - ten figures, as data."""
FIGURES = {
"fig_b21_u04_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The business desk, and the wall behind it',
 sub='Twelve things to find. Three are dated and two of those three disagree.',
 alt='A newspaper business desk with a framed 2014 announcement, a wall of forecasts, a budget '
     'board crossed out four times and a model of a station that was never built.',
 sky='#D7DBDC', ground='#8A8378', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B3AEA1', cutaway=True,
     floor_labels=['the 2014 announcement, framed', 'the forecast wall',
                   'the budget board'],
     label='the business desk'),
   dict(x=560, w=480, storeys=3, colour='#BBB7AB', cutaway=True,
     floor_labels=['the prediction log', 'a calendar with 2019 circled',
                   'the station model'],
     label='the records room'),
   dict(x=1120, w=460, storeys=3, colour='#B0ACA0', cutaway=True,
     floor_labels=['the 2014 front page', 'the contractor\'s letter',
                   'the groundbreaking'],
     label='the library')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='2031'),
   dict(kind='table', x=780, y=700, s=1.8), dict(kind='chair', x=720, y=700, s=1.1),
   dict(kind='box', x=240, y=700, s=1.0), dict(kind='crate', x=1300, y=700, s=1.0),
   dict(kind='hoarding', x=1000, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=840, y=700, h=92, skin=5, cloth=3, hair='short', arm='point'),
   dict(x=380, y=700, h=86, skin=1, cloth=0, hair='grey', arm='folded'),
   dict(x=1200, y=700, h=88, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=1460, y=700, h=88, skin=3, cloth=1, hair='bun', arm='hold'),
   dict(x=620, y=700, h=86, skin=0, cloth=2, hair='cap', arm='down')],
 names=[dict(x=840, t='Laran - forty forecasts, eleven right'),
   dict(x=380, t='Dennis - he set the 2014 front page'),
   dict(x=1200, t='the groundbreaking photograph, 2015'),
   dict(x=1460, t='the hard hat, with no dust on it'),
   dict(x=620, t='the empty display case'),
   dict(x=520, t='the current forecast: 2031'),
   dict(x=1000, t='the graph whose line keeps moving right'),
   dict(x=240, t='the budget board, crossed out four times')],
 markers=[dict(x=840, y=570), dict(x=380, y=574), dict(x=1200, y=574), dict(x=1460, y=574),
   dict(x=620, y=578), dict(x=520, y=630), dict(x=1000, y=644), dict(x=240, y=650),
   dict(x=780, y=652), dict(x=1300, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b21_u04_p01_v02": dict(type='V2', height=820,
 title='One forecast, in section',
 sub='Twelve words, and the layer each one belongs to. Only the top layer is ever quoted.',
 alt='A cutaway of a forecast in four layers, from the assumptions through the modelling and the '
     'range to the single number that reaches the headline.',
 floors=[dict(was='what you assume', now='assumption · scenario · contingency',
     year='', fill='#EDF1EC'),
   dict(was='what you model', now='projection · trajectory · horizon · foresight',
     year='', fill='#E8EEF0'),
   dict(was='what you publish', now='forecast · revision',
     year='', fill='#F3EADA'),
   dict(was='what you count later', now='overrun · shortfall · hindsight',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Change one of these and every layer above it moves'),
   dict(at=0.38, text='A range lives here, and it almost never leaves the building'),
   dict(at=0.62, text='One number, and the range has been dropped on the way up'),
   dict(at=0.88, text='These three words only exist because the layers above were wrong')]),

"fig_b21_u04_p02_v07": dict(type='V7', height=840,
 title='The forecast audit',
 sub='He has five years of the desk\'s own predictions. He set the 2014 front page himself.',
 alt='A business journalist and a long-serving subeditor at a desk with a printed prediction log '
     'between them, each with two speech balloons and a thought balloon.',
 bg='#E5E7E2',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=5, cloth=3, hair='short', arm='point', facing='right',
   label='Laran', role='business desk, and he ran the audit',
   says=['Forty forecasts. Eleven came off.',
         'It was going to open in 2019.'],
   thinks=['We never once printed the number we replaced.']),
  dict(x=1080, h=240, skin=1, cloth=0, hair='grey', arm='folded', facing='left',
   label='Dennis', role='thirty-one years, and he set that page',
   says=['It was to have been the first in forty years.',
         'That was the plan.'],
   thinks=['The model is still in the lobby.'])]),

"fig_b21_u04_p03_v09": dict(type='V9', kind='timeline', height=900,
 title='Standing in 2014, looking forward',
 sub='The same stretch of time, seen from inside the plan and from here.',
 alt='A timeline from 2012 to 2034 showing the 2014 vantage point, the future that was expected '
     'from it, the opening that did not happen, and the current forecast.',
 now=0.636, axis_y=710,
 bands=[dict(**{'from': 0.091, 'to': 0.091}, type='event', lane=1,
     label='the vantage point - October 2014',
     example='It was going to open in 2019.'),
   dict(**{'from': 0.091, 'to': 0.318}, type='future', lane=3,
     label='FUTURE IN THE PAST - what lay ahead then',
     example='It was due to open in the spring of 2019.'),
   dict(**{'from': 0.318, 'to': 0.318}, type='event', lane=5,
     label='spring 2019 - nothing opened',
     example='It would have opened, but for the harbour.'),
   dict(**{'from': 0.091, 'to': 0.636}, type='reach', lane=7,
     label='FROM HERE - the whole plan is past',
     example='It was to have been the first line in forty years.'),
   dict(**{'from': 0.636, 'to': 0.864}, type='future', lane=9,
     label='the current forecast',
     example='On current trends, 2031.')]),

"fig_b21_u04_p04_v04": dict(type='V4', height=740,
 title='The same line, announced twice',
 sub='October 2014 and March this year, on the same front page, ten years apart.',
 alt='Two front-page announcements of the same transit line side by side, one from 2014 and one '
     'from this year, with their dates and costs.',
 differences=6, prompt='Find the six. One of the two pages contains the figure the other one '
                       'replaced. Which, and what has it been renamed?',
 left=dict(label='October 2014', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=210, bh=24, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='opens spring 2019 · $2.4bn · 40 years since the last',
        colour='#2E6F5E')]),
 right=dict(label='March, this year', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=72, w=190, bh=24, colour='#A8372E'),
   dict(kind='label', x=300, y=218,
        text='opens 2031 · $6.1bn · no mention of 2019, 2023 or 2027',
        colour='#A8372E')])),

"fig_b21_u04_p05_v05": dict(type='V5', height=1120,
 title='The 2014 announcement, read from here',
 sub='Every date in it, and whether it still stands.',
 alt='A city transit announcement from 2014 annotated to show its dates, its costs, its one '
     'conditional clause and which of its figures have survived.',
 rows=[dict(t='org', text='CITY OF TORONTO  -  TRANSIT ANNOUNCEMENT  -  14 OCT 2014'),
   dict(t='head', text='EAST END LINE APPROVED'),
   dict(t='para', text='"The new line will open in the spring of 2019 at a cost of $2.4 billion. '
     'It is to be the first new line in forty years. Journey times to the east end will fall by '
     'twenty-two minutes."'),
   dict(t='para', text='"Construction is to begin in March 2015, subject to the completion of the '
     'harbour survey."'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT IT SAID', 'IN 2014', 'TODAY'],
     data=[['OPENING', 'SPRING 2019', '2031'],
           ['COST', '$2.4 BN', '$6.1 BN'],
           ['REVISIONS SINCE', '0', '4'],
           ['TUNNEL LENGTH', '11.3 KM', '11.3 KM'],
           ['JOURNEY TIME SAVED', '22 MIN', 'NOT RESTATED'],
           ['CONSTRUCTION START', 'MARCH 2015', 'JULY 2016'],
           ['CONDITIONAL CLAUSES', '1', '--'],
           ['SIGNATORIES STILL IN POST', '4', '0']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH VERB LOOKS LIKE FROM HERE'),
   dict(t='kv', k='"will open in spring 2019"', v='was going to - and did not', mono=False),
   dict(t='kv', k='"is to be the first"', v='was to have been', mono=False),
   dict(t='kv', k='"is to begin in March"', v='was due to - sixteen months late', mono=False),
   dict(t='kv', k='"subject to the survey"', v='the one clause that saved them', mono=False),
   dict(t='rule'),
   dict(t='para', text='The tunnel is the same length it was going to be. It is the only figure '
     'on this sheet that has not moved.')],
 callouts=[dict(at=0.08, text='A date, a cost, and a promise with no range attached'),
   dict(at=0.20, text='Eleven words of conditional, at the end of the second quote'),
   dict(at=0.46, text='Two rows unchanged out of eight, and one of them is geometry'),
   dict(at=0.74, text='Read from today, every main verb is a future in the past'),
   dict(at=0.95, text='Nobody who signed this is still in post')]),

"fig_b21_u04_p07_v10": dict(type='V10', kind='elision', height=620,
 title='Going to becomes one sound',
 sub='Written in full above, said at half the length below.',
 alt='Four future-in-the-past phrases written out and then transcribed as they are said, with '
     'going to reduced to gonna and would have to woulduv.',
 pairs=[
  dict(written='it was going to open', spoken='ɪt wəz ˈɡənə ˈəʊpən', dropped='',
       note='four words, two stresses'),
  dict(written='they were going to sign', spoken='ðeɪ wə ˈɡənə ˈsaɪn', dropped='',
       note='were is a schwa and an r'),
  dict(written='it would have opened', spoken='ɪt ˈwʊdəv ˈəʊpənd', dropped='',
       note='have survives as two sounds'),
  dict(written='it WAS going to open', spoken='ɪt ˈwɒz ˈɡənə ˈəʊpən', dropped='',
       note='stressed: and somebody just denied it')]),

"fig_b21_u04_p09_v05": dict(type='V5', height=900,
 title='Four study plans and what became of them',
 sub='The plan is almost never the problem. The horizon is.',
 alt='A study sheet setting out four learner study plans, the horizon each one had, the '
     'contingency it did not have, and the day each one stopped.',
 rows=[dict(t='org', text='STUDY FILE  -  THE PLAN THAT FELL THROUGH'),
   dict(t='para', text='A plan with no end date and no fallback is a wish. Every one of these was '
     'kept for between four and eleven days.'),
   dict(t='rule'),
   dict(t='grid', cols=['THE PLAN', 'THE HORIZON', 'IT STOPPED ON'],
     data=[['30 MINUTES EVERY DAY', 'NONE STATED', 'DAY 9'],
           ['A PODCAST EVERY MORNING', 'NONE STATED', 'DAY 4'],
           ['A NOTEBOOK, ALWAYS', 'NONE STATED', 'DAY 11'],
           ['50 WORDS A WEEK', 'NONE STATED', 'WEEK 3'],
           ['TUESDAY AND FRIDAY, 19:00', 'ONE TERM', 'STILL RUNNING']]),
   dict(t='rule'),
   dict(t='head', text='WHAT THE SURVIVOR HAD THAT THE OTHERS DID NOT'),
   dict(t='kv', k='a fixed time', v='not a quantity', mono=False),
   dict(t='kv', k='an end date', v='so it can be renewed, not failed', mono=False),
   dict(t='kv', k='a contingency', v='what happens on the day you miss', mono=False),
   dict(t='kv', k='a worst case', v='written down in advance, in words', mono=False),
   dict(t='rule'),
   dict(t='para', text='Write next month\'s plan and its worst case in the same number of words. '
     'The worst case is the half that will still be true in four weeks.')],
 callouts=[dict(at=0.12, text='A wish with a number on it is still a wish'),
   dict(at=0.44, text='Four plans, four horizons, and not one of them stated'),
   dict(at=0.74, text='A fixed time beats a quantity in nine cases out of ten'),
   dict(at=0.95, text='The worst case is the part that survives contact')]),

"fig_b21_u04_p10_v12": dict(type='V12',
 title='Seventeen years, four forecasts, one tunnel',
 sub='The whole line on one scale, from the announcement to the current opening date.',
 alt='An infographic of a transit project from 2014 to 2031 showing the forecast opening dates, '
     'the construction period, the budget revisions and the coverage.',
 span=['2014', '2031'], ticks=4,
 tick_labels=['2014', '2020', '2026', '2031'],
 bands=[dict(name='Forecast openings', type='events', items=[
   dict(at=0.04, label='spring 2019', colour='#2E6F5E'),
   dict(at=0.35, label='revised: 2023', colour='#C86B2B'),
   dict(at=0.59, label='revised: 2027', colour='#A8372E'),
   dict(at=0.94, label='revised: 2031', colour='#A8372E')]),
  dict(name='What was built', type='bars', items=[
   dict(**{'from': 0.12, 'to': 0.76}, label='tunnelling, 11.3 km - the one figure that held',
        colour='#9AA7AE')]),
  dict(name='The budget', type='events', items=[
   dict(at=0.04, label='$2.4bn', colour='#2E6F5E'),
   dict(at=0.15, label='down to $2.2bn', colour='#9AA7AE'),
   dict(at=0.65, label='$6.1bn - the central estimate', colour='#A8372E')]),
  dict(name='What the paper printed', type='events', items=[
   dict(at=0.30, label='240 pieces, 31 with a forecast date', colour='#D9A441'),
   dict(at=0.80, label='forecasts that named the one they replaced: 0', colour='#A8372E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.10, label='the worst case of 2029 was modelled in 2016 and not published'),
   dict(at=0.62, label='every revision was reported as news, never as a replacement')])]),

"fig_b21_u04_p11_v06": dict(type='V6', kind='line', height=820,
 title='The horizon that walks away',
 sub='Every time the forecast was made, the opening stayed about six years ahead of it.',
 alt='A line chart comparing the year each forecast was made with the opening year it predicted, '
     'showing the gap between them staying roughly constant.',
 labels=['2014', '2016', '2018', '2020', '2022', '2024'],
 ymin=2012, ymax=2034, fmt='{:.0f}',
 series=[dict(name='the opening year forecast', values=[2019, 2021, 2023, 2026, 2028, 2031],
              colour='#A8372E'),
   dict(name='the year the forecast was made', values=[2014, 2016, 2018, 2020, 2022, 2024],
        colour='#1F4E5F')],
 note='The distance between the two lines is the forecast horizon. It has never once closed, '
      'which is the signature of a schedule that is being re-stated rather than re-estimated.',
 warning='Each new date was reported as news. None of the six was reported beside the date it '
         'replaced, so a reader meeting any one of them alone would see a plan on track.'),
}
