"""B2.1 Unit 5 - Clause Seven - ten figures, as data."""
FIGURES = {
"fig_b21_u05_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The negotiating room, nine hours in',
 sub='Twelve things to find. Two of them are the same document and one has been signed.',
 alt='A newspaper negotiating room with a draft contract, a redline in four colours, a side '
     'letter face down, a flip chart in two columns and an untouched plate of sandwiches.',
 sky='#DADCD7', ground='#89827A', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B5B0A3', cutaway=True,
     floor_labels=['the draft contract, clause 7 flagged', 'the redline, four colours',
                   'the side letter'],
     label='the paper\'s side'),
   dict(x=560, w=480, storeys=3, colour='#BDB9AD', cutaway=True,
     floor_labels=['the flip chart, two columns', 'the nine-year claims log',
                   'the sandwiches'],
     label='the table'),
   dict(x=1120, w=460, storeys=3, colour='#B2AEA2', cutaway=True,
     floor_labels=['the counter-proposal', 'the list of 410 names',
                   'the insurance quote'],
     label='the association')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='19:20'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=90, y=700, s=1.0), dict(kind='crate', x=1150, y=700, s=1.0),
   dict(kind='hoarding', x=1030, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=280, y=700, h=92, skin=2, cloth=4, hair='bun', arm='point'),
   dict(x=1230, y=700, h=88, skin=5, cloth=0, hair='short', arm='folded'),
   dict(x=640, y=700, h=86, skin=1, cloth=3, hair='grey', arm='hold'),
   dict(x=1340, y=700, h=88, skin=3, cloth=1, hair='long', arm='hold'),
   dict(x=170, y=700, h=86, skin=4, cloth=2, hair='cap', arm='down')],
 names=[dict(x=280, t='Marta - standards, for the paper'),
   dict(x=1230, t='Yusra - negotiating for 410 people'),
   dict(x=640, t='the jug of water nobody has touched'),
   dict(x=1340, t='the governing-law page, tabbed'),
   dict(x=170, t='the claims log: three in nine years'),
   dict(x=520, t='the clock: twenty past seven'),
   dict(x=1030, t='the flip chart, two columns, one empty'),
   dict(x=90, t='the side letter, face down')],
 markers=[dict(x=280, y=570), dict(x=1230, y=574), dict(x=640, y=574), dict(x=1340, y=574),
   dict(x=170, y=578), dict(x=520, y=630), dict(x=1030, y=644), dict(x=90, y=650),
   dict(x=800, y=652), dict(x=1150, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b21_u05_p01_v02": dict(type='V2', height=820,
 title='One agreement, in section',
 sub='Twelve words, and the layer each one lives on. Only one of them is not in the document.',
 alt='A cutaway of a contract in four layers, from the operative clauses through what each side '
     'gives up and what happens on a breach, to the law outside the document.',
 floors=[dict(was='what the document says', now='clause · term · undertaking · covenant',
     year='', fill='#EDF1EC'),
   dict(was='what each side gives up', now='waiver · indemnity · concession',
     year='', fill='#E8EEF0'),
   dict(was='what happens when it fails', now='breach · remedy · arbitration · settlement',
     year='', fill='#F3EADA'),
   dict(was='what sits outside it', now='precedent',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='The only layer either side will read twice'),
   dict(at=0.38, text='Each of these three costs somebody something, today'),
   dict(at=0.62, text='Written for a day nobody expects to arrive'),
   dict(at=0.88, text='Not in the document, and the reason the rest is worded as it is')]),

"fig_b21_u05_p02_v07": dict(type='V7', height=840,
 title='Clause seven, at twenty past seven',
 sub='Eight of the nine pages are agreed. She has just turned the envelope over.',
 alt='A standards editor and a freelancers\' negotiator across a table with a draft contract and '
     'an envelope between them, each with two speech balloons and a thought balloon.',
 bg='#E5E7E2',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=2, cloth=4, hair='bun', arm='point', facing='right',
   label='Marta', role='standards, and she drafted clause 7',
   says=['We will cap it, provided the piece was disclosed.',
         'Failing agreement tonight, the old contract rolls over.'],
   thinks=['Three claims in nine years, none of them freelance.']),
  dict(x=1080, h=240, skin=5, cloth=0, hair='short', arm='folded', facing='left',
   label='Yusra', role='for the association, and for 410 people',
   says=['Only if it is capped at the fee.',
         'That is not what we agreed.'],
   thinks=['Eleven safe people and three hundred and ninety-nine quiet ones.'])]),

"fig_b21_u05_p03_v09": dict(type='V9', kind='branch', height=800,
 title='One event, six doors',
 sub='The same claim, and six ways of saying what has to be true before the cap applies.',
 alt='A branching diagram from a single claim event into six conditional connectors, each with '
     'the width of opening it allows and an example sentence.',
 root='a claim is made',
 branches=[dict(label='provided', colour='#2E6F5E',
     example='a requirement, formal: provided the piece was disclosed'),
   dict(label='as long as', colour='#2E6F5E',
     example='the same, spoken: as long as you tell us first'),
   dict(label='only if', colour='#1F4E5F',
     example='nothing else will do: only if the paper was told'),
   dict(label='unless', colour='#C86B2B',
     example='one exception, not a threat: unless you tell us'),
   dict(label='supposing', colour='#D9A441',
     example='an invited hypothesis: supposing nothing was disclosed'),
   dict(label='but for', colour='#A8372E',
     example='a condition on the past: but for the disclosure rule')]),

"fig_b21_u05_p04_v04": dict(type='V4', height=740,
 title='Clause seven, twice',
 sub='The paper\'s draft and the association\'s counter-proposal, on the same page.',
 alt='Two drafts of a contract clause side by side, one with an uncapped indemnity and one with '
     'a cap conditional on disclosure.',
 differences=6, prompt='Find the six. One version can be read once and understood. Which, and '
                       'what did it have to give up to be readable?',
 left=dict(label='the paper\'s draft', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=72, w=220, bh=24, colour='#A8372E'),
   dict(kind='label', x=300, y=218,
        text='no cap · 1 condition · 94 words · 3 subclauses',
        colour='#A8372E')]),
 right=dict(label='the counter-proposal', art=[
   dict(kind='block', x=150, y=140, w=230, bh=24, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=106, w=200, bh=24),
   dict(kind='block', x=150, y=72, w=170, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='capped at the fee · 2 conditions · 41 words · 1 subclause',
        colour='#2E6F5E')])),

"fig_b21_u05_p05_v05": dict(type='V5', height=1120,
 title='Clause seven, every condition marked',
 sub='Two drafts of one clause, and what each conditional connector lets in.',
 alt='A contract clause annotated to show its conditions, the connector each one uses, what it '
     'lets in or keeps out, and the counts for each draft.',
 rows=[dict(t='org', text='CONTRIBUTOR AGREEMENT  -  DRAFT 4  -  CLAUSE 7'),
   dict(t='para', text='"The Contributor shall indemnify the Publisher, without limit, against '
     'any claim arising from the Contribution, notwithstanding any editorial amendment."'),
   dict(t='rule'),
   dict(t='org', text='COUNTER-PROPOSAL  -  THE ASSOCIATION'),
   dict(t='para', text='"Liability is capped at the fee paid, provided the Contribution was '
     'disclosed in full to a named editor before publication. Unless that disclosure was made, '
     'the cap does not apply."'),
   dict(t='rule'),
   dict(t='grid', cols=['FEATURE', 'DRAFT 4', 'COUNTER'],
     data=[['WORDS', '94', '41'],
           ['CONDITIONS', '1', '2'],
           ['CAP', 'NONE', 'THE FEE PAID'],
           ['SUBCLAUSES', '3', '1'],
           ['CONNECTORS USED', 'NOTWITHSTANDING', 'PROVIDED, UNLESS'],
           ['WHO DECIDES', 'A COURT', 'A NAMED EDITOR'],
           ['SIDE LETTERS ISSUED', '11', '0'],
           ['CLAIMS IN 9 YEARS', '3', '3']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH CONNECTOR DOES'),
   dict(t='kv', k='notwithstanding', v='keeps the clause alive after an edit', mono=False),
   dict(t='kv', k='provided', v='a requirement, and it can be met', mono=False),
   dict(t='kv', k='unless', v='one exception, named in advance', mono=False),
   dict(t='kv', k='without limit', v='not a condition - a refusal to set one', mono=False),
   dict(t='rule'),
   dict(t='para', text='The shorter version is longer in one respect only: it names the person '
     'who decides whether the condition has been met.')],
 callouts=[dict(at=0.08, text='Ninety-four words and one condition, which is not a ratio'),
   dict(at=0.26, text='Forty-one words and two conditions a contributor can act on'),
   dict(at=0.52, text='The row that matters is the one naming who decides'),
   dict(at=0.76, text='Without limit is a refusal, dressed as a term'),
   dict(at=0.94, text='Readable and enforceable turned out to be the same change')]),

"fig_b21_u05_p07_v10": dict(type='V10', kind='pitch', height=860,
 title='The voice does not fall until the condition is finished',
 sub='Front the condition and it is the news. Put it last and it is a detail.',
 alt='Four pitch contours over conditional sentences, showing the level or rising tune across a '
     'fronted condition and the fall only on the main clause.',
 contours=[
  dict(text='Provided the piece was disclosed, we will cap it.',
       points=[0.4, 0.6, 0.7, 0.8, 0.6, 0.2, -0.6],
       meaning='fronted - level, then one fall at the end'),
  dict(text='We will cap it, provided the piece was disclosed.',
       points=[0.5, 0.3, -0.2, 0.1, 0.0, -0.2, -0.5],
       meaning='last - two small falls, and it sounds routine'),
  dict(text='Unless you tell us first, the cap does not apply.',
       points=[0.3, 0.5, 0.8, 1.0, 0.5, 0.0, -0.7],
       meaning='the exception rises, the consequence falls'),
  dict(text='But for the disclosure rule, there would be no cap.',
       points=[0.2, 0.4, 0.6, 0.7, 0.4, -0.1, -0.8],
       meaning='a condition on the past - and a long fall')]),

"fig_b21_u05_p09_v05": dict(type='V5', height=940,
 title='Four conditions a learner sets, and who decides them',
 sub='A condition only works if somebody other than you can tell whether it has been met.',
 alt='A study sheet setting out four conditions learners place on their own study, who decides '
     'whether each is met, and an enforceable version of each.',
 rows=[dict(t='org', text='STUDY FILE  -  THE CONDITIONS YOU SET ON YOURSELF'),
   dict(t='para', text='Each of these looks like a condition. Each is in fact a permanent '
     'exemption, because the person who decides is the person who benefits.'),
   dict(t='rule'),
   dict(t='grid', cols=['THE CONDITION', 'WHO DECIDES', 'ENFORCEABLE VERSION'],
     data=[['WHEN I HAVE TIME', 'ME', 'TUESDAY AND FRIDAY, 19:00'],
           ['AS LONG AS WORK CALMS', 'ME', 'UNLESS I AM ABROAD'],
           ['UNLESS SOMETHING COMES UP', 'ME', 'TWICE A TERM, NO MORE'],
           ['IF I FEEL READY', 'ME', 'AFTER FOUR RECORDINGS'],
           ['PROVIDED I FIND A PARTNER', 'ME', 'BY 30 NOVEMBER, OR ALONE']]),
   dict(t='rule'),
   dict(t='head', text='WHAT MAKES A CONDITION HOLD'),
   dict(t='kv', k='a named time', v='not a quantity and not a mood', mono=False),
   dict(t='kv', k='an exception, in advance', v='stated with unless, and counted', mono=False),
   dict(t='kv', k='somebody else can see it', v='the whole test, in one line', mono=False),
   dict(t='kv', k='a date it expires', v='so it is renewed, not abandoned', mono=False),
   dict(t='rule'),
   dict(t='para', text='Write one commitment with its exception, give it to somebody, and watch '
     'what they say the first time you use the exception.')],
 callouts=[dict(at=0.12, text='Five conditions, one decider, and it is always the same person'),
   dict(at=0.46, text='The right-hand column is the only one anybody could check'),
   dict(at=0.76, text='An exception named in advance is the part that keeps the rest'),
   dict(at=0.95, text='Hand it to somebody and the condition acquires a witness')]),

"fig_b21_u05_p10_v12": dict(type='V12',
 title='Four hundred and ten contributors, one clause',
 sub='Who signs it, who was offered more, and where the risk actually turned out to be.',
 alt='An infographic of a contributor contract showing who signs the clause, who was offered a '
     'side letter, where the claims actually arose and what the clause costs.',
 span=['0', '410 contributors'], ticks=4,
 tick_labels=['0', '137', '273', '410'],
 bands=[dict(name='Who signs clause 7', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='every contributor - 410', colour='#9AA7AE')]),
  dict(name='Who was offered a cap', type='events', items=[
   dict(at=0.12, label='a side letter, in private: 11 of 410', colour='#D9A441')]),
  dict(name='Claims in nine years', type='events', items=[
   dict(at=0.18, label='three, all from staff work', colour='#A8372E'),
   dict(at=0.62, label='from a freelance piece: none', colour='#2E6F5E')]),
  dict(name='What it costs', type='events', items=[
   dict(at=0.22, label='insurance: $1,900 a year', colour='#C86B2B'),
   dict(at=0.70, label='median freelance income: $4,300', colour='#1F4E5F')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='eleven people were made safe and the other 399 were not told'),
   dict(at=0.58, label='the clause sits where the risk is not, and costs 44% of a year\'s fees')])]),

"fig_b21_u05_p11_v06": dict(type='V6', kind='bar', height=820,
 title='What each version of clause seven actually produced',
 sub='A survey of 410 contributors, and the disclosure log for the year that followed.',
 alt='A bar chart comparing four versions of an indemnity clause on the share of contributors '
     'willing to file a difficult story and the share of risks flagged before publication.',
 labels=['uncapped', 'capped at the fee', 'deleted', 'side letters only'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='would file the hard story (%)', values=[18, 71, 83, 64],
              colour='#2E6F5E'),
   dict(name='risk flagged before publication (%)', values=[22, 68, 41, 59],
        colour='#C86B2B')],
 note='Deleting the clause produces the most willing contributors and the least disclosure. The '
      'cap is the only version where both numbers rise together.',
 warning='The side-letter column describes eleven people. It is on the chart because the paper '
         'treated it as policy, and no policy that applies to eleven of four hundred and ten can '
         'be measured as though it applied to everybody.'),
}
