"""B2.1 Unit 6 - What the City Did Was Borrow - ten figures, as data."""
FIGURES = {
"fig_b21_u06_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The cadet room, five past ten',
 sub='Twelve things to find. Four of them say the same thing in four different orders.',
 alt='A newspaper training room with four versions of one paragraph pinned up, a whiteboard '
     'carrying one sentence eight times, a readers\' survey and a fare-box diagram.',
 sky='#D8DCDA', ground='#8C857A', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B4AFA3', cutaway=True,
     floor_labels=['the four versions, pinned up', 'the readers\' survey, 600 responses',
                   'the handbook'],
     label='the pinboard'),
   dict(x=560, w=480, storeys=3, colour='#BCB8AC', cutaway=True,
     floor_labels=['the whiteboard: one sentence, eight times',
                   'the style guide, open at FIRST PARAGRAPH', 'the marker'],
     label='the front of the room'),
   dict(x=1120, w=460, storeys=3, colour='#B1ADA1', cutaway=True,
     floor_labels=['the fare-box diagram', 'a story with one line circled',
                   'the papers'],
     label='the back row')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='10:05'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='box', x=115, y=700, s=1.0), dict(kind='crate', x=1160, y=700, s=1.0),
   dict(kind='hoarding', x=1070, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=180, y=700, h=92, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=660, y=700, h=88, skin=3, cloth=2, hair='bun', arm='hold'),
   dict(x=1240, y=700, h=86, skin=4, cloth=4, hair='long', arm='down'),
   dict(x=1330, y=700, h=86, skin=0, cloth=1, hair='cap', arm='down'),
   dict(x=300, y=700, h=86, skin=5, cloth=3, hair='short', arm='folded')],
 names=[dict(x=180, t='Dennis - thirty-one years of taking those words out'),
   dict(x=660, t='Teodora - she has the survey'),
   dict(x=1240, t='a cadet, on version C'),
   dict(x=1330, t='a cadet, on version D'),
   dict(x=300, t='the standfirst box, drawn in marker'),
   dict(x=520, t='the clock: five past ten'),
   dict(x=1070, t='the window, with the line visible'),
   dict(x=115, t='the highlighter that has run out')],
 markers=[dict(x=180, y=570), dict(x=660, y=574), dict(x=1240, y=574), dict(x=1330, y=578),
   dict(x=300, y=574), dict(x=520, y=630), dict(x=1070, y=644), dict(x=115, y=650),
   dict(x=800, y=652), dict(x=1160, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b21_u06_p01_v02": dict(type='V2', height=820,
 title='One explanation, in section',
 sub='Twelve words, and the layer each one belongs to. The reader arrives on the bottom floor.',
 alt='A cutaway of an explanation in four layers, from what the reader already has, through what '
     'the teacher does and what the explanation aims at, to what gets in the way.',
 floors=[dict(was='what the reader brings', now='prerequisite · intuition · misconception',
     year='', fill='#EDF1EC'),
   dict(was='what you do with it', now='explanation · demonstration · paraphrase',
     year='', fill='#E8EEF0'),
   dict(was='what you build it from', now='analogy · scaffolding · abstraction',
     year='', fill='#F3EADA'),
   dict(was='what you aim at, and against', now='clarity · emphasis · ambiguity',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='A misconception is an intuition judged from the other end'),
   dict(at=0.38, text='Three tools, and most teaching uses only the first'),
   dict(at=0.62, text='An abstraction is a tool going up and an obstacle coming down'),
   dict(at=0.88, text='Clarity is about the reader; emphasis is about the sentence')]),

"fig_b21_u06_p02_v07": dict(type='V7', height=840,
 title='The cadet course, ten past ten',
 sub='He has thirty-one years. She has six hundred readers.',
 alt='A subeditor and a trainer at a table with four printed versions of one paragraph between '
     'them, each with two speech balloons and a thought balloon.',
 bg='#E6E7E1',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=1, cloth=0, hair='grey', arm='point', facing='right',
   label='Dennis', role='subeditor, and he cuts those five words',
   says=['What the city did was is five words of nothing.',
         'The city borrowed against the fare box.'],
   thinks=['By the standard I was taught, I was right every time.']),
  dict(x=1080, h=240, skin=3, cloth=2, hair='bun', arm='hold', facing='left',
   label='Teodora', role='she ran the survey, 600 readers',
   says=['Thirty-eight per cent could say what it meant.',
         'What the city did was sell the fare box.'],
   thinks=['The flab is the part they could hold on to.'])]),

"fig_b21_u06_p03_v09": dict(type='V9', kind='scope', height=500,
 title='Two clefts, two positions for the point',
 sub='The frame carries no information. What it carries is a position.',
 alt='One sentence drawn twice as chunks, with brackets marking the focus early in an it-cleft '
     'and at the end in a pseudo-cleft.',
 words=['It was', 'the fare box', 'that they sold', '—', 'What', 'they did', 'was sell',
        'the fare box'],
 focus=[1, 7],
 brackets=[dict(**{'from': 0, 'to': 2}, lane=0, colour='#C86B2B',
     label='IT-CLEFT: the focus arrives second, and everything after that is presupposed'),
   dict(**{'from': 4, 'to': 7}, lane=0, colour='#1F4E5F',
     label='PSEUDO-CLEFT: four words of empty frame, and the focus lands last'),
   dict(**{'from': 1, 'to': 1}, lane=1, colour='#A8372E', label='the news, early'),
   dict(**{'from': 7, 'to': 7}, lane=1, colour='#2E6F5E', label='the news, last')]),

"fig_b21_u06_p04_v04": dict(type='V4', height=740,
 title='The same paragraph, two orders',
 sub='Every fact identical. One of them six hundred readers could repeat back.',
 alt='Two versions of a first paragraph side by side, one in plain order with the point in the '
     'middle and one in a pseudo-cleft with the point at the end.',
 differences=6, prompt='Find the six. One version puts the point nineteen words in. Which, and '
                       'what is in front of it?',
 left=dict(label='as printed', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#9AA7AE'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#9AA7AE'),
   dict(kind='block', x=150, y=72, w=230, bh=24, colour='#9AA7AE'),
   dict(kind='label', x=300, y=218,
        text='point at word 19 · 38% understood it · 41 words',
        colour='#9AA7AE')]),
 right=dict(label='as the cadets rewrote it', art=[
   dict(kind='block', x=150, y=140, w=230, bh=24, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=106, w=190, bh=24),
   dict(kind='block', x=150, y=72, w=150, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='point at word 9 · 74% understood it · 17 words',
        colour='#2E6F5E')])),

"fig_b21_u06_p05_v05": dict(type='V5', height=1160,
 title='One paragraph, four orders',
 sub='The same four facts, and where the point arrives in each.',
 alt='Four versions of a newspaper first paragraph annotated with the position of the main point '
     'in each, the frame used and the proportion of readers who understood it.',
 rows=[dict(t='org', text='CADET EXERCISE  -  PARAGRAPH ONE  -  FOUR VERSIONS'),
   dict(t='para', text='A. "The city has finalised a financing package for the east-end line, '
     'involving a range of instruments including a securitisation of future farebox revenue."'),
   dict(t='para', text='B. "It was the fare box that the city sold, in 2016, to pay for the '
     'east-end line."'),
   dict(t='para', text='C. "What the city did in 2016 was sell the next thirty years of ticket '
     'income."'),
   dict(t='para', text='D. "A fare rise did not pay for the east-end line. What paid for it was '
     'the next thirty years of tickets."'),
   dict(t='rule'),
   dict(t='grid', cols=['VERSION', 'POINT AT WORD', 'UNDERSTOOD'],
     data=[['A  PLAIN, SUBORDINATED', '19', '38%'],
           ['B  IT-CLEFT', '4', '61%'],
           ['C  PSEUDO-CLEFT', '9', '74%'],
           ['D  MISCONCEPTION FIRST', '14', '66%'],
           ['A  WORD COUNT', '41', '--'],
           ['C  WORD COUNT', '17', '--'],
           ['B AND D SAME LENGTH', '22', '--'],
           ['PRINTED IN 2016', 'A', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH FRAME BUYS'),
   dict(t='kv', k='"it was X that"', v='the focus early, the rest agreed', mono=False),
   dict(t='kv', k='"what the city did was"', v='the focus last, where it is kept', mono=False),
   dict(t='kv', k='"a fare rise did not"', v='clears the reader\'s wrong idea first', mono=False),
   dict(t='kv', k='no frame at all', v='the point lands in a subclause', mono=False),
   dict(t='rule'),
   dict(t='para', text='Version A is the best-written sentence on this sheet by every rule the '
     'subeditors were taught, and the only one most readers could not restate.')],
 callouts=[dict(at=0.08, text='Forty-one words, all true, and the verb is a nominalisation'),
   dict(at=0.22, text='Four words in, and the rest of the sentence is now background'),
   dict(at=0.34, text='Five words of frame, and the point at the end where it stays'),
   dict(at=0.62, text='Two rows that say the length was not the variable'),
   dict(at=0.94, text='Best written and least understood, on the same sheet')]),

"fig_b21_u06_p07_v10": dict(type='V10', kind='stress', height=840,
 title='The last stressed word is what the sentence is about',
 sub='The same facts five times. Move the nuclear stress and you have moved the meaning.',
 alt='One sentence drawn five times as beats with a different word carrying the nuclear stress '
     'in each, and the reading that follows from it.',
 items=[
  dict(syllables=['the', 'ci-ty', 'sold', 'the', 'FARE', 'box'], strong=[4],
       note='the fare box is the news'),
  dict(syllables=['the', 'CI-ty', 'sold', 'the', 'fare', 'box'], strong=[1],
       note='and not the province'),
  dict(syllables=['the', 'ci-ty', 'SOLD', 'the', 'fare', 'box'], strong=[2],
       note='it did not borrow against it'),
  dict(syllables=['what', 'they', 'did', 'was', 'SELL', 'it'], strong=[4],
       note='the frame is unstressed, every word'),
  dict(syllables=['it', 'was', 'the', 'FARE', 'box', 'they', 'sold'], strong=[3],
       note='focus early, and the rest agreed')]),

"fig_b21_u06_p09_v05": dict(type='V5', height=940,
 title='Four explanations, and where the point sat',
 sub='Learners put the conclusion first. The listener has nothing to attach it to.',
 alt='A study sheet of four learner explanations showing where the main point sat in each, how '
     'much the listener kept, and a framed version of each.',
 rows=[dict(t='org', text='STUDY FILE  -  EXPLAINING IN A LANGUAGE YOU ARE LEARNING'),
   dict(t='para', text='Stating the conclusion first is insurance against a sentence you may not '
     'be able to finish. It works, and it costs the listener everything.'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT THEY SAID', 'POINT AT', 'LISTENER KEPT'],
     data=[['IT IS ABOUT TAX, SO...', 'WORD 4', '1 OF 3'],
           ['THE PROBLEM IS COST', 'WORD 4', '1 OF 3'],
           ['WHAT HAPPENS IS...', 'WORD 12', '3 OF 3'],
           ['THE THING THAT MATTERS...', 'WORD 14', '3 OF 3'],
           ['I WILL EXPLAIN. SO...', 'WORD 2', '0 OF 3']]),
   dict(t='rule'),
   dict(t='head', text='WHAT A FRAME BUYS A LEARNER'),
   dict(t='kv', k='four words of thinking time', v='before the hard noun arrives', mono=False),
   dict(t='kv', k='a position for the point', v='at the end, where it is kept', mono=False),
   dict(t='kv', k='a listener who is ready', v='they know something is coming', mono=False),
   dict(t='kv', k='two frames, not four', v='four of them sounds like a tic', mono=False),
   dict(t='rule'),
   dict(t='para', text='Explain one thing twice to somebody outside the class, point-first and '
     'point-last, and ask them afterwards which one they can repeat.')],
 callouts=[dict(at=0.12, text='The safe order, and the listener keeps one fact in three'),
   dict(at=0.46, text='The two framed versions are the two that landed'),
   dict(at=0.76, text='The frame is thinking time you are allowed to take out loud'),
   dict(at=0.95, text='Two frames is a style. Four is a tic')]),

"fig_b21_u06_p10_v12": dict(type='V12',
 title='Six hundred readers, four paragraphs',
 sub='How many understood each version, and how far into the story they got.',
 alt='An infographic comparing four versions of a first paragraph on reader comprehension and '
     'how far readers got into the story.',
 span=['0', '600 readers'], ticks=4,
 tick_labels=['0', '200', '400', '600'],
 bands=[dict(name='A - as printed', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.38}, label='stated the point: 228', colour='#9AA7AE')]),
  dict(name='B - it-cleft', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.61}, label='stated the point: 366', colour='#C86B2B')]),
  dict(name='C - pseudo-cleft', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.74}, label='444 - the version the subs cut', colour='#2E6F5E')]),
  dict(name='Where readers stopped', type='events', items=[
   dict(at=0.44, label='A: read past paragraph three', colour='#9AA7AE'),
   dict(at=0.78, label='C: read past paragraph three', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.10, label='the best-written version is the one fewest readers could restate'),
   dict(at=0.56, label='the frame costs five words and buys two hundred and sixteen readers')])]),

"fig_b21_u06_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four first paragraphs, six hundred readers',
 sub='The same four facts, four orders, and what readers did with each.',
 alt='A bar chart comparing four versions of a first paragraph on the share of readers who '
     'stated the point correctly and the share who read past paragraph three.',
 labels=['plain order', 'it-cleft', 'what-cleft', 'point in 7 words'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='stated the point (%)', values=[38, 61, 74, 66], colour='#2E6F5E'),
   dict(name='read past para 3 (%)', values=[44, 51, 63, 58], colour='#C86B2B')],
 note='The what-cleft wins on both measures, and it is the version every style guide in the '
      'building tells a subeditor to delete.',
 warning='The seven-word rule performs well here and badly in practice: it was tested on one '
         'story, where the point happened to fit. A rule that must fit every story will produce '
         'seven bad words at the top of the hardest ones.'),
}
