"""B2.1 Unit 7 - A Reduction in Exceedances - ten figures, as data."""
FIGURES = {
"fig_b21_u07_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The data desk, quarter past three',
 sub='Twelve things to find. Two of them are the same chart and one of them starts at zero.',
 alt='A newspaper data desk with the city\'s air-quality chart pinned up beside the same chart '
     'redrawn from zero, a monitor-site map with two pins and a printout of the raw figures.',
 sky='#D6DAD9', ground='#8B8479', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B3AEA2', cutaway=True,
     floor_labels=['the city\'s chart, pinned up', 'the same chart, redrawn from zero',
                   'the ruler'],
     label='the wall'),
   dict(x=560, w=480, storeys=3, colour='#BBB7AB', cutaway=True,
     floor_labels=['the monitor-site map, two pins', 'the 2023 report, open at page 40',
                   'the raw figures'],
     label='the desk'),
   dict(x=1120, w=460, storeys=3, colour='#B0ACA0', cutaway=True,
     floor_labels=['the university\'s data, emailed', 'the reporting-period memo',
                   'the certificate'],
     label='the file')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='15:15'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='box', x=115, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=200, y=700, h=92, skin=4, cloth=2, hair='long', arm='point'),
   dict(x=300, y=700, h=86, skin=5, cloth=3, hair='short', arm='folded'),
   dict(x=660, y=700, h=88, skin=1, cloth=0, hair='grey', arm='hold'),
   dict(x=1250, y=700, h=86, skin=2, cloth=4, hair='bun', arm='hold'),
   dict(x=1350, y=700, h=86, skin=0, cloth=1, hair='cap', arm='down')],
 names=[dict(x=200, t='Ines - she has both series'),
   dict(x=300, t='the note that says COMPARED WITH WHAT?'),
   dict(x=660, t='Laran - he asked for the raw figures'),
   dict(x=1250, t='the calibration certificate, 2019'),
   dict(x=1350, t='the window, with the ward beyond it'),
   dict(x=520, t='the clock: quarter past three'),
   dict(x=1075, t='the second pin, 1.4 km away'),
   dict(x=115, t='the ruler lying across the y axis')],
 markers=[dict(x=200, y=570), dict(x=300, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=115, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b21_u07_p01_v02": dict(type='V2', height=820,
 title='One chart, in section',
 sub='Twelve words, and the layer each one lives on. Only the top layer leaves the building.',
 alt='A cutaway of a chart in four layers, from the instrument and its calibration through the '
     'processing and the statement of uncertainty to the single figure that is published.',
 floors=[dict(was='the instrument', now='measurement · calibration · series',
     year='', fill='#EDF1EC'),
   dict(was='what you do to it', now='aggregation · granularity · resolution',
     year='', fill='#E8EEF0'),
   dict(was='how sure you are', now='variance · uncertainty · anomaly',
     year='', fill='#F3EADA'),
   dict(was='what you compare it with', now='benchmark · metric · proxy',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Move the instrument and every layer above is about a new place'),
   dict(at=0.38, text='Each step here loses detail on purpose, and the purpose is rarely stated'),
   dict(at=0.62, text='The layer that almost never reaches a chart'),
   dict(at=0.88, text='A proxy is a number standing in for one nobody could get')]),

"fig_b21_u07_p02_v07": dict(type='V7', height=840,
 title='Two monitors, one point four kilometres apart',
 sub='She has the city\'s chart. He has the university\'s series and a map.',
 alt='A data journalist and a business journalist at a desk with a chart and a site map between '
     'them, each with two speech balloons and a thought balloon.',
 bg='#E5E8E3',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=4, cloth=2, hair='long', arm='point', facing='right',
   label='Ines', role='data desk, and she asked for the raw figures',
   says=['A reduction of forty per cent has been achieved.',
         'Compared with what?'],
   thinks=['The axis starts at eighteen.']),
  dict(x=1080, h=240, skin=1, cloth=0, hair='grey', arm='hold', facing='left',
   label='Laran', role='he found the footnote on page forty',
   says=['They moved the monitor in 2021.',
         'Forty-one days then, thirty-nine now.'],
   thinks=['One year in that series is nine months long.'])]),

"fig_b21_u07_p03_v09": dict(type='V9', kind='mirror', height=680,
 title='Where the agent goes when the verb becomes a noun',
 sub='The same event, twice. Nothing is ungrammatical and three things have gone.',
 alt='Two sentence diagrams of the same event, the first with an agent and a verb, the second '
     'with the verb turned into a noun and the agent absent.',
 labels=['WITH THE VERB', 'WITH THE NOUN'],
 between='who, when and where have all gone, and no rule has been broken',
 active=dict(parts=[dict(w=18, role='agent', text='The city'),
   dict(w=16, role='action', text='moved'),
   dict(w=26, role='affected', text='the monitor'),
   dict(w=18, role='hidden', text='in 2021')]),
 passive=dict(parts=[dict(w=14, role='hidden', text='The'),
   dict(w=30, role='action', text='relocation'),
   dict(w=34, role='affected', text='of the monitor'),
   dict(w=22, role='hidden', text='took place')])),

"fig_b21_u07_p04_v04": dict(type='V4', height=740,
 title='The same eight years, drawn twice',
 sub='One chart is the city\'s. One starts at zero and keeps both monitors on it.',
 alt='Two charts of the same air-quality data side by side, one on a truncated axis with a '
     'single series and one from zero with both monitors shown.',
 differences=6, prompt='Find the six. One chart contains a change of place and the other does '
                       'not. Which, and how is it shown?',
 left=dict(label='as the city published it', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=190, bh=24, colour='#A8372E'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='axis starts at 18 · one series · baseline 2018 · no footnote',
        colour='#A8372E')]),
 right=dict(label='redrawn from the data', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=72, w=240, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='axis from 0 · two series · baseline 2016 · the move marked',
        colour='#2E6F5E')])),

"fig_b21_u07_p05_v05": dict(type='V5', height=1140,
 title='The chart page, every noun unpacked',
 sub='Four decisions, each defensible, and no document in which all four appear.',
 alt='A city air-quality report page annotated to show its nominalisations, the agent hidden in '
     'each, and the four changes to the series that the chart does not display.',
 rows=[dict(t='org', text='CITY OF TORONTO  -  AIR QUALITY REPORT 2023  -  P.12'),
   dict(t='head', text='WARD 7: A 40% REDUCTION IN EXCEEDANCES'),
   dict(t='para', text='"A reduction in exceedance days of forty per cent has been achieved since '
     'the baseline year. The implementation of revised monitoring arrangements is reflected in '
     'the series. The assessment is subject to revision."'),
   dict(t='para', text='Footnote, p.40: "Monitoring location revised 2021. Series not directly '
     'comparable."'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT CHANGED', 'WHEN', 'WHERE IT IS SAID'],
     data=[['THE MONITOR MOVED 1.4 KM', '2021', 'FOOTNOTE, P.40'],
           ['REPORTING PERIOD', '2021-22', 'NOWHERE'],
           ['ONE YEAR IS 9 MONTHS', '2021-22', 'NOWHERE'],
           ['BASELINE 2016 TO 2018', '2023', 'NOWHERE'],
           ['Y AXIS STARTS AT', '18', 'ON THE CHART'],
           ['UNIVERSITY SITE 2016', '41 DAYS', 'NOT IN THE REPORT'],
           ['UNIVERSITY SITE 2023', '39 DAYS', 'NOT IN THE REPORT'],
           ['DOCUMENTS LISTING ALL FOUR', '0', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHO IS THE AGENT OF EACH NOUN'),
   dict(t='kv', k='"a reduction ... achieved"', v='nobody named, no place, no date', mono=False),
   dict(t='kv', k='"the implementation of"', v='the city, in 2021', mono=False),
   dict(t='kv', k='"monitoring location revised"', v='the city moved it to a park', mono=False),
   dict(t='kv', k='"subject to revision"', v='a warning, and the only honest phrase here',
        mono=False),
   dict(t='rule'),
   dict(t='para', text='Every decision on this page has been defended in public, one at a time. '
     'The absence is not a decision anybody made, which is what makes it hard to answer.')],
 callouts=[dict(at=0.08, text='A ratio in the heading and no baseline beside it'),
   dict(at=0.20, text='Three abstract nouns and not one person in the paragraph'),
   dict(at=0.30, text='Eleven words on page forty, carrying the whole story'),
   dict(at=0.58, text='Three rows that say NOWHERE, and they are the three that matter'),
   dict(at=0.94, text='Each one defensible; the set of four never defended at all')]),

"fig_b21_u07_p07_v10": dict(type='V10', kind='stress', height=840,
 title='The beat moves one place to the right',
 sub='Turn the verb into a noun and the stress almost always lands before -tion.',
 alt='Five verb-and-noun pairs drawn as beats, with the stressed syllable marked in each and the '
     'stress moving when the noun is formed.',
 items=[
  dict(syllables=['CA', 'li', 'brate'], strong=[0], note='the verb'),
  dict(syllables=['ca', 'li', 'BRA', 'tion'], strong=[2], note='the noun - before -tion'),
  dict(syllables=['im', 'PLE', 'ment'], strong=[1], note='the verb'),
  dict(syllables=['im', 'ple', 'men', 'TA', 'tion'], strong=[3], note='the noun - same rule'),
  dict(syllables=['a', 're', 'DUC', 'tion', 'in', 'WHAT'], strong=[2, 5],
       note='move the last beat and the report becomes an argument')]),

"fig_b21_u07_p09_v05": dict(type='V5', height=940,
 title='Five nouns learners hide behind',
 sub='Each one is an event with the person, the date and the number removed.',
 alt='A study sheet of five abstract nouns learners use about their own progress, the agent and '
     'date missing from each, and a measurable version.',
 rows=[dict(t='org', text='STUDY FILE  -  THE NOUNS YOU HIDE BEHIND'),
   dict(t='para', text='An abstract noun about yourself cannot be acted on, because there is '
     'nobody in it and no date on it. Put the verb back and a plan appears.'),
   dict(t='rule'),
   dict(t='grid', cols=['THE NOUN', 'WHAT IS MISSING', 'THE VERB VERSION'],
     data=[['MY PROGRESS IS SLOW', 'SINCE WHEN', 'I READ 4 PAGES IN MAY, 11 NOW'],
           ['I NEED IMPROVEMENT', 'IN WHAT, BY HOW MUCH', 'I SPOKE 3 MIN, NOW 8'],
           ['THERE IS NO DEVELOPMENT', 'WHO, WHEN', 'I HAVE NOT RECORDED SINCE JUNE'],
           ['MY PRONUNCIATION IS BAD', 'COMPARED WITH WHAT', '2 OF 8 SOUNDS, TESTED'],
           ['A LACK OF CONFIDENCE', 'DOING WHAT, WITH WHOM', 'I ASKED 1 QUESTION IN 6 WEEKS']]),
   dict(t='rule'),
   dict(t='head', text='THE THREE THINGS A NOUN REMOVES'),
   dict(t='kv', k='the person', v='so nobody is responsible for it', mono=False),
   dict(t='kv', k='the date', v='so it cannot have got better', mono=False),
   dict(t='kv', k='the number', v='so it cannot be compared', mono=False),
   dict(t='kv', k='what is left', v='a feeling, reported as a finding', mono=False),
   dict(t='rule'),
   dict(t='para', text='Take one noun you use about yourself, turn it into a measurement with a '
     'date, and bring the first point. One point is not a series.')],
 callouts=[dict(at=0.12, text='Five sentences, five events, and not one person in any of them'),
   dict(at=0.44, text='The right-hand column is the only one that can change'),
   dict(at=0.74, text='A date is what lets you be wrong in your own favour'),
   dict(at=0.95, text='One point is a claim. Two points are evidence')]),

"fig_b21_u07_p10_v12": dict(type='V12',
 title='Eight years, two monitors, four changes',
 sub='Exceedance days in Ward 7, and everything that changed about the measuring.',
 alt='An infographic of eight years of air-quality monitoring showing both monitors, the '
     'relocation, the shortened reporting year and the moved baseline.',
 span=['2016', '2023'], ticks=4,
 tick_labels=['2016', '2018', '2021', '2023'],
 bands=[dict(name='The city\'s monitor', type='events', items=[
   dict(at=0.04, label='41 days', colour='#A8372E'),
   dict(at=0.72, label='moved 1.4 km, to a park', colour='#D9A441'),
   dict(at=0.96, label='22 days', colour='#2E6F5E')]),
  dict(name='The university monitor', type='events', items=[
   dict(at=0.04, label='41 days', colour='#9AA7AE'),
   dict(at=0.96, label='39 days - same junction throughout', colour='#9AA7AE')]),
  dict(name='The reporting year', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.70}, label='calendar year', colour='#1F4E5F'),
   dict(**{'from': 0.72, 'to': 1.0}, label='April to March', colour='#C86B2B')]),
  dict(name='The baseline used', type='events', items=[
   dict(at=0.14, label='2016, in 2022', colour='#9AA7AE'),
   dict(at=0.38, label='2018, in 2023', colour='#A8372E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.10, label='the two worst years left the comparison without leaving the data'),
   dict(at=0.60, label='one year in this series is nine months long')])]),

"fig_b21_u07_p11_v06": dict(type='V6', kind='line', height=820,
 title='Two instruments, one ward',
 sub='Exceedance days a year, from zero, with both series on the same axis.',
 alt='A line chart of exceedance days from 2016 to 2023 comparing the city monitor, which moved '
     'in 2021, with a university monitor left at the original junction.',
 labels=['2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'],
 ymin=0, ymax=50, fmt='{:.0f}',
 series=[dict(name='city monitor, moved 2021', values=[41, 40, 38, 38, 36, 24, 23, 22],
              colour='#A8372E'),
   dict(name='university, same site', values=[41, 40, 39, 38, 37, 38, 39, 39],
        colour='#1F4E5F')],
 note='The two series are identical until 2021 and then diverge by sixteen days in one year. '
      'Nothing in the air changed that fast; the instrument changed address.',
 warning='Drawn from zero, with both series, the forty per cent reduction is visible as a step in '
         'one line and no step at all in the other. The city\'s chart carries neither the second '
         'series nor the step, because the step is not in its data.'),
}
