"""B2.1 Unit 8 - Seventy-Three Words - ten figures, as data."""
FIGURES = {
"fig_b21_u08_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The stone, two minutes past six',
 sub='Twelve things to find. Two of them are the same story and one is eight hundred words shorter.',
 alt='A newspaper subeditors\' desk at edition time with the filed copy, the page-one proof, a '
     'spike holding four stories and a printout with one paragraph ringed.',
 sky='#D7DAD6', ground='#8A8378', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B4AFA2', cutaway=True,
     floor_labels=['the filed copy, 1,400 words', 'the page-one proof, 600',
                   'the spike'],
     label='the back bench'),
   dict(x=560, w=480, storeys=3, colour='#BCB8AC', cutaway=True,
     floor_labels=['the word-count box, on screen', 'the standfirst, written twice',
                   'the cuts file'],
     label='the subs\' desk'),
   dict(x=1120, w=460, storeys=3, colour='#B1ADA1', cutaway=True,
     floor_labels=['the caption, longer than its picture', 'the kicker, pencilled in',
                   'the stone'],
     label='the make-up')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='18:02'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=115, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=200, y=700, h=92, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=300, y=700, h=88, skin=4, cloth=2, hair='long', arm='folded'),
   dict(x=660, y=700, h=86, skin=5, cloth=3, hair='short', arm='hold'),
   dict(x=1250, y=700, h=86, skin=2, cloth=4, hair='bun', arm='hold'),
   dict(x=1350, y=700, h=86, skin=0, cloth=1, hair='cap', arm='down')],
 names=[dict(x=200, t='Dennis - he has ringed the paragraph'),
   dict(x=300, t='the reporter - she was at both meetings'),
   dict(x=660, t='the printout, one paragraph ringed'),
   dict(x=1250, t='the mug that says CONCISION'),
   dict(x=1350, t='the page, made up and waiting'),
   dict(x=520, t='the edition clock: two minutes past six'),
   dict(x=1075, t='the hole on page one: 600 words'),
   dict(x=115, t='the spike, with four stories on it')],
 markers=[dict(x=200, y=570), dict(x=300, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=115, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b21_u08_p01_v02": dict(type='V2', height=820,
 title='One story, in section',
 sub='Twelve words, and the layer each one lives on. The reader sees the top two.',
 alt='A cutaway of a newspaper story in four layers, from the draft and the proof through what '
     'you do to it and what you judge it by, to the furniture around it.',
 floors=[dict(was='the text, at a stage', now='draft · proof · abstract',
     year='', fill='#EDF1EC'),
   dict(was='what you do to it', now='edit · cut · trim',
     year='', fill='#E8EEF0'),
   dict(was='what you judge it by', now='redundancy · verbosity · concision',
     year='', fill='#F3EADA'),
   dict(was='what sits around it', now='caption · standfirst · kicker',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Three states of the same words, and only one is published'),
   dict(at=0.38, text='One of these three is also a stage, and the stress tells you which'),
   dict(at=0.62, text='Two faults and one virtue, and the virtue has no plural'),
   dict(at=0.88, text='Written last, read first, and usually by somebody else')]),

"fig_b21_u08_p02_v07": dict(type='V7', height=840,
 title='Two minutes past six',
 sub='Eight hundred words have to go and seventy-three of them are ringed.',
 alt='A subeditor and a reporter at a desk with a printout between them, one paragraph ringed in '
     'pencil, each with two speech balloons and a thought balloon.',
 bg='#E6E7E2',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=1, cloth=0, hair='grey', arm='point', facing='right',
   label='Dennis', role='the hole is six hundred and that is a measurement',
   says=['The second quote can go.', 'We are over by forty.'],
   thinks=['If this goes, what is the story for?']),
  dict(x=1080, h=240, skin=4, cloth=2, hair='long', arm='folded', facing='left',
   label='the reporter', role='she sat through both meetings',
   says=['So can the third.', 'Neither do I.'],
   thinks=['Nobody fights for names and dates.'])]),

"fig_b21_u08_p03_v09": dict(type='V9', kind='weight', height=640,
 title='Two words carrying a four-word clause',
 sub='What the speaker said, what the listener rebuilt, and what nobody can rebuild at all.',
 alt='A proportional bar showing the two words actually spoken in a short answer, the clause the '
     'listener recovers from the question, and the information nobody can recover.',
 parts=[dict(w=13, role='said', text='Dev', colour='#1F4E5F'),
   dict(w=13, role='said', text='has', colour='#1F4E5F'),
   dict(w=40, role='not said - rebuilt from the question', text='filed the story',
        colour='#2E6F5E'),
   dict(w=34, role='not said - and not rebuildable', text='when? to whom?', colour='#9AA7AE')],
 note='Ellipsis is only possible where recovery is certain. The green block is free; the grey '
      'block is the bet. A cut that leaves grey has not been brief, it has been unclear.'),

"fig_b21_u08_p04_v04": dict(type='V4', height=740,
 title='The same story, twice',
 sub='Fourteen hundred words as filed, six hundred as printed.',
 alt='Two versions of the same newspaper story side by side, the filed copy and the printed '
     'version, with the paragraphs that went marked.',
 differences=6, prompt='Find the six. One version contains two names and two dates. Which, and '
                       'how long is the paragraph that carries them?',
 left=dict(label='as filed, 16:00', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#1F4E5F'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#1F4E5F'),
   dict(kind='block', x=150, y=72, w=230, bh=24, colour='#1F4E5F'),
   dict(kind='label', x=300, y=218,
        text='1,400 words · 2 names · 2 dates · 4 quotes',
        colour='#1F4E5F')]),
 right=dict(label='as printed, 18:02', art=[
   dict(kind='block', x=150, y=140, w=200, bh=24, colour='#C86B2B'),
   dict(kind='gap', x=150, y=106, w=250, bh=24),
   dict(kind='block', x=150, y=72, w=120, bh=24, colour='#C86B2B'),
   dict(kind='label', x=300, y=218,
        text='600 words · 0 names · 0 dates · 1 quote',
        colour='#C86B2B')])),

"fig_b21_u08_p05_v05": dict(type='V5', height=1120,
 title='What went, in order, and what it cost',
 sub='Eight hundred words, five cuts, and one of them changes what a reader can know.',
 alt='An edited newspaper story annotated to show each cut in the order it was made, its length, '
     'and what the reader can no longer find out.',
 rows=[dict(t='org', text='WARD 7 CONTRACT  -  EDIT LOG  -  16:00 TO 18:02'),
   dict(t='para', text='FILED: "The contract was approved on 14 March by seven votes to two. '
     'Councillors Oyelaran and Whitfield voted for it in committee on 2 February and again in the '
     'chamber on 14 March. The former had declared an interest; the latter had not."'),
   dict(t='para', text='PRINTED: "The contract was approved on 14 March by seven votes to two."'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT WENT', 'WORDS', 'WHAT THE READER LOSES'],
     data=[['REPETITION, FIRST PASS', '300', 'NOTHING'],
           ['THE DUPLICATE QUOTE', '90', 'NOTHING'],
           ['THE JUNCTION DESCRIPTION', '240', 'THE PLACE'],
           ['QUOTES TWO AND THREE', '180', 'TWO VOICES'],
           ['THE NAMES AND DATES', '73', 'WHO DECIDED'],
           ['TOTAL CUT', '883', '--'],
           ['FILED', '1,400', '--'],
           ['PRINTED', '600', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHAT THE SHORT VERSION MAKES THE READER REBUILD'),
   dict(t='kv', k='"approved"', v='by a body, at a meeting, on a date', mono=False),
   dict(t='kv', k='"seven votes to two"', v='nine people, none of them named', mono=False),
   dict(t='kv', k='no quote at all', v='that somebody objected, and lost', mono=False),
   dict(t='kv', k='the missing 73 words', v='nothing - this one cannot be rebuilt', mono=False),
   dict(t='rule'),
   dict(t='para', text='Four of the five cuts leave a hole the reader fills correctly. The fifth '
     'leaves a hole the reader does not know is there.')],
 callouts=[dict(at=0.08, text='Three sentences, two names, two dates, one declared interest'),
   dict(at=0.20, text='One sentence, and every word of it true'),
   dict(at=0.42, text='Five rows, and only the fifth changes what can be known'),
   dict(at=0.78, text='Three recoverable holes and one that is not'),
   dict(at=0.94, text='The difference between brief and unclear, in one line')]),

"fig_b21_u08_p07_v10": dict(type='V10', kind='elision', height=640,
 title='Four words, two beats',
 sub='Written in full above, said at half the length below.',
 alt='Four spoken exchanges written out and then transcribed as they are said, with auxiliaries '
     'and modals reduced to single sounds.',
 pairs=[
  dict(written='I will if you will', spoken='aɪl ɪf juː ˈwɪl', dropped='',
       note='the first will is one sound, the last one carries the stress'),
  dict(written='we are over by forty', spoken='wɪər ˈəʊvə baɪ ˈfɔːti', dropped='',
       note='we are becomes one syllable'),
  dict(written='nobody will miss it', spoken='ˈnəʊbədi l ˈmɪs ɪt', dropped='',
       note='will survives as a single l'),
  dict(written='so can the third', spoken='ˈsəʊ kən ðə ˈθɜːd', dropped='',
       note='so carries a whole clause and the stress')]),

"fig_b21_u08_p09_v05": dict(type='V5', height=940,
 title='Five sentences a learner says in full',
 sub='Accurate, long, and audible as learner speech from across the room.',
 alt='A study sheet of five learner sentences with repeated noun phrases, the substitution a '
     'speaker would use, and the number of words saved.',
 rows=[dict(t='org', text='STUDY FILE  -  THE WORDS YOU ARE AFRAID TO LEAVE OUT'),
   dict(t='para', text='Repeating the whole noun phrase is not an error. It is a register, and it '
     'is the one that marks a speaker as still learning.'),
   dict(t='rule'),
   dict(t='grid', cols=['SAID IN FULL', 'WHAT A SPEAKER SAYS', 'SAVED'],
     data=[['THE BLUE BOOK, NOT THE RED BOOK', 'THE BLUE ONE', '3 WORDS'],
           ['I DO NOT LIKE IT AND SHE DOES NOT', 'NEITHER DOES SHE', '4 WORDS'],
           ['HE ASKED ME TO FILE AND I FILED', 'AND I DID', '2 WORDS'],
           ['SHE CUT IT AND I CUT IT TOO', 'AND SO DID I', '3 WORDS'],
           ['IF IT IS READY, SEND IT', 'IF SO, SEND IT', '2 WORDS']]),
   dict(t='rule'),
   dict(t='head', text='THE FOUR FORMS WORTH LEARNING AS CHUNKS'),
   dict(t='kv', k='one / ones', v='used freely by almost every learner', mono=False),
   dict(t='kv', k='so', v='avoided by almost every learner', mono=False),
   dict(t='kv', k='neither', v='avoided, and the easiest of the four', mono=False),
   dict(t='kv', k='the same', v='learned early and then forgotten', mono=False),
   dict(t='rule'),
   dict(t='para', text='Record ninety seconds, then say the same thing in thirty, and list what '
     'the short version left the listener to rebuild.')],
 callouts=[dict(at=0.12, text='Nothing here is wrong. All of it is long'),
   dict(at=0.44, text='Five sentences, fourteen words saved, same meaning'),
   dict(at=0.76, text='The two you avoid are the two that mark the register'),
   dict(at=0.95, text='Thirty seconds is where you find out what you can imply')]),

"fig_b21_u08_p10_v12": dict(type='V12',
 title='Fourteen hundred words, and where they went',
 sub='The whole edit on one scale, from the filed copy to the hole on page one.',
 alt='An infographic of a newspaper edit showing the filed length, the printed length, each cut '
     'in order and what readers could say afterwards.',
 span=['0', '1,400 words'], ticks=4,
 tick_labels=['0', '467', '933', '1,400'],
 bands=[dict(name='As filed', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='1,400 words, 16:00', colour='#1F4E5F')]),
  dict(name='In the paper', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.43}, label='600 words - the hole on page one',
        colour='#C86B2B')]),
  dict(name='What went, in order', type='events', items=[
   dict(at=0.21, label='repetition: 300', colour='#9AA7AE'),
   dict(at=0.48, label='the junction: 240', colour='#9AA7AE'),
   dict(at=0.70, label='two quotes: 180', colour='#D9A441'),
   dict(at=0.92, label='names and dates: 73', colour='#A8372E')]),
  dict(name='What readers could do', type='events', items=[
   dict(at=0.19, label='named who decided: 19%', colour='#A8372E'),
   dict(at=0.71, label='finished the story: 71%', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='four of the five cuts leave a hole readers fill correctly'),
   dict(at=0.60, label='the smallest cut is the only one nobody can rebuild')])]),

"fig_b21_u08_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four ways of publishing the same story',
 sub='What readers could say afterwards, and how many of them got to the end.',
 alt='A bar chart comparing four publication formats on the share of readers who could name who '
     'decided and the share who finished the story.',
 labels=['print only', 'print + full online', 'full online only', 'cuts marked'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='named who decided (%)', values=[19, 34, 58, 63], colour='#2E6F5E'),
   dict(name='finished the story (%)', values=[71, 68, 41, 59], colour='#C86B2B')],
 note='The full version alone is the best informed and the least read. Marking the cuts turns '
      'fourteen hundred words into something a reader can skim for absences.',
 warning='The print-plus-link column is the one most newsrooms already run, and it moves the '
         'first number by fifteen points because almost nobody follows the link.'),
}
