"""B2.1 Unit 9 - Three Readers, One Style Guide - ten figures, as data."""
FIGURES = {
"fig_b21_u09_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The style guide meeting, half past eleven',
 sub='Twelve things to find. Three of them are the same sentence written for three readers.',
 alt='A newsroom conference area with a 214-page style guide on the table, a newsletter draft on '
     'a screen, an app preview held up and a page proof showing the fold.',
 sky='#D8DBD8', ground='#8B8479', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B4AFA3', cutaway=True,
     floor_labels=['the style guide, 214 pages', 'the page proof, above the fold',
                   'the news list'],
     label='the paper'),
   dict(x=560, w=480, storeys=3, colour='#BCB8AC', cutaway=True,
     floor_labels=['the newsletter draft, on screen', 'the subscriber count: 61,000',
                   'the running order'],
     label='the newsletter'),
   dict(x=1120, w=460, storeys=3, colour='#B1ADA1', cutaway=True,
     floor_labels=['the app preview, held up', 'the wire feed, scrolling',
                   'the spike'],
     label='the app')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='11:30'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=115, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=200, y=700, h=92, skin=1, cloth=0, hair='grey', arm='folded'),
   dict(x=300, y=700, h=88, skin=5, cloth=2, hair='bun', arm='point'),
   dict(x=660, y=700, h=86, skin=3, cloth=3, hair='long', arm='hold'),
   dict(x=1250, y=700, h=86, skin=2, cloth=4, hair='short', arm='hold'),
   dict(x=1350, y=700, h=86, skin=0, cloth=1, hair='cap', arm='down')],
 names=[dict(x=200, t='Dennis - the guide is 214 pages'),
   dict(x=300, t='Priya - chairing, and she has the counts'),
   dict(x=660, t='Nkechi - 61,000 subscribers, three quarters open it'),
   dict(x=1250, t='the app: 340,000 readers last month'),
   dict(x=1350, t='the note that says WHO IS THIS FOR?'),
   dict(x=520, t='the clock: half past eleven'),
   dict(x=1075, t='the conference table, empty since nine'),
   dict(x=115, t='the spike, with two stories on it')],
 markers=[dict(x=200, y=570), dict(x=300, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=115, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b21_u09_p01_v02": dict(type='V2', height=820,
 title='One newsroom, in section',
 sub='Twelve words, and the layer each one lives on. Copy falls from the top.',
 alt='A cutaway of a newsroom in four layers, from where copy arrives through who touches it and '
     'where it ends up, to the documents that govern all of it.',
 floors=[dict(was='where copy comes from', now='wire · desk · conference',
     year='', fill='#EDF1EC'),
   dict(was='who touches it', now='subeditor · copytaster',
     year='', fill='#E8EEF0'),
   dict(was='where it ends up', now='splash · slot · galley · spike',
     year='', fill='#F3EADA'),
   dict(was='what governs all of it', now='style guide · house style · deadline',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Three sources, and two of them are rooms'),
   dict(at=0.38, text='Two jobs, and one of them decides what is never read'),
   dict(at=0.62, text='Four destinations, and one of them is a verb'),
   dict(at=0.88, text='Two of these are written down; the third is the only one obeyed')]),

"fig_b21_u09_p02_v07": dict(type='V7', height=840,
 title='The style guide meeting',
 sub='He has the guide. She has sixty-one thousand people reading on a bus.',
 alt='A subeditor and a newsletter writer across a conference table with the style guide and a '
     'phone between them, each with two speech balloons and a thought balloon.',
 bg='#E5E7E2',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=1, cloth=0, hair='grey', arm='folded', facing='right',
   label='Dennis', role='the guide says: use them sparingly',
   says=['However, the figures do not support that.',
         'So at the start of a sentence is a tic.'],
   thinks=['Nine per thousand words has been enough since 1911.']),
  dict(x=1080, h=240, skin=5, cloth=2, hair='bun', arm='point', facing='left',
   label='Nkechi', role='newsletter, and three quarters of them open it',
   says=['That said, the figures do not support that.',
         'On a phone there is no shape.'],
   thinks=['A reader who loses their place does not come back.'])]),

"fig_b21_u09_p03_v09": dict(type='V9', kind='branch', height=820,
 title='One sentence, six promises',
 sub='Each marker tells the reader what kind of clause is coming. Break the promise and they stop.',
 alt='A branching diagram from one clause into six discourse markers, each with the relationship '
     'it promises and an example of the clause that must follow.',
 root='the figures say X',
 branches=[dict(label='however', colour='#A8372E',
     example='CONTRAST: the next clause pushes back'),
   dict(label='nevertheless', colour='#C86B2B',
     example='CONTRAST IN SPITE OF: and the first clause still stands'),
   dict(label='that said', colour='#D9A441',
     example='CONCESSION: you grant the point, then continue'),
   dict(label='accordingly', colour='#2E6F5E',
     example='RESULT: the next clause follows from this one'),
   dict(label='meanwhile', colour='#1F4E5F',
     example='TIME: something else was happening at once'),
   dict(label='in any case', colour='#9AA7AE',
     example='DISMISSAL: the previous point is set aside, not answered')]),

"fig_b21_u09_p04_v04": dict(type='V4', height=740,
 title='The same paragraph, two readers',
 sub='One is read on paper, where the shape is visible. One is read on a phone.',
 alt='Two versions of the same paragraph side by side, the print version with few markers and '
     'the newsletter version with many.',
 differences=6, prompt='Find the six. One version tells the reader how much is left. Which, and '
                       'what does it use to do it?',
 left=dict(label='print', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#1F4E5F'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#1F4E5F'),
   dict(kind='block', x=150, y=72, w=240, bh=24, colour='#1F4E5F'),
   dict(kind='label', x=300, y=218,
        text='9 markers per 1,000 · the shape is visible · 44% finish',
        colour='#1F4E5F')]),
 right=dict(label='newsletter', art=[
   dict(kind='block', x=150, y=140, w=200, bh=24, colour='#C86B2B'),
   dict(kind='block', x=150, y=106, w=170, bh=24, colour='#C86B2B'),
   dict(kind='block', x=150, y=72, w=140, bh=24, colour='#C86B2B'),
   dict(kind='label', x=300, y=218,
        text='31 markers per 1,000 · no shape at all · 76% finish',
        colour='#C86B2B')])),

"fig_b21_u09_p05_v05": dict(type='V5', height=1140,
 title='One paragraph, three channels',
 sub='The same facts, three densities, and one marker that promises what it does not deliver.',
 alt='Three versions of the same paragraph annotated with their discourse markers, the kind of '
     'each, and the one marker whose promise is broken.',
 rows=[dict(t='org', text='HOUSE STYLE REVIEW  -  ONE PARAGRAPH, THREE CHANNELS'),
   dict(t='para', text='PRINT: "The app has more readers than the paper. It has no style guide. '
     'The guide was last revised in 1998."'),
   dict(t='para', text='NEWSLETTER: "So, here is the thing. The app has more readers than the '
     'paper — however, it has no style guide. And the guide? Last revised in 1998. Which brings me '
     'to the awkward bit."'),
   dict(t='para', text='APP: "The app has more readers than the paper. However, it has no style '
     'guide, last revised in 1998."'),
   dict(t='rule'),
   dict(t='grid', cols=['CHANNEL', 'MARKERS / 1,000', 'READERS'],
     data=[['PRINT', '9', '112,000 COPIES'],
           ['NEWSLETTER', '31', '61,000, 75% OPEN'],
           ['APP', '14', '340,000 A MONTH'],
           ['GUIDE ENTRY, LINES', '4', '--'],
           ['GUIDE PAGES', '214', '--'],
           ['LAST FULL REVISION', '1998', '--'],
           ['ENTRIES FOR APP', '0', '--'],
           ['BROKEN PROMISES FOUND', '1', 'NEWSLETTER']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH MARKER PROMISES HERE'),
   dict(t='kv', k='"so, here is the thing"', v='a signpost: background is coming', mono=False),
   dict(t='kv', k='"however" (newsletter)', v='kept - the clause does contrast', mono=False),
   dict(t='kv', k='"which brings me to"', v='broken - nothing follows it', mono=False),
   dict(t='kv', k='"however" (app)', v='cut from print, and now joins two facts',
        mono=False),
   dict(t='rule'),
   dict(t='para', text='The app version was made by cutting the print version. Its markers are '
     'whatever survived the cut, which is not a policy and reads like one.')],
 callouts=[dict(at=0.08, text='Three sentences, no signposts, and the shape is on the page'),
   dict(at=0.22, text='Five markers in forty words, and four of them are kept'),
   dict(at=0.40, text='Fourteen per thousand, by accident'),
   dict(at=0.66, text='Nought entries for the channel with the most readers'),
   dict(at=0.94, text='The one broken promise is the one the reader will remember')]),

"fig_b21_u09_p07_v10": dict(type='V10', kind='pitch', height=860,
 title='Where the marker sits, and what the voice does',
 sub='The same word in three positions, and the same word as a challenge.',
 alt='Four pitch contours showing however at the front, in the middle and at the end of a '
     'sentence, and so said as a signpost and as a challenge.',
 contours=[
  dict(text='However, the figures do not support that.',
       points=[0.8, 1.0, 0.4, 0.3, 0.1, -0.2, -0.7],
       meaning='front - a rise, a pause, then the clause'),
  dict(text='The figures, however, do not support that.',
       points=[0.4, 0.3, 0.3, 0.2, 0.1, -0.2, -0.6],
       meaning='middle - level, quieter, more confident'),
  dict(text='The figures do not support that, however.',
       points=[0.5, 0.3, 0.1, -0.2, -0.5, -0.7, -0.9],
       meaning='end - an afterthought, below everything'),
  dict(text='So the guide was written in 1911?',
       points=[1.2, 0.5, 0.4, 0.3, 0.5, 0.9, 1.3],
       meaning='a jump, and a rise: a challenge, not a signpost')]),

"fig_b21_u09_p09_v05": dict(type='V5', height=940,
 title='And, but, so - and the four groups they do not cover',
 sub='Fluent and flat: the listener follows the words and not the shape.',
 alt='A study sheet showing the three discourse markers most learners use, the four relationships '
     'they cannot express, and one marker to add from each group.',
 rows=[dict(t='org', text='STUDY FILE  -  THE THREE MARKERS YOU OWN'),
   dict(t='para', text='Almost every learner at this level runs an argument on three markers. '
     'Everything else is understood when heard and never produced.'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT YOU USE', 'WHAT IT SIGNALS', 'WHAT IS MISSING'],
     data=[['AND', 'ADDITION', 'SEQUENCE: TO BEGIN WITH'],
           ['BUT', 'CONTRAST', 'CONCESSION: THAT SAID'],
           ['SO', 'RESULT', 'DISMISSAL: IN ANY CASE'],
           ['-- ', '--', 'ASIDE: AS IT HAPPENS'],
           ['TOTAL IN USE', '3', 'AVAILABLE: ABOUT 40']]),
   dict(t='rule'),
   dict(t='head', text='THE FOUR TO ADD, ONE PER GROUP'),
   dict(t='kv', k='to begin with', v='opens a list the listener can count', mono=False),
   dict(t='kv', k='that said', v='grants a point and keeps the floor', mono=False),
   dict(t='kv', k='as it happens', v='an aside, and it goes in the middle', mono=False),
   dict(t='kv', k='in any case', v='sets the last point aside without answering it', mono=False),
   dict(t='rule'),
   dict(t='para', text='Record two minutes and count. If one marker is more than a third of your '
     'total, that is this month\'s work.')],
 callouts=[dict(at=0.12, text='Three markers covering the three coarsest relationships'),
   dict(at=0.44, text='Four columns of nothing, and the listener hears all four'),
   dict(at=0.74, text='One from each group is enough to change the shape'),
   dict(at=0.95, text='Counting is the whole diagnosis, and it takes two minutes')]),

"fig_b21_u09_p10_v12": dict(type='V12',
 title='One guide, three channels, three readers',
 sub='Who reads what, how dense the signposting is, and how many get to the end.',
 alt='An infographic comparing a newspaper, its newsletter and its app on readership, marker '
     'density and completion, against a style guide that covers only one of them.',
 span=['0', '340,000 readers'], ticks=4,
 tick_labels=['0', '113k', '227k', '340k'],
 bands=[dict(name='Who reads it', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.33}, label='print: 112,000 copies', colour='#1F4E5F'),
   dict(**{'from': 0.35, 'to': 0.48}, label='newsletter: 61,000', colour='#C86B2B')]),
  dict(name='The app', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='340,000 a month - and no guide of its own',
        colour='#9AA7AE')]),
  dict(name='Markers per 1,000 words', type='events', items=[
   dict(at=0.12, label='print: 9', colour='#1F4E5F'),
   dict(at=0.44, label='app: 14, by accident', colour='#9AA7AE'),
   dict(at=0.84, label='newsletter: 31', colour='#C86B2B')]),
  dict(name='Who finishes it', type='events', items=[
   dict(at=0.20, label='print: 44%', colour='#1F4E5F'),
   dict(at=0.70, label='newsletter: 76%', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='the guide has 214 pages and nought entries for the largest channel'),
   dict(at=0.58, label='on a phone the markers are the only shape the reader can see')])]),

"fig_b21_u09_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four signposting densities, one paragraph',
 sub='Six hundred readers, the same four hundred words, four marker counts.',
 alt='A bar chart comparing four discourse-marker densities on the share of readers who finished '
     'the text and the share who could state its main point.',
 labels=['no markers', 'print: 9', 'app: 14', 'newsletter: 31'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='finished it (%)', values=[31, 44, 58, 76], colour='#2E6F5E'),
   dict(name='stated the point (%)', values=[29, 47, 61, 52], colour='#C86B2B')],
 note='Completion rises all the way. Comprehension peaks at about fourteen per thousand and then '
      'falls, because past that point the markers are describing the text rather than the argument.',
 warning='The two lines cross between the third and fourth columns. A channel optimising for '
         'completion alone will keep adding markers past the point where readers stop '
         'understanding what they are finishing.'),
}
