"""B2.1 Unit 10 - Never Once in the Culture Pages - ten figures, as data."""
FIGURES = {
"fig_b21_u10_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The news desk, ten to ten',
 sub='Twelve things to find. Two of them are the same ward and one of them is not named.',
 alt='A newsroom desk with a headline log of eighty-one entries, a ward map with six streets '
     'ringed, a resident\'s letter and a sections board.',
 sky='#D7DBD9', ground='#8A8378', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B4AFA3', cutaway=True,
     floor_labels=['the headline log, 81 entries', 'the ward map, six streets ringed',
                   'the letter'],
     label='the count'),
   dict(x=560, w=480, storeys=3, colour='#BCB8AC', cutaway=True,
     floor_labels=['the sections board', 'the style guide, open at DATELINES',
                   'the tally chart'],
     label='the desk'),
   dict(x=1120, w=460, storeys=3, colour='#B1ADA1', cutaway=True,
     floor_labels=['Tuesday\'s front page', 'the culture page, same week',
                   'the census'],
     label='the file')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='09:50'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=115, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=200, y=700, h=92, skin=3, cloth=0, hair='bun', arm='point'),
   dict(x=300, y=700, h=88, skin=2, cloth=2, hair='grey', arm='hold'),
   dict(x=660, y=700, h=86, skin=5, cloth=3, hair='short', arm='folded'),
   dict(x=1250, y=700, h=86, skin=4, cloth=4, hair='long', arm='hold'),
   dict(x=1350, y=700, h=86, skin=0, cloth=1, hair='cap', arm='down')],
 names=[dict(x=200, t='Priya - eleven years of defending the practice'),
   dict(x=300, t='the letter-writer - 31 years in the ward'),
   dict(x=660, t='the photograph of the main street'),
   dict(x=1250, t='the tenure figures: 58% rented'),
   dict(x=1350, t='the window, with the ward in it'),
   dict(x=520, t='the clock: ten to ten'),
   dict(x=1075, t='the six streets, ringed in red'),
   dict(x=115, t='the tally chart, in two colours')],
 markers=[dict(x=200, y=570), dict(x=300, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=115, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b21_u10_p01_v02": dict(type='V2', height=820,
 title='One neighbourhood, in section',
 sub='Twelve words, and the layer each one belongs to. Only the top layer is written by the paper.',
 alt='A cutaway of a neighbourhood in print, in four layers: the place and its edges, who lives '
     'there, what is happening to them, and what the newspaper adds.',
 floors=[dict(was='the place and its edges', now='neighbourhood · ward · boundary · zoning',
     year='', fill='#EDF1EC'),
   dict(was='who lives there', now='resident · tenure · demographic',
     year='', fill='#E8EEF0'),
   dict(was='what happens to them', now='gentrification · displacement',
     year='', fill='#F3EADA'),
   dict(was='what the paper adds', now='framing · headline · stereotype',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Three of these four are drawn by somebody who does not live here'),
   dict(at=0.38, text='One of these is a word residents use; two are words used about them'),
   dict(at=0.62, text='Both are processes, and both are named afterwards'),
   dict(at=0.88, text='The only layer this building controls, and the only one readers see')]),

"fig_b21_u10_p02_v07": dict(type='V7', height=840,
 title='Ten to ten, with the letter on the table',
 sub='She has counted eighty-one headlines. He has never seen the rule written down.',
 alt='A news editor and a long-standing resident across a desk with a headline log and a ward '
     'map between them, each with two speech balloons and a thought balloon.',
 bg='#E6E7E2',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=3, cloth=0, hair='bun', arm='point', facing='right',
   label='Priya', role='news editor, and the practice is hers',
   says=['Only when the story is about crime do we use the ward.',
         'A crime happens somewhere.'],
   thinks=['Nobody has ever asked me about the other four sections.']),
  dict(x=1080, h=240, skin=2, cloth=2, hair='grey', arm='hold', facing='left',
   label='the letter-writer', role='thirty-one years, four streets from the junction',
   says=['Not once did the culture pages name it.',
         'A concert also happens somewhere.'],
   thinks=['Sixty-two of the eighty-one are the same six streets.'])]),

"fig_b21_u10_p03_v09": dict(type='V9', kind='mirror', height=700,
 title='The verb comes forward, and the sentence changes weight',
 sub='The same fact, twice. Nothing is added and one word has moved to the front.',
 alt='Two sentence diagrams of the same statement, the first in ordinary order and the second '
     'with the negative adverb fronted and the auxiliary inverted.',
 labels=['ORDINARY ORDER', 'MARKED ORDER'],
 between='the auxiliary comes forward, and if there is none, do is supplied',
 active=dict(parts=[dict(w=24, role='agent', text='The culture pages'),
   dict(w=18, role='hidden', text='never'),
   dict(w=18, role='action', text='named'),
   dict(w=16, role='affected', text='it')]),
 passive=dict(parts=[dict(w=20, role='hidden', text='Not once'),
   dict(w=14, role='action', text='did'),
   dict(w=26, role='agent', text='the culture pages'),
   dict(w=20, role='affected', text='name it')])),

"fig_b21_u10_p04_v04": dict(type='V4', height=740,
 title='The same week, two sections',
 sub='Both pieces are about the same six streets. One of them says so.',
 alt='Two newspaper pages side by side from the same week, a crime story naming the ward in the '
     'headline and a culture story about the same streets that does not.',
 differences=6, prompt='Find the six. One headline names a place and one names an event. Which '
                       'of the two pieces is actually about the neighbourhood?',
 left=dict(label='Tuesday, news', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=200, bh=24, colour='#A8372E'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='ward in the headline · 0 residents quoted · 1 event',
        colour='#A8372E')]),
 right=dict(label='Friday, culture', art=[
   dict(kind='block', x=150, y=140, w=230, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=72, w=180, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='no ward anywhere · 3 residents quoted · the hall reopening',
        colour='#2E6F5E')])),

"fig_b21_u10_p05_v05": dict(type='V5', height=1140,
 title='Eighty-one headlines, sorted by section',
 sub='Where the ward is named, where it is not, and what it is called instead.',
 alt='A headline log annotated by section showing how often a ward is named in the headline, how '
     'often a resident is quoted, and the names used in place of the ward.',
 rows=[dict(t='org', text='HEADLINE LOG  -  WARD 7  -  TWO YEARS, 81 PIECES'),
   dict(t='para', text='"POLICE SEEK WITNESSES IN WARD 7" — news, Tuesday. "HALL REOPENS AFTER '
     'FOUR YEARS" — culture, Friday. Both pieces are about the same six streets.'),
   dict(t='rule'),
   dict(t='grid', cols=['SECTION', 'WARD NAMED', 'RESIDENT QUOTED'],
     data=[['CRIME  (34 PIECES)', '71%', '11%'],
           ['PLANNING  (22)', '18%', '34%'],
           ['BUSINESS  (14)', '6%', '8%'],
           ['CULTURE  (11)', '0%', '52%'],
           ['ALL SECTIONS', '38%', '21%'],
           ['THE SAME SIX STREETS', '62 OF 81', '--'],
           ['WARD POPULATION', '40,000', '--'],
           ['RULE IN THE STYLE GUIDE', 'NONE', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHAT IT IS CALLED WHEN IT IS NOT CALLED WARD 7'),
   dict(t='kv', k='"the north end"', v='used by everybody who lives elsewhere', mono=False),
   dict(t='kv', k='"a problem neighbourhood"', v='describes the coverage, not the place',
        mono=False),
   dict(t='kv', k='"the Lake and Seventh area"', v='used only in planning stories', mono=False),
   dict(t='kv', k='no name at all', v='the culture pages, every time', mono=False),
   dict(t='rule'),
   dict(t='para', text='Every one of these eighty-one headlines is accurate. The pattern they '
     'make is not in any of them, and nobody chose it.')],
 callouts=[dict(at=0.08, text='Two headlines, one week, one set of six streets'),
   dict(at=0.26, text='Seventy-one in one row and nought in another, and no rule between them'),
   dict(at=0.48, text='The section that quotes residents most names the place least'),
   dict(at=0.80, text='Four names for one ward, and residents use none of them'),
   dict(at=0.95, text='Every headline true, and the pattern chosen by nobody')]),

"fig_b21_u10_p07_v10": dict(type='V10', kind='pitch', height=860,
 title='Marked order needs the jump that goes with it',
 sub='Inversion without the pitch jump sounds like a mistake. The two travel together.',
 alt='Four pitch contours over inverted and uninverted sentences, showing where the voice jumps '
     'on the fronted adverb and where a flat delivery loses the emphasis.',
 contours=[
  dict(text='We rarely name it.',
       points=[0.3, 0.2, 0.1, -0.1, -0.3, -0.5, -0.6],
       meaning='ordinary order, flat, forgettable'),
  dict(text='Rarely do we name it.',
       points=[0.95, 0.6, 0.3, 0.1, -0.1, -0.4, -0.7],
       meaning='the jump is on the first word'),
  dict(text='Not once did the culture pages name it.',
       points=[0.4, 0.9, 0.5, 0.3, 0.1, -0.2, -0.7],
       meaning='the jump waits for the second word'),
  dict(text='Only when it is crime do we name it.',
       points=[0.3, 0.4, 0.5, 0.9, 0.4, 0.0, -0.6],
       meaning='the jump waits for the content word')]),

"fig_b21_u10_p09_v05": dict(type='V5', height=940,
 title='Two versions of where you are from',
 sub='The stranger\'s version is efficient, accurate, and the only one most people keep.',
 alt='A study sheet comparing the version learners give a stranger with the version they would '
     'give a neighbour, and what is lost from the first.',
 rows=[dict(t='org', text='STUDY FILE  -  HOW YOU DESCRIBE WHERE YOU ARE FROM'),
   dict(t='para', text='The stranger\'s version has never once been questioned, which is why it '
     'survives. It is also the version that contains no place in it.'),
   dict(t='rule'),
   dict(t='grid', cols=['FOR A STRANGER', 'FOR A NEIGHBOUR', 'WHAT WAS LOST'],
     data=[['A SMALL CITY', 'THE NAME OF IT', 'THE NAME'],
           ['TWO HOURS FROM THE CAPITAL', 'THE RIVER SIDE OF IT', 'THE GEOGRAPHY'],
           ['NOT VERY INTERESTING', 'THE MARKET ON THURSDAYS', 'THE ONE DETAIL'],
           ['LIKE A SMALL VERSION OF X', 'NOT LIKE X AT ALL', 'THE COMPARISON'],
           ['EVERYBODY LEAVES', 'MY SISTER DID NOT', 'THE EXCEPTION']]),
   dict(t='rule'),
   dict(t='head', text='THE TEST, IN FOUR STEPS'),
   dict(t='kv', k='say it to a stranger', v='the version you already have', mono=False),
   dict(t='kv', k='say it to somebody who has been', v='and watch what you add', mono=False),
   dict(t='kv', k='replace every general word', v='with a specific one', mono=False),
   dict(t='kv', k='invert one sentence', v='and see which one they remember', mono=False),
   dict(t='rule'),
   dict(t='para', text='Write four sentences about where you are from, one of them inverted. Read '
     'all four to somebody and ask which one they remember.')],
 callouts=[dict(at=0.12, text='A fluent sentence said two hundred times and never questioned'),
   dict(at=0.44, text='Five rows, and the right-hand column is where the place is'),
   dict(at=0.76, text='A comparison is what you say when you have no detail'),
   dict(at=0.95, text='One inverted sentence is the one they will repeat')]),

"fig_b21_u10_p10_v12": dict(type='V12',
 title='Eighty-one headlines, four sections, six streets',
 sub='Where the ward is named, who is quoted, and what readers took from it.',
 alt='An infographic of two years of coverage of one ward showing how often it was named in '
     'headlines by section, how often residents were quoted, and what changed afterwards.',
 span=['0', '81 pieces'], ticks=4,
 tick_labels=['0', '27', '54', '81'],
 bands=[dict(name='Where the pieces are', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.42}, label='crime: 34', colour='#A8372E'),
   dict(**{'from': 0.44, 'to': 0.71}, label='planning: 22', colour='#C86B2B'),
   dict(**{'from': 0.73, 'to': 0.90}, label='business: 14', colour='#D9A441'),
   dict(**{'from': 0.92, 'to': 1.0}, label='culture: 11', colour='#2E6F5E')]),
  dict(name='Ward named in the headline', type='events', items=[
   dict(at=0.14, label='crime: 71%', colour='#A8372E'),
   dict(at=0.48, label='planning: 18%', colour='#C86B2B'),
   dict(at=0.80, label='culture: 0%', colour='#2E6F5E')]),
  dict(name='Where the pieces are about', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.77}, label='the same six streets: 62 of 81',
        colour='#9AA7AE')]),
  dict(name='Afterwards', type='events', items=[
   dict(at=0.22, label='headlines the next year: 140', colour='#1F4E5F'),
   dict(at=0.72, label='crime share of them: 29%', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='the section that quotes residents most names the place least'),
   dict(at=0.56, label='every headline accurate, and the pattern chosen by nobody')])]),

"fig_b21_u10_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Naming and quoting, by section',
 sub='Two years, eighty-one pieces, four sections of the same newspaper.',
 alt='A bar chart comparing four newspaper sections on how often a ward is named in the headline '
     'and how often a resident is quoted in the piece.',
 labels=['crime', 'planning', 'business', 'culture'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='ward in headline (%)', values=[71, 18, 6, 0], colour='#A8372E'),
   dict(name='resident quoted (%)', values=[11, 34, 8, 52], colour='#2E6F5E')],
 note='The two series run in opposite directions. The section that names the ward most often is '
      'the one that asks its residents least, and the section that asks them most never names it.',
 warning='Each section can defend its own practice and three editors did, all three on grounds of '
         'specificity. The defence is sound; it has only ever been applied where the news is bad.'),
}
