# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C9-1': ('case item C9-1', []),
    'C9-2': ('case item C9-2', []),
    'C9-3': ('case item C9-3', []),
    'C9-4': ('case item C9-4', []),
    'C9-5': ('case item C9-5', []),
    'C9-6': ('case item C9-6', []),
    'P9-01': ('practice item P9-01', []),
    'P9-02': ('practice item P9-02', []),
    'P9-03': ('practice item P9-03', []),
    'P9-04': ('practice item P9-04', []),
    'P9-05': ('practice item P9-05', []),
    'P9-06': ('practice item P9-06', []),
    'P9-07': ('practice item P9-07', []),
    'P9-08': ('practice item P9-08', []),
    'P9-09': ('practice item P9-09', []),
    'P9-10': ('practice item P9-10', []),
    'P9-11': ('practice item P9-11', []),
    'P9-12': ('practice item P9-12', []),
    'P9-13': ('practice item P9-13', []),
    'P9-14': ('practice item P9-14', []),
    'P9-15': ('practice item P9-15', []),
    'P9-16': ('practice item P9-16', []),
    'SC9-1': ('section-check item SC9-1', []),
    'SC9-2': ('section-check item SC9-2', []),
    'SC9-3': ('section-check item SC9-3', []),
    'SC9-4': ('section-check item SC9-4', []),
    'SC9-5': ('section-check item SC9-5', []),
    'SC9-6': ('section-check item SC9-6', []),
    'SC9-7': ('section-check item SC9-7', []),
    'term:available-for-sale (afs) securities': ("term-bridge row 'available-for-sale (AFS) securities'", []),
    'term:basis difference': ("term-bridge row 'basis difference'", []),
    'term:bond discount': ("term-bridge row 'bond discount'", []),
    'term:bond premium': ("term-bridge row 'bond premium'", []),
    'term:debt security': ("term-bridge row 'debt security'", []),
    'term:effective-interest method': ("term-bridge row 'effective-interest method'", []),
    'term:equity method': ("term-bridge row 'equity method'", []),
    'term:equity security': ("term-bridge row 'equity security'", []),
    'term:fair value': ("term-bridge row 'fair value'", []),
    'term:fair value option': ("term-bridge row 'fair value option'", []),
    'term:held-to-maturity (htm) securities': ("term-bridge row 'held-to-maturity (HTM) securities'", []),
    'term:investee': ("term-bridge row 'investee'", []),
    'term:measurement alternative': ("term-bridge row 'measurement alternative'", []),
    'term:other comprehensive income (oci)': ("term-bridge row 'other comprehensive income (OCI)'", []),
    'term:reclassification adjustment': ("term-bridge row 'reclassification adjustment'", []),
    'term:significant influence': ("term-bridge row 'significant influence'", []),
    'term:trading securities': ("term-bridge row 'trading securities'", []),
    'term:unrealized holding gain or loss': ("term-bridge row 'unrealized holding gain or loss'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C9-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'C9-6': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
}
