# -*- coding: utf-8 -*-
"""Handout 17.3, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '17.3',
 'n': 3,
 'pages': 4,
 'title': '(iii) Inventories',
 'sub': 'section 17.3 of the book',
 'covers': ['sec:17.3',
            'p:P17-13',
            'p:P17-14',
            'p:P17-15',
            'p:P17-16',
            'sc:P17-13',
            'term:development costs',
            'term:graded vesting',
            'term:fair value less costs of disposal'],
 'skills': [('read3', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['(iii) Inventories',
             'a figure to read · Item',
             'An asset has a carrying amount of $500,000, fair value less '
             'costs of disposal of $420,000 and value in use of $460,000. '
             'What is the IFRS impairment loss?'],
            ['The words this section uses precisely',
             'The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['GAAP allows it, and companies that use LIFO for tax '
                       'must also use it in their ',
                       11,
                       ' ',
                       12,
                       '. Chapter 7 showed how LIFO changes cost of goods '
                       'sold when prices rise. Both ',
                       12,
                       ' write inventory down when its value falls below '
                       'cost.'],
             'bank': ['frameworks',
                      'statements',
                      'recoverability test',
                      'financial',
                      'value in use'],
             'a': 'financial · statements · frameworks',
             'one': True,
             'why': 'The book writes: “GAAP allows it, and companies that '
                    'use LIFO for tax must also use it in their financial '
                    'statements. Chapter 7 showed how LIFO changes cost of '
                    'goods sold when prices rise. Both frameworks write '
                    'inventory down when its value falls below cost.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['IAS 2 uses the lower of cost and NRV for all ',
                       11,
                       '. GAAP uses lower of cost and NRV for FIFO and '
                       'average cost, but lower of cost or market for LIFO '
                       'and the retail method. The key ',
                       12,
                       ' comes when value ',
                       11,
                       '.'],
             'bank': ['inventory',
                      'recoverability test',
                      'recovers',
                      'value in use',
                      'difference'],
             'a': 'inventory · difference · recovers',
             'one': True,
             'why': 'The book writes: “IAS 2 uses the lower of cost and NRV '
                    'for all inventory. GAAP uses lower of cost and NRV for '
                    'FIFO and average cost, but lower of cost or market for '
                    'LIFO and the retail method. The key difference comes '
                    'when value recovers.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['IFRS reverses the ',
                       12,
                       ', but never above the original cost. ',
                       11,
                       ' write-down and recovery: IFRS reverses, U.S. French '
                       'stocks means inventory, not shares.'],
             'bank': ['value in use',
                      'write-down',
                      'recoverability test',
                      'Inventory'],
             'a': 'write-down · Inventory',
             'one': True,
             'why': 'The book writes: “IFRS reverses the write-down, but '
                    'never above the original cost. Inventory write-down and '
                    'recovery: IFRS reverses, U.S. French stocks means '
                    'inventory, not shares.”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['development costs', ''],
              ['graded vesting', ''],
              ['fair value less costs of disposal', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', '(iii) Inventories'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f3'),
          ('panel',
           'Item — the book’s own table',
           [['Item', 'Category'],
            ['L1 Development costs', ''],
            ['L2 Write-down reversal', ''],
            ['L3 Land revaluation', ''],
            ['L4 Fleet impairment', ''],
            ['L5 Truck lease', '']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which part of this chapter is section 17.2?',
             'o': ['(ii) Intangible assets',
                   '(v) Long-lived assets',
                   '(iii) Inventories',
                   '(iv) Leases: the lessee'],
             'a': 'A',
             'why': 'The book numbers “(ii) Intangible assets” as section '
                    '17.2.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 17.3?',
             'o': ['(iii) Inventories',
                   '(vi) Impairment',
                   '(ii) Intangible assets',
                   '(v) Long-lived assets'],
             'a': 'A',
             'why': 'The book numbers “(iii) Inventories” as section 17.3.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 17.4?',
             'o': ['(v) Long-lived assets',
                   '(ii) Intangible assets',
                   '(iii) Inventories',
                   '(iv) Leases: the lessee'],
             'a': 'D',
             'why': 'The book numbers “(iv) Leases: the lessee” as section '
                    '17.4.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 17.5?',
             'o': ['(ii) Intangible assets',
                   '(iii) Inventories',
                   '(v) Long-lived assets',
                   '(iv) Leases: the lessee'],
             'a': 'C',
             'why': 'The book numbers “(v) Long-lived assets” as section '
                    '17.5.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'An asset has a carrying amount of $500,000, fair value '
                  'less costs of disposal of $420,000 and value in use of '
                  '$460,000. What is the IFRS impairment loss?',
             'o': ['$0', '$40,000', '$60,000', '$80,000'],
             'a': 'B',
             'why': 'Recoverable amount is the higher amount, $460,000. A is '
                    'wrong: IFRS has no undiscounted screen. C is wrong: '
                    'This uses an average.',
             'src': 'P17-13'},
            {'t': 'MCQ',
             'q': 'Goodwill was impaired last year. This year the '
                  'cash-generating unit recovers. Under IFRS, the goodwill '
                  'impairment is:',
             'o': ['reversed in full',
                   'reversed up to original cost',
                   'reversed through OCI',
                   'never reversed'],
             'a': 'D',
             'why': 'IAS 36 prohibits reversal of goodwill impairment. A is '
                    'wrong: Goodwill impairments are never reversed. B is '
                    'wrong: No reversal is allowed for goodwill.',
             'src': 'P17-14'},
            {'t': 'MCQ',
             'q': "What is the IFRS equivalent of a U.S. 'asset group' in "
                  'impairment testing?',
             'o': ['A reporting unit',
                   'A cash-generating unit',
                   'A disposal group',
                   'A component of an entity'],
             'a': 'B',
             'why': 'IAS 36 tests assets in cash-generating units. A is '
                    'wrong: A reporting unit is the U.S. goodwill level. C '
                    'is wrong: A disposal group is for assets held for sale.',
             'src': 'P17-15'},
            {'t': 'MCQ',
             'q': 'Which pair shows a correct difference?',
             'o': ['U.S.: research and development expensed; IFRS: '
                   'development capitalized when criteria are met',
                   'U.S.: development capitalized; IFRS: expensed',
                   'Both capitalize research',
                   'Both expense all software costs'],
             'a': 'A',
             'why': 'This is the main intangibles difference. B is wrong: '
                    'The treatments are reversed. C is wrong: Research is '
                    'expensed under both.',
             'src': 'P17-16'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'An asset has a carrying amount of $500,000, fair value less '
           'costs of disposal of $420,000 and value in use of $460,000. What '
           'is the IFRS impairment loss?',
           ['$0', '$40,000', '$60,000', '$80,000'],
           'B',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'Recoverable amount is the higher amount, $460,000. A is wrong: '
           'IFRS has no undiscounted screen. C is wrong: This uses an '
           'average.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['development costs', 'تكاليف التطوير'],
            ['graded vesting', 'الاستحقاق المتدرج'],
            ['fair value less costs of disposal',
             'القيمة العادلة ناقصاً تكاليف الاستبعاد']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A glossary term and its translation are a pair the book '
                  'itself gives.',
             'a': 'T',
             'why': 'The term tables in each section are the book’s own.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'TF',
             'q': 'Writing a term in English is part of answering the '
                  'question, not an extra.',
             'a': 'T',
             'why': 'The exam marks the term, so the English word is the '
                    'answer.'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f3',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['development costs',
            'graded vesting',
            'fair value less costs of disposal'],
           'IFRS does not allow LIFO. U.S. GAAP allows it, and companies '
           'that use LIFO for tax must also use it in their financial '
           'statements. Chapter 7 showed how LIFO changes cost of goods sold '
           'when prices rise.')]}
