# -*- coding: utf-8 -*-
"""Handout 7.1, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '7.1',
 'n': 1,
 'pages': 5,
 'title': 'Which goods belong in inventory?',
 'sub': 'section 7.1 of the book',
 'covers': ['sec:7.1',
            'p:P7-01',
            'p:P7-02',
            'p:P7-04',
            'p:P7-07',
            'p:P7-08',
            'p:P7-10',
            'term:inventory',
            'term:weighted-average cost',
            'term:goods in transit',
            'term:consignee',
            'term:normal capacity',
            'term:specific identification'],
 'skills': [('read1', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['Which goods belong in inventory?',
             'a figure to read · Memo item',
             'Which of these did this cycle settle?'],
            ['The words this section uses precisely',
             'The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['Under ',
                       20,
                       ', control passes to the buyer when the goods leave '
                       'the seller, so the buyer includes them. Under ',
                       17,
                       ', the seller keeps control until the goods arrive, '
                       'so the seller includes them. In a ',
                       13,
                       ', the ',
                       11,
                       ' (the owner) gives goods to a ',
                       11,
                       ', who sells them for a commission.'],
             'bank': ['consignor',
                      'consignee',
                      'periodic inventory system',
                      'FOB destination',
                      'weighted-average cost',
                      'consignment',
                      'FOB shipping point'],
             'a': 'FOB shipping point · FOB destination · consignment · '
                  'consignor · consignee',
             'one': True,
             'why': 'The book writes: “Under FOB shipping point, control '
                    'passes to the buyer when the goods leave the seller, so '
                    'the buyer includes them. Under FOB destination, the '
                    'seller keeps control until the goods arrive, so the '
                    'seller includes them. In a consignment, the consignor '
                    '(the owner) gives goods to a consignee, who sells them '
                    'for a commission.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['In a bill-and-hold sale, the seller keeps the goods '
                       'in its ',
                       11,
                       ' unless strict conditions show that the buyer '
                       'already controls them. ',
                       20,
                       ': the BUYER includes ',
                       18,
                       '. ',
                       17,
                       ': the SELLER includes them.'],
             'bank': ['weighted-average cost',
                      'inventory',
                      'periodic inventory system',
                      'FOB shipping point',
                      'FOB destination',
                      'goods in transit'],
             'a': 'inventory · FOB shipping point · goods in transit · FOB '
                  'destination',
             'one': True,
             'why': 'The book writes: “In a bill-and-hold sale, the seller '
                    'keeps the goods in its inventory unless strict '
                    'conditions show that the buyer already controls them. '
                    'FOB shipping point: the BUYER includes goods in '
                    'transit. FOB destination: the SELLER includes them.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['In U.S. exam questions, ',
                       20,
                       ' and ',
                       17,
                       ' are simple shipping terms that decide who controls ',
                       18,
                       ', by truck, rail or sea. Do not bring Incoterm rules '
                       'into these questions. Arabic: البضاعة بالأمانة is ',
                       13,
                       '; the owner is the consignor (المُرسِل) and the '
                       'seller in the shop is the ',
                       11,
                       ' (المُرسَل إليه).'],
             'bank': ['consignment',
                      'periodic inventory system',
                      'weighted-average cost',
                      'goods in transit',
                      'FOB destination',
                      'FOB shipping point',
                      'consignee'],
             'a': 'FOB shipping point · FOB destination · goods in transit · '
                  'consignment · consignee',
             'one': True,
             'why': 'The book writes: “In U.S. exam questions, FOB shipping '
                    'point and FOB destination are simple shipping terms '
                    'that decide who controls goods in transit, by truck, '
                    'rail or sea. Do not bring Incoterm rules into these '
                    'questions. Arabic: البضاعة بالأمانة is consignment; the '
                    'owner is the consignor (المُرسِل) and the seller in the '
                    'shop is the consignee (المُرسَل إليه).”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['inventory', ''],
              ['weighted-average cost', ''],
              ['goods in transit', ''],
              ['consignee', ''],
              ['normal capacity', ''],
              ['specific identification', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', 'Which goods belong in inventory?'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'The book gives the category of M4 (at a Doha consignee) '
                  'as “Add to the count”.',
             'a': 'T',
             'why': 'The book pairs M4 (at a Doha consignee) with “Add to '
                    'the count”.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'goods_tree'),
          ('panel',
           'Memo item — the book’s own table',
           [['Memo item', 'Category'],
            ['M1 (FOB shipping point, bought)', 'Add to the count'],
            ['M2 (FOB destination, sold)', 'Add to the count'],
            ['M3 (held for a Beirut producer)', 'Subtract from the count'],
            ['M4 (at a Doha consignee)', 'Add to the count']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which memo item does the book pair with “Subtract from '
                  'the count”?',
             'o': ['M4 (at a Doha consignee)',
                   'M1 (FOB shipping point, bought)',
                   'M2 (FOB destination, sold)',
                   'M3 (held for a Beirut producer)'],
             'a': 'D',
             'why': 'The book’s own table pairs M3 (held for a Beirut '
                    'producer) with “Subtract from the count”.'},
            {'t': 'SORT',
             'q': 'Write each one under its category. Every item belongs to '
                  'exactly one group.',
             'regions': ['Add to the count', 'Subtract from the count'],
             'items': ['M1 (FOB shipping point, bought)',
                       'M2 (FOB destination, sold)',
                       'M3 (held for a Beirut producer)',
                       'M4 (at a Doha consignee)'],
             'a': ['Add to the count: M1 (FOB shipping point, bought), M2 '
                   '(FOB destination, sold), M4 (at a Doha consignee)',
                   'Subtract from the count: M3 (held for a Beirut '
                   'producer)'],
             'whys': ['', '']}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'A seller ships goods on December 30, FOB destination. The '
                  'goods arrive on January 2. At December 31, the goods '
                  'should be:',
             'o': ["included in the buyer's inventory.",
                   "included in the seller's inventory, with no sale "
                   'recorded yet.',
                   "removed from the seller's inventory, with a sale "
                   'recorded.',
                   "excluded from both companies' inventories."],
             'a': 'B',
             'why': 'Under FOB destination, the seller keeps control until '
                    'delivery. A is wrong: The buyer includes goods in '
                    'transit only under FOB shipping point. C is wrong: '
                    'Control has not passed, so no sale is recorded yet.',
             'src': 'P7-01'},
            {'t': 'MCQ',
             'q': 'A strike cut production far below normal capacity. How '
                  'should the fixed production overhead that was not '
                  'allocated to units be treated?',
             'o': ['As an expense of the period',
                   'Added to the cost of the units produced',
                   'Deferred as an asset to next year',
                   'Charged directly to retained earnings'],
             'a': 'A',
             'why': 'Fixed overhead is allocated on normal capacity; the '
                    'unallocated part is a period expense. B is wrong: This '
                    'would give each unit an abnormally high cost. C is '
                    'wrong: No future benefit exists, so it is not an asset.',
             'src': 'P7-02'},
            {'t': 'MCQ',
             'q': 'Which statement about periodic and perpetual systems is '
                  'TRUE?',
             'o': ['LIFO gives the same cost of goods sold under both '
                   'systems.',
                   'The moving average always equals the periodic weighted '
                   'average.',
                   'FIFO gives the same cost of goods sold under both '
                   'systems.',
                   'A perpetual system requires specific identification.'],
             'a': 'C',
             'why': 'FIFO always sells the oldest units first, whatever the '
                    'timing of sales. A is wrong: Perpetual LIFO can only '
                    'use costs that exist on each sale date. B is wrong: The '
                    'moving average changes after each purchase, so results '
                    'usually differ.',
             'src': 'P7-04'},
            {'t': 'MCQ',
             'q': 'Specific identification is MOST appropriate for:',
             'o': ['unique, high-value items such as cars.',
                   'large volumes of identical glass bottles.',
                   'any items when prices are rising.',
                   'perishable food products.'],
             'a': 'A',
             'why': 'It tracks the cost of each individual item, which is '
                    'practical only for distinct items. B is wrong: '
                    'Identical items are interchangeable; tracking each one '
                    'is costly and allows manipulation. C is wrong: Price '
                    'trends do not decide when specific identification fits.',
             'src': 'P7-07'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Which of these did this cycle settle?',
           ['the rule and where it comes from',
            'nothing in particular',
            'only the vocabulary',
            'only the arithmetic'],
           'A',
           'redo the READ THE MODEL questions of cycle A.',
           'Every cycle settles one rule and shows where it comes from.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['inventory', 'المخزون'],
            ['weighted-average cost', 'المتوسط المرجح للتكلفة'],
            ['goods in transit', 'بضاعة في الطريق'],
            ['consignee', 'المُرسَل إليه (الوكيل بالعمولة)'],
            ['normal capacity', 'الطاقة العادية'],
            ['specific identification', 'التحديد العيني (التمييز المحدد)']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MATCH',
             'q': 'Write the letter of the Arabic term beside each English '
                  'term. Every term is used once.',
             'left': ['specific identification',
                      'goods in transit',
                      'inventory',
                      'weighted-average cost',
                      'normal capacity',
                      'consignee'],
             'right': ['المتوسط المرجح للتكلفة',
                       'المُرسَل إليه (الوكيل بالعمولة)',
                       'الطاقة العادية',
                       'بضاعة في الطريق',
                       'المخزون',
                       'التحديد العيني (التمييز المحدد)'],
             'a': ['F', 'D', 'E', 'A', 'C', 'B'],
             'whys': ['', '', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Prices are falling. Which method gives the highest gross '
                  'profit?',
             'o': ['FIFO',
                   'Weighted average',
                   'LIFO',
                   'All methods give the same gross profit.'],
             'a': 'C',
             'why': 'With falling prices, LIFO puts the newest, lowest costs '
                    'into cost of goods sold. A is wrong: FIFO gives the '
                    'highest profit only when prices rise. B is wrong: The '
                    'average is always between FIFO and LIFO.',
             'src': 'P7-08'},
            {'t': 'MCQ',
             'q': 'Prices are rising, and a LIFO company sells more units '
                  'than it buys, so old layers are liquidated. What is the '
                  'effect in that year?',
             'o': ['Gross profit decreases.',
                   'Gross profit increases.',
                   'There is no effect, because costs are historical.',
                   'A loss arises that must be deferred.'],
             'a': 'B',
             'why': 'Old, low costs flow into cost of goods sold, so gross '
                    'profit rises for that year. A is wrong: Low old costs '
                    'reduce cost of goods sold. C is wrong: The old costs '
                    'are much lower than current costs, so income changes.',
             'src': 'P7-10'},
            {'t': 'MCQ',
             'q': 'The tax rate is 25%. Ending inventory was overstated by '
                  '40. By how much is net income overstated in that year?',
             'o': ['10', '30', '40', '50'],
             'a': 'B',
             'why': 'After-tax effect = pretax error × (1 − tax rate). A is '
                    'wrong: This is the tax effect only. C is wrong: This is '
                    'the pretax effect.',
             'src': 'P7-13'},
            {'t': 'MCQ',
             'q': 'Ending inventory for 2026 is understated by 15. Inventory '
                  'for 2025 was correct. What is the effect on 2026 cost of '
                  'goods sold?',
             'o': ['Understated by 15',
                   'No effect',
                   'Overstated by 15',
                   'Overstated by 30'],
             'a': 'C',
             'why': 'COGS = beginning inventory + purchases − ending '
                    'inventory, so low ending inventory raises COGS. A is '
                    'wrong: This reverses the direction. B is wrong: Ending '
                    'inventory directly changes COGS.',
             'src': 'P7-14'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'goods_tree',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['inventory',
            'weighted-average cost',
            'goods in transit',
            'consignee'],
           'Inventory means goods held for sale in the ordinary course of '
           'business, goods in production, and materials that will be used '
           'in production. A retailer such as Barada Wholesale, Inc. has one '
           'inventory account. A manufacturer such as Orontes has three: raw '
           'materials, work in process and finished goods.')]}
