# -*- coding: utf-8 -*-
"""Handout 3.4, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '3.4',
 'n': 4,
 'pages': 6,
 'title': 'Comprehensive income',
 'sub': 'section 3.4 of the book',
 'covers': ['sec:3.4',
            'p:P3-20',
            'p:P3-21',
            'sc:P3-20',
            'term:income from continuing operations',
            'term:earnings per share (eps)',
            'term:strategic shift'],
 'skills': [('read4', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Answer every one of these now, from what you already know or by '
           'guessing. You are not expected to get them right: you are about '
           'to be shown where each answer comes from.',
           [['This handout settles', 'where it is answered'],
            ['Comprehensive income', 'cycle A'],
            ['and you mark your own answers', 'at every checkpoint']],
           [{'t': 'MCQ',
             'q': 'Which item does the book pair with “OCI; reclassified to '
                  'net income on sale”?',
             'o': ['Pension gains, losses and prior service cost',
                   'Changes in fair value of equity securities',
                   'Unrealized gains and losses on debt securities (AFS / '
                   'FVOCI)',
                   'Revaluation of PP&E'],
             'a': 'C',
             'why': 'The book’s own table pairs Unrealized gains and losses '
                    'on debt securities (AFS / FVOCI) with “OCI; '
                    'reclassified to net income on sale”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Net income (no OCI '
                  'option)”?',
             'o': ['Pension gains, losses and prior service cost',
                   'Effective part of cash-flow hedges',
                   'Changes in fair value of equity securities',
                   'Unrealized gains and losses on debt securities (AFS / '
                   'FVOCI)'],
             'a': 'C',
             'why': 'The book’s own table pairs Changes in fair value of '
                    'equity securities with “Net income (no OCI option)”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “OCI; reclassified '
                  'when the foreign operation is sold”?',
             'o': ['Effective part of cash-flow hedges',
                   'Foreign-currency translation adjustments',
                   'Unrealized gains and losses on debt securities (AFS / '
                   'FVOCI)',
                   'Pension gains, losses and prior service cost'],
             'a': 'B',
             'why': 'The book’s own table pairs Foreign-currency translation '
                    'adjustments with “OCI; reclassified when the foreign '
                    'operation is sold”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “OCI; amortized into '
                  'net income later”?',
             'o': ['Unrealized gains and losses on debt securities (AFS / '
                   'FVOCI)',
                   'Pension gains, losses and prior service cost',
                   'Revaluation of PP&E',
                   'Effective part of cash-flow hedges'],
             'a': 'B',
             'why': 'The book’s own table pairs Pension gains, losses and '
                    'prior service cost with “OCI; amortized into net income '
                    'later”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “OCI; reclassified '
                  'when the hedged item affects income”?',
             'o': ['Foreign-currency translation adjustments',
                   'Unrealized gains and losses on debt securities (AFS / '
                   'FVOCI)',
                   'Effective part of cash-flow hedges',
                   'Changes in fair value of equity securities'],
             'a': 'C',
             'why': 'The book’s own table pairs Effective part of cash-flow '
                    'hedges with “OCI; reclassified when the hedged item '
                    'affects income”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Not allowed”?',
             'o': ['Foreign-currency translation adjustments',
                   'Revaluation of PP&E',
                   'Unrealized gains and losses on debt securities (AFS / '
                   'FVOCI)',
                   'Pension gains, losses and prior service cost'],
             'a': 'B',
             'why': 'The book’s own table pairs Revaluation of PP&E with '
                    '“Not allowed”.'},
            {'t': 'MCQ',
             'q': 'Which IFRS does the book give for Unrealized gains and '
                  'losses on debt securities (AFS / FVOCI)?',
             'o': ['Net income, or OCI by election (never reclassified)',
                   'OCI; reclassified on sale',
                   'OCI; never reclassified',
                   'Revaluation surplus in OCI; never reclassified'],
             'a': 'B',
             'why': 'The book’s own table gives OCI; reclassified on sale as '
                    'the IFRS of Unrealized gains and losses on debt '
                    'securities (AFS / FVOCI).'},
            {'t': 'MCQ',
             'q': 'Which IFRS does the book give for Changes in fair value '
                  'of equity securities?',
             'o': ['OCI; reclassified on sale',
                   'Same',
                   'Net income, or OCI by election (never reclassified)',
                   'OCI; never reclassified'],
             'a': 'C',
             'why': 'The book’s own table gives Net income, or OCI by '
                    'election (never reclassified) as the IFRS of Changes in '
                    'fair value of equity securities.'},
            {'t': 'MCQ',
             'q': 'Which IFRS does the book give for Foreign-currency '
                  'translation adjustments?',
             'o': ['OCI; never reclassified',
                   'Same',
                   'Revaluation surplus in OCI; never reclassified',
                   'OCI; reclassified on sale'],
             'a': 'B',
             'why': 'The book’s own table gives Same as the IFRS of '
                    'Foreign-currency translation adjustments.'},
            {'t': 'MCQ',
             'q': 'Which IFRS does the book give for Pension gains, losses '
                  'and prior service cost?',
             'o': ['Same',
                   'OCI; never reclassified',
                   'Net income, or OCI by election (never reclassified)',
                   'OCI; reclassified on sale'],
             'a': 'B',
             'why': 'The book’s own table gives OCI; never reclassified as '
                    'the IFRS of Pension gains, losses and prior service '
                    'cost.'},
            {'t': 'MCQ',
             'q': 'Which IFRS does the book give for Effective part of '
                  'cash-flow hedges?',
             'o': ['Net income, or OCI by election (never reclassified)',
                   'Same',
                   'Revaluation surplus in OCI; never reclassified',
                   'OCI; reclassified on sale'],
             'a': 'B',
             'why': 'The book’s own table gives Same as the IFRS of '
                    'Effective part of cash-flow hedges.'},
            {'t': 'MCQ',
             'q': 'Which IFRS does the book give for Revaluation of PP&E?',
             'o': ['OCI; never reclassified',
                   'Net income, or OCI by election (never reclassified)',
                   'Revaluation surplus in OCI; never reclassified',
                   'OCI; reclassified on sale'],
             'a': 'C',
             'why': 'The book’s own table gives Revaluation surplus in OCI; '
                    'never reclassified as the IFRS of Revaluation of PP&E.'},
            {'t': 'TF',
             'q': 'The book gives the IFRS of Unrealized gains and losses on '
                  'debt securities (AFS / FVOCI) as “OCI; reclassified on '
                  'sale”.',
             'a': 'T',
             'why': 'The book pairs Unrealized gains and losses on debt '
                    'securities (AFS / FVOCI) with “OCI; reclassified on '
                    'sale”.'},
            {'t': 'TF',
             'q': 'The book gives the IFRS of Changes in fair value of '
                  'equity securities as “OCI; never reclassified”.',
             'a': 'F',
             'why': 'The book pairs Changes in fair value of equity '
                    'securities with “Net income, or OCI by election (never '
                    'reclassified)”, not with “OCI; never reclassified”.'},
            {'t': 'TF',
             'q': 'The book gives the IFRS of Foreign-currency translation '
                  'adjustments as “Same”.',
             'a': 'T',
             'why': 'The book pairs Foreign-currency translation adjustments '
                    'with “Same”.'}]),
          ('page',),
          ('cycle', 'A', 'Comprehensive income'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'The book gives the U.S. GAAP of Unrealized gains and '
                  'losses on debt securities (AFS / FVOCI) as “OCI; '
                  'reclassified to net income on sale”.',
             'a': 'T',
             'why': 'The book pairs Unrealized gains and losses on debt '
                    'securities (AFS / FVOCI) with “OCI; reclassified to net '
                    'income on sale”.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f4'),
          ('panel',
           'Item — the book’s own table',
           [['Item', 'U.S. GAAP', 'IFRS'],
            ['Unrealized gains and losses on debt securities (AFS / FVOCI)',
             'OCI; reclassified to net income on sale',
             'OCI; reclassified on sale'],
            ['Changes in fair value of equity securities',
             'Net income (no OCI option)',
             'Net income, or OCI by election (never reclassified)'],
            ['Foreign-currency translation adjustments',
             'OCI; reclassified when the foreign operation is sold',
             'Same'],
            ['Pension gains, losses and prior service cost',
             'OCI; amortized into net income later',
             'OCI; never reclassified'],
            ['Effective part of cash-flow hedges',
             'OCI; reclassified when the hedged item affects income',
             'Same'],
            ['Revaluation of PP&E',
             'Not allowed',
             'Revaluation surplus in OCI; never reclassified']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which item does the book pair with “OCI; reclassified to '
                  'net income on sale”?',
             'o': ['Effective part of cash-flow hedges',
                   'Pension gains, losses and prior service cost',
                   'Changes in fair value of equity securities',
                   'Unrealized gains and losses on debt securities (AFS / '
                   'FVOCI)'],
             'a': 'D',
             'why': 'The book’s own table pairs Unrealized gains and losses '
                    'on debt securities (AFS / FVOCI) with “OCI; '
                    'reclassified to net income on sale”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Net income (no OCI '
                  'option)”?',
             'o': ['Revaluation of PP&E',
                   'Foreign-currency translation adjustments',
                   'Pension gains, losses and prior service cost',
                   'Changes in fair value of equity securities'],
             'a': 'D',
             'why': 'The book’s own table pairs Changes in fair value of '
                    'equity securities with “Net income (no OCI option)”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “OCI; reclassified '
                  'when the foreign operation is sold”?',
             'o': ['Effective part of cash-flow hedges',
                   'Pension gains, losses and prior service cost',
                   'Changes in fair value of equity securities',
                   'Foreign-currency translation adjustments'],
             'a': 'D',
             'why': 'The book’s own table pairs Foreign-currency translation '
                    'adjustments with “OCI; reclassified when the foreign '
                    'operation is sold”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “OCI; amortized into '
                  'net income later”?',
             'o': ['Revaluation of PP&E',
                   'Effective part of cash-flow hedges',
                   'Changes in fair value of equity securities',
                   'Pension gains, losses and prior service cost'],
             'a': 'D',
             'why': 'The book’s own table pairs Pension gains, losses and '
                    'prior service cost with “OCI; amortized into net income '
                    'later”.'},
            {'t': 'TF',
             'q': 'The book gives the IFRS of Unrealized gains and losses on '
                  'debt securities (AFS / FVOCI) as “OCI; reclassified on '
                  'sale”.',
             'a': 'T',
             'why': 'The book pairs Unrealized gains and losses on debt '
                    'securities (AFS / FVOCI) with “OCI; reclassified on '
                    'sale”.'},
            {'t': 'TF',
             'q': 'The book gives the IFRS of Changes in fair value of '
                  'equity securities as “Revaluation surplus in OCI; never '
                  'reclassified”.',
             'a': 'F',
             'why': 'The book pairs Changes in fair value of equity '
                    'securities with “Net income, or OCI by election (never '
                    'reclassified)”, not with “Revaluation surplus in OCI; '
                    'never reclassified”.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'An IFRS company revalues its land upward. How is the '
                  'increase reported?',
             'o': ['As a gain in profit or loss',
                   'In OCI, reclassified to profit when the land is sold',
                   'In OCI as a revaluation surplus, never reclassified to '
                   'profit',
                   'It is not recognized under IFRS'],
             'a': 'C',
             'why': 'IAS 16 revaluation increases go to OCI and are not '
                    'recycled. A is wrong: Revaluation increases go to OCI, '
                    'unless they reverse an earlier loss. B is wrong: '
                    'Revaluation surplus is never recycled under IFRS.',
             'src': 'P3-20'}]),
          ('panel',
           'Orontes Foods Inc., year ended December 31, 2025 — the extract '
           'for the question that follows',
           [['Orontes Foods Inc., year ended December 31, 2025', '2025'],
            ['Net sales', '42,000,000'],
            ['Cost of goods sold', '(27,300,000)'],
            ['Gross profit', '14,700,000'],
            ['Operating expenses', ''],
            ['Selling, general and administrative', '(7,237,000)'],
            ['Credit loss expense', '(63,000)'],
            ['Research and development', '(500,000)'],
            ['Impairment losses', '(2,724,000)'],
            ['Total operating expenses', '(10,524,000)'],
            ['Operating income', '4,176,000'],
            ['Other income and (expense)', ''],
            ['Interest expense', '(390,000)'],
            ['Interest and dividend income', '3,800'],
            ['Unrealized gains on securities', '4,000'],
            ['Equity-method income', '177,000'],
            ['Gain on sale of equipment', '3,000'],
            ['Loss on sale of receivables', '(15,000)'],
            ['Total other income and (expense)', '(217,200)'],
            ['Income before income taxes', '3,958,800'],
            ['Income tax expense', '(989,700)'],
            ['Net income', '2,969,100'],
            ['Earnings per share, basic and diluted', '$0.37'],
            ['Weighted-average shares outstanding', '8,099,726'],
            ['Other comprehensive income', ''],
            ['Unrealized loss on available-for-sale debt securities, net of '
             'tax of 375',
             '(1,125)'],
            ['Comprehensive income', '2,967,975']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. Which '
                  "amount is Orontes's income before income taxes for 2025 "
                  '(whole USD)?',
             'o': ['2,969,100', '3,781,800', '3,958,800', '4,176,000'],
             'a': 'C',
             'why': 'Operating income plus other income and expense. A is '
                    'wrong: This is after tax. B is wrong: This leaves out '
                    'equity-method income.',
             'src': 'P3-21'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'An IFRS company revalues its land upward. How is the increase '
           'reported?',
           ['As a gain in profit or loss',
            'In OCI, reclassified to profit when the land is sold',
            'In OCI as a revaluation surplus, never reclassified to profit',
            'It is not recognized under IFRS'],
           'C',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'IAS 16 revaluation increases go to OCI and are not recycled. A '
           'is wrong: Revaluation increases go to OCI, unless they reverse '
           'an earlier loss. B is wrong: Revaluation surplus is never '
           'recycled under IFRS.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['income from continuing operations',
             'الدخل من العمليات المستمرة'],
            ['earnings per share (EPS)', 'ربحية السهم'],
            ['strategic shift', 'تحول استراتيجي']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A glossary term and its translation are a pair the book '
                  'itself gives.',
             'a': 'T',
             'why': 'The term tables in each section are the book’s own.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'TF',
             'q': 'Writing a term in English is part of answering the '
                  'question, not an extra.',
             'a': 'T',
             'why': 'The exam marks the term, so the English word is the '
                    'answer.'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f4',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['income from continuing operations',
            'earnings per share (EPS)',
            'strategic shift'],
           'Some changes in value do not go through net income. U.S. GAAP '
           'sends them to other comprehensive income (OCI) until they are '
           'realized. Comprehensive income is net income plus OCI for the '
           'period.')]}
