# -*- coding: utf-8 -*-
"""Handout 16.1, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '16.1',
 'n': 1,
 'pages': 5,
 'title': 'What consolidated statements are',
 'sub': 'section 16.1 of the book',
 'covers': ['sec:16.1',
            'p:P16-01',
            'p:P16-02',
            'p:P16-03',
            'p:P16-04',
            'sc:P16-01',
            'p:P16-05',
            'p:P16-06',
            'term:consolidated financial statements',
            'term:intercompany transaction',
            'term:acquisition method'],
 'skills': [('read1', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['What consolidated statements are',
             'a figure to read · Item',
             'A parent owns 80% of a subsidiary. What part of the '
             "subsidiary's revenue appears in the consolidated income "
             'statement?'],
            ['The words this section uses precisely',
             'Investment · The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['',
                       35,
                       ' present a ',
                       11,
                       ' and its subsidiaries as a single economic entity. '
                       "They are prepared mainly for the parent's "
                       'shareholders and creditors, who need to see all the '
                       'resources the group controls and all its '
                       'obligations. A company consolidates another entity '
                       'when it has a ',
                       32,
                       ' in it.'],
             'bank': ['controlling financial interest',
                      'Consolidated financial statements',
                      'downstream sale',
                      'parent',
                      'joint venture'],
             'a': 'Consolidated financial statements · parent · controlling '
                  'financial interest',
             'one': True,
             'why': 'The book writes: “Consolidated financial statements '
                    'present a parent and its subsidiaries as a single '
                    'economic entity. They are prepared mainly for the '
                    "parent's shareholders and creditors, who need to see "
                    'all the resources the group controls and all its '
                    'obligations. A company consolidates another entity when '
                    'it has a controlling financial interest in it.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['Consolidation adds all of the ',
                       12,
                       "'s assets, liabilities, revenues and expenses to "
                       'the ',
                       11,
                       "'s, line by line, even when the parent owns less "
                       "than all of its shares. The part of a subsidiary's "
                       'equity that the parent does not own is the ',
                       25,
                       ' (NCI).'],
             'bank': ['noncontrolling interest',
                      'parent',
                      'subsidiary',
                      'downstream sale',
                      'joint venture'],
             'a': 'subsidiary · parent · noncontrolling interest',
             'one': True,
             'why': 'The book writes: “Consolidation adds all of the '
                    "subsidiary's assets, liabilities, revenues and expenses "
                    "to the parent's, line by line, even when the parent "
                    'owns less than all of its shares. The part of a '
                    "subsidiary's equity that the parent does not own is the "
                    'noncontrolling interest (NCI).”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['Net income and comprehensive income are split '
                       'between the ',
                       11,
                       ' and NCI on the face of the statements. These older '
                       'terms still appear in many MENA and French texts. '
                       'The exam uses ',
                       25,
                       ' (الحصص غير المسيطرة, participations ne donnant pas '
                       'le contrôle).'],
             'bank': ['downstream sale',
                      'joint venture',
                      'parent',
                      'noncontrolling interest'],
             'a': 'parent · noncontrolling interest',
             'one': True,
             'why': 'The book writes: “Net income and comprehensive income '
                    'are split between the parent and NCI on the face of the '
                    'statements. These older terms still appear in many MENA '
                    'and French texts. The exam uses noncontrolling interest '
                    '(الحصص غير المسيطرة, participations ne donnant pas le '
                    'contrôle).”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['consolidated financial statements', ''],
              ['intercompany transaction', ''],
              ['acquisition method', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', 'What consolidated statements are'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'The book gives the answer of Less: upstream unrealized '
                  'profit as “(25,000)”.',
             'a': 'T',
             'why': 'The book pairs Less: upstream unrealized profit with '
                    '“(25,000)”.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f1'),
          ('panel',
           'Item — the book’s own table',
           [['Item', 'Answer'],
            ['Less: upstream unrealized profit', '(25,000)'],
            ['Adjusted net income of Levant',
             '900,000 − 120,000 − 25,000 = 755,000'],
            ['NCI share', '20% × 755,000 = 151,000'],
            ['Less: dividends paid to NCI', '(20,000)'],
            ['NCI at December 31, 2027',
             '1,900,000 + 151,000 − 20,000 = 2,031,000']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which answer does the book give for Less: upstream '
                  'unrealized profit?',
             'o': ['20% × 755,000 = 151,000',
                   '900,000 − 120,000 − 25,000 = 755,000',
                   '(25,000)',
                   '(20,000)'],
             'a': 'C',
             'why': 'The book’s own table gives (25,000) as the answer of '
                    'Less: upstream unrealized profit.'},
            {'t': 'MCQ',
             'q': 'Which answer does the book give for Adjusted net income '
                  'of Levant?',
             'o': ['(25,000)',
                   '1,900,000 + 151,000 − 20,000 = 2,031,000',
                   '900,000 − 120,000 − 25,000 = 755,000',
                   '20% × 755,000 = 151,000'],
             'a': 'C',
             'why': 'The book’s own table gives 900,000 − 120,000 − 25,000 = '
                    '755,000 as the answer of Adjusted net income of '
                    'Levant.'},
            {'t': 'MCQ',
             'q': 'Which answer does the book give for NCI share?',
             'o': ['(20,000)',
                   '900,000 − 120,000 − 25,000 = 755,000',
                   '(25,000)',
                   '20% × 755,000 = 151,000'],
             'a': 'D',
             'why': 'The book’s own table gives 20% × 755,000 = 151,000 as '
                    'the answer of NCI share.'},
            {'t': 'MCQ',
             'q': 'Which answer does the book give for Less: dividends paid '
                  'to NCI?',
             'o': ['(20,000)',
                   '(25,000)',
                   '20% × 755,000 = 151,000',
                   '900,000 − 120,000 − 25,000 = 755,000'],
             'a': 'A',
             'why': 'The book’s own table gives (20,000) as the answer of '
                    'Less: dividends paid to NCI.'},
            {'t': 'TF',
             'q': 'The book gives the answer of Less: upstream unrealized '
                  'profit as “(25,000)”.',
             'a': 'T',
             'why': 'The book pairs Less: upstream unrealized profit with '
                    '“(25,000)”.'},
            {'t': 'TF',
             'q': 'The book gives the answer of Adjusted net income of '
                  'Levant as “20% × 755,000 = 151,000”.',
             'a': 'F',
             'why': 'The book pairs Adjusted net income of Levant with '
                    '“900,000 − 120,000 − 25,000 = 755,000”, not with “20% × '
                    '755,000 = 151,000”.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'A parent owns 80% of a subsidiary. What part of the '
                  "subsidiary's revenue appears in the consolidated income "
                  'statement?',
             'o': ['80%',
                   '20%',
                   "None; only the parent's share of net income",
                   '100%'],
             'a': 'D',
             'why': "Consolidation adds all the subsidiary's items; NCI is "
                    'shown separately. A is wrong: Adding only 80% is '
                    'proportionate consolidation. B is wrong: 20% is the NCI '
                    'share, not what is consolidated.',
             'src': 'P16-01'},
            {'t': 'MCQ',
             'q': 'How is consolidated net income presented under U.S. GAAP?',
             'o': ["Only the parent's share is shown",
                   "NCI's share is shown as an expense",
                   'In total, then split between the parent and NCI on the '
                   'face',
                   "NCI's share is shown only in the notes"],
             'a': 'C',
             'why': 'Both amounts are attributed on the face of the '
                    "statement. A is wrong: The total includes NCI's share. "
                    "B is wrong: NCI's share is an attribution, not an "
                    'expense.',
             'src': 'P16-02'},
            {'t': 'MCQ',
             'q': 'A parent pays $5,000,000 for 70% of a company. NCI is '
                  'worth $2,000,000, and net assets at fair value are '
                  '$6,500,000. What is goodwill under U.S. GAAP?',
             'o': ['$0', '$450,000', '$500,000', '$1,500,000'],
             'a': 'C',
             'why': 'Price + NCI fair value − net assets. A is wrong: '
                    'Goodwill arises because the total exceeds net assets. B '
                    'is wrong: This measures NCI at 30% of net assets '
                    '(partial goodwill).',
             'src': 'P16-03'},
            {'t': 'MCQ',
             'q': 'After an acquisition, the subsidiary has losses and NCI '
                  'would become negative. Under U.S. GAAP:',
             'o': ['losses are still attributed to NCI, even if NCI becomes '
                   'negative',
                   'all losses go to the parent once NCI reaches zero',
                   'NCI is reclassified as a liability',
                   'the parent stops consolidating'],
             'a': 'A',
             'why': 'ASC 810 attributes losses to NCI without a floor. B is '
                    'wrong: This was the old practice before FAS 160. C is '
                    'wrong: NCI stays in equity.',
             'src': 'P16-04'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           "A parent owns 80% of a subsidiary. What part of the subsidiary's "
           'revenue appears in the consolidated income statement?',
           ['80%',
            '20%',
            "None; only the parent's share of net income",
            '100%'],
           'D',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           "Consolidation adds all the subsidiary's items; NCI is shown "
           'separately. A is wrong: Adding only 80% is proportionate '
           'consolidation. B is wrong: 20% is the NCI share, not what is '
           'consolidated.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Investment — the book’s own table',
           [['Investment', 'Category'],
            ['Tadmor Retail (75%)', ''],
            ['Supplier (30%, significant influence)', ''],
            ['Listed food company (8%)', ''],
            ['Cold-storage SPV that Barada directs and guarantees (VIE)',
             '']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['consolidated financial statements', 'القوائم المالية الموحدة'],
            ['intercompany transaction', 'المعاملة داخل المجموعة'],
            ['acquisition method', 'طريقة الاستحواذ']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A glossary term and its translation are a pair the book '
                  'itself gives.',
             'a': 'T',
             'why': 'The term tables in each section are the book’s own.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which feature suggests that an entity is a VIE?',
             'o': ['It has many shareholders',
                   'Its equity at risk is too small to finance its '
                   'activities without extra support',
                   'It pays dividends',
                   'Its shares are listed'],
             'a': 'B',
             'why': 'Insufficient equity at risk is a VIE characteristic. A '
                    'is wrong: The number of owners is not a VIE test. C is '
                    'wrong: Dividends are not a VIE test.',
             'src': 'P16-05'},
            {'t': 'MCQ',
             'q': 'A bank lends to a VIE and bears large losses if it fails, '
                  'but has no power over its activities. The bank:',
             'o': ['is the primary beneficiary because it bears the losses',
                   'must use the equity method',
                   'is not the primary beneficiary',
                   'must use proportionate consolidation'],
             'a': 'C',
             'why': 'Both power and economics are required. A is wrong: '
                    'Economics alone are not enough. B is wrong: A lender '
                    'does not use the equity method.',
             'src': 'P16-06'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f1',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['consolidated financial statements',
            'intercompany transaction',
            'acquisition method'],
           'Consolidated financial statements present a parent and its '
           'subsidiaries as a single economic entity. They are prepared '
           "mainly for the parent's shareholders and creditors, who need to "
           'see all the resources the group controls and all its '
           'obligations.')]}
