# -*- coding: utf-8 -*-
"""Handout 16.1, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '16.1',
 'n': 1,
 'pages': 5,
 'title': 'What consolidated statements are',
 'sub': 'section 16.1 of the book',
 'covers': ['sec:16.1',
            'p:P16-01',
            'p:P16-08',
            'p:P16-09',
            'p:P16-11',
            'sc:P16-11',
            'p:P16-12',
            'p:P16-16',
            'term:consolidated financial statements',
            'term:intercompany transaction',
            'term:acquisition method'],
 'skills': [('read1', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['What consolidated statements are',
             'a figure to read · Item · Suppose: Levant items, 2027 (whole '
             'USD)',
             'Which of these did this cycle settle?'],
            ['The words this section uses precisely',
             'a figure to read · Investment · The English the exam uses, and '
             'what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['A company consolidates another entity when it has a ',
                       32,
                       ' in it. Consolidation adds all of the ',
                       12,
                       "'s assets, liabilities, revenues and expenses to "
                       'the ',
                       11,
                       "'s, line by line, even when the parent owns less "
                       'than all of its shares.'],
             'bank': ['parent',
                      'controlling financial interest',
                      'downstream sale',
                      'subsidiary',
                      'joint venture'],
             'a': 'controlling financial interest · subsidiary · parent',
             'one': True,
             'why': 'The book writes: “A company consolidates another entity '
                    'when it has a controlling financial interest in it. '
                    "Consolidation adds all of the subsidiary's assets, "
                    "liabilities, revenues and expenses to the parent's, "
                    'line by line, even when the parent owns less than all '
                    'of its shares.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['The part of a ',
                       12,
                       "'s equity that the ",
                       11,
                       ' does not own is the ',
                       25,
                       ' (NCI). It is shown within consolidated equity, '
                       "separately from the parent's equity."],
             'bank': ['noncontrolling interest',
                      'parent',
                      'subsidiary',
                      'downstream sale',
                      'joint venture'],
             'a': 'subsidiary · parent · noncontrolling interest',
             'one': True,
             'why': "The book writes: “The part of a subsidiary's equity "
                    'that the parent does not own is the noncontrolling '
                    'interest (NCI). It is shown within consolidated equity, '
                    "separately from the parent's equity.”"},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['Net income and comprehensive income are split '
                       'between the ',
                       11,
                       ' and NCI on the face of the statements. These older '
                       'terms still appear in many MENA and French texts. '
                       'The exam uses ',
                       25,
                       ' (الحصص غير المسيطرة, participations ne donnant pas '
                       'le contrôle).'],
             'bank': ['downstream sale',
                      'joint venture',
                      'parent',
                      'noncontrolling interest'],
             'a': 'parent · noncontrolling interest',
             'one': True,
             'why': 'The book writes: “Net income and comprehensive income '
                    'are split between the parent and NCI on the face of the '
                    'statements. These older terms still appear in many MENA '
                    'and French texts. The exam uses noncontrolling interest '
                    '(الحصص غير المسيطرة, participations ne donnant pas le '
                    'contrôle).”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['consolidated financial statements', ''],
              ['intercompany transaction', ''],
              ['acquisition method', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', 'What consolidated statements are'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f1'),
          ('panel',
           'Item — the book’s own table',
           [['Item', 'Answer'],
            ['Less: upstream unrealized profit', '(25,000)'],
            ['Adjusted net income of Levant',
             '900,000 − 120,000 − 25,000 = 755,000'],
            ['NCI share', '20% × 755,000 = 151,000'],
            ['Less: dividends paid to NCI', '(20,000)'],
            ['NCI at December 31, 2027',
             '1,900,000 + 151,000 − 20,000 = 2,031,000']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which part of this chapter is section 16.1?',
             'o': ['IFRS differences and what is changing',
                   'Two control models: VIE first, then votes',
                   'What consolidated statements are',
                   'Eliminating intercompany balances and transactions'],
             'a': 'C',
             'why': 'The book numbers “What consolidated statements are” as '
                    'section 16.1.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'A parent owns 80% of a subsidiary. What part of the '
                  "subsidiary's revenue appears in the consolidated income "
                  'statement?',
             'o': ['80%',
                   '20%',
                   "None; only the parent's share of net income",
                   '100%'],
             'a': 'D',
             'why': "Consolidation adds all the subsidiary's items; NCI is "
                    'shown separately. A is wrong: Adding only 80% is '
                    'proportionate consolidation. B is wrong: 20% is the NCI '
                    'share, not what is consolidated.',
             'src': 'P16-01'},
            {'t': 'MCQ',
             'q': 'Two companies each hold 50% of a joint venture and share '
                  'control. Under U.S. GAAP, each uses:',
             'o': ['the equity method',
                   'proportionate consolidation',
                   'full consolidation',
                   'fair value'],
             'a': 'A',
             'why': 'Joint ventures use the equity method. B is wrong: '
                    'Proportionate consolidation is generally not allowed. C '
                    'is wrong: Neither party controls alone.',
             'src': 'P16-08'},
            {'t': 'MCQ',
             'q': 'In which case does U.S. GAAP allow proportionate '
                  'consolidation?',
             'o': ['A 50% joint venture in food distribution',
                   'A 30% associate',
                   'An undivided interest in an oil and gas property',
                   'An 80% subsidiary'],
             'a': 'C',
             'why': 'Only limited industry practice allows it. A is wrong: '
                    'Joint ventures use the equity method. B is wrong: An '
                    'associate uses the equity method.',
             'src': 'P16-09'}]),
          ('panel',
           'Suppose: Levant items, 2027 (whole USD) — the extract for the '
           'question that follows',
           [['Suppose: Levant items, 2027 (whole USD)',
             'Eliminate',
             'Result',
             'Who bears it'],
            ['Intercompany sales and cost of sales',
             'Remove 750,000 of sales and cost of sales',
             'Revenue and expenses fall; no profit effect',
             '—'],
            ['Downstream unrealized profit (30% unsold)',
             '60,000 from inventory and profit',
             "Inventory at the group's cost",
             'Orontes'],
            ['Upstream unrealized profit (40% unsold)',
             '25,000 from inventory and profit',
             "Inventory at the group's cost",
             'Orontes 20,000, NCI 5,000'],
            ['Intercompany receivable and payable',
             '120,000 from both',
             'The group cannot owe itself',
             '—'],
            ['Truck sold for 90,000 (carrying 60,000)',
             'Gain 30,000; extra depreciation 6,000 a year',
             'Truck back to its original cost basis',
             'Orontes'],
            ['Loan of 1,000,000 at 6%',
             'Loan and interest of 60,000',
             'No debt or interest inside the group',
             '—'],
            ['Dividend of 100,000',
             "Orontes's dividend income 80,000",
             'NCI falls by 20,000',
             'NCI']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. How '
                  'much intercompany sales revenue is removed in '
                  'consolidation (whole USD)?',
             'o': ['0', '85,000', '500,000', '750,000'],
             'a': 'D',
             'why': 'Both downstream and upstream sales are removed in full. '
                    'A is wrong: Intercompany sales must be removed. B is '
                    'wrong: This is only the unrealized profit.',
             'src': 'P16-11'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Which of these did this cycle settle?',
           ['the rule and where it comes from',
            'nothing in particular',
            'only the vocabulary',
            'only the arithmetic'],
           'A',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'Every cycle settles one rule and shows where it comes from.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('fig', 'f1b'),
          ('panel',
           'Investment — the book’s own table',
           [['Investment', 'Category'],
            ['Tadmor Retail (75%)', ''],
            ['Supplier (30%, significant influence)', ''],
            ['Listed food company (8%)', ''],
            ['Cold-storage SPV that Barada directs and guarantees (VIE)',
             '']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['consolidated financial statements', 'القوائم المالية الموحدة'],
            ['intercompany transaction', 'المعاملة داخل المجموعة'],
            ['acquisition method', 'طريقة الاستحواذ']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A glossary term and its translation are a pair the book '
                  'itself gives.',
             'a': 'T',
             'why': 'The term tables in each section are the book’s own.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Under IFRS 11, how does a party account for a joint '
                  'operation?',
             'o': ['It uses the equity method',
                   'It recognizes its own share of the assets, liabilities, '
                   'revenues and expenses',
                   'It fully consolidates',
                   'It measures the interest at fair value'],
             'a': 'B',
             'why': 'Joint operators account for their rights and '
                    'obligations directly. A is wrong: The equity method is '
                    'for joint ventures. C is wrong: No single party '
                    'controls it.',
             'src': 'P16-16'},
            {'t': 'MCQ',
             'q': 'Under U.S. GAAP, which party must reassess whether it is '
                  "a VIE's primary beneficiary every reporting period?",
             'o': ['Every party with a variable interest',
                   'Only the largest lender',
                   'Only the equity holders',
                   'No one; it is decided once'],
             'a': 'A',
             'why': 'The primary beneficiary assessment is continuous. B is '
                    'wrong: All variable-interest holders reassess. C is '
                    'wrong: Other variable-interest holders reassess too.',
             'src': 'P16-18'},
            {'t': 'MATCH',
             'q': 'Write the letter of the matching answer beside each item. '
                  'Every one is used once.',
             'left': ['Less: upstream unrealized profit',
                      'Adjusted net income of Levant',
                      'NCI share',
                      'Less: dividends paid to NCI',
                      'NCI at December 31, 2027'],
             'right': ['(25,000)',
                       '20% × 755,000 = 151,000',
                       '(20,000)',
                       '1,900,000 + 151,000 − 20,000 = 2,031,000',
                       '900,000 − 120,000 − 25,000 = 755,000'],
             'a': ['A', 'E', 'B', 'C', 'D'],
             'whys': ['', '', '', '', '']}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. What '
                  'happens to the truck gain in the 2027 consolidated '
                  'statements?',
             'o': ['The gain stays because it was a real sale',
                   'The 30,000 gain is removed, and 6,000 of extra '
                   'depreciation is reversed',
                   'Only 80% of the gain is removed',
                   'The gain moves to OCI'],
             'a': 'B',
             'why': 'The truck returns to its original cost basis for the '
                    'group. A is wrong: A sale inside the group is not a '
                    'real sale. C is wrong: Intercompany gains are removed '
                    'in full.',
             'src': 'P16-12'},
            {'t': 'MCQ',
             'q': 'The extract for this question is printed with it. How '
                  'much intercompany sales revenue is removed in '
                  'consolidation (whole USD)?',
             'o': ['0', '85,000', '500,000', '750,000'],
             'a': 'D',
             'why': 'Both downstream and upstream sales are removed in full. '
                    'A is wrong: Intercompany sales must be removed. B is '
                    'wrong: This is only the unrealized profit.',
             'src': 'P16-11'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f1',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['consolidated financial statements',
            'intercompany transaction',
            'acquisition method'],
           'Consolidated financial statements present a parent and its '
           'subsidiaries as a single economic entity. They are prepared '
           "mainly for the parent's shareholders and creditors, who need to "
           'see all the resources the group controls and all its '
           'obligations.')]}
