# -*- coding: utf-8 -*-
"""Handout 16.2, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '16.2',
 'n': 2,
 'pages': 6,
 'title': 'Two control models: VIE first, then votes',
 'sub': 'section 16.2 of the book',
 'covers': ['sec:16.2',
            'p:P16-07',
            'p:P16-08',
            'p:P16-09',
            'p:P16-10',
            'sc:P16-07',
            'p:P16-11',
            'p:P16-12',
            'term:parent',
            'term:unrealized profit',
            'term:goodwill'],
 'skills': [('read2', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['Two control models: VIE first, then votes',
             'a figure to read · Suppose: Orontes Cold-Chain Logistics SPV, '
             '2027',
             'A company holds 60% of the votes, but a 40% owner must approve '
             'the annual budget and key hires. Under the voting model:'],
            ['The words this section uses precisely',
             'Investment · The English the exam uses, and what it translates '
             '· Suppose: Levant items, 2027 (whole USD)',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['GAAP has two ways to ',
                       11,
                       ' control, and they are applied in order. First, the '
                       'company asks whether the other entity is a ',
                       11,
                       ' interest entity (VIE). An entity is a VIE if its '
                       'equity at risk is too small to finance its ',
                       12,
                       ', or if its equity holders do not have the power to '
                       'direct it or do not bear its losses and returns.'],
             'bank': ['subsidiary',
                      'variable',
                      'activities',
                      'joint venture',
                      'identify'],
             'a': 'identify · variable · activities',
             'one': True,
             'why': 'The book writes: “GAAP has two ways to identify '
                    'control, and they are applied in order. First, the '
                    'company asks whether the other entity is a variable '
                    'interest entity (VIE). An entity is a VIE if its equity '
                    'at risk is too small to finance its activities, or if '
                    'its equity holders do not have the power to direct it '
                    'or do not bear its losses and returns.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['A company that holds more than 50% of the votes '
                       'generally controls the entity, unless other owners '
                       'have ',
                       13,
                       ' ',
                       15,
                       ' rights, such as the right to approve budgets. '
                       'Decision chart: test the VIE model first, then the '
                       'voting interest model. Suppose a logistics ',
                       14,
                       ' owns all the shares of Orontes Cold-Chain Logistics '
                       'SPV.'],
             'bank': ['substantive',
                      'participating',
                      'joint venture',
                      'subsidiary',
                      'entrepreneur'],
             'a': 'substantive · participating · entrepreneur',
             'one': True,
             'why': 'The book writes: “A company that holds more than 50% of '
                    'the votes generally controls the entity, unless other '
                    'owners have substantive participating rights, such as '
                    'the right to approve budgets. Decision chart: test the '
                    'VIE model first, then the voting interest model. '
                    'Suppose a logistics entrepreneur owns all the shares of '
                    'Orontes Cold-Chain Logistics SPV.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['Orontes has the power and bears the losses through '
                       'its ',
                       11,
                       ', so it is the primary ',
                       13,
                       '. Orontes ',
                       14,
                       ' the SPV although it owns no shares. Test the VIE '
                       'model before counting votes.'],
             'bank': ['subsidiary',
                      'beneficiary',
                      'guarantee',
                      'consolidates',
                      'joint venture'],
             'a': 'guarantee · beneficiary · consolidates',
             'one': True,
             'why': 'The book writes: “Orontes has the power and bears the '
                    'losses through its guarantee, so it is the primary '
                    'beneficiary. Orontes consolidates the SPV although it '
                    'owns no shares. Test the VIE model before counting '
                    'votes.”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['parent', ''],
              ['unrealized profit', ''],
              ['goodwill', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', 'Two control models: VIE first, then votes'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f2'),
          ('panel',
           'Suppose: Orontes Cold-Chain Logistics SPV, 2027 — the book’s own '
           'table',
           [['Suppose: Orontes Cold-Chain Logistics SPV, 2027',
             'Facts (whole USD)',
             'Conclusion'],
            ['Is equity at risk enough to finance the activities?',
             'No: third-party equity is 100,000, only 1% of total funding',
             'Suggests a VIE'],
            ['Do the equity holders direct the key activities?',
             'No: Orontes decides routes and customers',
             'VIE'],
            ['Who absorbs losses?',
             'Orontes guarantees the 9,900,000 of debt',
             'Orontes'],
            ['Primary beneficiary?',
             'Orontes has both power and exposure to significant losses',
             'Orontes consolidates'],
            ['NCI in consolidation',
             "The third party's equity of 100,000",
             'Shown as NCI']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which conclusion does the book give for Is equity at risk '
                  'enough to finance the activities??',
             'o': ['Orontes consolidates',
                   'Shown as NCI',
                   'Suggests a VIE',
                   'Orontes'],
             'a': 'C',
             'why': 'The book’s own table gives Suggests a VIE as the '
                    'conclusion of Is equity at risk enough to finance the '
                    'activities?.'},
            {'t': 'MCQ',
             'q': 'Which conclusion does the book give for Do the equity '
                  'holders direct the key activities??',
             'o': ['Shown as NCI', 'VIE', 'Orontes', 'Suggests a VIE'],
             'a': 'B',
             'why': 'The book’s own table gives VIE as the conclusion of Do '
                    'the equity holders direct the key activities?.'},
            {'t': 'MCQ',
             'q': 'Which conclusion does the book give for Who absorbs '
                  'losses??',
             'o': ['Shown as NCI', 'Orontes', 'Suggests a VIE', 'VIE'],
             'a': 'B',
             'why': 'The book’s own table gives Orontes as the conclusion of '
                    'Who absorbs losses?.'},
            {'t': 'MCQ',
             'q': 'Which conclusion does the book give for Primary '
                  'beneficiary??',
             'o': ['Orontes consolidates',
                   'Suggests a VIE',
                   'Shown as NCI',
                   'Orontes'],
             'a': 'A',
             'why': 'The book’s own table gives Orontes consolidates as the '
                    'conclusion of Primary beneficiary?.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company holds 60% of the votes, but a 40% owner must '
                  'approve the annual budget and key hires. Under the voting '
                  'model:',
             'o': ['the 60% holder controls',
                   'the 40% owner controls',
                   'both consolidate',
                   'the 60% holder does not have control, because the other '
                   'owner has substantive participating rights'],
             'a': 'D',
             'why': 'Substantive participating rights overcome majority '
                    'control. A is wrong: Votes alone do not decide when '
                    'others can block key decisions. B is wrong: Blocking '
                    'rights do not give the 40% owner control.',
             'src': 'P16-07'},
            {'t': 'MCQ',
             'q': 'Two companies each hold 50% of a joint venture and share '
                  'control. Under U.S. GAAP, each uses:',
             'o': ['the equity method',
                   'proportionate consolidation',
                   'full consolidation',
                   'fair value'],
             'a': 'A',
             'why': 'Joint ventures use the equity method. B is wrong: '
                    'Proportionate consolidation is generally not allowed. C '
                    'is wrong: Neither party controls alone.',
             'src': 'P16-08'},
            {'t': 'MCQ',
             'q': 'In which case does U.S. GAAP allow proportionate '
                  'consolidation?',
             'o': ['A 50% joint venture in food distribution',
                   'A 30% associate',
                   'An undivided interest in an oil and gas property',
                   'An 80% subsidiary'],
             'a': 'C',
             'why': 'Only limited industry practice allows it. A is wrong: '
                    'Joint ventures use the equity method. B is wrong: An '
                    'associate uses the equity method.',
             'src': 'P16-09'},
            {'t': 'MCQ',
             'q': "Under the equity method, the investor's investment "
                  'account increases by:',
             'o': ["all of the investee's net income",
                   'dividends received',
                   "the investee's revenue",
                   "its share of the investee's net income"],
             'a': 'D',
             'why': 'The investor records its share of income; dividends '
                    "reduce the investment. A is wrong: Only the investor's "
                    'share is recorded. B is wrong: Dividends reduce the '
                    'investment.',
             'src': 'P16-10'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'A company holds 60% of the votes, but a 40% owner must approve '
           'the annual budget and key hires. Under the voting model:',
           ['the 60% holder controls',
            'the 40% owner controls',
            'both consolidate',
            'the 60% holder does not have control, because the other owner '
            'has substantive participating rights'],
           'D',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'Substantive participating rights overcome majority control. A is '
           'wrong: Votes alone do not decide when others can block key '
           'decisions. B is wrong: Blocking rights do not give the 40% owner '
           'control.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Investment — the book’s own table',
           [['Investment', 'Category'],
            ['Tadmor Retail (75%)', 'Full consolidation'],
            ['Supplier (30%, significant influence)', 'Equity method'],
            ['Listed food company (8%)', 'Fair value through net income'],
            ['Cold-storage SPV that Barada directs and guarantees (VIE)',
             'Full consolidation']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['parent', 'المنشأة الأم'],
            ['unrealized profit', 'الربح غير المحقق'],
            ['goodwill', 'الشهرة']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which category does the book give for Tadmor Retail '
                  '(75%)?',
             'o': ['Full consolidation',
                   'Equity method',
                   'Fair value through net income'],
             'a': 'A',
             'why': 'The book’s own table gives Full consolidation as the '
                    'category of Tadmor Retail (75%).'},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Supplier (30%, '
                  'significant influence)?',
             'o': ['Full consolidation',
                   'Equity method',
                   'Fair value through net income'],
             'a': 'B',
             'why': 'The book’s own table gives Equity method as the '
                    'category of Supplier (30%, significant influence).'},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Listed food company '
                  '(8%)?',
             'o': ['Equity method',
                   'Fair value through net income',
                   'Full consolidation'],
             'a': 'B',
             'why': 'The book’s own table gives Fair value through net '
                    'income as the category of Listed food company (8%).'}]),
          ('move', 'APPLY', ''),
          ('panel',
           'Suppose: Levant items, 2027 (whole USD) — the extract for the '
           'question that follows',
           [['Suppose: Levant items, 2027 (whole USD)',
             'Eliminate',
             'Result',
             'Who bears it'],
            ['Intercompany sales and cost of sales',
             'Remove 750,000 of sales and cost of sales',
             'Revenue and expenses fall; no profit effect',
             '—'],
            ['Downstream unrealized profit (30% unsold)',
             '60,000 from inventory and profit',
             "Inventory at the group's cost",
             'Orontes'],
            ['Upstream unrealized profit (40% unsold)',
             '25,000 from inventory and profit',
             "Inventory at the group's cost",
             'Orontes 20,000, NCI 5,000'],
            ['Intercompany receivable and payable',
             '120,000 from both',
             'The group cannot owe itself',
             '—'],
            ['Truck sold for 90,000 (carrying 60,000)',
             'Gain 30,000; extra depreciation 6,000 a year',
             'Truck back to its original cost basis',
             'Orontes'],
            ['Loan of 1,000,000 at 6%',
             'Loan and interest of 60,000',
             'No debt or interest inside the group',
             '—'],
            ['Dividend of 100,000',
             "Orontes's dividend income 80,000",
             'NCI falls by 20,000',
             'NCI']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. How '
                  'much intercompany sales revenue is removed in '
                  'consolidation (whole USD)?',
             'o': ['0', '85,000', '500,000', '750,000'],
             'a': 'D',
             'why': 'Both downstream and upstream sales are removed in full. '
                    'A is wrong: Intercompany sales must be removed. B is '
                    'wrong: This is only the unrealized profit.',
             'src': 'P16-11'},
            {'t': 'MCQ',
             'q': 'The extract for this question is printed with it. What '
                  'happens to the truck gain in the 2027 consolidated '
                  'statements?',
             'o': ['The gain stays because it was a real sale',
                   'The 30,000 gain is removed, and 6,000 of extra '
                   'depreciation is reversed',
                   'Only 80% of the gain is removed',
                   'The gain moves to OCI'],
             'a': 'B',
             'why': 'The truck returns to its original cost basis for the '
                    'group. A is wrong: A sale inside the group is not a '
                    'real sale. C is wrong: Intercompany gains are removed '
                    'in full.',
             'src': 'P16-12'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f2',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['parent', 'unrealized profit', 'goodwill'],
           'U.S. GAAP has two ways to identify control, and they are applied '
           'in order. First, the company asks whether the other entity is a '
           'variable interest entity (VIE). An entity is a VIE if its equity '
           'at risk is too small to finance its activities, or if its equity '
           'holders do not have the power to direct it or do not bear its '
           'losses and returns.')]}
