# -*- coding: utf-8 -*-
"""Handout 16.4, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '16.4',
 'n': 4,
 'pages': 4,
 'title': 'The acquisition: goodwill and noncontrolling interest',
 'sub': 'section 16.4 of the book',
 'covers': ['sec:16.4',
            'p:P16-04',
            'term:variable interest entity',
            'term:proportionate consolidation',
            'term:upstream sale'],
 'skills': [('read4', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['The acquisition: goodwill and noncontrolling interest',
             'a figure to read · Consolidation worksheet, January 1, 2027 '
             '(whole',
             'Which of these did this cycle settle?'],
            ['The words this section uses precisely',
             'The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['When a company gains control of a business, it uses '
                       'the ',
                       20,
                       '. It measures the ',
                       12,
                       "'s identifiable assets and liabilities at fair "
                       'value, and it measures NCI at fair value too. ',
                       11,
                       ' is the price paid plus the fair value of NCI, minus '
                       'the fair value of the net assets.'],
             'bank': ['subsidiary',
                      'Goodwill',
                      'upstream sale',
                      'acquisition method',
                      'intercompany transaction'],
             'a': 'acquisition method · subsidiary · Goodwill',
             'one': True,
             'why': 'The book writes: “When a company gains control of a '
                    'business, it uses the acquisition method. It measures '
                    "the subsidiary's identifiable assets and liabilities at "
                    'fair value, and it measures NCI at fair value too. '
                    'Goodwill is the price paid plus the fair value of NCI, '
                    'minus the fair value of the net assets.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['After the ',
                       13,
                       ', if Orontes buys or sells some Levant shares but '
                       'keeps control, the change is an equity ',
                       13,
                       ': no gain or loss is recognized. If Orontes loses '
                       'control, it removes Levant from the ',
                       15,
                       ' and remeasures any interest it keeps at fair '
                       'value.'],
             'bank': ['consolidation',
                      'intercompany transaction',
                      'transaction',
                      'upstream sale',
                      'acquisition'],
             'a': 'acquisition · transaction · consolidation',
             'one': True,
             'why': 'The book writes: “After the acquisition, if Orontes '
                    'buys or sells some Levant shares but keeps control, the '
                    'change is an equity transaction: no gain or loss is '
                    'recognized. If Orontes loses control, it removes Levant '
                    'from the consolidation and remeasures any interest it '
                    'keeps at fair value.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap from the list. The list '
                  'holds more words than there are gaps.',
             'parts': ['The book’s own table “Consolidation worksheet, '
                       "January 1, 2027 (whole” settles these: for Levant's "
                       'equity (book value) it is ',
                       11,
                       ', for Property, plant and equipment (fair value '
                       'step-up) it is ',
                       11,
                       ' and for Goodwill it is ',
                       11,
                       '.'],
             'bank': ['1,400,000', '1,200,000', '9,900,000', '7,300,000'],
             'one': True,
             'a': '7,300,000 · 1,200,000 · 1,400,000',
             'why': 'From the book’s own table “Consolidation worksheet, '
                    'January 1, 2027 (whole”: The book’s own table '
                    '“Consolidation worksheet, January 1, 2027 (whole” '
                    "settles these: for Levant's equity (book value) it is "
                    '7,300,000 and for Property, plant and equipment (fair '
                    'value step-up) it is 1,200,000 and for Goodwill it is '
                    '1,400,000.'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['variable interest entity', ''],
              ['proportionate consolidation', ''],
              ['upstream sale', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle',
           'A',
           'The acquisition: goodwill and noncontrolling interest'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f4'),
          ('panel',
           'Consolidation worksheet, January 1, 2027 (whole — the book’s own '
           'table',
           [['Consolidation worksheet, January 1, 2027 (whole ',
             'Debit',
             'Credit'],
            ["Levant's equity (book value)", '7,300,000', ''],
            ['Property, plant and equipment (fair value step-up)',
             '1,200,000',
             ''],
            ['Goodwill', '1,400,000', ''],
            ["Investment in Levant (Orontes's books)", '', '8,000,000'],
            ['Noncontrolling interest (equity)', '', '1,900,000'],
            ['Totals', '9,900,000', '9,900,000']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which part of this chapter is section 16.1?',
             'o': ['IFRS differences and what is changing',
                   'Two control models: VIE first, then votes',
                   'What consolidated statements are',
                   'Eliminating intercompany balances and transactions'],
             'a': 'C',
             'why': 'The book numbers “What consolidated statements are” as '
                    'section 16.1.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'After an acquisition, the subsidiary has losses and NCI '
                  'would become negative. Under U.S. GAAP:',
             'o': ['losses are still attributed to NCI, even if NCI becomes '
                   'negative',
                   'all losses go to the parent once NCI reaches zero',
                   'NCI is reclassified as a liability',
                   'the parent stops consolidating'],
             'a': 'A',
             'why': 'ASC 810 attributes losses to NCI without a floor. B is '
                    'wrong: This was the old practice before FAS 160. C is '
                    'wrong: NCI stays in equity.',
             'src': 'P16-04'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Which of these did this cycle settle?',
           ['the rule and where it comes from',
            'nothing in particular',
            'only the vocabulary',
            'only the arithmetic'],
           'A',
           'redo the READ THE MODEL questions of cycle A.',
           'Every cycle settles one rule and shows where it comes from.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['variable interest entity', 'منشأة ذات حصص متغيرة'],
            ['proportionate consolidation', 'التوحيد التناسبي'],
            ['upstream sale', 'البيع من التابعة إلى الأم']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A glossary term and its translation are a pair the book '
                  'itself gives.',
             'a': 'T',
             'why': 'The term tables in each section are the book’s own.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MATCH',
             'q': 'Write the letter of the matching entry beside each one. '
                  'Every one is used once.',
             'left': ["Levant's equity (book value)",
                      'Property, plant and equipment (fair value step-up)',
                      'Goodwill',
                      'Totals'],
             'right': ['1,400,000', '7,300,000', '9,900,000', '1,200,000'],
             'a': ['B', 'D', 'A', 'C'],
             'whys': ['', '', '', '']}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f4',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['variable interest entity',
            'proportionate consolidation',
            'upstream sale'],
           'When a company gains control of a business, it uses the '
           "acquisition method. It measures the subsidiary's identifiable "
           'assets and liabilities at fair value, and it measures NCI at '
           'fair value too. Goodwill is the price paid plus the fair value '
           'of NCI, minus the fair value of the net assets.')]}
