# -*- coding: utf-8 -*-
"""Handout 16.5, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '16.5',
 'n': 5,
 'pages': 5,
 'title': 'Eliminating intercompany balances and transactions',
 'sub': 'section 16.5 of the book',
 'covers': ['sec:16.5', 'term:primary beneficiary', 'term:joint venture'],
 'skills': [('read5', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['Eliminating intercompany balances and transactions',
             'a figure to read · Suppose: NCI in Levant, 2027 (whole USD)',
             'Which of these did this cycle settle?'],
            ['The words this section uses precisely',
             'Suppose: Levant items, 2027 (whole USD) · The English the exam '
             'uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['Every ',
                       26,
                       ' is therefore eliminated in full, whatever the '
                       'percentage owned: sales and cost of sales, '
                       'receivables and payables, loans and interest, and '
                       'dividends. ',
                       19,
                       ' on goods still held inside the group is also '
                       'removed from inventory and income until the goods '
                       'are sold to outsiders.'],
             'bank': ['primary beneficiary',
                      'Unrealized profit',
                      'equity method',
                      'intercompany transaction'],
             'a': 'intercompany transaction · Unrealized profit',
             'one': True,
             'why': 'The book writes: “Every intercompany transaction is '
                    'therefore eliminated in full, whatever the percentage '
                    'owned: sales and cost of sales, receivables and '
                    'payables, loans and interest, and dividends. Unrealized '
                    'profit on goods still held inside the group is also '
                    'removed from inventory and income until the goods are '
                    'sold to outsiders.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['In a ',
                       17,
                       ' the ',
                       11,
                       ' earned the profit, so the whole elimination reduces '
                       "the parent's share. In an ",
                       15,
                       ' the ',
                       12,
                       ' earned it, so NCI bears its share. Downstream and '
                       'upstream sales between Orontes and Levant.'],
             'bank': ['unrealized profit',
                      'upstream sale',
                      'subsidiary',
                      'equity method',
                      'downstream sale',
                      'parent'],
             'a': 'downstream sale · parent · upstream sale · subsidiary',
             'one': True,
             'why': 'The book writes: “In a downstream sale the parent '
                    'earned the profit, so the whole elimination reduces the '
                    "parent's share. In an upstream sale the subsidiary "
                    'earned it, so NCI bears its share. Downstream and '
                    'upstream sales between Orontes and Levant.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['',
                       19,
                       ' on goods still held inside the group is also '
                       'removed from inventory and income until the goods '
                       'are sold to outsiders. In a ',
                       17,
                       ' the ',
                       11,
                       ' earned the profit, so the whole elimination reduces '
                       "the parent's share. In an ",
                       15,
                       ' the ',
                       12,
                       ' earned it, so NCI bears its share.'],
             'bank': ['primary beneficiary',
                      'Unrealized profit',
                      'upstream sale',
                      'subsidiary',
                      'equity method',
                      'downstream sale',
                      'parent'],
             'a': 'Unrealized profit · downstream sale · parent · upstream '
                  'sale · subsidiary',
             'one': True,
             'why': 'The book writes: “Unrealized profit on goods still held '
                    'inside the group is also removed from inventory and '
                    'income until the goods are sold to outsiders. In a '
                    'downstream sale the parent earned the profit, so the '
                    "whole elimination reduces the parent's share. In an "
                    'upstream sale the subsidiary earned it, so NCI bears '
                    'its share.”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['primary beneficiary', ''],
              ['joint venture', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle',
           'A',
           'Eliminating intercompany balances and transactions'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f5'),
          ('panel',
           'Suppose: NCI in Levant, 2027 (whole USD) — the book’s own table',
           [['Suppose: NCI in Levant, 2027 (whole USD)', 'Amount'],
            ['NCI at January 1, 2027 (fair value)', '1,900,000'],
            ["Levant's 2027 net income", '900,000'],
            ['Less: depreciation on the PP&E step-up (1,200,000 ÷ 10 years)',
             '(120,000)'],
            ['Less: upstream unrealized profit', '________'],
            ['Adjusted net income of Levant', '________'],
            ['NCI share (20%)', '________'],
            ['Less: dividends paid to NCI', '________'],
            ['NCI at December 31, 2027', '________']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which amount does the book give for NCI at January 1, '
                  '2027 (fair value)?',
             'o': ['1,900,000', '________', '(120,000)', '900,000'],
             'a': 'A',
             'why': 'The book’s own table gives 1,900,000 as the amount of '
                    'NCI at January 1, 2027 (fair value).'},
            {'t': 'MCQ',
             'q': "Which amount does the book give for Levant's 2027 net "
                  'income?',
             'o': ['________', '1,900,000', '900,000', '(120,000)'],
             'a': 'C',
             'why': 'The book’s own table gives 900,000 as the amount of '
                    "Levant's 2027 net income."},
            {'t': 'MCQ',
             'q': 'Which amount does the book give for Less: depreciation on '
                  'the PP&E step-up (1,200,000 ÷ 10 years)?',
             'o': ['________', '1,900,000', '900,000', '(120,000)'],
             'a': 'D',
             'why': 'The book’s own table gives (120,000) as the amount of '
                    'Less: depreciation on the PP&E step-up (1,200,000 ÷ 10 '
                    'years).'},
            {'t': 'MCQ',
             'q': 'Which amount does the book give for Less: upstream '
                  'unrealized profit?',
             'o': ['1,900,000', '900,000', '________', '(120,000)'],
             'a': 'C',
             'why': 'The book’s own table gives ________ as the amount of '
                    'Less: upstream unrealized profit.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'TF',
             'q': 'The rule you have just written is the book’s own rule.',
             'a': 'T',
             'why': 'Compare your sentence with the book’s wording in the '
                    'key.'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Which of these did this cycle settle?',
           ['the rule and where it comes from',
            'nothing in particular',
            'only the vocabulary',
            'only the arithmetic'],
           'A',
           'redo the READ THE MODEL questions of cycle A.',
           'Every cycle settles one rule and shows where it comes from.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Suppose: Levant items, 2027 (whole USD) — the book’s own table',
           [['Suppose: Levant items, 2027 (whole USD)',
             'Eliminate',
             'Result',
             'Who bears it'],
            ['Intercompany sales and cost of sales',
             'Remove 750,000 of sales and cost of sales',
             'Revenue and expenses fall; no profit effect',
             '—'],
            ['Downstream unrealized profit (30% unsold)',
             '60,000 from inventory and profit',
             "Inventory at the group's cost",
             'Orontes'],
            ['Upstream unrealized profit (40% unsold)',
             '25,000 from inventory and profit',
             "Inventory at the group's cost",
             'Orontes 20,000, NCI 5,000'],
            ['Intercompany receivable and payable',
             '120,000 from both',
             'The group cannot owe itself',
             '—'],
            ['Truck sold for 90,000 (carrying 60,000)',
             'Gain 30,000; extra depreciation 6,000 a year',
             'Truck back to its original cost basis',
             'Orontes'],
            ['Loan of 1,000,000 at 6%',
             'Loan and interest of 60,000',
             'No debt or interest inside the group',
             '—'],
            ['Dividend of 100,000',
             "Orontes's dividend income 80,000",
             'NCI falls by 20,000',
             'NCI']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['primary beneficiary', 'المستفيد الرئيسي'],
            ['joint venture', 'المشروع المشترك']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which eliminate does the book give for Intercompany sales '
                  'and cost of sales?',
             'o': ['60,000 from inventory and profit',
                   '25,000 from inventory and profit',
                   'Remove 750,000 of sales and cost of sales',
                   'Gain 30,000; extra depreciation 6,000 a year'],
             'a': 'C',
             'why': 'The book’s own table gives Remove 750,000 of sales and '
                    'cost of sales as the eliminate of Intercompany sales '
                    'and cost of sales.'},
            {'t': 'MCQ',
             'q': 'Which eliminate does the book give for Downstream '
                  'unrealized profit (30% unsold)?',
             'o': ["Orontes's dividend income 80,000",
                   'Loan and interest of 60,000',
                   '60,000 from inventory and profit',
                   '25,000 from inventory and profit'],
             'a': 'C',
             'why': 'The book’s own table gives 60,000 from inventory and '
                    'profit as the eliminate of Downstream unrealized profit '
                    '(30% unsold).'},
            {'t': 'MCQ',
             'q': 'Which eliminate does the book give for Upstream '
                  'unrealized profit (40% unsold)?',
             'o': ["Orontes's dividend income 80,000",
                   '25,000 from inventory and profit',
                   'Loan and interest of 60,000',
                   '60,000 from inventory and profit'],
             'a': 'B',
             'why': 'The book’s own table gives 25,000 from inventory and '
                    'profit as the eliminate of Upstream unrealized profit '
                    '(40% unsold).'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'TF',
             'q': 'Writing a term in English is part of answering the '
                  'question, not an extra.',
             'a': 'T',
             'why': 'The exam marks the term, so the English word is the '
                    'answer.'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f5',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['primary beneficiary', 'joint venture'],
           'A group cannot sell to itself, owe money to itself or earn '
           'income from itself. Every intercompany transaction is therefore '
           'eliminated in full, whatever the percentage owned: sales and '
           'cost of sales, receivables and payables, loans and interest, and '
           'dividends.')]}
