# -*- coding: utf-8 -*-
"""Handout 16.6, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '16.6',
 'n': 6,
 'pages': 6,
 'title': 'IFRS differences and what is changing',
 'sub': 'section 16.6 of the book',
 'covers': ['sec:16.6',
            'sc:SC16-3',
            'sc:SC16-4',
            'p:P16-06',
            'sc:SC16-1',
            'sc:SC16-2',
            'sc:SC16-1',
            'sc:SC16-2',
            'term:noncontrolling interest',
            'term:equity method'],
 'skills': [('read6', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['IFRS differences and what is changing',
             'a figure to read · Suppose: Barada Wholesale and Tadmor '
             'Retail, 202 · Suppose: Orontes Cold-Chain Logistics SPV, 2027',
             'What do consolidated financial statements present?'],
            ['The words this section uses precisely',
             'Topic · The English the exam uses, and what it translates · '
             'Method',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['IFRS 10 uses one control model: an ',
                       11,
                       ' ',
                       11,
                       ' an entity if it has power over it, ',
                       11,
                       ' to variable returns, and the ability to use its '
                       'power to affect those returns. There is no separate '
                       'VIE model, and an investor can have de facto control '
                       'with less than half of the votes.'],
             'bank': ['equity method',
                      'exposure',
                      'investor',
                      'unrealized profit',
                      'controls'],
             'a': 'investor · controls · exposure',
             'one': True,
             'why': 'The book writes: “IFRS 10 uses one control model: an '
                    'investor controls an entity if it has power over it, '
                    'exposure to variable returns, and the ability to use '
                    'its power to affect those returns. There is no separate '
                    'VIE model, and an investor can have de facto control '
                    'with less than half of the votes.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['Under IFRS 11, joint ventures use the ',
                       15,
                       ' and joint ',
                       12,
                       ' recognize their own share of assets and ',
                       13,
                       '. ASU 2025-03 changes how to identify the acquirer '
                       'when the acquired company is a VIE; it is not '
                       'testable before about January 2028.'],
             'bank': ['operations',
                      'unrealized profit',
                      'liabilities',
                      'equity method',
                      'variable interest entity'],
             'a': 'equity method · operations · liabilities',
             'one': True,
             'why': 'The book writes: “Under IFRS 11, joint ventures use the '
                    'equity method and joint operations recognize their own '
                    'share of assets and liabilities. ASU 2025-03 changes '
                    'how to identify the acquirer when the acquired company '
                    'is a VIE; it is not testable before about January '
                    '2028.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap from the list. The list '
                  'holds more words than there are gaps.',
             'parts': ['The book’s own table “Suppose: Barada Wholesale and '
                       'Tadmor Retail, 202” settles these: for Price paid '
                       'for 75% of Tadmor Retail LLC, January 1, 2028 it is ',
                       11,
                       ', for Fair value of the 25% noncontrolling interest '
                       'it is ',
                       11,
                       " and for Fair value of Tadmor's identifiable net "
                       'assets it is ',
                       11,
                       '.'],
             'bank': ['120', '190', '600', '700'],
             'one': True,
             'a': '600 · 190 · 700',
             'why': 'From the book’s own table “Suppose: Barada Wholesale '
                    'and Tadmor Retail, 202”: The book’s own table “Suppose: '
                    'Barada Wholesale and Tadmor Retail, 202” settles these: '
                    'for Price paid for 75% of Tadmor Retail LLC, January 1, '
                    '2028 it is 600 and for Fair value of the 25% '
                    'noncontrolling interest it is 190 and for Fair value of '
                    "Tadmor's identifiable net assets it is 700."}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['noncontrolling interest', ''],
              ['equity method', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', 'IFRS differences and what is changing'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f6'),
          ('panel',
           'Suppose: Barada Wholesale and Tadmor Retail, 202 — the book’s '
           'own table',
           [['Suppose: Barada Wholesale and Tadmor Retail, 202', 'Amount'],
            ['Price paid for 75% of Tadmor Retail LLC, January 1, 2028',
             '600'],
            ['Fair value of the 25% noncontrolling interest', '190'],
            ["Fair value of Tadmor's identifiable net assets", '700'],
            ['Barada sold goods to Tadmor: sales 200, margin 30%, 25% still '
             'held by Tadmor',
             ''],
            ['Tadmor sold goods to Barada: sales 160, margin 25%, 50% still '
             'held by Barada',
             ''],
            ['Tadmor owes Barada at December 31, 2028', '40'],
            ["Tadmor's 2028 net income (before any consolidation adjustment)",
             '120'],
            ['Dividends paid by Tadmor in 2028', '40'],
            ['M1',
             "Tadmor's assets are at fair value on its books, so there is no "
             'step-up to depreciate.'],
            ['M2',
             'Barada also holds 30% of a supplier (significant influence) '
             'and 8% of a listed food company.']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which amount does the book give for Price paid for 75% of '
                  'Tadmor Retail LLC, January 1, 2028?',
             'o': ['700', '600', '190', '120'],
             'a': 'B',
             'why': 'The book’s own table gives 600 as the amount of Price '
                    'paid for 75% of Tadmor Retail LLC, January 1, 2028.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Under U.S. GAAP, which test does a company apply first to '
                  'decide whether to consolidate an entity?',
             'o': ['Whether the entity is a variable interest entity',
                   'Whether it holds more than 50% of the votes',
                   'Whether it has significant influence',
                   'Whether the entity is profitable'],
             'a': 'A',
             'why': 'The VIE model comes before the voting model. B is '
                    'wrong: Votes are tested only if the entity is not a '
                    'VIE. C is wrong: Significant influence decides the '
                    'equity method, not consolidation.',
             'src': 'SC16-3'},
            {'t': 'MCQ',
             'q': 'A bank lends to a VIE and bears large losses if it fails, '
                  'but has no power over its activities. The bank:',
             'o': ['is the primary beneficiary because it bears the losses',
                   'must use the equity method',
                   'is not the primary beneficiary',
                   'must use proportionate consolidation'],
             'a': 'C',
             'why': 'Both power and economics are required. A is wrong: '
                    'Economics alone are not enough. B is wrong: A lender '
                    'does not use the equity method.',
             'src': 'P16-06'}]),
          ('panel',
           'Suppose: Orontes Cold-Chain Logistics SPV, 2027 — the extract '
           'for the question that follows',
           [['Suppose: Orontes Cold-Chain Logistics SPV, 2027',
             'Facts (whole USD)',
             'Conclusion'],
            ['Is equity at risk enough to finance the activities?',
             'No: third-party equity is 100,000, only 1% of total funding',
             'Suggests a VIE'],
            ['Do the equity holders direct the key activities?',
             'No: Orontes decides routes and customers',
             'VIE'],
            ['Who absorbs losses?',
             'Orontes guarantees the 9,900,000 of debt',
             'Orontes'],
            ['Primary beneficiary?',
             'Orontes has both power and exposure to significant losses',
             'Orontes consolidates'],
            ['NCI in consolidation',
             "The third party's equity of 100,000",
             'Shown as NCI']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. Why '
                  'does Orontes consolidate the cold-chain SPV?',
             'o': ['It owns more than 50% of the shares',
                   'It has both the power to direct the SPV and exposure to '
                   'its losses through the guarantee',
                   'It lends money to the SPV',
                   'The SPV is profitable'],
             'a': 'B',
             'why': 'Orontes is the primary beneficiary. A is wrong: Orontes '
                    'owns no shares. C is wrong: Economics alone are not '
                    'enough; power is also needed.',
             'src': 'SC16-4'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'What do consolidated financial statements present?',
           ["Only the parent's own assets and liabilities",
            "The parent's share of each subsidiary's assets",
            'A parent and its subsidiaries as a single economic entity',
            'All companies in which the parent holds any shares'],
           'C',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'Consolidation shows the group as one entity. A is wrong: That is '
           "the parent's separate statements. B is wrong: That is "
           'proportionate consolidation.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Topic — the book’s own table',
           [['Topic', 'U.S. GAAP (ASC 810, 805)', 'IFRS (IFRS 10, 3, 11)'],
            ['Control model',
             'Two: VIE model first, then voting interest',
             'One: power, variable returns and the link between them'],
            ['Control below 50% of votes',
             'Not through voting alone (unless a VIE)',
             'Possible: de facto control'],
            ['Measuring NCI',
             'Fair value (full goodwill)',
             'Fair value or share of net assets (partial goodwill), deal by '
             'deal'],
            ['Joint arrangements',
             'Joint ventures: equity method',
             'Joint ventures: equity method; joint operations: own share of '
             'assets and liabilities'],
            ['Group accounting policies',
             'No general uniformity rule',
             'Uniform policies required'],
            ["Investment-entity subsidiaries in a parent's statements",
             'Parent keeps their fair value accounting',
             'A non-investment-entity parent consolidates them']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['noncontrolling interest', 'الحصص غير المسيطرة'],
            ['equity method', 'طريقة حقوق الملكية']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which topic does the book pair with “Two: VIE model '
                  'first, then voting interest”?',
             'o': ['Control model',
                   "Investment-entity subsidiaries in a parent's statements",
                   'Group accounting policies',
                   'Joint arrangements'],
             'a': 'A',
             'why': 'The book’s own table pairs Control model with “Two: VIE '
                    'model first, then voting interest”.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Where does Orontes present the noncontrolling interest in '
                  'Levant?',
             'o': ['As a noncurrent liability',
                   "Between liabilities and equity, as 'minority interest'",
                   'Only in the notes',
                   "In consolidated equity, separately from the parent's "
                   'equity'],
             'a': 'D',
             'why': 'NCI is equity of the group. A is wrong: NCI is not an '
                    "obligation. B is wrong: The mezzanine 'minority "
                    "interest' line is an old practice.",
             'src': 'SC16-2'},
            {'t': 'MCQ',
             'q': 'What do consolidated financial statements present?',
             'o': ["Only the parent's own assets and liabilities",
                   "The parent's share of each subsidiary's assets",
                   'A parent and its subsidiaries as a single economic '
                   'entity',
                   'All companies in which the parent holds any shares'],
             'a': 'C',
             'why': 'Consolidation shows the group as one entity. A is '
                    "wrong: That is the parent's separate statements. B is "
                    'wrong: That is proportionate consolidation.',
             'src': 'SC16-1'},
            {'t': 'MCQ',
             'q': 'Orontes holds 30% of Jordan Glass and has significant '
                  'influence. Which method does it use?',
             'o': ['Full consolidation',
                   'Proportionate consolidation',
                   'Fair value through net income',
                   'The equity method'],
             'a': 'D',
             'why': 'Significant influence without control leads to the '
                    'equity method. A is wrong: Orontes does not control '
                    'Jordan Glass. B is wrong: Proportionate consolidation '
                    'is generally not allowed.',
             'src': 'SC16-5'},
            {'t': 'MCQ',
             'q': 'In 2028 Orontes buys another 10% of Levant from the NCI '
                  'holders and keeps control. It records:',
             'o': ['a gain or loss in net income',
                   'an equity transaction, with no gain or loss',
                   'new goodwill',
                   "a remeasurement of Levant's assets to fair value"],
             'a': 'B',
             'why': 'Changes in ownership without loss of control are equity '
                    'transactions. A is wrong: No gain or loss arises while '
                    'control is kept. C is wrong: Goodwill is measured only '
                    'when control is obtained.',
             'src': 'SC16-8'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. Why '
                  'does Orontes consolidate the cold-chain SPV?',
             'o': ['It owns more than 50% of the shares',
                   'It has both the power to direct the SPV and exposure to '
                   'its losses through the guarantee',
                   'It lends money to the SPV',
                   'The SPV is profitable'],
             'a': 'B',
             'why': 'Orontes is the primary beneficiary. A is wrong: Orontes '
                    'owns no shares. C is wrong: Economics alone are not '
                    'enough; power is also needed.',
             'src': 'SC16-4'}]),
          ('panel',
           'Method — the extract for the question that follows',
           [['Method',
             'When used (U.S. GAAP)',
             'What appears',
             'Intercompany profit removed',
             'Orontes'],
            ['Full consolidation',
             'Control (subsidiary or VIE)',
             '100% of each asset, liability, revenue and expense; NCI shown',
             '100% of intercompany items',
             'Levant (80%)'],
            ['Equity method',
             'Significant influence (20%–50%); joint ventures',
             'One line: investment and share of income',
             "Only the investor's share: 30% × 40,000 = 12,000",
             'Jordan Glass (30%)'],
            ['Proportionate consolidation',
             'Rare in U.S. GAAP: some construction and oil and gas interests',
             "Investor's share of each line",
             "Investor's share",
             'Not used by Orontes']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. How '
                  'much unrealized profit on bottles bought from Jordan '
                  'Glass does Orontes remove (whole USD)?',
             'o': ['0', '12,000', '40,000', '80,000'],
             'a': 'B',
             'why': "Only Orontes's 30% share of the $40,000 unrealized "
                    "profit. A is wrong: The investor's share must be "
                    'removed. C is wrong: Full elimination is for '
                    'subsidiaries, not equity-method investees.',
             'src': 'SC16-6'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f6',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['noncontrolling interest', 'equity method'],
           'IFRS 10 uses one control model: an investor controls an entity '
           'if it has power over it, exposure to variable returns, and the '
           'ability to use its power to affect those returns. There is no '
           'separate VIE model, and an investor can have de facto control '
           'with less than half of the votes.')]}
