# -*- coding: utf-8 -*-
"""Figures for chapter 9, drawn from the chapter's own tables.

Generated by wsgen. Each builder renders the model and, with
blank=True, the twin the student rebuilds from memory.
"""
from wsfiggen import (flowchain, cardset, lanes, splitbar,
                      chaptermap)


def f1(blank=False):
    return flowchain(blank=blank, **{'title': 'Item — Answer', 'steps': [('Share of net income', '30% × 400,000 = 120,000'), ('Extra depreciation', '3,000'), ('Dividends', '30% × 100,000 = 30,000'), ('Ending balance', '1,287,000 + 120,000 − 3,000 − 30,000 = 1,374,000'), ('Equity-method income', '120,000 − 3,000 = 117,000')]})


def f2(blank=False):
    return lanes(blank=blank, **{'title': 'Category by on sale, oci is', 'groups': [('—', ['Trading (debt)', 'Held-to-maturity (debt)', 'Equity, no significant influence', 'Equity, no readily determinable fair value', 'Equity method']), ('Reclassified to net income', ['Available-for-sale (debt)'])], 'sub': 'every one of these is in the book’s own table'})


def f3(blank=False):
    return flowchain(blank=blank, **{'title': 'Investment — Category', 'steps': [('A', 'Trading'), ('B', 'Held-to-maturity'), ('C', 'Available-for-sale'), ('D', 'Equity: fair value through net income'), ('E', 'Equity method')]})


def f4(blank=False):
    return chaptermap(blank=blank, **{'title': 'Where this section sits', 'nodes': [('Three categories of debt securities', 'section 9.1'), ('Measuring debt securities', 'section 9.2'), ('Credit losses on debt securities', 'section 9.3'), ('Equity securities and the equity method', 'you are here · section 9.4')], 'sub': 'each section uses what the one before it settled'})


def chmap(blank=False):
    return chaptermap(blank=blank, **{'title': 'Chapter 9 at a glance', 'nodes': [('Three categories of debt securities', 'section 9.1'), ('Measuring debt securities', 'section 9.2'), ('Credit losses on debt securities', 'section 9.3'), ('Equity securities and the equity method', 'section 9.4')], 'note': 'Every section uses what the one before it settled.'})


FIGS = {'f1': f1, 'f2': f2, 'f3': f3, 'f4': f4, 'chmap': chmap}
