# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C16-1': ('case item C16-1', []),
    'C16-2': ('case item C16-2', []),
    'C16-3': ('case item C16-3', []),
    'C16-4': ('case item C16-4', []),
    'C16-5': ('case item C16-5', []),
    'C16-6': ('case item C16-6', []),
    'P16-01': ('practice item P16-01', []),
    'P16-02': ('practice item P16-02', []),
    'P16-03': ('practice item P16-03', []),
    'P16-04': ('practice item P16-04', []),
    'P16-05': ('practice item P16-05', []),
    'P16-06': ('practice item P16-06', []),
    'P16-07': ('practice item P16-07', []),
    'P16-08': ('practice item P16-08', []),
    'P16-09': ('practice item P16-09', []),
    'P16-10': ('practice item P16-10', []),
    'P16-11': ('practice item P16-11', []),
    'P16-12': ('practice item P16-12', []),
    'P16-13': ('practice item P16-13', []),
    'P16-14': ('practice item P16-14', []),
    'P16-15': ('practice item P16-15', []),
    'P16-16': ('practice item P16-16', []),
    'P16-17': ('practice item P16-17', []),
    'P16-18': ('practice item P16-18', []),
    'SC16-1': ('section-check item SC16-1', []),
    'SC16-10': ('section-check item SC16-10', []),
    'SC16-11': ('section-check item SC16-11', []),
    'SC16-2': ('section-check item SC16-2', []),
    'SC16-3': ('section-check item SC16-3', []),
    'SC16-4': ('section-check item SC16-4', []),
    'SC16-5': ('section-check item SC16-5', []),
    'SC16-6': ('section-check item SC16-6', []),
    'SC16-7': ('section-check item SC16-7', []),
    'SC16-8': ('section-check item SC16-8', []),
    'SC16-9': ('section-check item SC16-9', []),
    'term:acquisition method': ("term-bridge row 'acquisition method'", []),
    'term:consolidated financial statements': ("term-bridge row 'consolidated financial statements'", []),
    'term:controlling financial interest': ("term-bridge row 'controlling financial interest'", []),
    'term:downstream sale': ("term-bridge row 'downstream sale'", []),
    'term:equity method': ("term-bridge row 'equity method'", []),
    'term:goodwill': ("term-bridge row 'goodwill'", []),
    'term:intercompany transaction': ("term-bridge row 'intercompany transaction'", []),
    'term:joint venture': ("term-bridge row 'joint venture'", []),
    'term:noncontrolling interest': ("term-bridge row 'noncontrolling interest'", []),
    'term:parent': ("term-bridge row 'parent'", []),
    'term:primary beneficiary': ("term-bridge row 'primary beneficiary'", []),
    'term:proportionate consolidation': ("term-bridge row 'proportionate consolidation'", []),
    'term:subsidiary': ("term-bridge row 'subsidiary'", []),
    'term:unrealized profit': ("term-bridge row 'unrealized profit'", []),
    'term:upstream sale': ("term-bridge row 'upstream sale'", []),
    'term:variable interest entity': ("term-bridge row 'variable interest entity'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C16-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'SC16-10': 'it sends the reader to F16-07, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC16-7': 'it sends the reader to F16-05, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
