"""A2.1 Unit 2 - The Van at Half Past Four - fourteen figures, as data."""
FIGURES = {
"fig_a21_u02_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The loading bay, 04.30',
 sub='Three of these people had already been working for an hour when the van came in.',
 alt='A market loading bay before dawn with a van reversing in, pallets, crates, a hose running '
     'and traders working under lights.',
 sky='#DCDCD6', ground='#9FA3A0', ground_line=660,
 buildings=[dict(x=40, w=880, storeys=2, colour='#D8D2C4', label='the covered market'),
   dict(x=960, w=580, storeys=3, colour='#C9C3B4', label='the cold store')],
 props=[dict(kind='van', x=1120, y=660, s=1.2, colour='#1F4E5F'),
   dict(kind='crate', x=250, y=660, s=1.2), dict(kind='crate', x=322, y=660, s=1.2),
   dict(kind='box', x=560, y=660, s=1.3), dict(kind='box', x=650, y=660, s=1.2),
   dict(kind='table', x=800, y=660, s=1.3),
   dict(kind='stall', x=120, y=660, s=.95, colour='#C86B2B'),
   dict(kind='sign', x=1495, y=660, s=.8, text='04:30')],
 people=[dict(x=196, y=660, h=86, skin=2, cloth=3, hair='wrap', arm='hold'),
   dict(x=470, y=660, h=85, skin=3, cloth=1, hair='short', arm='hold'),
   dict(x=722, y=660, h=86, skin=4, cloth=2, hair='bun', arm='down'),
   dict(x=1010, y=660, h=85, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=1330, y=660, h=86, skin=0, cloth=4, hair='cap', arm='raise')],
 names=[dict(x=196, t='Siti, price cards since four'), dict(x=470, t='Ravi, washing the ice'),
   dict(x=722, t='Mei Ling, watching the pot'), dict(x=1010, t='Mr Tan, counting pallets'),
   dict(x=1330, t='Zul, forty minutes late'), dict(x=1495, t='the bay clock')],
 markers=[dict(x=196, y=548), dict(x=470, y=548), dict(x=722, y=548), dict(x=1010, y=548),
   dict(x=1330, y=548), dict(x=286, y=612), dict(x=605, y=600), dict(x=1495, y=596)]),

"fig_a21_u02_p01_v08": dict(type='V8', height=780,
 title='From the soil to your bag',
 sub='Six stages. The dashed line is the one the label on the stall pretends happens.',
 alt='A network from seed and soil through farm, cold room, van and market to the buyer, with a '
     'dashed shortcut labelled straight from the farm.',
 nodes={
  'seed': dict(x=170, y=400, short='1', name='Seed & soil', sub='water, sun, rain', colour='#2E6F5E'),
  'farm': dict(x=500, y=240, short='2', name='The farm', sub='the farmer picks', colour='#2E6F5E'),
  'cold': dict(x=500, y=560, short='3', name='Cold room', sub='12 degrees, not colder', colour='#1F4E5F'),
  'van':  dict(x=870, y=400, short='4', name='The van', sub='58 km, two hours', r=54, colour='#C86B2B'),
  'mkt':  dict(x=1210, y=250, short='5', name='The market', sub='04:00, price cards', colour='#D9A441'),
  'you':  dict(x=1210, y=560, short='6', name='Your bag', sub='08:00, three of them', r=52, colour='#8C6A9E')},
 edges=[dict(a='seed', b='farm', label='it grows', sw=5),
   dict(a='farm', b='cold', label='forty crates', sw=5),
   dict(a='cold', b='van', label='loaded at one', sw=5),
   dict(a='farm', b='van', label='when the room is full', sw=3, dash='5 5'),
   dict(a='van', b='mkt', label='unloaded at 04:40', sw=5),
   dict(a='mkt', b='you', label='you choose', sw=5),
   dict(a='farm', b='you', label='"straight from the farm"', sw=2, dash='6 6', colour='#9AA7AE')]),

"fig_a21_u02_p01_v02": dict(type='V2', height=780,
 title='The cold room, in section',
 sub='Cold falls. That is the whole reason the shelves are arranged like this.',
 alt='A cold room drawn in section with four shelf levels labelled by temperature and by what is '
     'stored there.',
 floors=[dict(was='the fan', now='Cold comes out here - 8 degrees at the grille', year='', fill='#DCE6EA'),
   dict(was='top shelf', now='Leaves and herbs - they wilt first', year='', fill='#E4ECEF'),
   dict(was='middle shelf', now='Tomatoes - 12 degrees, never below ten', year='', fill='#F6F0E4'),
   dict(was='the floor', now='Root vegetables and anything in a sack', year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='The coldest point in the room'),
   dict(at=0.36, text='Nearest the fan, out first'),
   dict(at=0.62, text='Below ten they stop ripening for good'),
   dict(at=0.88, text='Warmest shelf, and it does not matter here')]),

"fig_a21_u02_p02_v07": dict(type='V7', height=800,
 title='Zul and Ravi in the loading bay',
 sub='One of them is explaining. One of them has been waiting since four.',
 alt='A van driver and a fish trader talking in a loading bay with crates between them and '
     'speech bubbles about the rain and the road.',
 bg='#E8E6E0',
 set=[dict(kind='van', x=1180, y=680, s=.95, colour='#1F4E5F'),
   dict(kind='crate', x=640, y=680, s=1.2), dict(kind='crate', x=720, y=680, s=1.2)],
 people=[dict(x=430, h=240, skin=0, cloth=4, hair='cap', arm='raise', facing='right',
   label='Zul', role='the van', says=['It was raining when I left the farm.',
     'While I was loading, the road closed.']),
  dict(x=930, h=240, skin=3, cloth=1, hair='short', arm='folded', facing='left',
   label='Ravi', role='fish, in at four', says=['I was here at four. Where were you?'])]),

"fig_a21_u02_p03_v09": dict(type='V9', kind='timeline', height=700,
 title='The background and the event',
 sub='The long bar is the weather. The short mark is what happened in it.',
 alt='A timeline with a long past-continuous band for the rain and short past-simple events for '
     'leaving the farm and the road closing, with while and when marked.',
 now=0.92, axis_y=490,
 bands=[dict(type='reach', lane=1, **{'from': 0.08}, label='past continuous - the background',
     example='It was raining all morning.'),
   dict(type='event', lane=3, **{'from': 0.34}, label='past simple - the event',
     example='The road closed.'),
   dict(type='before', lane=5, **{'from': 0.30, 'to': 0.38}, label='WHILE - cuts the long one',
     example='While I was loading, the road closed.  |  WHEN - names the short one')],
 rule='while + the long thing (while I was loading). when + the short thing (when the road '
      'closed). as works like while.'),

"fig_a21_u02_p03_v09b": dict(type='V9', kind='ladder', height=700,
 title='How long was it going on?',
 sub='Five sentences about the same morning, from one second to the whole of it.',
 alt='A ladder from a single instant through a short event to something that went on all '
     'morning.',
 top_label='went on and on', bottom_label='one second',
 steps=[dict(form='It was raining all morning', meaning='the background to everything else'),
   dict(form='I was loading the van', meaning='long enough to be interrupted'),
   dict(form='I was phoning him when he answered', meaning='the long one and the short one meet'),
   dict(form='The road closed', meaning='one short event, finished'),
   dict(form='Suddenly the pallet went over', meaning='one instant, and you can hear it')],
 rule='Know, understand, belong and cost almost never take the continuous. You cannot be knowing '
      'something at half past four.'),

"fig_a21_u02_p04_v04": dict(type='V4', height=720,
 title='Two mornings, one moment',
 sub='Learner A has the van. Learner B has the stall. Find the moment the two mornings met.',
 alt='Two panels side by side: a van on a wet road and a market stall being set up, each with '
     'its own clock and its own activity.',
 differences=7, prompt='Describe only. Do not show the page.',
 left=dict(label='the van', art=[
   dict(kind='block', x=120, y=0, w=200, bh=70, colour='#1F4E5F'),
   dict(kind='person', x=360, y=0, h=110, skin=0, cloth=4),
   dict(kind='arrow', x=420, y=40),
   dict(kind='label', x=300, y=200, text='01:20  -  still raining', colour='#1F4E5F')]),
 right=dict(label='the stall', art=[
   dict(kind='person', x=180, y=0, h=112, skin=2, cloth=3),
   dict(kind='crate', x=280, y=0), dict(kind='crate', x=340, y=0),
   dict(kind='doc', x=420, y=10),
   dict(kind='label', x=300, y=200, text='04:00  -  writing price cards', colour='#C86B2B')])),

"fig_a21_u02_p05_v05": dict(type='V5', height=980,
 title='The delivery note',
 sub='Printed by the farm, signed at the bay, and one line added by hand at the bottom.',
 alt='A delivery note listing crates loaded and received, load and signature times, a cold room '
     'temperature reading and a handwritten line about the cold room door.',
 rows=[dict(t='org', text='HIGHLAND GREENS SDN BHD  -  DELIVERY NOTE  4417'),
   dict(t='kv', k='Farm', v='Lot 9, Cameron Highlands', mono=False),
   dict(t='kv', k='To', v='Pasar Chow Kit, bay 2', mono=False),
   dict(t='rule'),
   dict(t='head', text='1 - WHAT WENT ON THE VAN'),
   dict(t='grid', cols=['ITEM', 'LOADED', 'RECEIVED'],
     data=[['Tomatoes (crate)', '40', '38'], ['Long beans (crate)', '12', '12'],
           ['Herbs (tray)', '18', '18']]),
   dict(t='rule'),
   dict(t='head', text='2 - TIMES'),
   dict(t='kv', k='Cold room in', v='Tue 21:00', mono=True),
   dict(t='kv', k='Loaded', v='Wed 00:55', mono=True),
   dict(t='kv', k='Left farm', v='Wed 01:20', mono=True),
   dict(t='kv', k='Signed for at bay', v='Wed 04:40', mono=True),
   dict(t='rule'),
   dict(t='head', text='3 - COLD ROOM READING'),
   dict(t='kv', k='At loading', v='9 C', mono=True),
   dict(t='para', text='Reading taken at the grille. Driver is not responsible for the reading. '
     'Any dispute to be raised within 24 hours of signature.'),
   dict(t='rule'),
   dict(t='sign', text='ADDED BY HAND, IN BLUE:'),
   dict(t='para', text='"Door was open when I got there at midnight. Not mine. - Z."')],
 callouts=[dict(at=0.26, text='Two crates short, and nobody has signed for the difference'),
   dict(at=0.48, text='Twenty-five minutes between loaded and left'),
   dict(at=0.56, text='Three hours twenty for fifty-eight kilometres'),
   dict(at=0.72, text='Nine degrees - the explainer said twelve'),
   dict(at=0.80, text='Twenty-four hours, and it is already eight'),
   dict(at=0.93, text='The only line with a person behind it')]),

"fig_a21_u02_p06_v03a": dict(type='V3', height=640,
 title='Before, during, after',
 sub='The same forty minutes, told three ways.',
 alt='A four-panel strip showing an earlier event, two things happening at the same time, an '
     'interruption, and what came afterwards.',
 axis_start='01:20', axis_end='05:00',
 panels=[dict(caption='EARLIER - it had started to rain', art=[
     dict(kind='label', x=160, y=170, text='earlier', colour='#1F4E5F'),
     dict(kind='block', x=70, y=0, w=20, bh=110, colour='#1F4E5F'),
     dict(kind='arrow', x=200, y=50)]),
   dict(caption='MEANWHILE - two long things at once', art=[
     dict(kind='block', x=100, y=0, w=240, bh=38, colour='#2E6F5E'),
     dict(kind='block', x=100, y=60, w=240, bh=38, colour='#C86B2B'),
     dict(kind='label', x=160, y=175, text='at the same time', colour='#2E6F5E')]),
   dict(caption='JUST AS - the short one cuts in', art=[
     dict(kind='block', x=90, y=20, w=260, bh=34, colour='#2E6F5E'),
     dict(kind='cross', x=250, y=95),
     dict(kind='label', x=160, y=180, text='at that moment', colour='#A8372E')]),
   dict(caption='AFTERWARDS - and by five it was over', art=[
     dict(kind='tick', x=170, y=70),
     dict(kind='label', x=160, y=180, text="by five o'clock", colour='#2E6F5E')])]),

"fig_a21_u02_p06_v04b": dict(type='V4', height=700,
 title='Two sentences, one difference',
 sub='The same driver and the same road. One of these is finished.',
 alt='Two sentences compared side by side, one past continuous drawn as a long band and one past '
     'simple drawn as a short block.',
 differences=6, prompt='Which one can be interrupted?',
 left=dict(label='I WAS DRIVING', art=[
   dict(kind='block', x=120, y=0, w=340, bh=46, colour='#2E6F5E'),
   dict(kind='arrow', x=470, y=10),
   dict(kind='label', x=300, y=200, text='long - and still going when something cut it',
        colour='#2E6F5E')]),
 right=dict(label='I DROVE', art=[
   dict(kind='block', x=240, y=0, w=90, bh=46, colour='#9AA7AE'),
   dict(kind='tick', x=400, y=30),
   dict(kind='label', x=300, y=200, text='short - the whole trip, in one word',
        colour='#9AA7AE')])),

"fig_a21_u02_p07_v10": dict(type='V10', kind='elision', height=620,
 title='The word you nearly cannot hear',
 sub='Was and were are grammar, not news. English hides them.',
 alt='Four phrases shown written and spoken, with was and were reduced to a single weak vowel.',
 pairs=[dict(written='it was raining', spoken='ɪtwəzˈreɪnɪŋ', dropped='a', note='was becomes /wəz/'),
   dict(written='they were loading', spoken='ðeɪwəˈləʊdɪŋ', dropped='ere',
        note='were becomes /wə/ - no r'),
   dict(written='what were you doing', spoken='wɒtwəjəˈduːɪŋ', dropped='ere',
        note='were /wə/, you /jə/'),
   dict(written='she was already there', spoken='ʃiwəzɔːlˈredi', dropped='a',
        note='three weak syllables in a row'),
   dict(written='it WAS raining', spoken='ɪtˈwɒzˈreɪnɪŋ', dropped='',
        note='loud only when you are arguing')]),

"fig_a21_u02_p08_v06": dict(type='V6', kind='line', height=780,
 title='What time the van arrived, every day for a month',
 sub='Twenty-four delivery days. The line at 04:00 is the slot Ravi pays for.',
 alt='A line chart of van arrival times over a month showing eight days well after four o clock '
     'and the rest close to it.',
 labels=['wk1 M', 'wk1 W', 'wk1 F', 'wk2 M', 'wk2 W', 'wk2 F', 'wk3 M', 'wk3 W', 'wk3 F',
         'wk4 M', 'wk4 W', 'wk4 F'],
 ymin=3.5, ymax=6.0, fmt='{:,.1f}',
 series=[dict(name='arrival (hours)', values=[4.0, 4.1, 4.0, 4.7, 5.3, 4.2, 4.1, 5.6, 5.1,
   4.0, 4.7, 5.4], colour='#C86B2B'),
   dict(name='the slot', values=[4.0]*12, colour='#9AA7AE', dash='5 5')],
 note='Eight of the twenty-four days are more than half an hour late. Six of those eight are a '
      'Wednesday or a Friday.',
 warning='The ice plant delivers to the port on Wednesday and Friday. Nobody had put those two '
         'facts next to each other.'),

"fig_a21_u02_p09_v03b": dict(type='V3', height=640,
 title='Taking notes in two columns',
 sub='Left: what she said. Right: what you want to ask. The right column is the one that learns.',
 alt='A four-panel strip of a student taking notes in a split page during a lecture and then '
     'using the right-hand column to ask a question.',
 axis_start='minute 0', axis_end='minute 12',
 panels=[dict(caption='Read the handout before she starts', art=[
     dict(kind='doc', x=160, y=20),
     dict(kind='label', x=160, y=190, text='two headings, ten seconds', colour='#1F4E5F')]),
   dict(caption='"There are three stages." - write the three', art=[
     dict(kind='person', x=110, y=0, h=112, skin=4, cloth=2, arm='point'),
     dict(kind='doc', x=250, y=20)]),
   dict(caption='Right column: but why not colder?', art=[
     dict(kind='doc', x=160, y=20),
     dict(kind='label', x=160, y=190, text='your question, not hers', colour='#C86B2B')]),
   dict(caption='Ask it. That is what the column is for.', art=[
     dict(kind='person', x=140, y=0, h=112, skin=2, cloth=3, arm='raise'),
     dict(kind='tick', x=270, y=70)])]),

"fig_a21_u02_p10_v12": dict(type='V12', height=840,
 title='Six hours you were asleep for',
 sub='Half the class sees Tuesday. Half sees Wednesday. Rebuild the chain by speaking.',
 alt='An infographic of a single delivery across two days showing picking, cold storage, the '
     'drive, the temperature and the moment of sale.',
 span=['Tue 15:00', 'Wed 08:00'], ticks=6,
 tick_labels=['15:00', '21:00', '01:20', '03:00', '04:40', '08:00'],
 bands=[dict(name='The crates', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.26}, label='picking in the rain', colour='#2E6F5E'),
   dict(**{'from': 0.26, 'to': 0.46}, label='cold room', colour='#1F4E5F'),
   dict(**{'from': 0.46, 'to': 0.82}, label='on the road', colour='#C86B2B'),
   dict(**{'from': 0.82, 'to': 1.0}, label='on the table', colour='#D9A441')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.04, label='two women, forty crates', colour='#2E6F5E'),
   dict(at=0.30, label='door found open at midnight', colour='#A8372E'),
   dict(at=0.50, label='van leaves, still raining', colour='#C86B2B'),
   dict(at=0.70, label='road closed - twenty minutes', colour='#A8372E'),
   dict(at=0.86, label='Siti is already writing cards', colour='#8C6A9E')]),
  dict(name='Temperature', type='line',
   points=[(0, 24), (0.26, 14), (0.4, 9), (0.6, 13), (0.82, 17), (1.0, 21)], end_label='21 C'),
  dict(name='Who was awake', type='flags', items=[
   dict(at=0.08, label='the pickers'), dict(at=0.46, label='Zul'),
   dict(at=0.80, label='Siti, Ravi, Mei Ling'), dict(at=0.98, label='you')])]),
}
