"""A2.1 Unit 6 - The Chiller or the Phone - fourteen figures, as data."""
FIGURES = {
"fig_a21_u06_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The money end of the market, 09.20',
 sub='Eleven prices in this picture. Three of them are for the same thing.',
 alt='A row of market stalls with chalkboards, handwritten price cards, a discount sticker, a '
     'till, a second-hand equipment pitch and a phone screen showing an order.',
 sky='#EAE6DC', ground='#AFA895', ground_line=660,
 buildings=[dict(x=20, w=520, storeys=2, colour='#DFD7C6', label='the produce row'),
   dict(x=580, w=480, storeys=3, colour='#D5CDBC', label='the equipment pitch'),
   dict(x=1100, w=480, storeys=2, colour='#C9C3B6', label='the office end')],
 props=[dict(kind='stall', x=140, y=660, s=1.0, colour='#C86B2B'),
   dict(kind='stall', x=400, y=660, s=1.0, colour='#2E6F5E'),
   dict(kind='table', x=680, y=660, s=1.2), dict(kind='table', x=880, y=660, s=1.2),
   dict(kind='box', x=1180, y=660, s=1.2), dict(kind='crate', x=1280, y=660, s=1.1),
   dict(kind='sign', x=300, y=660, s=.75, text='2.20'),
   dict(kind='sign', x=560, y=660, s=.75, text='-30%'),
   dict(kind='sign', x=1000, y=660, s=.75, text='900'),
   dict(kind='sign', x=1500, y=660, s=.75, text='2400')],
 people=[dict(x=200, y=660, h=86, skin=2, cloth=3, hair='wrap', arm='hold'),
   dict(x=460, y=660, h=85, skin=0, cloth=4, hair='short', arm='point'),
   dict(x=760, y=660, h=86, skin=3, cloth=1, hair='short', arm='down'),
   dict(x=1230, y=660, h=85, skin=4, cloth=2, hair='bun', arm='hold'),
   dict(x=1420, y=660, h=86, skin=1, cloth=0, hair='grey', arm='folded')],
 names=[dict(x=200, t='Siti, the chalkboard'), dict(x=460, t='Hafiz, the phone screen'),
   dict(x=760, t='the second-hand pitch'), dict(x=1230, t='the till and the receipts'),
   dict(x=1420, t='Mr Tan, the bill on the nail'), dict(x=1500, t='new, with a warranty')],
 markers=[dict(x=200, y=548), dict(x=460, y=548), dict(x=760, y=548), dict(x=1230, y=548),
   dict(x=1420, y=548), dict(x=300, y=596), dict(x=560, y=596), dict(x=1000, y=596),
   dict(x=1500, y=596), dict(x=880, y=612), dict(x=1280, y=614)]),

"fig_a21_u06_p01_v08": dict(type='V8', height=780,
 title='Price is printed. Worth is argued about.',
 sub='Five nodes. Only one of them has a number you can read off a label.',
 alt='A network connecting price, cost, running cost, value and worth, showing which are '
     'measurable and which are judgements.',
 nodes={
  'pri': dict(x=190, y=400, short='1', name='Price', sub='printed on the card', colour='#1F4E5F'),
  'run': dict(x=540, y=230, short='2', name='Running cost', sub='every year, quietly', colour='#C86B2B'),
  'lif': dict(x=540, y=570, short='3', name='How long it lasts', sub='nobody tells you', colour='#8C6A9E'),
  'val': dict(x=920, y=400, short='4', name='Value for money', sub='price ÷ years', r=54, colour='#2E6F5E'),
  'wor': dict(x=1300, y=400, short='5', name='Worth it?', sub='and that is a judgement', r=54, colour='#D9A441')},
 edges=[dict(a='pri', b='run', label='the bill you forget', sw=5),
   dict(a='pri', b='lif', label='the warranty hints at it', sw=5),
   dict(a='run', b='val', label='add it up over the years', sw=5),
   dict(a='lif', b='val', label='divide by the years', sw=5),
   dict(a='val', b='wor', label='and then you decide', sw=5),
   dict(a='pri', b='wor', label='what most people actually use', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_a21_u06_p01_v02": dict(type='V2', height=780,
 title='The chiller, in section',
 sub='Four parts, four costs. The one that fails first is not the one you looked at.',
 alt='A refrigerated display cabinet drawn in section with the compressor, the motor, the seals '
     'and the shelves labelled with what each costs to replace.',
 floors=[dict(was='the shelves', now='Shelves and glass - 60 to replace, almost never fail',
     year='', fill='#F2EDE2'),
   dict(was='the door seals', now='Seals - 45 a set, fail every three years, nobody notices',
     year='', fill='#E4ECEF'),
   dict(was='the motor', now='Motor - 310. This is what the warranty covers', year='', fill='#F6F0E4'),
   dict(was='the compressor', now='Compressor - 740. This is what actually breaks', year='',
     fill='#EFE2DD')],
 callouts=[dict(at=0.12, text='The part you can see, and the cheapest'),
   dict(at=0.38, text='Fail quietly. The machine just costs more to run'),
   dict(at=0.62, text='Covered. And the least likely to go'),
   dict(at=0.88, text='Not covered. Nearly as much as a second-hand machine')]),

"fig_a21_u06_p02_v07": dict(type='V7', height=800,
 title='Hafiz and Siti, and 2,600 ringgit',
 sub='One of them has already done the research. One of them has thirty-one years of it.',
 alt='A young man and an older trader talking across a stall about a phone system and a chiller, '
     'with speech bubbles showing verb patterns.',
 bg='#EEE9DE',
 set=[dict(kind='stall', x=680, y=680, s=1.3, colour='#2E6F5E'),
   dict(kind='box', x=1300, y=680, s=1.2)],
 people=[dict(x=450, h=242, skin=0, cloth=4, hair='short', arm='point', facing='right',
   label='Hafiz', role='three years', says=["I've decided to ask the customers first.",
     "I don't mind asking them."]),
  dict(x=950, h=240, skin=2, cloth=3, hair='wrap', arm='folded', facing='left',
   label='Siti', role='thirty-one years', says=["We can't afford to do both.",
     "I'd avoid buying anything second-hand."])]),

"fig_a21_u06_p03_v09": dict(type='V9', kind='ladder', height=720,
 title='Which form after the first verb',
 sub='A half-rule that covers most of the list, and a list for the rest.',
 alt='A ladder of verb patterns from decisions about the future taking to-infinitive down to '
     'ongoing experiences taking the -ing form.',
 top_label='a future decision', bottom_label='something already happening',
 steps=[dict(form='I decided TO ASK', meaning='decide, plan, hope, promise, refuse - all take to'),
   dict(form="I can't afford TO DO both", meaning='afford, manage, agree, offer, learn - also to'),
   dict(form='I like COOKING / I like TO COOK', meaning='like, love, hate, start - either, no real change'),
   dict(form="I don't mind ASKING", meaning='mind, enjoy, avoid, suggest, keep, give up - all -ing'),
   dict(form='I thought about BUYING it', meaning='after any preposition, always -ing')],
 rule='Half-rule: a future decision takes to, an experience you are already having takes -ing. '
      'It covers most of the list, and you will still have to learn the rest.'),

"fig_a21_u06_p03_v09b": dict(type='V9', kind='branch', height=700,
 title='The same first verb, two roads',
 sub='With four verbs in English, the form you choose changes what happened.',
 alt='A branching diagram from the verb stop into a to-infinitive branch meaning in order to and '
     'an -ing branch meaning the activity that ended.',
 root='she stopped...',
 branches=[dict(label='...TO COUNT the crates', example='she stopped doing something else, in '
     'order to count them', colour='#1F4E5F'),
   dict(label='...COUNTING the crates', example='counting is the thing that stopped',
     colour='#C86B2B'),
   dict(label='remember / try / go on', example='the same split: two forms, two meanings',
     colour='#2E6F5E'),
   dict(label='enjoy / decide / avoid / afford', example='only one form is possible at all, so '
     'there is nothing to choose', colour='#9AA7AE', dash='6 6')]),

"fig_a21_u06_p04_v04": dict(type='V4', height=720,
 title='Two quotations, one stall',
 sub='Learner A has the chiller. Learner B has the phone system. Both cost about 2,400.',
 alt='Two panels compared: a refrigerated cabinet with a price and a warranty, and a phone '
     'order system with an annual fee.',
 differences=7, prompt='Which of these can be sold again in three years?',
 left=dict(label='the chiller', art=[
   dict(kind='block', x=140, y=0, w=180, bh=110, colour='#1F4E5F'),
   dict(kind='person', x=380, y=0, h=112, skin=2, cloth=3),
   dict(kind='label', x=300, y=210, text='2,400 new  /  900 used  -  a thing you own',
        colour='#1F4E5F')]),
 right=dict(label='the phone system', art=[
   dict(kind='doc', x=200, y=0),
   dict(kind='person', x=360, y=0, h=112, skin=0, cloth=4),
   dict(kind='arrow', x=430, y=40),
   dict(kind='label', x=300, y=210, text='2,350 a year  -  a thing you rent', colour='#C86B2B')])),

"fig_a21_u06_p05_v05": dict(type='V5', height=1000,
 title='Two quotations for one chiller',
 sub='One new, one second-hand, and one line added in pen that nobody read.',
 alt='Two equipment quotations side by side listing price, warranty, running cost and '
     'exclusions, with a handwritten note about the compressor.',
 rows=[dict(t='org', text='QUOTATION A  -  NEW, SUPPLIED AND INSTALLED'),
   dict(t='kv', k='Price', v='2,400', mono=True),
   dict(t='kv', k='Warranty', v='3 years, parts and labour', mono=False),
   dict(t='kv', k='Running cost', v='about 520 a year', mono=True),
   dict(t='kv', k='Delivery', v='included', mono=False),
   dict(t='rule'),
   dict(t='org', text='QUOTATION B  -  SECOND-HAND, 2019 MODEL'),
   dict(t='kv', k='Price', v='900', mono=True),
   dict(t='kv', k='Warranty', v='6 months, motor only', mono=False),
   dict(t='kv', k='Running cost', v='about 680 a year', mono=True),
   dict(t='kv', k='Delivery', v='140 extra', mono=True),
   dict(t='rule'),
   dict(t='head', text='THE ARITHMETIC NOBODY DOES'),
   dict(t='grid', cols=['AFTER', 'A (NEW)', 'B (USED)'],
     data=[['1 year', '2,920', '1,720'], ['3 years', '3,960', '3,080'],
           ['6 years', '5,520', '5,120'], ['9 years', '7,080', '7,160']]),
   dict(t='para', text='The second-hand machine is cheaper until year nine. Most second-hand '
     'chillers of this model do not reach year nine.'),
   dict(t='rule'),
   dict(t='sign', text='ADDED IN PEN AT THE BOTTOM OF QUOTATION B:'),
   dict(t='para', text='"Motor only. Compressor is not covered - K."')],
 callouts=[dict(at=0.10, text='The price everybody compares'),
   dict(at=0.17, text='Three years, parts AND labour'),
   dict(at=0.23, text='160 a year less to run'),
   dict(at=0.44, text='Six months, and only one part'),
   dict(at=0.74, text='The cheaper machine overtakes in year nine'),
   dict(at=0.94, text='Seven words, and the compressor costs 740')]),

"fig_a21_u06_p06_v03a": dict(type='V3', height=640,
 title='From a wish to a receipt',
 sub='Four stages, and each one takes a different verb pattern.',
 alt='A four-panel strip from hoping to buy something, through deciding, avoiding a bad option, '
     'to finishing the purchase.',
 axis_start='a wish', axis_end='a receipt',
 panels=[dict(caption='HOPE TO - nothing has happened yet', art=[
     dict(kind='gap', x=140, y=0, w=180, bh=60),
     dict(kind='label', x=160, y=180, text='hope to / plan to', colour='#9AA7AE')]),
   dict(caption='DECIDE TO - now it is a plan', art=[
     dict(kind='block', x=140, y=0, w=180, bh=60, colour='#1F4E5F'),
     dict(kind='label', x=160, y=180, text='decide to / agree to', colour='#1F4E5F')]),
   dict(caption='AVOID -ING - and what you will not do', art=[
     dict(kind='cross', x=200, y=60),
     dict(kind='label', x=160, y=180, text='avoid buying / give up', colour='#A8372E')]),
   dict(caption='MANAGE TO - and it is done', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='tick', x=320, y=60),
     dict(kind='label', x=160, y=190, text='manage to / finish -ing', colour='#2E6F5E')])]),

"fig_a21_u06_p06_v04b": dict(type='V4', height=700,
 title='Cheap, and good value',
 sub='Two kettles. One of them cost more and has cost less.',
 alt='Two panels comparing a cheap kettle that lasted five months with an expensive one that '
     'lasted eleven years, with the annual cost of each.',
 differences=6, prompt='Which number should be on the price card?',
 left=dict(label='19 ringgit, five months', art=[
   dict(kind='block', x=180, y=0, w=90, bh=60, colour='#9AA7AE'),
   dict(kind='cross', x=340, y=60),
   dict(kind='label', x=300, y=200, text='45 a year, and bought four times', colour='#A8372E')]),
 right=dict(label='90 ringgit, eleven years', art=[
   dict(kind='block', x=180, y=0, w=90, bh=130, colour='#2E6F5E'),
   dict(kind='tick', x=350, y=60),
   dict(kind='label', x=300, y=200, text='8 a year, and still working', colour='#2E6F5E')])),

"fig_a21_u06_p07_v10": dict(type='V10', kind='stress', height=700,
 title='Which of the three words is loud',
 sub='In a two-verb phrase, to almost disappears. The -ing form keeps its own beat.',
 alt='Five verb phrases with the stressed syllables drawn as large dots and the weak ones as '
     'small dots, showing where to is reduced.',
 items=[dict(syllables=['I\'ve', 'de', 'CI', 'ded', 'to', 'ASK'], strong=[2, 5],
     note='to becomes /tə/ and nearly vanishes'),
   dict(syllables=['I', 'don\'t', 'MIND', 'ASK', 'ing'], strong=[2, 3],
     note='two strong words side by side'),
   dict(syllables=['we', 'can\'t', 'af', 'FORD', 'to', 'DO'], strong=[3, 5],
     note='to /tə/ again, between two strong beats'),
   dict(syllables=['I\'d', 'a', 'VOID', 'BUY', 'ing', 'it'], strong=[2, 3],
     note='-ing keeps a beat that to never gets'),
   dict(syllables=['I', 'don\'t', 'mind', 'ASK', 'ing'], strong=[3],
     note='only asking is fine. The answer is not')]),

"fig_a21_u06_p08_v06": dict(type='V6', kind='line', height=780,
 title='Produce thrown away each week',
 sub='Fourteen months, weighed on Sunday nights and written on the back of a receipt.',
 alt='A line chart of weekly produce waste in ringgit across fourteen months showing a sharp '
     'rise in the hot months.',
 labels=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
 ymin=0, ymax=220, fmt='{:,.0f}',
 series=[dict(name='thrown away (ringgit/week)',
   values=[52, 58, 96, 148, 186, 194, 178, 171, 132, 88, 61, 55], colour='#A8372E'),
   dict(name='if chilled', values=[30, 32, 38, 44, 48, 50, 47, 46, 41, 36, 33, 31],
     colour='#2E6F5E', dash='5 5')],
 note='The gap between the two lines is 4,600 a year, and nearly two thirds of it falls in '
      'four months.',
 warning='Siti said about 180 a week. She was right about the hot months and nearly double the '
         'truth about the year.'),

"fig_a21_u06_p09_v03b": dict(type='V3', height=640,
 title='Why the joke works, and where it stops working',
 sub='Four things a listener has to already have.',
 alt='A four-panel strip showing a joke that needs a shared price, a shared place, a pause, and '
     'what has to be explained to an outsider.',
 axis_start='inside', axis_end='outside',
 panels=[dict(caption='THE SHARED NUMBER - everybody knows the price', art=[
     dict(kind='label', x=160, y=80, text='2.20', colour='#C86B2B'),
     dict(kind='label', x=160, y=185, text='and what it was last year', colour='#C86B2B')]),
   dict(caption='THE PAUSE - before the last word', art=[
     dict(kind='person', x=150, y=0, h=112, skin=3, cloth=2, arm='hold'),
     dict(kind='label', x=160, y=185, text='timing, not vocabulary', colour='#1F4E5F')]),
   dict(caption='SAYING THE OPPOSITE - and meaning it', art=[
     dict(kind='person', x=120, y=0, h=110, skin=2, cloth=3),
     dict(kind='person', x=230, y=0, h=112, skin=0, cloth=1),
     dict(kind='label', x=160, y=185, text='"a real bargain"', colour='#8C6A9E')]),
   dict(caption='EXPLAINED - and now it is information', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='cross', x=320, y=60),
     dict(kind='label', x=160, y=190, text='true, and no longer funny', colour='#9AA7AE')])]),

"fig_a21_u06_p10_v12": dict(type='V12', height=840,
 title='2,600 ringgit, and fourteen months of waste',
 sub='Half the class sees the chiller quotation. Half sees the phone system. Rebuild it by '
     'speaking.',
 alt='An infographic of a stall savings decision showing the money available, the two options, '
     'the waste it would prevent and what actually happened.',
 span=['last Jan', 'next Jan'], ticks=6,
 tick_labels=['Jan', 'Apr', 'Jul', 'Oct', 'Dec', 'Jan'],
 bands=[dict(name='The savings', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.62}, label='building up to 2,600', colour='#2E6F5E'),
   dict(**{'from': 0.62, 'to': 0.70}, label='900 on the chiller', colour='#1F4E5F'),
   dict(**{'from': 0.86, 'to': 0.94}, label='740 on the compressor', colour='#A8372E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.30, label='waste peaks at 194 a week', colour='#A8372E'),
   dict(at=0.62, label='second-hand chiller delivered', colour='#1F4E5F'),
   dict(at=0.74, label='paid for itself in eleven weeks', colour='#2E6F5E'),
   dict(at=0.86, label='compressor fails - not covered', colour='#A8372E'),
   dict(at=0.96, label='free messaging group, built badly', colour='#D9A441')]),
  dict(name='Waste per week', type='line',
   points=[(0, 52), (0.3, 194), (0.5, 171), (0.62, 132), (0.75, 44), (1.0, 40)], end_label='40'),
  dict(name='The arguments', type='flags', items=[
   dict(at=0.10, label='Hafiz: four stalls already have it'),
   dict(at=0.42, label='Siti: thirty-one years of throwing it away'),
   dict(at=0.68, label='nobody read the line in pen'),
   dict(at=0.97, label='the cheap version of the other idea works')])]),
}
