"""A2.1 Unit 7 - Four Hundred Kilometres - fourteen figures, as data."""
FIGURES = {
"fig_a21_u07_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The labels end of the market, 08.50',
 sub='Nine labels. Three of them say where something is from. One is true and misleading.',
 alt='A market row with large printed origin signs above the stalls, crates of produce with '
     'country-of-origin boxes stacked behind, and shoppers reading the labels.',
 sky='#E6E9E3', ground='#ABA596', ground_line=660,
 buildings=[dict(x=20, w=700, storeys=2, colour='#DED6C5', label='the produce row'),
   dict(x=770, w=380, storeys=3, colour='#D2CBBA', label='the import pitch'),
   dict(x=1200, w=380, storeys=2, colour='#C8C1B2', label='the packers agent')],
 props=[dict(kind='stall', x=160, y=660, s=1.0, colour='#C86B2B'),
   dict(kind='stall', x=430, y=660, s=1.0, colour='#2E6F5E'),
   dict(kind='stall', x=880, y=660, s=1.0, colour='#D9A441'),
   dict(kind='box', x=640, y=660, s=1.3), dict(kind='box', x=1020, y=660, s=1.3),
   dict(kind='crate', x=1120, y=660, s=1.1), dict(kind='crate', x=1300, y=660, s=1.1),
   dict(kind='sign', x=240, y=660, s=.8, text='LOCAL'),
   dict(kind='sign', x=740, y=660, s=.75, text='THAI'),
   dict(kind='sign', x=1440, y=660, s=.75, text='PACKED')],
 people=[dict(x=330, y=660, h=86, skin=2, cloth=3, hair='wrap', arm='hold'),
   dict(x=520, y=660, h=85, skin=0, cloth=4, hair='short', arm='point'),
   dict(x=820, y=660, h=86, skin=4, cloth=1, hair='long', arm='down'),
   dict(x=1200, y=660, h=85, skin=3, cloth=2, hair='bun', arm='hold'),
   dict(x=1380, y=660, h=86, skin=1, cloth=0, hair='cap', arm='folded')],
 names=[dict(x=330, t='Siti, never says the word'), dict(x=520, t='Hafiz, reading the box'),
   dict(x=820, t='the Thai long beans'), dict(x=1200, t='the garlic, via Selangor'),
   dict(x=1380, t="the packer's driver"), dict(x=240, t='the sign at eye level'),
   dict(x=1440, t='PACKED IN, not GROWN IN')],
 markers=[dict(x=330, y=548), dict(x=520, y=548), dict(x=820, y=548), dict(x=1200, y=548),
   dict(x=1380, y=548), dict(x=240, y=590), dict(x=740, y=592), dict(x=1440, y=592),
   dict(x=640, y=606)]),

"fig_a21_u07_p01_v08": dict(type='V8', height=780,
 title='Four answers to one question',
 sub='Five nodes. Nobody who is asked this question twice gets to use only one of them.',
 alt='A network of the things people mean by where are you from - birthplace, upbringing, '
     'papers, accent and belonging - with the links between them labelled.',
 nodes={
  'bor': dict(x=190, y=400, short='1', name='Born in', sub='one line on one paper', colour='#1F4E5F'),
  'bro': dict(x=540, y=230, short='2', name='Brought up in', sub='where the accent came from', colour='#C86B2B'),
  'pap': dict(x=540, y=570, short='3', name='The papers', sub='passport, visa, citizen', colour='#8C6A9E'),
  'liv': dict(x=920, y=400, short='4', name='Where you live', sub='and have for years', r=54, colour='#2E6F5E'),
  'bel': dict(x=1300, y=400, short='5', name='Belong', sub='and this one is not yours to decide',
    r=54, colour='#D9A441')},
 edges=[dict(a='bor', b='bro', label='often not the same place', sw=5),
   dict(a='bor', b='pap', label='sometimes decides them', sw=4),
   dict(a='bro', b='liv', label='you moved away', sw=5),
   dict(a='pap', b='liv', label='or you did not', sw=4),
   dict(a='liv', b='bel', label='after long enough', sw=5),
   dict(a='bro', b='bel', label='the accent, which people hear first', sw=3, dash='5 5'),
   dict(a='bor', b='bel', label='"but where are you REALLY from"', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_a21_u07_p01_v02": dict(type='V2', height=780,
 title='The family house, in section',
 sub='Three floors, built over fifty years, and the oldest one is in the middle.',
 alt='A three-storey family house drawn in section showing which floor was built when and who '
     'was born in which country.',
 floors=[dict(was='added 2009', now='Two rooms for the grandchildren - born here', year='2009',
     fill='#EDE7DA'),
   dict(was='the roof terrace', now='Was the roof until 2009. The washing still goes here',
     year='1998', fill='#E4ECEF'),
   dict(was='built 1974', now='The first floor - she was born in Kedah, not here', year='1974',
     fill='#F6F0E4'),
   dict(was='the shop below', now='Rented out since 1991. Nobody in the family uses it',
     year='1974', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='The newest floor, and the only people born in this town'),
   dict(at=0.38, text='A roof that became a room'),
   dict(at=0.62, text='Built first. Everything else was added to this'),
   dict(at=0.88, text='Income, and three different tenants since 1991')]),

"fig_a21_u07_p02_v07": dict(type='V7', height=800,
 title='The sign says local',
 sub='One of them hung it. One of them has never said the word out loud.',
 alt='A young trader and an older trader under a large LOCAL sign, with crates behind them '
     'marked with countries of origin.',
 bg='#ECEDE7',
 set=[dict(kind='stall', x=690, y=680, s=1.3, colour='#C86B2B'),
   dict(kind='box', x=1290, y=680, s=1.2), dict(kind='sign', x=300, y=680, s=.9, text='LOCAL')],
 people=[dict(x=520, h=240, skin=0, cloth=4, hair='short', arm='point', facing='right',
   label='Hafiz', role='hung the sign', says=['The garlic is grown in China.',
     "It's packed in Selangor."]),
  dict(x=1000, h=242, skin=2, cloth=3, hair='wrap', arm='folded', facing='left',
   label='Siti', role='thirty-one years', says=['Somebody put the sign up last year.'])]),

"fig_a21_u07_p03_v09": dict(type='V9', kind='mirror', height=640,
 title='The same event, two first words',
 sub='Active starts with the person. Passive starts with the thing, and can end without one.',
 alt='Two parallel sentences, one active and one passive, drawn as coloured slots showing the '
     'agent, the action and the affected thing.',
 active=dict(parts=[dict(w=1.0, role='agent', text='They'),
   dict(w=1.0, role='action', text='grow'),
   dict(w=1.6, role='affected', text='the garlic in China')]),
 passive=dict(parts=[dict(w=1.6, role='affected', text='The garlic'),
   dict(w=1.2, role='action', text='is grown in China'),
   dict(w=1.0, role='hidden', text='(by whom?)')]),
 rule='Three reasons to use the passive: nobody knows who, it does not matter who, or somebody '
      'would rather you did not ask. Only the third is suspicious.'),

"fig_a21_u07_p03_v09b": dict(type='V9', kind='scope', height=560,
 title='The slot you can delete',
 sub='Every passive sentence has a by-slot. Most of the time it is empty on purpose.',
 alt='A passive sentence with brackets marking the thing, the action and the optional by-phrase '
     'that can be deleted.',
 words=['The', 'sign', 'was', 'put', 'up', 'last', 'year', 'by', 'Hafiz'],
 focus=[1, 3, 8],
 brackets=[dict(**{'from': 0, 'to': 1}, lane=0, label='the thing, promoted to first', colour='#2E6F5E'),
   dict(**{'from': 2, 'to': 6}, lane=0, label='be + past participle', colour='#1F4E5F'),
   dict(**{'from': 7, 'to': 8}, lane=1, label='delete this and the sentence still works',
     colour='#C86B2B')]),

"fig_a21_u07_p04_v04": dict(type='V4', height=720,
 title='The label, and the delivery record',
 sub='Learner A has the records. Learner B has the labels. Two of them disagree.',
 alt='Two panels side by side, one showing a printed origin label and one showing a delivery '
     'note with a different place on it.',
 differences=7, prompt='Which two products do the label and the record disagree about?',
 left=dict(label='the label, at eye level', art=[
   dict(kind='sign', x=200, y=0, s=1.1, text='LOCAL'),
   dict(kind='person', x=360, y=0, h=112, skin=4, cloth=1),
   dict(kind='label', x=300, y=200, text='printed, large, above the crates', colour='#C86B2B')]),
 right=dict(label='the box, on the floor', art=[
   dict(kind='box', x=200, y=0, s=1.4),
   dict(kind='doc', x=360, y=10),
   dict(kind='label', x=300, y=200, text='PRODUCT OF CHINA, in 9pt', colour='#1F4E5F')])),

"fig_a21_u07_p05_v05": dict(type='V5', height=1010,
 title='Three labels and one delivery record',
 sub='Two of them name a country. One names a company and lets you assume the rest.',
 alt='Three produce labels and a delivery record listing origin, packer, distance travelled and '
     'what each label does and does not state.',
 rows=[dict(t='org', text='LABEL 1  -  TOMATOES'),
   dict(t='kv', k='Printed', v='GROWN IN CAMERON HIGHLANDS', mono=False),
   dict(t='kv', k='Distance', v='172 km', mono=True),
   dict(t='rule'),
   dict(t='org', text='LABEL 2  -  LONG BEANS'),
   dict(t='kv', k='Printed', v='PRODUCT OF THAILAND', mono=False),
   dict(t='kv', k='Distance', v='1,140 km', mono=True),
   dict(t='rule'),
   dict(t='org', text='LABEL 3  -  GARLIC'),
   dict(t='kv', k='Printed', v='PACKED IN SELANGOR BY SRI MURNI SDN BHD', mono=False),
   dict(t='kv', k='Origin stated', v='none', mono=False),
   dict(t='para', text='PACKED IN names where the bag was filled. It does not name where '
     'anything was grown, and there is no requirement that it should.'),
   dict(t='rule'),
   dict(t='head', text='DELIVERY RECORD, 11th'),
   dict(t='grid', cols=['ITEM', 'FROM', 'KM'],
     data=[['Tomatoes', 'Cameron Highlands', '172'], ['Long beans', 'Nakhon Pathom, TH', '1,140'],
           ['Garlic', 'Sri Murni, Selangor', '38'], ['Garlic (origin)', 'Shandong, CN', '4,290']]),
   dict(t='rule'),
   dict(t='sign', text='THE STALL SIGN, ABOVE ALL THREE:'),
   dict(t='para', text='"LOCAL PRODUCE"')],
 callouts=[dict(at=0.10, text='A real place, and the only label that gives one'),
   dict(at=0.26, text='A country, printed plainly, and the furthest of the three'),
   dict(at=0.44, text='A company, not a country'),
   dict(at=0.52, text='Four words that most shoppers read as an origin'),
   dict(at=0.78, text='Thirty-eight kilometres - and four thousand two hundred and ninety'),
   dict(at=0.94, text='Hung above all of it, and not regulated anywhere')]),

"fig_a21_u07_p06_v03a": dict(type='V3', height=640,
 title='Grown, made, moved, sold',
 sub='Four verbs, and each one hides a different thing.',
 alt='A four-panel strip following a product from the field through the factory and the lorry to '
     'the stall, with the passive verb for each stage.',
 axis_start='the field', axis_end='the stall',
 panels=[dict(caption='IS GROWN - and the farmer is not named', art=[
     dict(kind='block', x=120, y=40, w=200, bh=40, colour='#2E6F5E'),
     dict(kind='label', x=160, y=180, text='grown in Shandong', colour='#2E6F5E')]),
   dict(caption='IS PACKED - and this is the step people read', art=[
     dict(kind='box', x=200, y=0, s=1.3),
     dict(kind='label', x=160, y=180, text='packed in Selangor', colour='#C86B2B')]),
   dict(caption='IS BROUGHT - thirty-eight kilometres', art=[
     dict(kind='arrow', x=200, y=40),
     dict(kind='label', x=160, y=180, text='sent by road, overnight', colour='#1F4E5F')]),
   dict(caption='IS SOLD - by a person, at last', art=[
     dict(kind='person', x=180, y=0, h=112, skin=2, cloth=3, arm='hold'),
     dict(kind='label', x=160, y=185, text='sold at stall 14', colour='#D9A441')])]),

"fig_a21_u07_p06_v04b": dict(type='V4', height=700,
 title='By hand, and by machine',
 sub='The same product, two methods, and two things the label will not tell you.',
 alt='Two panels comparing hand finishing and machine finishing, with the output rate and the '
     'visible difference in each.',
 differences=6, prompt='Which one does the label mention, and why that one?',
 left=dict(label='BY HAND', art=[
   dict(kind='person', x=250, y=0, h=130, skin=3, cloth=2, arm='hold'),
   dict(kind='label', x=300, y=200, text='forty an hour, and you can see the marks',
        colour='#C86B2B')]),
 right=dict(label='BY MACHINE, AT THE FACTORY', art=[
   dict(kind='block', x=200, y=0, w=180, bh=90, colour='#9AA7AE'),
   dict(kind='arrow', x=410, y=30),
   dict(kind='label', x=300, y=200, text='four hundred an hour, all identical',
        colour='#1F4E5F')])),

"fig_a21_u07_p07_v10": dict(type='V10', kind='elision', height=640,
 title='The -ed you cannot hear',
 sub='Three endings, and one of these words has no -ed in it at all.',
 alt='Five past participles shown written and spoken, with the -ed realised as a t, a d, a full '
     'syllable, or not present.',
 pairs=[dict(written='packed', spoken='pækt', dropped='e', note='-ed sounds like a t'),
   dict(written='sold', spoken='səʊld', dropped='', note='a d, and no extra syllable'),
   dict(written='imported', spoken='ɪmˈpɔːtɪd', dropped='', note='a whole extra syllable: /ɪd/'),
   dict(written='grown', spoken='ɡrəʊn', dropped='', note='not an -ed word at all'),
   dict(written='built', spoken='bɪlt', dropped='', note='irregular, and ends in t anyway')]),

"fig_a21_u07_p08_v06": dict(type='V6', kind='bar', height=780,
 title='How far each product travels',
 sub='Nine products on one stall, measured from where they were grown.',
 alt='A bar chart of distance travelled by nine market products showing three that travel under '
     'two hundred kilometres and two that travel over a thousand.',
 labels=['spinach', 'tomatoes', 'chillies', 'beans', 'cabbage', 'garlic'],
 ymin=0, ymax=4500, fmt='{:,.0f}',
 series=[dict(name='kilometres from where it grew', values=[40, 172, 210, 1140, 310, 4290],
   colour='#1F4E5F')],
 note='Three products travel less than 250 km. One travels more than four thousand, and its '
      'label gives a town thirty-eight kilometres away.',
 warning='The sign over all of them says LOCAL, which is not defined in law and so cannot '
         'be wrong.'),

"fig_a21_u07_p09_v03b": dict(type='V3', height=640,
 title='Four moves on a bad line',
 sub='Nobody can see anybody. Everything that is usually a look has to be said.',
 alt='A four-panel strip of a phone call to a distant supplier: identifying yourself, stating '
     'the problem with dates, asking for a named person and fixing a deadline.',
 axis_start='hello', axis_end='Thursday',
 panels=[dict(caption='"This is Hafiz at Chow Kit, stall 14."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=0, cloth=4, arm='hold'),
     dict(kind='label', x=160, y=185, text='who, and where', colour='#1F4E5F')]),
   dict(caption='"Twice - the fourth and the eleventh."', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='label', x=160, y=190, text='a date is harder to argue with', colour='#C86B2B')]),
   dict(caption='"Who should I ask for next time?"', art=[
     dict(kind='person', x=120, y=0, h=110, skin=3, cloth=1),
     dict(kind='person', x=230, y=0, h=112, skin=4, cloth=2),
     dict(kind='label', x=160, y=185, text='a name beats a department', colour='#8C6A9E')]),
   dict(caption='"So you\'ll call me back by Thursday."', art=[
     dict(kind='tick', x=180, y=60),
     dict(kind='label', x=160, y=185, text='one step, one date', colour='#2E6F5E')])]),

"fig_a21_u07_p10_v12": dict(type='V12', height=840,
 title='Where the stall actually buys from',
 sub='Half the class sees the labels. Half sees the records. Rebuild the chain by speaking.',
 alt='An infographic of a stall supply chain across one week showing origins, packers, '
     'distances and what each label states.',
 span=['the field', 'the stall'], ticks=6,
 tick_labels=['grown', 'picked', 'packed', 'loaded', 'driven', 'sold'],
 bands=[dict(name='Tomatoes', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.52}, label='Cameron Highlands, 172 km', colour='#2E6F5E'),
   dict(**{'from': 0.52, 'to': 1.0}, label='down overnight', colour='#D9A441')]),
  dict(name='Garlic', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.30}, label='Shandong, 4,290 km', colour='#A8372E'),
   dict(**{'from': 0.30, 'to': 0.74}, label='Sri Murni, Selangor - PACKED IN', colour='#8C6A9E'),
   dict(**{'from': 0.74, 'to': 1.0}, label='38 km by road', colour='#D9A441')]),
  dict(name='What the label says', type='events', items=[
   dict(at=0.12, label='nothing yet', colour='#9AA7AE'),
   dict(at=0.46, label='PACKED IN SELANGOR', colour='#8C6A9E'),
   dict(at=0.78, label='no origin stated', colour='#A8372E'),
   dict(at=0.96, label='and LOCAL, above all of it', colour='#C86B2B')]),
  dict(name='Who could tell you', type='flags', items=[
   dict(at=0.08, label='the grower, unnamed'),
   dict(at=0.44, label='the packer, named'),
   dict(at=0.72, label='the driver, who has never been asked'),
   dict(at=0.97, label='the trader, who did not print the sign')])]),
}
