"""A2.1 Unit 9 - Free Wifi, Nine Cameras - fourteen figures, as data."""
FIGURES = {
"fig_a21_u09_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The gate end of the market, 11.10',
 sub='Nine cameras in this picture. Two of them are not cameras.',
 alt='A market entrance with cameras on poles and walls, a till, an office window, a smoke '
     'detector, a doorbell and traders working underneath.',
 sky='#E1E6EA', ground='#A4A8A8', ground_line=660,
 buildings=[dict(x=20, w=480, storeys=3, colour='#D3D6D2', label='the gatehouse'),
   dict(x=560, w=560, storeys=2, colour='#DCD6C8', label='the covered market'),
   dict(x=1180, w=400, storeys=3, colour='#C7C4BC', label='the cold store')],
 props=[dict(kind='sign', x=120, y=660, s=.7, text='CCTV'),
   dict(kind='sign', x=460, y=660, s=.7, text='WIFI'),
   dict(kind='stall', x=680, y=660, s=1.0, colour='#C86B2B'),
   dict(kind='stall', x=940, y=660, s=1.0, colour='#2E6F5E'),
   dict(kind='table', x=300, y=660, s=1.1),
   dict(kind='box', x=1120, y=660, s=1.2), dict(kind='crate', x=1300, y=660, s=1.1),
   dict(kind='van', x=1460, y=660, s=.85, colour='#8C6A9E')],
 people=[dict(x=240, y=660, h=86, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=400, y=660, h=85, skin=3, cloth=2, hair='short', arm='hold'),
   dict(x=620, y=660, h=86, skin=2, cloth=3, hair='wrap', arm='hold'),
   dict(x=880, y=660, h=85, skin=0, cloth=4, hair='short', arm='down'),
   dict(x=1230, y=660, h=86, skin=4, cloth=1, hair='bun', arm='hold')],
 names=[dict(x=240, t='Mr Tan, counting the cameras'), dict(x=400, t='the salesman'),
   dict(x=620, t='Siti, under camera 3'), dict(x=880, t='Hafiz, reading the contract'),
   dict(x=1230, t='the till, and camera 6'), dict(x=120, t='above the gate, since 2023'),
   dict(x=460, t='the one on a pole')],
 markers=[dict(x=240, y=548), dict(x=400, y=548), dict(x=620, y=548), dict(x=880, y=548),
   dict(x=1230, y=548), dict(x=120, y=592), dict(x=460, y=592), dict(x=1300, y=610),
   dict(x=1460, y=600)]),

"fig_a21_u09_p01_v08": dict(type='V8', height=780,
 title='What a device can see, and who gets it',
 sub='Five nodes. The last one is the only one that is hard to find out.',
 alt='A network from a phone and its sensors through the account and the settings to the company '
     'and its partners, with the partners shown as the unknown node.',
 nodes={
  'dev': dict(x=180, y=400, short='1', name='The device', sub='screen, camera, microphone', colour='#1F4E5F'),
  'set': dict(x=520, y=230, short='2', name='The settings', sub='what you turned off', colour='#2E6F5E'),
  'acc': dict(x=520, y=570, short='3', name='The account', sub='password, notifications', colour='#C86B2B'),
  'com': dict(x=900, y=400, short='4', name='The company', sub='keeps it, for a while', r=54, colour='#8C6A9E'),
  'par': dict(x=1290, y=400, short='5', name='Who else?', sub='the question nobody answers',
    r=54, colour='#9AA7AE')},
 edges=[dict(a='dev', b='set', label='you can change this', sw=5),
   dict(a='dev', b='acc', label='and this', sw=5),
   dict(a='set', b='com', label='what is left after you turn things off', sw=5),
   dict(a='acc', b='com', label='everything you signed up to', sw=5),
   dict(a='com', b='par', label='clause 11, in smaller type', sw=3, dash='5 5'),
   dict(a='dev', b='par', label='and it never passes through a setting', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_a21_u09_p01_v02": dict(type='V2', height=780,
 title='The market gate, in section',
 sub='Four levels, four things being counted, and one device nobody asked for.',
 alt='A market gatehouse drawn in section showing the roof aerial, the camera bracket, the '
     'office window and the till, each labelled with what it records.',
 floors=[dict(was='the roof', now='Wifi aerial - installed free, and it counts connections',
     year='2026', fill='#E4ECEF'),
   dict(was='the bracket', now='Two cameras - "for counting vehicles", since 2023', year='2023',
     fill='#EFE2DD'),
   dict(was='the office window', now='One camera, pointing in. Nobody asked for this one',
     year='?', fill='#F6F0E4'),
   dict(was='the till', now='Card reader - time, amount, and which stall', year='2018',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Free, and counting before anybody logs in'),
   dict(at=0.38, text='Vehicles, allegedly. The question from 2011'),
   dict(at=0.62, text='Pointing at the committee room door'),
   dict(at=0.88, text='The oldest one, and the only one anybody consented to')]),

"fig_a21_u09_p02_v07": dict(type='V7', height=800,
 title='The offer',
 sub='One of them is selling. One of them is counting the cameras on the drawing.',
 alt='A salesman with a brochure and a market manager at a table, with speech bubbles using too, '
     'enough, so and such.',
 bg='#EAEDEF',
 set=[dict(kind='table', x=700, y=680, s=1.4), dict(kind='doc', x=700, y=600)],
 people=[dict(x=470, h=240, skin=3, cloth=2, hair='short', arm='point', facing='right',
   label='the salesman', role='sells them', says=["It's such a simple system.",
     'There are so many cameras because the coverage has to overlap.']),
  dict(x=980, h=242, skin=1, cloth=0, hair='grey', arm='folded', facing='left',
   label='Mr Tan', role='nine years', says=["It's too expensive to install ourselves.",
     "We don't have enough money to do it properly."])]),

"fig_a21_u09_p03_v09": dict(type='V9', kind='scope', height=560,
 title='What too and enough attach to',
 sub='Too complains about an adjective. Enough answers the question: enough for what?',
 alt='A sentence with brackets marking the word too modifies, the word enough modifies and the '
     'purpose clause that completes it.',
 words=['It', 'is', 'too', 'expensive', 'for', 'us', 'to', 'install', 'ourselves'],
 focus=[2, 3],
 brackets=[dict(**{'from': 2, 'to': 3}, lane=0, label='too + adjective = a complaint',
     colour='#A8372E'),
   dict(**{'from': 4, 'to': 5}, lane=1, label='too expensive for WHOM', colour='#C86B2B'),
   dict(**{'from': 6, 'to': 8}, lane=1, label='too expensive to DO WHAT', colour='#1F4E5F')]),

"fig_a21_u09_p03_v09b": dict(type='V9', kind='ladder', height=720,
 title='From not enough to far too much',
 sub='Five rungs, one quantity. Where would you put nine cameras?',
 alt='A ladder from not enough through enough and more than you need up to far too much, with '
     'an example sentence on each rung.',
 top_label='far too much', bottom_label='not enough',
 steps=[dict(form='There are far too many cameras', meaning='and I want some taken down'),
   dict(form='There are too many cameras', meaning='more than the job needs'),
   dict(form='There are so many cameras', meaning='a strong feeling - and you cannot tell which'),
   dict(form='There are enough cameras', meaning='enough for the job, and the job is named'),
   dict(form='There are not enough cameras', meaning='less than the job needs')],
 rule='too is a complaint; so is a feeling. It is too simple = it does not do what I need. It is '
      'so simple = and I am pleased.'),

"fig_a21_u09_p04_v04": dict(type='V4', height=720,
 title='What it says it counts, and what it could',
 sub='Learner A has the brochure. Learner B has the technical diagram. They are not the same '
     'document.',
 alt='Two panels compared: a marketing brochure showing a single footfall counter and a '
     'technical diagram showing several separate data streams.',
 differences=7, prompt='Which of these would you have to read the small type to find?',
 left=dict(label='the brochure', art=[
   dict(kind='doc', x=200, y=0),
   dict(kind='person', x=360, y=0, h=112, skin=3, cloth=2),
   dict(kind='label', x=300, y=200, text='"footfall" - one word, one picture', colour='#2E6F5E')]),
 right=dict(label='the diagram', art=[
   dict(kind='block', x=140, y=0, w=70, bh=50, colour='#8C6A9E'),
   dict(kind='block', x=230, y=0, w=70, bh=50, colour='#8C6A9E'),
   dict(kind='block', x=320, y=0, w=70, bh=50, colour='#8C6A9E'),
   dict(kind='block', x=410, y=0, w=70, bh=50, colour='#9AA7AE'),
   dict(kind='label', x=300, y=200, text='four streams, two of them unlabelled',
        colour='#A8372E')])),

"fig_a21_u09_p05_v05": dict(type='V5', height=1010,
 title='The wifi contract, clauses 1 to 12',
 sub='Eleven clauses in nine point type, and one in seven.',
 alt='An extract from a commercial wifi contract showing the term, what the cameras collect, '
     'data retention, ownership and a small-type clause about partners.',
 rows=[dict(t='org', text='AGREEMENT  -  NETWORK AND SENSOR INSTALLATION'),
   dict(t='kv', k='Term', v='5 years', mono=True),
   dict(t='kv', k='Cost to the market', v='nil', mono=True),
   dict(t='kv', k='Notice to end', v='none before year 5', mono=False),
   dict(t='rule'),
   dict(t='head', text='CLAUSE 4 - WHAT THE SENSORS COLLECT'),
   dict(t='grid', cols=['STREAM', 'STATED PURPOSE', 'STORED'],
     data=[['Footfall count', 'visitor numbers', '36 months'],
           ['Dwell time', 'queue management', '36 months'],
           ['Direction of travel', 'layout planning', '36 months'],
           ['Device identifiers', 'de-duplication', '36 months']]),
   dict(t='para', text='"Footfall" is not further defined in this agreement.'),
   dict(t='rule'),
   dict(t='head', text='CLAUSE 7 - OWNERSHIP'),
   dict(t='para', text='All data collected by the sensors is the property of the supplier. '
     'The market may request an aggregated monthly summary.'),
   dict(t='rule'),
   dict(t='sign', text='CLAUSE 11, SET IN SMALLER TYPE THAN THE REST:'),
   dict(t='para', text='"The supplier may share collected data with commercial partners. '
     'A list of current partners is available on request."')],
 callouts=[dict(at=0.12, text='Five years, and no way out of it'),
   dict(at=0.17, text='Free, which is the word everybody reads'),
   dict(at=0.40, text='Four streams, not one'),
   dict(at=0.46, text='Device identifiers - this is not counting people'),
   dict(at=0.68, text='Theirs, not the market\'s. A summary is all you get'),
   dict(at=0.93, text='On request. Nobody has ever requested it')]),

"fig_a21_u09_p06_v03a": dict(type='V3', height=640,
 title='Not enough, enough, too much',
 sub='The same quantity, four judgements, and the judgement is the whole sentence.',
 alt='A four-panel strip showing a quantity below what is needed, at what is needed, above it '
     'and far above it.',
 axis_start='none', axis_end='far too much',
 panels=[dict(caption='NOT ENOUGH - less than the job needs', art=[
     dict(kind='block', x=140, y=20, w=70, bh=46, colour='#9AA7AE'),
     dict(kind='gap', x=230, y=20, w=110, bh=46),
     dict(kind='label', x=160, y=180, text="not enough / isn't big enough", colour='#9AA7AE')]),
   dict(caption='ENOUGH - and you can say what for', art=[
     dict(kind='block', x=140, y=20, w=190, bh=46, colour='#2E6F5E'),
     dict(kind='tick', x=370, y=40),
     dict(kind='label', x=160, y=180, text='enough money to do it properly', colour='#2E6F5E')]),
   dict(caption='TOO MUCH - more than the job needs', art=[
     dict(kind='block', x=120, y=20, w=250, bh=46, colour='#C86B2B'),
     dict(kind='label', x=160, y=180, text='too much data / too many cameras', colour='#C86B2B')]),
   dict(caption='FAR TOO MUCH - and now it is a complaint', art=[
     dict(kind='block', x=100, y=20, w=300, bh=46, colour='#A8372E'),
     dict(kind='cross', x=430, y=50),
     dict(kind='label', x=160, y=180, text="far too / that's quite enough", colour='#A8372E')])]),

"fig_a21_u09_p06_v04b": dict(type='V4', height=700,
 title='SO, and TOO',
 sub='Both are strong. Only one of them wants something changed.',
 alt='Two panels comparing a sentence with so, drawn as an emphatic tick, and the same sentence '
     'with too, drawn as a cross.',
 differences=6, prompt='Which one is a complaint, and which could be either?',
 left=dict(label='SO simple', art=[
   dict(kind='block', x=200, y=0, w=180, bh=60, colour='#2E6F5E'),
   dict(kind='tick', x=430, y=30),
   dict(kind='label', x=300, y=200, text='a feeling - and I am pleased about it',
        colour='#2E6F5E')]),
 right=dict(label='TOO simple', art=[
   dict(kind='block', x=200, y=0, w=180, bh=60, colour='#A8372E'),
   dict(kind='cross', x=430, y=40),
   dict(kind='label', x=300, y=200, text='a complaint - it does not do what I need',
        colour='#A8372E')])),

"fig_a21_u09_p07_v10": dict(type='V10', kind='stress', height=700,
 title='The word you lean on',
 sub='With so and too, the intensifier takes the stress. With such, the adjective does.',
 alt='Five sentences with the stressed syllables drawn as large dots, showing the stress on so '
     'and too but not on such.',
 items=[dict(syllables=["it's", 'SO', 'sim', 'ple'], strong=[1],
     note='so is the loudest word in the sentence'),
   dict(syllables=["it's", 'such', 'a', 'SIM', 'ple', 'sys', 'tem'], strong=[3],
     note='such is not stressed - the adjective is'),
   dict(syllables=["it's", 'TOO', 'ex', 'pen', 'sive'], strong=[1],
     note='too carries the complaint'),
   dict(syllables=['there', 'are', 'SO', 'ma', 'ny'], strong=[2],
     note='impressed, or appalled - you can hear which'),
   dict(syllables=['there', 'are', 'TOO', 'ma', 'ny'], strong=[2],
     note='and this one wants some taken down')]),

"fig_a21_u09_p08_v06": dict(type='V6', kind='bar', height=780,
 title='What each data stream is worth to the supplier',
 sub='Estimated annual value per site, from the supplier\'s own investor presentation.',
 alt='A bar chart of the annual value of four data streams, with footfall worth least and device '
     'identifiers worth most.',
 labels=['footfall', 'dwell time', 'direction', 'device IDs'],
 ymin=0, ymax=9000, fmt='{:,.0f}',
 series=[dict(name='value per site per year', values=[900, 1600, 2100, 8400], colour='#8C6A9E')],
 note='The stream the brochure is about is worth the least. The stream in the fourth row of '
      'clause 4 is worth nine times as much.',
 warning='The wifi is worth about 2,800 a year to the traders. The data is worth about 13,000 a '
         'year to the supplier, which is why it is free.'),

"fig_a21_u09_p09_v03b": dict(type='V3', height=640,
 title='The same sentence, four registers',
 sub='Too formal with a friend is as strange as too casual with a stranger.',
 alt='A four-panel strip of one request - turn the microphone off - said to a friend, a '
     'colleague, a stranger and in a document.',
 axis_start='a friend', axis_end='a document',
 panels=[dict(caption='"Turn it off."', art=[
     dict(kind='person', x=130, y=0, h=112, skin=0, cloth=4, arm='point'),
     dict(kind='person', x=240, y=0, h=110, skin=2, cloth=3),
     dict(kind='label', x=160, y=185, text='a friend', colour='#2E6F5E')]),
   dict(caption='"Could you turn it off?"', art=[
     dict(kind='person', x=170, y=0, h=112, skin=3, cloth=1, arm='hold'),
     dict(kind='label', x=160, y=185, text='a colleague', colour='#1F4E5F')]),
   dict(caption='"Would you mind turning that off?"', art=[
     dict(kind='person', x=130, y=0, h=112, skin=4, cloth=2),
     dict(kind='person', x=250, y=0, h=110, skin=1, cloth=0),
     dict(kind='label', x=160, y=185, text='a stranger', colour='#C86B2B')]),
   dict(caption='"Users may disable audio capture in settings."', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='label', x=160, y=190, text='a document - and nobody is asked',
        colour='#9AA7AE')])]),

"fig_a21_u09_p10_v12": dict(type='V12', height=840,
 title='Fifteen years of cameras at one gate',
 sub='Half the class sees the 2011 minutes. Half sees the 2026 contract. Rebuild it by speaking.',
 alt='An infographic from 2011 to the present showing cameras installed and removed, questions '
     'asked, answers received and the current offer.',
 span=['2011', 'now'], ticks=6,
 tick_labels=['2011', '2014', '2018', '2023', '2026', 'now'],
 bands=[dict(name='Cameras at the gate', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.22}, label='two, "for vehicles"', colour='#9AA7AE'),
   dict(**{'from': 0.22, 'to': 0.78}, label='none - removed in the roof works', colour='#E4E0D8'),
   dict(**{'from': 0.78, 'to': 1.0}, label='four, and nine offered', colour='#8C6A9E')]),
  dict(name='Questions and answers', type='events', items=[
   dict(at=0.02, label='three questions agreed, 7 votes to 1', colour='#1F4E5F'),
   dict(at=0.10, label='letter written, never sent', colour='#A8372E'),
   dict(at=0.52, label='card reader installed - consented to', colour='#2E6F5E'),
   dict(at=0.86, label='two questions answered in four days', colour='#2E6F5E'),
   dict(at=0.96, label='the third answered after six weeks', colour='#C86B2B')]),
  dict(name='Streams collected', type='line',
   points=[(0, 1), (0.22, 0), (0.52, 1), (0.78, 2), (0.9, 4), (1.0, 4)], end_label='4'),
  dict(name='What it is worth', type='flags', items=[
   dict(at=0.30, label='wifi: 2,800 a year to the traders'),
   dict(at=0.62, label='data: about 13,000 a year to the supplier'),
   dict(at=0.88, label='one partner sets supermarket prices'),
   dict(at=0.99, label='and the market now pays 400 a month')])]),
}
