"""A2.1 Unit 10 - Three People Who Cannot Read the Notice - fourteen figures, as data."""
FIGURES = {
"fig_a21_u10_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The committee room, 10.55',
 sub='Twelve people. Three of them have not said anything. Two of them will decide.',
 alt='A market committee meeting with people at a table, standing at the back, in the doorway '
     'and by the window, with an agenda, a notice board and a clock.',
 sky='#E7E4DC', ground='#A8A294', ground_line=660,
 buildings=[dict(x=20, w=760, storeys=2, colour='#DBD5C7', label='the committee room'),
   dict(x=840, w=340, storeys=2, colour='#D0CABB', label='the office'),
   dict(x=1240, w=340, storeys=3, colour='#C6C0B2', label='the market, through the window')],
 props=[dict(kind='table', x=380, y=660, s=1.8),
   dict(kind='doc', x=200, y=640), dict(kind='sign', x=900, y=660, s=.75, text='AGENDA'),
   dict(kind='sign', x=1100, y=660, s=.7, text='3 JUNE'),
   dict(kind='box', x=1300, y=660, s=1.1), dict(kind='crate', x=1420, y=660, s=1.1)],
 people=[dict(x=140, y=660, h=86, skin=1, cloth=0, hair='grey', arm='hold'),
   dict(x=250, y=660, h=85, skin=2, cloth=3, hair='wrap', arm='down'),
   dict(x=350, y=660, h=86, skin=4, cloth=2, hair='bun', arm='raise'),
   dict(x=470, y=660, h=85, skin=0, cloth=4, hair='short', arm='down'),
   dict(x=580, y=660, h=86, skin=3, cloth=1, hair='short', arm='hold'),
   dict(x=700, y=660, h=85, skin=2, cloth=1, hair='long', arm='down'),
   dict(x=960, y=660, h=86, skin=0, cloth=2, hair='cap', arm='folded'),
   dict(x=1180, y=660, h=85, skin=3, cloth=0, hair='short', arm='down')],
 names=[dict(x=140, t='Mr Tan, chairing'), dict(x=250, t='Siti, has not spoken'),
   dict(x=350, t='Mei Ling, the letter'), dict(x=470, t='Hafiz, taking notes'),
   dict(x=580, t='Ravi, arrived late'), dict(x=700, t='Farah, by the window'),
   dict(x=960, t='Zul, in the doorway'), dict(x=1180, t='has not spoken since 2019')],
 markers=[dict(x=140, y=548), dict(x=250, y=548), dict(x=350, y=548), dict(x=470, y=548),
   dict(x=580, y=548), dict(x=700, y=548), dict(x=960, y=548), dict(x=1180, y=548),
   dict(x=900, y=594), dict(x=1100, y=594), dict(x=200, y=606), dict(x=380, y=616)]),

"fig_a21_u10_p01_v08": dict(type='V8', height=780,
 title='How a decision is made, and where it is actually made',
 sub='Five stages. The arrow that matters most does not pass through the room.',
 alt='A network from the notice through the agenda, the meeting and the vote to the minutes, '
     'with a dashed line showing the conversation that happens outside the room.',
 nodes={
  'not': dict(x=180, y=400, short='1', name='The notice', sub='fourteen days, on a board', colour='#1F4E5F'),
  'age': dict(x=520, y=230, short='2', name='The agenda', sub='written by one person', colour='#C86B2B'),
  'mee': dict(x=520, y=570, short='3', name='The meeting', sub='twenty minutes, twelve people', colour='#2E6F5E'),
  'vot': dict(x=900, y=400, short='4', name='The vote', sub='and it is over in a minute', r=54, colour='#8C6A9E'),
  'min': dict(x=1290, y=400, short='5', name='The minutes', sub='which is what survives', r=54, colour='#D9A441')},
 edges=[dict(a='not', b='age', label='if anybody read it', sw=4),
   dict(a='not', b='mee', label='fifteen days later', sw=5),
   dict(a='age', b='mee', label='three items, twenty minutes', sw=5),
   dict(a='mee', b='vot', label='after four people have spoken', sw=5),
   dict(a='vot', b='min', label='eight to four', sw=5),
   dict(a='not', b='vot', label='the conversations in the aisle, the week before', sw=3,
        dash='5 5', colour='#C86B2B'),
   dict(a='mee', b='min', label='what was said and not resolved', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_a21_u10_p01_v02": dict(type='V2', height=780,
 title='The committee room, in section',
 sub='Four zones, four kinds of power, and they are not in the order you would expect.',
 alt='A committee room drawn in section showing the table, the chairs at the back, the doorway '
     'and the corridor, with who sits where and how much each group speaks.',
 floors=[dict(was='the table', now='Six seats. 84 per cent of the speaking happens here',
     year='', fill='#E4ECEF'),
   dict(was='the back row', now='Four chairs. Two people have never spoken from them', year='',
     fill='#F6F0E4'),
   dict(was='the doorway', now='Standing. Leaves early, and is usually the driver', year='',
     fill='#F2EDE2'),
   dict(was='the corridor', now='Where the decision was actually agreed, on Tuesday', year='',
     fill='#EFE2DD')],
 callouts=[dict(at=0.12, text='Six of twelve, and most of the minutes'),
   dict(at=0.38, text='Present, counted in the quorum, silent'),
   dict(at=0.62, text='The person the rule affects most'),
   dict(at=0.88, text='Two people, four minutes, and no minutes taken')]),

"fig_a21_u10_p02_v07": dict(type='V7', height=800,
 title='The vote on Thursday',
 sub='One of them wrote the notice. One of them is asking who read it.',
 alt='A market manager and a trader across a committee table, with speech bubbles showing '
     'question tags and indirect questions.',
 bg='#EDEAE2',
 set=[dict(kind='table', x=700, y=680, s=1.5), dict(kind='doc', x=700, y=610)],
 people=[dict(x=470, h=242, skin=1, cloth=0, hair='grey', arm='hold', facing='right',
   label='Mr Tan', role='the chair', says=['You put the notice up last week, didn\'t you?']),
  dict(x=980, h=240, skin=4, cloth=2, hair='bun', arm='point', facing='left',
   label='Mei Ling', role='stall 22', says=["Nobody's read it, have they?",
     'Could you tell me when it went up?'])]),

"fig_a21_u10_p03_v09": dict(type='V9', kind='scope', height=560,
 title='What happens inside an indirect question',
 sub='The question word stays. The inversion goes. So does do.',
 alt='An indirect question with brackets marking the polite opening, the question word and the '
     'statement word order that follows it.',
 words=['Could', 'you', 'tell', 'me', 'when', 'it', 'went', 'up', '?'],
 focus=[4, 5, 6],
 brackets=[dict(**{'from': 0, 'to': 3}, lane=0, label='the polite opening', colour='#2E6F5E'),
   dict(**{'from': 4, 'to': 4}, lane=1, label='question word stays', colour='#C86B2B'),
   dict(**{'from': 5, 'to': 7}, lane=1, label='statement order - no did, no inversion',
     colour='#1F4E5F')]),

"fig_a21_u10_p03_v09b": dict(type='V9', kind='branch', height=700,
 title='One tag, two voices',
 sub='The words are identical. The pitch decides whether you are asking or accusing.',
 alt='A branching diagram from a single question tag into a rising version that asks and a '
     'falling version that accuses.',
 root='...didn\'t you?',
 branches=[dict(label='RISING - a real question',
     example='I think so, but tell me. The answer could be no', colour='#2E6F5E'),
   dict(label='FALLING - you already know',
     example='and so does everybody in the room. This is an accusation', colour='#A8372E'),
   dict(label='FALLING, after a pause',
     example='giving them a moment to say it themselves before you do', colour='#C86B2B'),
   dict(label='and the auxiliary never changes',
     example='you put = didn\'t you  |  nobody\'s read = have they  |  she can = can\'t she',
     colour='#9AA7AE', dash='6 6')]),

"fig_a21_u10_p04_v04": dict(type='V4', height=720,
 title='Who is in the room, and who is affected',
 sub='Learner A has the attendance list. Learner B has the list of who the rule touches.',
 alt='Two panels compared: the people present at a meeting and the people the decision affects, '
     'with the overlap smaller than either.',
 differences=7, prompt='How many people are in both lists, and how many in only one?',
 left=dict(label='in the room', art=[
   dict(kind='person', x=150, y=0, h=108, skin=1, cloth=0),
   dict(kind='person', x=220, y=0, h=110, skin=2, cloth=3),
   dict(kind='person', x=290, y=0, h=108, skin=4, cloth=2),
   dict(kind='person', x=360, y=0, h=110, skin=0, cloth=4),
   dict(kind='label', x=300, y=200, text='nine of twelve, and six of them silent',
        colour='#1F4E5F')]),
 right=dict(label='affected by it', art=[
   dict(kind='person', x=150, y=0, h=110, skin=2, cloth=3),
   dict(kind='person', x=230, y=0, h=108, skin=3, cloth=1),
   dict(kind='gap', x=310, y=10, w=70, bh=90),
   dict(kind='gap', x=390, y=10, w=70, bh=90),
   dict(kind='label', x=300, y=200, text='twelve, and three could not read the notice',
        colour='#A8372E')])),

"fig_a21_u10_p05_v05": dict(type='V5', height=1000,
 title='The notice of 3 June',
 sub='Two hundred and six words, one sentence of forty-one, and a board by the office.',
 alt='A market notice announcing a change to opening hours, with the objection procedure, the '
     'deadline and a very long sentence marked.',
 rows=[dict(t='org', text='PASAR CHOW KIT  -  NOTICE TO ALL TRADERS'),
   dict(t='kv', k='Posted', v='3 June, board by the office', mono=False),
   dict(t='kv', k='Vote', v='Thursday 18 June, 11.00', mono=True),
   dict(t='rule'),
   dict(t='head', text='THE PROPOSED RULE'),
   dict(t='para', text='From 1 August the market will open at 05.00 rather than 04.00, with the '
     'exception of the fish and ice bays which may open at 04.30 subject to a separate '
     'application being made in writing to the office not later than fourteen days before the '
     'date on which the trader wishes the arrangement to commence.'),
   dict(t='kv', k='Words in that sentence', v='41', mono=True),
   dict(t='rule'),
   dict(t='head', text='IF YOU WISH TO OBJECT'),
   dict(t='kv', k='How', v='in writing, to the office', mono=False),
   dict(t='kv', k='By', v='14 days from posting', mono=True),
   dict(t='kv', k='Which is', v='17 June', mono=True),
   dict(t='para', text='Objections received after this date will be recorded but will not be '
     'read to the meeting.'),
   dict(t='rule'),
   dict(t='sign', text='THE WHOLE NOTICE:'),
   dict(t='para', text='206 words. No headings. Nine point type. One copy, on one board, '
     'facing the office door.')],
 callouts=[dict(at=0.10, text='One board, and you have to walk past the office to see it'),
   dict(at=0.34, text='Forty-one words, and the exception is buried in the middle'),
   dict(at=0.62, text='In writing - which settles it for three of the twelve'),
   dict(at=0.70, text='Seventeenth. The vote is on the eighteenth'),
   dict(at=0.78, text='Recorded, but not read aloud'),
   dict(at=0.94, text='One copy. The thing that caused all of this')]),

"fig_a21_u10_p06_v03a": dict(type='V3', height=640,
 title='From most direct to least',
 sub='Four ways of asking the same question, and what each one costs you.',
 alt='A four-panel strip of the same question asked as an order, a direct question, an indirect '
     'question and a wondering, with the cost of each.',
 axis_start='an order', axis_end='a wondering',
 panels=[dict(caption='"Tell me when it went up."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=1, cloth=0, arm='point'),
     dict(kind='label', x=160, y=185, text='fastest, and hardest to refuse', colour='#A8372E')]),
   dict(caption='"When did it go up?"', art=[
     dict(kind='person', x=170, y=0, h=112, skin=3, cloth=2, arm='hold'),
     dict(kind='label', x=160, y=185, text='neutral - and this is most of speech',
       colour='#1F4E5F')]),
   dict(caption='"Could you tell me when it went up?"', art=[
     dict(kind='person', x=130, y=0, h=110, skin=4, cloth=1),
     dict(kind='person', x=240, y=0, h=112, skin=0, cloth=4),
     dict(kind='label', x=160, y=185, text='easy to deflect, and that is the point',
       colour='#2E6F5E')]),
   dict(caption='"I was wondering when it went up."', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='label', x=160, y=190, text='so easy to ignore that it often is',
       colour='#9AA7AE')])]),

"fig_a21_u10_p06_v04b": dict(type='V4', height=700,
 title='The tag, and the indirect question',
 sub='One of them is quicker. The other gets a longer answer.',
 alt='Two panels comparing a question tag, drawn as a short exchange, and an indirect question, '
     'drawn as a longer one.',
 differences=6, prompt='Which one would you use with somebody you have never met?',
 left=dict(label='THE TAG', art=[
   dict(kind='person', x=200, y=0, h=112, skin=1, cloth=0, arm='hold'),
   dict(kind='person', x=310, y=0, h=110, skin=2, cloth=3),
   dict(kind='label', x=300, y=200, text='"...didn\'t you?"  -  yes or no, in a second',
        colour='#C86B2B')]),
 right=dict(label='THE INDIRECT QUESTION', art=[
   dict(kind='person', x=200, y=0, h=112, skin=4, cloth=2, arm='point'),
   dict(kind='person', x=320, y=0, h=110, skin=3, cloth=1),
   dict(kind='doc', x=410, y=20),
   dict(kind='label', x=300, y=200, text='"Could you tell me...?"  -  and they explain',
        colour='#2E6F5E')])),

"fig_a21_u10_p07_v10": dict(type='V10', kind='pitch', height=680,
 title='The tag that rises, and the tag that does not',
 sub='Identical words. The last three notes decide what kind of sentence it was.',
 alt='Three question tags drawn as pitch contours, one rising into a genuine question and two '
     'falling into statements.',
 contours=[dict(text='You put it up last week, | didn\'t you? (rising)',
     points=[.2, .1, 0, -.1, -.2, .2, .6, .9], meaning='a real question - the answer could be no'),
   dict(text='You put it up last week, | didn\'t you? (falling)',
     points=[.3, .2, .1, 0, .1, 0, -.4, -.8], meaning='and we both know you did'),
   dict(text="Nobody's read it, | ... | have they?",
     points=[.2, .1, 0, -.1, -.1, -.1, -.5, -.9],
     meaning='the pause gives them a chance to say it first')]),

"fig_a21_u10_p08_v06": dict(type='V6', kind='bar', height=780,
 title='Who speaks, and for how long',
 sub='Twelve meetings, timed with a phone by a student doing a project.',
 alt='A bar chart of speaking time per person across twelve committee meetings, with two people '
     'accounting for most of it and three at almost nothing.',
 labels=['Mr Tan', 'Mr Lim', 'Mei Ling', 'Ravi', 'Siti', 'the other 7'],
 ymin=0, ymax=60, fmt='{:,.0f}',
 series=[dict(name='% of speaking time', values=[38, 23, 14, 9, 4, 12], colour='#1F4E5F')],
 note='Two people out of twelve take sixty-one per cent of the speaking time. Seven people share '
      'twelve per cent, and three of those seven have not spoken at all since 2019.',
 warning='Nobody in this room believes they are talking too much. The chair has 38 per cent and '
         'thinks of himself as the person who keeps things moving.'),

"fig_a21_u10_p09_v03b": dict(type='V3', height=640,
 title='Four moves in a negotiation',
 sub='Nobody says yes or no before minute five. That is not a trick; it is the whole method.',
 alt='A four-panel strip of a negotiation: stating a position, asking what is behind the other '
     'side, making a conditional offer and writing it down.',
 axis_start='minute 0', axis_end='in writing',
 panels=[dict(caption='"We can\'t open at six."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=2, cloth=3, arm='folded'),
     dict(kind='label', x=160, y=185, text='your position, stated once', colour='#1F4E5F')]),
   dict(caption='"Can I ask why six?"', art=[
     dict(kind='person', x=130, y=0, h=110, skin=0, cloth=4, arm='point'),
     dict(kind='person', x=250, y=0, h=112, skin=3, cloth=1),
     dict(kind='label', x=160, y=185, text='what is behind theirs', colour='#C86B2B')]),
   dict(caption='"IF you give us 05.15, we could live with six."', art=[
     dict(kind='block', x=130, y=10, w=100, bh=50, colour='#2E6F5E'),
     dict(kind='block', x=250, y=10, w=100, bh=50, colour='#8C6A9E'),
     dict(kind='label', x=160, y=185, text='two things on the table, not one',
       colour='#2E6F5E')]),
   dict(caption='"So - 05.15, from the first, in writing."', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='tick', x=320, y=60),
     dict(kind='label', x=160, y=190, text='and now it exists', colour='#D9A441')])]),

"fig_a21_u10_p10_v12": dict(type='V12', height=840,
 title='One notice, one vote, three conversations',
 sub='Half the class sees the notice. Half sees the minutes. Rebuild the dispute by speaking.',
 alt='An infographic of a market rule change from the posting of the notice through the letter, '
     'the postponement, three visits and the final vote.',
 span=['3 June', '24 June'], ticks=6,
 tick_labels=['3 Jun', '10 Jun', '17 Jun', '18 Jun', '20 Jun', '24 Jun'],
 bands=[dict(name='The notice', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.66}, label='up on one board, 206 words', colour='#9AA7AE'),
   dict(**{'from': 0.66, 'to': 1.0}, label='read aloud, and rewritten', colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.00, label='notice posted', colour='#1F4E5F'),
   dict(at=0.62, label='objection deadline - 17 June', colour='#C86B2B'),
   dict(at=0.68, label="Mei Ling's letter", colour='#8C6A9E'),
   dict(at=0.72, label='vote postponed to the 24th', colour='#D9A441'),
   dict(at=0.84, label='three visits, in person', colour='#2E6F5E'),
   dict(at=1.00, label='vote: 8 to 4 against', colour='#A8372E')]),
  dict(name='Traders who knew what it said', type='line',
   points=[(0, 4), (0.3, 6), (0.62, 8), (0.72, 9), (0.86, 12), (1.0, 12)], end_label='12'),
  dict(name='The arguments', type='flags', items=[
   dict(at=0.14, label='fifteen days - one more than the rule'),
   dict(at=0.46, label='the notice was up. It was not read'),
   dict(at=0.76, label='two of the three had it slightly wrong'),
   dict(at=0.96, label='the third was the one it affected most')])]),
}
