# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C12-1': ('case item C12-1', []),
    'C12-2': ('case item C12-2', []),
    'C12-3': ('case item C12-3', []),
    'C12-4': ('case item C12-4', []),
    'C12-5': ('case item C12-5', []),
    'C12-6': ('case item C12-6', []),
    'P12-01': ('practice item P12-01', []),
    'P12-02': ('practice item P12-02', []),
    'P12-03': ('practice item P12-03', []),
    'P12-04': ('practice item P12-04', []),
    'P12-05': ('practice item P12-05', []),
    'P12-06': ('practice item P12-06', []),
    'P12-07': ('practice item P12-07', []),
    'P12-08': ('practice item P12-08', []),
    'P12-09': ('practice item P12-09', []),
    'P12-10': ('practice item P12-10', []),
    'P12-11': ('practice item P12-11', []),
    'P12-12': ('practice item P12-12', []),
    'P12-13': ('practice item P12-13', []),
    'P12-14': ('practice item P12-14', []),
    'P12-15': ('practice item P12-15', []),
    'P12-16': ('practice item P12-16', []),
    'P12-17': ('practice item P12-17', []),
    'P12-18': ('practice item P12-18', []),
    'P12-19': ('practice item P12-19', []),
    'P12-20': ('practice item P12-20', []),
    'SC12-1': ('section-check item SC12-1', []),
    'SC12-2': ('section-check item SC12-2', []),
    'SC12-3': ('section-check item SC12-3', []),
    'SC12-5': ('section-check item SC12-5', []),
    'SC12-6': ('section-check item SC12-6', []),
    'SC12-7': ('section-check item SC12-7', []),
    'SC12-8': ('section-check item SC12-8', []),
    'SC12-9': ('section-check item SC12-9', []),
    'term:assurance-type warranty': ("term-bridge row 'assurance-type warranty'", []),
    'term:commercial paper': ("term-bridge row 'commercial paper'", []),
    'term:compensated absences': ("term-bridge row 'compensated absences'", []),
    'term:current liabilities': ("term-bridge row 'current liabilities'", []),
    'term:payroll taxes': ("term-bridge row 'payroll taxes'", []),
    'term:qualifying financing agreement': ("term-bridge row 'qualifying financing agreement'", []),
    'term:sales tax payable': ("term-bridge row 'sales tax payable'", []),
    'term:service-type warranty': ("term-bridge row 'service-type warranty'", []),
    'term:short-term obligation': ("term-bridge row 'short-term obligation'", []),
    'term:warranty liability': ("term-bridge row 'warranty liability'", []),
    'term:withholding': ("term-bridge row 'withholding'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C12-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P12-08': 'it sends the reader to F12-05, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC12-5': 'it sends the reader to F12-05, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC12-6': 'it sends the reader to F12-05, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC12-7': 'it sends the reader to F12-05, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC12-9': 'it sends the reader to F12-09, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
