# -*- coding: utf-8 -*-
"""Figures for chapter 14, drawn from the chapter's own tables.

Generated by wsgen. Each builder renders the model and, with
blank=True, the twin the student rebuilds from memory.
"""
from wsfiggen import (flowchain, cardset, lanes, splitbar,
                      chaptermap)


def f1(blank=False):
    return flowchain(blank=blank, **{'title': 'Lease — Category', 'steps': [('L1 Delivery trucks', ''), ('L2 Forklift', ''), ('L3 Storage room', ''), ('L4 Laptops', '')]})


def f2(blank=False):
    return cardset(blank=blank, **{'title': 'Criterion', 'cards': [('1. Ownership transfers', ['Warehouse (5 years, 100,000 a year): No', 'Olive press (4 years, 250,000 a year): No']), ('2. Purchase option reasonably certain', ['Warehouse (5 years, 100,000 a year): No', 'Olive press (4 years, 250,000 a year): No']), ('3. Major part of economic life', ['Warehouse (5 years, 100,000 a year): No: 5 of 30 years (17%)', 'Olive press (4 years, 250,000 a year): Yes: 4 of 5 years (80%)']), ('4. PV ≥ substantially all of fair value', ['Warehouse (5 years, 100,000 a year): No: 421,236 of 1,500,000 (28%)', 'Olive press (4 years, 250,000 a year): Not needed']), ('5. Specialized asset', ['Warehouse (5 years, 100,000 a year): No: any company could use it', 'Olive press (4 years, 250,000 a year): Yes: built for Orontes']), ('Classification', ['Warehouse (5 years, 100,000 a year): Operating lease', 'Olive press (4 years, 250,000 a year): Finance lease'])], 'sub': 'Warehouse (5 years, 100,000 a year) · Olive press (4 years, 250,000 a year)'})


def f3(blank=False):
    return cardset(blank=blank, **{'title': 'Suppose: January 1, 2026 (whole USD)', 'cards': [('Annual payment (end of each year)', ['Warehouse: 100,000', 'Olive press: 250,000']), ('Number of payments', ['Warehouse: 5', 'Olive press: 4']), ('Discount rate (incremental borrowing rate)', ['Warehouse: 6%', 'Olive press: 6%']), ('Undiscounted payments', ['Warehouse: 500,000', 'Olive press: 1,000,000']), ('Lease liability = present value of payments', ['Warehouse: 421,236', 'Olive press: 866,276']), ('Right-of-use asset (no prepayments, costs or incentives)', ['Warehouse: 421,236', 'Olive press: 866,276'])], 'sub': 'Warehouse · Olive press'})


def f4(blank=False):
    return lanes(blank=blank, **{'title': 'Lease by category', 'groups': [('Operating lease', ['L1 Delivery trucks', 'L4 Laptops']), ('Finance lease', ['L2 Forklift']), ('Short-term lease (exempt)', ['L3 Storage room'])], 'sub': 'every one of these is in the book’s own table'})


def f5(blank=False):
    return chaptermap(blank=blank, **{'title': 'Where this section sits', 'nodes': [('What is a lease?', 'section 14.1'), ('Finance or operating? The five criteria', 'section 14.2'), ('Initial measurement', 'section 14.3'), ('Subsequent measurement: two expense patterns', 'section 14.4'), ('Presentation', 'you are here · section 14.5'), ('Short-term leases, sale and leaseback, and IFRS 16', 'section 14.6')], 'sub': 'each section uses what the one before it settled'})


def f6(blank=False):
    return cardset(blank=blank, **{'title': 'Topic', 'cards': [('Lessee models', ['U.S. GAAP (ASC 842): Two: finance and operating', 'IFRS 16: One: all leases like finance leases']), ("Expense pattern for a 'plain' lease", ['U.S. GAAP (ASC 842): Straight-line single cost (operating)', 'IFRS 16: Depreciation plus interest: higher early']), ('Low-value assets (e.g., laptops)', ['U.S. GAAP (ASC 842): No exemption (materiality only)', 'IFRS 16: Exemption allowed']), ('Short-term leases (12 months or less)', ['U.S. GAAP (ASC 842): Exemption by class of asset', 'IFRS 16: Exemption by class of asset']), ('Index or rate changes (e.g., CPI)', ['U.S. GAAP (ASC 842): No remeasurement; expense as incurred', 'IFRS 16: Remeasure the liability']), ('Interest paid in the cash flow statement', ['U.S. GAAP (ASC 842): Operating', 'IFRS 16: Operating or financing (IAS 7 today)'])], 'sub': 'U.S. GAAP (ASC 842) · IFRS 16'})


def frev(blank=False):
    return flowchain(blank=blank, **{'title': 'Lease — Category', 'steps': [('L1 Delivery trucks', ''), ('L2 Forklift', ''), ('L3 Storage room', ''), ('L4 Laptops', '')]})


def chmap(blank=False):
    return chaptermap(blank=blank, **{'title': 'Chapter 14 at a glance', 'nodes': [('What is a lease?', 'section 14.1'), ('Finance or operating? The five criteria', 'section 14.2'), ('Initial measurement', 'section 14.3'), ('Subsequent measurement: two expense patterns', 'section 14.4'), ('Presentation', 'section 14.5'), ('Short-term leases, sale and leaseback, and IFRS 16', 'section 14.6')], 'note': 'Every section uses what the one before it settled.'})


FIGS = {'f1': f1, 'f2': f2, 'f3': f3, 'f4': f4, 'f5': f5, 'f6': f6, 'frev': frev, 'chmap': chmap}
