# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C2-1': ('case item C2-1', []),
    'C2-2': ('case item C2-2', []),
    'C2-3': ('case item C2-3', []),
    'C2-4': ('case item C2-4', []),
    'C2-5': ('case item C2-5', []),
    'C2-6': ('case item C2-6', []),
    'P2-01': ('practice item P2-01', []),
    'P2-02': ('practice item P2-02', []),
    'P2-03': ('practice item P2-03', []),
    'P2-04': ('practice item P2-04', []),
    'P2-05': ('practice item P2-05', []),
    'P2-06': ('practice item P2-06', []),
    'P2-07': ('practice item P2-07', []),
    'P2-08': ('practice item P2-08', []),
    'P2-09': ('practice item P2-09', []),
    'P2-10': ('practice item P2-10', []),
    'P2-11': ('practice item P2-11', []),
    'P2-12': ('practice item P2-12', []),
    'P2-13': ('practice item P2-13', []),
    'P2-14': ('practice item P2-14', []),
    'P2-15': ('practice item P2-15', []),
    'P2-16': ('practice item P2-16', []),
    'P2-17': ('practice item P2-17', []),
    'P2-18': ('practice item P2-18', []),
    'P2-19': ('practice item P2-19', []),
    'P2-20': ('practice item P2-20', []),
    'P2-21': ('practice item P2-21', []),
    'SC2-1': ('section-check item SC2-1', []),
    'SC2-2': ('section-check item SC2-2', []),
    'SC2-3': ('section-check item SC2-3', []),
    'SC2-4': ('section-check item SC2-4', []),
    'SC2-5': ('section-check item SC2-5', []),
    'SC2-6': ('section-check item SC2-6', []),
    'SC2-7': ('section-check item SC2-7', []),
    'SC2-8': ('section-check item SC2-8', []),
    'SC2-9': ('section-check item SC2-9', []),
    'term:balance sheet': ("term-bridge row 'balance sheet'", []),
    'term:callable debt': ("term-bridge row 'callable debt'", []),
    'term:classified balance sheet': ("term-bridge row 'classified balance sheet'", []),
    'term:covenant': ("term-bridge row 'covenant'", []),
    'term:current assets': ("term-bridge row 'current assets'", []),
    'term:current liabilities': ("term-bridge row 'current liabilities'", []),
    'term:current portion of long-term debt': ("term-bridge row 'current portion of long-term debt'", []),
    'term:current ratio': ("term-bridge row 'current ratio'", []),
    'term:financial flexibility': ("term-bridge row 'financial flexibility'", []),
    'term:grace period': ("term-bridge row 'grace period'", []),
    'term:liquidity': ("term-bridge row 'liquidity'", []),
    'term:loss contingency': ("term-bridge row 'loss contingency'", []),
    'term:operating cycle': ("term-bridge row 'operating cycle'", []),
    'term:refinancing': ("term-bridge row 'refinancing'", []),
    'term:restricted cash': ("term-bridge row 'restricted cash'", []),
    'term:right of setoff': ("term-bridge row 'right of setoff'", []),
    'term:solvency': ("term-bridge row 'solvency'", []),
    'term:subjective acceleration clause': ("term-bridge row 'subjective acceleration clause'", []),
    'term:subsequent events': ("term-bridge row 'subsequent events'", []),
    'term:waiver': ("term-bridge row 'waiver'", []),
    'term:working capital': ("term-bridge row 'working capital'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C2-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P2-05': 'it sends the reader to F02-02, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'P2-06': 'it sends the reader to F02-02, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC2-4': 'it sends the reader to F02-02, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
