# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C3-1': ('case item C3-1', []),
    'C3-2': ('case item C3-2', []),
    'C3-3': ('case item C3-3', []),
    'C3-4': ('case item C3-4', []),
    'C3-5': ('case item C3-5', []),
    'C3-6': ('case item C3-6', []),
    'P3-01': ('practice item P3-01', []),
    'P3-02': ('practice item P3-02', []),
    'P3-03': ('practice item P3-03', []),
    'P3-04': ('practice item P3-04', []),
    'P3-05': ('practice item P3-05', []),
    'P3-06': ('practice item P3-06', []),
    'P3-07': ('practice item P3-07', []),
    'P3-08': ('practice item P3-08', []),
    'P3-09': ('practice item P3-09', []),
    'P3-10': ('practice item P3-10', []),
    'P3-11': ('practice item P3-11', []),
    'P3-12': ('practice item P3-12', []),
    'P3-13': ('practice item P3-13', []),
    'P3-14': ('practice item P3-14', []),
    'P3-15': ('practice item P3-15', []),
    'P3-16': ('practice item P3-16', []),
    'P3-17': ('practice item P3-17', []),
    'P3-18': ('practice item P3-18', []),
    'P3-19': ('practice item P3-19', []),
    'P3-20': ('practice item P3-20', []),
    'P3-21': ('practice item P3-21', []),
    'SC3-1': ('section-check item SC3-1', []),
    'SC3-2': ('section-check item SC3-2', []),
    'SC3-3': ('section-check item SC3-3', []),
    'SC3-4': ('section-check item SC3-4', []),
    'SC3-5': ('section-check item SC3-5', []),
    'SC3-6': ('section-check item SC3-6', []),
    'SC3-7': ('section-check item SC3-7', []),
    'SC3-8': ('section-check item SC3-8', []),
    'SC3-9': ('section-check item SC3-9', []),
    'term:accumulated other comprehensive income (aoci)': ("term-bridge row 'accumulated other comprehensive income (AOCI)'", []),
    'term:component of an entity': ("term-bridge row 'component of an entity'", []),
    'term:comprehensive income': ("term-bridge row 'comprehensive income'", []),
    'term:discontinued operation': ("term-bridge row 'discontinued operation'", []),
    'term:earnings per share (eps)': ("term-bridge row 'earnings per share (EPS)'", []),
    'term:function of expense': ("term-bridge row 'function of expense'", []),
    'term:income from continuing operations': ("term-bridge row 'income from continuing operations'", []),
    'term:income statement': ("term-bridge row 'income statement'", []),
    'term:intraperiod tax allocation': ("term-bridge row 'intraperiod tax allocation'", []),
    'term:multi-step income statement': ("term-bridge row 'multi-step income statement'", []),
    'term:operating income': ("term-bridge row 'operating income'", []),
    'term:other comprehensive income (oci)': ("term-bridge row 'other comprehensive income (OCI)'", []),
    'term:other income and expense': ("term-bridge row 'other income and expense'", []),
    'term:reclassification adjustment': ("term-bridge row 'reclassification adjustment'", []),
    'term:single-step income statement': ("term-bridge row 'single-step income statement'", []),
    'term:strategic shift': ("term-bridge row 'strategic shift'", []),
    'term:unusual or infrequent item': ("term-bridge row 'unusual or infrequent item'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C3-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'C3-6': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P3-18': 'it sends the reader to F03-09, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'P3-21': 'it sends the reader to F03-02, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC3-3': 'it sends the reader to F03-02, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
