# -*- coding: utf-8 -*-
"""Handout 11.2, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '11.2',
 'n': 2,
 'pages': 7,
 'title': 'Steps 1 and 2: the contract and its performance obligations',
 'sub': 'section 11.2 of the book',
 'covers': ['sec:11.2',
            'p:P11-07',
            'p:P11-08',
            'p:P11-09',
            'p:P11-10',
            'sc:P11-07',
            'p:P11-11',
            'p:P11-12',
            'term:performance obligation',
            'term:principal',
            'term:output method',
            'term:incremental costs of obtaining a contract'],
 'skills': [('read2', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['Steps 1 and 2: the contract and its performance obligations',
             'a figure to read · Step · Suppose: sales of 2,400,000 with a '
             '3% volume reb',
             'Customers earn loyalty points worth a discount on future '
             'purchases that they would not otherwise get. The points are:'],
            ['The words this section uses precisely',
             'Item · The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['Fixed price; no variable amounts, no financing '
                       'component, no payments to GreenBasket. Oil and '
                       'dispenser: at delivery (',
                       15,
                       '). Maintenance: over 24 months (',
                       11,
                       '). GAAP, probable means likely to occur: in '
                       'practice, about 75% or more.'],
             'bank': ['output method',
                      'over time',
                      'breakage',
                      'point in time'],
             'a': 'point in time · over time',
             'one': True,
             'why': 'The book writes: “Fixed price; no variable amounts, no '
                    'financing component, no payments to GreenBasket. Oil '
                    'and dispenser: at delivery (point in time). '
                    'Maintenance: over 24 months (over time). GAAP, probable '
                    'means likely to occur: in practice, about 75% or '
                    'more.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['Olive oil, the dispenser and maintenance can each be '
                       'bought separately and are not highly interdependent. '
                       'Fixed price; no variable amounts, no financing '
                       'component, no payments to GreenBasket. Oil and '
                       'dispenser: at delivery (',
                       15,
                       '). Maintenance: over 24 months (',
                       11,
                       ').'],
             'bank': ['over time',
                      'breakage',
                      'point in time',
                      'output method'],
             'a': 'point in time · over time',
             'one': True,
             'why': 'The book writes: “Olive oil, the dispenser and '
                    'maintenance can each be bought separately and are not '
                    'highly interdependent. Fixed price; no variable '
                    'amounts, no financing component, no payments to '
                    'GreenBasket. Oil and dispenser: at delivery (point in '
                    'time). Maintenance: over 24 months (over time).”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['Oil and dispenser: at delivery (',
                       15,
                       '). Maintenance: over 24 months (',
                       11,
                       '). GAAP, probable means likely to occur: in '
                       'practice, about 75% or more. IFRS 15 uses probable '
                       'to mean more likely than not.'],
             'bank': ['over time',
                      'output method',
                      'breakage',
                      'point in time'],
             'a': 'point in time · over time',
             'one': True,
             'why': 'The book writes: “Oil and dispenser: at delivery (point '
                    'in time). Maintenance: over 24 months (over time). '
                    'GAAP, probable means likely to occur: in practice, '
                    'about 75% or more. IFRS 15 uses probable to mean more '
                    'likely than not.”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['performance obligation', ''],
              ['principal', ''],
              ['output method', ''],
              ['incremental costs of obtaining a contract', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle',
           'A',
           'Steps 1 and 2: the contract and its performance obligations'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f2'),
          ('panel',
           'Step — the book’s own table',
           [['Step', "Orontes's analysis", 'Result (whole USD)'],
            ['1. Identify the contract',
             'A signed agreement for olive oil, a dispenser and maintenance; '
             'payment terms clear; collection probable.',
             'Contract exists'],
            ['2. Identify the performance obligations',
             'Olive oil, the dispenser and maintenance can each be bought '
             'separately and are not highly interdependent.',
             'Three obligations'],
            ['3. Determine the transaction price',
             'Fixed price; no variable amounts, no financing component, no '
             'payments to GreenBasket.',
             '1,080,000'],
            ['4. Allocate the price',
             'Relative standalone selling prices totalling 1,200,000; each '
             'obligation gets 90%.',
             '810,000 / 180,000 / 90,000'],
            ['5. Recognize revenue',
             'Oil and dispenser: at delivery (point in time). Maintenance: '
             'over 24 months (over time).',
             '2026: 515,250']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which step does the book pair with “A signed agreement '
                  'for olive oil, a dispenser and maintenance; payment terms '
                  'clear; collection probable.”?',
             'o': ['4. Allocate the price',
                   '2. Identify the performance obligations',
                   '1. Identify the contract',
                   '3. Determine the transaction price'],
             'a': 'C',
             'why': 'The book’s own table pairs 1. Identify the contract '
                    'with “A signed agreement for olive oil, a dispenser and '
                    'maintenance; payment terms clear; collection '
                    'probable.”.'},
            {'t': 'MCQ',
             'q': 'Which step does the book pair with “Olive oil, the '
                  'dispenser and maintenance can each be bought separately '
                  'and are not highly interdependent.”?',
             'o': ['1. Identify the contract',
                   '5. Recognize revenue',
                   '2. Identify the performance obligations',
                   '3. Determine the transaction price'],
             'a': 'C',
             'why': 'The book’s own table pairs 2. Identify the performance '
                    'obligations with “Olive oil, the dispenser and '
                    'maintenance can each be bought separately and are not '
                    'highly interdependent.”.'},
            {'t': 'MCQ',
             'q': 'Which step does the book pair with “Fixed price; no '
                  'variable amounts, no financing component, no payments to '
                  'GreenBasket.”?',
             'o': ['1. Identify the contract',
                   '5. Recognize revenue',
                   '3. Determine the transaction price',
                   '2. Identify the performance obligations'],
             'a': 'C',
             'why': 'The book’s own table pairs 3. Determine the transaction '
                    'price with “Fixed price; no variable amounts, no '
                    'financing component, no payments to GreenBasket.”.'},
            {'t': 'MCQ',
             'q': 'Which step does the book pair with “Relative standalone '
                  'selling prices totalling 1,200,000; each obligation gets '
                  '90%.”?',
             'o': ['1. Identify the contract',
                   '5. Recognize revenue',
                   '4. Allocate the price',
                   '2. Identify the performance obligations'],
             'a': 'C',
             'why': 'The book’s own table pairs 4. Allocate the price with '
                    '“Relative standalone selling prices totalling '
                    '1,200,000; each obligation gets 90%.”.'},
            {'t': 'TF',
             'q': 'The book gives the Result (whole USD) of 1. Identify the '
                  'contract as “Contract exists”.',
             'a': 'T',
             'why': 'The book pairs 1. Identify the contract with “Contract '
                    'exists”.'},
            {'t': 'TF',
             'q': 'The book gives the Result (whole USD) of 2. Identify the '
                  'performance obligations as “810,000 / 180,000 / 90,000”.',
             'a': 'F',
             'why': 'The book pairs 2. Identify the performance obligations '
                    'with “Three obligations”, not with “810,000 / 180,000 / '
                    '90,000”.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Customers earn loyalty points worth a discount on future '
                  'purchases that they would not otherwise get. The points '
                  'are:',
             'o': ['a separate performance obligation (a material right)',
                   'a marketing expense',
                   'ignored until redeemed',
                   'a reduction of cost of goods sold'],
             'a': 'A',
             'why': 'A material right is part of what the customer pays for. '
                    'B is wrong: Part of the price must be allocated to the '
                    'points. C is wrong: The points are a promise made at '
                    'the sale.',
             'src': 'P11-07'},
            {'t': 'MCQ',
             'q': 'A gym charges a nonrefundable joining fee when a customer '
                  'signs a one-year membership. The fee is:',
             'o': ['revenue at once, because it is nonrefundable',
                   'a liability until the customer leaves',
                   'deferred and recognized over the membership period',
                   'deducted from expenses'],
             'a': 'C',
             'why': 'The fee relates to future services, not to a distinct '
                    'service at signing. A is wrong: Nonrefundable does not '
                    'mean earned. B is wrong: It is earned over the year, '
                    'not held until the customer leaves.',
             'src': 'P11-08'},
            {'t': 'MCQ',
             'q': 'A customer will pay for goods two years after delivery, '
                  'and the price includes a large interest element. The '
                  'company should:',
             'o': ['recognize the full price as revenue at delivery',
                   'recognize revenue when cash is received',
                   'adjust the transaction price for the significant '
                   'financing component',
                   'ignore the interest because payment is certain'],
             'a': 'C',
             'why': 'The practical expedient applies only when the gap is '
                    'one year or less. A is wrong: Part of the price is '
                    'interest, not revenue. B is wrong: Revenue follows '
                    'control, not cash.',
             'src': 'P11-10'}]),
          ('panel',
           'Suppose: sales of 2,400,000 with a 3% volume reb — the extract '
           'for the question that follows',
           [['Suppose: sales of 2,400,000 with a 3% volume reb',
             'How it works',
             'Revenue (whole USD)'],
            ['Most likely amount',
             'The rebate is all or nothing, so use the single most likely '
             'outcome: the rebate is earned (70% likely).',
             '2,328,000'],
            ['Expected value',
             'Probability-weighted: 70% × 72,000 = 50,400 rebate. Best when '
             'there are many possible outcomes.',
             '2,349,600'],
            ['Constraint',
             'Include variable amounts only if a significant reversal of '
             'revenue is not probable later.',
             'Applies to both']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. '
                  "Orontes's rebate is all or nothing. What revenue does "
                  'Orontes recognize on the sales (whole USD)?',
             'o': ['72,000', '2,328,000', '2,349,600', '2,400,000'],
             'a': 'B',
             'why': 'For an all-or-nothing outcome, the most likely amount '
                    'is the better estimate. A is wrong: This is the rebate, '
                    'not the revenue. C is wrong: Expected value suits many '
                    'possible outcomes, not a single threshold.',
             'src': 'P11-09'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Customers earn loyalty points worth a discount on future '
           'purchases that they would not otherwise get. The points are:',
           ['a separate performance obligation (a material right)',
            'a marketing expense',
            'ignored until redeemed',
            'a reduction of cost of goods sold'],
           'A',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'A material right is part of what the customer pays for. B is '
           'wrong: Part of the price must be allocated to the points. C is '
           'wrong: The points are a promise made at the sale.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Item — the book’s own table',
           [['Item', 'Answer'],
            ['Revenue recognized', '(1,000 − 50) × $20 = 19,000'],
            ['Refund liability', '50 × $20 = 1,000'],
            ['Asset: right to recover products',
             '50 × $12 = 600, shown separately from the refund liability'],
            ['Cost of goods sold', '(1,000 − 50) × $12 = 11,400']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['performance obligation', 'التزام الأداء'],
            ['principal', 'الأصيل'],
            ['output method', 'طريقة المخرجات'],
            ['incremental costs of obtaining a contract',
             'التكاليف الإضافية للحصول على العقد']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MATCH',
             'q': 'Write the letter of the Arabic term beside each English '
                  'term. Every term is used once.',
             'left': ['output method',
                      'incremental costs of obtaining a contract',
                      'performance obligation',
                      'principal'],
             'right': ['التزام الأداء',
                       'طريقة المخرجات',
                       'الأصيل',
                       'التكاليف الإضافية للحصول على العقد'],
             'a': ['B', 'D', 'A', 'C'],
             'whys': ['', '', '', '']},
            {'t': 'MCQ',
             'q': 'Which answer does the book give for Revenue recognized?',
             'o': ['(1,000 − 50) × $12 = 11,400',
                   '(1,000 − 50) × $20 = 19,000',
                   '50 × $12 = 600, shown separately from the refund '
                   'liability',
                   '50 × $20 = 1,000'],
             'a': 'B',
             'why': 'The book’s own table gives (1,000 − 50) × $20 = 19,000 '
                    'as the answer of Revenue recognized.'},
            {'t': 'MCQ',
             'q': 'Which answer does the book give for Refund liability?',
             'o': ['50 × $20 = 1,000',
                   '(1,000 − 50) × $20 = 19,000',
                   '50 × $12 = 600, shown separately from the refund '
                   'liability',
                   '(1,000 − 50) × $12 = 11,400'],
             'a': 'A',
             'why': 'The book’s own table gives 50 × $20 = 1,000 as the '
                    'answer of Refund liability.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “50 × $12 = 600, shown '
                  'separately from the refund liability”?',
             'o': ['Asset: right to recover products',
                   'Revenue recognized',
                   'Refund liability',
                   'Cost of goods sold'],
             'a': 'A',
             'why': 'The book’s own table pairs Asset: right to recover '
                    'products with “50 × $12 = 600, shown separately from '
                    'the refund liability”.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'A U.S. retailer collects 5% sales tax from customers for '
                  'the state. Under its policy election, the tax is:',
             'o': ['included in revenue',
                   'excluded from revenue and recorded as a liability',
                   'recorded as an expense when paid',
                   'recorded in OCI'],
             'a': 'B',
             'why': 'Amounts collected for third parties are not revenue. A '
                    'is wrong: The tax belongs to the state. C is wrong: It '
                    "is not the retailer's cost.",
             'src': 'P11-11'},
            {'t': 'MCQ',
             'q': 'When may a company use the residual approach to estimate '
                  'a standalone selling price?',
             'o': ['Only when the price is highly variable or uncertain',
                   'Always, because it is the simplest',
                   'Whenever the contract includes a discount',
                   'Never under U.S. GAAP'],
             'a': 'A',
             'why': 'The residual approach is a limited exception. B is '
                    'wrong: It is not a default method. C is wrong: A '
                    'discount is normally shared by all obligations.',
             'src': 'P11-12'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f2',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['performance obligation',
            'principal',
            'output method',
            'incremental costs of obtaining a contract'],
           'Step 1: identify the contract. A contract exists only if the '
           "parties have approved it and are committed to it, each party's "
           'rights and the payment terms can be identified, and the contract '
           'has commercial substance. Finally, it must be probable that the '
           'company will collect substantially all of the consideration.')]}
