# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C17-1': ('case item C17-1', []),
    'C17-2': ('case item C17-2', []),
    'C17-3': ('case item C17-3', []),
    'C17-4': ('case item C17-4', []),
    'C17-5': ('case item C17-5', []),
    'C17-6': ('case item C17-6', []),
    'P17-01': ('practice item P17-01', []),
    'P17-02': ('practice item P17-02', []),
    'P17-03': ('practice item P17-03', []),
    'P17-04': ('practice item P17-04', []),
    'P17-05': ('practice item P17-05', []),
    'P17-06': ('practice item P17-06', []),
    'P17-07': ('practice item P17-07', []),
    'P17-08': ('practice item P17-08', []),
    'P17-09': ('practice item P17-09', []),
    'P17-10': ('practice item P17-10', []),
    'P17-11': ('practice item P17-11', []),
    'P17-12': ('practice item P17-12', []),
    'P17-13': ('practice item P17-13', []),
    'P17-14': ('practice item P17-14', []),
    'P17-15': ('practice item P17-15', []),
    'P17-16': ('practice item P17-16', []),
    'SC17-1': ('section-check item SC17-1', []),
    'SC17-10': ('section-check item SC17-10', []),
    'SC17-11': ('section-check item SC17-11', []),
    'SC17-2': ('section-check item SC17-2', []),
    'SC17-3': ('section-check item SC17-3', []),
    'SC17-4': ('section-check item SC17-4', []),
    'SC17-5': ('section-check item SC17-5', []),
    'SC17-6': ('section-check item SC17-6', []),
    'SC17-7': ('section-check item SC17-7', []),
    'SC17-8': ('section-check item SC17-8', []),
    'SC17-9': ('section-check item SC17-9', []),
    'term:cash-generating unit': ("term-bridge row 'cash-generating unit'", []),
    'term:component depreciation': ("term-bridge row 'component depreciation'", []),
    'term:defined benefit plan': ("term-bridge row 'defined benefit plan'", []),
    'term:development costs': ("term-bridge row 'development costs'", []),
    'term:fair value less costs of disposal': ("term-bridge row 'fair value less costs of disposal'", []),
    'term:graded vesting': ("term-bridge row 'graded vesting'", []),
    'term:lower of cost and net realizable value (lcnrv)': ("term-bridge row 'lower of cost and net realizable value (LCNRV)'", []),
    'term:net realizable value (nrv)': ("term-bridge row 'net realizable value (NRV)'", []),
    'term:prior service cost': ("term-bridge row 'prior service cost'", []),
    'term:recoverability test': ("term-bridge row 'recoverability test'", []),
    'term:recoverable amount': ("term-bridge row 'recoverable amount'", []),
    'term:remeasurements': ("term-bridge row 'remeasurements'", []),
    'term:research and development (r&d)': ("term-bridge row 'research and development (R&D)'", []),
    'term:revaluation model': ("term-bridge row 'revaluation model'", []),
    'term:revaluation surplus': ("term-bridge row 'revaluation surplus'", []),
    'term:value in use': ("term-bridge row 'value in use'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C17-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'C17-6': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'SC17-11': 'it sends the reader to F17-07, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC17-5': 'it sends the reader to F17-04, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
