"""A1.1 Unit 1 - The Yellow Building - fifteen figures, as data."""
FIGURES = {
"fig_a11_u01_p00_v01": dict(type='V1', height=900, storey_h=116,
 title='Escola Monte, Monday, 9.05',
 sub='Fourteen things to find. One of the cats has a name tag, and you can read it.',
 alt='A yellow four-storey language school on a steep Lisbon street, open at one side to show a '
     'reception desk with a queue, a classroom above it, and a cafe next door with tables outside.',
 sky='#DCE6EC', ground='#B6A894', ground_line=700,
 buildings=[dict(x=20, w=560, storeys=4, colour='#E8CE7A', cutaway=True,
     floor_labels=['room 3 - Teresa teaches here',
                   'the office',
                   'reception - Ana, and three people waiting',
                   'the steps - two cats'],
     label='Escola Monte'),
   dict(x=660, w=360, storeys=2, colour='#C9BFA8', label="Marco's cafe, four tables"),
   dict(x=1120, w=460, storeys=3, colour='#BFB6A4', label='the top of the street, a tram')],
 props=[dict(kind='tree', x=620, y=700, s=1.0),
   dict(kind='table', x=760, y=700, s=1.2), dict(kind='table', x=880, y=700, s=1.2),
   dict(kind='hoarding', x=1070, y=700, s=.9),
   dict(kind='box', x=1500, y=700, s=1.0),
   dict(kind='sign', x=120, y=700, s=.7, text='9:05'),
   dict(kind='sign', x=1280, y=700, s=.7, text='TRAM')],
 people=[dict(x=200, y=700, h=84, skin=1, cloth=2, hair='bun', arm='hold'),
   dict(x=320, y=700, h=84, skin=4, cloth=3, hair='short', arm='down'),
   dict(x=430, y=700, h=84, skin=0, cloth=1, hair='long', arm='hold'),
   dict(x=820, y=700, h=84, skin=3, cloth=0, hair='cap', arm='point'),
   dict(x=1400, y=700, h=84, skin=2, cloth=4, hair='grey', arm='folded')],
 names=[dict(x=200, t='Ana - reception, every day'),
   dict(x=320, t='Yusuf - he is new'),
   dict(x=430, t='Lin - three years here'),
   dict(x=820, t='Marco - the cafe, next door'),
   dict(x=1400, t='Teresa - she is in room 3'),
   dict(x=120, t='the clock: five past nine'),
   dict(x=1280, t='the tram, at the top'),
   dict(x=1070, t='the noticeboard')],
 markers=[dict(x=200, y=582), dict(x=320, y=582), dict(x=430, y=582), dict(x=820, y=582),
   dict(x=1400, y=582), dict(x=120, y=636), dict(x=1280, y=636), dict(x=1070, y=650),
   dict(x=760, y=656), dict(x=880, y=656), dict(x=620, y=640), dict(x=1500, y=652),
   dict(x=300, y=466), dict(x=300, y=350)]),

"fig_a11_u01_p01_v08": dict(type='V8', height=760,
 title='Six people, and what joins them',
 sub='Not a list of jobs. A ring of people, and a word on every line.',
 alt='Six faces in a ring with their names and countries, joined by labelled lines reading '
     'teaches, works next door, sits next to, lives with, and belongs to nobody.',
 nodes={
  'ana': dict(x=200, y=250, short='A', name='Ana', sub='Portugal', colour='#1F4E5F'),
  'ter': dict(x=200, y=560, short='T', name='Teresa', sub='Portugal', colour='#2E6F5E'),
  'yus': dict(x=580, y=390, short='Y', name='Yusuf', sub='Egypt', colour='#C86B2B'),
  'lin': dict(x=960, y=250, short='L', name='Lin', sub='Korea', colour='#D9A441'),
  'mar': dict(x=1300, y=430, short='M', name='Marco', sub='Brazil', r=52, colour='#8C6A9E'),
  'bru': dict(x=960, y=600, short='B', name='Bruno', sub='the cat', r=46, colour='#9AA7AE')},
 edges=[dict(a='ter', b='yus', label='teaches', sw=6),
   dict(a='ter', b='lin', label='teaches', sw=6),
   dict(a='ana', b='yus', label='gives him the key', sw=5),
   dict(a='yus', b='lin', label='sits next to', sw=6),
   dict(a='ana', b='mar', label='works next door', sw=5),
   dict(a='bru', b='mar', label='belongs to nobody', sw=2, dash='6 6', colour='#9AA7AE')]),

"fig_a11_u01_p01_v02a": dict(type='V2', height=780,
 title='The reception desk, in section',
 sub='Twelve things. Twelve words. Put each word under the right one.',
 alt='A cutaway of a reception desk showing the pigeonholes, the diary, the computer, the '
     'noticeboard and the counter, each with an empty label.',
 floors=[dict(was='on the wall', now='pigeonholes - one for every name', year='', fill='#F3EADA'),
   dict(was='on the desk', now='the diary, the phone, the computer', year='', fill='#E8EEF0'),
   dict(was='under the desk', now='the bags, the box, the cat', year='', fill='#EFE6DC'),
   dict(was='behind it', now='Ana, and the key cupboard', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='name · address · email'),
   dict(at=0.38, text='class · teacher · student'),
   dict(at=0.62, text='bag · phone · people'),
   dict(at=0.88, text='man · woman · friend')]),

"fig_a11_u01_p02_v07": dict(type='V7', height=780,
 title='Monday morning, nine o\'clock',
 sub='He is new. She is here every day.',
 alt='A new student and a receptionist at a desk, speaking, with short speech balloons using am, '
     'is and are.',
 bg='#EDE6D8',
 set=[dict(kind='table', x=700, y=660, s=1.5), dict(kind='doc', x=700, y=590)],
 people=[dict(x=470, h=240, skin=4, cloth=3, hair='short', arm='hold', facing='right',
   label='Yusuf', role='he is new',
   says=['Hello. I am Yusuf.', 'I am from Egypt.']),
  dict(x=980, h=238, skin=1, cloth=2, hair='bun', arm='point', facing='left',
   label='Ana', role='she is here every day',
   says=['You are in room 3. Teresa is your teacher.'])]),

"fig_a11_u01_p03_v09a": dict(type='V9', kind='branch', height=620,
 title='Who gets which word',
 sub='One person speaking. One person spoken about. More than one.',
 alt='A branching diagram sorting the subject pronouns into three groups, one for am, one for is '
     'and one for are.',
 root='I / he / they ...',
 branches=[dict(label='am - one person, and it is me', colour='#C86B2B',
     example='I am a student.'),
   dict(label='is - one person or thing, spoken about', colour='#1F4E5F',
     example='he · she · it -- She is a teacher.'),
   dict(label='are - more than one, or the person in front of you', colour='#2E6F5E',
     example='you · we · they -- They are in room 3.')]),

"fig_a11_u01_p03_v09b": dict(type='V9', kind='mirror', height=620,
 title='Not, and the swap',
 sub='For a negative, put not after the verb. For a question, swap the first two words.',
 alt='Two sentence diagrams showing not inserted after the verb, and the verb and the pronoun '
     'changing places to make a question.',
 active=dict(parts=[dict(w=18, role='agent', text='She'),
   dict(w=18, role='action', text='is'),
   dict(w=20, role='hidden', text='not'),
   dict(w=34, role='affected', text='a teacher')]),
 passive=dict(parts=[dict(w=18, role='action', text='Is'),
   dict(w=18, role='agent', text='she'),
   dict(w=34, role='affected', text='a teacher'),
   dict(w=20, role='hidden', text='? the first two swap')]),
 rule='Negative: put not straight after am, is or are. Question: the verb goes first and the '
      'person goes second. Nothing else moves.'),

"fig_a11_u01_p03_v11": dict(type='V11', height=680,
 title='The verb that goes missing',
 alt='Two panels comparing she teacher with she is a teacher.',
 wrong=dict(sentence='She teacher.',
            boundary=0.34, boundary_label='She',
            event=0.60, event_label='and then a noun, with no verb between them',
            why='Many languages join a person to a job with nothing in between. English will not '
                'do it. Without is there is no sentence, only two words, and a listener keeps '
                'waiting for the rest.'),
 right=dict(sentence='She is a teacher.',
            boundary=0.34, boundary_label='She',
            event=0.52, event_label='is - the verb, and then a',
            why='Two small words do the work: is joins the person to the job, and a says one of '
                'many. English needs both, every time, in every sentence of this kind.'),
 misconception='This is the commonest sentence in the first month of English and the commonest '
               'thing to leave out. Say it aloud ten times: She IS A teacher.'),

"fig_a11_u01_p04_v04a": dict(type='V4', height=720,
 title='Two name badges',
 sub='The same badge, filled in twice. One of them has six mistakes.',
 alt='Two name badges side by side, one correctly completed and one with the first and family '
     'names reversed, no capital letters and the country missing.',
 differences=6, prompt='Find the six. Which one would you give to a new student?',
 left=dict(label='right', art=[
   dict(kind='block', x=150, y=120, w=230, bh=26, colour='#2E6F5E'),
   dict(kind='block', x=150, y=80, w=180, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=150, y=44, w=140, bh=22, colour='#9AA7AE'),
   dict(kind='label', x=300, y=210, text='Mariana COSTA · Brazil · room 3', colour='#2E6F5E')]),
 right=dict(label='wrong', art=[
   dict(kind='block', x=150, y=120, w=230, bh=26, colour='#A8372E'),
   dict(kind='block', x=150, y=80, w=180, bh=22, colour='#9AA7AE'),
   dict(kind='gap', x=150, y=44, w=140, bh=22),
   dict(kind='label', x=300, y=210, text='costa mariana · room3 · (no country)',
        colour='#A8372E')])),

"fig_a11_u01_p05_v05": dict(type='V5', height=900,
 title='The sign-in sheet',
 sub='Everybody writes on it and nobody reads it. Today it has eight lines.',
 alt='A school sign-in sheet with columns for name in capitals, room and time, filled in '
     'by eight people, with one line left incomplete.',
 rows=[dict(t='org', text='ESCOLA MONTE  -  SIGN-IN  -  MONDAY'),
   dict(t='grid', cols=['NAME (CAPITALS)', 'ROOM', 'TIME'],
     data=[['SILVA, ANA', 'reception', '08.30'],
           ['LOPES, TERESA', '3', '08.45'],
           ['KIM, LIN', '3', '08.52'],
           ['OKONKWO, CHIKA', '2', '08.55'],
           ['DEMIR, EMRE', '2', '09.00'],
           ['yusuf', '?', '09.05'],
           ['NOWAK, PIOTR', '3', '09.06'],
           ['SANTOS, MARCO', 'cafe', '07.10']]),
   dict(t='rule'),
   dict(t='head', text='THE RULES AT THE TOP OF THE SHEET'),
   dict(t='kv', k='Family name first', v='yes', mono=False),
   dict(t='kv', k='Capital letters', v='yes', mono=False),
   dict(t='kv', k='Room number', v='yes', mono=False),
   dict(t='kv', k='Signature', v='no - this is not a contract', mono=False),
   dict(t='rule'),
   dict(t='sign', text='THE SIXTH LINE:'),
   dict(t='para', text='"yusuf" - one name, small letters, no room. He arrived at 9.05 and '
     'nobody had told him any of the three rules.')],
 callouts=[dict(at=0.16, text='Family name, then first name. Every line but one'),
   dict(at=0.42, text='Five people before nine o\'clock'),
   dict(at=0.50, text='One name, no capitals, no room'),
   dict(at=0.72, text='No signature. It is a list, not a contract'),
   dict(at=0.93, text='Nobody told him. That is the whole of Part 9')]),

"fig_a11_u01_p06_v03a": dict(type='V3',
 title='One room number, six places',
 sub='The same number. You have to read it and say it in six different ways.',
 alt='Six panels showing a room number as it appears on a door, on a form, on a phone screen, '
     'in speech, in a list and said aloud.',
 panels=[
  dict(caption='On the door: 3', art=[dict(kind='doc', x=160, y=0)]),
  dict(caption='On the form: Room ___', art=[dict(kind='doc', x=160, y=0),
     dict(kind='gap', x=160, y=20, w=50, bh=22)]),
  dict(caption='On the phone: "R3"', art=[dict(kind='block', x=160, y=10, w=70, bh=100,
     colour='#1F4E5F')]),
  dict(caption='Said to you: "room three"', art=[dict(kind='person', x=160, y=0, h=110,
     skin=1, cloth=2)]),
  dict(caption='In the list: 3 (Lopes)', art=[dict(kind='doc', x=160, y=0)]),
  dict(caption='Said by you: "I am in room three"', art=[dict(kind='person', x=160, y=0,
     h=110, skin=4, cloth=3, arm='point')])]),

"fig_a11_u01_p07_v10": dict(type='V10', kind='mouth', height=680,
 title='A short sound and a long one',
 sub='The tongue hardly moves. The difference is the length, and it changes the word.',
 alt='Two mouth cross-sections side by side showing the tongue position for the short i and the '
     'long ee, with minimal pairs.',
 sounds=[
  dict(ipa='/i/', desc='short, and the tongue is a little lower',
       examples='ship · this · it · live · fill', length='short',
       tongue=dict(high=.62, front=.72), lips='neutral'),
  dict(ipa='/ii/', desc='long, and the tongue is high and forward',
       examples='sheep · these · eat · leave · feel', length='long',
       tongue=dict(high=.88, front=.90), lips='spread')]),

"fig_a11_u01_p09_v02b": dict(type='V2', height=760,
 title='The desk from behind',
 sub='Four layers. The learner only ever sees the first one.',
 alt='A cutaway of the reception desk seen from behind, showing the diary, the pigeonholes, the '
     'key cupboard and the forms that have not been entered.',
 floors=[dict(was='what you see', now='A counter, and somebody who says good morning', year='',
     fill='#F3EADA'),
   dict(was='the diary', now='Who is expected, and who has not come', year='', fill='#E8EEF0'),
   dict(was='the pigeonholes', now='One for every name, and three with no name on them',
     year='', fill='#EFE6DC'),
   dict(was='the tray', now='Eleven forms, filled in, not yet typed in anywhere', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The only layer a new student knows about'),
   dict(at=0.38, text='And this is how she knew Yusuf was coming'),
   dict(at=0.62, text='Three with no name. Nobody has asked who they are for'),
   dict(at=0.88, text='Eleven forms. The system is a tray')]),

"fig_a11_u01_p09_v03b": dict(type='V3',
 title='Spelling a name out loud',
 sub='Five steps. Step four is the one everybody forgets.',
 alt='Five panels showing how to spell a name aloud: say it, slow down, spell it, check the hard '
     'letters, and say it again.',
 panels=[
  dict(caption='1 Say the whole name first', art=[dict(kind='person', x=150, y=0, h=112,
     skin=4, cloth=3)]),
  dict(caption='2 "How do you spell it?"', art=[dict(kind='person', x=150, y=0, h=110,
     skin=1, cloth=2, arm='point')]),
  dict(caption='3 Spell it slowly, in twos', art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='4 Check the ones that sound alike', art=[dict(kind='doc', x=150, y=0),
     dict(kind='arrow', x=150, y=130)]),
  dict(caption='5 Say the whole name again', art=[dict(kind='person', x=150, y=0, h=112,
     skin=4, cloth=3, arm='hold')])]),

"fig_a11_u01_p10_v12": dict(type='V12', height=820,
 title='One morning at Escola Monte',
 sub='Half the class has the sign-in sheet. Half has the pigeonholes. Rebuild the morning.',
 alt='An infographic of one school morning from half past eight to half past nine, showing who '
     'arrived, who was expected, and who had been told what.',
 span=['08.30', '09.30'], ticks=5,
 tick_labels=['08.30', '08.45', '09.00', '09.15', '09.30'],
 bands=[dict(name='Reception', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.42}, label='Ana alone, no queue', colour='#2E6F5E'),
   dict(**{'from': 0.42, 'to': 0.78}, label='three waiting', colour='#D9A441'),
   dict(**{'from': 0.78, 'to': 1.0}, label='quiet again', colour='#2E6F5E')]),
  dict(name='Room 3', type='bars', items=[
   dict(**{'from': 0.28, 'to': 1.0}, label='Teresa, and the class filling up',
     colour='#1F4E5F')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.05, label='Ana signs in. 08.30', colour='#2E6F5E'),
   dict(at=0.38, label='Lin signs in, family name first', colour='#1F4E5F'),
   dict(at=0.62, label='Yusuf signs in: one name, no room', colour='#A8372E'),
   dict(at=0.70, label='Teresa starts. Yusuf is not there', colour='#C86B2B'),
   dict(at=0.92, label='Ana walks him to room 3', colour='#2E6F5E')]),
  dict(name='People in room 3', type='line',
   points=[(0, 0), (0.3, 2), (0.55, 6), (0.75, 8), (1.0, 9)], end_label='9'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.20, label='show him the three rules at the top of the sheet'),
   dict(at=0.50, label='put a name on the three empty pigeonholes'),
   dict(at=0.84, label='ask him how to spell it')])]),

"fig_a11_u01_p11_v04b": dict(type='V4', height=720,
 title='Two ways to put the names on the pigeonholes',
 sub='Learner A has the list as it is. Learner B has the list by first name.',
 alt='Two sets of pigeonhole labels compared, one ordered by family name and one by first name, '
     'with the same eleven people.',
 differences=6, prompt='Which one would you find your own name in faster, and which one would '
                       'Ana find a name in faster?',
 left=dict(label='by family name', art=[
   dict(kind='block', x=140, y=130, w=220, bh=20, colour='#1F4E5F'),
   dict(kind='block', x=140, y=100, w=220, bh=20, colour='#1F4E5F'),
   dict(kind='block', x=140, y=70, w=220, bh=20, colour='#1F4E5F'),
   dict(kind='label', x=300, y=210, text='DEMIR · KIM · LOPES · NOWAK · SILVA',
        colour='#1F4E5F')]),
 right=dict(label='by first name', art=[
   dict(kind='block', x=140, y=130, w=220, bh=20, colour='#C86B2B'),
   dict(kind='block', x=140, y=100, w=220, bh=20, colour='#C86B2B'),
   dict(kind='gap', x=140, y=70, w=220, bh=20),
   dict(kind='label', x=300, y=210, text='Ana · Emre · Lin · Piotr · Teresa · (yusuf?)',
        colour='#C86B2B')])),
}
