"""A1.1 Unit 2 - The Six O'Clock Class - fifteen figures, as data."""
FIGURES = {
"fig_a11_u02_p00_v01": dict(type='V1', height=900, storey_h=116,
 title='The same street, twenty to seven',
 sub='Fourteen things to find. Two of the clocks do not agree, and one of them is wrong.',
 alt='A steep Lisbon street before seven in the morning. The language school is dark except for '
     'one lit window on the second floor where a cleaner is working. Next door the cafe is open, '
     'its lights on, with three people standing at the counter.',
 sky='#3B4B57', ground='#5F5A52', ground_line=700,
 buildings=[dict(x=20, w=560, storeys=4, colour='#8A7C52', cutaway=True,
     floor_labels=['room 3 - dark, nobody until nine',
                   'the office - dark',
                   'one light - Dona Filipa',
                   'the door, and the sign on it'],
     label='Escola Monte - closed'),
   dict(x=620, w=460, storeys=2, colour='#E8CE7A', cutaway=True,
     floor_labels=['a bed, and nobody in it', 'the counter'],
     label="Marco's cafe - open since half past six"),
   dict(x=1120, w=460, storeys=3, colour='#6E6A62', label='the top of the street - dark')],
 props=[dict(kind='sign', x=140, y=700, s=.7, text='6:40'),
   dict(kind='chair', x=900, y=700, s=1.0),
   dict(kind='table', x=940, y=700, s=1.0),
   dict(kind='cup', x=980, y=654, s=1.4),
   dict(kind='tree', x=1100, y=700, s=1.0),
   dict(kind='hoarding', x=1150, y=700, s=.9, w=200),
   dict(kind='sign', x=1430, y=700, s=.7, text='TRAM'),
   dict(kind='box', x=1540, y=700, s=1.0)],
 people=[dict(x=650, y=700, h=84, skin=3, cloth=0, hair='cap', arm='hold'),
   dict(x=720, y=700, h=84, skin=1, cloth=2, hair='bun', arm='hold'),
   dict(x=790, y=700, h=84, skin=2, cloth=4, hair='short', arm='down'),
   dict(x=860, y=700, h=84, skin=4, cloth=3, hair='long', arm='folded'),
   dict(x=1505, y=700, h=84, skin=0, cloth=1, hair='grey', arm='down')],
 names=[dict(x=650, t='Marco - he opens at half past six'),
   dict(x=720, t='Ana - a coffee, standing up'),
   dict(x=790, t='a tram driver - he starts at seven'),
   dict(x=860, t='a nurse - she finishes at seven'),
   dict(x=1505, t='somebody waiting for the first tram'),
   dict(x=140, t='the cafe clock: twenty to seven'),
   dict(x=1430, t='the tram, empty, at the top'),
   dict(x=1250, t='the noticeboard, in the dark')],
 markers=[dict(x=650, y=582), dict(x=720, y=582), dict(x=790, y=582), dict(x=860, y=582),
   dict(x=1505, y=582), dict(x=140, y=636), dict(x=1430, y=636), dict(x=1250, y=650),
   dict(x=960, y=656), dict(x=900, y=664), dict(x=1100, y=640), dict(x=1560, y=652),
   dict(x=300, y=526), dict(x=800, y=526)]),

"fig_a11_u02_p01_v08": dict(type='V8', height=760,
 title='A day is a circle',
 sub='Six moments, and the hours on the lines between them. It comes back to where it started.',
 alt='Six moments of a day arranged in a ring - wake up, have breakfast, work, eat, study, go to '
     'bed - joined by lines labelled with the number of hours between them.',
 nodes={
  'wake': dict(x=800, y=140, short='6', name='wake up', sub='6.00', colour='#D9A441'),
  'brek': dict(x=1180, y=280, short='6½', name='have breakfast', sub='6.30', colour='#C86B2B'),
  'work': dict(x=1280, y=560, short='7', name='work', sub='7.00', colour='#1F4E5F'),
  'eat':  dict(x=880, y=680, short='3', name='eat', sub='15.00', colour='#2E6F5E'),
  'stud': dict(x=480, y=600, short='7', name='study', sub='19.00', r=50, colour='#8C6A9E'),
  'bed':  dict(x=400, y=300, short='10½', name='go to bed', sub='22.30', colour='#55646D')},
 edges=[dict(a='wake', b='brek', label='half an hour', sw=5),
   dict(a='brek', b='work', label='half an hour', sw=5),
   dict(a='work', b='eat', label='eight hours', sw=7),
   dict(a='eat', b='stud', label='four hours', sw=5),
   dict(a='stud', b='bed', label='three hours', sw=5),
   dict(a='bed', b='wake', label='seven and a half - and it starts again', sw=3, dash='7 6',
        colour='#9AA7AE')]),

"fig_a11_u02_p01_v02a": dict(type='V2', height=780,
 title='One flat at six in the morning',
 sub='Eleven things. Eleven words. Put each word in the right place.',
 alt='A cutaway of a small flat at six in the morning showing the bed, the bathroom, the kitchen '
     'and the door, each room with empty labels for the objects in it.',
 floors=[dict(was='the bed', now='somebody wakes up, and does not get up', year='',
     fill='#EFE6DC'),
   dict(was='the bathroom', now='wash · brush · the light is on', year='', fill='#E8EEF0'),
   dict(was='the kitchen', now='eat · drink · the cup · the chair', year='', fill='#F3EADA'),
   dict(was='the door', now='the bag is here, by the door, from last night', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='sleep · tired · the bed · the window'),
   dict(at=0.38, text='wash · brush · the hand · the head'),
   dict(at=0.62, text='eat · drink · hungry · thirsty'),
   dict(at=0.88, text='the bag · the door · and then the street')]),

"fig_a11_u02_p02_v07": dict(type='V7', height=820,
 title='The counter, twenty to seven',
 sub='He has been here ten minutes. She has fourteen hours in front of her.',
 alt='A cafe owner behind his counter early in the morning and a woman in a coat holding a bag, '
     'not sitting down, each with two speech balloons and a thought balloon.',
 bg='#EFE3CC',
 set=[dict(kind='table', x=800, y=660, s=1.8), dict(kind='chair', x=1360, y=660, s=1.2),
   dict(kind='cup', x=1280, y=660, s=1.5)],
 people=[dict(x=520, h=240, skin=3, cloth=0, hair='cap', arm='hold', facing='right',
   label='Marco', role='he opens at half past six',
   says=['Good morning. Early today.', 'I get up at six. Every day.'],
   thinks=['Four hours before anybody says thank you.']),
  dict(x=1080, h=238, skin=1, cloth=2, hair='bun', arm='hold', facing='left',
   label='Ana', role='she opens the school at half past eight',
   says=['I am not early. I am awake.', 'I do not eat at home on Monday.'],
   thinks=['Fourteen hours. And it is Monday.'])]),

"fig_a11_u02_p03_v09a": dict(type='V9', kind='weight', height=470,
 title='Four people, one verb',
 sub='Look at the four boxes. They are the same colour because they are the same word.',
 alt='Five boxes in a row. The first four read I work, you work, we work and they work in the '
     'same colour; the fifth is greyed out with a question mark and labelled Unit 3.',
 parts=[dict(w=20, role='I', text='I work', colour='#1F4E5F'),
   dict(w=20, role='you', text='you work', colour='#1F4E5F'),
   dict(w=20, role='we', text='we work', colour='#1F4E5F'),
   dict(w=20, role='they', text='they work', colour='#1F4E5F'),
   dict(w=20, role='Unit 3 - here it changes', text='he work ?', colour='#9AA7AE')],
 note='Four boxes, one word. The verb does not change for I, you, we or they. In Unit 3 it '
      'changes for he, she and it - and that is the only place in the whole language where it '
      'changes at all.'),

"fig_a11_u02_p03_v09b": dict(type='V9', kind='mirror', height=640,
 title='Do, and where it goes',
 sub='For a negative, do not drops in before the verb. For a question, do jumps to the front.',
 alt='Two sentence diagrams. In the first, do not is inserted before the verb; in the second, do '
     'moves to the front of the sentence. The verb itself does not move in either.',
 labels=['NEGATIVE', 'QUESTION'],
 between='\u2195 the verb does not move. Only do moves.',
 active=dict(parts=[dict(w=16, role='agent', text='I'),
   dict(w=24, role='hidden', text='do not'),
   dict(w=18, role='action', text='work'),
   dict(w=28, role='affected', text='on Saturday')]),
 passive=dict(parts=[dict(w=20, role='hidden', text='Do'),
   dict(w=16, role='agent', text='you'),
   dict(w=18, role='action', text='work'),
   dict(w=28, role='affected', text='on Saturday ?')]),
 rule='Negative: do not, or don\'t, goes in front of the verb. Question: do goes to the very '
      'front of the sentence. The verb stays as it is, both times. It never takes an s and it '
      'never moves.'),

"fig_a11_u02_p03_v11": dict(type='V11', height=680,
 title='Two verbs in one slot',
 alt='Two panels comparing I am work with I work, showing two verbs competing for a single slot '
     'in the first and one verb in the second.',
 wrong=dict(sentence='I am work at six.',
            boundary=0.30, boundary_label='I',
            event=0.56, event_label='am AND work - two verbs, one slot',
            why='There is room for one verb here and two have arrived. English takes am for '
                'things you are and work for things you do, and it will not take both at once. '
                'A listener hears am and waits for a job or a place, and then gets a verb '
                'instead.'),
 right=dict(sentence='I work at six.',
            boundary=0.30, boundary_label='I',
            event=0.50, event_label='work - one verb, and then the time',
            why='One verb, and the time after it. This is the shape of almost everything you '
                'will say about your own life: a person, a thing they do, and when they do it. '
                'Three parts, in that order.'),
 misconception='Am, is and are are not helpers here. You learned I am a student in Unit 1 and '
               'the am stuck. For an action, drop it: I work, I get up, I study. Say it aloud: '
               'I work at six - not I am work at six.'),

"fig_a11_u02_p04_v04a": dict(type='V4', height=720,
 title='Two timetables for the same week',
 sub='The same template, filled in twice. One of them you can meet somebody with.',
 alt='Two weekly timetables side by side for the same person. The left one gives clock times; '
     'the right one gives only vague phrases such as early, late and after work.',
 differences=6, prompt='Find the six. Which one can you use to arrange to meet somebody, and '
                       'why can you not use the other one?',
 left=dict(label='with times', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='label', x=300, y=210, text='Mon 7.00 · Wed 19.00 · Sat 10.30',
        colour='#1F4E5F')]),
 right=dict(label='without times', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='early · after work · in the morning',
        colour='#C86B2B')])),

"fig_a11_u02_p05_v05": dict(type='V5', height=840,
 title='The sign on the school door',
 sub='Seven days down the side. Read it before you answer, and then read the bottom.',
 alt='The opening hours sign on a school door, listing each day with an opening and a closing '
     'time, Sunday marked closed, and a small handwritten note at the bottom about the back door.',
 rows=[dict(t='org', text='ESCOLA MONTE  -  OPENING HOURS'),
   dict(t='grid', cols=['DAY', 'OPEN', 'CLOSE'],
     data=[['MONDAY', '08.30', '21.00'],
           ['TUESDAY', '08.30', '21.00'],
           ['WEDNESDAY', '08.30', '21.00'],
           ['THURSDAY', '08.30', '21.00'],
           ['FRIDAY', '08.30', '19.00'],
           ['SATURDAY', '09.30', '13.00'],
           ['SUNDAY', 'CLOSED', '-']]),
   dict(t='rule'),
   dict(t='head', text='THE EVENING CLASSES'),
   dict(t='kv', k='Monday and Wednesday', v='19.00 - 21.00', mono=True),
   dict(t='kv', k='Tuesday and Thursday', v='19.00 - 21.00', mono=True),
   dict(t='kv', k='The last tram up the hill', v='21.10', mono=True),
   dict(t='rule'),
   dict(t='sign', text='AND AT THE BOTTOM, IN PEN:'),
   dict(t='para', text='"The cleaner comes in at 5 by the back door. Do not ring the bell '
     'before 8.30 - nobody at the desk." Written by Ana, for the delivery drivers, and read '
     'by everybody except the delivery drivers.')],
 callouts=[dict(at=0.14, text='Five days the same. Two days different'),
   dict(at=0.38, text='Saturday is on the sign - and it is an hour later'),
   dict(at=0.44, text='One day closed. Only one'),
   dict(at=0.68, text='The class ends at nine. The tram goes at ten past'),
   dict(at=0.93, text='Written in pen, so it was not true when the sign was printed')]),

"fig_a11_u02_p06_v03a": dict(type='V3',
 title='Half past six, in six places',
 sub='The same half hour. You have to read it, and then say it, in six different forms.',
 alt='Six panels showing half past six as it appears on a clock face, a phone screen, a printed '
     'timetable, a handwritten note, in somebody else\'s speech and in your own.',
 panels=[
  dict(caption='On the clock: the hand halfway down',
       art=[dict(kind='block', x=160, y=20, w=90, bh=90, colour='#1F4E5F')]),
  dict(caption='On the phone: 06:30', art=[dict(kind='block', x=160, y=10, w=80, bh=110,
     colour='#1C2B33')]),
  dict(caption='In the timetable: 6.30', art=[dict(kind='doc', x=160, y=0)]),
  dict(caption='In the note: "1/2 past 6"', art=[dict(kind='doc', x=160, y=0),
     dict(kind='gap', x=160, y=20, w=60, bh=20)]),
  dict(caption='Said to you: "half six"', art=[dict(kind='person', x=160, y=0, h=110,
     skin=3, cloth=0, arm='point')]),
  dict(caption='Said by you: "half past six"', art=[dict(kind='person', x=160, y=0, h=110,
     skin=1, cloth=2, arm='hold')])]),

"fig_a11_u02_p07_v10": dict(type='V10', kind='groups', height=680,
 title='One letter, three sounds',
 sub='Nothing changes in the spelling. What decides the sound is the letter in front of it.',
 alt='Three columns sorting words that all end in s by the sound of that ending - s, z and iz - '
     'with the rule for each column written under the phonetic symbol.',
 groups=[
  dict(ipa='/s/', colour='#1F4E5F', rule='after a quiet sound, the s stays quiet',
       words=['cats', 'books', 'eats', 'works', 'stops'],
       before='your voice is off for /t/ /k/ /p/ /f/, so it stays off for the s'),
  dict(ipa='/z/', colour='#2E6F5E', rule='after a loud sound, the s turns on too',
       words=['days', 'eyes', 'legs', 'opens', 'feels'],
       before='your voice is on for a vowel and for /n/ /g/ /l/, so it stays on'),
  dict(ipa='/ɪz/', colour='#C86B2B',
       rule='after a hissing sound, a whole syllable appears',
       words=['buses', 'watches', 'washes', 'closes', 'finishes'],
       before='two hisses cannot touch, so English puts a small vowel between them')]),

"fig_a11_u02_p09_v02b": dict(type='V2', height=780,
 title='One week, in section',
 sub='The top layer is what a student plans. Each layer down is nearer to what happens.',
 alt='A cutaway of one study week in four layers, from the two hours a day a student plans down '
     'to the twenty minutes they actually do, late at night, three days out of seven.',
 floors=[dict(was='Sunday evening', now='the plan: two hours a day, five days - ten hours',
     year='', fill='#E8EEF0'),
   dict(was='Monday and Tuesday', now='forty minutes, and it feels like failing', year='',
     fill='#F3EADA'),
   dict(was='Wednesday to Friday', now='nothing on two days, twenty minutes at eleven at night',
     year='', fill='#EFE6DC'),
   dict(was='Saturday', now='the real total: about an hour. And the same plan is written again',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Ten hours planned. Nobody has ever done ten'),
   dict(at=0.38, text='The gap starts on day one, not on day five'),
   dict(at=0.62, text='Late and tired. The hour is the problem, not the will'),
   dict(at=0.88, text='One hour a week - and a plan for ten, again')]),

"fig_a11_u02_p09_v03b": dict(type='V3',
 title='The same week, five times',
 sub='Five panels. Four of them are real and one of them is Sunday evening.',
 alt='Five panels showing a study week: planning it on Sunday, Monday at seven, Wednesday at ten '
     'at night, Friday with nothing at all, and Sunday again writing the same plan.',
 panels=[
  dict(caption='1 Sunday: the plan is written',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='2 Monday, 19.00: twenty minutes',
       art=[dict(kind='person', x=150, y=0, h=112, skin=2, cloth=4, arm='hold')]),
  dict(caption='3 Wednesday, 22.00: ten minutes, in bed',
       art=[dict(kind='person', x=150, y=0, h=100, skin=2, cloth=4, arm='down')]),
  dict(caption='4 Friday: nothing',
       art=[dict(kind='gap', x=150, y=30, w=120, bh=60)]),
  dict(caption='5 Sunday: the same plan, again',
       art=[dict(kind='doc', x=150, y=0), dict(kind='arrow', x=150, y=130)])]),

"fig_a11_u02_p10_v12": dict(type='V12', height=1180,
 title='One street, twenty-four hours, four people',
 sub='Half the class has two of these people. Half has the other two. The bottom line is the '
     'answer to a question nobody asked.',
 alt='An infographic of one street across twenty-four hours with a band for each of four people '
     'showing when each is asleep, awake, working and eating, and a line along the bottom '
     'counting how many of the four are awake at each hour.',
 span=['00.00', '24.00'], ticks=5,
 tick_labels=['midnight', '6.00', '12.00', '18.00', 'midnight'],
 bands=[dict(name='Dona Filipa', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.18}, label='asleep', colour='#9AA7AE'),
   dict(**{'from': 0.21, 'to': 0.33}, label='cleans the school, 5 to 8', colour='#1F4E5F'),
   dict(**{'from': 0.35, 'to': 0.52}, label='the second building', colour='#1F4E5F'),
   dict(**{'from': 0.54, 'to': 0.67}, label='asleep, 1 to 4', colour='#9AA7AE'),
   dict(**{'from': 0.70, 'to': 0.92}, label='awake, at home', colour='#2E6F5E')]),
  dict(name='Marco', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.25}, label='asleep', colour='#9AA7AE'),
   dict(**{'from': 0.27, 'to': 0.62}, label='the cafe, half past six to three', colour='#C86B2B'),
   dict(**{'from': 0.64, 'to': 0.94}, label='awake', colour='#2E6F5E')]),
  dict(name='Ana', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.29}, label='asleep', colour='#9AA7AE'),
   dict(**{'from': 0.29, 'to': 0.36}, label='breakfast', colour='#D9A441'),
   dict(**{'from': 0.37, 'to': 0.88}, label='the school, half past eight to nine',
        colour='#1F4E5F'),
   dict(**{'from': 0.90, 'to': 1.0}, label='asleep', colour='#9AA7AE')]),
  dict(name='Yusuf', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.30}, label='asleep - or eleven, on Saturday', colour='#9AA7AE'),
   dict(**{'from': 0.32, 'to': 0.78}, label='work, and then the seven o\'clock class',
        colour='#8C6A9E'),
   dict(**{'from': 0.80, 'to': 1.0}, label='home, late', colour='#2E6F5E')]),
  dict(name='Awake, out of four', type='line',
   points=[(0, 0), (0.20, 1), (0.28, 3), (0.36, 4), (0.56, 3), (0.68, 4), (0.90, 2), (1.0, 1)],
   end_label='1'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.22, label='somebody is working at five, and the street calls itself quiet'),
   dict(at=0.60, label='one hour, half past three, when three of the four are free'),
   dict(at=0.95, label='the line never reaches zero')])]),

"fig_a11_u02_p11_v04b": dict(type='V4', height=720,
 title='Room 3 at seven, and at half past seven',
 sub='The same room, drawn twice, from the same place in the corridor.',
 alt='Two drawings of the same classroom. On the left, seven students and four empty chairs at '
     'seven o\'clock. On the right, eleven students at half past seven, with a dark window '
     'behind them.',
 differences=6, prompt='Find the six. One of them is in the corridor, not in the room - and it '
                       'is the one that decides the question.',
 left=dict(label='seven o\'clock', art=[
   dict(kind='block', x=150, y=130, w=220, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=98, w=220, bh=22, colour='#1F4E5F'),
   dict(kind='gap', x=150, y=66, w=220, bh=22),
   dict(kind='label', x=300, y=210, text='7 here · 4 chairs empty · light outside',
        colour='#1F4E5F')]),
 right=dict(label='half past seven', art=[
   dict(kind='block', x=150, y=130, w=220, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=220, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=220, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='11 here · 0 empty · dark outside · tram at 21.10',
        colour='#2E6F5E')])),
}
