"""A1.1 Unit 3 - Eleven Screens - fifteen figures, as data."""
FIGURES = {
"fig_a11_u03_p00_v01": dict(type='V1', height=900, storey_h=116,
 title='Room 3, eleven o\'clock, from the back',
 sub='Fourteen things to find. Four of the eleven screens are showing the same thing.',
 alt='A language classroom seen from the back. Eleven students sit at desks with a screen at '
     'every desk or in every hand, while the teacher writes at the board with her back turned. '
     'One phone is face down, one is charging from the wall, and one is showing a map.',
 sky='#D6DEE2', ground='#A79C8A', ground_line=700,
 buildings=[dict(x=20, w=700, storeys=4, colour='#CFC2A4', cutaway=True,
     floor_labels=['the roof - a cable comes in here',
                   'room 7 - empty, and the wifi is better',
                   'room 3 - eleven people, eleven screens',
                   'the corridor'],
     label='Escola Monte, the back wall of room 3'),
   dict(x=800, w=340, storeys=2, colour='#B9C7CC',
     label='the window - the street, and nobody looking at it'),
   dict(x=1200, w=380, storeys=3, colour='#C3BBA8', label='the board - Teresa, facing it')],
 props=[dict(kind='table', x=120, y=700, s=1.1), dict(kind='table', x=300, y=700, s=1.1),
   dict(kind='table', x=480, y=700, s=1.1), dict(kind='table', x=880, y=700, s=1.1),
   dict(kind='chair', x=240, y=700, s=1.0), dict(kind='chair', x=420, y=700, s=1.0),
   dict(kind='cup', x=340, y=654, s=1.4),
   dict(kind='box', x=620, y=700, s=1.0),
   dict(kind='sign', x=1000, y=700, s=.7, text='11:00'),
   dict(kind='hoarding', x=1240, y=700, s=.9, w=220),
   dict(kind='crate', x=1520, y=700, s=1.0)],
 people=[dict(x=170, y=700, h=86, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=350, y=700, h=86, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=530, y=700, h=86, skin=0, cloth=1, hair='cap', arm='hold'),
   dict(x=900, y=700, h=86, skin=3, cloth=2, hair='bun', arm='down'),
   dict(x=1400, y=700, h=92, skin=1, cloth=0, hair='grey', arm='point')],
 names=[dict(x=170, t='Yusuf - a message, not a word'),
   dict(x=350, t='Lin - a map, and she knows the way'),
   dict(x=530, t='Emre - the screen is face down'),
   dict(x=900, t='Chika - charging, on the floor'),
   dict(x=1400, t='Teresa - at the board, facing away'),
   dict(x=1000, t='the clock: eleven o\'clock'),
   dict(x=1240, t='the noticeboard - nobody reads it either'),
   dict(x=620, t='the box the school wants to put by the door')],
 markers=[dict(x=170, y=580), dict(x=350, y=580), dict(x=530, y=580), dict(x=900, y=580),
   dict(x=1400, y=574), dict(x=1000, y=636), dict(x=1240, y=650), dict(x=620, y=652),
   dict(x=340, y=656), dict(x=240, y=664), dict(x=1520, y=660), dict(x=120, y=656),
   dict(x=300, y=466), dict(x=900, y=526)]),

"fig_a11_u03_p01_v08": dict(type='V8', height=760,
 title='Nothing on a phone works alone',
 sub='Six parts, and a line that says what each one does for the others.',
 alt='A phone in the centre joined by labelled lines to six things - the screen, the battery, '
     'the camera, the internet, an app and a password - with each line naming what that part '
     'does for the phone rather than what it is called.',
 nodes={
  'ph':  dict(x=800, y=400, short='P', name='the phone', sub='one object', r=62,
              colour='#1C2B33'),
  'scr': dict(x=430, y=200, short='S', name='the screen', sub='what you see', colour='#1F4E5F'),
  'bat': dict(x=400, y=560, short='B', name='the battery', sub='100 to 14', colour='#C86B2B'),
  'cam': dict(x=800, y=680, short='C', name='the camera', sub='two, you use one',
              colour='#2E6F5E'),
  'net': dict(x=1200, y=200, short='I', name='the internet', sub='not in the phone',
              colour='#8C6A9E'),
  'app': dict(x=1240, y=520, short='A', name='an app', sub='ninety of them', colour='#D9A441'),
  'pwd': dict(x=1470, y=330, short='*', name='a password', sub='in your head', r=44,
              colour='#A8372E')},
 edges=[dict(a='ph', b='scr', label='shows it to you', sw=6),
   dict(a='ph', b='bat', label='gives it four hours', sw=6),
   dict(a='ph', b='cam', label='takes the photo', sw=5),
   dict(a='ph', b='net', label='goes out and comes back', sw=5),
   dict(a='app', b='net', label='is useless without it', sw=5),
   dict(a='ph', b='app', label='opens it', sw=5),
   dict(a='app', b='pwd', label='asks you for it', sw=2, dash='6 6',
        colour='#A8372E')]),

"fig_a11_u03_p01_v02a": dict(type='V2', height=780,
 title='One phone, in section',
 sub='Eleven things. Eleven words. Put each word on the right layer.',
 alt='A cutaway of a phone drawn like a building in section, showing the glass at the front, the '
     'screen under it, the battery under that and the camera at the back, each layer with empty '
     'labels.',
 floors=[dict(was='the glass', now='you touch this. It is not the screen', year='',
     fill='#E8EEF0'),
   dict(was='the screen', now='the app · the message · the photo · the video', year='',
     fill='#F3EADA'),
   dict(was='the battery', now='it takes most of the room and nobody draws it', year='',
     fill='#EFE6DC'),
   dict(was='the back', now='the camera · the charger goes in here', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='glass · screen · you touch one and see the other'),
   dict(at=0.38, text='app · message · photo · video · notification'),
   dict(at=0.62, text='battery · charger · four hours, or fourteen'),
   dict(at=0.88, text='camera · map · and the internet, which is somewhere else')]),

"fig_a11_u03_p02_v07": dict(type='V7', height=820,
 title='The back of room 3',
 sub='Both phones are face down. Both of them are still being thought about.',
 alt='Two students at the back of a classroom with their phones face down on the desk between '
     'them, each with two speech balloons and a thought balloon.',
 bg='#E6EBEA',
 set=[dict(kind='table', x=760, y=660, s=2.0), dict(kind='cup', x=1300, y=660, s=1.4),
   dict(kind='chair', x=1380, y=660, s=1.2)],
 people=[dict(x=520, h=240, skin=4, cloth=3, hair='short', arm='down', facing='right',
   label='Yusuf', role='he thinks it is about ten',
   says=['I check it, I don\'t know. Ten times?', 'My sister checks hers more than me.'],
   thinks=['Where is it? I put it somewhere.']),
  dict(x=1080, h=238, skin=2, cloth=4, hair='long', arm='point', facing='left',
   label='Lin', role='she already knows her number',
   says=['How often does your sister check hers?', 'Mine says ninety-six. Every day.'],
   thinks=['He has looked at the desk four times.'])]),

"fig_a11_u03_p03_v09a": dict(type='V9', kind='weight', height=470,
 title='Four the same, and one with a letter on it',
 sub='The fifth box is the whole of the present simple. One letter, one group of people.',
 alt='Five boxes in a row. The first four read I check, you check, we check and they check in the '
     'same colour; the fifth reads he checks with the final s in a second colour and larger than '
     'the rest of the word.',
 parts=[dict(w=19, role='I', text='I check', colour='#1F4E5F'),
   dict(w=19, role='you', text='you check', colour='#1F4E5F'),
   dict(w=19, role='we', text='we check', colour='#1F4E5F'),
   dict(w=19, role='they', text='they check', colour='#1F4E5F'),
   dict(w=24, role='he · she · it', text='he checkS', colour='#C86B2B')],
 note='One letter. It goes on for he, she and it, and nowhere else in the present simple. It is '
      'the only ending this tense has, and it is the one that gets left off.'),

"fig_a11_u03_p03_v09b": dict(type='V9', kind='mirror', height=640,
 title='The s is only in one place at a time',
 sub='When does arrives at the front, it takes the s with it. The verb gives it up.',
 alt='Two sentence diagrams. In the first, she checks carries the s on the verb; in the second, '
     'does has taken the s to the front and the verb is left bare.',
 labels=['A FACT', 'A QUESTION'],
 between='↕ one s per sentence, and the helper gets it',
 active=dict(parts=[dict(w=20, role='agent', text='She'),
   dict(w=24, role='action', text='checkS'),
   dict(w=34, role='affected', text='her phone at six')]),
 passive=dict(parts=[dict(w=22, role='hidden', text='DoeS'),
   dict(w=18, role='agent', text='she'),
   dict(w=20, role='action', text='check'),
   dict(w=34, role='affected', text='her phone at six ?')]),
 rule='Does already has the s. The verb after it goes back to its plain form: Does she check, '
      'not Does she checks. The same is true of the negative: She doesn\'t check.'),

"fig_a11_u03_p03_v11": dict(type='V11', height=700,
 title='The letter that gets used twice',
 alt='Two panels comparing Does she checks with Does she check, the first showing the letter s '
     'drawn on both the helper and the verb with the second crossed out.',
 wrong=dict(sentence='Does she checks her phone?',
            boundary=0.34, boundary_label='Does - it has the s',
            event=0.62, event_label='and the verb has it too',
            why='Two esses in one question, and English only ever pays for one. The helper does '
                'is already the he-she-it form; it did the job before the verb was reached. '
                'Putting the ending on again is like saying the same word twice and hoping '
                'nobody counts.'),
 right=dict(sentence='Does she check her phone?',
            boundary=0.34, boundary_label='Does - it has the s',
            event=0.60, event_label='so the verb is plain',
            why='One ess, on the helper, at the front, where the listener hears it first. '
                'Everything after it is the plain verb. This is also why the negative is '
                'she doesn\'t check and never she doesn\'t checks.'),
 misconception='The rule you learned in 3C was: he, she and it take an s. It is true, and here '
               'it looks as though it has stopped being true. It has not. The s is still there '
               '- it has just moved to the front of the question, onto does.'),

"fig_a11_u03_p04_v04a": dict(type='V4', height=720,
 title='Two interviews, same classmate',
 sub='Written down by two learners, in the same ten minutes, with the same person.',
 alt='Two pages of interview notes side by side. The left page has a question word at the start '
     'of every line and long answers; the right page has yes and no questions and one-word '
     'answers.',
 differences=6, prompt='Find the six. Which learner knows something now, and which learner only '
                       'knows yes?',
 left=dict(label='question words', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='label', x=300, y=210, text='How often? Why? Which one? - long answers',
        colour='#1F4E5F')]),
 right=dict(label='yes / no only', art=[
   dict(kind='block', x=150, y=130, w=100, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='block', x=150, y=66, w=90, bh=22, colour='#C86B2B'),
   dict(kind='label', x=300, y=210, text='Do you? Does she? - yes · no · yes',
        colour='#C86B2B')])),

"fig_a11_u03_p05_v05": dict(type='V5', height=1010,
 title='A weekly screen-time report',
 sub='Everything on this page is a number the person did not choose to produce.',
 alt='A weekly screen time report from a phone, showing the total hours, the change on last '
     'week, a bar for each day, the three apps that took the most time, the number of daily '
     'pick-ups, and the time of the first pick-up of the day.',
 rows=[dict(t='org', text='SCREEN TIME  -  WEEK OF 12 MAY'),
   dict(t='kv', k='Daily average', v='6 h 42 m', mono=True),
   dict(t='kv', k='Weekly total', v='46 h 54 m', mono=True),
   dict(t='kv', k='Change on last week', v='+ 11 %', mono=True),
   dict(t='rule'),
   dict(t='head', text='BY DAY'),
   dict(t='grid', cols=['DAY', 'HOURS', 'PICK-UPS'],
     data=[['MON', '6 h 10 m', '88'],
           ['TUE', '5 h 48 m', '81'],
           ['WED', '6 h 02 m', '90'],
           ['THU', '6 h 31 m', '95'],
           ['FRI', '7 h 14 m', '112'],
           ['SAT', '8 h 26 m', '126'],
           ['SUN', '6 h 43 m', '82']]),
   dict(t='rule'),
   dict(t='head', text='MOST USED'),
   dict(t='kv', k='messages', v='14 h 20 m', mono=True),
   dict(t='kv', k='video', v='11 h 05 m', mono=True),
   dict(t='kv', k='the map', v='2 h 48 m', mono=True),
   dict(t='rule'),
   dict(t='sign', text='AND IN SMALL TYPE AT THE BOTTOM:'),
   dict(t='para', text='Average pick-ups a day: 96. First pick-up of the day: 06.12.')],
 callouts=[dict(at=0.10, text='Six hours and forty-two minutes, every day'),
   dict(at=0.20, text='Up eleven per cent, and nobody decided that'),
   dict(at=0.46, text='Saturday is the highest. It is not a work day'),
   dict(at=0.72, text='Fourteen hours of messages. Four full working days a month'),
   dict(at=0.94, text='06.12 - before the alarm, before the eyes are properly open')]),

"fig_a11_u03_p06_v03a": dict(type='V3',
 title='One fact, six questions',
 sub='Lin opens the map at 7.40. Change only the first word and six different things go missing.',
 alt='Six panels showing the same fact turned into six questions by changing the first word, '
     'each panel marking which part of the fact the question is asking for.',
 panels=[
  dict(caption='Who opens the map at 7.40?', art=[dict(kind='person', x=160, y=0, h=110,
     skin=2, cloth=4)]),
  dict(caption='What does Lin open at 7.40?', art=[dict(kind='block', x=160, y=10, w=80,
     bh=100, colour='#1F4E5F')]),
  dict(caption='When does Lin open the map?', art=[dict(kind='doc', x=160, y=0)]),
  dict(caption='Where does Lin open it?', art=[dict(kind='block', x=160, y=10, w=110,
     bh=70, colour='#2E6F5E')]),
  dict(caption='Why does Lin open it?', art=[dict(kind='gap', x=160, y=20, w=100, bh=70)]),
  dict(caption='How often does Lin open it?', art=[dict(kind='arrow', x=160, y=60),
     dict(kind='arrow', x=160, y=20)])]),

"fig_a11_u03_p07_v10": dict(type='V10', kind='pitch', height=980,
 title='Two tunes, and the question decides',
 sub='The words can be almost the same. The end of the line is not.',
 alt='Two pitch contours over spoken questions. The first rises at the end, marked as a yes or '
     'no question; the second falls at the end, marked as a question with a question word.',
 contours=[
  dict(text='Do you check it at night?', points=[0.1, 0.2, 0.1, 0.3, 1.2],
       meaning='yes / no question - the voice goes UP'),
  dict(text='Where do you put it at night?', points=[1.1, 0.9, 0.6, 0.4, -0.5],
       meaning='question word - the voice goes DOWN'),
  dict(text='You check it at night.', points=[0.6, 0.5, 0.3, 0.2, -0.6],
       meaning='not a question at all - down, and flat'),
  dict(text='You check it at night?', points=[0.2, 0.2, 0.1, 0.4, 1.3],
       meaning='the same seven words - up, and surprised')]),

"fig_a11_u03_p09_v02b": dict(type='V2', height=780,
 title='The same phone, in languages',
 sub='Four layers. A word can be on any of them, and only one of them keeps it.',
 alt='A cutaway of a phone in four layers: what the phone shows, the language it shows it in, '
     'the words looked up and lost, and the one place a word is actually kept.',
 floors=[dict(was='what the phone shows you', now='four hundred words a day, and you read them',
     year='', fill='#E8EEF0'),
   dict(was='the language it is in', now='one setting, changed in nine seconds, never changed',
     year='', fill='#F3EADA'),
   dict(was='the words you looked up', now='in the app, in order, and you will not open it again',
     year='', fill='#EFE6DC'),
   dict(was='paper, or a wall, or a hand', now='the only layer a word stays on', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='You already read English here. You just do not notice'),
   dict(at=0.38, text='Nine seconds, once, and then four hundred words a day for free'),
   dict(at=0.62, text='Every word you have ever looked up is in here. None of them are in you'),
   dict(at=0.88, text='Where you can see it without looking for it')]),

"fig_a11_u03_p09_v03b": dict(type='V3',
 title='Four minutes',
 sub='Five panels. The fourth one is the one everybody recognises.',
 alt='Five panels following one new word: meeting it, looking it up, closing the app, meeting it '
     'again four days later, and not knowing it.',
 panels=[
  dict(caption='1 A new word, in a message',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='2 You look it up. Four seconds',
       art=[dict(kind='person', x=150, y=0, h=112, skin=4, cloth=3, arm='hold')]),
  dict(caption='3 You close the app',
       art=[dict(kind='block', x=150, y=10, w=80, bh=100, colour='#1C2B33')]),
  dict(caption='4 Four days later, the same word',
       art=[dict(kind='doc', x=150, y=0), dict(kind='arrow', x=150, y=130)]),
  dict(caption='5 And you do not know it',
       art=[dict(kind='gap', x=150, y=20, w=110, bh=80)])]),

"fig_a11_u03_p10_v12": dict(type='V12', height=1180,
 title='One lesson, eleven phones',
 sub='Ninety minutes. Sixty-four pick-ups. Three moments when nearly everybody reached at once.',
 alt='An infographic of one ninety-minute lesson showing when phones were picked up, three '
     'moments when nearly all eleven were picked up together, and what the teacher was doing at '
     'each of those moments.',
 span=['11.00', '12.30'], ticks=4,
 tick_labels=['11.00', '11.30', '12.00', '12.30'],
 bands=[dict(name='Pick-ups', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.14}, label='4 - the first ten minutes are the quietest',
        colour='#2E6F5E'),
   dict(**{'from': 0.16, 'to': 0.38}, label='11 - grammar explanation', colour='#D9A441'),
   dict(**{'from': 0.40, 'to': 0.56}, label='23 - written exercise, alone', colour='#A8372E'),
   dict(**{'from': 0.58, 'to': 0.80}, label='9 - pair work', colour='#2E6F5E'),
   dict(**{'from': 0.82, 'to': 1.0}, label='17 - the last ten minutes', colour='#C86B2B')]),
  dict(name='What Teresa was doing', type='events', items=[
   dict(at=0.08, label='speaking to the class', colour='#1F4E5F'),
   dict(at=0.28, label='writing on the board, back turned', colour='#A8372E'),
   dict(at=0.48, label='at her desk, marking', colour='#A8372E'),
   dict(at=0.68, label='walking between the pairs', colour='#2E6F5E'),
   dict(at=0.90, label='summing up, at the front', colour='#1F4E5F')]),
  dict(name='The three moments', type='bars', items=[
   dict(**{'from': 0.26, 'to': 0.30}, label='8 phones in 40 seconds', colour='#A8372E'),
   dict(**{'from': 0.46, 'to': 0.50}, label='9 phones in 30 seconds', colour='#A8372E'),
   dict(**{'from': 0.86, 'to': 0.90}, label='10 phones in 25 seconds', colour='#A8372E')]),
  dict(name='Phones face down', type='line',
   points=[(0, 11), (0.2, 7), (0.45, 3), (0.65, 6), (0.85, 4), (1.0, 1)], end_label='1'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.30, label='all three moments are moments when nobody was being looked at'),
   dict(at=0.60, label='pair work is the quietest part of the lesson, and the loudest'),
   dict(at=0.92, label='three of the sixty-four were dictionary look-ups')])]),

"fig_a11_u03_p11_v04b": dict(type='V4', height=720,
 title='The same ninety minutes, twice',
 sub='With the box by the door, and without it. Drawn from the same place at the back.',
 alt='Two drawings of the same lesson. On the left, sixty-four pick-ups including three '
     'dictionary look-ups. On the right, no pick-ups and three hands up instead.',
 differences=6, prompt='Find the six. One of them is in the corridor - and it is the one the '
                       'school did not think about.',
 left=dict(label='no box', art=[
   dict(kind='block', x=150, y=130, w=250, bh=22, colour='#A8372E'),
   dict(kind='block', x=150, y=98, w=250, bh=22, colour='#A8372E'),
   dict(kind='block', x=150, y=66, w=60, bh=22, colour='#1F4E5F'),
   dict(kind='label', x=300, y=210, text='64 pick-ups · 3 of them a dictionary',
        colour='#A8372E')]),
 right=dict(label='box by the door', art=[
   dict(kind='gap', x=150, y=130, w=250, bh=22),
   dict(kind='gap', x=150, y=98, w=250, bh=22),
   dict(kind='block', x=150, y=66, w=60, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='0 pick-ups · 3 hands up · 1 phone ringing outside',
        colour='#2E6F5E')])),
}
