"""A1.1 Unit 4 - Eleven Signs, One Building - fifteen figures, as data."""
FIGURES = {
"fig_a11_u04_p00_v01": dict(type='V1', height=900, storey_h=116,
 title='The stairwell and the corridor, half past twelve',
 sub='Fourteen things to find. Three of the signs are written by three different hands.',
 alt='A four-storey stairwell and corridor seen in section, with a sign on nearly every door, a '
     'lift with a handwritten notice taped to it, a cleaner waiting beside it with a trolley, and '
     'two students on the stairs both keeping to the same side.',
 sky='#D9DFE0', ground='#A99E8C', ground_line=700,
 buildings=[dict(x=20, w=620, storeys=4, colour='#C6B89A', cutaway=True,
     floor_labels=['floor 3 - two doors, two signs',
                   'floor 2 - the toilet, and the queue',
                   'floor 1 - the exam room',
                   'the entrance'],
     label='the stairs - everybody, all four floors'),
   dict(x=720, w=260, storeys=4, colour='#B4BEC2', cutaway=True,
     floor_labels=['floor 3', 'floor 2', 'floor 1', 'the lift'],
     label='the lift - a piece of paper decides'),
   dict(x=1060, w=520, storeys=3, colour='#C9C0AE',
     label='the corridor - two people wide, if they both move')],
 props=[dict(kind='sign', x=190, y=700, s=.7, text='ENTRANCE'),
   dict(kind='sign', x=1480, y=700, s=.7, text='EXIT'),
   dict(kind='crate', x=840, y=700, s=1.1),
   dict(kind='box', x=1000, y=700, s=1.0),
   dict(kind='chair', x=1120, y=700, s=1.0),
   dict(kind='table', x=1180, y=700, s=1.1),
   dict(kind='hoarding', x=1280, y=700, s=.9, w=180),
   dict(kind='tree', x=680, y=700, s=.8)],
 people=[dict(x=300, y=700, h=86, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=440, y=700, h=86, skin=4, cloth=3, hair='cap', arm='down'),
   dict(x=800, y=700, h=88, skin=1, cloth=0, hair='grey', arm='hold'),
   dict(x=1150, y=700, h=86, skin=3, cloth=2, hair='bun', arm='point'),
   dict(x=1420, y=700, h=86, skin=0, cloth=1, hair='short', arm='folded')],
 names=[dict(x=300, t='one student going up, on the left'),
   dict(x=440, t='one student coming down, also on the left'),
   dict(x=800, t='Dona Filipa - staff, and she takes the stairs'),
   dict(x=1150, t='Ana - she counted the signs'),
   dict(x=1420, t='a student looking for the exit that is not locked'),
   dict(x=190, t='the entrance - one, for everybody'),
   dict(x=1480, t='the exit - three, two of them locked'),
   dict(x=1280, t='the noticeboard, below the sign about it')],
 markers=[dict(x=300, y=580), dict(x=440, y=580), dict(x=800, y=578), dict(x=1150, y=580),
   dict(x=1420, y=580), dict(x=190, y=636), dict(x=1480, y=636), dict(x=1280, y=650),
   dict(x=840, y=660), dict(x=1000, y=652), dict(x=1120, y=664), dict(x=680, y=640),
   dict(x=300, y=466), dict(x=300, y=350)]),

"fig_a11_u04_p01_v08": dict(type='V8', height=760,
 title='Who is allowed to go which way',
 sub='Six places, and a line for every route. Two of the lines are dotted, and they are the ones '
     'worth reading.',
 alt='A network of six places in a building - entrance, stairs, lift, corridor, toilet and exit - '
     'joined by labelled lines saying who may use each route, with two routes drawn as dotted '
     'lines.',
 nodes={
  'ent': dict(x=220, y=400, short='1', name='the entrance', sub='one, for everybody',
              colour='#2E6F5E'),
  'cor': dict(x=620, y=400, short='C', name='the corridor', sub='two wide', r=54,
              colour='#1F4E5F'),
  'sta': dict(x=1000, y=200, short='S', name='the stairs', sub='four floors', colour='#1F4E5F'),
  'lif': dict(x=1000, y=600, short='L', name='the lift', sub='staff only, it says',
              colour='#C86B2B'),
  'toi': dict(x=1360, y=330, short='T', name='the toilet', sub='second floor', colour='#8C6A9E'),
  'exi': dict(x=1360, y=620, short='E', name='the exit', sub='three, two locked', r=48,
              colour='#A8372E')},
 edges=[dict(a='ent', b='cor', label='everybody, all day', sw=7),
   dict(a='cor', b='sta', label='everybody', sw=7),
   dict(a='cor', b='lif', label='staff - and a piece of paper says so', sw=3, dash='7 6',
        colour='#C86B2B'),
   dict(a='sta', b='toi', label='up two floors, and a queue at eleven', sw=5),
   dict(a='lif', b='toi', label='would be one button', sw=2, dash='5 6', colour='#9AA7AE'),
   dict(a='cor', b='exi', label='locked, except the middle one', sw=4, colour='#A8372E')]),

"fig_a11_u04_p01_v02a": dict(type='V2', height=780,
 title='The building, in section',
 sub='Eleven places. Eleven words. Put each word on the right floor.',
 alt='A cutaway of the school building showing the entrance at the bottom, the corridor, the '
     'stairs running up through four floors and the lift beside them, with empty labels.',
 floors=[dict(was='floor 3', now='two doors · two signs · one of them handwritten', year='',
     fill='#F1EDE2'),
   dict(was='floor 2', now='the toilet · a queue at eleven · a sign that says quiet', year='',
     fill='#E8EEF0'),
   dict(was='floor 1', now='the exam room · the corridor · Keep right, and nobody does',
     year='', fill='#EFE6DC'),
   dict(was='the ground floor', now='the entrance · the exit · the stairs · the lift', year='',
     fill='#F3EADA')],
 callouts=[dict(at=0.12, text='sign · rule · open · closed'),
   dict(at=0.38, text='toilet · quiet · allowed'),
   dict(at=0.62, text='corridor · forbidden · smoking'),
   dict(at=0.88, text='entrance · exit · stairs · lift')]),

"fig_a11_u04_p02_v07": dict(type='V7', height=820,
 title='Beside the lift, half past twelve',
 sub='She is staff. The paper on the door does not know that about her.',
 alt='A cleaner with a trolley standing beside a lift with a handwritten notice taped to it, and '
     'a receptionist in the corridor holding a folder, each with two speech balloons and a '
     'thought balloon.',
 bg='#E9E3D6',
 set=[dict(kind='crate', x=740, y=660, s=1.4), dict(kind='box', x=1320, y=660, s=1.1),
   dict(kind='chair', x=1420, y=660, s=1.2)],
 people=[dict(x=520, h=242, skin=1, cloth=0, hair='grey', arm='hold', facing='right',
   label='Dona Filipa', role='staff, for nineteen years',
   says=['I can\'t carry it up four floors.', 'The paper says staff only.'],
   thinks=['Four floors, twice a day, since March.']),
  dict(x=1080, h=238, skin=3, cloth=2, hair='bun', arm='point', facing='left',
   label='Ana', role='she counted the signs',
   says=['You can use it. You are staff.', 'I don\'t know who wrote that.'],
   thinks=['Who put it there? It was before me.'])]),

"fig_a11_u04_p03_v09a": dict(type='V9', kind='branch', height=680,
 title='One word, three destinations',
 sub='Can does not change. What changes is the situation it lands in.',
 alt='A branching diagram from the single word can to three destinations: ability, permission '
     'and prohibition, each with an example sentence.',
 root='can',
 branches=[dict(label='ABILITY - a body or a mind', colour='#2E6F5E',
     example='I can carry it. I can\'t carry it up four floors. -- nobody decided this'),
   dict(label='PERMISSION - somebody decided', colour='#1F4E5F',
     example='You can use the lift. -- and they could decide otherwise tomorrow'),
   dict(label='PROHIBITION - a rule, and no author', colour='#A8372E',
     example='You can\'t smoke here. -- the person who decided is not in the building')]),

"fig_a11_u04_p03_v09b": dict(type='V9', kind='mirror', height=640,
 title='Not joins on, and can jumps',
 sub='For a negative, not joins the back of can. For a question, can goes to the front.',
 alt='Two sentence diagrams. In the first, not joins can to make can not; in the second, can '
     'moves to the front of the sentence. The verb after it is plain in both.',
 labels=['NEGATIVE', 'QUESTION'],
 between='↕ can never takes an s, and the verb after it never takes to',
 active=dict(parts=[dict(w=16, role='agent', text='I'),
   dict(w=26, role='hidden', text="can + n't"),
   dict(w=18, role='action', text='use'),
   dict(w=24, role='affected', text='the lift')]),
 passive=dict(parts=[dict(w=18, role='hidden', text='Can'),
   dict(w=16, role='agent', text='I'),
   dict(w=20, role='action', text='leave'),
   dict(w=30, role='affected', text='this here ?')]),
 rule='Can is the same for I, you, he, she, we and they. There is no does in the question and no '
      'to after it: Can she use it, never Can she uses it and never Can she to use it.'),

"fig_a11_u04_p03_v11": dict(type='V11', height=700,
 title='The s with nowhere to go',
 alt='Two panels comparing She cans use it with She can use it, the first showing an s arriving '
     'at a slot that is already full.',
 wrong=dict(sentence='She cans use it.',
            boundary=0.32, boundary_label='She',
            event=0.58, event_label='cans - an s on a word that has no room',
            why='The s you learned in Unit 3 is for ordinary verbs. Can is not an ordinary verb; '
                'it is a helper, and helpers are the same for everybody. There is no cans, no '
                'canned and no to can. The word simply does not move.'),
 right=dict(sentence='She can use it.',
            boundary=0.32, boundary_label='She',
            event=0.56, event_label='can - identical for all six people',
            why='One form, six people. That makes can easier than every ordinary verb in the '
                'language, and it is the reason learners reach for it when they are tired. '
                'The verb after it stays plain: use, go, come, never to use.'),
 misconception='You have just spent a unit putting an s on he and she. The habit is new and it '
               'is strong, and it reaches for the nearest verb. Can is the first word in this '
               'book that refuses it, and there are only about ten such words in all of English.'),

"fig_a11_u04_p04_v04a": dict(type='V4', height=720,
 title='The same request, twice',
 sub='Three words on the left, nine on the right, at the same desk, to the same person.',
 alt='Two versions of one request written out side by side, the left one three words long and '
     'the right one nine, with the answer each one got.',
 differences=6, prompt='Find the six. Which one got the yes - and is it the one you expected?',
 left=dict(label='three words', art=[
   dict(kind='block', x=150, y=130, w=110, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='"Open the window." - no', colour='#A8372E')]),
 right=dict(label='nine words', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=140, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='"Excuse me - could you open the window, please?" - yes', colour='#2E6F5E')])),

"fig_a11_u04_p05_v05": dict(type='V5', height=820,
 title='The notice on the lift',
 sub='One piece of paper. Three hands. No name.',
 alt='A photograph of the notice taped to the lift door, showing a printed line, a handwritten '
     'line below it in different ink, a date in the corner, and a lifted corner of tape.',
 rows=[dict(t='org', text='LIFT'),
   dict(t='sign', text='STAFF ONLY'),
   dict(t='rule'),
   dict(t='para', text='Underneath, in blue pen, in a second hand: "and students with a teacher"'),
   dict(t='para', text='Under that, in pencil, in a third hand: "ask Ana"'),
   dict(t='rule'),
   dict(t='head', text='WHAT IS ALSO ON THE PAPER'),
   dict(t='kv', k='A date in the corner', v='11 / 09', mono=True),
   dict(t='kv', k='A year', v='not written', mono=False),
   dict(t='kv', k='A name', v='none', mono=False),
   dict(t='kv', k='Tape', v='four pieces, one lifted', mono=False),
   dict(t='rule'),
   dict(t='para', text='The printed line is a rule. The blue line is an exception to it. The '
     'pencil line is neither - it is the name of a person, and it is the only part of this '
     'notice that tells you what to do next.')],
 callouts=[dict(at=0.14, text='Printed, so it looks official. Nobody knows who printed it'),
   dict(at=0.34, text='A second hand widened the rule. Could they?'),
   dict(at=0.42, text='A third hand gave up and named a person'),
   dict(at=0.70, text='Eleven September. Four years ago, if you ask Ana'),
   dict(at=0.92, text='Three people wrote here. One of them had the authority')]),

"fig_a11_u04_p06_v03a": dict(type='V3',
 title='Open the window, at six temperatures',
 sub='The same request, six times. Only the beginning and the end change.',
 alt='Six panels showing the same request made at six levels of politeness, from a bare order to '
     'a long apologetic question.',
 panels=[
  dict(caption='1 "Open the window."', art=[dict(kind='block', x=160, y=10, w=60, bh=40,
     colour='#A8372E')]),
  dict(caption='2 "Open the window, please."', art=[dict(kind='block', x=160, y=10, w=90,
     bh=40, colour='#C86B2B')]),
  dict(caption='3 "Can you open the window?"', art=[dict(kind='block', x=160, y=10, w=120,
     bh=40, colour='#D9A441')]),
  dict(caption='4 "Could you open the window?"', art=[dict(kind='block', x=160, y=10, w=150,
     bh=40, colour='#2E6F5E')]),
  dict(caption='5 "Is it OK if I open the window?"', art=[dict(kind='block', x=160, y=10,
     w=180, bh=40, colour='#1F4E5F')]),
  dict(caption='6 "Sorry - would you mind if I...?"', art=[dict(kind='block', x=160, y=10,
     w=210, bh=40, colour='#8C6A9E'), dict(kind='arrow', x=160, y=120)])]),

"fig_a11_u04_p07_v10": dict(type='V10', kind='mouth', height=680,
 title='Two vowels, and a word you can hardly hear',
 sub='The tongue moves a long way between these two, and most learners move it halfway.',
 alt='Two mouth cross-sections side by side showing the tongue position for the vowel in can and '
     'the vowel in come, with minimal pairs under each.',
 sounds=[
  dict(ipa='/æ/', desc='low and forward - the jaw really opens',
       examples='can · bag · man · hand · that', length='short',
       tongue=dict(high=.22, front=.82), lips='spread'),
  dict(ipa='/ʌ/', desc='middle and back - the jaw hardly moves',
       examples='come · one · but · much · up', length='short',
       tongue=dict(high=.46, front=.34), lips='neutral')]),

"fig_a11_u04_p09_v02b": dict(type='V2', height=780,
 title='The rules you gave yourself',
 sub='Four walls, in the same style as the signs in Part 0. None of them has a name on it either.',
 alt='A cutaway of a learner\'s week with the rules they have set themselves drawn as walls, each '
     'labelled with the rule and with what it actually prevents.',
 floors=[dict(was='no English before coffee', now='and the coffee is at eight, and the bus is '
     'at half past seven', year='', fill='#F3EADA'),
   dict(was='not on the bus', now='it is the only twenty minutes nobody else wants', year='',
     fill='#E8EEF0'),
   dict(was='not if I am tired', now='which rules out every evening after the first week',
     year='', fill='#EFE6DC'),
   dict(was='not at the weekend', now='because the weekend is for resting, and it is two '
     'sevenths of the year', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Who made this rule? You did, once, when you were tired'),
   dict(at=0.38, text='This one removes the best twenty minutes in the week'),
   dict(at=0.62, text='This one is a wall with no door in it'),
   dict(at=0.88, text='Four rules. Together they allow about four hours a month')]),

"fig_a11_u04_p09_v03b": dict(type='V3',
 title='Four days, and then one',
 sub='Five panels. Panel four does the damage, not panel three.',
 alt='Five panels following a self-imposed rule: making it, keeping it for four days, breaking it '
     'once, deciding this means failure, and stopping altogether.',
 panels=[
  dict(caption='1 Thirty minutes a day. No exceptions',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='2 Day 1 to 4. It works',
       art=[dict(kind='tick', x=150, y=60), dict(kind='tick', x=150, y=20)]),
  dict(caption='3 Day 5. One missed day',
       art=[dict(kind='cross', x=150, y=40)]),
  dict(caption='4 "I can\'t do this"',
       art=[dict(kind='person', x=150, y=0, h=108, skin=2, cloth=4)]),
  dict(caption='5 Day 6 onwards. Nothing',
       art=[dict(kind='gap', x=150, y=20, w=120, bh=80)])]),

"fig_a11_u04_p10_v12": dict(type='V12',
 title='Eleven signs, three questions each',
 sub='Who put it there, how old it is, and how many people obey it. The three bands do not line up.',
 alt='An infographic laying out the eleven signs in the building against three bands: the '
     'authority behind each sign, its age, and the proportion of people who follow it.',
 span=['the law', 'nobody'], ticks=4,
 tick_labels=['the city', 'the school', 'a person', 'nobody'],
 bands=[dict(name='Authority', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.22}, label='4 signs - fire and the law, screwed to the wall',
        colour='#1F4E5F'),
   dict(**{'from': 0.24, 'to': 0.58}, label='4 signs - the school, four years ago, taped',
        colour='#C86B2B'),
   dict(**{'from': 0.60, 'to': 1.0}, label='3 signs - handwritten, no name', colour='#A8372E')]),
  dict(name='Age', type='events', items=[
   dict(at=0.08, label='renewed every year', colour='#2E6F5E'),
   dict(at=0.36, label='four years, three deciders gone', colour='#C86B2B'),
   dict(at=0.66, label='Out of order - since March, and it works', colour='#A8372E'),
   dict(at=0.88, label='Keep right - nobody remembers it going up', colour='#A8372E')]),
  dict(name='Who obeys it', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.22}, label='everybody', colour='#2E6F5E'),
   dict(**{'from': 0.24, 'to': 0.58}, label='almost everybody', colour='#2E6F5E'),
   dict(**{'from': 0.60, 'to': 0.74}, label='nobody - Keep right', colour='#9AA7AE'),
   dict(**{'from': 0.76, 'to': 1.0}, label='everybody - Out of order, and it is wrong',
        colour='#D9A441')]),
  dict(name='Could be removed', type='line',
   points=[(0, 0), (0.25, 1), (0.6, 3), (0.8, 4), (1.0, 4)], end_label='4'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.20, label='the signs with the most authority are the ones nobody argues with'),
   dict(at=0.62, label='the sign nobody obeys and the sign everybody obeys are the same age'),
   dict(at=0.90, label='the most obeyed sign in the building is also the only untrue one')])]),

"fig_a11_u04_p11_v04b": dict(type='V4', height=720,
 title='The same lift door, twice',
 sub='The rule is identical in both. Only the paper is different.',
 alt='Two drawings of the same lift door. On the left, the old taped notice with a handwritten '
     'line under it. On the right, a small printed sign carrying a name and a date, with a key '
     'hook beside the door.',
 differences=6, prompt='Find the six. One of them is behind the door, on the stairs - and it is '
                       'the one that measures whether this worked.',
 left=dict(label='as it is', art=[
   dict(kind='block', x=150, y=130, w=200, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=150, y=98, w=150, bh=18, colour='#C86B2B'),
   dict(kind='gap', x=150, y=66, w=200, bh=22),
   dict(kind='label', x=300, y=210, text='STAFF ONLY · no name · no date · a queue on the stairs',
        colour='#A8372E')]),
 right=dict(label='with a name on it', art=[
   dict(kind='block', x=150, y=130, w=200, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=98, w=200, bh=18, colour='#1F4E5F'),
   dict(kind='block', x=150, y=66, w=90, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='Ask at reception · A. Silva, March · a key hook',
        colour='#2E6F5E')])),
}
