"""A1.1 Unit 5 - One Dictionary, Eleven People - fifteen figures, as data."""
FIGURES = {
"fig_a11_u05_p00_v01": dict(type='V1', height=900, storey_h=116,
 title='Room 3 at ten past nine, from the front',
 sub='Fourteen things to find. One of them has not moved since Tuesday.',
 alt='A classroom seen from the front with eleven desks, a board still carrying yesterday\'s '
     'lesson, and an open cupboard holding a single shelf with one dictionary, a box of pens and '
     'four notebooks.',
 sky='#DCE3E3', ground='#AFA392', ground_line=700,
 buildings=[dict(x=20, w=560, storeys=4, colour='#C8BBA0', cutaway=True,
     floor_labels=['the top of the board - yesterday, not wiped',
                   'the board - today, nothing yet',
                   'the cupboard - one shelf',
                   'the front desk'],
     label='the front wall of room 3'),
   dict(x=660, w=520, storeys=2, colour='#BFC9CB',
     label='the window - and a plant that belongs to nobody'),
   dict(x=1260, w=320, storeys=3, colour='#C6BDA9', label='the back wall - the clock, and the door')],
 props=[dict(kind='table', x=640, y=700, s=1.1), dict(kind='table', x=800, y=700, s=1.1),
   dict(kind='table', x=960, y=700, s=1.1), dict(kind='table', x=1120, y=700, s=1.1),
   dict(kind='chair', x=700, y=700, s=1.0), dict(kind='chair', x=860, y=700, s=1.0),
   dict(kind='chair', x=1020, y=700, s=1.0),
   dict(kind='box', x=1200, y=700, s=1.0),
   dict(kind='sign', x=1400, y=700, s=.7, text='9:10'),
   dict(kind='tree', x=620, y=700, s=.7),
   dict(kind='crate', x=1480, y=700, s=1.0)],
 people=[dict(x=200, y=700, h=88, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=760, y=700, h=84, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=920, y=700, h=84, skin=4, cloth=3, hair='short', arm='down'),
   dict(x=1080, y=700, h=84, skin=0, cloth=1, hair='cap', arm='hold'),
   dict(x=1340, y=700, h=84, skin=3, cloth=2, hair='bun', arm='folded')],
 names=[dict(x=200, t='Teresa - at the board, teaching at ten'),
   dict(x=760, t='Lin - she looked a word up on Tuesday'),
   dict(x=920, t='Yusuf - a notebook, and no pen'),
   dict(x=1080, t='Emre - the dictionary is on his desk, face down'),
   dict(x=1340, t='Ana - counting what is in the cupboard'),
   dict(x=1400, t='the clock: ten past nine'),
   dict(x=1200, t='the box of pens - one box, eleven people'),
   dict(x=620, t='the plant - somebody waters it')],
 markers=[dict(x=200, y=578), dict(x=760, y=582), dict(x=920, y=582), dict(x=1080, y=582),
   dict(x=1340, y=582), dict(x=1400, y=636), dict(x=1200, y=652), dict(x=620, y=640),
   dict(x=640, y=656), dict(x=700, y=664), dict(x=1480, y=660), dict(x=960, y=656),
   dict(x=300, y=466), dict(x=300, y=350)]),

"fig_a11_u05_p01_v08": dict(type='V8', height=760,
 title='What moves between the things in a room',
 sub='Six objects, and a line for every journey a word can make. One line leaves the room.',
 alt='A network of six classroom objects - board, desk, cupboard, notebook, dictionary and '
     'homework - joined by labelled lines showing what travels between them, with the homework '
     'line leaving the room and returning the next day.',
 nodes={
  'bd':  dict(x=300, y=220, short='B', name='the board', sub='yesterday, still on it',
              colour='#1F4E5F'),
  'dk':  dict(x=700, y=400, short='D', name='the desk', sub='eleven, three wobble', r=54,
              colour='#2E6F5E'),
  'cup': dict(x=300, y=580, short='C', name='the cupboard', sub='one shelf', colour='#9AA7AE'),
  'nb':  dict(x=1080, y=220, short='N', name='the notebook', sub='four spare', colour='#C86B2B'),
  'dic': dict(x=1080, y=580, short='?', name='the dictionary', sub='one, face down',
              colour='#8C6A9E'),
  'hw':  dict(x=1420, y=400, short='H', name='the homework', sub='it leaves', r=50,
              colour='#D9A441')},
 edges=[dict(a='bd', b='nb', label='a word, copied', sw=6),
   dict(a='cup', b='dk', label='a pen, if there is one', sw=4),
   dict(a='dk', b='nb', label='a sentence, written', sw=6),
   dict(a='nb', b='dic', label='a word you did not know', sw=5),
   dict(a='dic', b='nb', label='and a meaning, back', sw=3, dash='6 5'),
   dict(a='nb', b='hw', label='out of the building, and back tomorrow', sw=5,
        colour='#D9A441')]),

"fig_a11_u05_p01_v02a": dict(type='V2', height=780,
 title='The cupboard, shelf by shelf',
 sub='Eleven things. Eleven words. Everything the school owns for this room is here.',
 alt='A cutaway of the classroom cupboard showing each shelf and what is on it, with empty '
     'labels, and one shelf that is empty and labelled too.',
 floors=[dict(was='the top shelf', now='one dictionary · a box of pens · a stack of paper',
     year='', fill='#F3EADA'),
   dict(was='the second shelf', now='four notebooks · a pencil case with no pencils in it',
     year='', fill='#E8EEF0'),
   dict(was='the third shelf', now='last year\'s exercise books, nobody\'s', year='',
     fill='#EFE6DC'),
   dict(was='the bottom shelf', now='empty - and it has a label too', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='dictionary · pen · page · word'),
   dict(at=0.38, text='notebook · pencil · exercise'),
   dict(at=0.62, text='homework · answer · question'),
   dict(at=0.88, text='the empty shelf is the one this unit is about')]),

"fig_a11_u05_p02_v07": dict(type='V7', height=820,
 title='In front of the open cupboard',
 sub='One of them is counting. The other one is teaching in fifty minutes.',
 alt='A teacher and a receptionist standing in front of an open classroom cupboard with a '
     'clipboard between them, each with two speech balloons and a thought balloon.',
 bg='#EAE6DA',
 set=[dict(kind='crate', x=760, y=660, s=1.3), dict(kind='box', x=1300, y=660, s=1.1),
   dict(kind='chair', x=1400, y=660, s=1.2)],
 people=[dict(x=520, h=242, skin=1, cloth=0, hair='grey', arm='point', facing='right',
   label='Teresa', role='she teaches in this room at ten',
   says=['There is one dictionary. There are eleven of us.',
         'There aren\'t any pencils at all.'],
   thinks=['What do I do at ten without it?']),
  dict(x=1080, h=238, skin=3, cloth=2, hair='bun', arm='hold', facing='left',
   label='Ana', role='she has the inventory list',
   says=['Are there any notebooks?', 'We have two hundred euros for this room.'],
   thinks=['Two hundred. That is eleven of something cheap.'])]),

"fig_a11_u05_p03_v09a": dict(type='V9', kind='weight', height=500,
 title='The verb looks forwards, not backwards',
 sub='There is not a thing. The thing arrives after the verb, and the verb agrees with that.',
 alt='Two rows of boxes. In the first, there is is followed by one object; in the second, there '
     'are is followed by a row of identical objects, with an arrow pointing forwards from the '
     'verb to what it agrees with.',
 parts=[dict(w=16, role='not a thing', text='There', colour='#9AA7AE'),
   dict(w=14, role='one', text='is', colour='#1F4E5F'),
   dict(w=26, role='→ the verb agrees with this', text='a board', colour='#2E6F5E'),
   dict(w=14, role='more than one', text='are', colour='#C86B2B'),
   dict(w=30, role='→ and with this', text='eleven desks', colour='#2E6F5E')],
 note='There holds the front of the sentence open and means nothing. Look past it, find the '
      'thing, and count it: one board, so is; eleven desks, so are.'),

"fig_a11_u05_p03_v09b": dict(type='V9', kind='branch', height=680,
 title='a, an, some and any',
 sub='Three roads out of one question: how many, and what kind of sentence is this?',
 alt='A branching diagram sorting a, an, some and any by whether the thing is countable, how '
     'many there are, and whether the sentence is positive, negative or a question.',
 root='how many?',
 branches=[dict(label='ONE, and you can count it — a / an', colour='#1F4E5F',
     example='a desk · a pen · an exercise · an answer -- an before a vowel SOUND'),
   dict(label='MORE THAN ONE, or an amount — some', colour='#2E6F5E',
     example='some pens · some paper -- in positive sentences'),
   dict(label='NEGATIVE or QUESTION — any', colour='#C86B2B',
     example='There aren\'t any pens. Are there any pens? -- the two doorways')]),

"fig_a11_u05_p03_v11": dict(type='V11', height=700,
 title='The verb that agreed with the wrong word',
 alt='Two panels comparing There is eleven desks with There are eleven desks, the first showing '
     'the verb reaching backwards to the word there.',
 wrong=dict(sentence='There is eleven desks.',
            boundary=0.30, boundary_label='There',
            event=0.52, event_label='is - agreeing with a word that is not a thing',
            why='The verb has reached backwards and found there, which looks like a subject and '
                'is not one. There is a placeholder: it has no number, no size and nothing to '
                'agree with. Behind the verb, eleven desks are waiting, and they are plural.'),
 right=dict(sentence='There are eleven desks.',
            boundary=0.30, boundary_label='There',
            event=0.58, event_label='are - agreeing with the eleven desks',
            why='The verb looks forwards. Whatever arrives after it decides the form: one board, '
                'so is; eleven desks, so are. This is the only sentence pattern in English where '
                'the subject comes after the verb, which is why it feels strange.'),
 misconception='Every other sentence you have met puts the subject first, so the eye reaches for '
               'the nearest word on the left. Here there is nothing on the left. Read past the '
               'verb before you choose it.'),

"fig_a11_u05_p04_v04a": dict(type='V4', height=720,
 title='Two drawings of the same room',
 sub='Both learners listened to a one-minute description. Both drew what they heard.',
 alt='Two drawings of the same classroom made from two spoken descriptions. The left one has the '
     'furniture in roughly the right places; the right one has the right objects in the wrong '
     'places.',
 differences=6, prompt='Find the six. One description said where things were and one only said '
                       'what they were. Which drawing came from which?',
 left=dict(label='the room', art=[
   dict(kind='block', x=150, y=130, w=230, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=180, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=120, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='board at the front · cupboard by the window',
        colour='#2E6F5E')]),
 right=dict(label='the same words, no places', art=[
   dict(kind='block', x=150, y=130, w=120, bh=22, colour='#C86B2B'),
   dict(kind='block', x=150, y=98, w=230, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=66, w=180, bh=22),
   dict(kind='label', x=300, y=210, text='a board · a cupboard · desks · somewhere',
        colour='#C86B2B')])),

"fig_a11_u05_p05_v05": dict(type='V5', height=900,
 title='The inventory list for room 3',
 sub='Printed in March. Filled in by hand in June. Four rows do not match.',
 alt='The school inventory list for room 3, with a printed column for how many items there '
     'should be and a handwritten column for how many there are, with four mismatched rows and '
     'an unsigned signature line.',
 rows=[dict(t='org', text='ESCOLA MONTE  -  ROOM 3  -  INVENTORY'),
   dict(t='grid', cols=['ITEM', 'SHOULD BE', 'THERE ARE'],
     data=[['DESKS', '11', '11'],
           ['CHAIRS', '11', '10'],
           ['BOARD', '1', '1'],
           ['DICTIONARIES', '2', '1'],
           ['NOTEBOOKS', '11', '4'],
           ['PENS (BOXES)', '1', '1'],
           ['PENCILS', '20', '0'],
           ['CLOCK', '1', '1']]),
   dict(t='rule'),
   dict(t='head', text='AT THE BOTTOM OF THE SHEET'),
   dict(t='kv', k='Checked by', v='(blank)', mono=False),
   dict(t='kv', k='Date checked', v='(blank)', mono=False),
   dict(t='kv', k='Budget, this room, this year', v='200 EUR', mono=True),
   dict(t='rule'),
   dict(t='para', text='In the NOTEBOOKS row the number was written 7, crossed out, and '
     'written again as 4. Somebody counted twice, three days apart, and lost three notebooks '
     'between the two counts.')],
 callouts=[dict(at=0.18, text='Eleven desks and ten chairs. One person stands, every lesson'),
   dict(at=0.30, text='Two dictionaries on the list. One in the room'),
   dict(at=0.38, text='Twenty pencils on the list. None at all'),
   dict(at=0.68, text='Nobody signed it, so nobody is answerable for any of this'),
   dict(at=0.92, text='7, crossed out, then 4. Three notebooks in three days')]),

"fig_a11_u05_p06_v03a": dict(type='V3',
 title='One rule, five exceptions',
 sub='The rule is add s. Everything interesting is in the other five panels.',
 alt='Six panels showing how English makes plurals: add s, add es after a hiss, y becomes ies, f '
     'becomes ves, words that change in the middle, and words that do not change at all.',
 panels=[
  dict(caption='1 book → books. Add s', art=[dict(kind='doc', x=160, y=0)]),
  dict(caption='2 box → boxes. A hiss needs a vowel',
       art=[dict(kind='block', x=160, y=10, w=90, bh=70, colour='#1F4E5F')]),
  dict(caption='3 city → cities. The y goes',
       art=[dict(kind='block', x=160, y=10, w=70, bh=80, colour='#2E6F5E')]),
  dict(caption='4 knife → knives. The f softens',
       art=[dict(kind='arrow', x=160, y=50)]),
  dict(caption='5 man → men. Inside the word',
       art=[dict(kind='person', x=160, y=0, h=110, skin=1, cloth=0)]),
  dict(caption='6 fish → fish. Nothing at all',
       art=[dict(kind='gap', x=160, y=20, w=100, bh=60)])]),

"fig_a11_u05_p07_v10": dict(type='V10', kind='mouth', height=680,
 title='The sound that lives between your teeth',
 sub='Two millimetres of tongue. It is the difference between there and dare.',
 alt='Two mouth cross-sections. In the first the tongue tip is between the teeth with the voice '
     'on; in the second the same position with the voice off, with example words under each.',
 sounds=[
  dict(ipa='/ð/', desc='tongue between the teeth, voice ON - and it is the common one',
       examples='there · the · this · they · with', length='long',
       tongue=dict(high=.52, front=.98), lips='neutral'),
  dict(ipa='/θ/', desc='the same place, voice OFF - just air',
       examples='think · thing · three · thank · month', length='short',
       tongue=dict(high=.52, front=.98), lips='spread')]),

"fig_a11_u05_p09_v02b": dict(type='V2', height=780,
 title='One word, in layers',
 sub='Four meetings, four depths. Only the bottom one is yours.',
 alt='A cutaway of a single word in four layers: a shape you have seen, a shape with a '
     'translation, a shape inside a sentence, and a word that leaves your own mouth unasked.',
 floors=[dict(was='meeting 1', now='a shape. You have seen it. You could not use it', year='',
     fill='#E8EEF0'),
   dict(was='meetings 2 and 3', now='a shape with a translation stuck to it', year='',
     fill='#F3EADA'),
   dict(was='meetings 4 and 5', now='a shape inside a sentence - you recognise it when you read',
     year='', fill='#EFE6DC'),
   dict(was='meetings 6 and 7', now='it comes out of your mouth without being fetched', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='This is where a word list leaves every word'),
   dict(at=0.38, text='Translation is a rope. It works, and you have to pull it every time'),
   dict(at=0.62, text='Reading gets you here. Most learners stop here'),
   dict(at=0.88, text='Only speaking and writing take a word this far down')]),

"fig_a11_u05_p09_v03b": dict(type='V3',
 title='Day 1, day 3, day 7, day 21',
 sub='Five panels. The effort shrinks and never reaches zero, and that is the good news.',
 alt='Five panels showing the same word recalled after one day, three days, a week, three weeks '
     'and three months, with the effort needed shrinking at each meeting.',
 panels=[
  dict(caption='Day 1 - met, and written down',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='Day 3 - hard, and it comes',
       art=[dict(kind='block', x=150, y=10, w=110, bh=90, colour='#A8372E')]),
  dict(caption='Day 7 - slower than you expect',
       art=[dict(kind='block', x=150, y=10, w=110, bh=62, colour='#C86B2B')]),
  dict(caption='Day 21 - almost free',
       art=[dict(kind='block', x=150, y=10, w=110, bh=34, colour='#D9A441')]),
  dict(caption='Month 3 - and still not zero',
       art=[dict(kind='block', x=150, y=10, w=110, bh=16, colour='#2E6F5E'),
            dict(kind='tick', x=150, y=120)])]),

"fig_a11_u05_p10_v12": dict(type='V12',
 title='One term, one word list',
 sub='Three hundred and fifty words were taught. Follow them to June.',
 alt='An infographic following one term\'s vocabulary from the lesson that taught it, through '
     'later lessons, into students\' own speech, and on to what is still known in June.',
 span=['September', 'June'], ticks=4,
 tick_labels=['taught', 'met again', 'used', 'June'],
 bands=[dict(name='Taught', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='350 words, every one of them explained',
        colour='#1F4E5F')]),
  dict(name='Met again later', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.62}, label='218 words appeared in a later lesson',
        colour='#2E6F5E'),
   dict(**{'from': 0.63, 'to': 1.0}, label='132 never appeared again', colour='#9AA7AE')]),
  dict(name='Used by a student', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.34}, label='119 came out of a student\'s own mouth',
        colour='#C86B2B'),
   dict(**{'from': 0.35, 'to': 1.0}, label='231 were only ever read or heard',
        colour='#9AA7AE')]),
  dict(name='Still there in June', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.27}, label='96 words', colour='#D9A441'),
   dict(**{'from': 0.28, 'to': 1.0}, label='254 gone, and they were all taught equally well',
        colour='#9AA7AE')]),
  dict(name='Survival', type='line',
   points=[(0, 350), (0.33, 218), (0.66, 119), (1.0, 96)], end_label='96'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.06, label='a word met once more survives three times as often'),
   dict(at=0.40, label='nearly every word that survived was used by the student')])]),

"fig_a11_u05_p11_v04b": dict(type='V4', height=720,
 title='The same shelf in June',
 sub='Two hundred euros, spent two ways, nine months earlier.',
 alt='Two drawings of the same shelf in June. On the left, eleven dictionaries in a straight row '
     'with dust on the top edge. On the right, twenty readers with eight gaps where books are out '
     'with students, and a sign-out sheet taped to the shelf.',
 differences=6, prompt='Find the six. One of them is a piece of paper, and it is the one that '
                       'tells you which shelf is working.',
 left=dict(label='eleven dictionaries', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='label', x=300, y=210, text='11 books · 0 out · dust on the top edge',
        colour='#1F4E5F')]),
 right=dict(label='twenty readers', art=[
   dict(kind='block', x=150, y=130, w=150, bh=22, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='block', x=150, y=66, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='12 here · 8 out · a sign-out sheet, taped',
        colour='#2E6F5E')])),
}
