"""A1.1 Unit 6 - Two Streets from the Cafe - fifteen figures, as data."""
FIGURES = {
"fig_a11_u06_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The market at seven, down the hill',
 sub='Fourteen things to find. Two of the stalls are selling the same thing at the same price.',
 alt='A street market early in the morning with six stalls, open crates, a van being unloaded, a '
     'queue of four people at one stall and nobody at the identical stall beside it.',
 sky='#CFD9DC', ground='#9E9382', ground_line=700,
 buildings=[dict(x=20, w=420, storeys=3, colour='#C7BBA2',
     label='the shop at the top of the street - open all day'),
   dict(x=520, w=560, storeys=2, colour='#D6C9A6', cutaway=True,
     floor_labels=['the awning', 'six stalls'],
     label='the market'),
   dict(x=1160, w=420, storeys=3, colour='#BAC3C4',
     label='the bakery, two streets away - baked at five')],
 props=[dict(kind='stall', x=560, y=700, s=.9), dict(kind='stall', x=800, y=700, s=.9),
   dict(kind='crate', x=1040, y=700, s=1.1), dict(kind='crate', x=1120, y=700, s=1.1),
   dict(kind='van', x=1300, y=700, s=.9),
   dict(kind='box', x=460, y=700, s=1.0),
   dict(kind='sign', x=500, y=700, s=.7, text='2.20'),
   dict(kind='sign', x=180, y=700, s=.7, text='SHOP'),
   dict(kind='tree', x=1120, y=700, s=.8)],
 people=[dict(x=620, y=700, h=84, skin=3, cloth=0, hair='cap', arm='hold'),
   dict(x=700, y=700, h=84, skin=1, cloth=2, hair='bun', arm='down'),
   dict(x=780, y=700, h=84, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=860, y=700, h=84, skin=2, cloth=4, hair='long', arm='folded'),
   dict(x=1020, y=700, h=88, skin=0, cloth=1, hair='grey', arm='point')],
 names=[dict(x=620, t='Marco - two bags, every Tuesday'),
   dict(x=700, t='a queue of four, at seven'),
   dict(x=780, t='the stall with the handwritten sign'),
   dict(x=860, t='the same tomatoes, the same price'),
   dict(x=1020, t='nineteen years here, and nobody in front of her'),
   dict(x=180, t='the shop - a fridge, a card machine'),
   dict(x=500, t='the sign: two euros twenty a kilo'),
   dict(x=1300, t='the van, half unloaded')],
 markers=[dict(x=620, y=582), dict(x=700, y=582), dict(x=780, y=582), dict(x=860, y=582),
   dict(x=1020, y=578), dict(x=180, y=636), dict(x=500, y=636), dict(x=1300, y=646),
   dict(x=1040, y=660), dict(x=1120, y=660), dict(x=460, y=652), dict(x=1180, y=640),
   dict(x=560, y=600), dict(x=940, y=600)]),

"fig_a11_u06_p01_v08": dict(type='V8', height=760,
 title='One breakfast, backwards',
 sub='Six things in a cup and on a plate, and how far each of them came. One line leaves the page.',
 alt='A network with one cup of coffee and one piece of bread at the centre, and lines running '
     'back to the shop, the market, the van, the farm and the port, each labelled with a distance '
     'and a time.',
 nodes={
  'cup': dict(x=800, y=400, short='☕', name='one breakfast', sub='coffee and bread', r=62,
              colour='#1C2B33'),
  'bak': dict(x=400, y=200, short='B', name='bread', sub='2 streets, 4 hours', colour='#C86B2B'),
  'far': dict(x=360, y=580, short='M', name='milk', sub='11 km, yesterday', colour='#1F4E5F'),
  'por': dict(x=1240, y=190, short='C', name='coffee', sub='6,000 km, 3 weeks',
              colour='#8C6A9E'),
  'egg': dict(x=1240, y=580, short='E', name='egg', sub='40 km, Tuesday', colour='#D9A441'),
  'tap': dict(x=800, y=690, short='W', name='water', sub='under the street', r=48,
              colour='#2E6F5E'),
  'sug': dict(x=1480, y=380, short='?', name='sugar', sub='nobody knows', r=44,
              colour='#9AA7AE')},
 edges=[dict(a='bak', b='cup', label='walked, in a bag', sw=6),
   dict(a='far', b='cup', label='a van, at six', sw=5),
   dict(a='por', b='cup', label='a ship, then a lorry, then a shop', sw=5),
   dict(a='egg', b='cup', label='a crate, on Tuesday', sw=5),
   dict(a='tap', b='cup', label='it did not travel at all', sw=6, colour='#2E6F5E'),
   dict(a='por', b='sug', label='and nobody has ever asked', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_a11_u06_p01_v02a": dict(type='V2', height=780,
 title='One stall, in section',
 sub='Eleven foods. Eleven words. Put each word where it actually sits.',
 alt='A cutaway of a market stall from the front crates down through the table to the boxes '
     'underneath and the van behind, with empty labels.',
 floors=[dict(was='the front crates', now='tomato · apple · the ones people see first',
     year='', fill='#F3EADA'),
   dict(was='the table', now='cheese · bread · egg · the scales', year='',
     fill='#E8EEF0'),
   dict(was='under the table', now='rice · sugar · salt · in packets and sacks',
     year='', fill='#EFE6DC'),
   dict(was='the van behind', now='milk · water · fish · what has not come out yet',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='You can count these. One, two, eleven'),
   dict(at=0.38, text='You can count the eggs. You cannot count the cheese'),
   dict(at=0.62, text='None of these can be counted. All of them can be weighed'),
   dict(at=0.88, text='And the van is where run out of is decided')]),

"fig_a11_u06_p02_v07": dict(type='V7', height=820,
 title='Seven o\'clock at the stall',
 sub='He buys for a cafe. She has sold here for nineteen years. Neither says the real question.',
 alt='A cafe owner with two bags at a market stall, crates between him and the woman behind it, '
     'each with two speech balloons and a thought balloon.',
 bg='#E7E0CE',
 set=[dict(kind='crate', x=760, y=660, s=1.3), dict(kind='crate', x=860, y=660, s=1.3),
   dict(kind='box', x=1340, y=660, s=1.1)],
 people=[dict(x=520, h=242, skin=3, cloth=0, hair='cap', arm='hold', facing='right',
   label='Marco', role='every Tuesday, for six years',
   says=['How much is it?', 'Two kilos, please. And six eggs.'],
   thinks=['Can I sell two kilos before Thursday?']),
  dict(x=1080, h=240, skin=0, cloth=1, hair='grey', arm='point', facing='left',
   label='the stallholder', role='nineteen years at this stall',
   says=['Two twenty a kilo. How many do you want?',
         'There aren\'t any eggs left. Tomorrow?'],
   thinks=['Will he still come when I put the price up?'])]),

"fig_a11_u06_p03_v09a": dict(type='V9', kind='weight', height=500,
 title='Things you count and things you weigh',
 sub='The same wheat is bread and a sandwich. The food did not change. The language did.',
 alt='Two groups of boxes. On the left, countable foods with numbers in front of them; on the '
     'right, uncountable foods with containers in front of them instead.',
 parts=[dict(w=18, role='countable', text='six eggs', colour='#1F4E5F'),
   dict(w=20, role='countable', text='eleven apples', colour='#1F4E5F'),
   dict(w=20, role='uncountable', text='some bread', colour='#C86B2B'),
   dict(w=20, role='uncountable', text='some rice', colour='#C86B2B'),
   dict(w=24, role='the bridge', text='two loaves of bread', colour='#2E6F5E')],
 note='How many goes with the blue. How much goes with the orange. The green is the bridge: put '
      'a container in front and anything becomes countable again.'),

"fig_a11_u06_p03_v09b": dict(type='V9', kind='mirror', height=640,
 title='The container is the bridge',
 sub='Bread cannot take a number. A loaf can, and it carries the bread across with it.',
 alt='Two sentence diagrams. In the first, a number tries to attach directly to bread; in the '
     'second, the number attaches to loaves and of bread hangs beneath it.',
 labels=['NO BRIDGE', 'WITH A BRIDGE'],
 between='↕ the number lands on the container, not on the food',
 active=dict(parts=[dict(w=16, role='hidden', text='two'),
   dict(w=28, role='affected', text='bread'),
   dict(w=36, role='hidden', text='— nothing for the number to land on')]),
 passive=dict(parts=[dict(w=14, role='agent', text='two'),
   dict(w=22, role='action', text='loaves'),
   dict(w=14, role='hidden', text='of'),
   dict(w=26, role='affected', text='bread')]),
 rule='Any uncountable food becomes countable the moment you name its container or its weight: '
      'a bottle of water, a kilo of rice, a slice of cheese, a bit of sugar.'),

"fig_a11_u06_p03_v11": dict(type='V11', height=700,
 title='The number with nothing to land on',
 alt='Two panels comparing two breads with two loaves of bread, the first showing a number '
     'floating above a substance with no object beneath it.',
 wrong=dict(sentence='I bought two breads.',
            boundary=0.30, boundary_label='two',
            event=0.58, event_label='bread - a substance, with no edges',
            why='A number needs something with edges to count. Bread, in English, is a substance '
                'like water or sand: it has no edges, so the number has nothing to settle on. '
                'Many languages count it happily, which is why this error is so common and so '
                'invisible to the person making it.'),
 right=dict(sentence='I bought two loaves of bread.',
            boundary=0.30, boundary_label='two',
            event=0.50, event_label='loaves - and these have edges',
            why='Loaves are objects. The number lands on them and the bread hangs underneath, '
                'unchanged and still uncountable. Every container word in this unit does the '
                'same job: bottle, packet, kilo, slice, piece.'),
 misconception='The mistake is not in the food, it is in the picture. Ask yourself whether you '
               'could draw a line round one of them. One egg, yes. One bread, no - you would '
               'have to draw a loaf, and that is the word you need.'),

"fig_a11_u06_p04_v04a": dict(type='V4', height=720,
 title='The same stall, two Tuesdays',
 sub='Same hour, same tomatoes, same price. One of them has a piece of card on it.',
 alt='Two photographs of the same market stall at the same hour on two different Tuesdays, one '
     'with a handwritten price sign and a queue, one without a sign and without a queue.',
 differences=6, prompt='Find the six. One of them is not on the stall at all - it is in front of '
                       'it, and it is what the sign bought.',
 left=dict(label='with a sign', art=[
   dict(kind='block', x=150, y=130, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='2.20 a kilo · the farm · the village · 9 people',
        colour='#2E6F5E')]),
 right=dict(label='no sign', art=[
   dict(kind='gap', x=150, y=130, w=200, bh=22),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#C86B2B'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#C86B2B'),
   dict(kind='label', x=300, y=210, text='2.20 a kilo · nineteen years · nobody, at seven',
        colour='#C86B2B')])),

"fig_a11_u06_p05_v05": dict(type='V5', height=900,
 title='The till receipt from the shop',
 sub='The same six things Marco buys at the market. Everything here is a number except one line.',
 alt='A till receipt listing six grocery items with amounts, unit prices and totals, followed by '
     'the total, the card line, the time and a line of small print offering ten per cent off next '
     'Tuesday.',
 rows=[dict(t='org', text='MERCEARIA DO ALTO  -  RUA DA ESCOLA 2'),
   dict(t='grid', cols=['ITEM', 'AMOUNT', 'EUR'],
     data=[['TOMATOES', '1 kg', '3.10'],
           ['BREAD', '2 loaves', '1.40'],
           ['MILK', '6 x 1 L', '5.34'],
           ['EGGS', '12', '3.60'],
           ['RICE', '1 kg', '1.85'],
           ['CHEESE', '220 g', '4.07']]),
   dict(t='rule'),
   dict(t='kv', k='TOTAL', v='19.36', mono=True),
   dict(t='kv', k='CARD', v='**** 4417', mono=True),
   dict(t='kv', k='TIME', v='07.04', mono=True),
   dict(t='kv', k='ITEMS', v='6', mono=True),
   dict(t='rule'),
   dict(t='sign', text='AND IN SMALL PRINT:'),
   dict(t='para', text='"10% off your next shop, Tuesdays only, before 9 a.m." The only line on '
     'this receipt that is not about what you bought. It is about when you come back.')],
 callouts=[dict(at=0.14, text='Three ten a kilo. The market is two euros twenty'),
   dict(at=0.26, text='Six times one litre - the amount is in the line, not just the price'),
   dict(at=0.40, text='Two hundred and twenty grams. Weighed, not counted'),
   dict(at=0.66, text='Seven minutes past seven. He was here before the market opened'),
   dict(at=0.92, text='Tuesdays, before nine. Exactly when he goes to the market')]),

"fig_a11_u06_p06_v03a": dict(type='V3',
 title='The same rice, six times',
 sub='The rice never changes. The word in front of it changes in every panel.',
 alt='Six panels showing the same rice loose in a sack, in a kilo bag, in a packet, in a jar, in '
     'a bowl and on a plate, each with the phrase used for it.',
 panels=[
  dict(caption='loose in a sack: rice', art=[dict(kind='block', x=160, y=0, w=120, bh=70,
     colour='#C9A97A')]),
  dict(caption='a kilo of rice', art=[dict(kind='block', x=160, y=0, w=90, bh=90,
     colour='#1F4E5F')]),
  dict(caption='a packet of rice', art=[dict(kind='block', x=160, y=0, w=70, bh=100,
     colour='#2E6F5E')]),
  dict(caption='a jar of rice', art=[dict(kind='block', x=160, y=0, w=60, bh=80,
     colour='#8C6A9E')]),
  dict(caption='a bowl of rice', art=[dict(kind='block', x=160, y=0, w=100, bh=46,
     colour='#D9A441')]),
  dict(caption='and on the plate: rice again', art=[dict(kind='block', x=160, y=0, w=130,
     bh=24, colour='#C9A97A'), dict(kind='arrow', x=160, y=120)])]),

"fig_a11_u06_p07_v10": dict(type='V10', kind='mouth', height=680,
 title='Long ee and short e',
 sub='Cheese and bread. The jaw moves between these two and most learners keep it still.',
 alt='Two mouth cross-sections for the long ee and the short e, with the tongue high and forward '
     'for the first and lower for the second, and minimal pairs under each.',
 sounds=[
  dict(ipa='/iː/', desc='long, high and far forward - the lips spread',
       examples='cheese · tea · meat · need · three', length='long',
       tongue=dict(high=.90, front=.92), lips='spread'),
  dict(ipa='/e/', desc='short, and the jaw drops a little',
       examples='bread · egg · ten · cent · left', length='short',
       tongue=dict(high=.58, front=.78), lips='neutral')]),

"fig_a11_u06_p09_v02b": dict(type='V2', height=780,
 title='One jar, or seven bottles',
 sub='The same four hours, in two shapes. The drawing shows why only one of them fits.',
 alt='A cutaway comparing one large jar holding four hours on a Sunday with seven small bottles '
     'holding twenty minutes each, the two having the same volume but very different shapes.',
 floors=[dict(was='the Sunday jar', now='four hours, planned, in one container', year='',
     fill='#E8EEF0'),
   dict(was='what actually goes in', now='about seventy minutes, and then it spills', year='',
     fill='#F3EADA'),
   dict(was='the seven bottles', now='twenty minutes each, and every one of them fills',
     year='', fill='#EFE6DC'),
   dict(was='the same volume', now='two hours twenty - and all of it arrived', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The plan. It has been the plan for three years'),
   dict(at=0.38, text='Seventy minutes is not a failure of will. It is a failure of shape'),
   dict(at=0.62, text='Twenty minutes is short enough that starting is not a decision'),
   dict(at=0.88, text='Less time planned, more time done')]),

"fig_a11_u06_p09_v03b": dict(type='V3',
 title='Pouring four hours into Sunday',
 sub='Five panels. Watch where it stops going in.',
 alt='Five panels showing four hours being poured into one Sunday: the first hour going in '
     'easily, the second slowly, the third spilling and the fourth not going in at all.',
 panels=[
  dict(caption='The plan: four hours',
       art=[dict(kind='block', x=150, y=0, w=110, bh=120, colour='#1F4E5F')]),
  dict(caption='Hour 1 - it goes in',
       art=[dict(kind='block', x=150, y=0, w=110, bh=90, colour='#2E6F5E')]),
  dict(caption='Hour 2 - slower',
       art=[dict(kind='block', x=150, y=0, w=110, bh=56, colour='#D9A441')]),
  dict(caption='Hour 3 - it spills',
       art=[dict(kind='block', x=150, y=0, w=110, bh=26, colour='#C86B2B')]),
  dict(caption='Hour 4 - nothing',
       art=[dict(kind='gap', x=150, y=10, w=110, bh=70)])]),

"fig_a11_u06_p10_v12": dict(type='V12',
 title='One breakfast, as distance and time',
 sub='The cheapest thing on the plate travelled furthest and was touched by the most people.',
 alt='An infographic of one breakfast across four bands: how far each item travelled, how long it '
     'took, what it cost, and how many pairs of hands touched it between the field and the cup.',
 span=['the field', 'the cup'], ticks=4,
 tick_labels=['grown', 'moved', 'sold', 'eaten'],
 bands=[dict(name='Distance', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.06}, label='water - 0 km', colour='#2E6F5E'),
   dict(**{'from': 0.08, 'to': 0.14}, label='bread - 2 streets', colour='#C86B2B'),
   dict(**{'from': 0.16, 'to': 0.26}, label='milk - 11 km', colour='#1F4E5F'),
   dict(**{'from': 0.28, 'to': 0.42}, label='egg - 40 km', colour='#D9A441'),
   dict(**{'from': 0.44, 'to': 1.0}, label='coffee - 6,000 km', colour='#8C6A9E')]),
  dict(name='Time', type='events', items=[
   dict(at=0.06, label='water: no time at all', colour='#2E6F5E'),
   dict(at=0.22, label='bread: four hours', colour='#C86B2B'),
   dict(at=0.44, label='milk: one night', colour='#1F4E5F'),
   dict(at=0.68, label='egg: six days', colour='#D9A441'),
   dict(at=0.92, label='coffee: three weeks at sea', colour='#8C6A9E')]),
  dict(name='Cost in the cup', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.30}, label='coffee - 11 cents', colour='#8C6A9E'),
   dict(**{'from': 0.32, 'to': 0.56}, label='milk - 8 cents', colour='#1F4E5F'),
   dict(**{'from': 0.58, 'to': 1.0}, label='bread - 37 cents', colour='#C86B2B')]),
  dict(name='Hands that touched it', type='line',
   points=[(0, 1), (0.3, 3), (0.6, 7), (1.0, 14)], end_label='14'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.10, label='the thing that came furthest is the cheapest thing on the plate'),
   dict(at=0.48, label='fourteen people touched the coffee and you can name none of them')])]),

"fig_a11_u06_p11_v04b": dict(type='V4', height=720,
 title='The same counter at half past nine',
 sub='Bakery bread on the left, supermarket bread on the right. Three customers in both.',
 alt='Two drawings of the same cafe counter at half past nine, one with bakery bread and one '
     'with supermarket bread, three customers standing at each.',
 differences=6, prompt='Find the six. One of them is at the end of the day, not at half past '
                       'nine, and it is the one that decides the money.',
 left=dict(label='the bakery, 1.10', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#C86B2B'),
   dict(kind='block', x=150, y=98, w=190, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='3 loaves · 22 minutes walking · 0 left at two',
        colour='#C86B2B')]),
 right=dict(label='the supermarket, 0.70', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=66, w=100, bh=22, colour='#9AA7AE'),
   dict(kind='label', x=300, y=210, text='3 loaves · 40 seconds · 1 left at two',
        colour='#1F4E5F')])),
}
