"""A1.1 Unit 7 - Friday at Six - fifteen figures, as data."""
FIGURES = {
"fig_a11_u07_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The park at the bottom of the hill, Saturday, four o\'clock',
 sub='Fourteen things to find. Eleven people are doing something and four are watching them.',
 alt='A city park on a Saturday afternoon with a football game, a bench with two people and a '
     'guitar, three runners, somebody drawing, and a concert poster on a wall.',
 sky='#CCDBE2', ground='#8FA07C', ground_line=700,
 buildings=[dict(x=20, w=380, storeys=3, colour='#C0B8A4',
     label='the wall - and the concert poster on it'),
   dict(x=480, w=620, storeys=1, colour='#9FB888',
     label='the pitch - a game every Saturday for nine years'),
   dict(x=1180, w=400, storeys=2, colour='#B7C2C4', label='the cafe at the gate - closed at four')],
 props=[dict(kind='hoarding', x=120, y=700, s=.9, w=200, notice=True),
   dict(kind='table', x=1140, y=700, s=1.2),
   dict(kind='chair', x=1120, y=700, s=1.1),
   dict(kind='tree', x=440, y=700, s=1.2), dict(kind='tree', x=1160, y=700, s=1.0),
   dict(kind='box', x=1300, y=700, s=.9),
   dict(kind='crate', x=1500, y=700, s=1.0),
   dict(kind='sign', x=300, y=700, s=.7, text='4:00')],
 people=[dict(x=560, y=700, h=86, skin=4, cloth=3, hair='short', arm='point'),
   dict(x=700, y=700, h=86, skin=2, cloth=1, hair='cap', arm='down'),
   dict(x=840, y=700, h=86, skin=0, cloth=4, hair='long', arm='hold'),
   dict(x=1040, y=700, h=86, skin=3, cloth=2, hair='bun', arm='hold'),
   dict(x=1420, y=700, h=86, skin=1, cloth=0, hair='grey', arm='folded')],
 names=[dict(x=560, t='eleven playing, and nobody organised it'),
   dict(x=700, t='three running past, every Saturday'),
   dict(x=840, t='Emre - a guitar that belongs to nobody'),
   dict(x=1040, t='Lin - on the bench, and she came to play'),
   dict(x=1420, t='somebody drawing, alone'),
   dict(x=300, t='the clock on the gate: four o\'clock'),
   dict(x=220, t='the concert poster'),
   dict(x=1300, t='a bag, a bottle, and a dog asleep on both')],
 markers=[dict(x=560, y=580), dict(x=700, y=580), dict(x=840, y=580), dict(x=1040, y=580),
   dict(x=1420, y=580), dict(x=300, y=636), dict(x=220, y=640), dict(x=1300, y=650),
   dict(x=1140, y=650), dict(x=1120, y=664), dict(x=440, y=620), dict(x=1500, y=660),
   dict(x=620, y=620), dict(x=960, y=620)]),

"fig_a11_u07_p01_v08": dict(type='V8', height=760,
 title='What goes with what',
 sub='Eight things people do with a Saturday, and a line wherever two of them share something. '
     'Two have no line at all.',
 alt='Eight free-time activities in a ring with labelled lines joining the ones that share a '
     'quality, and two activities left unconnected.',
 nodes={
  'foo': dict(x=360, y=200, short='F', name='football', sub='22 people', colour='#2E6F5E'),
  'run': dict(x=260, y=480, short='R', name='running', sub='alone', colour='#1F4E5F'),
  'cyc': dict(x=460, y=680, short='C', name='cycling', sub='alone, faster', colour='#1F4E5F'),
  'mus': dict(x=800, y=180, short='M', name='music', sub='alone or together', r=54,
              colour='#C86B2B'),
  'dan': dict(x=1100, y=350, short='D', name='dancing', sub='together', colour='#C86B2B'),
  'coo': dict(x=1180, y=640, short='K', name='cooking', sub='you can give it away',
              colour='#D9A441'),
  'dra': dict(x=840, y=700, short='A', name='drawing', sub='cheap and quiet', colour='#8C6A9E'),
  'han': dict(x=1440, y=250, short='H', name='hang out', sub='no name for it', r=48,
              colour='#9AA7AE')},
 edges=[dict(a='run', b='cyc', label='nobody can talk to you', sw=6),
   dict(a='foo', b='run', label='you come home tired', sw=4),
   dict(a='mus', b='dan', label='one makes the other possible', sw=6),
   dict(a='coo', b='dra', label='you have something at the end', sw=5),
   dict(a='mus', b='foo', label='both work with eleven people or with one', sw=3, dash='6 5'),
   dict(a='han', b='mus', label='the only one with no equipment at all', sw=2, dash='5 6',
        colour='#9AA7AE')]),

"fig_a11_u07_p01_v02a": dict(type='V2', height=780,
 title='One Saturday, in section',
 sub='Eleven activities. Eleven words. Put each one in the hour where it actually happened.',
 alt='A cutaway of one Saturday hour by hour from waking to bed, showing what was done in each '
     'band, with empty labels.',
 floors=[dict(was='morning', now='cooking · a book · and two hours that vanished',
     year='', fill='#F3EADA'),
   dict(was='afternoon', now='the park · football · running · watching',
     year='', fill='#E8EEF0'),
   dict(was='evening', now='music · the guitar · dancing, somewhere else', year='',
     fill='#EFE6DC'),
   dict(was='late', now='a film · a series · a game · and then four more episodes',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The two hours nobody can account for'),
   dict(at=0.38, text='Eleven playing. Four watching. Two of the four came to play'),
   dict(at=0.62, text='The only part of the day that was arranged in advance'),
   dict(at=0.88, text='Four hours, and all of it already in English')]),

"fig_a11_u07_p02_v07": dict(type='V7', height=820,
 title='On the bench, four o\'clock',
 sub='There is a guitar between them and it belongs to neither of them.',
 alt='Two students sitting on a park bench with a guitar between them, each with two speech '
     'balloons and a thought balloon.',
 bg='#DEE8DA',
 set=[dict(kind='table', x=760, y=660, s=1.6), dict(kind='tree', x=1420, y=660, s=1.3),
   dict(kind='box', x=1300, y=660, s=1.0)],
 people=[dict(x=520, h=240, skin=2, cloth=1, hair='cap', arm='hold', facing='right',
   label='Emre', role='he plays most evenings',
   says=['I love playing. I usually play in the evening.',
         'I never go swimming. I hate it.'],
   thinks=['Should I offer it to her?']),
  dict(x=1080, h=238, skin=3, cloth=2, hair='bun', arm='down', facing='left',
   label='Lin', role='she has never played anything',
   says=['I don\'t like running. I quite like cycling.',
         'I hardly ever watch films in English.'],
   thinks=['If I say I can\'t play, he will offer.'])]),

"fig_a11_u07_p03_v09a": dict(type='V9', kind='scope', height=620,
 title='Where the frequency word stands',
 sub='Before an ordinary verb. After am, is and are. The verb decides, not the word.',
 alt='A sentence drawn as a row of words with brackets marking where a frequency adverb may '
     'stand: before an ordinary verb, and after the verb be.',
 words=['I', '(usually)', 'play', 'football', 'I', 'am', '(always)', 'late'],
 focus=[1, 2, 5, 6],
 brackets=[dict(**{'from': 1, 'to': 2}, lane=0, colour='#1F4E5F',
     label='an ordinary verb: the frequency word goes IN FRONT of it'),
   dict(**{'from': 5, 'to': 6}, lane=0, colour='#C86B2B',
     label='am, is, are: the frequency word goes AFTER it'),
   dict(**{'from': 0, 'to': 7}, lane=1, colour='#2E6F5E',
     label='Everything else in the sentence stays exactly where it was.')]),

"fig_a11_u07_p03_v09b": dict(type='V9', kind='ladder', height=760,
 title='From always down to never',
 sub='Six words on the ladder, and the longer phrases beside them at the height they mean.',
 alt='A vertical frequency ladder from always at the top through usually, often, sometimes and '
     'hardly ever to never at the bottom, with longer frequency phrases set beside it.',
 top_label='every time', bottom_label='no times',
 steps=[dict(form='always', meaning='100% · every day · and it goes after am, is, are'),
   dict(form='usually', meaning='about 80% · most days'),
   dict(form='often', meaning='about 60% · every week'),
   dict(form='sometimes', meaning='about 40% · twice a month · at the weekend'),
   dict(form='hardly ever', meaning='about 5% · two words, and almost never'),
   dict(form='never', meaning='0% · already negative, so no don\'t with it')]),

"fig_a11_u07_p03_v11": dict(type='V11', height=700,
 title='Two plain verbs with nothing between them',
 alt='Two panels comparing I like play with I like playing, the first showing two bare verbs '
     'side by side with no join.',
 wrong=dict(sentence='I like play football.',
            boundary=0.34, boundary_label='like',
            event=0.58, event_label='play - a second plain verb, unattached',
            why='Two verbs have arrived in a row and nothing is joining them. Like needs a '
                'thing to like, and a plain verb is not a thing: it is an action looking for a '
                'subject. English has to turn it into a thing first, and the tool for that is '
                '-ing.'),
 right=dict(sentence='I like playing football.',
            boundary=0.34, boundary_label='like',
            event=0.60, event_label='playing - now it is a thing',
            why='The -ing turns the action into something you can like, hate, start, finish or '
                'be good at. It behaves exactly like music or football in the sentence: I like '
                'music, I like playing. Same slot, same job.'),
 misconception='In many languages the second verb simply stays in its dictionary form, and that '
               'form is what you learned first. English allows that after can, must and will, '
               'and refuses it after like, love and hate. The difference is not logical; it is '
               'just which word you are standing behind.'),

"fig_a11_u07_p04_v04a": dict(type='V4', height=720,
 title='Two recommendations of the same thing',
 sub='One of them is about the speaker. One of them is about the listener.',
 alt='Two written recommendations of the same free activity set side by side, one listing what '
     'the speaker enjoys and one listing what the listener would get from it.',
 differences=6, prompt='Find the six. Which one got somebody to turn up, and what is the word '
                       'that appears in it and not in the other?',
 left=dict(label='about me', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#C86B2B'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='I love it · I go every week · it is great — 0 came',
        colour='#C86B2B')]),
 right=dict(label='about you', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=160, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='nobody is good · come at ten to · you can leave — 3 came',
        colour='#2E6F5E')])),

"fig_a11_u07_p05_v05": dict(type='V5', height=880,
 title='The poster on the noticeboard',
 sub='Four activities, four lines for names. Read the names, not the activities.',
 alt='A poster for the school Friday club listing four activities with lines for names under '
     'each, showing eleven names on one, three on another, two on a third and none on the fourth, '
     'with a handwritten line at the bottom.',
 rows=[dict(t='org', text='FRIDAY CLUB  -  ROOM 3  -  18.00'),
   dict(t='para', text='One hour. Free. A teacher stays. Put your name on one line.'),
   dict(t='rule'),
   dict(t='grid', cols=['ACTIVITY', 'HOW OFTEN', 'NAMES'],
     data=[['FILM CLUB', 'once a month', '11'],
           ['FOOTBALL', 'every week', '3'],
           ['CONVERSATION HOUR', 'every week', '2'],
           ['BOOK GROUP', 'twice a month', '0']]),
   dict(t='rule'),
   dict(t='head', text='WHAT THE NAMES LOOK LIKE'),
   dict(t='kv', k='Film club', v='11 names, 9 in the same pen', mono=False),
   dict(t='kv', k='Football', v='3 names, all of them already play on Saturday', mono=False),
   dict(t='kv', k='Conversation hour', v='2 names, both of them teachers', mono=False),
   dict(t='kv', k='Book group', v='no line drawn under it at all', mono=False),
   dict(t='rule'),
   dict(t='sign', text='AND AT THE BOTTOM, IN A DIFFERENT PEN:'),
   dict(t='para', text='"or we can just hang out" - no line for names under it, and four ticks '
     'beside it put there by four different people.')],
 callouts=[dict(at=0.20, text='Eleven. More than the other three together'),
   dict(at=0.30, text='Nought. And it is the one the teacher suggested'),
   dict(at=0.52, text='Nine names in one pen means one person signed up nine friends'),
   dict(at=0.66, text='Both the conversation names are staff'),
   dict(at=0.94, text='No line, no name, four ticks. This is the real answer')]),

"fig_a11_u07_p06_v03a": dict(type='V3',
 title='Going swimming, at six frequencies',
 sub='The same activity, six times. What each frequency actually looks like on a calendar.',
 alt='Six panels showing the same activity at six frequencies from every day down to once in a '
     'life, each panel showing the calendar pattern it makes.',
 panels=[
  dict(caption='every day - always', art=[dict(kind='block', x=160, y=0, w=140, bh=110,
     colour='#2E6F5E')]),
  dict(caption='most days - usually', art=[dict(kind='block', x=160, y=0, w=140, bh=86,
     colour='#1F4E5F')]),
  dict(caption='every week - often', art=[dict(kind='block', x=160, y=0, w=140, bh=58,
     colour='#D9A441')]),
  dict(caption='twice a month - sometimes', art=[dict(kind='block', x=160, y=0, w=140,
     bh=34, colour='#C86B2B')]),
  dict(caption='once a year - hardly ever', art=[dict(kind='block', x=160, y=0, w=140,
     bh=14, colour='#A8372E')]),
  dict(caption='not yet - never', art=[dict(kind='gap', x=160, y=10, w=140, bh=60)])]),

"fig_a11_u07_p07_v10": dict(type='V10', kind='stress', height=640,
 title='One sentence, four meanings',
 sub='The same five words. The big circle moves, and the answer changes.',
 alt='Four copies of the same sentence drawn as circles, one large and the rest small, with the '
     'large circle in a different position in each and the question it answers beside it.',
 items=[
  dict(syllables=['I', 'play', 'foot-ball', 'on', 'Sa-tur-day'], strong=[0],
       note='Who plays? - I do, not him'),
  dict(syllables=['I', 'play', 'foot-ball', 'on', 'Sa-tur-day'], strong=[1],
       note='Do you watch? - no, I play'),
  dict(syllables=['I', 'play', 'foot-ball', 'on', 'Sa-tur-day'], strong=[2],
       note='What do you play? - football, not tennis'),
  dict(syllables=['I', 'play', 'foot-ball', 'on', 'Sa-tur-day'], strong=[4],
       note='When? - Saturday, not Sunday')]),

"fig_a11_u07_p09_v02b": dict(type='V2', height=780,
 title='The hours that are both',
 sub='Study in one colour, free time in another, and a third colour for the hours that are '
     'already both.',
 alt='A cutaway of one week showing study hours, free hours, and a much larger third band of '
     'hours that are already spent on English-language material without being counted as study.',
 floors=[dict(was='what you call study', now='about 90 minutes a week, and it feels like three',
     year='', fill='#E8EEF0'),
   dict(was='what you call free time', now='about 20 hours a week', year='', fill='#F3EADA'),
   dict(was='already in English', now='the series · the music · the game · about '
     '7 hours of it', year='', fill='#EFE6DC'),
   dict(was='counted as study', now='none of those seven hours', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Ninety minutes. This is the part people try to grow'),
   dict(at=0.38, text='Twenty hours, and nobody is asking you to give them up'),
   dict(at=0.62, text='Seven hours already happening, in English, for pleasure'),
   dict(at=0.88, text='Change one setting and seven hours change colour')]),

"fig_a11_u07_p09_v03b": dict(type='V3',
 title='One hour of a series, five ways',
 sub='Five panels. Only the second panel costs anything, and it costs four seconds.',
 alt='Five panels following one hour of a series: watched with subtitles in the first language, '
     'with English subtitles, one scene twice, one line said out loud, and that line used four '
     'days later.',
 panels=[
  dict(caption='1 Subtitles in your language',
       art=[dict(kind='block', x=150, y=10, w=140, bh=80, colour='#9AA7AE')]),
  dict(caption='2 Change them to English. 4 seconds',
       art=[dict(kind='block', x=150, y=10, w=140, bh=80, colour='#1F4E5F'),
            dict(kind='arrow', x=150, y=120)]),
  dict(caption='3 One scene, twice',
       art=[dict(kind='arrow', x=150, y=60), dict(kind='arrow', x=150, y=20)]),
  dict(caption='4 Say one line out loud',
       art=[dict(kind='person', x=150, y=0, h=110, skin=3, cloth=2, arm='hold')]),
  dict(caption='5 Four days later, you use it',
       art=[dict(kind='tick', x=150, y=50)])]),

"fig_a11_u07_p10_v12": dict(type='V12',
 title='What the class says, and what the class did',
 sub='Two bands that ought to be the same shape. They are, except in two places.',
 alt='An infographic comparing what a class says it likes doing with what it actually did last '
     'month, alongside what each activity costs and whether it needs other people.',
 span=['nobody', 'everybody'], ticks=4,
 tick_labels=['0', '4', '8', '11'],
 bands=[dict(name='Says they like it', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.72}, label='watching films - 8 of 11', colour='#1F4E5F'),
   dict(**{'from': 0.74, 'to': 1.0}, label='music - 3', colour='#C86B2B')]),
  dict(name='Actually did it', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.90}, label='watching films - 10 of 11', colour='#1F4E5F'),
   dict(**{'from': 0.92, 'to': 1.0}, label='music - 1', colour='#C86B2B')]),
  dict(name='Costs money', type='events', items=[
   dict(at=0.10, label='park: nothing', colour='#2E6F5E'),
   dict(at=0.34, label='football: nothing', colour='#2E6F5E'),
   dict(at=0.60, label='film: a subscription', colour='#D9A441'),
   dict(at=0.86, label='concert: 18 euros', colour='#A8372E')]),
  dict(name='Needs other people', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.34}, label='alone: running, drawing, reading', colour='#8C6A9E'),
   dict(**{'from': 0.36, 'to': 1.0}, label='together: football, dancing, hanging out',
        colour='#2E6F5E')]),
  dict(name='Said vs did', type='line',
   points=[(0, 8), (0.33, 10), (0.66, 3), (1.0, 1)], end_label='1'),
  dict(name='The two gaps', type='flags', items=[
   dict(at=0.08, label='more people watched films than said they liked them'),
   dict(at=0.44, label='three said music and one went to anything')])]),

"fig_a11_u07_p11_v04b": dict(type='V4', height=720,
 title='Room 3 at seven on a Friday',
 sub='The film club on the left, the conversation hour on the right. Same room, same hour.',
 alt='Two drawings of the same classroom on a Friday evening: on the left eleven people with the '
     'lights off and nobody speaking, on the right four people with the lights on, everybody '
     'speaking, and seven empty chairs.',
 differences=6, prompt='Find the six. One of them is not visible at seven at all - it is who is '
                       'still there at eight.',
 left=dict(label='film club', art=[
   dict(kind='block', x=150, y=130, w=250, bh=22, colour='#1F4E5F'),
   dict(kind='block', x=150, y=98, w=250, bh=22, colour='#1F4E5F'),
   dict(kind='gap', x=150, y=66, w=250, bh=22),
   dict(kind='label', x=300, y=210, text='11 here · lights off · 0 speaking · 11 at eight',
        colour='#1F4E5F')]),
 right=dict(label='conversation hour', art=[
   dict(kind='block', x=150, y=130, w=90, bh=22, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=98, w=250, bh=22),
   dict(kind='block', x=150, y=66, w=90, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='4 here · lights on · 4 speaking · 4 at half past eight',
        colour='#2E6F5E')])),
}
