"""A1.1 Unit 8 - What Dona Filipa Actually Does - fifteen figures, as data."""
FIGURES = {
"fig_a11_u08_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='Four workplaces at twenty past eleven',
 sub='Fourteen things to find. In every one of them, somebody is doing something that is not in '
     'their job title.',
 alt='Four workplaces drawn side by side at the same moment - a cafe kitchen, a school office, a '
     'hospital corridor and a small factory - each with somebody doing something outside their '
     'job title.',
 sky='#D4DADC', ground='#A59B8A', ground_line=700,
 buildings=[dict(x=20, w=360, storeys=2, colour='#D8C48C', cutaway=True,
     floor_labels=['the flat above', 'the kitchen - forty coffees by eleven'],
     label='the cafe'),
   dict(x=440, w=340, storeys=3, colour='#C3BBA6', cutaway=True,
     floor_labels=['the corridor', 'the office - and nobody at the desk', 'the entrance'],
     label='the school'),
   dict(x=840, w=360, storeys=2, colour='#BFCBCF', cutaway=True,
     floor_labels=['the ward', 'the corridor - a shift that started at seven'],
     label='the hospital'),
   dict(x=1260, w=320, storeys=2, colour='#B3AE9E', cutaway=True,
     floor_labels=['the roof', 'the floor - one machine, not working'],
     label='the factory')],
 props=[dict(kind='cup', x=300, y=700, s=1.6), dict(kind='table', x=240, y=700, s=1.0),
   dict(kind='chair', x=560, y=700, s=1.0), dict(kind='box', x=680, y=700, s=1.0),
   dict(kind='crate', x=960, y=700, s=1.0),
   dict(kind='bowser', x=1380, y=700, s=1.0),
   dict(kind='sign', x=420, y=700, s=.7, text='11:20')],
 people=[dict(x=180, y=700, h=86, skin=3, cloth=0, hair='cap', arm='hold'),
   dict(x=500, y=700, h=86, skin=1, cloth=2, hair='grey', arm='point'),
   dict(x=620, y=700, h=86, skin=4, cloth=3, hair='bun', arm='hold'),
   dict(x=900, y=700, h=86, skin=2, cloth=4, hair='short', arm='down'),
   dict(x=1320, y=700, h=86, skin=0, cloth=1, hair='short', arm='folded')],
 names=[dict(x=180, t='Marco - a cook, washing up'),
   dict(x=500, t='Dona Filipa - a cleaner, answering the phone'),
   dict(x=620, t='Ana - at a desk she is not sitting at'),
   dict(x=900, t='a nurse - five hours into a twelve-hour shift'),
   dict(x=1320, t='an engineer - no uniform'),
   dict(x=420, t='the clock: twenty past eleven'),
   dict(x=300, t='the fortieth coffee'),
   dict(x=1380, t='the machine that is not working')],
 markers=[dict(x=180, y=582), dict(x=500, y=582), dict(x=620, y=582), dict(x=900, y=582),
   dict(x=1320, y=582), dict(x=420, y=636), dict(x=300, y=650), dict(x=1380, y=640),
   dict(x=240, y=656), dict(x=560, y=664), dict(x=960, y=660), dict(x=680, y=652),
   dict(x=300, y=584), dict(x=1000, y=584)]),

"fig_a11_u08_p01_v08": dict(type='V8', height=800,
 title='One job title, nine things',
 sub='The solid lines are in the contract. The dotted ones are not, and they are longer.',
 alt='A network with the job title cleaner at the centre and nine lines going out to the nine '
     'things the person actually does, four drawn solid for contracted duties and five dotted for '
     'everything else.',
 nodes={
  'job': dict(x=800, y=400, short='C', name='cleaner', sub='the word on the contract', r=62,
              colour='#1C2B33'),
  'f1':  dict(x=360, y=170, short='1', name='open at five', sub='in the contract',
              colour='#1F4E5F'),
  'f2':  dict(x=240, y=430, short='2', name='clean 3 floors', sub='in the contract',
              colour='#1F4E5F'),
  'f3':  dict(x=360, y=670, short='3', name='the bins', sub='in the contract', colour='#1F4E5F'),
  'f4':  dict(x=800, y=720, short='4', name='lock up', sub='in the contract', colour='#1F4E5F'),
  'x1':  dict(x=1240, y=150, short='5', name='the phone', sub='7.00 to 8.30', colour='#C86B2B'),
  'x2':  dict(x=1420, y=380, short='6', name='the chairs in room 3', sub='nobody asked',
              colour='#C86B2B'),
  'x3':  dict(x=1300, y=620, short='7', name='the delivery drivers', sub='every morning',
              colour='#C86B2B'),
  'x4':  dict(x=900, y=140, short='8', name='the radiator', sub='four managers told',
              colour='#A8372E')},
 edges=[dict(a='job', b='f1', label='duty 1', sw=6),
   dict(a='job', b='f2', label='duty 2', sw=6),
   dict(a='job', b='f3', label='duty 3', sw=6),
   dict(a='job', b='f4', label='duty 4', sw=6),
   dict(a='job', b='x1', label='nobody at the desk', sw=3, dash='7 6',
        colour='#C86B2B'),
   dict(a='job', b='x2', label='the next class needs them', sw=3, dash='7 6',
        colour='#C86B2B'),
   dict(a='job', b='x3', label='she is the only one there', sw=3, dash='7 6',
        colour='#C86B2B'),
   dict(a='job', b='x4', label='nothing happened', sw=2, dash='5 6', colour='#A8372E')]),

"fig_a11_u08_p01_v02a": dict(type='V2', height=780,
 title='One working day, in section',
 sub='Eleven tasks. Eleven words. The band in the middle is twice as thick as the others.',
 alt='A cutaway of one working day from the first hour to the last, with the tasks in each band '
     'and the middle band drawn twice as thick.',
 floors=[dict(was='05.00 to 07.00', now='open the building · clean the floor · nobody else here',
     year='', fill='#E8EEF0'),
   dict(was='07.00 to 08.30', now='answer the phone · the delivery drivers · the boxes',
     year='', fill='#F3EADA'),
   dict(was='08.30 to 11.00', now='the three floors · the chairs · the bins · the radiator, again',
     year='', fill='#EFE6DC'),
   dict(was='11.00 to 13.00', now='the second building · and the shift says it ended at eight',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Two hours before anybody can see the work being done'),
   dict(at=0.38, text='None of this hour and a half is in the contract'),
   dict(at=0.62, text='This is the part the word cleaner describes'),
   dict(at=0.88, text='The shift ended. The work did not')]),

"fig_a11_u08_p02_v07": dict(type='V7', height=820,
 title='The corridor, twenty past eleven',
 sub='One of them is writing a job description. The other one is doing the job.',
 alt='A cleaner with a trolley in a corridor and a receptionist with a clipboard, each with two '
     'speech balloons and a thought balloon.',
 bg='#E7E4D8',
 set=[dict(kind='crate', x=740, y=660, s=1.3), dict(kind='box', x=1340, y=660, s=1.1),
   dict(kind='chair', x=1420, y=660, s=1.2)],
 people=[dict(x=520, h=242, skin=1, cloth=0, hair='grey', arm='hold', facing='right',
   label='Dona Filipa', role='the word on the contract is cleaner',
   says=['I\'m answering the phone. Nobody is at the desk.',
         'I clean the office every morning at six.'],
   thinks=['Should I tell her the whole list?']),
  dict(x=1080, h=238, skin=4, cloth=3, hair='bun', arm='point', facing='left',
   label='Ana', role='she is writing the new job description',
   says=['What are you doing at this moment?',
         'And what do you usually do at this hour?'],
   thinks=['Four duties. There is no box for the rest.'])]),

"fig_a11_u08_p03_v09a": dict(type='V9', kind='timeline', height=680,
 title='A wide lens and a narrow one',
 sub='The same verb, twice. What changes is how much of the week you can see.',
 alt='A timeline with a wide lens bracket over the whole week labelled present simple and a '
     'narrow one over this minute labelled present continuous, with the same verb under each.',
 now=0.62,
 bands=[dict(**{'from': 0.04, 'to': 0.96}, type='span', lane=4,
     label='PRESENT SIMPLE - true about the whole week',
     example='She answers the phone. She cleans the office every morning.'),
   dict(**{'from': 0.56, 'to': 0.68}, type='span', lane=1,
     label='PRESENT CONTINUOUS - true about this minute',
     example='She is answering the phone right now.')]),

"fig_a11_u08_p03_v09b": dict(type='V9', kind='mirror', height=660,
 title='The same verb, two widths',
 sub='One of these is true about the week. The other is true about this minute.',
 alt='Two sentence diagrams of the same event. The first spreads across the whole week with a '
     'plain verb; the second is one minute wide and carries is and -ing as extra pieces.',
 labels=['EVERY DAY', 'RIGHT NOW'],
 between='\u2195 same person, same verb, two kinds of truth',
 active=dict(parts=[dict(w=18, role='agent', text='She'),
   dict(w=22, role='action', text='cleans'),
   dict(w=30, role='affected', text='the office'),
   dict(w=28, role='hidden', text='every morning')]),
 passive=dict(parts=[dict(w=16, role='agent', text='She'),
   dict(w=14, role='hidden', text='is'),
   dict(w=26, role='action', text='cleaning'),
   dict(w=30, role='affected', text='the office'),
   dict(w=20, role='hidden', text='now')]),
 rule='The present continuous is two extra pieces on the same verb: a form of be, and -ing. Take '
      'both off and you are back in the present simple. Put both on and the sentence shrinks to '
      'this minute.'),

"fig_a11_u08_p03_v11": dict(type='V11', height=700,
 title='The job name standing bare',
 alt='Two panels comparing She is nurse with She is a nurse, the first showing a job name with '
     'nothing in front of it where English expects one of a group.',
 wrong=dict(sentence='She is nurse.',
            boundary=0.34, boundary_label='is',
            event=0.60, event_label='nurse - with nothing in front of it',
            why='In English a job name is a group you belong to, not a title you hold. Without '
                'the small word in front, the sentence sounds as though nurse were her name, or '
                'a rank like Captain. Many languages need no article here, which is why this '
                'error survives for years.'),
 right=dict(sentence='She is a nurse.',
            boundary=0.34, boundary_label='is',
            event=0.56, event_label='a - one of a large group',
            why='The a says one of many. It is the same a as in a desk and a pen, and it is '
                'required with every job name in the singular: a cook, a driver, a manager, an '
                'engineer. Only in the plural does it go: They are nurses.'),
 misconception='The word feels like a title, and titles in English do go bare - she is Head of '
               'Year, he is Captain. Jobs are not titles. If ten people in the building could '
               'truthfully say it, it needs a or an.'),

"fig_a11_u08_p04_v04a": dict(type='V4', height=720,
 title='The same job, described twice',
 sub='On the left, the contract. On the right, one hour of a Tuesday morning.',
 alt='Two descriptions of the same job side by side, one giving the title and contract hours and '
     'one listing what the person actually did between nine and ten.',
 differences=6, prompt='Find the six. One of the two would let you do the job tomorrow. Which, '
                       'and what is in it that is not in the other?',
 left=dict(label='the contract', art=[
   dict(kind='block', x=150, y=130, w=200, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=150, y=98, w=160, bh=22, colour='#9AA7AE'),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='CLEANER · 05.00-08.00 · four duties',
        colour='#9AA7AE')]),
 right=dict(label='one hour of a Tuesday', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='phone x11 · 2 drivers · chairs in room 3 · the radiator',
        colour='#2E6F5E')])),

"fig_a11_u08_p05_v05": dict(type='V5', height=880,
 title='The job description, in draft',
 sub='Four numbered duties, and one line at the bottom that does all the work.',
 alt='A draft job description showing the title, the hours, the shift pattern, four numbered '
     'duties and a final line reading and other duties as required, with a pencil list begun in '
     'the margin.',
 rows=[dict(t='org', text='ESCOLA MONTE  -  JOB DESCRIPTION  -  DRAFT 2'),
   dict(t='kv', k='Title', v='CLEANER', mono=True),
   dict(t='kv', k='Hours', v='05.00 - 08.00', mono=True),
   dict(t='kv', k='Days', v='Monday to Saturday', mono=True),
   dict(t='kv', k='Hours a week', v='18', mono=True),
   dict(t='rule'),
   dict(t='head', text='DUTIES'),
   dict(t='grid', cols=['NO.', 'DUTY', 'HOW OFTEN'],
     data=[['1', 'OPEN THE BUILDING', 'daily'],
           ['2', 'CLEAN THREE FLOORS', 'daily'],
           ['3', 'EMPTY THE BINS', 'daily'],
           ['4', 'LOCK THE BACK DOOR', 'daily']]),
   dict(t='rule'),
   dict(t='sign', text='AND THE LAST LINE:'),
   dict(t='para', text='"and other duties as required". Five words. They cover answering the '
     'phone for ninety minutes a day, meeting the delivery drivers, putting the chairs back in '
     'room 3, and knowing which radiator does not work.'),
   dict(t='rule'),
   dict(t='para', text='In the margin, in pencil, a second list has been started and the first '
     'two items crossed out.')],
 callouts=[dict(at=0.10, text='Three hours a day on paper'),
   dict(at=0.20, text='Eighteen hours a week. She is in the building for about thirty'),
   dict(at=0.52, text='Four duties, all of them things you can see when they are not done'),
   dict(at=0.76, text='Five words that are doing more work than the four duties above them'),
   dict(at=0.94, text='Somebody started to fix this and stopped after two lines')]),

"fig_a11_u08_p06_v03a": dict(type='V3',
 title='What do you do?',
 sub='One person, six answers, at the same party, one hour later each time.',
 alt='Six panels showing the same person answering the question what do you do, from a one-word '
     'job title to an answer that says what the work actually is.',
 panels=[
  dict(caption='1 "A cleaner."', art=[dict(kind='block', x=160, y=10, w=60, bh=40,
     colour='#9AA7AE')]),
  dict(caption='2 "I\'m a cleaner."', art=[dict(kind='block', x=160, y=10, w=90, bh=46,
     colour='#1F4E5F')]),
  dict(caption='3 "I work in a school."', art=[dict(kind='block', x=160, y=10, w=120,
     bh=52, colour='#1F4E5F')]),
  dict(caption='4 "I start at five."', art=[dict(kind='doc', x=160, y=0)]),
  dict(caption='5 "I open the building."',
       art=[dict(kind='person', x=160, y=0, h=110, skin=1, cloth=0)]),
  dict(caption='6 "I am the first person there."',
       art=[dict(kind='person', x=160, y=0, h=110, skin=1, cloth=0, arm='point'),
            dict(kind='tick', x=160, y=128)])]),

"fig_a11_u08_p07_v10": dict(type='V10', kind='elision', height=640,
 title='The words that shrink',
 sub='Written at full length above, said at half length below. The shaded letters are not heard.',
 alt='Four phrases written out in full and then as they are actually said, with the dropped '
     'sounds shaded.',
 pairs=[
  dict(written='I am working', spoken='Imworking', dropped='a',
       note='two words, one beat'),
  dict(written='she is working', spoken='sheezworking', dropped='i',
       note='is becomes a z on the end of she'),
  dict(written='they are working', spoken='thairworking', dropped='ae',
       note='are disappears into one r'),
  dict(written='what are you doing', spoken='whatchadooin', dropped='areyu',
       note='four words, two beats, no g at the end')]),

"fig_a11_u08_p09_v02b": dict(type='V2', height=780,
 title='The week that gets counted, and the week that does not',
 sub='The lesson is the thin band. Everything thicker than it is invisible to everybody.',
 alt='A cutaway of a learner\'s week with the lesson drawn as a thin band near the top and '
     'thicker bands beneath it for reading, listening, thinking and rehearsing.',
 floors=[dict(was='the lesson', now='90 minutes - and it is the only part anybody records',
     year='', fill='#E8EEF0'),
   dict(was='the homework', now='40 minutes, and it feels like the real work', year='',
     fill='#F3EADA'),
   dict(was='reading and listening', now='about 4 hours, most of it not called study', year='',
     fill='#EFE6DC'),
   dict(was='rehearsing in your head', now='uncounted, unlimited, and free', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Ninety minutes a week. This is what people mean by learning'),
   dict(at=0.38, text='The part that gets marked'),
   dict(at=0.62, text='Four hours, and it is already happening'),
   dict(at=0.88, text='The only one of the four that makes speaking faster')]),

"fig_a11_u08_p09_v03b": dict(type='V3',
 title='One sentence, five stages',
 sub='Five panels. The third one is the one everybody wants to skip.',
 alt='Five panels on a single sentence: deciding to say it, building it silently, saying it '
     'badly, being understood anyway, and saying it correctly four days later.',
 panels=[
  dict(caption='1 You decide to say it',
       art=[dict(kind='person', x=150, y=0, h=112, skin=2, cloth=4)]),
  dict(caption='2 You build it in your head',
       art=[dict(kind='block', x=150, y=10, w=110, bh=80, colour='#9AA7AE')]),
  dict(caption='3 You say it badly',
       art=[dict(kind='cross', x=150, y=50)]),
  dict(caption='4 And you are understood',
       art=[dict(kind='tick', x=150, y=50)]),
  dict(caption='5 Four days later, no building',
       art=[dict(kind='person', x=150, y=0, h=112, skin=2, cloth=4, arm='hold'),
            dict(kind='arrow', x=150, y=130)])]),

"fig_a11_u08_p10_v12": dict(type='V12',
 title='One Saturday at the cafe',
 sub='The busiest two hours are not the two hours with the most money in them.',
 alt='An infographic of one Saturday at the cafe showing customers, coffees made, money taken and '
     'how many people were working, hour by hour from eight to four.',
 span=['08.00', '16.00'], ticks=5,
 tick_labels=['08.00', '10.00', '12.00', '14.00', '16.00'],
 bands=[dict(name='Customers', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.18}, label='quiet - 9 people', colour='#9AA7AE'),
   dict(**{'from': 0.20, 'to': 0.44}, label='busy - 61 people', colour='#C86B2B'),
   dict(**{'from': 0.46, 'to': 0.64}, label='the peak - 78 people', colour='#A8372E'),
   dict(**{'from': 0.66, 'to': 1.0}, label='afternoon - 44 people', colour='#2E6F5E')]),
  dict(name='Money taken', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.18}, label='41 EUR', colour='#9AA7AE'),
   dict(**{'from': 0.20, 'to': 0.44}, label='118 EUR - coffee only', colour='#C86B2B'),
   dict(**{'from': 0.46, 'to': 0.64}, label='96 EUR - coffee only, and queues',
        colour='#A8372E'),
   dict(**{'from': 0.66, 'to': 1.0}, label='204 EUR - people eat in the afternoon',
        colour='#2E6F5E')]),
  dict(name='People working', type='events', items=[
   dict(at=0.06, label='Marco alone', colour='#1F4E5F'),
   dict(at=0.36, label='Marco alone, and running', colour='#A8372E'),
   dict(at=0.56, label='Marco alone, and three people leave the queue', colour='#A8372E'),
   dict(at=0.80, label='Marco alone, hour seven', colour='#A8372E')]),
  dict(name='Minutes a customer waited', type='line',
   points=[(0, 1), (0.3, 4), (0.55, 9), (0.8, 6), (1.0, 3)], end_label='3 min'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.12, label='the loudest hours are not the richest ones'),
   dict(at=0.50, label='the afternoon makes the most money and is the first thing he would cut')])]),

"fig_a11_u08_p11_v04b": dict(type='V4', height=720,
 title='The counter at half past two',
 sub='One person eight hours in, and the second of two people two hours in.',
 alt='Two drawings of the same cafe counter at half past two, one with a single worker eight '
     'hours into a shift and three customers waiting, the other with the second of two workers '
     'two hours in and nobody waiting.',
 differences=6, prompt='Find the six. One of them is on the floor behind the counter, and it is '
                       'the one that costs money later.',
 left=dict(label='one person, hour eight', art=[
   dict(kind='block', x=150, y=130, w=250, bh=22, colour='#A8372E'),
   dict(kind='block', x=150, y=98, w=180, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=66, w=250, bh=22),
   dict(kind='label', x=300, y=210, text='2 served · 3 waiting · 9 min wait · a dropped cup',
        colour='#A8372E')]),
 right=dict(label='two people, hour two', art=[
   dict(kind='block', x=150, y=130, w=250, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=250, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=120, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='2 served · 0 waiting · 1 min wait · a clean floor',
        colour='#2E6F5E')])),
}
