"""A1.1 Unit 9 - Five Minutes from the Metro - fifteen figures, as data."""
FIGURES = {
"fig_a11_u09_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The square at the bottom of the hill, half past eight',
 sub='Fourteen things to find. There are four ways out of this square and three of them look '
     'the same.',
 alt='A city square early in the morning with a metro entrance, a tram stop, a bus stop, a '
     'pharmacy on the corner, a church and a steep street going up out of the picture, with one '
     'person standing in the middle turning round with a phone.',
 sky='#CBD8DE', ground='#A6A092', ground_line=700,
 buildings=[dict(x=20, w=380, storeys=3, colour='#C4B9A2',
     label='the church - on the corner, and the first landmark'),
   dict(x=460, w=300, storeys=2, colour='#BDC8C9',
     label='the pharmacy - the second landmark'),
   dict(x=820, w=300, storeys=4, colour='#C9C0AC',
     label='the hotel - and the bank next to it'),
   dict(x=1180, w=400, storeys=3, colour='#B9B0A0',
     label='the street going up - out of the picture')],
 props=[dict(kind='sign', x=440, y=700, s=.7, text='METRO'),
   dict(kind='sign', x=800, y=700, s=.7, text='8:30'),
   dict(kind='sign', x=1140, y=700, s=.7, text='BUS'),
   dict(kind='hoarding', x=1240, y=700, s=.8, w=160),
   dict(kind='van', x=160, y=700, s=.8),
   dict(kind='tree', x=760, y=700, s=1.0),
   dict(kind='crate', x=1480, y=700, s=1.0),
   dict(kind='box', x=620, y=700, s=1.0)],
 people=[dict(x=700, y=700, h=88, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=500, y=700, h=86, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=960, y=700, h=86, skin=4, cloth=3, hair='cap', arm='down'),
   dict(x=1080, y=700, h=86, skin=3, cloth=2, hair='bun', arm='folded'),
   dict(x=1340, y=700, h=86, skin=0, cloth=1, hair='short', arm='hold')],
 names=[dict(x=700, t='one person, turning round, with a phone'),
   dict(x=500, t='the man at the pharmacy door'),
   dict(x=960, t='two people waiting for the tram'),
   dict(x=1080, t='and neither of them is going up the hill'),
   dict(x=1340, t='somebody who knows the way, walking fast'),
   dict(x=440, t='the metro entrance - four minutes underground'),
   dict(x=1140, t='the bus stop - on the wrong side of the square'),
   dict(x=800, t='the clock: half past eight')],
 markers=[dict(x=700, y=578), dict(x=500, y=580), dict(x=960, y=580), dict(x=1080, y=580),
   dict(x=1340, y=580), dict(x=440, y=636), dict(x=1140, y=636), dict(x=800, y=636),
   dict(x=160, y=646), dict(x=620, y=652), dict(x=1480, y=660), dict(x=1240, y=650),
   dict(x=200, y=584), dict(x=1300, y=584)]),

"fig_a11_u09_p01_v08": dict(type='V8', height=780,
 title='Four ways out of one square',
 sub='Every line has a time and a cost on it. Two of them take the same time and only one is flat.',
 alt='The square drawn as a network with the metro, the tram stop, the bus stop and four streets, '
     'with lines labelled by how long each route takes and what it costs.',
 nodes={
  'sq':  dict(x=800, y=400, short='●', name='the square', sub='four ways out', r=60,
              colour='#1C2B33'),
  'met': dict(x=330, y=200, short='M', name='the metro', sub='4 min, underground',
              colour='#1F4E5F'),
  'tra': dict(x=280, y=560, short='T', name='the tram', sub='11 min, you can see',
              colour='#2E6F5E'),
  'bus': dict(x=760, y=700, short='B', name='the bus', sub='9 min, wrong side',
              colour='#D9A441'),
  'tax': dict(x=1300, y=200, short='X', name='the taxi', sub='6 min, 7 EUR', colour='#8C6A9E'),
  'foo': dict(x=1300, y=580, short='F', name='on foot', sub='22 min, always', colour='#C86B2B'),
  'sch': dict(x=1420, y=390, short='▲', name='the school', sub='400 m, and up', r=52,
              colour='#A8372E')},
 edges=[dict(a='met', b='sq', label='4 min · 1.65 EUR', sw=6),
   dict(a='tra', b='sq', label='11 min · 1.65 EUR', sw=5),
   dict(a='bus', b='sq', label='9 min · and then cross', sw=4),
   dict(a='tax', b='sq', label='6 min · cannot go up', sw=4),
   dict(a='foo', b='sq', label='22 min · free', sw=5),
   dict(a='sq', b='sch', label='10 min up this hill', sw=7,
        colour='#A8372E')]),

"fig_a11_u09_p01_v02a": dict(type='V2', height=780,
 title='The hill, in section',
 sub='Eleven places. Eleven words. The gradient is the whole problem and you can see it here.',
 alt='A cutaway of the hill from the square at the bottom to the school at the top, showing what '
     'is on each level, with empty labels.',
 floors=[dict(was='the top - 42 m up', now='the school · the yellow building · the bell',
     year='', fill='#F1EDE2'),
   dict(was='two thirds up', now='three streets on the left · ignore all three', year='',
     fill='#EFE6DC'),
   dict(was='one third up', now='the bank · the hotel · the traffic lights', year='',
     fill='#E8EEF0'),
   dict(was='the square - 0 m', now='the metro · the tram · the bus stop · the church · the pharmacy',
     year='', fill='#F3EADA')],
 callouts=[dict(at=0.12, text='Four hundred metres from the square, and forty-two metres above it'),
   dict(at=0.38, text='Three streets, and all three of them look like the right one'),
   dict(at=0.62, text='The only turn in the whole route is here'),
   dict(at=0.88, text='Everybody who telephones is standing on this line')]),

"fig_a11_u09_p02_v07": dict(type='V7', height=820,
 title='In the square, twenty to nine',
 sub='She has the address. He has the directions. Neither has what the other needs.',
 alt='A new student in a square holding a phone and a man standing at a pharmacy door, each with '
     'two speech balloons and a thought balloon.',
 bg='#E4E9EA',
 set=[dict(kind='box', x=740, y=660, s=1.1), dict(kind='tree', x=1420, y=660, s=1.2),
   dict(kind='crate', x=1300, y=660, s=1.0)],
 people=[dict(x=520, h=240, skin=2, cloth=4, hair='long', arm='hold', facing='right',
   label='a new student', role='first lesson, nine o\'clock',
   says=['Excuse me. Where is Escola Monte?', 'I have the address. Rua do Monte, 14.'],
   thinks=['I have been here for twenty minutes.']),
  dict(x=1080, h=240, skin=1, cloth=0, hair='grey', arm='point', facing='left',
   label='the man at the pharmacy', role='he has lived here all his life',
   says=['Go straight on. Turn left at the traffic lights.',
         'It\'s opposite the church. About ten minutes.'],
   thinks=['Do I say three streets, or is that too much?'])]),

"fig_a11_u09_p03_v09a": dict(type='V9', kind='scope', height=680,
 title='Words that sit still, and words that move',
 sub='Place words put a dot on the map. Movement words draw a line across it.',
 alt='A sentence drawn as words with brackets marking the place prepositions as still and the '
     'movement prepositions as arrows.',
 words=['The school', 'is', 'opposite', 'the church', '—', 'Go', 'up', 'the hill'],
 focus=[2, 6],
 brackets=[dict(**{'from': 1, 'to': 3}, lane=0, colour='#1F4E5F',
     label='STILL: next to · opposite · behind · between · in front of · on the corner'),
   dict(**{'from': 5, 'to': 7}, lane=0, colour='#C86B2B',
     label='MOVING: up · down · along · across · into · out of · past'),
   dict(**{'from': 5, 'to': 5}, lane=1, colour='#2E6F5E',
     label='And the instruction has no subject at all. Go, turn, take, walk - the plain verb, '
           'with don\'t in front of it for the negative.')]),

"fig_a11_u09_p03_v09b": dict(type='V9', kind='weight', height=520,
 title='at, on and in - three sizes of container',
 sub='The same three words you use for places, reused for time, and the shapes match.',
 alt='Three boxes of increasing width labelled at, on and in, each holding the kind of time it '
     'goes with: a point, a named day and a long stretch.',
 parts=[dict(w=14, role='a point', text='AT', colour='#A8372E'),
   dict(w=22, role='six o\'clock · night · the weekend', text='•', colour='#A8372E'),
   dict(w=14, role='a named day', text='ON', colour='#C86B2B'),
   dict(w=22, role='Monday · the first of May', text='▬', colour='#C86B2B'),
   dict(w=14, role='a long stretch', text='IN', colour='#1F4E5F'),
   dict(w=30, role='the morning · May · 2026', text='━━━', colour='#1F4E5F')],
 note='Small to large, left to right. The two that break the pattern are at night and at the '
      'weekend, and they are worth learning as single words.'),

"fig_a11_u09_p03_v11": dict(type='V11', height=700,
 title='The bracket with nothing to close on',
 alt='Two panels comparing between the pharmacy with between the pharmacy and the bank, the '
     'first showing a bracket open on one side only.',
 wrong=dict(sentence='The bank is between the pharmacy.',
            boundary=0.40, boundary_label='between',
            event=0.70, event_label='one thing - and the bracket cannot close',
            why='Between needs two sides. With one noun after it the listener waits for the '
                'second and the sentence never finishes. It is the only preposition in this '
                'unit that takes two objects, and the word that joins them is and, never with '
                'or or.'),
 right=dict(sentence='The bank is between the pharmacy and the hotel.',
            boundary=0.34, boundary_label='between',
            event=0.66, event_label='two things, joined by and',
            why='Now the bracket closes. Both sides are named and the listener can place the '
                'bank exactly. If you only know one side, use next to or opposite instead - '
                'they take one object and they are just as precise.'),
 misconception='Learners reach for between because it feels like the strongest place word. It '
               'is, but only when you can name both sides. Half a between is less useful than a '
               'whole next to.'),

"fig_a11_u09_p04_v04a": dict(type='V4', height=720,
 title='The same route, written twice',
 sub='Landmarks on the left. Metres on the right. Both of them are accurate.',
 alt='Two sets of written directions for the same route, one naming a landmark at every turn and '
     'one giving distances in metres.',
 differences=6, prompt='Find the six. Nine out of ten people followed one of these successfully. '
                       'Which, and why is accuracy not the reason?',
 left=dict(label='landmarks', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=180, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='church · pharmacy · traffic lights · yellow building — 9 of 10',
        colour='#2E6F5E')]),
 right=dict(label='metres', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210,
        text='120 m · turn · 240 m · turn · 40 m — 3 of 10',
        colour='#C86B2B')])),

"fig_a11_u09_p05_v05": dict(type='V5', height=840,
 title='The How to find us page',
 sub='Everything on it is true. The biggest thing on the page is a telephone number.',
 alt='The school website page printed out, showing the address, one line about the metro, one '
     'about the bus, a small map with no street names, and a telephone number in bold at the '
     'bottom.',
 rows=[dict(t='org', text='ESCOLA MONTE  -  HOW TO FIND US'),
   dict(t='kv', k='Address', v='Rua do Monte 14, 1200 Lisboa', mono=True),
   dict(t='rule'),
   dict(t='head', text='GETTING HERE'),
   dict(t='kv', k='Metro', v='5 minutes from Alto', mono=False),
   dict(t='kv', k='Bus', v='3 minutes from the square', mono=False),
   dict(t='kv', k='Tram', v='not mentioned', mono=False),
   dict(t='kv', k='Parking', v='not mentioned', mono=False),
   dict(t='rule'),
   dict(t='head', text='THE MAP ON THE PAGE'),
   dict(t='kv', k='Street names', v='none', mono=False),
   dict(t='kv', k='Landmarks', v='none', mono=False),
   dict(t='kv', k='The hill', v='not shown - the map is flat', mono=False),
   dict(t='kv', k='Size', v='4 cm wide', mono=False),
   dict(t='rule'),
   dict(t='sign', text='AND AT THE BOTTOM, IN BOLD, 18 POINT:'),
   dict(t='para', text='"Lost? Telephone 21 333 4455." It is the largest thing on the page. '
     'Somebody knew about the problem and solved it with a telephone number instead of with '
     'two more sentences of directions.')],
 callouts=[dict(at=0.10, text='True. Four hundred metres, and five minutes on flat ground'),
   dict(at=0.30, text='Three minutes from the square - and the square is the problem'),
   dict(at=0.56, text='A map with no names on it is a picture, not a map'),
   dict(at=0.70, text='The one fact that matters most is the one the map cannot show'),
   dict(at=0.94, text='The biggest thing on the page is an admission')]),

"fig_a11_u09_p06_v03a": dict(type='V3',
 title='Six decisions between the square and the door',
 sub='In four of the six, the obvious choice is the wrong one.',
 alt='Six panels showing one journey from the square to the school, each panel at the moment a '
     'decision has to be made.',
 panels=[
  dict(caption='1 Out of the metro - which way?',
       art=[dict(kind='person', x=160, y=0, h=112, skin=2, cloth=4)]),
  dict(caption='2 The church: go past it, not round it',
       art=[dict(kind='block', x=160, y=0, w=80, bh=110, colour='#C4B9A2')]),
  dict(caption='3 The traffic lights: turn LEFT',
       art=[dict(kind='arrow', x=160, y=60)]),
  dict(caption='4 Three streets on the left: all wrong',
       art=[dict(kind='cross', x=160, y=50)]),
  dict(caption='5 The hill: keep going, 4 minutes',
       art=[dict(kind='block', x=160, y=0, w=120, bh=70, colour='#A99E8C')]),
  dict(caption='6 The yellow building: ring the bell',
       art=[dict(kind='tick', x=160, y=50)])]),

"fig_a11_u09_p07_v10": dict(type='V10', kind='stress', height=820,
 title='Two words, one stress',
 sub='In a compound the first word is louder. In an ordinary phrase it is the second.',
 alt='Six compound words and three ordinary phrases drawn as pairs of circles, with the large '
     'circle on the first word in the compounds and on the second in the phrases.',
 items=[
  dict(syllables=['BUS', 'stop'], strong=[0], note='a compound - one thing, with a name'),
  dict(syllables=['TRAF-fic', 'lights'], strong=[0], note='a compound'),
  dict(syllables=['POST', 'of-fice'], strong=[0], note='a compound'),
  dict(syllables=['a big', 'STREET'], strong=[1], note='an ordinary phrase - adjective + noun'),
  dict(syllables=['the next', 'COR-ner'], strong=[1], note='an ordinary phrase'),
  dict(syllables=['a', 'GREEN-house'], strong=[1], note='a building for plants'),
  dict(syllables=['a green', 'HOUSE'], strong=[1], note='a house that is green')]),

"fig_a11_u09_p09_v02b": dict(type='V2', height=780,
 title='The course is the same hill',
 sub='Four false turnings off the route, and all four of them feel like progress.',
 alt='A cutaway of a language course drawn as the same hill, with the square at the bottom and '
     'the school at the top, and four false turnings labelled with what learners mistake for '
     'progress.',
 floors=[dict(was='the top', now='you say what you mean, and you stop noticing that you did',
     year='', fill='#F1EDE2'),
   dict(was='the long middle', now='weeks 7 to 20 · the same effort, and no feeling of moving',
     year='', fill='#EFE6DC'),
   dict(was='the four turnings', now='more words · more grammar · another app · more hours',
     year='', fill='#E8EEF0'),
   dict(was='the flat part', now='the first six weeks · everything is new and everything sticks',
     year='', fill='#F3EADA')],
 callouts=[dict(at=0.12, text='Nobody arrives here by changing method four times'),
   dict(at=0.38, text='This is the hill. It is not a wrong turning'),
   dict(at=0.62, text='All four feel like doing something. All four leave the route'),
   dict(at=0.88, text='Six weeks of fast progress, and then it is supposed to slow down')]),

"fig_a11_u09_p09_v03b": dict(type='V3',
 title='Twelve weeks, five panels',
 sub='The fourth panel is a decision. The fifth is what happens if you do not make it.',
 alt='Five panels following a learner through the first fast month, the flat month, the decision '
     'to change method, and the same learner twelve weeks later.',
 panels=[
  dict(caption='1 Week 1 - everything is new',
       art=[dict(kind='block', x=150, y=0, w=110, bh=30, colour='#2E6F5E')]),
  dict(caption='2 Week 6 - visible progress',
       art=[dict(kind='block', x=150, y=0, w=110, bh=70, colour='#2E6F5E')]),
  dict(caption='3 Week 12 - the same effort, no change',
       art=[dict(kind='block', x=150, y=0, w=110, bh=76, colour='#D9A441')]),
  dict(caption='4 "This method is not working"',
       art=[dict(kind='person', x=150, y=0, h=110, skin=4, cloth=3)]),
  dict(caption='5 Week 24 - if you changed nothing',
       art=[dict(kind='block', x=150, y=0, w=110, bh=120, colour='#1F4E5F'),
            dict(kind='tick', x=150, y=130)])]),

"fig_a11_u09_p10_v12": dict(type='V12',
 title='Four ways out of the square, as data',
 sub='The route most people take is the worst on three of the four measures.',
 alt='An infographic of the four routes out of the square showing how many people take each, how '
     'long it takes, how many get lost and what each one costs.',
 span=['0', 'all'], ticks=4,
 tick_labels=['nobody', 'a few', 'most', 'everybody'],
 bands=[dict(name='Who takes it', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.62}, label='metro - 62%', colour='#1F4E5F'),
   dict(**{'from': 0.64, 'to': 0.80}, label='bus - 16%', colour='#D9A441'),
   dict(**{'from': 0.82, 'to': 0.92}, label='tram - 11%', colour='#2E6F5E'),
   dict(**{'from': 0.94, 'to': 1.0}, label='foot - 6%', colour='#C86B2B')]),
  dict(name='Minutes', type='events', items=[
   dict(at=0.08, label='metro: 4 + 10 uphill', colour='#1F4E5F'),
   dict(at=0.36, label='bus: 9 + cross the square', colour='#D9A441'),
   dict(at=0.62, label='tram: 11, and you can see where you are', colour='#2E6F5E'),
   dict(at=0.88, label='foot: 22, always 22', colour='#C86B2B')]),
  dict(name='Got lost', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.52}, label='metro - 1 in 4 of all new students',
        colour='#A8372E'),
   dict(**{'from': 0.54, 'to': 0.70}, label='bus - 1 in 9', colour='#D9A441'),
   dict(**{'from': 0.72, 'to': 0.80}, label='tram - almost nobody', colour='#2E6F5E'),
   dict(**{'from': 0.82, 'to': 1.0}, label='foot - nobody', colour='#2E6F5E')]),
  dict(name='Cost in euros', type='line',
   points=[(0, 1.65), (0.33, 1.65), (0.66, 0), (1.0, 7)], end_label='7.00'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.10, label='the route most people take is the one you cannot see out of'),
   dict(at=0.50, label='the tram takes longest and loses nobody')])]),

"fig_a11_u09_p11_v04b": dict(type='V4', height=720,
 title='The square at ten to nine in September',
 sub='The same nine people, drawn twice. One pole is different.',
 alt='Two drawings of the same square at ten to nine in September. On the left, nine people '
     'standing apart looking at phones. On the right, the same nine walking in one direction with '
     'a sign visible on a pole.',
 differences=6, prompt='Find the six. One of them is a clock, and it tells you what the sign '
                       'was actually worth.',
 left=dict(label='no sign', art=[
   dict(kind='block', x=150, y=130, w=70, bh=22, colour='#A8372E'),
   dict(kind='block', x=150, y=98, w=70, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='9 standing · 9 phones · 4 directions · 08.50',
        colour='#A8372E')]),
 right=dict(label='one sign', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=120, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='9 walking · 1 direction · 1 pole · 08.50',
        colour='#2E6F5E')])),
}
