"""A1.1 Unit 10 - Thirty-Nine Euros - fifteen figures, as data."""
FIGURES = {
"fig_a11_u10_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The shopping street, first of December, ten past five',
 sub='Fourteen things to find. Three of the four sale signs give the old price. One does not.',
 alt='A shopping street at dusk on the first of December with sale signs in four windows, a queue '
     'at a till, somebody holding a jacket up against themselves in a doorway, and somebody '
     'walking back towards a shop carrying a bag.',
 sky='#56626B', ground='#8E8678', ground_line=700,
 buildings=[dict(x=20, w=380, storeys=3, colour='#D9C98E', cutaway=True,
     floor_labels=['the office above', 'the stockroom - the boxes', '89 to 39'],
     label='the first shop - and the only one with a queue'),
   dict(x=460, w=300, storeys=2, colour='#C6B9A0',
     label='SALE - 60 to 30, both prices shown'),
   dict(x=820, w=300, storeys=3, colour='#BDC5C4',
     label='SALE - 45 to 25, both prices shown'),
   dict(x=1180, w=400, storeys=2, colour='#C9BFAC',
     label='SALE - 20, and no old price anywhere')],
 props=[dict(kind='sign', x=200, y=700, s=.7, text='SALE'),
   dict(kind='sign', x=1340, y=700, s=.7, text='SALE'),
   dict(kind='sign', x=620, y=700, s=.7, text='5:10'),
   dict(kind='box', x=900, y=700, s=1.0),
   dict(kind='crate', x=1020, y=700, s=1.0),
   dict(kind='van', x=1440, y=700, s=.8),
   dict(kind='table', x=520, y=700, s=1.1),
   dict(kind='chair', x=480, y=700, s=1.0)],
 people=[dict(x=280, y=700, h=86, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=340, y=700, h=86, skin=4, cloth=3, hair='bun', arm='down'),
   dict(x=700, y=700, h=86, skin=1, cloth=0, hair='cap', arm='hold'),
   dict(x=960, y=700, h=86, skin=3, cloth=2, hair='short', arm='point'),
   dict(x=1260, y=700, h=86, skin=0, cloth=1, hair='grey', arm='folded')],
 names=[dict(x=280, t='Lin - holding the jacket against herself'),
   dict(x=340, t='the queue at the till - nine people'),
   dict(x=700, t='somebody walking back with a bag'),
   dict(x=960, t='a shop assistant, outside, on a break'),
   dict(x=1260, t='the shop with one price and the most customers'),
   dict(x=200, t='SALE - and it does not say 89'),
   dict(x=1340, t='SALE - and it does not say anything else'),
   dict(x=620, t='the clock: ten past five')],
 markers=[dict(x=280, y=582), dict(x=340, y=582), dict(x=700, y=582), dict(x=960, y=582),
   dict(x=1260, y=582), dict(x=200, y=636), dict(x=1340, y=636), dict(x=620, y=636),
   dict(x=900, y=652), dict(x=1020, y=660), dict(x=1440, y=646), dict(x=520, y=656),
   dict(x=200, y=584), dict(x=200, y=468)]),

"fig_a11_u10_p01_v08": dict(type='V8', height=780,
 title='One jacket, five numbers',
 sub='Four of the five are known. The fifth is the only one that decides anything.',
 alt='A jacket at the centre joined by labelled lines to five numbers: what it cost to make, what '
     'the shop paid, the first price, the sale price and what it is worth to the wearer.',
 nodes={
  'jac': dict(x=800, y=400, short='J', name='one jacket', sub='the same object throughout', r=62,
              colour='#1C2B33'),
  'mak': dict(x=330, y=200, short='4', name='4 EUR', sub='to make it', colour='#9AA7AE'),
  'sho': dict(x=280, y=580, short='22', name='22 EUR', sub='what the shop paid',
              colour='#1F4E5F'),
  'p1':  dict(x=800, y=140, short='89', name='89 EUR', sub='September to November',
              colour='#A8372E'),
  'p2':  dict(x=1280, y=230, short='39', name='39 EUR', sub='1 December', colour='#C86B2B'),
  'p3':  dict(x=1300, y=600, short='19', name='19 EUR', sub='6 January', colour='#D9A441'),
  'wor': dict(x=820, y=700, short='?', name='worth to you', sub='nobody knows this one', r=52,
              colour='#2E6F5E')},
 edges=[dict(a='mak', b='sho', label='18 EUR, somewhere between', sw=3, dash='6 5'),
   dict(a='sho', b='jac', label='what it costs the shop to own it', sw=6),
   dict(a='jac', b='p1', label='11 people tried it on. Nobody bought it', sw=5),
   dict(a='jac', b='p2', label='sold in 4 minutes, untried', sw=6, colour='#C86B2B'),
   dict(a='jac', b='p3', label='3 left, sold in 2 days', sw=5, colour='#D9A441'),
   dict(a='jac', b='wor', label='and this is the only price that is yours', sw=4,
        colour='#2E6F5E')]),

"fig_a11_u10_p01_v02a": dict(type='V2', height=780,
 title='One shop, in section',
 sub='Eleven things. Eleven words. The most expensive thing is at the front and the cheapest is '
     'at the back.',
 alt='A cutaway of a clothes shop from the window at the front through the rails and the till to '
     'the stockroom at the back, with empty labels.',
 floors=[dict(was='the window', now='the jacket · the price · the word SALE', year='',
     fill='#F3EADA'),
   dict(was='the rails', now='shirt · shoes · size · colour · and the label on everything',
     year='', fill='#E8EEF0'),
   dict(was='the till', now='money · cash · card · change · receipt', year='',
     fill='#EFE6DC'),
   dict(was='the stockroom', now='the boxes · and what nobody tried on in November', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The sign is the cheapest thing here and it does the most work'),
   dict(at=0.38, text='Everything on a rail has four numbers attached to it'),
   dict(at=0.62, text='Where the only piece of paper in the story is printed'),
   dict(at=0.88, text='Nothing back here has been looked at by a customer')]),

"fig_a11_u10_p02_v07": dict(type='V7', height=820,
 title='The counter, second of December',
 sub='She has the jacket and the receipt. The assistant has a rule from Monday.',
 alt='A customer at a shop counter holding a jacket and a receipt, and a shop assistant behind '
     'the till, each with two speech balloons and a thought balloon.',
 bg='#E9E2D4',
 set=[dict(kind='table', x=760, y=660, s=1.9), dict(kind='box', x=1340, y=660, s=1.1),
   dict(kind='crate', x=1440, y=660, s=1.0)],
 people=[dict(x=520, h=240, skin=2, cloth=4, hair='long', arm='hold', facing='right',
   label='Lin', role='she bought it yesterday',
   says=['I bought it yesterday. It was thirty-nine euros.',
         'I tried it on at home. It\'s too small.'],
   thinks=['Do I argue, or is this forty minutes?']),
  dict(x=1080, h=238, skin=3, cloth=2, hair='bun', arm='point', facing='left',
   label='the assistant', role='she was told this on Monday',
   says=['They were all half price. It\'s a sale item.',
         'I can give you a credit note. Not cash.'],
   thinks=['It says so at the bottom. Nobody reads it.'])]),

"fig_a11_u10_p03_v09a": dict(type='V9', kind='timeline', height=700,
 title='The box behind now',
 sub='Everything inside the box wears -ed. Am, is and are become two words only.',
 alt='A timeline with a wide band for the present and a closed box behind it for the past, '
     'labelled yesterday, with the past forms inside it.',
 now=0.74,
 bands=[dict(**{'from': 0.06, 'to': 0.62}, type='before', lane=4,
     label='THE PAST - closed, finished, and it has an edge',
     example='I tried · she asked · they wanted · it WAS · they WERE'),
   dict(**{'from': 0.66, 'to': 0.96}, type='span', lane=1,
     label='NOW - the tenses you already have',
     example='I try · she asks · it is · they are · she is trying')]),

"fig_a11_u10_p03_v09b": dict(type='V9', kind='ladder', height=760,
 title='Three odd ones, then a rule',
 sub='First, second and third have to be learned. Everything after them is the same ending.',
 alt='A vertical ladder of ordinal numbers showing first, second and third as irregular forms and '
     'fourth onwards following one pattern.',
 top_label='learn these', bottom_label='then it is a rule',
 steps=[dict(form='first', meaning='1st · nothing like one'),
   dict(form='second', meaning='2nd · nothing like two'),
   dict(form='third', meaning='3rd · almost like three, and not quite'),
   dict(form='fourth', meaning='4th · and from here it is just + th'),
   dict(form='fifth', meaning='5th · the v turns into an f'),
   dict(form='tenth', meaning='10th · ten + th'),
   dict(form='twentieth', meaning='20th · the y turns into ie, then + th')]),

"fig_a11_u10_p03_v11": dict(type='V11', height=700,
 title='The past, marked twice',
 alt='Two panels comparing Did you tried with Did you try, the first showing the past marked on '
     'both did and the verb.',
 wrong=dict(sentence='Did you tried it on?',
            boundary=0.30, boundary_label='Did - already past',
            event=0.62, event_label='tried - past again',
            why='Did is the past of do, and it has already told the listener when this happened. '
                'The -ed on the verb says it a second time, and English pays for it once. This '
                'is the same rule you met in Unit 3 with does and the s - the helper takes the '
                'ending and the verb goes bare.'),
 right=dict(sentence='Did you try it on?',
            boundary=0.30, boundary_label='Did - already past',
            event=0.58, event_label='try - plain, because did did the work',
            why='One past marker, at the front, where the listener meets it first and can stop '
                'waiting. The same applies to the negative: I didn\'t try, never I didn\'t '
                'tried.'),
 misconception='You have just learned to add -ed, and the habit is new and loud. It reaches for '
               'every verb it can see. The test is simple: if did or didn\'t is in the sentence, '
               'the verb has nothing on the end.'),

"fig_a11_u10_p04_v04a": dict(type='V4', height=720,
 title='The same complaint, twice',
 sub='One of them begins with the problem. One of them begins with a date.',
 alt='Two versions of the same complaint at the same counter, the first opening with the problem '
     'and the second opening with the date and the receipt.',
 differences=6, prompt='Find the six. One of the two got something back. Which, and what is in '
                       'the first sentence that made the difference?',
 left=dict(label='the problem first', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210,
        text='"This doesn\'t fit." — no date, no receipt — nothing back',
        colour='#A8372E')]),
 right=dict(label='the date first', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=160, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='"I bought it on the 1st. Here is the receipt." — a credit note',
        colour='#2E6F5E')])),

"fig_a11_u10_p05_v05": dict(type='V5', height=900,
 title='The receipt',
 sub='Everything above the line is about one jacket. Everything below it is about every jacket.',
 alt='A shop receipt showing the shop name, the date, the item, the price, the word SALE, the '
     'card line, and the four-line returns policy in small type at the bottom.',
 rows=[dict(t='org', text='CASA VERDE  -  RUA AUGUSTA 41  -  LISBOA'),
   dict(t='kv', k='DATE', v='01/12  17.14', mono=True),
   dict(t='rule'),
   dict(t='grid', cols=['ITEM', 'SIZE', 'EUR'],
     data=[['JACKET - NAVY', 'S', '39.00'],
           ['', 'SALE', '-50.00']]),
   dict(t='rule'),
   dict(t='kv', k='TOTAL', v='39.00', mono=True),
   dict(t='kv', k='CARD', v='**** 2208', mono=True),
   dict(t='kv', k='ITEMS', v='1', mono=True),
   dict(t='rule'),
   dict(t='sign', text='AND IN SMALL TYPE AT THE BOTTOM, FOUR LINES:'),
   dict(t='kv', k='1', v='Returns within 14 days with this receipt', mono=False),
   dict(t='kv', k='2', v='Goods must be unworn', mono=False),
   dict(t='kv', k='3', v='Sale items: credit note only', mono=False),
   dict(t='kv', k='4', v='Credit notes valid 6 months. No change given', mono=False),
   dict(t='rule'),
   dict(t='para', text='Line 3 is the one that applies. It is forty characters long, it is '
     'printed at six point, and it was on the paper before she paid - on the other side of the '
     'counter, inside the till.')],
 callouts=[dict(at=0.10, text='The date. Everything in Part 11 depends on it'),
   dict(at=0.24, text='Thirty-nine. And the fifty it came down from is printed here, not in '
     'the window'),
   dict(at=0.40, text='Paid by card, so there is a second record somewhere'),
   dict(at=0.72, text='Line 3 is the whole of the problem'),
   dict(at=0.94, text='It was printed after the money moved')]),

"fig_a11_u10_p06_v03a": dict(type='V3',
 title='One jacket, six dates',
 sub='Six panels, six prices. Watch the eleven people in panel two.',
 alt='Six panels following one jacket from September at eighty-nine euros through the December '
     'sale to January at nineteen euros and gone.',
 panels=[
  dict(caption='September: 89 EUR', art=[dict(kind='block', x=160, y=0, w=90, bh=120,
     colour='#A8372E')]),
  dict(caption='November: 89, and 11 tried it on',
       art=[dict(kind='block', x=160, y=0, w=90, bh=120, colour='#A8372E'),
            dict(kind='person', x=250, y=0, h=70, skin=2, cloth=4)]),
  dict(caption='1 December: 39 EUR', art=[dict(kind='block', x=160, y=0, w=90, bh=54,
     colour='#C86B2B')]),
  dict(caption='2 December: back in a bag', art=[dict(kind='arrow', x=160, y=50)]),
  dict(caption='6 January: 19 EUR', art=[dict(kind='block', x=160, y=0, w=90, bh=26,
     colour='#D9A441')]),
  dict(caption='8 January: gone', art=[dict(kind='gap', x=160, y=10, w=90, bh=60)])]),

"fig_a11_u10_p07_v10": dict(type='V10', kind='groups', height=700,
 title='One ending, three sounds',
 sub='All of these are spelled -ed. Only one of the three groups adds a beat to the word.',
 alt='Three columns sorting regular past verbs that all end in -ed by the sound that ending '
     'makes, with the rule for each column underneath.',
 groups=[
  dict(ipa='/t/', colour='#1F4E5F', rule='after a quiet sound, the ending stays quiet',
       words=['asked', 'looked', 'stopped', 'washed', 'watched'],
       before='your voice is off for /k/ /p/ /sh/ /ch/, so it stays off - and no extra beat'),
  dict(ipa='/d/', colour='#2E6F5E', rule='after a loud sound, the ending turns on',
       words=['tried', 'opened', 'called', 'arrived', 'played'],
       before='your voice is on for a vowel and for /n/ /l/ /v/, so it stays on - still no beat'),
  dict(ipa='/ɪd/', colour='#C86B2B',
       rule='after t or d, a whole syllable appears',
       words=['wanted', 'started', 'needed', 'decided', 'waited'],
       before='two t sounds cannot touch, so English puts a vowel between them - one extra beat')]),

"fig_a11_u10_p09_v02b": dict(type='V2', height=780,
 title='A year, in section',
 sub='The hours are the thickest layer. The bottom layer is the only one anybody will ever see.',
 alt='A cutaway of one year of study with the hours at the top, the words in the middle, and at '
     'the bottom the small number of things the learner can now do.',
 floors=[dict(was='the hours', now='about 140 of them, and you cannot remember most of them',
     year='', fill='#E8EEF0'),
   dict(was='the words', now='350 taught · about 96 of them yours', year='', fill='#F3EADA'),
   dict(was='the grammar', now='ten tenses and shapes · four of them automatic', year='',
     fill='#EFE6DC'),
   dict(was='what you can do', now='buy things · give directions · ask about a habit · '
     'tell what happened', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='This is what you paid'),
   dict(at=0.38, text='This is what you were given'),
   dict(at=0.62, text='This is what stuck'),
   dict(at=0.88, text='And this is the only layer anybody else can see')]),

"fig_a11_u10_p09_v03b": dict(type='V3',
 title='Two recordings, one year',
 sub='Five panels. The fifth one is the only measurement in this book that cannot lie.',
 alt='Five panels: recording thirty seconds in September, forgetting it, recording the same '
     'thirty seconds now, listening to both, and the moment of hearing the difference.',
 panels=[
  dict(caption='1 September: thirty seconds',
       art=[dict(kind='person', x=150, y=0, h=110, skin=2, cloth=4)]),
  dict(caption='2 You forget it exists',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='3 Today: the same thirty seconds',
       art=[dict(kind='person', x=150, y=0, h=110, skin=2, cloth=4, arm='hold')]),
  dict(caption='4 Listen to both, in that order',
       art=[dict(kind='arrow', x=150, y=60), dict(kind='arrow', x=150, y=20)]),
  dict(caption='5 And you cannot un-hear it',
       art=[dict(kind='tick', x=150, y=50)])]),

"fig_a11_u10_p10_v12": dict(type='V12',
 title='One jacket, five months',
 sub='The month with the most sales is not the month with the most money in it.',
 alt='An infographic following one jacket across five months with bands for the price, the '
     'number of people who tried it on, the number sold and what the shop made.',
 span=['September', 'January'], ticks=5,
 tick_labels=['Sep', 'Oct', 'Nov', 'Dec', 'Jan'],
 bands=[dict(name='Price', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.58}, label='89 EUR', colour='#A8372E'),
   dict(**{'from': 0.60, 'to': 0.80}, label='39 EUR', colour='#C86B2B'),
   dict(**{'from': 0.82, 'to': 1.0}, label='19 EUR', colour='#D9A441')]),
  dict(name='Tried it on', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.22}, label='4 people', colour='#9AA7AE'),
   dict(**{'from': 0.24, 'to': 0.58}, label='11 people - and none of them bought it',
        colour='#1F4E5F'),
   dict(**{'from': 0.60, 'to': 0.80}, label='2 people', colour='#9AA7AE'),
   dict(**{'from': 0.82, 'to': 1.0}, label='1 person', colour='#9AA7AE')]),
  dict(name='Sold', type='events', items=[
   dict(at=0.10, label='0', colour='#9AA7AE'),
   dict(at=0.40, label='0', colour='#9AA7AE'),
   dict(at=0.68, label='6 in the first week of the sale', colour='#C86B2B'),
   dict(at=0.92, label='3, in two days', colour='#D9A441')]),
  dict(name='Made on each one', type='line',
   points=[(0, 0), (0.5, 0), (0.7, 17), (1.0, -3)], end_label='-3 EUR'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.10, label='eleven people wanted it at 89 and the shop never found out why not'),
   dict(at=0.52, label='the busiest month lost money on every jacket sold')])]),

"fig_a11_u10_p11_v04b": dict(type='V4', height=720,
 title='The same window, five weeks apart',
 sub='First of December on the left, sixth of January on the right. Both of them say SALE.',
 alt='Two drawings of the same shop window. On the left, a sale sign with no old price; on the '
     'right, a sale sign with the old price crossed out beside the new one.',
 differences=6, prompt='Find the six. One of them is the number of people inside, and it is not '
                       'the one you would predict.',
 left=dict(label='1 December', art=[
   dict(kind='block', x=150, y=130, w=140, bh=26, colour='#A8372E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='SALE · 39 · no old price · 9 people inside',
        colour='#A8372E')]),
 right=dict(label='6 January', art=[
   dict(kind='block', x=150, y=130, w=240, bh=26, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=120, bh=22, colour='#9AA7AE'),
   dict(kind='label', x=300, y=210, text='SALE · 89 crossed out · 19 · 4 people inside',
        colour='#2E6F5E')])),
}
