# -*- coding: utf-8 -*-
"""Handout 13.4, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '13.4',
 'n': 4,
 'pages': 6,
 'title': 'Rate changes, valuation allowances, losses and presentation',
 'sub': 'section 13.4 of the book',
 'covers': ['sec:13.4',
            'p:P13-19',
            'p:P13-20',
            'sc:P13-19',
            'term:deferred tax liability',
            'term:current tax expense',
            'term:effective tax rate'],
 'skills': [('read4', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['Rate changes, valuation allowances, losses and presentation',
             'a figure to read · Item · the book’s own rule, gapped',
             'Under ASU 2023-09, a public company with a 21% statutory rate '
             'must separately show a reconciling item when it is at least:'],
            ['The words this section uses precisely',
             'Item · The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['A ',
                       20,
                       ' is useful only if the company will have enough ',
                       16,
                       ' to use it. If it is more likely than not that some '
                       'of the asset will not be realized, the company '
                       'records a ',
                       21,
                       '.'],
             'bank': ['permanent difference',
                      'deferred tax asset',
                      'valuation allowance',
                      'taxable income',
                      'deferred tax liability'],
             'a': 'deferred tax asset · taxable income · valuation allowance',
             'one': True,
             'why': 'The book writes: “A deferred tax asset is useful only '
                    'if the company will have enough taxable income to use '
                    'it. If it is more likely than not that some of the '
                    'asset will not be realized, the company records a '
                    'valuation allowance.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['Decision chart: does a ',
                       20,
                       ' need a ',
                       21,
                       '?. A tax loss creates a ',
                       33,
                       ', which is a deferred tax asset. They can be carried '
                       'forward without a time limit, but they can reduce '
                       'only 80% of ',
                       16,
                       ' in any year.'],
             'bank': ['taxable income',
                      'deferred tax liability',
                      'deferred tax asset',
                      'net operating loss carryforward',
                      'valuation allowance',
                      'permanent difference'],
             'a': 'deferred tax asset · valuation allowance · net operating '
                  'loss carryforward · taxable income',
             'one': True,
             'why': 'The book writes: “Decision chart: does a deferred tax '
                    'asset need a valuation allowance?. A tax loss creates a '
                    'net operating loss carryforward, which is a deferred '
                    'tax asset. They can be carried forward without a time '
                    'limit, but they can reduce only 80% of taxable income '
                    'in any year.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['Record the full effect of a rate change in '
                       'continuing operations when the law is enacted. '
                       'Record the full DTA, then a ',
                       21,
                       ': do not record only the probable part. An ',
                       24,
                       ' is recognized only if it is more likely than not to '
                       'be accepted by the tax authority.'],
             'bank': ['valuation allowance',
                      'deferred tax liability',
                      'uncertain tax position',
                      'permanent difference'],
             'a': 'valuation allowance · uncertain tax position',
             'one': True,
             'why': 'The book writes: “Record the full effect of a rate '
                    'change in continuing operations when the law is '
                    'enacted. Record the full DTA, then a valuation '
                    'allowance: do not record only the probable part. An '
                    'uncertain tax position is recognized only if it is more '
                    'likely than not to be accepted by the tax authority.”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['deferred tax liability', ''],
              ['current tax expense', ''],
              ['effective tax rate', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle',
           'A',
           'Rate changes, valuation allowances, losses and presentation'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'The book gives the type of Tax-exempt municipal bond '
                  'interest as “Permanent”.',
             'a': 'T',
             'why': 'The book pairs Tax-exempt municipal bond interest with '
                    '“Permanent”.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f4'),
          ('panel',
           'Item — the book’s own table',
           [['Item', 'Type', 'Creates'],
            ['Tax-exempt municipal bond interest', 'Permanent', 'None'],
            ['Tax depreciation faster than book depreciation',
             'Temporary, taxable',
             'DTL'],
            ['Warranty expense accrued now, deducted for tax when repairs '
             'are paid',
             '________',
             '________'],
            ['Fine for breaking an environmental law',
             '________',
             '________'],
            ['Rent received in advance, taxed when received',
             '________',
             '________'],
            ['Equity-method income, taxed only when dividends are received',
             '________',
             '________']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which type does the book give for Tax-exempt municipal '
                  'bond interest?',
             'o': ['Permanent', 'Temporary, taxable', '________'],
             'a': 'A',
             'why': 'The book’s own table gives Permanent as the type of '
                    'Tax-exempt municipal bond interest.'},
            {'t': 'MCQ',
             'q': 'Which type does the book give for Tax depreciation faster '
                  'than book depreciation?',
             'o': ['________', 'Temporary, taxable', 'Permanent'],
             'a': 'B',
             'why': 'The book’s own table gives Temporary, taxable as the '
                    'type of Tax depreciation faster than book '
                    'depreciation.'},
            {'t': 'MCQ',
             'q': 'Which type does the book give for Warranty expense '
                  'accrued now, deducted for tax when repairs are paid?',
             'o': ['________', 'Temporary, taxable', 'Permanent'],
             'a': 'A',
             'why': 'The book’s own table gives ________ as the type of '
                    'Warranty expense accrued now, deducted for tax when '
                    'repairs are paid.'},
            {'t': 'MCQ',
             'q': 'Which type does the book give for Fine for breaking an '
                  'environmental law?',
             'o': ['Permanent', 'Temporary, taxable', '________'],
             'a': 'C',
             'why': 'The book’s own table gives ________ as the type of Fine '
                    'for breaking an environmental law.'},
            {'t': 'TF',
             'q': 'The book gives the creates of Tax-exempt municipal bond '
                  'interest as “None”.',
             'a': 'T',
             'why': 'The book pairs Tax-exempt municipal bond interest with '
                    '“None”.'},
            {'t': 'TF',
             'q': 'The book gives the creates of Tax depreciation faster '
                  'than book depreciation as “________”.',
             'a': 'F',
             'why': 'The book pairs Tax depreciation faster than book '
                    'depreciation with “DTL”, not with “________”.'}]),
          ('move', 'INVENT THE RULE', ''),
          ('rule',
           'Complete the book’s own sentence. The list holds more words than '
           'there are gaps.',
           [['A ',
             20,
             ' is useful only if the company will have enough ',
             16,
             ' to use it.']],
           ['deferred tax asset',
            'taxable income',
            'uncertain tax position',
            'current tax expense'],
           'A deferred tax asset is useful only if the company will have '
           'enough taxable income to use it.',
           'deferred tax asset · taxable income'),
          ('contrast',
           'Two of the book’s own cases, side by side',
           [('Tax-exempt municipal bond interest', ['Type: Permanent']),
            ('Tax depreciation faster than book depreciation',
             ['Type: Temporary, taxable'])],
           'Only the facts above differ. What is the creates of Tax-exempt '
           'municipal bond interest?',
           ['________', 'DTL', 'None'],
           'C',
           'The book gives None as the creates of Tax-exempt municipal bond '
           'interest.'),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Under ASU 2023-09, a public company with a 21% statutory '
                  'rate must separately show a reconciling item when it is '
                  'at least:',
             'o': ['1% of revenue',
                   '5% of pretax income multiplied by the statutory rate',
                   '10% of tax expense',
                   'any amount, however small'],
             'a': 'B',
             'why': 'The 5% threshold applies to the statutory-rate tax. A '
                    'is wrong: The threshold is not based on revenue. C is '
                    'wrong: The threshold is 5% of the statutory tax.',
             'src': 'P13-19'},
            {'t': 'MCQ',
             'q': 'Which pair lists one taxable and one deductible temporary '
                  'difference?',
             'o': ['Accelerated tax depreciation; accrued litigation loss',
                   'Municipal interest; fines',
                   'Accrued warranty; allowance for credit losses',
                   'Installment sale; accelerated tax depreciation'],
             'a': 'A',
             'why': 'Depreciation creates a DTL; the litigation accrual '
                    'creates a DTA. B is wrong: Both are permanent '
                    'differences. C is wrong: Both are deductible '
                    'differences.',
             'src': 'P13-20'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Under ASU 2023-09, a public company with a 21% statutory rate '
           'must separately show a reconciling item when it is at least:',
           ['1% of revenue',
            '5% of pretax income multiplied by the statutory rate',
            '10% of tax expense',
            'any amount, however small'],
           'B',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'The 5% threshold applies to the statutory-rate tax. A is wrong: '
           'The threshold is not based on revenue. C is wrong: The threshold '
           'is 5% of the statutory tax.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Item — the book’s own table',
           [['Item', 'Answer'],
            ['Warranty expense accrued now', 'Temporary, deductible: DTA'],
            ['Fine for breaking the law', 'Permanent: no deferred tax'],
            ['Rent received in advance',
             'Temporary, deductible (taxed now, earned later): DTA'],
            ['Equity-method income',
             'Temporary, taxable (taxed later): DTL']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['deferred tax liability', 'التزام ضريبي مؤجل'],
            ['current tax expense', 'مصروف الضريبة الجارية'],
            ['effective tax rate', 'معدل الضريبة الفعلي']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which answer does the book give for Warranty expense '
                  'accrued now?',
             'o': ['Temporary, deductible: DTA',
                   'Temporary, deductible (taxed now, earned later): DTA',
                   'Permanent: no deferred tax',
                   'Temporary, taxable (taxed later): DTL'],
             'a': 'A',
             'why': 'The book’s own table gives Temporary, deductible: DTA '
                    'as the answer of Warranty expense accrued now.'},
            {'t': 'MCQ',
             'q': 'Which answer does the book give for Fine for breaking the '
                  'law?',
             'o': ['Temporary, deductible: DTA',
                   'Permanent: no deferred tax',
                   'Temporary, taxable (taxed later): DTL',
                   'Temporary, deductible (taxed now, earned later): DTA'],
             'a': 'B',
             'why': 'The book’s own table gives Permanent: no deferred tax '
                    'as the answer of Fine for breaking the law.'},
            {'t': 'MCQ',
             'q': 'Which answer does the book give for Rent received in '
                  'advance?',
             'o': ['Temporary, deductible: DTA',
                   'Temporary, taxable (taxed later): DTL',
                   'Temporary, deductible (taxed now, earned later): DTA',
                   'Permanent: no deferred tax'],
             'a': 'C',
             'why': 'The book’s own table gives Temporary, deductible (taxed '
                    'now, earned later): DTA as the answer of Rent received '
                    'in advance.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'TF',
             'q': 'Writing a term in English is part of answering the '
                  'question, not an extra.',
             'a': 'T',
             'why': 'The exam marks the term, so the English word is the '
                    'answer.'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f4',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['deferred tax liability',
            'current tax expense',
            'effective tax rate'],
           'When a new tax law changes the rate, the company remeasures its '
           'deferred taxes at once. The whole effect goes to income from '
           'continuing operations in the period that includes the enactment '
           'date, even if the original item was in OCI. For example, a U.S. '
           'tax law signed on July 4, 2025 changed several deduction rules; '
           'companies recorded the effects in the quart')]}
