# -*- coding: utf-8 -*-
"""Handout 8.6, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '8.6',
 'n': 6,
 'pages': 7,
 'title': 'The whole chapter',
 'sub': 'every section, shuffled, and the chapter’s own case set',
 'covers': ['sec:summary',
            'sc:SC8-1',
            'sc:SC8-2',
            'sc:SC8-4',
            'sc:SC8-5',
            'sc:SC8-6',
            'sc:SC8-7',
            'sc:SC8-8',
            'sc:SC8-9',
            'term:net realizable value (nrv)',
            'term:lower of cost and net realizable value (lcnrv)',
            'term:lower of cost or market (lcm)',
            'term:replacement cost',
            'term:write-down',
            'term:retail inventory method',
            'term:cost-to-retail ratio',
            'term:conventional retail method',
            'term:gross profit method',
            'term:ceiling',
            'term:floor',
            'term:normal profit margin',
            'term:item-by-item basis',
            'term:purchase commitment',
            'term:markup',
            'term:markdown',
            'term:shrinkage',
            'case:C8-1',
            'case:C8-2',
            'case:C8-3',
            'case:C8-4',
            'case:C8-5',
            'case:C8-6'],
 'skills': [('review', 0)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this chapter, in the book’s own words, with '
           'words taken out. Read all three first: together they are the '
           'whole chapter. Then fill the gaps.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['The whole chapter, in order',
             'a figure to read',
             'Orontes measures olive oil using FIFO. Which test applies at '
             'year-end?'],
            ['The chapter’s case set',
             'The chapter’s case set, item by item · Orontes olive oil, '
             'December 31, 2025',
             'What has to be settled before any figure in a case set is '
             'worked out?'],
            ['The words it uses precisely',
             'net realizable value (NRV) · lower of cost and net realizable '
             'value (LCNRV) · lower of cost or market (LCM) · replacement '
             'cost · write-down · retail inventory method',
             'matching, at the end of cycle B']],
           [{'t': 'FILL',
             'q': 'Where the chapter starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['GAAP never reverses an annual ',
                       12,
                       '. SC8-1 Orontes measures olive oil using FIFO. Under '
                       'LCM, market starts with ',
                       18,
                       ': the current cost to buy or make the item again. It '
                       'cannot be higher than a ',
                       11,
                       ' equal to NRV, and it cannot be lower than a ',
                       11,
                       ' equal to NRV minus a ',
                       22,
                       '.'],
             'bank': ['gross profit method',
                      'markdown',
                      'normal profit margin',
                      'floor',
                      'ceiling',
                      'replacement cost',
                      'write-down'],
             'a': 'write-down · replacement cost · ceiling · floor · normal '
                  'profit margin',
             'one': True,
             'why': 'The book writes: “GAAP never reverses an annual '
                    'write-down. SC8-1 Orontes measures olive oil using '
                    'FIFO. Under LCM, market starts with replacement cost: '
                    'the current cost to buy or make the item again. It '
                    'cannot be higher than a ceiling equal to NRV, and it '
                    'cannot be lower than a floor equal to NRV minus a '
                    'normal profit margin.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['The ',
                       20,
                       ' is the most conservative. One more rule: if a '
                       'company has a firm, non-cancellable ',
                       21,
                       ' at a price above the current market, it records the '
                       'expected loss now, in the current period. Do not '
                       'compare ',
                       18,
                       ' directly with cost. First limit it by the ',
                       11,
                       ' and the ',
                       11,
                       '.'],
             'bank': ['purchase commitment',
                      'floor',
                      'ceiling',
                      'replacement cost',
                      'markdown',
                      'gross profit method',
                      'item-by-item basis'],
             'a': 'item-by-item basis · purchase commitment · replacement '
                  'cost · ceiling · floor',
             'one': True,
             'why': 'The book writes: “The item-by-item basis is the most '
                    'conservative. One more rule: if a company has a firm, '
                    'non-cancellable purchase commitment at a price above '
                    'the current market, it records the expected loss now, '
                    'in the current period. Do not compare replacement cost '
                    'directly with cost. First limit it by the ceiling and '
                    'the floor.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['For example, a ',
                       11,
                       ' of one half on cost is a gross profit rate of one '
                       'third on sales. Conventional retail: markups IN the '
                       'ratio, markdowns OUT. Freight-in goes in the cost '
                       'column only; normal ',
                       11,
                       ' is deducted from retail after the ratio.'],
             'bank': ['markup', 'floor', 'shrinkage', 'gross profit method'],
             'a': 'markup · shrinkage',
             'one': True,
             'why': 'The book writes: “For example, a markup of one half on '
                    'cost is a gross profit rate of one third on sales. '
                    'Conventional retail: markups IN the ratio, markdowns '
                    'OUT. Freight-in goes in the cost column only; normal '
                    'shrinkage is deducted from retail after the ratio.”'}]),
          ('page',),
          ('cycle', 'A', 'The whole chapter, in order'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'The sections of a chapter have to be taken in order, '
                  'because each one uses what the one before it settled.',
             'a': 'T',
             'why': 'The map shows the order the decisions have to be taken '
                    'in.'}]),
          ('move', 'MODEL', ''),
          ('fig', 'chmap'),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which part of this chapter is section 8.1?',
             'o': ['Recommending a method',
                   'Advantages and disadvantages of the methods',
                   'Lower of cost or market',
                   'Which test applies?'],
             'a': 'D',
             'why': 'The book numbers “Which test applies?” as section 8.1.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 8.2?',
             'o': ['Which test applies?',
                   'Recommending a method',
                   'Advantages and disadvantages of the methods',
                   'Lower of cost or market'],
             'a': 'D',
             'why': 'The book numbers “Lower of cost or market” as section '
                    '8.2.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 8.3?',
             'o': ['Lower of cost or market',
                   'Recommending a method',
                   'The retail inventory method and the gross profit method',
                   'Advantages and disadvantages of the methods'],
             'a': 'C',
             'why': 'The book numbers “The retail inventory method and the '
                    'gross profit method” as section 8.3.'},
            {'t': 'MATCH',
             'q': 'Write the letter of the section number beside each '
                  'section title. Every number is used once.',
             'left': ['Which test applies?',
                      'Lower of cost or market',
                      'The retail inventory method and the gross profit '
                      'method',
                      'Advantages and disadvantages of the methods',
                      'Recommending a method'],
             'right': ['8.1', '8.2', '8.3', '8.4', '8.5'],
             'a': ['A', 'B', 'C', 'D', 'E'],
             'whys': ['', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Use the Jebel Ali fire example. What is the estimated '
                  'inventory at the date of the fire (whole USD)?',
             'o': ['72,308', '88,000', '100,000', '260,000'],
             'a': 'C',
             'why': 'Goods available − net sales × (1 − gross profit rate). '
                    'A is wrong: This treats the rate as a markup on cost '
                    'instead of a margin on sales. B is wrong: This is the '
                    'fire loss after salvage, not the inventory at the fire '
                    'date.',
             'src': 'SC8-6'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'When prices are rising, which is an advantage of LIFO?',
             'o': ['It matches current costs with current revenues.',
                   'It shows inventory close to current cost.',
                   'It is allowed under IFRS.',
                   'It needs the fewest records.'],
             'a': 'A',
             'why': 'LIFO puts the newest costs into cost of goods sold. B '
                    'is wrong: That is a FIFO advantage; LIFO inventory '
                    'holds old costs. C is wrong: IFRS prohibits LIFO.',
             'src': 'SC8-7'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'For large volumes of identical items, the main '
                  'disadvantage of specific identification is that:',
             'o': ['it is not allowed under U.S. GAAP.',
                   'it always overstates income.',
                   'it ignores the physical flow of goods.',
                   'management can choose which units to sell and so change '
                   'income.'],
             'a': 'D',
             'why': 'Identical units with different costs let management '
                    'pick the cost that gives the income it wants. A is '
                    'wrong: Specific identification is allowed. B is wrong: '
                    'It can raise or lower income, depending on the units '
                    'chosen.',
             'src': 'SC8-8'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'Cedar Retail S.A.L. reports under IFRS. Prices are '
                  'rising, and it wants lower taxes. Which recommendation is '
                  'appropriate?',
             'o': ['LIFO, because it lowers taxes when prices rise',
                   'FIFO or weighted average, because LIFO is not allowed',
                   'Specific identification for all of its items',
                   'The LIFO retail method'],
             'a': 'B',
             'why': 'IFRS rules out LIFO, whatever the tax goal. A is wrong: '
                    'LIFO is prohibited under IAS 2. C is wrong: A '
                    "retailer's items are interchangeable.",
             'src': 'SC8-9'}]),
          ('pair',
           'Compare every answer with your partner first.',
           'name the section each question belongs to. Most disagreements '
           'turn out to be about the section, not the answer.'),
          ('check',
           'Orontes measures olive oil using FIFO. Which test applies at '
           'year-end?',
           ['Lower of cost or market',
            'Replacement cost only',
            'Lower of cost and net realizable value',
            'No test; FIFO inventory stays at cost'],
           'C',
           'go back to the MODEL move of cycle A and find the section this '
           'question belongs to.',
           'FIFO, average cost and specific identification use LCNRV. A is '
           'wrong: LCM applies only to LIFO and the retail inventory method. '
           'B is wrong: Replacement cost is only the starting point for '
           'market under LCM.'),
          ('cycle', 'B', 'The chapter’s case set'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'In a case question, the exhibit has to be read and '
                  'adjusted before any figure is worked out.',
             'a': 'T',
             'why': 'Every later answer depends on the adjusted exhibit.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The chapter’s case set, item by item',
           [['Item', 'What it asks'],
            ['C8-1',
             'Match each product line to the test that applies. (On the exam '
             'screen you would drag each line into a box.)'],
            ['C8-2', 'Enter the write-down for pomegranate molasses (USD).'],
            ['C8-3', 'Enter the total write-down for all five lines (USD).'],
            ['C8-4',
             'Enter the total carrying amount of the five lines after the '
             'write-downs (USD).'],
            ['C8-5',
             "In 2026, the NRV of za'atar mix rises to $13 a unit. Under "
             'U.S. GAAP, the 2025 write-down: [select]'],
            ['C8-6',
             "If Orontes reported under IFRS, how much of the za'atar "
             'write-down would it reverse in 2026 (USD)?']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which of these does item C8-1 ask for?',
             'o': ['Match each product line to the test that applies. (On '
                   'the exam screen ',
                   'Enter the total carrying amount of the five lines after '
                   'the write-down',
                   "If Orontes reported under IFRS, how much of the za'atar "
                   'write-down wou',
                   "In 2026, the NRV of za'atar mix rises to $13 a unit. "
                   'Under U.S. GAAP, '],
             'a': 'A',
             'why': 'The book states item C8-1 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C8-2 ask for?',
             'o': ['Enter the write-down for pomegranate molasses (USD).',
                   'Enter the total write-down for all five lines (USD).',
                   'Match each product line to the test that applies. (On '
                   'the exam screen ',
                   'Enter the total carrying amount of the five lines after '
                   'the write-down'],
             'a': 'A',
             'why': 'The book states item C8-2 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C8-3 ask for?',
             'o': ['Enter the write-down for pomegranate molasses (USD).',
                   'Match each product line to the test that applies. (On '
                   'the exam screen ',
                   'Enter the total carrying amount of the five lines after '
                   'the write-down',
                   'Enter the total write-down for all five lines (USD).'],
             'a': 'D',
             'why': 'The book states item C8-3 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C8-4 ask for?',
             'o': ['Enter the total carrying amount of the five lines after '
                   'the write-down',
                   "In 2026, the NRV of za'atar mix rises to $13 a unit. "
                   'Under U.S. GAAP, ',
                   'Match each product line to the test that applies. (On '
                   'the exam screen ',
                   "If Orontes reported under IFRS, how much of the za'atar "
                   'write-down wou'],
             'a': 'A',
             'why': 'The book states item C8-4 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C8-5 ask for?',
             'o': ["If Orontes reported under IFRS, how much of the za'atar "
                   'write-down wou',
                   "In 2026, the NRV of za'atar mix rises to $13 a unit. "
                   'Under U.S. GAAP, ',
                   'Match each product line to the test that applies. (On '
                   'the exam screen ',
                   'Enter the total carrying amount of the five lines after '
                   'the write-down'],
             'a': 'B',
             'why': 'The book states item C8-5 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C8-6 ask for?',
             'o': ["If Orontes reported under IFRS, how much of the za'atar "
                   'write-down wou',
                   'Enter the total carrying amount of the five lines after '
                   'the write-down',
                   "In 2026, the NRV of za'atar mix rises to $13 a unit. "
                   'Under U.S. GAAP, ',
                   'Match each product line to the test that applies. (On '
                   'the exam screen '],
             'a': 'A',
             'why': 'The book states item C8-6 in those words.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Orontes measures olive oil using FIFO. Which test applies '
                  'at year-end?',
             'o': ['Lower of cost or market',
                   'Replacement cost only',
                   'Lower of cost and net realizable value',
                   'No test; FIFO inventory stays at cost'],
             'a': 'C',
             'why': 'FIFO, average cost and specific identification use '
                    'LCNRV. A is wrong: LCM applies only to LIFO and the '
                    'retail inventory method. B is wrong: Replacement cost '
                    'is only the starting point for market under LCM.',
             'src': 'SC8-1'}]),
          ('panel',
           'Orontes olive oil, December 31, 2025 — the extract for the '
           'question that follows',
           [['Orontes olive oil, December 31, 2025', 'Amount'],
            ['Olive oil cases on hand (FIFO layer from Chapter 7)', '2,000'],
            ['Cost per case', '$50'],
            ['New estimated selling price per case', '$54'],
            ['Costs to sell and deliver per case', '$6'],
            ['NRV per case', '$48'],
            ['Inventory at cost', '$100,000'],
            ['Inventory at LCNRV', '$96,000'],
            ['Write-down (loss in income)', '$4,000']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Use the olive-oil example in the extract. What is the '
                  'write-down (whole USD)?',
             'o': ['0', '4,000', '12,000', '96,000'],
             'a': 'B',
             'why': 'NRV = selling price − costs to sell; write-down = (cost '
                    '− NRV) × cases. A is wrong: This compares cost with the '
                    'selling price and ignores the costs to sell. C is '
                    'wrong: This is the total of the costs to sell, not the '
                    'write-down.',
             'src': 'SC8-2'}]),
          ('check',
           'What has to be settled before any figure in a case set is worked '
           'out?',
           ['the exhibit, adjusted for every note that goes with it',
            'the method the company uses',
            'the tax rate',
            'the order of the items'],
           'A',
           'reread the case panel in the MODEL move of cycle B.',
           'Every later answer depends on the adjusted exhibit.'),
          ('build',
           'chmap',
           'Rebuild the chapter map. Write every section in order and what '
           'each one settles.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a student starting this chapter tomorrow',
           'In four or five sentences, write what the whole chapter settles, '
           'section by section.',
           ['net realizable value (NRV)',
            'lower of cost and net realizable value (LCNRV)',
            'lower of cost or market (LCM)',
            'replacement cost'],
           '8.1: Which test applies?. 8.2: Lower of cost or market. 8.3: The '
           'retail inventory method and the gross profit method. 8.4: '
           'Advantages and disadvantages of the methods. 8.5: Recommending a '
           'method.')]}
