# -*- coding: utf-8 -*-
"""Handout 8.6, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '8.6',
 'n': 6,
 'pages': 6,
 'title': 'The whole chapter',
 'sub': 'every section, shuffled, and the chapter’s own case set',
 'covers': ['sec:summary',
            'p:P8-13',
            'p:P8-14',
            'sc:SC8-1',
            'sc:SC8-2',
            'sc:SC8-4',
            'sc:SC8-5',
            'sc:SC8-6',
            'sc:SC8-7',
            'sc:SC8-8',
            'sc:SC8-9',
            'term:net realizable value (nrv)',
            'term:lower of cost and net realizable value (lcnrv)',
            'term:lower of cost or market (lcm)',
            'term:replacement cost',
            'term:write-down',
            'term:retail inventory method',
            'term:cost-to-retail ratio',
            'term:conventional retail method',
            'term:gross profit method',
            'term:ceiling',
            'term:floor',
            'term:normal profit margin',
            'term:item-by-item basis',
            'term:purchase commitment',
            'term:markup',
            'term:markdown',
            'term:shrinkage',
            'case:C8-1',
            'case:C8-2',
            'case:C8-3',
            'case:C8-4',
            'case:C8-5',
            'case:C8-6'],
 'skills': [('review', 0)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this chapter, in the book’s own words, with '
           'words taken out. Read all three first: together they are the '
           'whole chapter. Then fill the gaps.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['The whole chapter, in order',
             'a figure to read',
             'A company sells custom-built industrial ovens, each with a '
             'different cost. Which method should it recommend?'],
            ['The chapter’s case set',
             'The chapter’s case set, item by item',
             'What has to be settled before any figure in a case set is '
             'worked out?'],
            ['The words it uses precisely',
             'net realizable value (NRV) · lower of cost and net realizable '
             'value (LCNRV) · lower of cost or market (LCM) · replacement '
             'cost · write-down · retail inventory method',
             'matching, at the end of cycle B']],
           [{'t': 'FILL',
             'q': 'Where the chapter starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['U.S. GAAP never reverses an annual ',
                       12,
                       '. Under LCM, market starts with ',
                       18,
                       ': the current cost to buy or make the item again. It '
                       'cannot be higher than a ',
                       11,
                       ' equal to NRV, and it cannot be lower than a ',
                       11,
                       ' equal to NRV minus a ',
                       22,
                       '.'],
             'bank': ['gross profit method',
                      'markdown',
                      'normal profit margin',
                      'floor',
                      'ceiling',
                      'replacement cost',
                      'write-down'],
             'a': 'write-down · replacement cost · ceiling · floor · normal '
                  'profit margin',
             'one': True,
             'why': 'The book writes: “U.S. GAAP never reverses an annual '
                    'write-down. Under LCM, market starts with replacement '
                    'cost: the current cost to buy or make the item again. '
                    'It cannot be higher than a ceiling equal to NRV, and it '
                    'cannot be lower than a floor equal to NRV minus a '
                    'normal profit margin.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['When ',
                       18,
                       ' is below the ',
                       11,
                       ', market is the floor. When it is above the ',
                       11,
                       ', market is the ceiling. Read the basis in the '
                       'question: item by item, by category or total. In '
                       'French, dépréciation des stocks is an inventory ',
                       12,
                       ', not depreciation (amortissement).'],
             'bank': ['floor',
                      'gross profit method',
                      'write-down',
                      'ceiling',
                      'markdown',
                      'replacement cost'],
             'a': 'replacement cost · floor · ceiling · write-down',
             'one': True,
             'why': 'The book writes: “When replacement cost is below the '
                    'floor, market is the floor. When it is above the '
                    'ceiling, market is the ceiling. Read the basis in the '
                    'question: item by item, by category or total. In '
                    'French, dépréciation des stocks is an inventory '
                    'write-down, not depreciation (amortissement).”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['If items are identical and sold in large volumes, '
                       'specific ',
                       16,
                       ' is costly and open to ',
                       14,
                       '. If the company wants the U.S. tax benefit of LIFO, '
                       'it must also report LIFO profits to investors, and '
                       'it must avoid ',
                       13,
                       ' old layers.'],
             'bank': ['identification',
                      'manipulation',
                      'gross profit method',
                      'liquidating',
                      'floor'],
             'a': 'identification · manipulation · liquidating',
             'one': True,
             'why': 'The book writes: “If items are identical and sold in '
                    'large volumes, specific identification is costly and '
                    'open to manipulation. If the company wants the U.S. tax '
                    'benefit of LIFO, it must also report LIFO profits to '
                    'investors, and it must avoid liquidating old '
                    'layers.”'}]),
          ('page',),
          ('cycle', 'A', 'The whole chapter, in order'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'The sections of a chapter have to be taken in order, '
                  'because each one uses what the one before it settled.',
             'a': 'T',
             'why': 'The map shows the order the decisions have to be taken '
                    'in.'}]),
          ('move', 'MODEL', ''),
          ('fig', 'chmap'),
          ('fig', 'frev'),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which part of this chapter is section 8.1?',
             'o': ['Recommending a method',
                   'Advantages and disadvantages of the methods',
                   'Lower of cost or market',
                   'Which test applies?'],
             'a': 'D',
             'why': 'The book numbers “Which test applies?” as section 8.1.'},
            {'t': 'MATCH',
             'q': 'Write the letter of the section number beside each '
                  'section title. Every number is used once.',
             'left': ['Which test applies?',
                      'Lower of cost or market',
                      'The retail inventory method and the gross profit '
                      'method',
                      'Advantages and disadvantages of the methods',
                      'Recommending a method'],
             'right': ['8.1', '8.2', '8.3', '8.4', '8.5'],
             'a': ['A', 'B', 'C', 'D', 'E'],
             'whys': ['', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which basis gives the largest LCM write-down?',
             'o': ['Item by item',
                   'Total inventory',
                   'By category',
                   'All bases give the same write-down.'],
             'a': 'A',
             'why': 'Item by item does not let gains on some items offset '
                    'losses on others. B is wrong: The total basis lets '
                    'increases offset decreases, so the write-down is '
                    'smallest. C is wrong: Categories allow some offsetting '
                    'inside each category.',
             'src': 'SC8-4'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'In the conventional retail method, net markdowns are:',
             'o': ['included in the cost-to-retail ratio.',
                   'left out of the cost-to-retail ratio.',
                   'deducted from the cost column.',
                   'ignored completely.'],
             'a': 'B',
             'why': 'Leaving markdowns out gives a lower ratio, which '
                    'approximates LCM. A is wrong: That is the average-cost '
                    'retail method. C is wrong: Markdowns are retail amounts '
                    'only.',
             'src': 'SC8-5'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'Use the Jebel Ali fire example. What is the estimated '
                  'inventory at the date of the fire (whole USD)?',
             'o': ['72,308', '88,000', '100,000', '260,000'],
             'a': 'C',
             'why': 'Goods available − net sales × (1 − gross profit rate). '
                    'A is wrong: This treats the rate as a markup on cost '
                    'instead of a margin on sales. B is wrong: This is the '
                    'fire loss after salvage, not the inventory at the fire '
                    'date.',
             'src': 'SC8-6'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'When prices are rising, which is an advantage of LIFO?',
             'o': ['It matches current costs with current revenues.',
                   'It shows inventory close to current cost.',
                   'It is allowed under IFRS.',
                   'It needs the fewest records.'],
             'a': 'A',
             'why': 'LIFO puts the newest costs into cost of goods sold. B '
                    'is wrong: That is a FIFO advantage; LIFO inventory '
                    'holds old costs. C is wrong: IFRS prohibits LIFO.',
             'src': 'SC8-7'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'For large volumes of identical items, the main '
                  'disadvantage of specific identification is that:',
             'o': ['it is not allowed under U.S. GAAP.',
                   'it always overstates income.',
                   'it ignores the physical flow of goods.',
                   'management can choose which units to sell and so change '
                   'income.'],
             'a': 'D',
             'why': 'Identical units with different costs let management '
                    'pick the cost that gives the income it wants. A is '
                    'wrong: Specific identification is allowed. B is wrong: '
                    'It can raise or lower income, depending on the units '
                    'chosen.',
             'src': 'SC8-8'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'Cedar Retail S.A.L. reports under IFRS. Prices are '
                  'rising, and it wants lower taxes. Which recommendation is '
                  'appropriate?',
             'o': ['LIFO, because it lowers taxes when prices rise',
                   'FIFO or weighted average, because LIFO is not allowed',
                   'Specific identification for all of its items',
                   'The LIFO retail method'],
             'a': 'B',
             'why': 'IFRS rules out LIFO, whatever the tax goal. A is wrong: '
                    'LIFO is prohibited under IAS 2. C is wrong: A '
                    "retailer's items are interchangeable.",
             'src': 'SC8-9'}]),
          ('pair',
           'Compare every answer with your partner first.',
           'name the section each question belongs to. Most disagreements '
           'turn out to be about the section, not the answer.'),
          ('check',
           'A company sells custom-built industrial ovens, each with a '
           'different cost. Which method should it recommend?',
           ['LIFO',
            'Specific identification',
            'Weighted average',
            'The retail inventory method'],
           'B',
           'go back to the MODEL move of cycle A and find the section this '
           'question belongs to.',
           'Each oven is unique and valuable, so the actual cost of each '
           'unit can be tracked. A is wrong: LIFO suits interchangeable '
           'goods, not unique items. C is wrong: Averaging unique costs '
           'would distort the cost of each sale.'),
          ('cycle', 'B', 'The chapter’s case set'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'In a case question, the exhibit has to be read and '
                  'adjusted before any figure is worked out.',
             'a': 'T',
             'why': 'Every later answer depends on the adjusted exhibit.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The chapter’s case set, item by item',
           [['Item', 'What it asks'],
            ['C8-1',
             'Match each product line to the test that applies. (On the exam '
             'screen you would drag each line into a box.)'],
            ['C8-2', 'Enter the write-down for pomegranate molasses (USD).'],
            ['C8-3', 'Enter the total write-down for all five lines (USD).'],
            ['C8-4',
             'Enter the total carrying amount of the five lines after the '
             'write-downs (USD).'],
            ['C8-5',
             "In 2026, the NRV of za'atar mix rises to $13 a unit. Under "
             'U.S. GAAP, the 2025 write-down: [select]'],
            ['C8-6',
             "If Orontes reported under IFRS, how much of the za'atar "
             'write-down would it reverse in 2026 (USD)?']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MATCH',
             'q': 'The tasks of a case set have to be worked in one order, '
                  'because each one uses the result of the one before it. '
                  'Write the letter of its place beside each task.',
             'left': ['Match each product line to the test that applies. (On '
                      'the exam screen you would drag each line into a box.)',
                      'Enter the write-down for pomegranate molasses (USD).',
                      'Enter the total carrying amount of the five lines '
                      'after the write-downs (USD).',
                      'Enter the total write-down for all five lines (USD).',
                      "In 2026, the NRV of za'atar mix rises to $13 a unit. "
                      'Under U.S. GAAP, the 2025 write-down: [select]',
                      'If Orontes reported under IFRS, how much of the '
                      "za'atar write-down would it reverse in 2026 (USD)?"],
             'right': ['first',
                       'second',
                       'third',
                       'fourth',
                       'fifth',
                       'sixth'],
             'a': ['A', 'B', 'D', 'C', 'E', 'F'],
             'whys': ['', '', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'A U.S. subsidiary reports under U.S. GAAP, but its parent '
                  'prepares IFRS group statements. The parent wants one '
                  'method for group reporting. Which recommendation fits '
                  'best?',
             'o': ['FIFO or weighted average, so the same records work for '
                   'the IFRS group statements',
                   'LIFO, because the subsidiary reports under U.S. GAAP',
                   'LIFO for the subsidiary and the retail method for the '
                   'group',
                   'Specific identification, to avoid the IFRS rules'],
             'a': 'A',
             'why': 'The group cannot use LIFO under IFRS, so a non-LIFO '
                    'method avoids two sets of records. B is wrong: LIFO '
                    'would need to be reversed for the IFRS group '
                    'statements. C is wrong: This adds complexity and still '
                    'uses LIFO.',
             'src': 'P8-14'}]),
          ('check',
           'What has to be settled before any figure in a case set is worked '
           'out?',
           ['the exhibit, adjusted for every note that goes with it',
            'the method the company uses',
            'the tax rate',
            'the order of the items'],
           'A',
           'reread the case panel in the MODEL move of cycle B.',
           'Every later answer depends on the adjusted exhibit.'),
          ('build',
           'chmap',
           'Rebuild the chapter map. Write every section in order and what '
           'each one settles.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a student starting this chapter tomorrow',
           'In four or five sentences, write what the whole chapter settles, '
           'section by section.',
           ['net realizable value (NRV)',
            'lower of cost and net realizable value (LCNRV)',
            'lower of cost or market (LCM)',
            'replacement cost'],
           '8.1: Which test applies?. 8.2: Lower of cost or market. 8.3: The '
           'retail inventory method and the gross profit method. 8.4: '
           'Advantages and disadvantages of the methods. 8.5: Recommending a '
           'method.')]}
