"""A2.2 Unit 1 - Twelve Centimetres - fourteen figures, as data."""
FIGURES = {
"fig_a22_u01_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='Strand Road, eight months after',
 sub='Eleven things to find. Three of them were not here in January.',
 alt='A small coastal street with a sea wall, a slipway, a community hall, skips, scaffolding, '
     'a boat on a trailer and a watermark on the house fronts.',
 sky='#DDE3E6', ground='#9FA6A6', ground_line=660,
 buildings=[dict(x=20, w=420, storeys=2, colour='#D7D2C6', label='14 Strand Road'),
   dict(x=470, w=360, storeys=2, colour='#CFCCC2', label='the terrace'),
   dict(x=870, w=300, storeys=1, colour='#D9D3C2', label='the community hall'),
   dict(x=1210, w=370, storeys=2, colour='#C6C4BE', label='the old store')],
 props=[dict(kind='hoarding', x=560, y=660, s=1.0),
   dict(kind='scaffold', x=300, y=660, s=1.0),
   dict(kind='box', x=180, y=660, s=1.2), dict(kind='box', x=700, y=660, s=1.2),
   dict(kind='crate', x=990, y=660, s=1.1),
   dict(kind='van', x=1320, y=660, s=.95, colour='#2E6F5E'),
   dict(kind='sign', x=120, y=660, s=.75, text='12 cm'),
   dict(kind='sign', x=1480, y=660, s=.75, text='FOR SALE')],
 people=[dict(x=250, y=660, h=86, skin=0, cloth=1, hair='long', arm='hold'),
   dict(x=460, y=660, h=85, skin=1, cloth=0, hair='cap', arm='point'),
   dict(x=760, y=660, h=86, skin=0, cloth=2, hair='bun', arm='down'),
   dict(x=1030, y=660, h=85, skin=1, cloth=4, hair='grey', arm='hold'),
   dict(x=1260, y=660, h=86, skin=2, cloth=3, hair='short', arm='raise')],
 names=[dict(x=250, t='Eimear, 14 Strand Road'), dict(x=460, t='Donal, who moved his car'),
   dict(x=760, t='Sinead, opened the hall'), dict(x=1030, t='Peadar, who lost a boat'),
   dict(x=1260, t='Aoife, filming again'), dict(x=120, t='the watermark, still there'),
   dict(x=1480, t='two of these on this street')],
 markers=[dict(x=250, y=548), dict(x=460, y=548), dict(x=760, y=548), dict(x=1030, y=548),
   dict(x=1260, y=548), dict(x=120, y=592), dict(x=1480, y=592), dict(x=300, y=556),
   dict(x=560, y=600), dict(x=990, y=612), dict(x=1320, y=604)]),

"fig_a22_u01_p01_v08": dict(type='V8', height=780,
 title='Before, during, after',
 sub='Five stages. The dashed line is the one everybody discovers in February.',
 alt='A network from warning through preparation, the flood, recovery and the insurance claim, '
     'with a dashed line to the things that are not covered.',
 nodes={
  'war': dict(x=180, y=400, short='1', name='The warning', sub='and the one that came to nothing', colour='#D9A441'),
  'pre': dict(x=520, y=230, short='2', name='Prepare', sub='sandbags, the car, the shed', colour='#2E6F5E'),
  'flo': dict(x=520, y=570, short='3', name='The water', sub='up through the drain', colour='#1F4E5F'),
  'rec': dict(x=900, y=400, short='4', name='Recover', sub='eight months to dry a floor', r=54, colour='#C86B2B'),
  'cov': dict(x=1290, y=400, short='5', name='Not covered', sub='and this is the surprise', r=54, colour='#A8372E')},
 edges=[dict(a='war', b='pre', label='if you believe it', sw=5),
   dict(a='war', b='flo', label='and if you do not', sw=4, dash='5 5'),
   dict(a='pre', b='flo', label='twelve centimetres anyway', sw=5),
   dict(a='flo', b='rec', label='skips, dehumidifiers, waiting', sw=5),
   dict(a='rec', b='cov', label='ninety days of accommodation', sw=5),
   dict(a='pre', b='cov', label='the excess, which is the same either way', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_a22_u01_p01_v02": dict(type='V2', height=780,
 title='14 Strand Road, in section',
 sub='One watermark, twelve centimetres up the kitchen wall, and eight months of drying.',
 alt='A two-storey house drawn in section showing the roof, the bedrooms, the ground floor with '
     'a watermark and the sub-floor, each labelled with what the water did.',
 floors=[dict(was='the roof', now='Untouched. The storm took two slates and nothing else',
     year='', fill='#EDE7DA'),
   dict(was='upstairs', now='Where everybody slept for three months', year='', fill='#E4ECEF'),
   dict(was='the ground floor', now='12 cm. The watermark is still on the wall', year='Jan',
     fill='#EFE2DD'),
   dict(was='under the floor', now='The expensive part. Still damp in September', year='',
     fill='#DCE6EA')],
 callouts=[dict(at=0.12, text='The cheapest repair, and the first one done'),
   dict(at=0.38, text='Dry, and crowded, for ninety days'),
   dict(at=0.62, text='Twelve centimetres is nothing until it is in your kitchen'),
   dict(at=0.88, text='You cannot tell when it is dry, so you wait')]),

"fig_a22_u01_p02_v07": dict(type='V7', height=800,
 title='Donal, and the top road',
 sub='One of them moved a car two days early. The other had sandbags in a shed.',
 alt='Two neighbours talking on a street, one leaning on a wall, with speech bubbles using '
     'second conditionals.',
 bg='#E8EBEC',
 set=[dict(kind='box', x=680, y=680, s=1.2), dict(kind='sign', x=1300, y=680, s=.8, text='12 cm')],
 people=[dict(x=470, h=242, skin=1, cloth=0, hair='cap', arm='folded', facing='right',
   label='Donal', role='moved it Thursday', says=["If it happened again, I'd move it on the "
     'Wednesday.', "I'd rather look foolish than lose a car."]),
  dict(x=970, h=240, skin=0, cloth=1, hair='long', arm='hold', facing='left',
   label='Eimear', role='14 Strand Road', says=["If I were you, I'd have gone earlier."])]),

"fig_a22_u01_p03_v09": dict(type='V9', kind='branch', height=700,
 title='Two conditionals, two distances',
 sub='The grammar is not about time. It is about how far away you think the thing is.',
 alt='A branching diagram from one situation into a first conditional for a real possibility and '
     'a second conditional for an imagined one.',
 root='if the water...',
 branches=[dict(label='FIRST: ...comes tonight, we WILL move',
     example='a real possibility - the forecast says so', colour='#2E6F5E'),
   dict(label='SECOND: ...came again, we WOULD move',
     example='imagined, unlikely, or just held at a distance', colour='#1F4E5F'),
   dict(label='SECOND, about the past: ...had come, we WOULD HAVE moved',
     example='and this one cannot be changed at all', colour='#8C6A9E'),
   dict(label='never: if it WOULD come',
     example='would lives in the result half, never in the if half', colour='#A8372E',
     dash='6 6')],
 rule='The past tense after if is not past time. It is distance. The less likely a thing is, the '
      'further back the verb goes.'),

"fig_a22_u01_p03_v09b": dict(type='V9', kind='ladder', height=720,
 title='From certain to impossible',
 sub='Five rungs. The second conditional lives on the middle three and is comfortable there.',
 alt='A ladder from a certain future at the top through likely and unlikely to impossible at the '
     'bottom, with the matching form on each rung.',
 top_label='certain', bottom_label='impossible now',
 steps=[dict(form='When it floods, we move the car', meaning='when, not if. It will happen'),
   dict(form='If it floods, we will move the car', meaning='a real possibility this winter'),
   dict(form='If it flooded, we would move the car', meaning='unlikely, or kept at a distance'),
   dict(form='If I were you, I would move it', meaning='impossible - I am not you'),
   dict(form='If I had known, I would have moved it', meaning='the past. Nothing can be done')],
 rule='were, not was, after if I. If I were you is the fixed form; if I was you is heard '
      'everywhere and is still the one to avoid in writing.'),

"fig_a22_u01_p04_v04": dict(type='V4', height=720,
 title='Thursday, and Saturday',
 sub='Learner A has the Thursday. Learner B has the Saturday. The same street.',
 alt='Two panels of the same street, one with cars parked and a shed closed, the other with '
     'water, sandbags and a boat on its side.',
 differences=7, prompt='Which two differences were decisions, and which five were weather?',
 left=dict(label='Thursday', art=[
   dict(kind='block', x=120, y=0, w=160, bh=90, colour='#D7D2C6'),
   dict(kind='person', x=320, y=0, h=112, skin=1, cloth=0),
   dict(kind='crate', x=410, y=0),
   dict(kind='label', x=300, y=200, text='one car moved, and people laughing',
        colour='#2E6F5E')]),
 right=dict(label='Saturday, 02.00', art=[
   dict(kind='block', x=120, y=0, w=160, bh=90, colour='#9AA7AE'),
   dict(kind='block', x=100, y=100, w=380, bh=24, colour='#1F4E5F'),
   dict(kind='cross', x=360, y=50),
   dict(kind='label', x=300, y=200, text='twelve centimetres, fourteen houses',
        colour='#1F4E5F')])),

"fig_a22_u01_p05_v05": dict(type='V5', height=1010,
 title='The policy summary',
 sub='Two pages reduced to one, by the insurer, and one line of it is in bold.',
 alt='A household insurance policy summary showing cover limits, excesses, exclusions and the '
     'time limits for claiming after a flood.',
 rows=[dict(t='org', text='HOUSEHOLD POLICY  -  SUMMARY OF COVER'),
   dict(t='kv', k='Policy', v='HH-4471-N', mono=True),
   dict(t='kv', k='Buildings cover', v='up to 300,000', mono=True),
   dict(t='kv', k='Contents cover', v='up to 40,000', mono=True),
   dict(t='rule'),
   dict(t='head', text='EXCESSES'),
   dict(t='grid', cols=['CAUSE', 'EXCESS', 'NOTE'],
     data=[['Storm damage', '350', 'wind, falling trees'],
           ['Escape of water', '350', 'burst pipes'],
           ['Flood', '2,500', 'rising water, any source'],
           ['Subsidence', '1,000', '-']]),
   dict(t='rule'),
   dict(t='head', text='NOT COVERED'),
   dict(t='para', text='Gradual damp. Items stored below ground level. Floor coverings laid '
     'less than 12 months before the claim. Garden structures, including sheds, and their '
     'contents.'),
   dict(t='rule'),
   dict(t='head', text='TIME LIMITS'),
   dict(t='kv', k='Notify us within', v='30 days', mono=True),
   dict(t='kv', k='We respond within', v='15 working days', mono=True),
   dict(t='kv', k='Alternative accommodation', v='up to 90 days', mono=True),
   dict(t='rule'),
   dict(t='sign', text='PRINTED IN BOLD, ON ITS OWN LINE:'),
   dict(t='para', text='"Flood cover may be withdrawn at renewal following a claim."')],
 callouts=[dict(at=0.26, text='350 for a tree. 2,500 for water'),
   dict(at=0.33, text='Seven times the excess, for the thing that happened'),
   dict(at=0.52, text='Sheds. And the sandbags were in a shed'),
   dict(at=0.56, text='Floor coverings under twelve months - hers was eight'),
   dict(at=0.78, text='Ninety days. The floor took eight months'),
   dict(at=0.94, text='The only line in bold, and the only one about next year')]),

"fig_a22_u01_p06_v03a": dict(type='V3', height=640,
 title='Four ways of putting it differently',
 sub='The same decision, offered at four distances.',
 alt='A four-panel strip of the same advice given as a plain statement, a preference, a '
     'hypothetical and an unspoken alternative.',
 axis_start='plain', axis_end='at a distance',
 panels=[dict(caption="MOVE IT - a plain instruction", art=[
     dict(kind='arrow', x=200, y=40),
     dict(kind='label', x=160, y=180, text='nothing to refuse', colour='#1F4E5F')]),
   dict(caption="I'D RATHER - a preference, not advice", art=[
     dict(kind='block', x=120, y=10, w=90, bh=50, colour='#2E6F5E'),
     dict(kind='block', x=240, y=10, w=90, bh=50, colour='#9AA7AE'),
     dict(kind='label', x=160, y=180, text='two options, one preferred', colour='#2E6F5E')]),
   dict(caption='IF I WERE YOU - advice at one remove', art=[
     dict(kind='person', x=130, y=0, h=110, skin=0, cloth=1),
     dict(kind='person', x=240, y=0, h=112, skin=1, cloth=0),
     dict(kind='label', x=160, y=185, text='in your place, I would', colour='#C86B2B')]),
   dict(caption='OTHERWISE - the thing you do not say', art=[
     dict(kind='cross', x=200, y=60),
     dict(kind='label', x=160, y=180, text='and you will be doing it in the dark',
       colour='#A8372E')])]),

"fig_a22_u01_p06_v04b": dict(type='V4', height=700,
 title='Will, and would',
 sub='Both are about the future. One of them expects to be right.',
 alt='Two panels comparing a first conditional drawn as a solid road and a second conditional '
     'drawn as a faded one.',
 differences=6, prompt='Which one would a weather forecast use?',
 left=dict(label='IF IT FLOODS, WE WILL MOVE', art=[
   dict(kind='block', x=140, y=0, w=240, bh=56, colour='#2E6F5E'),
   dict(kind='arrow', x=410, y=16),
   dict(kind='label', x=300, y=200, text='a real possibility, this winter', colour='#2E6F5E')]),
 right=dict(label='IF IT FLOODED, WE WOULD MOVE', art=[
   dict(kind='block', x=140, y=0, w=240, bh=56, colour='#9AA7AE'),
   dict(kind='gap', x=400, y=0, w=90, bh=56),
   dict(kind='label', x=300, y=200, text='imagined, or held at arm\'s length',
        colour='#9AA7AE')])),

"fig_a22_u01_p07_v10": dict(type='V10', kind='elision', height=640,
 title='The word that becomes a letter',
 sub='Would is almost never said in full. It survives as a d.',
 alt='Five phrases with would shown written and spoken, reduced to a d or a schwa in each.',
 pairs=[dict(written='I would', spoken='aɪd', dropped='woul', note='one letter is all that is left'),
   dict(written='would you', spoken='wədʒə', dropped='', note='would + you run together'),
   dict(written='I would have', spoken='aɪdəv', dropped='woul', note='never "would of" in writing'),
   dict(written='if I were you', spoken='ɪfaɪwəjə', dropped='', note='were /wə/, you /jə/'),
   dict(written='I WOULD do it', spoken='aɪˈwʊddu:ɪt', dropped='',
        note='full only when a but is coming')]),

"fig_a22_u01_p08_v06": dict(type='V6', kind='bar', height=780,
 title='Water height at each house, against floor level',
 sub='Fourteen houses on Strand Road, measured in March from the marks on the plaster.',
 alt='A bar chart of water depth above floor level at fourteen houses, showing the deepest at '
     'the harbour end and three houses untouched.',
 labels=['no. 2', 'no. 6', 'no. 10', 'no. 14', 'no. 18', 'no. 22'],
 ymin=0, ymax=40, fmt='{:,.0f}',
 series=[dict(name='water above floor (cm)', values=[31, 24, 17, 12, 4, 0], colour='#1F4E5F'),
   dict(name='floor above road (cm)', values=[8, 14, 19, 26, 34, 41], colour='#D9A441')],
 note='The two lines cross between number 14 and number 18. Every house below that crossing took '
      'water; every house above it did not.',
 warning='The deepest water is at the harbour end, nearest the old storm drain - not nearest '
         'the sea wall.'),

"fig_a22_u01_p09_v03b": dict(type='V3', height=640,
 title='Four minutes, four moves',
 sub='A short pitch has one number people remember. Choose it before you start.',
 alt='A four-panel strip of a funding pitch: the problem in one sentence, the amount, what it '
     'buys, and the consequence of refusing.',
 axis_start='minute 0', axis_end='minute 4',
 panels=[dict(caption='"Twelve centimetres got into fourteen houses."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=1, cloth=4, arm='point'),
     dict(kind='label', x=160, y=185, text='the problem, in one sentence', colour='#1F4E5F')]),
   dict(caption='"We\'re asking for 1.8 million."', art=[
     dict(kind='label', x=160, y=80, text='1.8 m', colour='#C86B2B'),
     dict(kind='label', x=160, y=185, text='the number, said early', colour='#C86B2B')]),
   dict(caption='"The wall, the survey, three years of upkeep."', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='label', x=160, y=190, text='what it buys', colour='#2E6F5E')]),
   dict(caption='"Without it we will be back, and it will be more than fourteen."', art=[
     dict(kind='cross', x=190, y=60),
     dict(kind='label', x=160, y=185, text='the consequence', colour='#A8372E')])]),

"fig_a22_u01_p10_v12": dict(type='V12', height=840,
 title='One night, and the eight months after it',
 sub='Half the class sees the night. Half sees the recovery. Rebuild the year by speaking.',
 alt='An infographic of a flood and its aftermath showing the night itself, the drying, the '
     'insurance timeline and the funding decision.',
 span=['Thu', 'September'], ticks=6,
 tick_labels=['Thu', 'Sat 02:00', 'Feb', 'Apr', 'Jul', 'Sep'],
 bands=[dict(name='The houses', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.14}, label='dry', colour='#2E6F5E'),
   dict(**{'from': 0.14, 'to': 0.30}, label='under water', colour='#1F4E5F'),
   dict(**{'from': 0.30, 'to': 0.92}, label='drying - eight months', colour='#C86B2B'),
   dict(**{'from': 0.92, 'to': 1.0}, label='floors going back down', colour='#D9A441')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.04, label='Donal moves the car, and is laughed at', colour='#2E6F5E'),
   dict(at=0.16, label='the drain reverses at about ten', colour='#A8372E'),
   dict(at=0.22, label='Sinead opens the hall', colour='#D9A441'),
   dict(at=0.46, label='claims notified - 30 day limit', colour='#8C6A9E'),
   dict(at=0.62, label='90 days of accommodation runs out', colour='#A8372E')]),
  dict(name='Houses still out', type='line',
   points=[(0.14, 14), (0.3, 14), (0.5, 11), (0.7, 6), (0.9, 2), (1.0, 1)], end_label='1'),
  dict(name='The money', type='flags', items=[
   dict(at=0.36, label='flood excess: 2,500 each'),
   dict(at=0.58, label='sheds not covered'),
   dict(at=0.78, label='1.8 million offered'),
   dict(at=0.97, label='and a survey nobody likes')])]),
}
