"""A2.2 Unit 2 - Nowhere Near Finished - fourteen figures, as data."""
FIGURES = {
"fig_a22_u02_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The hall and the slipway, September',
 sub='Ten signs of work. Two of them have not moved since March.',
 alt='A small town street with scaffolding on a hall, a skip, a contractor board, a generator, '
     'a stack of plasterboard and a temporary road surface.',
 sky='#DEE4E6', ground='#A2A6A4', ground_line=660,
 buildings=[dict(x=20, w=520, storeys=2, colour='#D6D1C4', label='the community hall'),
   dict(x=600, w=380, storeys=2, colour='#CCC8BC', label='the terrace'),
   dict(x=1040, w=540, storeys=1, colour='#D4CEBE', label='the boathouse')],
 props=[dict(kind='scaffold', x=200, y=660, s=1.15),
   dict(kind='hoarding', x=640, y=660, s=1.0),
   dict(kind='box', x=420, y=660, s=1.3), dict(kind='box', x=510, y=660, s=1.2),
   dict(kind='crate', x=900, y=660, s=1.1),
   dict(kind='van', x=1200, y=660, s=.95, colour='#C86B2B'),
   dict(kind='sign', x=120, y=660, s=.75, text='68%'),
   dict(kind='sign', x=1480, y=660, s=.75, text='1 APR')],
 people=[dict(x=330, y=660, h=86, skin=0, cloth=2, hair='bun', arm='point'),
   dict(x=570, y=660, h=85, skin=1, cloth=0, hair='cap', arm='hold'),
   dict(x=800, y=660, h=86, skin=0, cloth=1, hair='long', arm='down'),
   dict(x=1100, y=660, h=85, skin=1, cloth=4, hair='grey', arm='hold'),
   dict(x=1380, y=660, h=86, skin=2, cloth=3, hair='short', arm='raise')],
 names=[dict(x=330, t='Sinead, eleven phone calls'), dict(x=570, t='the contractor, four sites'),
   dict(x=800, t='Eimear, still drying'), dict(x=1100, t='Peadar, no boat'),
   dict(x=1380, t='Aoife, filming the scaffolding'), dict(x=120, t='the report says 68 per cent'),
   dict(x=1480, t='the original start date')],
 markers=[dict(x=330, y=548), dict(x=570, y=548), dict(x=800, y=548), dict(x=1100, y=548),
   dict(x=1380, y=548), dict(x=200, y=540), dict(x=420, y=606), dict(x=640, y=600),
   dict(x=120, y=592), dict(x=1480, y=592)]),

"fig_a22_u02_p01_v08": dict(type='V8', height=780,
 title='Why a job takes eight months',
 sub='Six stages. Only two of them are building work.',
 alt='A network from the flood through the survey, the appointment of a contractor, the '
     'scaffolding, the roof and the plasterboard, with the waiting marked on each link.',
 nodes={
  'flo': dict(x=170, y=400, short='1', name='The water', sub='14 January', colour='#1F4E5F'),
  'sur': dict(x=500, y=230, short='2', name='The survey', sub='a man looked, and left', colour='#9AA7AE'),
  'con': dict(x=500, y=570, short='3', name='The contractor', sub='appointed 9 March', colour='#C86B2B'),
  'roo': dict(x=880, y=400, short='4', name='The roof', sub='three men, four weeks', r=54, colour='#2E6F5E'),
  'pla': dict(x=1270, y=400, short='5', name='Plasterboard', sub='ordered June. Still ordered',
    r=54, colour='#A8372E')},
 edges=[dict(a='flo', b='sur', label='nineteen days', sw=5),
   dict(a='sur', b='con', label='five weeks, and no paper', sw=4, dash='5 5'),
   dict(a='con', b='roo', label='six weeks to the scaffolding', sw=5),
   dict(a='roo', b='pla', label='and then they moved to the school', sw=5),
   dict(a='flo', b='roo', label='the only finished thing', sw=3),
   dict(a='con', b='pla', label='supplier changed in July', sw=2, dash='6 6', colour='#9AA7AE')]),

"fig_a22_u02_p01_v02": dict(type='V2', height=780,
 title='The community hall, in section',
 sub='Four levels, four stages, and one of them has not been touched since March.',
 alt='A community hall drawn in section showing the roof, the window line, the main floor and '
     'the under-floor, each labelled with its state of repair.',
 floors=[dict(was='the roof', now='Done in June. Two ridge tiles missing', year='Jun',
     fill='#E6EFE9'),
   dict(was='the windows', now='Two of four. The other two are boarded', year='Aug',
     fill='#E4ECEF'),
   dict(was='the main floor', now='Not started. Waiting on plasterboard since June', year='-',
     fill='#EFE2DD'),
   dict(was='under the floor', now='Cleared 14 January by eleven volunteers in six hours',
     year='Jan', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Finished, according to the contractor'),
   dict(at=0.38, text='Half. And that half took seven weeks'),
   dict(at=0.62, text='Nothing has happened here since March'),
   dict(at=0.88, text='The fastest work of the whole year, and nobody was paid')]),

"fig_a22_u02_p02_v07": dict(type='V7', height=800,
 title='Eight months of it',
 sub='One of them has been phoning. One of them has four other sites.',
 alt='A hall manager and a contractor on a site, with speech bubbles contrasting the perfect '
     'simple and the perfect continuous.',
 bg='#E9ECEC',
 set=[dict(kind='scaffold', x=1180, y=680, s=.9), dict(kind='box', x=700, y=680, s=1.2)],
 people=[dict(x=470, h=242, skin=0, cloth=2, hair='bun', arm='point', facing='right',
   label='Sinead', role='runs the hall', says=["I've phoned him four times.",
     "I've been phoning him all week."]),
  dict(x=950, h=240, skin=1, cloth=0, hair='cap', arm='folded', facing='left',
   label='the contractor', role='four sites', says=["We've done the roof.",
     "We've been doing the roof since June."])]),

"fig_a22_u02_p03_v09": dict(type='V9', kind='mirror', height=660,
 title='The result, and the activity',
 sub='Same eight months. One form counts what is done; the other measures how long.',
 alt='Two parallel sentences compared, one present perfect simple with a number and one present '
     'perfect continuous with a duration.',
 active=dict(parts=[dict(w=1.0, role='agent', text='We'),
   dict(w=1.3, role='action', text="'ve done"),
   dict(w=1.3, role='affected', text='the roof - HOW MANY')]),
 passive=dict(parts=[dict(w=1.0, role='agent', text='We'),
   dict(w=1.6, role='action', text="'ve been doing"),
   dict(w=1.6, role='affected', text='the roof since June - HOW LONG')]),
 rule='How many? takes the simple. How long? takes the continuous. The continuous dislikes '
      'numbers: I have been phoning him four times does not work.'),

"fig_a22_u02_p03_v09b": dict(type='V9', kind='ladder', height=720,
 title='From a finished result to no end in sight',
 sub='Five sentences about the same hall. Only two of them say anything is finished.',
 alt='A ladder from a completed job at the bottom up through partial completion to an ongoing '
     'activity with no end stated.',
 top_label='no end in sight', bottom_label='finished',
 steps=[dict(form="We've been waiting since June", meaning='an activity, and it is still going'),
   dict(form="We've been doing the roof for eight months", meaning='how long, and still at it'),
   dict(form="We've finished two of the four windows", meaning='how many - half of a job'),
   dict(form="We've phoned him eleven times", meaning='how many - and it is a complaint'),
   dict(form="We've done the roof", meaning='a result. It is finished and you can see it')],
 rule='Some verbs have no continuous at all: know, believe, own, belong, cost, mean. I have '
      'known him for years, never I have been knowing him.'),

"fig_a22_u02_p04_v04": dict(type='V4', height=720,
 title='The door log, and the progress report',
 sub='Learner A has the log. Learner B has the report. They describe the same building.',
 alt='Two panels compared: a handwritten log on the back of a door and a printed contractor '
     'progress report with a percentage.',
 differences=7, prompt='Which three items do the two documents disagree about?',
 left=dict(label='the door log', art=[
   dict(kind='doc', x=200, y=0),
   dict(kind='person', x=360, y=0, h=112, skin=0, cloth=2),
   dict(kind='label', x=300, y=200, text='four hands, fifteen entries, no percentages',
        colour='#C86B2B')]),
 right=dict(label='the progress report', art=[
   dict(kind='doc', x=200, y=0),
   dict(kind='label', x=300, y=120, text='68%', colour='#1F4E5F'),
   dict(kind='label', x=300, y=200, text='one hand, one page, one number',
        colour='#1F4E5F')])),

"fig_a22_u02_p05_v05": dict(type='V5', height=1000,
 title="The contractor's progress report",
 sub='One page, one percentage, and a completion date that has moved four times.',
 alt='A contractor progress report listing work packages, their claimed completion status, the '
     'reason for delay and a revised completion date.',
 rows=[dict(t='org', text='CONLON BUILDING LTD  -  PROGRESS REPORT 6'),
   dict(t='kv', k='Site', v='Ballinmore Community Hall', mono=False),
   dict(t='kv', k='Period', v='1 August - 31 August', mono=False),
   dict(t='kv', k='Overall complete', v='68 %', mono=True),
   dict(t='rule'),
   dict(t='head', text='WORK PACKAGES'),
   dict(t='grid', cols=['PACKAGE', 'STATUS', '%'],
     data=[['Strip out and clear', 'complete', '100'],
           ['Roof', 'complete', '100'],
           ['Windows', 'in progress', '50'],
           ['Electrical first fix', 'complete', '100'],
           ['Plasterboard and skim', 'awaiting materials', '0'],
           ['Floor', 'not commenced', '0']]),
   dict(t='rule'),
   dict(t='head', text='DELAYS'),
   dict(t='para', text='Plasterboard delivery has been delayed by a change of supplier. This is '
     'outside the contractor\'s control. No extension of time is claimed at this stage.'),
   dict(t='rule'),
   dict(t='head', text='COMPLETION'),
   dict(t='kv', k='Original', v='30 June', mono=True),
   dict(t='kv', k='Revision 1', v='31 July', mono=True),
   dict(t='kv', k='Revision 2', v='30 September', mono=True),
   dict(t='kv', k='Revision 3 (this report)', v='30 November', mono=True),
   dict(t='rule'),
   dict(t='sign', text='FOOTER, IN SIX POINT TYPE:'),
   dict(t='para', text='"Percentages are by value of work, not by number of packages."')],
 callouts=[dict(at=0.17, text='Sixty-eight per cent, and two of six packages at zero'),
   dict(at=0.30, text='Complete - and the door log says daylight through the ridge'),
   dict(at=0.38, text='Fifty per cent is two windows of four'),
   dict(at=0.46, text='Complete, and the kitchen still has no power'),
   dict(at=0.70, text='Outside our control, and no extension claimed - read that twice'),
   dict(at=0.92, text='By value. The roof was the expensive bit')]),

"fig_a22_u02_p06_v03a": dict(type='V3', height=640,
 title='A point, a length, a frequency',
 sub='Three different questions, and English answers each with its own word.',
 alt='A four-panel strip distinguishing since and a point in time, for and a length, how often, '
     'and whether it has happened yet.',
 axis_start='January', axis_end='September',
 panels=[dict(caption='SINCE - a point you can name', art=[
     dict(kind='block', x=80, y=10, w=18, bh=110, colour='#1F4E5F'),
     dict(kind='arrow', x=210, y=50),
     dict(kind='label', x=160, y=180, text='since June / since the flood', colour='#1F4E5F')]),
   dict(caption='FOR - a length you can measure', art=[
     dict(kind='block', x=110, y=20, w=230, bh=42, colour='#2E6F5E'),
     dict(kind='label', x=160, y=180, text='for eight months / all this time',
       colour='#2E6F5E')]),
   dict(caption='ON AND OFF - how often, not how long', art=[
     dict(kind='block', x=100, y=20, w=50, bh=38, colour='#C86B2B'),
     dict(kind='gap', x=170, y=20, w=50, bh=38),
     dict(kind='block', x=240, y=20, w=50, bh=38, colour='#C86B2B'),
     dict(kind='label', x=160, y=180, text='constantly / day after day', colour='#C86B2B')]),
   dict(caption='YET - and has it happened?', art=[
     dict(kind='cross', x=200, y=60),
     dict(kind='label', x=160, y=180, text='still waiting / not yet', colour='#A8372E')])]),

"fig_a22_u02_p06_v04b": dict(type='V4', height=700,
 title='Four times, and all week',
 sub='Two complaints about the same contractor. Only one of them has a number in it.',
 alt='Two panels compared: a perfect simple sentence drawn as four separate marks and a perfect '
     'continuous sentence drawn as one unbroken band.',
 differences=6, prompt='Which one would you put in a letter, and which would you say out loud?',
 left=dict(label="I'VE PHONED HIM FOUR TIMES", art=[
   dict(kind='block', x=140, y=0, w=40, bh=56, colour='#1F4E5F'),
   dict(kind='block', x=210, y=0, w=40, bh=56, colour='#1F4E5F'),
   dict(kind='block', x=280, y=0, w=40, bh=56, colour='#1F4E5F'),
   dict(kind='block', x=350, y=0, w=40, bh=56, colour='#1F4E5F'),
   dict(kind='label', x=300, y=200, text='countable. A record', colour='#1F4E5F')]),
 right=dict(label="I'VE BEEN PHONING HIM ALL WEEK", art=[
   dict(kind='block', x=140, y=0, w=320, bh=56, colour='#C86B2B'),
   dict(kind='label', x=300, y=200, text='unbroken. A feeling', colour='#C86B2B')])),

"fig_a22_u02_p07_v10": dict(type='V10', kind='elision', height=640,
 title='The word in the middle',
 sub='Been is the quietest word in a perfect continuous, and it is not pronounced bean.',
 alt='Five perfect continuous phrases shown written and spoken, with been reduced to /bIn/ and '
     'have reduced to a v.',
 pairs=[dict(written='I have been waiting', spoken='aɪvbɪnˈweɪtɪŋ', dropped='ha',
     note='been is /bɪn/, never /biːn/'),
   dict(written='we have been at it', spoken='wiːvbɪnˈætɪt', dropped='ha',
     note='four words, two beats'),
   dict(written='they have been doing it', spoken='ðeɪvbɪnˈduːɪŋɪt', dropped='ha',
     note='have survives as a v'),
   dict(written="how long have you been", spoken='haʊlɒŋəvjəbɪn', dropped='',
     note='three weak syllables in a row'),
   dict(written="we've BEEN waiting", spoken='wiːvˈbiːnˈweɪtɪŋ', dropped='',
     note='full only when you are arguing')]),

"fig_a22_u02_p08_v06": dict(type='V6', kind='bar', height=780,
 title='Eight months, package by package',
 sub='Weeks spent working, against weeks spent waiting, on each part of the job.',
 alt='A bar chart comparing weeks of actual work with weeks of waiting for each work package, '
     'showing waiting far exceeding work on most packages.',
 labels=['strip out', 'survey', 'roof', 'windows', 'plasterboard', 'floor'],
 ymin=0, ymax=16, fmt='{:,.0f}',
 series=[dict(name='weeks working', values=[1, 0, 4, 7, 0, 0], colour='#2E6F5E'),
   dict(name='weeks waiting', values=[0, 5, 6, 2, 12, 12], colour='#A8372E')],
 note='Twelve weeks of work and thirty-seven weeks of waiting. The waiting is not on site and '
      'so it does not appear in any report.',
 warning='The report is honest: 68 per cent by value. The roof was the expensive package and '
         'the floor is the cheap one, which is why it is last.'),

"fig_a22_u02_p09_v03b": dict(type='V3', height=640,
 title='Quote, paraphrase, steal',
 sub='Changing the words does not make the idea yours.',
 alt='A four-panel strip showing a direct quotation with a name, a paraphrase with a name, an '
     'unattributed use, and an original conclusion.',
 axis_start='her words', axis_end='your words',
 panels=[dict(caption='QUOTE - her words, in marks, with her name', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='person', x=320, y=0, h=108, skin=2, cloth=3),
     dict(kind='label', x=160, y=190, text='Aoife Byrne said "..."', colour='#2E6F5E')]),
   dict(caption='PARAPHRASE - your words, her idea, her name', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='label', x=160, y=190, text='According to Aoife Byrne, ...', colour='#1F4E5F')]),
   dict(caption='STEAL - her idea, no name', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='cross', x=330, y=50),
     dict(kind='label', x=160, y=190, text='and rewriting it changes nothing',
       colour='#A8372E')]),
   dict(caption='YOUR OWN - and this is the only one that is yours', art=[
     dict(kind='person', x=180, y=0, h=112, skin=0, cloth=1, arm='point'),
     dict(kind='label', x=160, y=185, text='In my view, therefore...', colour='#D9A441')])]),

"fig_a22_u02_p10_v12": dict(type='V12', height=840,
 title='Eight months on the back of a door',
 sub='Half the class sees the log. Half sees the report. Rebuild the year by speaking.',
 alt='An infographic of a repair project from January to September showing work periods, waiting '
     'periods, revised completion dates and donations arriving.',
 span=['Jan', 'Sep'], ticks=6,
 tick_labels=['Jan', 'Mar', 'May', 'Jun', 'Aug', 'Sep'],
 bands=[dict(name='On site', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.06}, label='volunteers clear it', colour='#2E6F5E'),
   dict(**{'from': 0.06, 'to': 0.38}, label='nothing - survey, then waiting', colour='#E4E0D8'),
   dict(**{'from': 0.42, 'to': 0.60}, label='the roof', colour='#2E6F5E'),
   dict(**{'from': 0.62, 'to': 0.86}, label='two windows', colour='#D9A441'),
   dict(**{'from': 0.60, 'to': 1.0}, label='waiting for plasterboard', colour='#A8372E')]),
  dict(name='Dates promised', type='events', items=[
   dict(at=0.22, label='start 1 April', colour='#1F4E5F'),
   dict(at=0.52, label='finish 30 June', colour='#1F4E5F'),
   dict(at=0.66, label='revised to 31 July', colour='#C86B2B'),
   dict(at=0.80, label='revised to 30 September', colour='#C86B2B'),
   dict(at=0.97, label='revised to 30 November', colour='#A8372E')]),
  dict(name='Per cent complete, claimed', type='line',
   points=[(0.06, 8), (0.3, 12), (0.52, 44), (0.7, 58), (0.86, 68), (1.0, 68)],
   end_label='68'),
  dict(name='What the log says', type='flags', items=[
   dict(at=0.16, label='"Man came, looked, left. No paper yet"'),
   dict(at=0.46, label='"Roof is NOT done - you can see daylight"'),
   dict(at=0.74, label='"Plasterboard not delivered" x 3'),
   dict(at=0.98, label='"Eight months, and the roof is not finished"')])]),
}
