"""A2.2 Unit 3 - Who Was Warned, and When - fourteen figures, as data."""
FIGURES = {
"fig_a22_u03_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='Strand Road, 22.40, the night itself',
 sub='Nine things to find. Three of the people here already knew.',
 alt='A coastal street at night with a car being moved to the top road, a lit community hall, '
     'torches, a phone screen, the harbour wall and the tide line.',
 sky='#2E3A42', ground='#4A5057', ground_line=660,
 buildings=[dict(x=20, w=440, storeys=2, colour='#4F565C', label='the terrace'),
   dict(x=510, w=320, storeys=1, colour='#6B7A66', label='the hall - lights on'),
   dict(x=880, w=300, storeys=2, colour='#4A5157', label='9 Strand Road'),
   dict(x=1230, w=350, storeys=1, colour='#434A51', label='the harbour wall')],
 props=[dict(kind='van', x=1000, y=660, s=1.0, colour='#C86B2B'),
   dict(kind='box', x=300, y=660, s=1.1), dict(kind='crate', x=700, y=660, s=1.1),
   dict(kind='sign', x=120, y=660, s=.75, text='22:40'),
   dict(kind='sign', x=1420, y=660, s=.75, text='1.6 m')],
 people=[dict(x=230, y=660, h=86, skin=0, cloth=1, hair='long', arm='hold'),
   dict(x=420, y=660, h=85, skin=1, cloth=0, hair='cap', arm='point'),
   dict(x=620, y=660, h=86, skin=0, cloth=2, hair='bun', arm='raise'),
   dict(x=860, y=660, h=85, skin=1, cloth=4, hair='grey', arm='hold'),
   dict(x=1300, y=660, h=86, skin=2, cloth=3, hair='short', arm='hold')],
 names=[dict(x=230, t='Eimear - the drain in her yard'), dict(x=420, t='Donal - car already gone'),
   dict(x=620, t='Sinead - opening the hall'), dict(x=860, t='Peadar - watching the tide'),
   dict(x=1300, t='Aoife - filming, 22.40'), dict(x=120, t='the church clock'),
   dict(x=1420, t='the revised surge')],
 markers=[dict(x=230, y=548), dict(x=420, y=548), dict(x=620, y=548), dict(x=860, y=548),
   dict(x=1300, y=548), dict(x=120, y=592), dict(x=1420, y=592), dict(x=1000, y=600),
   dict(x=300, y=610)]),

"fig_a22_u03_p01_v08": dict(type='V8', height=780,
 title='What an inquiry is actually asking',
 sub='Five nodes. Only one of them is about what happened; the rest are about what was known.',
 alt='A network from the event through what was known, who was told, who decided and the finding '
     'of the inquiry, with the gap between knowing and telling marked.',
 nodes={
  'eve': dict(x=180, y=400, short='1', name='What happened', sub='the water, at 22.40', colour='#1F4E5F'),
  'kno': dict(x=520, y=230, short='2', name='What was known', sub='the forecast, at 13.40', colour='#D9A441'),
  'tol': dict(x=520, y=570, short='3', name='Who was told', sub='four people', colour='#C86B2B'),
  'dec': dict(x=900, y=400, short='4', name='Who decided', sub='and with what in front of them', r=54, colour='#8C6A9E'),
  'fin': dict(x=1290, y=400, short='5', name='The finding', sub='eleven pages on a drain', r=54, colour='#2E6F5E')},
 edges=[dict(a='kno', b='tol', label='nine hours, and four doors', sw=5),
   dict(a='kno', b='eve', label='and nobody connected the two', sw=3, dash='5 5'),
   dict(a='tol', b='dec', label='two laughed, one said nothing', sw=5),
   dict(a='eve', b='dec', label='by then it was already running', sw=5),
   dict(a='dec', b='fin', label='eight months and eleven pages', sw=5),
   dict(a='kno', b='fin', label='the chain failed at the council, not in the town', sw=2,
        dash='6 6', colour='#9AA7AE')]),

"fig_a22_u03_p01_v02": dict(type='V2', height=780,
 title='The harbour, in section',
 sub='Four levels. Everybody was watching the top one, and the water came from the third.',
 alt='A harbour drawn in section showing the wall, the quay, the old storm drain and the harbour '
     'bed, with the water level marked on each.',
 floors=[dict(was='the wall', now='1.9 m. Everybody watched this all night', year='1974',
     fill='#DCE6EA'),
   dict(was='the quay', now='The tide reached 1.6 m. The wall held, exactly as built', year='',
     fill='#E4ECEF'),
   dict(was='the old storm drain', now='Built 1961. Connects below the wall line', year='1961',
     fill='#EFE2DD'),
   dict(was='the harbour bed', now='Silted since the 1990s. Not surveyed since 1988', year='',
     fill='#E8E2D6')],
 callouts=[dict(at=0.12, text='The thing in every photograph that night'),
   dict(at=0.38, text='The wall did its job. That is the finding nobody expected'),
   dict(at=0.62, text='The water came up through here, below everything'),
   dict(at=0.88, text='Nobody had looked at this since 1988')]),

"fig_a22_u03_p02_v07": dict(type='V7', height=800,
 title='The order of the night',
 sub='Two witnesses who agree about every fact and disagree about the order.',
 alt='Two residents giving evidence, with speech bubbles contrasting the past simple and the '
     'past perfect.',
 bg='#E7EAEB',
 set=[dict(kind='table', x=700, y=680, s=1.4), dict(kind='doc', x=700, y=612)],
 people=[dict(x=470, h=242, skin=1, cloth=0, hair='cap', arm='hold', facing='right',
   label='Donal', role='submission 14', says=['The forecast changed on the Thursday.',
     'The forecast had changed before I moved the car.']),
  dict(x=970, h=240, skin=0, cloth=1, hair='long', arm='point', facing='left',
   label='Eimear', role='submission 15', says=['By the time we got there, it had already '
     'started.'])]),

"fig_a22_u03_p03_v09": dict(type='V9', kind='timeline', height=700,
 title='The past before the past',
 sub='Two events in the past. The earlier one takes had.',
 alt='A timeline showing a past-simple event and, before it, an earlier event drawn with had plus '
     'past participle.',
 now=0.92, axis_y=490,
 bands=[dict(type='before', lane=1, **{'from': 0.08, 'to': 0.22},
     label='EARLIER - past perfect', example='The forecast had changed at 13.40.'),
   dict(type='event', lane=3, **{'from': 0.40}, label='THE EVENT - past simple',
     example='He moved the car at 16.00.'),
   dict(type='before', lane=5, **{'from': 0.60, 'to': 0.74},
     label='AND BY THEN - past perfect again',
     example='By the time the hall opened, the water had reached the doors.')],
 rule='You do not need the past perfect when the sentence order is the event order. You do need '
      'it when you go backwards.'),

"fig_a22_u03_p03_v09b": dict(type='V9', kind='mirror', height=660,
 title='Forwards, and backwards',
 sub='The same two events, told in two directions. Only one of them needs had.',
 alt='Two parallel sentences compared, one telling two events in the order they happened and one '
     'telling them in reverse with the past perfect.',
 active=dict(parts=[dict(w=1.3, role='agent', text='He moved the car.'),
   dict(w=0.6, role='action', text='Then'),
   dict(w=1.3, role='affected', text='it flooded. (no had)')]),
 passive=dict(parts=[dict(w=1.2, role='affected', text='It flooded.'),
   dict(w=1.6, role='action', text='He HAD moved the car'),
   dict(w=1.0, role='agent', text='two days earlier.')]),
 rule='The words that invite the past perfect: by the time, already, before, until, once, '
      'previously, the night before, up to that point.'),

"fig_a22_u03_p04_v04": dict(type='V4', height=720,
 title='Thursday afternoon, and Saturday night',
 sub='Learner A has the Thursday. Learner B has the night. Both are the same street.',
 alt='Two panels of the same street, one in afternoon light with a car being moved and one at '
     'night with water and torches.',
 differences=7, prompt='Which three differences had already happened by the time of panel two?',
 left=dict(label='Thursday, 16.00', art=[
   dict(kind='block', x=120, y=0, w=160, bh=90, colour='#D7D2C6'),
   dict(kind='person', x=320, y=0, h=112, skin=1, cloth=0),
   dict(kind='arrow', x=400, y=30),
   dict(kind='label', x=300, y=200, text='one car going up the hill', colour='#2E6F5E')]),
 right=dict(label='Saturday, 22.40', art=[
   dict(kind='block', x=120, y=0, w=160, bh=90, colour='#5A6166'),
   dict(kind='block', x=100, y=100, w=380, bh=20, colour='#1F4E5F'),
   dict(kind='person', x=350, y=0, h=110, skin=0, cloth=2, arm='raise'),
   dict(kind='label', x=300, y=200, text='the hall lit, the drain already running',
        colour='#1F4E5F')])),

"fig_a22_u03_p05_v05": dict(type='V5', height=1010,
 title="The inquiry's timeline of the night",
 sub='Eighteen entries. Two of them say NO RECORD, and one time is disputed by forty minutes.',
 alt='An official inquiry timeline listing the forecast revision, warnings, the drain reversal, '
     'the hall opening and the first water, with sources and gaps.',
 rows=[dict(t='org', text='INDEPENDENT INQUIRY  -  AGREED TIMELINE, ANNEX B'),
   dict(t='grid', cols=['TIME', 'EVENT', 'SOURCE'],
     data=[['08.15', 'Forecast issued - surge 1.1 m', 'met service log'],
           ['13.40', 'Forecast revised - surge 1.6 m', 'met service log'],
           ['13.40', 'Revision sent to council duty phone', 'met service log'],
           ['--.--', 'Council duty officer reads revision', 'NO RECORD'],
           ['16.00', 'Vehicle moved to upper road', 'submission 14'],
           ['16.00-18.00', 'Four residents informed', 'submission 14'],
           ['--.--', 'Any council warning to residents', 'NO RECORD'],
           ['21.50 *', 'Yard drain reverses, 14 Strand Rd', 'submission 15'],
           ['22.40', 'Hall opened', 'hall log'],
           ['23.30', 'First water at door level', 'photographs']]),
   dict(t='rule'),
   dict(t='head', text='NOTE *'),
   dict(t='para', text='The 21.50 entry is disputed. The resident states "about ten". '
     'Photographic metadata gives 21.50. The difference is forty minutes and the inquiry has '
     'adopted the metadata.'),
   dict(t='rule'),
   dict(t='head', text='THE GAP'),
   dict(t='kv', k='Forecast revised', v='13.40', mono=True),
   dict(t='kv', k='First water', v='23.30', mono=True),
   dict(t='kv', k='Hours available', v='9 h 50 m', mono=True),
   dict(t='para', text='No official warning was issued to residents at any point in that '
     'period.')],
 callouts=[dict(at=0.17, text='Two forecasts. The second one is the whole inquiry'),
   dict(at=0.24, text='Sent at 13.40, to a phone'),
   dict(at=0.29, text='NO RECORD - and this is the finding'),
   dict(at=0.38, text='Two hours and twenty minutes later, one man moves a car'),
   dict(at=0.44, text='The only warning anybody received, and it came from a neighbour'),
   dict(at=0.88, text='Nine hours fifty, and nothing official in any of them')]),

"fig_a22_u03_p06_v03a": dict(type='V3', height=640,
 title='Earlier, at the time, and afterwards',
 sub='Four positions on one line, and each one has its own words.',
 alt='A four-panel strip placing an event earlier, at the moment, as a deadline already met, and '
     'afterwards.',
 axis_start='13.40', axis_end='March',
 panels=[dict(caption='PREVIOUSLY - and nobody connected it', art=[
     dict(kind='block', x=100, y=20, w=70, bh=48, colour='#9AA7AE'),
     dict(kind='label', x=160, y=180, text='the night before / previously', colour='#9AA7AE')]),
   dict(caption='BY THE TIME - the deadline was already met', art=[
     dict(kind='block', x=100, y=20, w=180, bh=48, colour='#1F4E5F'),
     dict(kind='cross', x=330, y=50),
     dict(kind='label', x=160, y=180, text='by the time / already', colour='#1F4E5F')]),
   dict(caption='AS SOON AS - the two touch', art=[
     dict(kind='block', x=140, y=20, w=90, bh=48, colour='#C86B2B'),
     dict(kind='block', x=250, y=20, w=90, bh=48, colour='#C86B2B'),
     dict(kind='label', x=160, y=180, text='as soon as / once / just', colour='#C86B2B')]),
   dict(caption='AFTERWARDS - and in hindsight', art=[
     dict(kind='arrow', x=220, y=40),
     dict(kind='label', x=160, y=180, text='afterwards / up to that point', colour='#2E6F5E')])]),

"fig_a22_u03_p06_v04b": dict(type='V4', height=700,
 title='BEFORE, and BY THE TIME',
 sub='Both put one thing earlier. One of them is a sequence; the other is a deadline.',
 alt='Two panels comparing two events in sequence and one event already completed when a second '
     'arrives.',
 differences=6, prompt='Which one tells you the first thing was finished?',
 left=dict(label='BEFORE - one, then the other', art=[
   dict(kind='block', x=130, y=0, w=110, bh=56, colour='#2E6F5E'),
   dict(kind='block', x=270, y=0, w=110, bh=56, colour='#1F4E5F'),
   dict(kind='label', x=300, y=200, text='he moved it before the forecast changed',
        colour='#2E6F5E')]),
 right=dict(label='BY THE TIME - a deadline, already met', art=[
   dict(kind='block', x=130, y=0, w=220, bh=56, colour='#1F4E5F'),
   dict(kind='tick', x=400, y=24),
   dict(kind='label', x=300, y=200, text='by the time it changed, he HAD moved it',
        colour='#1F4E5F')])),

"fig_a22_u03_p07_v10": dict(type='V10', kind='elision', height=640,
 title='The word that attaches itself',
 sub='Had almost never stands alone. It becomes a d on the end of the word before it.',
 alt='Five past perfect phrases shown written and spoken, with had reduced to a d or a schwa.',
 pairs=[dict(written='it had already started', spoken='ɪtədɔːlˈredɪd', dropped='ha',
     note="it'd - and most people do not hear a word at all"),
   dict(written='he had moved it', spoken='hiːdˈmuːvdɪt', dropped='ha', note="he'd, one syllable"),
   dict(written='they had gone', spoken='ðeɪdˈɡɒn', dropped='ha', note="they'd"),
   dict(written='I had known', spoken='aɪdˈnəʊn', dropped='ha', note="I'd - and never I would"),
   dict(written='he HAD moved it', spoken='hiːˈhædˈmuːvdɪt', dropped='',
        note='full only when somebody has said he did not')]),

"fig_a22_u03_p08_v06": dict(type='V6', kind='line', height=780,
 title='What was known, hour by hour',
 sub='From the forecast revision at 13.40 to the first water at 23.30.',
 alt='A line chart of how many people knew the forecast had been revised, hour by hour, '
     'alongside the rising tide.',
 labels=['13.40', '16.00', '18.00', '20.00', '21.50', '23.30'],
 ymin=0, ymax=20, fmt='{:,.0f}',
 series=[dict(name='people who knew', values=[1, 2, 6, 6, 8, 20], colour='#D9A441'),
   dict(name='surge (tenths of a metre)', values=[2, 5, 8, 11, 14, 16], colour='#1F4E5F')],
 note='One person knew for two hours and twenty minutes. Six knew for five and a half hours. '
      'Everybody knew when the water arrived.',
 warning='The council duty officer is not on this chart, because there is no record of when the '
         'revision was read.'),

"fig_a22_u03_p09_v03b": dict(type='V3', height=640,
 title='A favour, and what it leaves behind',
 sub='Four doors, four answers, and only one of them creates a debt.',
 alt='A four-panel strip of help offered and received, showing it dismissed, repaid, silenced '
     'and deferred.',
 axis_start='the night', axis_end='eight months on',
 panels=[dict(caption='"You\'d have done the same."', art=[
     dict(kind='person', x=130, y=0, h=112, skin=0, cloth=2, arm='point'),
     dict(kind='person', x=250, y=0, h=110, skin=1, cloth=0),
     dict(kind='label', x=160, y=185, text='dismissed - and that is the gift',
       colour='#2E6F5E')]),
   dict(caption='"I\'ll pay you back."', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='label', x=160, y=190, text='a debt, named, and in some places an insult',
       colour='#C86B2B')]),
   dict(caption='"Say nothing about it."', art=[
     dict(kind='person', x=180, y=0, h=112, skin=1, cloth=4),
     dict(kind='label', x=160, y=185, text='closed. Do not raise it again', colour='#8C6A9E')]),
   dict(caption='"We\'ll have you over when the kitchen\'s done."', art=[
     dict(kind='tick', x=190, y=60),
     dict(kind='label', x=160, y=185, text='deferred - and eight months later, still owed',
       colour='#D9A441')])]),

"fig_a22_u03_p10_v12": dict(type='V12', height=840,
 title='Nine hours and fifty minutes',
 sub='Half the class sees the Thursday. Half sees the night. Rebuild the order by speaking.',
 alt='An infographic of one night showing the forecast revision, the warnings, the drain, the '
     'hall opening and the first water, with what each person knew.',
 span=['08.15', '23.30'], ticks=6,
 tick_labels=['08.15', '13.40', '16.00', '20.00', '21.50', '23.30'],
 bands=[dict(name='What the council had', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.36}, label='the 1.1 m forecast', colour='#9AA7AE'),
   dict(**{'from': 0.36, 'to': 1.0}, label='the 1.6 m revision, on a duty phone',
     colour='#A8372E')]),
  dict(name='What the town had', type='bars', items=[
   dict(**{'from': 0.52, 'to': 0.64}, label='one neighbour, four doors', colour='#C86B2B'),
   dict(**{'from': 0.64, 'to': 0.90}, label='nothing new', colour='#E4E0D8'),
   dict(**{'from': 0.90, 'to': 1.0}, label='the drain, and then everybody', colour='#1F4E5F')]),
  dict(name='Surge, tenths of a metre', type='line',
   points=[(0, 1), (0.36, 2), (0.52, 5), (0.76, 11), (0.90, 14), (1.0, 16)], end_label='1.6 m'),
  dict(name='The record', type='flags', items=[
   dict(at=0.38, label='revision sent to the duty phone'),
   dict(at=0.46, label='NO RECORD that it was read'),
   dict(at=0.62, label='four told. Two laughed. One said nothing'),
   dict(at=0.94, label='no official warning in nine hours fifty')])]),
}
