"""A2.2 Unit 4 - Forty Minutes Apart - fourteen figures, as data."""
FIGURES = {
"fig_a22_u04_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The hall, the morning the report came out',
 sub='Eight sources in this picture. Two of them are the same source twice.',
 alt='A community hall on the morning a report is published, with a noticeboard, a journalist '
     'with a notebook, a phone recording, a printed statement and a television screen.',
 sky='#E0E5E6', ground='#A0A5A4', ground_line=660,
 buildings=[dict(x=20, w=560, storeys=2, colour='#D6D1C4', label='the community hall'),
   dict(x=640, w=380, storeys=2, colour='#CCC7BA', label='the shop and the post office'),
   dict(x=1080, w=500, storeys=3, colour='#C5C0B4', label='the terrace')],
 props=[dict(kind='hoarding', x=300, y=660, s=1.0),
   dict(kind='table', x=760, y=660, s=1.2),
   dict(kind='box', x=1140, y=660, s=1.2), dict(kind='crate', x=1240, y=660, s=1.1),
   dict(kind='van', x=1420, y=660, s=.9, colour='#8C6A9E'),
   dict(kind='sign', x=120, y=660, s=.75, text='23:30'),
   dict(kind='sign', x=620, y=660, s=.7, text='ANNEX C')],
 people=[dict(x=230, y=660, h=86, skin=0, cloth=1, hair='long', arm='hold'),
   dict(x=430, y=660, h=85, skin=1, cloth=0, hair='cap', arm='folded'),
   dict(x=700, y=660, h=86, skin=0, cloth=2, hair='bun', arm='point'),
   dict(x=960, y=660, h=85, skin=2, cloth=3, hair='short', arm='hold'),
   dict(x=1320, y=660, h=86, skin=1, cloth=4, hair='grey', arm='down')],
 names=[dict(x=230, t='Eimear - "about eleven"'), dict(x=430, t='Donal - "half past"'),
   dict(x=700, t='Sinead - "when the hall filled"'), dict(x=960, t='the journalist, notebook'),
   dict(x=1320, t='Peadar, reading page four'), dict(x=120, t='the adopted time'),
   dict(x=620, t='the annex nobody quotes')],
 markers=[dict(x=230, y=548), dict(x=430, y=548), dict(x=700, y=548), dict(x=960, y=548),
   dict(x=1320, y=548), dict(x=120, y=592), dict(x=620, y=596), dict(x=300, y=606)]),

"fig_a22_u04_p01_v08": dict(type='V8', height=780,
 title='How a claim becomes a fact',
 sub='Five stages. It can stop being checked at any of them, and usually stops at three.',
 alt='A network from a witness through a journalist, an editor, a headline and a reader, with '
     'the checking shown as links that can be skipped.',
 nodes={
  'wit': dict(x=180, y=400, short='1', name='The witness', sub='the best instrument they had', colour='#2E6F5E'),
  'jou': dict(x=520, y=230, short='2', name='The journalist', sub='notebook, word for word', colour='#1F4E5F'),
  'edi': dict(x=520, y=570, short='3', name='The editor', sub='and the headline', colour='#C86B2B'),
  'hea': dict(x=900, y=400, short='4', name='The published line', sub='one verb does the work', r=54, colour='#8C6A9E'),
  'rea': dict(x=1290, y=400, short='5', name='The reader', sub='who has only this', r=54, colour='#D9A441')},
 edges=[dict(a='wit', b='jou', label='said, quoted, recorded', sw=5),
   dict(a='jou', b='edi', label='filed, with the annex attached', sw=5),
   dict(a='edi', b='hea', label='and the verb is chosen here', sw=5),
   dict(a='hea', b='rea', label='and this is all most people see', sw=5),
   dict(a='jou', b='hea', label='when there is no time to check', sw=3, dash='5 5'),
   dict(a='wit', b='rea', label='the correction, page four, eleven days later', sw=2,
        dash='6 6', colour='#9AA7AE')]),

"fig_a22_u04_p01_v02": dict(type='V2', height=780,
 title='The newsroom, in section',
 sub='Four levels. A claim becomes a fact on the third one, and nobody there was at the flood.',
 alt='A newsroom drawn in section with the reporter desk, the sub-editors, the editor and the '
     'front page, each labelled with the decision made there.',
 floors=[dict(was='the front page', now='One headline. Six words. Chosen last', year='',
     fill='#EFE2DD'),
   dict(was="the editor's desk", now='Where the reporting verb is changed', year='',
     fill='#E4ECEF'),
   dict(was='the sub-editors', now='Length cut by a third. Annex C goes first', year='',
     fill='#F6F0E4'),
   dict(was='the reporter', now='Notebook, recording, the full 48 pages', year='',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='The only part most readers ever meet'),
   dict(at=0.38, text='said becomes claimed in one keystroke'),
   dict(at=0.62, text='The annex is always the first thing cut'),
   dict(at=0.88, text='The only level with the whole document on it')]),

"fig_a22_u04_p02_v07": dict(type='V7', height=800,
 title='Three times, one night',
 sub='Two of them are certain. Neither of them checked the same thing.',
 alt='Two residents talking outside a hall, with speech bubbles showing direct speech and the '
     'same words reported.',
 bg='#E9EBEB',
 set=[dict(kind='table', x=700, y=680, s=1.3), dict(kind='doc', x=700, y=612)],
 people=[dict(x=470, h=242, skin=0, cloth=1, hair='long', arm='hold', facing='right',
   label='Eimear', role='checked the clock', says=['"The water was at the door at eleven."']),
  dict(x=970, h=240, skin=1, cloth=0, hair='cap', arm='point', facing='left',
   label='Donal', role='heard the radio', says=['She said the water was at the door at eleven.',
     'He insisted it was half past.'])]),

"fig_a22_u04_p03_v09": dict(type='V9', kind='mirror', height=660,
 title='The words, and the report of them',
 sub='Everything steps one back: the tense, the pronoun, and the time word.',
 alt='Two parallel sentences compared, one in direct speech and one reported, with the shifted '
     'elements highlighted.',
 active=dict(parts=[dict(w=0.7, role='agent', text='"I'),
   dict(w=1.1, role='action', text='HAVE checked'),
   dict(w=1.2, role='affected', text='it NOW."')]),
 passive=dict(parts=[dict(w=1.2, role='agent', text='She said'),
   dict(w=1.2, role='action', text='SHE HAD checked'),
   dict(w=1.2, role='affected', text='it THEN.')]),
 rule='say that - never say somebody that. tell somebody that - never tell that. And no shift is '
      'needed when the thing is still true: she said the drain IS still blocked.'),

"fig_a22_u04_p03_v09b": dict(type='V9', kind='ladder', height=720,
 title='From flat to loaded',
 sub='Five reporting verbs. Only the bottom one leaves the reader free.',
 alt='A ladder of reporting verbs from said at the bottom through added and insisted up to '
     'admitted and claimed, with what each one implies.',
 top_label='the reader has been told what to think', bottom_label='flat',
 steps=[dict(form='She CLAIMED she had checked', meaning='and I do not believe her'),
   dict(form='She ADMITTED she had checked', meaning='and it was somehow against her interest'),
   dict(form='She INSISTED she had checked', meaning='and somebody had pushed back'),
   dict(form='She ADDED that she had checked', meaning='and it came after something else'),
   dict(form='She SAID she had checked', meaning='and nothing else at all')],
 rule='The reporting verb is the cheapest place in a sentence to hide an opinion, which is why '
      'it is the first thing an editor changes.'),

"fig_a22_u04_p04_v04": dict(type='V4', height=720,
 title='The report, and the article',
 sub='Learner A has section 4. Learner B has the newspaper. Same night, same three people.',
 alt='Two panels compared: a numbered official report page and a newspaper page with a headline '
     'and a photograph.',
 differences=7, prompt='Which three of the differences are verbs?',
 left=dict(label='the report, section 4', art=[
   dict(kind='doc', x=200, y=0),
   dict(kind='label', x=300, y=120, text='4.1 - 4.6', colour='#1F4E5F'),
   dict(kind='label', x=300, y=200, text='six paragraphs, one verb: said', colour='#1F4E5F')]),
 right=dict(label='the article', art=[
   dict(kind='doc', x=200, y=0),
   dict(kind='person', x=370, y=0, h=112, skin=2, cloth=3),
   dict(kind='label', x=300, y=200, text='one headline, three different verbs',
        colour='#A8372E')])),

"fig_a22_u04_p05_v05": dict(type='V5', height=1010,
 title='The newspaper article',
 sub='Four hundred words about a six-paragraph section, and paragraph 4.6 is not in it.',
 alt='A newspaper article about an inquiry section, showing the headline, the quoted paragraphs, '
     'the reporting verbs used for each witness and what was left out.',
 rows=[dict(t='org', text='THE WESTERN HERALD  -  PAGE 1'),
   dict(t='head', text='HEADLINE'),
   dict(t='para', text='"WITNESSES CONTRADICT EACH OTHER OVER FLOOD TIMING"'),
   dict(t='rule'),
   dict(t='head', text='WHAT IT QUOTES'),
   dict(t='grid', cols=['PARAGRAPH', 'QUOTED?', 'VERB USED'],
     data=[['4.1 - times differ by 40 min', 'yes', 'the report states'],
           ['4.2 - Resident A, clock', 'yes', 'A claims'],
           ['4.3 - Resident B, radio', 'yes', 'B insists'],
           ['4.4 - Resident C, the hall', 'yes', 'C admits'],
           ['4.5 - metadata adopted', 'yes', 'the inquiry has settled on'],
           ['4.6 - all accounts honest', 'NO', '-']]),
   dict(t='rule'),
   dict(t='head', text='ONE SENTENCE WITH NO SOURCE'),
   dict(t='para', text='"The inquiry is understood to have found the residents\' evidence of '
     'limited value." No paragraph of the report says this.'),
   dict(t='rule'),
   dict(t='head', text='THE CORRECTION, ELEVEN DAYS LATER'),
   dict(t='kv', k='Page', v='4, foot', mono=True),
   dict(t='kv', k='Words', v='31', mono=True),
   dict(t='rule'),
   dict(t='sign', text='THE CORRECTION, IN FULL:'),
   dict(t='para', text='"Our report of the 14th stated that the inquiry had found residents\' '
     'evidence to be of limited value. The inquiry made no such finding. We apologise."')],
 callouts=[dict(at=0.09, text='Six words, and all of them are true'),
   dict(at=0.30, text='claims, insists, admits - three people, three verdicts'),
   dict(at=0.44, text='The one paragraph that defends them is the one left out'),
   dict(at=0.62, text='"is understood to have" - the phrase with no source behind it'),
   dict(at=0.78, text='Thirty-one words, page four, eleven days'),
   dict(at=0.93, text='Accurate, complete, and read by almost nobody')]),

"fig_a22_u04_p06_v03a": dict(type='V3', height=640,
 title='The same claim, four verbs',
 sub='Nothing else changes. The reader ends up in four different places.',
 alt='A four-panel strip of one sentence reported with said, added, insisted and claimed, with '
     'what each implies.',
 axis_start='flat', axis_end='loaded',
 panels=[dict(caption='SHE SAID - nothing added', art=[
     dict(kind='block', x=140, y=20, w=180, bh=50, colour='#2E6F5E'),
     dict(kind='label', x=160, y=180, text='say / tell / state', colour='#2E6F5E')]),
   dict(caption='SHE ADDED - and something came first', art=[
     dict(kind='block', x=110, y=20, w=90, bh=50, colour='#9AA7AE'),
     dict(kind='block', x=220, y=20, w=110, bh=50, colour='#1F4E5F'),
     dict(kind='label', x=160, y=180, text='add / go on to say / mention', colour='#1F4E5F')]),
   dict(caption='SHE INSISTED - and somebody pushed back', art=[
     dict(kind='person', x=120, y=0, h=110, skin=0, cloth=1),
     dict(kind='person', x=240, y=0, h=112, skin=1, cloth=0, arm='point'),
     dict(kind='label', x=160, y=185, text='insist / repeat', colour='#C86B2B')]),
   dict(caption='SHE CLAIMED - and you now doubt her', art=[
     dict(kind='cross', x=200, y=60),
     dict(kind='label', x=160, y=180, text='claim / admit / reveal', colour='#A8372E')])]),

"fig_a22_u04_p06_v04b": dict(type='V4', height=700,
 title='SAY, and TELL',
 sub='Two verbs that mean nearly the same and take completely different shapes.',
 alt='Two panels comparing say that with no object and tell somebody that with an object, each '
     'with its wrong version crossed out.',
 differences=6, prompt='Which one needs a person after it, always?',
 left=dict(label='SAY (that)', art=[
   dict(kind='block', x=150, y=0, w=110, bh=54, colour='#2E6F5E'),
   dict(kind='gap', x=280, y=0, w=90, bh=54),
   dict(kind='label', x=300, y=200, text='she said that... - never she said me',
        colour='#2E6F5E')]),
 right=dict(label='TELL somebody (that)', art=[
   dict(kind='block', x=130, y=0, w=100, bh=54, colour='#1F4E5F'),
   dict(kind='person', x=270, y=0, h=108, skin=0, cloth=2),
   dict(kind='label', x=300, y=200, text='she told me that... - never she told that',
        colour='#1F4E5F')])),

"fig_a22_u04_p07_v10": dict(type='V10', kind='stress', height=700,
 title='Where the stress goes when you report',
 sub='A flat report leaves the reporting verb alone. Stress it and you have taken a side.',
 alt='Five reported sentences with the stressed syllables drawn as large dots, showing how '
     'stressing the reporting verb adds doubt.',
 items=[dict(syllables=['she', 'said', "she'd", 'CHECKED', 'it'], strong=[3],
     note='flat - the content is the news'),
   dict(syllables=['she', 'SAID', "she'd", 'checked', 'it'], strong=[1],
     note='loaded - and I am not sure I believe her'),
   dict(syllables=['he', 'in', 'SIST', 'ed', 'it', 'was', 'HALF', 'past'], strong=[2, 6],
     note='the verb already carries it; stress adds more'),
   dict(syllables=['ac', 'CORD', 'ing', 'to', 'the', 'in', 'QUIR', 'y'], strong=[1, 6],
     note='the source, named and stressed'),
   dict(syllables=['she', 'told', 'me', 'she', 'had', 'CHECKED'], strong=[5],
     note='told me, unstressed, and the fact arrives last')]),

"fig_a22_u04_p08_v06": dict(type='V6', kind='bar', height=780,
 title='Each account, its instrument, and that instrument\'s error',
 sub='Three residents, three ways of knowing the time, measured afterwards.',
 alt='A bar chart of the time each resident gave against the true time, with the error of each '
     'instrument shown.',
 labels=['A: kitchen clock', 'B: radio programme', 'C: hall filling', 'metadata'],
 ymin=0, ymax=40, fmt='{:,.0f}',
 series=[dict(name='minutes from 23.30', values=[30, 0, 5, 0], colour='#C86B2B'),
   dict(name='error in the instrument', values=[11, 15, 5, 0], colour='#1F4E5F')],
 note='Resident B gave the closest time and had the largest instrument error. Resident A gave '
      'the furthest time and had checked an actual clock.',
 warning='Being right and being careful are not the same thing here, and a report that only '
         'prints the times makes the careful one look worst.'),

"fig_a22_u04_p09_v03b": dict(type='V3', height=640,
 title='A safety brief in four moves',
 sub='Four minutes before anybody picks anything up. The last move is the one that gets skipped.',
 alt='A four-panel strip of a safety brief: the task, the hazard, the equipment and who has the '
     'authority to stop the work.',
 axis_start='minute 0', axis_end='minute 4',
 panels=[dict(caption='"We\'re clearing the ground floor and nothing above it."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=0, cloth=2, arm='point'),
     dict(kind='label', x=160, y=185, text='the task, and its edge', colour='#1F4E5F')]),
   dict(caption='"The floor is soft at the back. Two people have gone through it."', art=[
     dict(kind='cross', x=190, y=60),
     dict(kind='label', x=160, y=185, text='the hazard, with evidence', colour='#A8372E')]),
   dict(caption='"Boots, gloves, and nobody in shorts."', art=[
     dict(kind='box', x=190, y=10, s=1.2),
     dict(kind='label', x=160, y=190, text='the equipment', colour='#C86B2B')]),
   dict(caption='"If you think it\'s unsafe, you say stop. Not me. You."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=1, cloth=0, arm='raise'),
     dict(kind='label', x=160, y=185, text='who stops it - and it is a name', colour='#2E6F5E')])]),

"fig_a22_u04_p10_v12": dict(type='V12', height=840,
 title='One section, two documents, one correction',
 sub='Half the class sees the report. Half sees the article. Rebuild what was said by speaking.',
 alt='An infographic following one paragraph of an inquiry report into a newspaper, through the '
     'headline and the omission to the correction.',
 span=['the night', 'day 11'], ticks=6,
 tick_labels=['the night', 'evidence', 'report', 'page 1', 'page 4', 'day 11'],
 bands=[dict(name='The three accounts', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.30}, label='three times, forty minutes apart', colour='#C86B2B'),
   dict(**{'from': 0.30, 'to': 0.56}, label='all three accepted as honest', colour='#2E6F5E'),
   dict(**{'from': 0.56, 'to': 1.0}, label='claims, insists, admits', colour='#A8372E')]),
  dict(name='What happened to 4.6', type='events', items=[
   dict(at=0.34, label='written: "we do not regard any account as unreliable"',
     colour='#2E6F5E'),
   dict(at=0.52, label='filed with the annex attached', colour='#1F4E5F'),
   dict(at=0.62, label='cut for length', colour='#C86B2B'),
   dict(at=0.70, label='headline written', colour='#A8372E'),
   dict(at=0.98, label='correction, 31 words, page four', colour='#9AA7AE')]),
  dict(name='Readers reached', type='line',
   points=[(0.3, 0), (0.5, 40), (0.7, 9000), (0.8, 9000), (0.9, 900), (1.0, 900)],
   end_label='≈900'),
  dict(name='The verbs', type='flags', items=[
   dict(at=0.36, label='the report uses said, six times'),
   dict(at=0.66, label='the article uses three different verbs'),
   dict(at=0.84, label='"is understood to have" - no source'),
   dict(at=0.99, label='"The inquiry made no such finding"')])]),
}
