"""A2.2 Unit 6 - Two Miles Out, and Empty - fourteen figures, as data."""
FIGURES = {
"fig_a22_u06_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The pier, the Tuesday',
 sub='Nine things to find. Four of them are evidence of something.',
 alt='A small harbour pier with moorings, a boat on a trailer, an empty mooring buoy, a coil of '
     'rope, a fuel can, a weather board and a coastguard notice.',
 sky='#D9E0E4', ground='#96A0A4', ground_line=660,
 buildings=[dict(x=20, w=400, storeys=1, colour='#CFCBBE', label='the boathouse'),
   dict(x=480, w=320, storeys=2, colour='#C7C2B6', label='the coastguard station'),
   dict(x=870, w=300, storeys=1, colour='#D2CCBC', label="Peadar's shed"),
   dict(x=1230, w=350, storeys=2, colour='#BFBAAE', label='the terrace')],
 props=[dict(kind='crate', x=220, y=660, s=1.1), dict(kind='crate', x=300, y=660, s=1.1),
   dict(kind='box', x=620, y=660, s=1.2), dict(kind='table', x=980, y=660, s=1.2),
   dict(kind='van', x=1380, y=660, s=.9, colour='#2E6F5E'),
   dict(kind='sign', x=120, y=660, s=.75, text='2 mi'),
   dict(kind='sign', x=450, y=660, s=.7, text='F 6'),
   dict(kind='sign', x=840, y=660, s=.7, text='EMPTY')],
 people=[dict(x=170, y=660, h=86, skin=1, cloth=4, hair='grey', arm='hold'),
   dict(x=420, y=660, h=85, skin=0, cloth=1, hair='long', arm='point'),
   dict(x=700, y=660, h=86, skin=2, cloth=3, hair='cap', arm='folded'),
   dict(x=940, y=660, h=85, skin=0, cloth=2, hair='bun', arm='down'),
   dict(x=1300, y=660, h=86, skin=1, cloth=0, hair='short', arm='hold')],
 names=[dict(x=170, t='Mossie - "it must have broken"'),
   dict(x=420, t='the insurance assessor'), dict(x=700, t='the coastguard officer'),
   dict(x=940, t='Peadar, who owns her'), dict(x=1300, t='Donal, who coiled rope for forty years'),
   dict(x=120, t='where it was found'), dict(x=840, t='the mooring')],
 markers=[dict(x=170, y=548), dict(x=420, y=548), dict(x=700, y=548), dict(x=940, y=548),
   dict(x=1300, y=548), dict(x=120, y=592), dict(x=450, y=596), dict(x=840, y=596),
   dict(x=220, y=610)]),

"fig_a22_u06_p01_v08": dict(type='V8', height=780,
 title='One boat, three roads, one form',
 sub='Five nodes. Two of the roads are closed by physical evidence and the form has no box for '
     'the third.',
 alt='A network from the empty boat through three explanations to the insurance form, with the '
     'evidence that closes each road marked on the links.',
 nodes={
  'boa': dict(x=170, y=400, short='1', name='The boat', sub='two miles out, hatch open', colour='#1F4E5F'),
  'moo': dict(x=510, y=200, short='2', name='Mooring failure', sub='the rope says no', colour='#A8372E'),
  'eng': dict(x=510, y=400, short='3', name='Engine failure', sub='the tank says unlikely', colour='#C86B2B'),
  'own': dict(x=510, y=600, short='4', name='He untied it', sub='the lifejacket says no', colour='#8C6A9E'),
  'frm': dict(x=1120, y=400, short='5', name='The form', sub='one box, three amounts', r=54, colour='#D9A441')},
 edges=[dict(a='boa', b='moo', label='what Mossie said at nine', sw=4, dash='5 5'),
   dict(a='boa', b='eng', label='possible, and nobody has looked', sw=5),
   dict(a='boa', b='own', label='fits the rope, fits nothing else', sw=5),
   dict(a='moo', b='frm', label='pays 18,000', sw=5),
   dict(a='eng', b='frm', label='pays 18,000', sw=5),
   dict(a='own', b='frm', label='no box at all', sw=2, dash='6 6', colour='#9AA7AE')]),

"fig_a22_u06_p01_v02": dict(type='V2', height=780,
 title='The boat, in section',
 sub='Four levels, four clues, and the one on the third level closes a road.',
 alt='A small fishing boat drawn in section showing the wheelhouse, the deck, the cabin below '
     'and the bilge, each labelled with what was found there.',
 floors=[dict(was='the wheelhouse', now='Radio off at the set, not broken. Nobody called',
     year='', fill='#E4ECEF'),
   dict(was='the deck', now='A coil of rope, coiled properly, and a fuel can', year='',
     fill='#F6F0E4'),
   dict(was='the cabin', now='Hatch open. Nothing disturbed. No lifejacket', year='',
     fill='#EFE2DD'),
   dict(was='the bilge', now='Dry. So she had not been taking water', year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Off at the set. That takes a hand'),
   dict(at=0.38, text='Coiled by somebody who coils rope for a living'),
   dict(at=0.62, text='Open from the inside, and the lifejacket is in the shed'),
   dict(at=0.88, text='Dry, which rules out the simplest story of all')]),

"fig_a22_u06_p02_v07": dict(type='V7', height=800,
 title='Three explanations',
 sub='One of them was being said before anybody had looked at the rope.',
 alt='A coastguard officer and a neighbour on a pier discussing what happened, with speech '
     'bubbles using modals of deduction.',
 bg='#E6EAEC',
 set=[dict(kind='crate', x=680, y=680, s=1.2), dict(kind='box', x=1300, y=680, s=1.1)],
 people=[dict(x=470, h=242, skin=2, cloth=3, hair='cap', arm='hold', facing='right',
   label='the coastguard', role='found it at 11.30', says=['It might have been the current.',
     "He can't have taken it out - his lifejacket's in the shed."]),
  dict(x=970, h=240, skin=1, cloth=4, hair='grey', arm='point', facing='left',
   label='Mossie', role='since nine that morning', says=['The rope must have broken.'])]),

"fig_a22_u06_p03_v09": dict(type='V9', kind='ladder', height=720,
 title='How sure are you, and why',
 sub='Five levels. Each one has to be bought with a piece of evidence.',
 alt='A ladder of deduction from almost certainly true at the top down to ruled out at the '
     'bottom, with the evidence for each level.',
 top_label='almost certainly true', bottom_label='ruled out',
 steps=[dict(form='It MUST have been untied', meaning='the turns are still in the rope'),
   dict(form='It COULD have been the engine', meaning='possible, and nobody has looked'),
   dict(form='It MIGHT have been the current', meaning='the tide turned at two'),
   dict(form='It MIGHT NOT have been the current', meaning='weaker than can\'t - still open'),
   dict(form="He CAN'T have been aboard", meaning='the lifejacket is on the hook')],
 rule="The negative of must is can't, not mustn't. Mustn't is about rules; can't have is about "
      'evidence.'),

"fig_a22_u06_p03_v09b": dict(type='V9', kind='branch', height=700,
 title='Three roads from one empty boat',
 sub='Each road is closed or opened by one physical thing.',
 alt='A branching diagram from an empty boat into mooring failure, engine failure and the owner '
     'untying it, with the evidence on each branch.',
 root='the boat was found...',
 branches=[dict(label='...because the mooring failed',
     example="CAN'T HAVE - the rope was untied, with the turns still in it", colour='#A8372E'),
   dict(label='...because the engine failed',
     example='MIGHT HAVE - the tank was nearly full, but a fuel line can block', colour='#C86B2B'),
   dict(label='...because he untied it himself',
     example='MUST HAVE - it is the only thing that fits the rope', colour='#8C6A9E'),
   dict(label='...and the lifejacket is still in the shed',
     example='which fits none of the three, and nobody has explained it', colour='#9AA7AE',
     dash='6 6')],
 rule='Pick one level of certainty and stay there. It must have been the current, possibly is '
      'not a sentence.'),

"fig_a22_u06_p04_v04": dict(type='V4', height=720,
 title='The rope that broke, and the rope that was untied',
 sub='Learner A has a broken rope. Learner B has this one. They do not look alike.',
 alt='Two panels comparing a frayed broken rope end and a rope that has been untied with its '
     'turns still in it.',
 differences=6, prompt='Which one can be made to look like the other, and which cannot?',
 left=dict(label='BROKEN', art=[
   dict(kind='block', x=150, y=20, w=220, bh=28, colour='#9AA7AE'),
   dict(kind='cross', x=410, y=40),
   dict(kind='label', x=300, y=200, text='frayed, uneven, no turns left', colour='#9AA7AE')]),
 right=dict(label='UNTIED', art=[
   dict(kind='block', x=150, y=20, w=150, bh=28, colour='#2E6F5E'),
   dict(kind='block', x=150, y=70, w=150, bh=28, colour='#2E6F5E'),
   dict(kind='block', x=150, y=120, w=150, bh=28, colour='#2E6F5E'),
   dict(kind='label', x=300, y=200, text='coiled, and the turns are still in it',
        colour='#2E6F5E')])),

"fig_a22_u06_p05_v05": dict(type='V5', height=1010,
 title='The insurance claim form',
 sub='Three boxes, one tick, and one box that has been ticked, crossed out and ticked again.',
 alt='A marine insurance claim form listing three causes of loss, the payout and evidence '
     'required for each, and a settlement timescale.',
 rows=[dict(t='org', text='WESTERN MARINE  -  CLAIM FORM MC-3  (VESSEL, TOTAL LOSS)'),
   dict(t='kv', k='Vessel', v='Ballinmore, 7.4 m', mono=False),
   dict(t='kv', k='Policy', v='MV-2219', mono=True),
   dict(t='para', text='Tick ONE cause only. Where more than one box is ticked the claim is '
     'referred and settlement is suspended pending survey.'),
   dict(t='rule'),
   dict(t='head', text='CAUSE OF LOSS'),
   dict(t='grid', cols=['BOX', 'PAYS', 'EVIDENCE REQUIRED'],
     data=[['A  Mooring failure', '18,000', 'the mooring, or a photograph of it'],
           ['B  Mechanical failure', '18,000', 'engineer report on the vessel'],
           ['C  Cause unknown', '6,000', 'none']]),
   dict(t='para', text='Box B requires the vessel. The vessel has not been recovered.'),
   dict(t='rule'),
   dict(t='head', text='TIME TO SETTLE'),
   dict(t='kv', k='Box A', v='21 days', mono=True),
   dict(t='kv', k='Box B', v='4-9 months', mono=True),
   dict(t='kv', k='Box C', v='21 days', mono=True),
   dict(t='rule'),
   dict(t='head', text='DECLARATION'),
   dict(t='para', text='I declare that the cause stated is true to the best of my knowledge. '
     'A false declaration voids this policy and may be a criminal offence.'),
   dict(t='rule'),
   dict(t='sign', text='BOX A: TICKED, CROSSED OUT, TICKED AGAIN, THEN CROSSED OUT:'),
   dict(t='para', text='"Rope untied, not broken. Photographs attached. - A.H., assessor"')],
 callouts=[dict(at=0.14, text='One box. The whole decision is this sentence'),
   dict(at=0.34, text='Box A: twenty-one days, and the rope says it is not true'),
   dict(at=0.40, text='Box B: needs a boat that is two miles out'),
   dict(at=0.46, text='Box C: honest, and a third of the money'),
   dict(at=0.76, text='A false declaration voids the policy'),
   dict(at=0.93, text='Ticked twice by somebody, and crossed out by the assessor')]),

"fig_a22_u06_p06_v03a": dict(type='V3', height=640,
 title='Certain, probable, possible, ruled out',
 sub='Four positions, and each one is a different sentence about the same rope.',
 alt='A four-panel strip of four levels of certainty from a near-certainty through a probability '
     'and a possibility to something ruled out.',
 axis_start='certain', axis_end='impossible',
 panels=[dict(caption='MUST HAVE - and here is the reason', art=[
     dict(kind='tick', x=190, y=60),
     dict(kind='label', x=160, y=180, text='definitely / clearly / obviously',
       colour='#2E6F5E')]),
   dict(caption='PRESUMABLY - I am filling a gap with logic', art=[
     dict(kind='block', x=130, y=20, w=180, bh=48, colour='#1F4E5F'),
     dict(kind='gap', x=330, y=20, w=60, bh=48),
     dict(kind='label', x=160, y=180, text='presumably / surely', colour='#1F4E5F')]),
   dict(caption='APPARENTLY - somebody told me', art=[
     dict(kind='person', x=130, y=0, h=110, skin=1, cloth=0),
     dict(kind='person', x=240, y=0, h=112, skin=0, cloth=2, arm='point'),
     dict(kind='label', x=160, y=185, text='apparently / possibly', colour='#C86B2B')]),
   dict(caption="CAN'T HAVE - and here is what closes it", art=[
     dict(kind='cross', x=200, y=60),
     dict(kind='label', x=160, y=180, text='the lifejacket, on the hook', colour='#A8372E')])]),

"fig_a22_u06_p06_v04b": dict(type='V4', height=700,
 title="MUSTN'T, and CAN'T HAVE",
 sub='One of them is a rule. The other is a conclusion from evidence.',
 alt='Two panels comparing a prohibition and a deduction, each with its own kind of reason.',
 differences=6, prompt='Which one changes if you find a new piece of evidence?',
 left=dict(label="MUSTN'T - a rule", art=[
   dict(kind='doc', x=200, y=0),
   dict(kind='cross', x=380, y=40),
   dict(kind='label', x=300, y=200, text='you mustn\'t go past the line', colour='#C86B2B')]),
 right=dict(label="CAN'T HAVE - a deduction", art=[
   dict(kind='person', x=200, y=0, h=120, skin=1, cloth=4),
   dict(kind='block', x=330, y=20, w=90, bh=60, colour='#A8372E'),
   dict(kind='label', x=300, y=200, text="he can't have been aboard - the lifejacket",
        colour='#A8372E')])),

"fig_a22_u06_p07_v10": dict(type='V10', kind='elision', height=640,
 title='The word that disappears and leaves a mistake behind',
 sub='All four of these sound like of. None of them is.',
 alt='Five modal perfect phrases shown written and spoken, with have reduced to a schwa and the '
     'common misspelling marked.',
 pairs=[dict(written='must have', spoken='ˈmʌstəv', dropped='ha', note="must've - never must of"),
   dict(written='might have', spoken='ˈmaɪtəv', dropped='ha', note="might've - never might of"),
   dict(written="can't have", spoken='ˈkɑːntəv', dropped='ha', note='the h goes first'),
   dict(written='could have been', spoken='ˈkʊdəvbɪn', dropped='ha', note='three words, two beats'),
   dict(written='it MUST have been', spoken='ɪtˈmʌstˈhævbɪn', dropped='',
        note='full only when you are arguing')]),

"fig_a22_u06_p08_v06": dict(type='V6', kind='bar', height=780,
 title='What each box pays, and what it costs to prove',
 sub='Three causes, three amounts, and the time each one takes to settle.',
 alt='A bar chart comparing the payout and the settlement time for each of three causes of loss '
     'on an insurance form.',
 labels=['A mooring', 'B mechanical', 'C unknown'],
 ymin=0, ymax=20000, fmt='{:,.0f}',
 series=[dict(name='payout', values=[18000, 18000, 6000], colour='#D9A441'),
   dict(name='weeks to settle (x400)', values=[1200, 10400, 1200], colour='#1F4E5F')],
 note='Box B pays the same as box A and takes six months, because it needs an engineer report '
      'on a vessel that is two miles out.',
 warning='Box C is the only one with no evidence requirement, the only one the rope supports, '
         'and a third of the money.'),

"fig_a22_u06_p09_v03b": dict(type='V3', height=640,
 title='Four speakers, no native speakers',
 sub='What makes somebody easy to understand in English is almost never vocabulary.',
 alt='A four-panel strip of a multilingual conversation showing short sentences, checking back, '
     'repeating a number and repairing a misunderstanding.',
 axis_start='minute 0', axis_end='understood',
 panels=[dict(caption='SHORT SENTENCES - one idea each', art=[
     dict(kind='person', x=170, y=0, h=112, skin=3, cloth=2, arm='hold'),
     dict(kind='label', x=160, y=185, text='and no idioms at all', colour='#2E6F5E')]),
   dict(caption='"So you\'re saying it was untied, not broken."', art=[
     dict(kind='person', x=120, y=0, h=110, skin=0, cloth=1),
     dict(kind='person', x=240, y=0, h=112, skin=2, cloth=4, arm='point'),
     dict(kind='label', x=160, y=185, text='confirming their meaning', colour='#1F4E5F')]),
   dict(caption='"Two miles. Two. Zero point... two miles."', art=[
     dict(kind='label', x=160, y=80, text='2 mi', colour='#C86B2B'),
     dict(kind='label', x=160, y=185, text='numbers said twice', colour='#C86B2B')]),
   dict(caption='"Let me say that again differently."', art=[
     dict(kind='tick', x=190, y=60),
     dict(kind='label', x=160, y=185, text='repairing your own English, in advance',
       colour='#D9A441')])]),

"fig_a22_u06_p10_v12": dict(type='V12', height=840,
 title='From the mooring to the form',
 sub='Half the class sees the rope. Half sees the form. Rebuild the case by speaking.',
 alt='An infographic of a marine loss from the night of the disappearance through the search and '
     'the claim to the settlement.',
 span=['Sunday', 'six months on'], ticks=6,
 tick_labels=['Sun', 'Tue 11.30', 'the form', 'the rope', 'March', '+6 mo'],
 bands=[dict(name='The boat', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.14}, label='on its mooring', colour='#2E6F5E'),
   dict(**{'from': 0.14, 'to': 0.30}, label='missing', colour='#A8372E'),
   dict(**{'from': 0.30, 'to': 1.0}, label='two miles out, not recovered', colour='#9AA7AE')]),
  dict(name='The explanations', type='events', items=[
   dict(at=0.20, label='"it must have broken its mooring" - before anyone looked',
     colour='#C86B2B'),
   dict(at=0.44, label='the rope: untied, turns still in it', colour='#1F4E5F'),
   dict(at=0.50, label='the lifejacket, on the hook since Sunday', colour='#8C6A9E'),
   dict(at=0.72, label='search closed', colour='#A8372E'),
   dict(at=0.96, label='"circumstances not determined, no owner fault"', colour='#2E6F5E')]),
  dict(name='What the claim is worth', type='line',
   points=[(0.3, 18000), (0.45, 6000), (0.6, 6000), (0.8, 6000), (0.95, 18000), (1.0, 18000)],
   end_label='18,000'),
  dict(name='The arguments', type='flags', items=[
   dict(at=0.24, label='rope that breaks does not look like that'),
   dict(at=0.56, label='box B needs a boat nobody can reach'),
   dict(at=0.78, label='the honest box pays a third'),
   dict(at=0.99, label='a heading that is not on the household form')])]),
}
