"""A2.2 Unit 7 - This Time Next Year - fourteen figures, as data."""
FIGURES = {
"fig_a22_u07_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The boatyard and the bus stop, March',
 sub='Eleven things to find. Four of them are plans, not objects.',
 alt='A boatyard beside a road with a boat for sale, a half-built extension, a job advert on a '
     'board, a bus to Galway and a college prospectus on a table.',
 sky='#DEE6E8', ground='#9DA4A4', ground_line=660,
 buildings=[dict(x=20, w=460, storeys=2, colour='#D4CFC2', label='the boatyard'),
   dict(x=540, w=300, storeys=1, colour='#CAC5B8', label='the half-built extension'),
   dict(x=900, w=320, storeys=2, colour='#D0CABA', label='the college office'),
   dict(x=1280, w=300, storeys=2, colour='#C2BDB1', label='the terrace')],
 props=[dict(kind='scaffold', x=600, y=660, s=.95),
   dict(kind='hoarding', x=270, y=660, s=1.0),
   dict(kind='table', x=980, y=660, s=1.2), dict(kind='doc', x=980, y=592),
   dict(kind='van', x=1180, y=660, s=.95, colour='#D9A441'),
   dict(kind='crate', x=120, y=660, s=1.1),
   dict(kind='sign', x=440, y=660, s=.75, text='FOR SALE'),
   dict(kind='sign', x=1420, y=660, s=.75, text='GALWAY')],
 people=[dict(x=180, y=660, h=86, skin=1, cloth=4, hair='grey', arm='hold'),
   dict(x=380, y=660, h=85, skin=2, cloth=3, hair='short', arm='point'),
   dict(x=720, y=660, h=86, skin=0, cloth=2, hair='bun', arm='down'),
   dict(x=1020, y=660, h=85, skin=2, cloth=1, hair='long', arm='hold'),
   dict(x=1340, y=660, h=86, skin=0, cloth=1, hair='short', arm='raise')],
 names=[dict(x=180, t='Peadar, deciding in February'), dict(x=380, t='Tomas, two apprentices'),
   dict(x=720, t='Sinead, not going anywhere'), dict(x=1020, t="Aoife's brother, Sligo or here"),
   dict(x=1340, t='Aoife, Dublin by October'), dict(x=440, t='the boat that is not coming back'),
   dict(x=1420, t='the 07.40, twice a day')],
 markers=[dict(x=180, y=548), dict(x=380, y=548), dict(x=720, y=548), dict(x=1020, y=548),
   dict(x=1340, y=548), dict(x=440, y=592), dict(x=1420, y=592), dict(x=270, y=606),
   dict(x=600, y=580), dict(x=980, y=600), dict(x=1180, y=604)]),

"fig_a22_u07_p01_v08": dict(type='V8', height=780,
 title='One plan with eleven authors',
 sub='Five nodes. Every arrow is somebody waiting for somebody else to answer.',
 alt='A network of five people whose plans each depend on another, with the one decision that '
     'starts the chain marked.',
 nodes={
  'pea': dict(x=180, y=400, short='1', name='Peadar', sub='decides in February', colour='#1F4E5F'),
  'yar': dict(x=520, y=230, short='2', name='The boatyard', sub='its best customer', colour='#C86B2B'),
  'bro': dict(x=520, y=570, short='3', name='Two apprentices', sub='one is her brother', colour='#2E6F5E'),
  'hal': dict(x=900, y=400, short='4', name='The hall', sub='insurance, January', r=54, colour='#8C6A9E'),
  'aoi': dict(x=1290, y=400, short='5', name='Aoife', sub='Dublin, by October', r=54, colour='#D9A441')},
 edges=[dict(a='pea', b='yar', label='if he goes, it loses him', sw=5),
   dict(a='yar', b='bro', label='and then it takes nobody on', sw=5),
   dict(a='bro', b='aoi', label='Sligo instead, which he does not want', sw=4),
   dict(a='hal', b='aoi', label='somebody will have to run it', sw=4, dash='5 5'),
   dict(a='yar', b='hal', label='the plasterboard, still', sw=3),
   dict(a='pea', b='aoi', label='the only sentence with no if in it', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_a22_u07_p01_v02": dict(type='V2', height=780,
 title='The boatyard, in section',
 sub='Four levels, four futures. One of them will look identical in a year.',
 alt='A boatyard drawn in section showing the office, the workshop, the slip and the yard, each '
     'labelled with what it will be like in a year.',
 floors=[dict(was='the office', now='The job board. Two posts, neither of them here', year='',
     fill='#E4ECEF'),
   dict(was='the workshop', now='Two benches. One apprentice, or none, by March', year='',
     fill='#EFE2DD'),
   dict(was='the slip', now="Peadar's mooring, empty since January", year='', fill='#F6F0E4'),
   dict(was='the yard', now='Four boats on blocks. Three of them since 2019', year='',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Both posts are in Galway'),
   dict(at=0.38, text='This is the level that depends on one man in February'),
   dict(at=0.62, text='Empty, and nobody is building him another'),
   dict(at=0.88, text='Identical in a year, and identical in five')]),

"fig_a22_u07_p02_v07": dict(type='V7', height=800,
 title='The Galway boat',
 sub='One of them has an offer. The other has already written the consequences on an envelope.',
 alt='A skipper and a young woman talking on a pier, with speech bubbles contrasting will and '
     'the future continuous.',
 bg='#E7EBEC',
 set=[dict(kind='crate', x=680, y=680, s=1.2), dict(kind='doc', x=1280, y=640)],
 people=[dict(x=470, h=242, skin=1, cloth=4, hair='grey', arm='folded', facing='right',
   label='Peadar', role='two seasons offered', says=["I'll take it.",
     "I'll be taking the boat out at four, same as here."]),
  dict(x=970, h=240, skin=0, cloth=1, hair='long', arm='point', facing='left',
   label='Aoife', role='Dublin by October', says=["This time next year I'll be living in "
     'Dublin.'])]),

"fig_a22_u07_p03_v09": dict(type='V9', kind='mirror', height=660,
 title='A decision, and a future that is simply running',
 sub='Both use will. Only one of them is a decision being made in the sentence.',
 alt='Two parallel sentences compared, one a spontaneous decision with will and one a future '
     'arrangement with will be plus -ing.',
 active=dict(parts=[dict(w=0.8, role='agent', text="I'll"),
   dict(w=1.0, role='action', text='take'),
   dict(w=1.4, role='affected', text='it. - A DECISION, NOW')]),
 passive=dict(parts=[dict(w=0.8, role='agent', text="I'll"),
   dict(w=1.4, role='action', text='be taking'),
   dict(w=1.8, role='affected', text='the boat out at four. - ALREADY IN MOTION')]),
 rule='Will you be coming? is softer than Are you coming?, because it asks about your '
      'arrangements rather than your intentions.'),

"fig_a22_u07_p03_v09b": dict(type='V9', kind='ladder', height=720,
 title='From deciding now to a year already running',
 sub='Five futures. The top one carries no decision at all, and that is why it is polite.',
 alt='A ladder from a spontaneous decision at the bottom up through intention and arrangement to '
     'a future that is simply in motion.',
 top_label='already in motion', bottom_label='decided as you speak',
 steps=[dict(form="This time next year I'll be living in Galway",
     meaning='a future described as ordinary. No decision in the sentence'),
   dict(form='Will you be coming to the meeting?',
     meaning='about your arrangements - and therefore polite'),
   dict(form="I'm meeting him on Tuesday", meaning='an arrangement, already fixed with somebody'),
   dict(form="I'm going to apply in March", meaning='an intention you already had'),
   dict(form="I'll take it", meaning='decided in the moment of speaking')],
 rule='State verbs still have no continuous: I will know by March, never I will be knowing by '
      'March.'),

"fig_a22_u07_p04_v04": dict(type='V4', height=720,
 title='The town in March, and the town next March',
 sub='Learner A has this year. Learner B has next year. Seven things change.',
 alt='Two panels of the same boatyard a year apart, one with a For Sale sign and an empty '
     'mooring, the other with different people and a finished extension.',
 differences=7, prompt='Which of the changes depend on one person\'s decision?',
 left=dict(label='this March', art=[
   dict(kind='person', x=150, y=0, h=112, skin=1, cloth=4),
   dict(kind='person', x=240, y=0, h=110, skin=0, cloth=1),
   dict(kind='gap', x=330, y=10, w=90, bh=80),
   dict(kind='label', x=300, y=200, text='an empty mooring and a half-built wall',
        colour='#9AA7AE')]),
 right=dict(label='next March', art=[
   dict(kind='block', x=150, y=0, w=160, bh=100, colour='#2E6F5E'),
   dict(kind='person', x=360, y=0, h=112, skin=2, cloth=3),
   dict(kind='label', x=300, y=200, text='a finished wall, and two people gone',
        colour='#2E6F5E')])),

"fig_a22_u07_p05_v05": dict(type='V5', height=1010,
 title='The job advert, and the contract summary',
 sub='The advert is forty words. The contract summary is the one with the nights in it.',
 alt='A job advert for a crew berth and the contract summary that goes with it, listing term, '
     'pay, patterns of work, accommodation and the acceptance deadline.',
 rows=[dict(t='org', text='ADVERT  -  GALWAY, CREW BERTH'),
   dict(t='para', text='"Experienced hand wanted for 18 m vessel, Galway. Two seasons. Good '
     'rates. Accommodation available. Immediate start for the right person."'),
   dict(t='kv', k='Words in the advert', v='40', mono=True),
   dict(t='rule'),
   dict(t='org', text='CONTRACT SUMMARY  -  THE SAME POST'),
   dict(t='grid', cols=['ITEM', 'DETAIL', 'NOTE'],
     data=[['Term', '2 seasons (20 months)', 'no break clause before month 10'],
           ['Pattern', '3 weeks on, 10 days off', 'nights away: 21 at a time'],
           ['Rate', '1.9 x local berth', 'before deductions'],
           ['Accommodation', 'shared, 140/month', '"available", not included'],
           ['Start', '1 March', 'see clause 9']]),
   dict(t='rule'),
   dict(t='head', text='CLAUSE 9'),
   dict(t='para', text='Where the vessel\'s refit is not completed, the start date moves to the '
     'first sailing. The engagement is not paid between 1 March and that date.'),
   dict(t='rule'),
   dict(t='head', text='ACCEPTANCE'),
   dict(t='kv', k='Reply by', v='15 January', mono=True),
   dict(t='kv', k='After that', v='post is re-advertised', mono=True),
   dict(t='rule'),
   dict(t='sign', text='WRITTEN ON THE ADVERT IN THE YARD OFFICE:'),
   dict(t='para', text='"Ask about the refit. - T."')],
 callouts=[dict(at=0.10, text='Forty words, and three of them are doing a lot of work'),
   dict(at=0.34, text='Twenty months. Nothing can be undone for ten of them'),
   dict(at=0.40, text='Twenty-one nights at a time - and the advert does not say this'),
   dict(at=0.48, text='"Available" means you may rent it'),
   dict(at=0.70, text='Unpaid until the refit finishes, and nobody knows when that is'),
   dict(at=0.84, text='Fifteenth of January. The essay says he decides in February')]),

"fig_a22_u07_p06_v03a": dict(type='V3', height=640,
 title='Soon, by then, eventually',
 sub='Four distances into the future, and each one commits you to a different amount.',
 alt='A four-panel strip placing a future event as imminent, dated, far off and indefinite.',
 axis_start='now', axis_end='eventually',
 panels=[dict(caption='SHORTLY - and you can be held to it', art=[
     dict(kind='block', x=130, y=20, w=70, bh=48, colour='#2E6F5E'),
     dict(kind='label', x=160, y=180, text='soon / shortly', colour='#2E6F5E')]),
   dict(caption='BY THEN - a date, and a deadline', art=[
     dict(kind='block', x=110, y=20, w=180, bh=48, colour='#1F4E5F'),
     dict(kind='tick', x=330, y=40),
     dict(kind='label', x=160, y=180, text='by then / by the end of', colour='#1F4E5F')]),
   dict(caption="THIS TIME NEXT YEAR - a morning you can picture", art=[
     dict(kind='label', x=160, y=80, text='Tue 08:10', colour='#C86B2B'),
     dict(kind='label', x=160, y=185, text="in a year's time", colour='#C86B2B')]),
   dict(caption='EVENTUALLY - and nobody can hold you to it', art=[
     dict(kind='arrow', x=220, y=40),
     dict(kind='label', x=160, y=180, text='eventually / onwards / ahead', colour='#9AA7AE')])]),

"fig_a22_u07_p06_v04b": dict(type='V4', height=700,
 title="I'LL GO, and I'LL BE GOING",
 sub='The same journey. One of them is news and the other is a timetable.',
 alt='Two panels comparing a simple future decision and a future continuous arrangement, drawn '
     'as a single event and as a running band.',
 differences=6, prompt='Which one would be on a noticeboard?',
 left=dict(label="I'LL GO - a decision", art=[
   dict(kind='block', x=240, y=0, w=90, bh=56, colour='#C86B2B'),
   dict(kind='arrow', x=380, y=16),
   dict(kind='label', x=300, y=200, text='decided in the moment of speaking',
        colour='#C86B2B')]),
 right=dict(label="I'LL BE GOING - an arrangement", art=[
   dict(kind='block', x=140, y=0, w=320, bh=56, colour='#2E6F5E'),
   dict(kind='label', x=300, y=200, text='already in motion, and nobody is deciding',
        colour='#2E6F5E')])),

"fig_a22_u07_p07_v10": dict(type='V10', kind='elision', height=640,
 title='Three words that become one and a half',
 sub="I will be is three words in writing and about one and a half in speech.",
 alt='Five future continuous phrases shown written and spoken, with will reduced to an l and be '
     'reduced to /bi/.',
 pairs=[dict(written='I will be', spoken='aɪlbi', dropped='wil', note="I'll be - one and a half"),
   dict(written='she will be working', spoken='ʃiːlbiˈwɜːkɪŋ', dropped='wil',
     note='four words, two beats'),
   dict(written='we will be waiting', spoken='wiːlbiˈweɪtɪŋ', dropped='wil', note='the same shape'),
   dict(written='this time next year', spoken='ðɪstaɪmnekstˈjɪə', dropped='',
     note='four words, one stress, at the end'),
   dict(written='I WILL be there', spoken='aɪˈwɪlbiˈðeə', dropped='',
     note='full only when somebody has doubted it')]),

"fig_a22_u07_p08_v06": dict(type='V6', kind='line', height=780,
 title='What a berth here has paid, each season, for ten years',
 sub='Local boats against the Galway rate, in thousands, after deductions.',
 alt='A line chart of seasonal earnings from a local berth over ten years against the rate '
     'offered in Galway, showing a steady decline locally.',
 labels=['yr 1', 'yr 3', 'yr 5', 'yr 7', 'yr 9', 'yr 10'],
 ymin=0, ymax=40, fmt='{:,.0f}',
 series=[dict(name='a berth here', values=[26, 25, 23, 21, 17, 14], colour='#C86B2B'),
   dict(name='the Galway rate', values=[28, 29, 29, 30, 31, 31], colour='#1F4E5F')],
 note='A local berth has lost nearly half its value in ten years. The Galway rate has moved '
      'almost not at all, which is why it now looks like double.',
 warning='Two of the ten local seasons were better than Galway. Both of them were more than six '
         'years ago, and people on the pier still quote them.'),

"fig_a22_u07_p09_v03b": dict(type='V3', height=640,
 title='Four parts of an interview',
 sub='The third one decides it, and most people prepare for the second.',
 alt='A four-panel strip of an interview: the warm-up, what you can do, what you have not done, '
     'and the question you ask them.',
 axis_start='minute 0', axis_end='minute 25',
 panels=[dict(caption='"Did you find us all right?"', art=[
     dict(kind='person', x=130, y=0, h=110, skin=2, cloth=3),
     dict(kind='person', x=240, y=0, h=112, skin=1, cloth=4),
     dict(kind='label', x=160, y=185, text='the warm-up, and it is not scored',
       colour='#9AA7AE')]),
   dict(caption='"Tell me about a bad night at sea."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=1, cloth=4, arm='hold'),
     dict(kind='label', x=160, y=185, text='what you can do - and you prepared this',
       colour='#2E6F5E')]),
   dict(caption='"You\'ve not worked a boat this size."', art=[
     dict(kind='cross', x=200, y=60),
     dict(kind='label', x=160, y=180, text='and this is the one that decides it',
       colour='#A8372E')]),
   dict(caption='"How many of your crew came back last season?"', art=[
     dict(kind='person', x=170, y=0, h=112, skin=1, cloth=4, arm='point'),
     dict(kind='label', x=160, y=185, text='your question, and it has to be real',
       colour='#D9A441')])]),

"fig_a22_u07_p10_v12": dict(type='V12', height=840,
 title='One decision, eleven plans',
 sub='Half the class sees the advert. Half sees the essay. Rebuild the chain by speaking.',
 alt='An infographic of a year ahead in a small town showing one decision in February and the '
     'consequences for the boatyard, the apprentices, the hall and a student.',
 span=['Jan', 'next Oct'], ticks=6,
 tick_labels=['Jan', 'Feb', 'Mar', 'Jun', 'Sep', 'Oct'],
 bands=[dict(name='Peadar', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.18}, label='deciding', colour='#D9A441'),
   dict(**{'from': 0.18, 'to': 1.0}, label='Galway - 3 weeks on, 10 days off', colour='#1F4E5F')]),
  dict(name='The consequences', type='events', items=[
   dict(at=0.08, label='acceptance deadline: 15 January', colour='#A8372E'),
   dict(at=0.22, label='the yard loses its best customer', colour='#C86B2B'),
   dict(at=0.34, label='two apprentices not taken on', colour='#C86B2B'),
   dict(at=0.52, label='Sligo instead - and he does well', colour='#2E6F5E'),
   dict(at=0.90, label='Aoife in Dublin by October', colour='#8C6A9E')]),
  dict(name='People in the town', type='line',
   points=[(0, 11), (0.2, 11), (0.35, 10), (0.6, 9), (0.9, 8), (1.0, 8)], end_label='8'),
  dict(name='What nobody said', type='flags', items=[
   dict(at=0.12, label='he has been awake at four since January'),
   dict(at=0.44, label='the contract is unpaid until the refit ends'),
   dict(at=0.68, label='"available" accommodation costs 140 a month'),
   dict(at=0.96, label='and he is back ten days in four')])]),
}
