"""A2.2 Unit 9 - Four Claims, Enough for Three - fourteen figures, as data."""
FIGURES = {
"fig_a22_u09_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='The committee room and the store, December',
 sub='Ten things to find. Four of them are being counted.',
 alt='A council committee room beside a half-empty supply store, with a table of forms, a cash '
     'box, a list on the wall, a queue outside and a locked cupboard.',
 sky='#DFE4E6', ground='#9FA5A5', ground_line=660,
 buildings=[dict(x=20, w=520, storeys=2, colour='#D4CFC3', label='the committee room'),
   dict(x=600, w=400, storeys=1, colour='#CAC5B8', label='the supply store'),
   dict(x=1060, w=520, storeys=2, colour='#C3BEB2', label='the county office')],
 props=[dict(kind='table', x=260, y=660, s=1.6),
   dict(kind='doc', x=220, y=592), dict(kind='doc', x=310, y=598),
   dict(kind='box', x=680, y=660, s=1.3), dict(kind='box', x=780, y=660, s=1.1),
   dict(kind='crate', x=900, y=660, s=1.1),
   dict(kind='sign', x=120, y=660, s=.75, text='180k'),
   dict(kind='sign', x=1020, y=660, s=.7, text='4 CLAIMS'),
   dict(kind='van', x=1380, y=660, s=.9, colour='#8C6A9E')],
 people=[dict(x=170, y=660, h=86, skin=0, cloth=2, hair='bun', arm='hold'),
   dict(x=420, y=660, h=85, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=620, y=660, h=86, skin=2, cloth=3, hair='short', arm='down'),
   dict(x=1000, y=660, h=85, skin=0, cloth=1, hair='long', arm='folded'),
   dict(x=1180, y=660, h=86, skin=1, cloth=4, hair='cap', arm='hold')],
 names=[dict(x=170, t='Sinead, claim 1'), dict(x=420, t='the chair, six votes to three'),
   dict(x=620, t='Tomas, counting the store'), dict(x=1000, t='Eimear, claim 3, insured'),
   dict(x=1180, t='the boatyard, claim 4, not insured'),
   dict(x=120, t='the total available'), dict(x=1020, t='238,500 asked for')],
 markers=[dict(x=170, y=548), dict(x=420, y=548), dict(x=620, y=548), dict(x=1000, y=548),
   dict(x=1180, y=548), dict(x=120, y=592), dict(x=1020, y=592), dict(x=260, y=604),
   dict(x=680, y=602), dict(x=900, y=612)]),

"fig_a22_u09_p01_v08": dict(type='V8', height=780,
 title='Four meanings of fair',
 sub='Five nodes. Everybody in the room agrees on the word and on nothing else.',
 alt='A network from a limited fund into four allocation methods - equal, proportional, by need '
     'and first come - and the consequence of each.',
 nodes={
  'fun': dict(x=180, y=400, short='1', name='180,000', sub='and 238,500 asked for', colour='#1F4E5F'),
  'equ': dict(x=520, y=180, short='2', name='Equal', sub='45,000 each', colour='#2E6F5E'),
  'pro': dict(x=520, y=400, short='3', name='Proportional', sub='about 75 % each', colour='#D9A441'),
  'nee': dict(x=520, y=620, short='4', name='By need', sub='the two with no insurance', colour='#C86B2B'),
  'out': dict(x=1120, y=400, short='5', name='What happens', sub='and this is the only test',
    r=54, colour='#8C6A9E')},
 edges=[dict(a='fun', b='equ', label='clean and defensible', sw=5),
   dict(a='fun', b='pro', label='rewards the optimistic estimate', sw=5),
   dict(a='fun', b='nee', label='and you have to say it out loud', sw=5),
   dict(a='equ', b='out', label='two projects stall. The money sits', sw=4, dash='5 5'),
   dict(a='pro', b='out', label='four half-finished things', sw=4, dash='5 5'),
   dict(a='nee', b='out', label='two finished things and two angry people', sw=5)]),

"fig_a22_u09_p01_v02": dict(type='V2', height=780,
 title='The supply store, in section',
 sub='Four shelves. One will be empty by Friday and one has not been touched since February.',
 alt='A supply store drawn in section with four shelves of flood relief equipment, each labelled '
     'with how much is left and how fast it goes.',
 floors=[dict(was='top shelf', now='Blankets - 140. Untouched since February', year='',
     fill='#E4ECEF'),
   dict(was='second shelf', now='Dehumidifiers - 3 left of 22. Run out three times', year='',
     fill='#EFE2DD'),
   dict(was='third shelf', now='Forms and sign-up sheets - plenty, and nobody wants them',
     year='', fill='#F6F0E4'),
   dict(was='the floor', now='Generator fuel - used up in six weeks, never reordered', year='',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Nobody needed blankets. Somebody sent 140'),
   dict(at=0.38, text='The only thing that has run out, and it has run out three times'),
   dict(at=0.62, text='Plenty, which is the word for a thing nobody wants'),
   dict(at=0.88, text='Used up, and the reorder form is on the shelf above')]),

"fig_a22_u09_p02_v07": dict(type='V7', height=800,
 title='One hundred and eighty thousand',
 sub='One of them has to say no out loud. The other has one of the four claims.',
 alt='A committee chair and a claimant across a table with forms between them, speech bubbles '
     'using all, most, neither and none.',
 bg='#E8EAEB',
 set=[dict(kind='table', x=700, y=680, s=1.5), dict(kind='doc', x=700, y=608)],
 people=[dict(x=470, h=242, skin=1, cloth=0, hair='grey', arm='hold', facing='right',
   label='the chair', role='six to three', says=['All of them are honest.',
     'Neither of the last two has any insurance at all.']),
  dict(x=970, h=240, skin=0, cloth=1, hair='long', arm='point', facing='left',
   label='Eimear', role='claim 3', says=['None of it can be carried over.'])]),

"fig_a22_u09_p03_v09": dict(type='V9', kind='ladder', height=720,
 title='One bar, cut six ways',
 sub='Six quantifiers, from everything to nothing, and two of them are only ever about two.',
 alt='A ladder of quantifiers from all at the top down through most, half and several to none at '
     'the bottom, with the of rule on each rung.',
 top_label='everything', bottom_label='nothing',
 steps=[dict(form='ALL of them', meaning='100 %. Of is compulsory before a pronoun'),
   dict(form='MOST of them', meaning='more than half, and no number is implied'),
   dict(form='BOTH of them / EITHER of them', meaning='exactly two. Either takes a singular verb'),
   dict(form='SEVERAL of them / A COUPLE of them', meaning='more than two, fewer than most'),
   dict(form='NEITHER of them is / NONE of it', meaning='zero. Neither is only ever about two')],
 rule='Before a pronoun, of is compulsory: all of them, never all them. Before the or my it is '
      'optional. Before a bare plural there is no of, and the sentence becomes general.'),

"fig_a22_u09_p03_v09b": dict(type='V9', kind='scope', height=580,
 title='Where of is compulsory',
 sub='Three slots, and only one of them can be empty.',
 alt='A sentence with brackets marking the quantifier, the optional of, and the pronoun that '
     'makes it compulsory.',
 words=['All', '(of)', 'the', 'claims', '/', 'All', 'OF', 'them'],
 focus=[1, 6],
 brackets=[dict(**{'from': 0, 'to': 3}, lane=0, label='before THE: of is optional',
     colour='#2E6F5E'),
   dict(**{'from': 5, 'to': 7}, lane=0, label='before a pronoun: of is compulsory',
     colour='#A8372E'),
   dict(**{'from': 3, 'to': 3}, lane=1, label='all claims (no of, no the) = every claim anywhere',
     colour='#9AA7AE')]),

"fig_a22_u09_p04_v04": dict(type='V4', height=720,
 title='Equal shares, and shares by need',
 sub='Learner A has the equal split. Learner B has the need split. Same total.',
 alt='Two panels comparing four equal portions of a fund with two full portions and two empty '
     'ones.',
 differences=6, prompt='Which split finishes something?',
 left=dict(label='EQUAL - 45,000 each', art=[
   dict(kind='block', x=130, y=0, w=70, bh=60, colour='#9AA7AE'),
   dict(kind='block', x=215, y=0, w=70, bh=60, colour='#9AA7AE'),
   dict(kind='block', x=300, y=0, w=70, bh=60, colour='#9AA7AE'),
   dict(kind='block', x=385, y=0, w=70, bh=60, colour='#9AA7AE'),
   dict(kind='label', x=300, y=200, text='four started, none finished', colour='#9AA7AE')]),
 right=dict(label='BY NEED - two funded', art=[
   dict(kind='block', x=130, y=0, w=70, bh=130, colour='#2E6F5E'),
   dict(kind='block', x=215, y=0, w=70, bh=130, colour='#2E6F5E'),
   dict(kind='gap', x=300, y=0, w=70, bh=130),
   dict(kind='gap', x=385, y=0, w=70, bh=130),
   dict(kind='label', x=300, y=200, text='two finished, two angry', colour='#2E6F5E')])),

"fig_a22_u09_p05_v05": dict(type='V5', height=1010,
 title='The allocation sheet',
 sub='Four claims, one of them quietly reduced in April, and a contingency nobody has touched.',
 alt='A committee allocation sheet listing four claims, their amounts, whether each is insured, '
     'the contingency and the rule on unspent money.',
 rows=[dict(t='org', text='BALLINMORE RELIEF FUND  -  ALLOCATION SHEET, DECEMBER'),
   dict(t='kv', k='Available', v='180,000', mono=True),
   dict(t='kv', k='Claims received', v='4', mono=True),
   dict(t='rule'),
   dict(t='head', text='THE CLAIMS'),
   dict(t='grid', cols=['CLAIM', 'ASKED', 'INSURED?'],
     data=[['1  Hall - floor and wiring', '52,000', 'yes, partly'],
           ['2  Terrace - 4 households', '61,500', 'yes'],
           ['3  Guest house', '58,000', 'no'],
           ['4  Boatyard - slip and shed', '67,000', 'no']]),
   dict(t='kv', k='Total asked', v='238,500', mono=True),
   dict(t='kv', k='Shortfall', v='58,500', mono=True),
   dict(t='para', text='Claim 2 was submitted in March at 69,000 and reduced by the claimant '
     'in April. The reduction is not minuted.'),
   dict(t='rule'),
   dict(t='head', text='THE RULES'),
   dict(t='kv', k='Contingency held', v='8,000', mono=True),
   dict(t='kv', k='Contingency spent', v='0', mono=True),
   dict(t='kv', k='Carry over to next year', v='not permitted', mono=False),
   dict(t='para', text='Any sum unspent at 31 December returns to the county.'),
   dict(t='rule'),
   dict(t='sign', text='PENCILLED IN THE MARGIN BESIDE CLAIM 2:'),
   dict(t='para', text='"Reduced. Says he found a cheaper contractor. Nobody asked him to."')],
 callouts=[dict(at=0.14, text='One hundred and eighty, and that is the whole room'),
   dict(at=0.32, text='Two insured, two not. This column is the argument'),
   dict(at=0.46, text='Fifty-eight and a half thousand short, whatever you do'),
   dict(at=0.56, text='Reduced by seven and a half thousand, and not minuted'),
   dict(at=0.74, text='Eight thousand held back, and never used'),
   dict(at=0.94, text='Nobody asked him to - and nobody thanked him either')]),

"fig_a22_u09_p06_v03a": dict(type='V3', height=640,
 title='Countable, uncountable, and what goes with each',
 sub='Four pairs. The quantifier changes and the noun stays where it is.',
 alt='A four-panel strip pairing countable nouns with few and several and uncountable nouns with '
     'little and much.',
 axis_start='countable', axis_end='uncountable',
 panels=[dict(caption='FEW / SEVERAL - things you can count', art=[
     dict(kind='block', x=130, y=20, w=40, bh=48, colour='#1F4E5F'),
     dict(kind='block', x=190, y=20, w=40, bh=48, colour='#1F4E5F'),
     dict(kind='block', x=250, y=20, w=40, bh=48, colour='#1F4E5F'),
     dict(kind='label', x=160, y=180, text='few claims / several forms', colour='#1F4E5F')]),
   dict(caption='LITTLE / MUCH - things you cannot', art=[
     dict(kind='block', x=130, y=20, w=200, bh=48, colour='#C86B2B'),
     dict(kind='label', x=160, y=180, text='little money / much relief', colour='#C86B2B')]),
   dict(caption='NONE OF THEM - the claims', art=[
     dict(kind='cross', x=190, y=60),
     dict(kind='label', x=160, y=180, text='plural, and you could count them',
       colour='#A8372E')]),
   dict(caption='NONE OF IT - the money', art=[
     dict(kind='cross', x=190, y=60),
     dict(kind='label', x=160, y=180, text='singular, and you cannot', colour='#A8372E')])]),

"fig_a22_u09_p06_v04b": dict(type='V4', height=700,
 title='NEITHER, and NONE',
 sub='Both mean zero. One of them insists there were exactly two.',
 alt='Two panels comparing neither with two options and none with four, each with its verb form.',
 differences=6, prompt='Which one can you use about four claims?',
 left=dict(label='NEITHER of them is...', art=[
   dict(kind='block', x=200, y=0, w=80, bh=70, colour='#9AA7AE'),
   dict(kind='block', x=300, y=0, w=80, bh=70, colour='#9AA7AE'),
   dict(kind='cross', x=420, y=30),
   dict(kind='label', x=300, y=200, text='exactly two, and a singular verb',
        colour='#9AA7AE')]),
 right=dict(label='NONE of them are...', art=[
   dict(kind='block', x=140, y=0, w=60, bh=70, colour='#A8372E'),
   dict(kind='block', x=220, y=0, w=60, bh=70, colour='#A8372E'),
   dict(kind='block', x=300, y=0, w=60, bh=70, colour='#A8372E'),
   dict(kind='block', x=380, y=0, w=60, bh=70, colour='#A8372E'),
   dict(kind='label', x=300, y=200, text='any number at all', colour='#A8372E')])),

"fig_a22_u09_p07_v10": dict(type='V10', kind='stress', height=700,
 title='Stress as an argument',
 sub='The words do not change. The stressed one tells you what has just been denied.',
 alt='Five identical sentences with different syllables stressed, each answering a different '
     'unspoken accusation.',
 items=[dict(syllables=['ALL', 'of', 'them', 'are', 'hon', 'est'], strong=[0],
     note='and you had suggested some were not'),
   dict(syllables=['all', 'of', 'THEM', 'are', 'hon', 'est'], strong=[2],
     note='and somebody else is not'),
   dict(syllables=['all', 'of', 'them', 'ARE', 'hon', 'est'], strong=[3],
     note='and you had just denied it'),
   dict(syllables=['we', 'fund', 'ed', 'THREE', 'of', 'them'], strong=[3], note='not four'),
   dict(syllables=['we', 'fund', 'ed', 'three', 'of', 'THEM'], strong=[5],
     note='not of somebody else')]),

"fig_a22_u09_p08_v06": dict(type='V6', kind='bar', height=780,
 title='What each claim buys at 45, 75 and 100 per cent',
 sub='Four claims, three allocation methods, and the figure that matters is the finished one.',
 alt='A bar chart showing how much of each project would be completed under equal, proportional '
     'and need-based allocation.',
 labels=['hall', 'terrace', 'guest house', 'boatyard'],
 ymin=0, ymax=100, fmt='{:,.0f}',
 series=[dict(name='% complete if equal', values=[87, 73, 78, 67], colour='#9AA7AE'),
   dict(name='% complete if by need', values=[0, 0, 100, 100], colour='#2E6F5E')],
 note='Under equal shares nothing reaches a hundred. Under need two do, and two get nothing at '
      'all.',
 warning='A project at 78 per cent is not 78 per cent of a building. It is a building that '
         'cannot open, which is why percentage-complete is the wrong chart to put in front of a '
         'committee.'),

"fig_a22_u09_p09_v03b": dict(type='V3', height=640,
 title='Silence, overlap and turn-taking',
 sub='The same meeting, two sets of rules, and both of them work for the people used to them.',
 alt='A four-panel strip comparing overlapping speech, a long silence, protecting somebody '
     'else\'s turn and giving a turn back.',
 axis_start='one norm', axis_end='another',
 panels=[dict(caption='OVERLAP - and it is not an argument', art=[
     dict(kind='person', x=120, y=0, h=110, skin=0, cloth=1, arm='point'),
     dict(kind='person', x=230, y=0, h=112, skin=2, cloth=3, arm='point'),
     dict(kind='label', x=160, y=185, text='agreement, where this is normal',
       colour='#C86B2B')]),
   dict(caption='A TWO-SECOND SILENCE', art=[
     dict(kind='gap', x=150, y=20, w=160, bh=60),
     dict(kind='label', x=160, y=180, text='go ahead - or: something is wrong',
       colour='#9AA7AE')]),
   dict(caption='"I think Sinead was still speaking."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=1, cloth=0, arm='raise'),
     dict(kind='label', x=160, y=185, text='protecting somebody else\'s turn',
       colour='#2E6F5E')]),
   dict(caption='"Go on, go on."', art=[
     dict(kind='arrow', x=200, y=40),
     dict(kind='label', x=160, y=180, text='giving a turn back', colour='#1F4E5F')])]),

"fig_a22_u09_p10_v12": dict(type='V12', height=840,
 title='One hundred and eighty thousand, March to December',
 sub='Half the class sees the sheet. Half sees the column. Rebuild the decision by speaking.',
 alt='An infographic of a relief fund from the claims arriving in March through the reduction, '
     'the vote and the unspent balance returning in December.',
 span=['March', 'December'], ticks=6,
 tick_labels=['Mar', 'Apr', 'Jul', 'Oct', 'the vote', 'Dec'],
 bands=[dict(name='The fund', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.74}, label='180,000, unallocated', colour='#D9A441'),
   dict(**{'from': 0.74, 'to': 0.96}, label='125,000 paid out', colour='#2E6F5E'),
   dict(**{'from': 0.96, 'to': 1.0}, label='4,100 returned', colour='#A8372E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.02, label='two claims in. Quietly assumed into the budget', colour='#9AA7AE'),
   dict(at=0.16, label='claim 2 reduced by 7,500 - not minuted', colour='#8C6A9E'),
   dict(at=0.74, label='vote: by need, 6 to 3, two hours', colour='#2E6F5E'),
   dict(at=0.82, label='an insured claimant asks for a letter', colour='#1F4E5F'),
   dict(at=0.88, label='his insurer settles in April because of it', colour='#2E6F5E')]),
  dict(name='Unallocated', type='line',
   points=[(0, 180), (0.4, 180), (0.74, 180), (0.8, 55), (0.96, 4.1), (1.0, 0)],
   end_label='0'),
  dict(name='The four meanings of fair', type='flags', items=[
   dict(at=0.20, label='equal: 45,000 each, and nothing finishes'),
   dict(at=0.44, label='proportional: rewards the optimistic estimate'),
   dict(at=0.64, label='by need: and you have to say it out loud'),
   dict(at=0.92, label='first come: it had already partly happened')])]),
}
