"""A2.2 Unit 10 - The Town That Came Back - fourteen figures, as data."""
FIGURES = {
"fig_a22_u10_p00_v01": dict(type='V1', height=830, storey_h=150,
 title='Strand Road, the following September',
 sub='Ten things to find. Three of them are new words for old things.',
 alt='A coastal street a year after a flood with a repainted shopfront, a new town sign, a bus '
     'of visitors, scaffolding coming off and a watermark left on purpose.',
 sky='#E0E6E7', ground='#A1A7A6', ground_line=660,
 buildings=[dict(x=20, w=420, storeys=2, colour='#D8D3C6', label='14 Strand Road'),
   dict(x=490, w=340, storeys=2, colour='#CFCABC', label='the repainted terrace'),
   dict(x=880, w=300, storeys=1, colour='#D4CEBE', label='the community hall'),
   dict(x=1230, w=350, storeys=2, colour='#C6C1B4', label='the visitor centre')],
 props=[dict(kind='scaffold', x=560, y=660, s=.9),
   dict(kind='van', x=1060, y=660, s=1.1, colour='#2E6F5E'),
   dict(kind='table', x=1300, y=660, s=1.2), dict(kind='doc', x=1300, y=594),
   dict(kind='crate', x=190, y=660, s=1.0),
   dict(kind='sign', x=120, y=660, s=.75, text='12 cm'),
   dict(kind='sign', x=860, y=660, s=.7, text='1884'),
   dict(kind='sign', x=1470, y=660, s=.75, text='CAME BACK')],
 people=[dict(x=260, y=660, h=86, skin=0, cloth=1, hair='long', arm='point'),
   dict(x=450, y=660, h=85, skin=1, cloth=0, hair='cap', arm='hold'),
   dict(x=760, y=660, h=86, skin=0, cloth=2, hair='bun', arm='down'),
   dict(x=1140, y=660, h=85, skin=2, cloth=3, hair='short', arm='hold'),
   dict(x=1400, y=660, h=86, skin=2, cloth=1, hair='long', arm='raise')],
 names=[dict(x=260, t='Eimear - the watermark, kept'), dict(x=450, t='Donal, unchanged'),
   dict(x=760, t='Sinead, and the hall they kept'), dict(x=1140, t='the agency'),
   dict(x=1400, t='Aoife, back for the weekend'), dict(x=120, t='left on purpose'),
   dict(x=1470, t='the line somebody said in February')],
 markers=[dict(x=260, y=548), dict(x=450, y=548), dict(x=760, y=548), dict(x=1140, y=548),
   dict(x=1400, y=548), dict(x=120, y=592), dict(x=860, y=594), dict(x=1470, y=592),
   dict(x=560, y=580), dict(x=1300, y=602)]),

"fig_a22_u10_p01_v08": dict(type='V8', height=780,
 title='Who tells the story, and who is in it',
 sub='Five nodes. The dashed line is the seven households that are not on any of them.',
 alt='A network from an event through memory, the local account, the campaign and the record, '
     'with the people who left shown off to one side.',
 nodes={
  'eve': dict(x=170, y=400, short='1', name='What happened', sub='twelve centimetres', colour='#1F4E5F'),
  'mem': dict(x=510, y=230, short='2', name='Memory', sub='fifty-one households', colour='#2E6F5E'),
  'loc': dict(x=510, y=570, short='3', name='The local account', sub='said first in February', colour='#C86B2B'),
  'cam': dict(x=890, y=400, short='4', name='The campaign', sub='three years, nine thousand', r=54, colour='#D9A441'),
  'rec': dict(x=1280, y=400, short='5', name='The record', sub='in ten years, this is all', r=54, colour='#8C6A9E')},
 edges=[dict(a='eve', b='mem', label='and it is already unreliable', sw=5),
   dict(a='mem', b='loc', label='a sentence, in the hall, unattributed', sw=5),
   dict(a='loc', b='cam', label='the agency did not invent it', sw=5),
   dict(a='cam', b='rec', label='and this is what survives', sw=5),
   dict(a='eve', b='rec', label='the seven who left', sw=2, dash='6 6', colour='#9AA7AE')]),

"fig_a22_u10_p01_v02": dict(type='V2', height=780,
 title="Eimear's kitchen, in section",
 sub='Four levels, one year, and one of them has been left exactly as it was.',
 alt='A kitchen drawn in section showing the ceiling, the wall with a watermark, the new floor '
     'and the sub-floor, each labelled with what changed.',
 floors=[dict(was='the ceiling', now='Repainted in May. Nothing happened up here at all',
     year='May', fill='#EDE7DA'),
   dict(was='the wall at 12 cm', now='The watermark. Left on purpose, and nobody agreed to it',
     year='-', fill='#EFE2DD'),
   dict(was='the floor', now='Laid in August. A slightly different colour', year='Aug',
     fill='#E6EFE9'),
   dict(was='under the floor', now='Dry since June. Measured four times to be sure', year='Jun',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='The only part that cost nothing'),
   dict(at=0.38, text='Twelve centimetres. She has never said why she kept it'),
   dict(at=0.62, text='Not the colour she chose, and she has decided not to mind'),
   dict(at=0.88, text='Eight months, and you cannot tell by looking')]),

"fig_a22_u10_p02_v07": dict(type='V7', height=800,
 title='The brochure',
 sub='One of them has a campaign. The other has a year of arguing about accuracy.',
 alt='An agency account manager and a resident at a table with a brochure proof between them, '
     'speech bubbles turning on articles.',
 bg='#EAECEC',
 set=[dict(kind='table', x=700, y=680, s=1.4), dict(kind='doc', x=700, y=608)],
 people=[dict(x=470, h=242, skin=2, cloth=3, hair='short', arm='point', facing='right',
   label='the agency', role='three years', says=["It's a story about a town."]),
  dict(x=970, h=240, skin=0, cloth=1, hair='long', arm='folded', facing='left',
   label='Eimear', role='14 Strand Road', says=["It's the story of this town.",
     "And that's not what happened."])]),

"fig_a22_u10_p03_v09": dict(type='V9', kind='scope', height=580,
 title='One word, two towns',
 sub='The only difference between these two sentences is an article, and they are about '
     'different places.',
 alt='Two near-identical sentences with brackets marking the indefinite and definite articles '
     'and what each one implies.',
 words=['A', 'town', 'came', 'back', '/', 'THE', 'town', 'came', 'back'],
 focus=[0, 5],
 brackets=[dict(**{'from': 0, 'to': 3}, lane=0, label='any town. A general claim',
     colour='#9AA7AE'),
   dict(**{'from': 5, 'to': 8}, lane=0, label='this one, and we both know which',
     colour='#1F4E5F'),
   dict(**{'from': 5, 'to': 5}, lane=1, label='one word, and the whole argument is here',
     colour='#A8372E')]),

"fig_a22_u10_p03_v09b": dict(type='V9', kind='ladder', height=720,
 title='From no article to the',
 sub='Five steps, from a thing in general to the one thing we are both looking at.',
 alt='A ladder from bare plural nouns through a and an to the and this, with an example on each '
     'rung.',
 top_label='this one, and no other', bottom_label='in general',
 steps=[dict(form='THIS town', meaning='pointing. And you can see where I am pointing'),
   dict(form='THE town', meaning='we both know which, and nobody has to say'),
   dict(form='A town', meaning='one of several. First mention'),
   dict(form='SUCH a town', meaning='one of that kind - and the kind has just been described'),
   dict(form='Towns change. Water is heavy.', meaning='no article. General, plural or uncountable')],
 rule='Abstract nouns: no article when general, the when specified. Truth matters. The truth '
      'about that night.'),

"fig_a22_u10_p04_v04": dict(type='V4', height=720,
 title='Fifty-one households, and forty-four',
 sub='Learner A has the brochure. Learner B has the survey. The same town, a year apart.',
 alt='Two panels comparing a brochure photograph of a full street and the same street with seven '
     'shut houses.',
 differences=7, prompt='Which seven differences are the same difference?',
 left=dict(label='the brochure', art=[
   dict(kind='person', x=130, y=0, h=108, skin=0, cloth=1),
   dict(kind='person', x=200, y=0, h=110, skin=1, cloth=0),
   dict(kind='person', x=270, y=0, h=108, skin=2, cloth=3),
   dict(kind='person', x=340, y=0, h=110, skin=0, cloth=2),
   dict(kind='person', x=410, y=0, h=108, skin=1, cloth=4),
   dict(kind='label', x=300, y=200, text='"a community of fifty-one households"',
        colour='#D9A441')]),
 right=dict(label='the street', art=[
   dict(kind='person', x=150, y=0, h=108, skin=0, cloth=1),
   dict(kind='person', x=230, y=0, h=110, skin=1, cloth=0),
   dict(kind='gap', x=310, y=10, w=60, bh=90),
   dict(kind='gap', x=390, y=10, w=60, bh=90),
   dict(kind='label', x=300, y=200, text='forty-four, and seven shut', colour='#A8372E')])),

"fig_a22_u10_p05_v05": dict(type='V5', height=1010,
 title='The brochure page',
 sub='Six photographs, four numbers, and the number fourteen does not appear.',
 alt='A tourism brochure page for a recovered town showing the headline, photograph captions, '
     'the numbers used and the funding small print.',
 rows=[dict(t='org', text='FAILTE WEST  -  BALLINMORE  -  PAGE 2'),
   dict(t='head', text='THE HEADLINE'),
   dict(t='para', text='"THE TOWN THAT CAME BACK"'),
   dict(t='rule'),
   dict(t='head', text='THE NUMBERS THAT APPEAR'),
   dict(t='grid', cols=['FIGURE', 'USED AS', 'TRUE?'],
     data=[['51 households', '"a community of 51 households"', 'was, in January'],
           ['8 months', '"eight months of work"', 'yes'],
           ['200 people', '"two hundred in the hall"', 'yes'],
           ['1884', '"a hall built in 1884"', 'yes']]),
   dict(t='rule'),
   dict(t='head', text='THE NUMBERS THAT DO NOT'),
   dict(t='kv', k='Households gone', v='7', mono=True),
   dict(t='kv', k='As a percentage', v='14 %', mono=True),
   dict(t='kv', k='Hall completion', v='not stated', mono=False),
   dict(t='rule'),
   dict(t='head', text='CAPTIONS'),
   dict(t='para', text='Photograph 4 is captioned "the hall, in use again". The hall is in use '
     'and is not finished. No caption says it is finished.'),
   dict(t='rule'),
   dict(t='head', text='SMALL PRINT, FOOT OF PAGE'),
   dict(t='para', text='"Campaign funded by the county council and the regional tourism fund. '
     'Photographs by residents."'),
   dict(t='rule'),
   dict(t='sign', text='THE LINE THE TOWN ASKED FOR, ADDED IN PROOF 3:'),
   dict(t='para', text='"...and one household who has asked not to be named."')],
 callouts=[dict(at=0.09, text='Six words, and the town said them first'),
   dict(at=0.26, text='Was fifty-one. The tense is doing a lot of work'),
   dict(at=0.56, text='Seven, and fourteen per cent, and neither is on the page'),
   dict(at=0.62, text='Nobody claims the hall is finished - and nobody says it is not'),
   dict(at=0.80, text='Photographs by residents, which is why nobody can object to them'),
   dict(at=0.94, text='Eleven words, added at proof three, and the best line on the page')]),

"fig_a22_u10_p06_v03a": dict(type='V3', height=640,
 title='A thing, a kind of thing, and the thing',
 sub='Four steps from a noun with nothing in front of it to one with a finger pointing at it.',
 alt='A four-panel strip showing a bare noun, an indefinite article, a definite article and a '
     'demonstrative, each with its example.',
 axis_start='general', axis_end='this one',
 panels=[dict(caption='NO ARTICLE - all of them, everywhere', art=[
     dict(kind='block', x=100, y=20, w=50, bh=44, colour='#9AA7AE'),
     dict(kind='block', x=170, y=20, w=50, bh=44, colour='#9AA7AE'),
     dict(kind='block', x=240, y=20, w=50, bh=44, colour='#9AA7AE'),
     dict(kind='label', x=160, y=180, text='towns change / truth matters', colour='#9AA7AE')]),
   dict(caption='A - one of several, first mention', art=[
     dict(kind='block', x=180, y=20, w=70, bh=44, colour='#C86B2B'),
     dict(kind='label', x=160, y=180, text='a town / a story / a kind of', colour='#C86B2B')]),
   dict(caption='THE - and we both know which', art=[
     dict(kind='block', x=180, y=20, w=70, bh=44, colour='#1F4E5F'),
     dict(kind='tick', x=300, y=40),
     dict(kind='label', x=160, y=180, text='the town / the truth about it', colour='#1F4E5F')]),
   dict(caption='THIS - and I am pointing at it', art=[
     dict(kind='person', x=160, y=0, h=112, skin=0, cloth=1, arm='point'),
     dict(kind='label', x=160, y=185, text='this town / that winter / such a story',
       colour='#2E6F5E')])]),

"fig_a22_u10_p06_v04b": dict(type='V4', height=700,
 title='A STORY ABOUT A TOWN, and THE STORY OF THE TOWN',
 sub='Two sentences, four articles, and only one of them can be argued with.',
 alt='Two panels comparing a generic claim about any town and a specific claim about one town.',
 differences=6, prompt='Which one can somebody who lives there contradict?',
 left=dict(label='a story about a town', art=[
   dict(kind='block', x=140, y=0, w=60, bh=60, colour='#9AA7AE'),
   dict(kind='block', x=220, y=0, w=60, bh=60, colour='#9AA7AE'),
   dict(kind='block', x=300, y=0, w=60, bh=60, colour='#9AA7AE'),
   dict(kind='label', x=300, y=200, text='any town. Nobody can object', colour='#9AA7AE')]),
 right=dict(label='the story of the town', art=[
   dict(kind='block', x=240, y=0, w=110, bh=80, colour='#1F4E5F'),
   dict(kind='person', x=400, y=0, h=112, skin=0, cloth=1, arm='point'),
   dict(kind='label', x=300, y=200, text='this one, and seven people are not in it',
        colour='#1F4E5F')])),

"fig_a22_u10_p07_v10": dict(type='V10', kind='elision', height=640,
 title='One word, two sounds, three jobs',
 sub='The has a weak form, a strong form, and a stressed form that means something else again.',
 alt='Five phrases with the shown written and spoken, as a schwa before consonants, as /i:/ '
     'before vowels, and stressed.',
 pairs=[dict(written='the town', spoken='ðə taʊn', dropped='', note='before a consonant: /ðə/'),
   dict(written='the only one', spoken='ðiː əʊnli wʌn', dropped='',
     note='before a vowel sound: /ðiː/'),
   dict(written='the hall', spoken='ðə hɔːl', dropped='', note='h counts as a consonant here'),
   dict(written='the hour', spoken='ðiː aʊə', dropped='', note='and here it does not'),
   dict(written='THE town', spoken='ðiː taʊn', dropped='',
     note='stressed: the real one, and no other')]),

"fig_a22_u10_p08_v06": dict(type='V6', kind='bar', height=780,
 title='Fifty-one households, before and after',
 sub='The same street, counted in January, in September, and a year later.',
 alt='A bar chart of household occupancy on one street across three counts, showing seven '
     'households gone by the second year.',
 labels=['Jan, before', 'Jan, after', 'Mar', 'Jun', 'Sep', 'a year on'],
 ymin=0, ymax=55, fmt='{:,.0f}',
 series=[dict(name='households occupied', values=[51, 37, 39, 44, 46, 44], colour='#2E6F5E'),
   dict(name='households gone for good', values=[0, 0, 2, 4, 6, 7], colour='#A8372E')],
 note='Occupancy recovered to forty-six by September and then fell to forty-four, because two '
      'households that had come back sold in the following spring.',
 warning='The brochure says "a community of fifty-one households". That was true in January, '
         'before the water, and the tense in the sentence does the rest.'),

"fig_a22_u10_p09_v03b": dict(type='V3', height=640,
 title='Saying no to a client and still being there at minute ten',
 sub='Four moves. The second one is where most of these conversations fail.',
 alt='A four-panel strip of a client meeting: hearing the objection, separating what can and '
     'cannot change, offering something real, and writing it down.',
 axis_start='minute 0', axis_end='minute 20',
 panels=[dict(caption='"Say that again - I want to get it right."', art=[
     dict(kind='person', x=170, y=0, h=112, skin=2, cloth=3, arm='hold'),
     dict(kind='label', x=160, y=185, text='hearing it properly, and slowly',
       colour='#1F4E5F')]),
   dict(caption='"The line is in print. The captions aren\'t."', art=[
     dict(kind='block', x=120, y=20, w=100, bh=50, colour='#A8372E'),
     dict(kind='block', x=240, y=20, w=100, bh=50, colour='#2E6F5E'),
     dict(kind='label', x=160, y=180, text='what cannot change, and what can',
       colour='#2E6F5E')]),
   dict(caption='"We can add a page, and you write it."', art=[
     dict(kind='doc', x=170, y=20),
     dict(kind='label', x=160, y=190, text='something real, not a gesture', colour='#D9A441')]),
   dict(caption='"Your page, our line, and we both sign off the proof."', art=[
     dict(kind='tick', x=190, y=60),
     dict(kind='label', x=160, y=185, text='and now it exists', colour='#2E6F5E')])]),

"fig_a22_u10_p10_v12": dict(type='V12', height=840,
 title='A sentence about yourselves',
 sub='Half the class sees the brochure. Half sees the feature. Rebuild the argument by speaking.',
 alt='An infographic of a town campaign from the sentence first said in a hall through the '
     'brochure proofs to the funded drain.',
 span=['February', 'two years on'], ticks=6,
 tick_labels=['Feb', 'the offer', 'proof 1', 'proof 3', 'year 1', 'year 2'],
 bands=[dict(name='The sentence', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.22}, label='said in the hall, unattributed', colour='#C86B2B'),
   dict(**{'from': 0.22, 'to': 0.56}, label='the agency line, in print', colour='#D9A441'),
   dict(**{'from': 0.56, 'to': 1.0}, label='the line, and the page', colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.22, label='campaign offered - three years, nine thousand a year', colour='#D9A441'),
   dict(at=0.38, label='"that is not what happened"', colour='#A8372E'),
   dict(at=0.56, label='one page, written by the town', colour='#2E6F5E'),
   dict(at=0.62, label='six of the seven agree to be named', colour='#1F4E5F'),
   dict(at=0.96, label='drain funded - mostly by the county, who were going to anyway',
     colour='#8C6A9E')]),
  dict(name='Visitors, thousands', type='line',
   points=[(0.56, 0), (0.7, 2.4), (0.84, 6.0), (0.92, 6.3), (1.0, 6.1)], end_label='6,100'),
  dict(name='What the page carries', type='flags', items=[
   dict(at=0.30, label='seven households, fourteen per cent'),
   dict(at=0.58, label='six names, with permission'),
   dict(at=0.74, label='"and one household who has asked not to be named"'),
   dict(at=0.98, label='in ten years, this is the record')])]),
}
