"""B1.1 Unit 4 · Nobody's Job — the twelve figures, as data."""
FIGURES = {
"fig_b11_u04_p00_v01": dict(type='V1', height=900, storey_h=150,
 title='Jengo House, the parts nobody owns',
 sub='Twelve things in this picture are somebody\'s responsibility. Three have no name against them.',
 alt='A shared workspace building cut open across four floors, showing fire doors, extinguishers, '
     'a blocked corridor, trailing cables and people moving between floors.',
 sky='#E8EDEA', ground='#B9AC97', ground_line=720,
 buildings=[dict(x=60, w=1480, storeys=4, colour='#F4EEE2', cutaway=True,
                 floor_labels=['storage — one exit', 'studios — fire door propped',
                               'the workspace — cables', 'ENTRANCE — no accessible WC'])],
 props=[dict(kind='sign', x=240, y=720, s=.7, text='FIRE EXIT'),
        dict(kind='box', x=420, y=720, s=1.0), dict(kind='box', x=490, y=720, s=1.0),
        dict(kind='table', x=900, y=720, s=1.4),
        dict(kind='crate', x=1240, y=720, s=1.0),
        dict(kind='sign', x=1430, y=720, s=.7, text='NO RAMP')],
 people=[dict(x=330, y=720, h=86, skin=1, cloth=3, hair='long', arm='hold'),
         dict(x=620, y=720, h=84, skin=4, cloth=0, hair='short', arm='point'),
         dict(x=980, y=720, h=86, skin=2, cloth=2, hair='wrap', arm='down'),
         dict(x=1340, y=720, h=85, skin=0, cloth=5, hair='short', arm='hold')],
 names=[dict(x=240,t='fire exit, blocked'), dict(x=455,t='stored in the corridor'),
        dict(x=620,t='Wanjiru'), dict(x=900,t='the desk'),
        dict(x=1240,t='first-aid box, 2019'), dict(x=1430,t='three steps, no ramp')],
 markers=[dict(x=250,y=686),dict(x=455,y=692),dict(x=1240,y=694),dict(x=1430,y=676),
          dict(x=760,y=560),dict(x=300,y=420),dict(x=1100,y=300),dict(x=820,y=690)]),

"fig_b11_u04_p01_v08": dict(type='V8', height=820,
 title='Who owes what to whom',
 sub='Each line is a duty. Two of them are drawn dashed, because nobody has ever confirmed them.',
 alt='A network of six parties — landlord, tenants, individual, insurer, inspector and regulator '
     '— with the duties between them, two of which are unconfirmed.',
 nodes={
  'reg':   dict(x=820,  y=120, short='REG', name='The regulator', sub='sets the rule', colour='#1F4E5F'),
  'insp':  dict(x=330,  y=330, short='INSP', name='The inspector', sub='reports, does not enforce', colour='#8C6A9E'),
  'land':  dict(x=820,  y=400, short='LL', name='The landlord', sub='owns the common parts', r=56, colour='#C86B2B'),
  'ten':   dict(x=1330, y=330, short='TEN', name='The tenants', sub='occupy, do not own', colour='#2E6F5E'),
  'ind':   dict(x=820,  y=700, short='YOU', name='The individual', sub='bears it either way', r=56, colour='#A8372E'),
  'ins':   dict(x=1330, y=680, short='INS', name='The insurer', sub='asks questions later', colour='#D9A441')},
 edges=[dict(a='reg', b='land', label='duty of care', sw=4),
        dict(a='reg', b='insp', label='appoints', sw=2),
        dict(a='insp', b='land', label='reports "for attention"', sw=3, dash='7 5'),
        dict(a='land', b='ten', label='the lease', sw=4),
        dict(a='ten', b='ind', label='no formal duty', sw=2, dash='7 5', colour='#9AA7AE'),
        dict(a='land', b='ind', label='duty of care, in principle', sw=3),
        dict(a='ins', b='land', label='asks about the report', sw=3, colour='#D9A441')]),

"fig_b11_u04_p02_v07": dict(type='V7', height=840,
 title='Three people, one problem, no name on it',
 sub='Watch who is facing whom. One of them has not turned round at all.',
 alt='Three people in a meeting, two talking across each other and one turned away.',
 bg='#ECEEEA',
 set=[dict(kind='table', x=560, y=690, s=2.2)],
 people=[dict(x=400, h=250, skin=3, cloth=0, hair='long', arm='hold', facing='right',
              label='Wanjiru', role='chairing', says=["We have to do something."]),
         dict(x=860, h=252, skin=4, cloth=5, hair='grey', arm='folded', facing='front',
              label='Mr Kamau', role='landlord',
              says=['We were never required to.'], thinks=['Required by whom, though.']),
         dict(x=1300, h=248, skin=1, cloth=2, hair='short', arm='down', facing='left',
              label='Priya', role='seven months', says=['Fine.'])]),

"fig_b11_u04_p03_v09": dict(type='V9', kind='ladder', height=780,
 title='Obligation, from binding to free',
 sub='Two of these are opposites that look like variants.',
 alt='A vertical ladder of modal forms from must at the top through should and may to needn\'t and '
     'mustn\'t, with their meanings.',
 top_label='no choice', bottom_label='forbidden',
 steps=[dict(form='must / have to', meaning='you are obliged — there is no version where you do not'),
        dict(form='had to', meaning='you were obliged. must has no past; this is it'),
        dict(form='be supposed to', meaning='expected, and everybody knows it is sometimes skipped'),
        dict(form='should / ought to', meaning='advised. a real cost if you do not, but not a rule'),
        dict(form='can / may / be allowed to', meaning='permitted. the door is open'),
        dict(form="don't have to / needn't", meaning='released. the door is open and you may leave'),
        dict(form='needn\'t have', meaning='you did it, and it turned out not to be necessary'),
        dict(form="mustn't / isn't allowed to", meaning='forbidden. the opposite of the two above')],
 rule="mustn't and don't have to are opposites, not variants. One forbids; one releases."),

"fig_b11_u04_p03_v11": dict(type='V11', height=640,
 title='Why this sentence gives permission instead of refusing it',
 alt='Two panels contrasting "you don\'t have to sign" with "you mustn\'t sign".',
 wrong=dict(sentence="You don't have to sign this — it's not safe.",
            boundary=0.50, boundary_label='the line', event=0.76,
            event_label='door open', why="don't have to releases the listener. It says the choice "
            'is theirs. If the point is that signing would be wrong, this sentence invites it.'),
 right=dict(sentence="You mustn't sign this — it's not safe.",
            boundary=0.50, boundary_label='the line', event=0.22,
            event_label='door closed', why='mustn\'t forbids. The listener now knows there is no '
            'version of this where signing is acceptable.'),
 misconception="The writer treated mustn't as a stronger don't have to. It is not stronger. It "
               'points the other way.'),

"fig_b11_u04_p04_v04": dict(type='V4', height=720,
 title='The same ten minutes, chaired and not chaired',
 sub='Learner A holds the lease. Learner B holds the inspection. Neither sees the other.',
 alt='Two meeting timelines side by side: one circling without a decision, one reaching a named '
     'action with a date.',
 differences=8, prompt='Describe only. Find out whose obligation this is.',
 left=dict(label='forty minutes, no decision', art=[
   dict(kind='block', x=120, y=0, w=46, bh=40, colour='#9AA7AE'),
   dict(kind='block', x=190, y=0, w=46, bh=56, colour='#9AA7AE'),
   dict(kind='block', x=260, y=0, w=46, bh=34, colour='#9AA7AE'),
   dict(kind='block', x=330, y=0, w=46, bh=62, colour='#9AA7AE'),
   dict(kind='block', x=400, y=0, w=46, bh=30, colour='#9AA7AE'),
   dict(kind='cross', x=500, y=60),
   dict(kind='label', x=300, y=220, text='"revisit at a future meeting"', colour='#A8372E')]),
 right=dict(label='ten minutes, one decision', art=[
   dict(kind='block', x=140, y=0, w=70, bh=48, colour='#1F4E5F'),
   dict(kind='block', x=240, y=0, w=70, bh=120, colour='#C86B2B'),
   dict(kind='block', x=340, y=0, w=70, bh=64, colour='#2E6F5E'),
   dict(kind='tick', x=470, y=60),
   dict(kind='label', x=300, y=220, text='Obi · three quotes · 14 March', colour='#2E6F5E')])),

"fig_b11_u04_p05_v05": dict(type='V5', height=1020,
 title='The 2019 inspection report',
 sub='Nine hundred words. One sentence is the one everything since has depended on.',
 alt='A premises inspection report listing items for attention, with a compliance statement and a '
     'signature in a stated capacity.',
 rows=[dict(t='org', text='PREMISES INSPECTION · REPORT 2019/0774'),
   dict(t='kv', k='Premises', v='Jengo House, Ngong Lane'),
   dict(t='kv', k='Date of inspection', v='19 September 2019', mono=True),
   dict(t='kv', k='Inspected under', v='Occupational Safety regulations then in force'),
   dict(t='rule'),
   dict(t='head', text='Finding'),
   dict(t='para', text='The premises were found to be in substantial compliance with the '
        'regulations then in force. Three items are noted below for attention. None constitutes a '
        'contravention at the date of inspection.'),
   dict(t='rule'),
   dict(t='grid', cols=['#', 'ITEM', 'STATUS', 'ACTION BY'],
     data=[['1', 'Fire door, second floor, propped', 'for attention', 'occupier'],
           ['2', 'First-aid provision not signed', 'for attention', 'occupier'],
           ['3', 'No accessible sanitary facility', 'for attention', '—']]),
   dict(t='rule'),
   dict(t='head', text='Future obligations'),
   dict(t='para', text='Where a material change of use is undertaken, the premises will be '
        'assessed against the regulations in force at that date and items noted above may become '
        'requirements in due course.'),
   dict(t='rule'),
   dict(t='kv', k='Signed', v='E. Wanyama'),
   dict(t='kv', k='In the capacity of', v='Inspecting Officer (reporting only)', bold=True),
   dict(t='small', text='This report records the condition of the premises at the date of '
        'inspection. It does not constitute approval, certification or a direction to act. The '
        'allocation of responsibility between owner and occupier is a matter for the lease.')],
 callouts=[dict(at=0.20, text='"Then in force" — the whole argument is in three words'),
   dict(at=0.29, text='Substantial, not full. Nobody defines the gap'),
   dict(at=0.46, text='Item 3 has no action-by at all'),
   dict(at=0.60, text='"May become requirements" — and did, in 2021'),
   dict(at=0.78, text='Reporting only. He cannot make anybody do anything'),
   dict(at=0.90, text='And here it is handed to the lease')]),

"fig_b11_u04_p06_v02": dict(type='V2', height=820,
 title='One obligation, six strengths',
 sub='The same duty, worded six ways. Each layer is easier to walk away from.',
 alt='A sectioned diagram of six strengths of obligation with the typical wording at each level.',
 floors=[dict(was='in the regulations', now='"Premises must provide…"', year='enforceable', fill='#DCE6EA'),
   dict(was='in the lease', now='"The landlord shall maintain…"', year='actionable', fill='#E4ECEF'),
   dict(was='in the inspection', now='"Noted for attention."', year='no actor named', fill='#F2EDE2'),
   dict(was='in the minutes', now='"It was agreed we would look at…"', year='no date', fill='#F6F0E4'),
   dict(was='in an email', now='"Happy to revisit if anything changes."', year='conditional on nothing', fill='#F6E6D6'),
   dict(was='in conversation', now='"Someone should really…"', year='nobody', fill='#F3DCDC')],
 callouts=[dict(at=0.10, text='Only the top two name an actor'),
   dict(at=0.33, text='"For attention" by whom? The report does not say'),
   dict(at=0.55, text='An agreement with no date is a feeling'),
   dict(at=0.76, text='"If anything changes" — nothing has to'),
   dict(at=0.93, text='This is where most duties actually live')]),

"fig_b11_u04_p07_v10": dict(type='V10', kind='elision', height=640,
 title='Modals vanish in the middle of a sentence',
 sub='Every one of these is two syllables in real speech, not three.',
 alt='Six modal phrases shown written and spoken, with the reduced forms marked.',
 pairs=[dict(written='have to', spoken='hæf_tə', dropped='_', note='the /v/ becomes /f/'),
   dict(written='has to', spoken='hæs_tə', dropped='_', note='the /z/ becomes /s/'),
   dict(written='had to', spoken='hæd_tə', dropped='_', note='two /d/ sounds become one'),
   dict(written='must have', spoken='mʌs_təv', dropped='_', note='have → /əv/, never /hæv/'),
   dict(written='should have', spoken='ʃʊd_əv', dropped='_', note='never "should of" in writing'),
   dict(written='ought to', spoken='ɔː_tə', dropped='_', note='the /t/ does double duty')]),

"fig_b11_u04_p08_v06": dict(type='V6', kind='bar', height=820,
 title='What actually happens to an action point',
 sub='Four hundred meeting actions, followed up twelve weeks later.',
 alt='A bar chart comparing completion rates for meeting actions with a named person and a date '
     'against those with neither.',
 labels=['name + date', 'name, no date', 'date, no name', 'neither'],
 ymin=0, ymax=100, fmt='{:,.0f}%',
 series=[dict(name='done within 12 weeks', values=[78, 41, 29, 9], colour='#2E6F5E'),
   dict(name='still open', values=[22, 59, 71, 91], colour='#A8372E')],
 note='The gap between the first bar and the last is not about effort or goodwill. It is about '
      'whether anybody in the room could say, afterwards, who was supposed to do it.',
 warning='One organisation, one year. The shape is robust; the numbers are not.'),

"fig_b11_u04_p10_v12": dict(type='V12', height=880,
 title='Seven years of one missing toilet',
 sub='Half the class sees the obligations. Half sees what happened. Neither sees both.',
 alt='An infographic tracking a building accessibility issue across seven years, showing rule '
     'changes, who was obliged, what was said, and who was affected.',
 span=['2019', '2026'], ticks=6,
 tick_labels=['2019', '2020', '2021', '2023', '2025', '2026'],
 bands=[dict(name='The rule', type='events', items=[
     dict(at=0.00, label='inspection — "for attention"', colour='#8C6A9E'),
     dict(at=0.30, label='regulation tightened', colour='#1F4E5F'),
     dict(at=0.52, label='change of use — studios', colour='#C86B2B'),
     dict(at=0.95, label='insurer asks about 2019', colour='#D9A441')]),
   dict(name='Who was obliged', type='bars', items=[
     dict(**{'from': 0.0, 'to': 1.0}, label='nobody, formally', colour='#9AA7AE'),
     dict(**{'from': 0.52, 'to': 1.0}, label='arguably the landlord, from the conversion', colour='#C86B2B'),
     dict(**{'from': 0.95, 'to': 1.0}, label='the insurer made it his', colour='#D9A441')]),
   dict(name='Who was affected', type='line',
     points=[(0,0),(0.3,1),(0.52,1),(0.72,2),(0.88,3),(1.0,2)], end_label='people'),
   dict(name='What was said', type='flags', items=[
     dict(at=0.04, label='"noted"'), dict(at=0.34, label='"not required to"'),
     dict(at=0.74, label='seven months of nothing'), dict(at=0.97, label='paid half')])]),

"fig_b11_u04_p09_v05": dict(type='V5', height=940,
 title='Two agendas for the same meeting',
 sub='One of these takes forty minutes. One takes ten. Nothing else differs.',
 alt='Two meeting agendas side by side in a circulated email, one with three bare items and one '
     'with a decision, a time and an owner against each line.',
 rows=[dict(t='org', text='JENGO HOUSE · TENANTS\' MEETING · CIRCULATED MONDAY'),
   dict(t='head', text='AGENDA A — as circulated in February'),
   dict(t='grid', cols=['#', 'ITEM'],
     data=[['1', 'Accessibility'], ['2', 'The lease'], ['3', 'AOB']]),
   dict(t='small', text='No times. No owners. No statement of what the meeting is for. Item 1 is '
        'a topic, not a question, so it cannot be finished — only left.'),
   dict(t='rule'),
   dict(t='head', text='AGENDA B — as circulated in March'),
   dict(t='grid', cols=['#', 'DECISION NEEDED', 'MIN', 'BRINGS IT', 'PAPERS'],
     data=[['1', 'Do we fund the survey ourselves?', '10', 'Wanjiru', '2019 report, quote'],
           ['2', 'AOB', '3', '—', '—']]),
   dict(t='rule'),
   dict(t='head', text='Standing note at the foot of every agenda'),
   dict(t='para', text='Any item that reaches the end of its time without a named person and a '
        'date is carried, and the chair will say so out loud. Items without papers attached are '
        'not taken.'),
   dict(t='sign', text='— circulated by W.M., 48 hours before')],
 callouts=[dict(at=0.17, text='A topic. You cannot finish a topic'),
   dict(at=0.26, text='Three items, no times — so all of them overrun'),
   dict(at=0.48, text='A question with a yes or a no at the end of it'),
   dict(at=0.54, text='Ten minutes, and somebody owns the ten'),
   dict(at=0.60, text='Papers named, so nobody can say they had not seen them'),
   dict(at=0.82, text='The rule that makes the chair\'s job possible')]),
}
