"""B1.1 Unit 5 · The Rota — the twelve figures, as data."""
FIGURES = {
"fig_b11_u05_p00_v01": dict(type='V1', height=900, storey_h=150,
 title='The shared office, Monday, 08.20',
 sub='Two rotas in this room. They do not match. One of them is the one people follow.',
 alt='A shared open-plan office cut open across four floors, with a whiteboard rota, a wall screen '
     'showing a different rota, desks, a key board and five people arriving.',
 sky='#E9EDF0', ground='#B5AB99', ground_line=720,
 buildings=[dict(x=60, w=1480, storeys=4, colour='#F4EEE2', cutaway=True,
   floor_labels=['storage', 'studios', 'THE WORKSPACE — eleven desks', 'entrance'])],
 props=[dict(kind='sign', x=250, y=720, s=.8, text='ROTA'),
        dict(kind='table', x=520, y=720, s=1.8), dict(kind='table', x=860, y=720, s=1.8),
        dict(kind='box', x=1230, y=720, s=1.0), dict(kind='crate', x=1340, y=720, s=1.0),
        dict(kind='sign', x=1450, y=720, s=.8, text='KEYS')],
 people=[dict(x=330, y=720, h=86, skin=2, cloth=3, hair='wrap', arm='point'),
         dict(x=600, y=720, h=84, skin=0, cloth=0, hair='short', arm='hold'),
         dict(x=940, y=720, h=86, skin=4, cloth=4, hair='long', arm='down'),
         dict(x=1140, y=720, h=85, skin=1, cloth=2, hair='short', arm='hold'),
         dict(x=1420, y=720, h=84, skin=5, cloth=1, hair='grey', arm='down')],
 names=[dict(x=250,t='whiteboard rota — hand-edited'), dict(x=430,t='Grace, four Sundays running'),
        dict(x=600,t='Tom, who built it'), dict(x=940,t='the screen rota'),
        dict(x=1230,t='sign-in sheet'), dict(x=1450,t='key board')],
 markers=[dict(x=250,y=676),dict(x=940,y=660),dict(x=1230,y=694),dict(x=1450,y=672),
          dict(x=700,y=560),dict(x=330,y=420),dict(x=1100,y=300),dict(x=520,y=690)]),

"fig_b11_u05_p01_v08": dict(type='V8', height=820,
 title='The shape of an automated decision',
 sub='Six stages. The dashed one is the one this system does not have.',
 alt='A flow network from input through threshold and algorithm to output, with audit, override '
     'and fallback branches, one drawn dashed because it is absent.',
 nodes={
  'in':   dict(x=180,  y=400, short='IN', name='Input', sub='availability, hours, seniority', colour='#1F4E5F'),
  'thr':  dict(x=500,  y=240, short='≥', name='Threshold', sub='two nights, max', colour='#8C6A9E'),
  'alg':  dict(x=680,  y=440, short='fn', name='The algorithm', sub='weights and breaks ties', r=58, colour='#C86B2B'),
  'out':  dict(x=1020, y=300, short='OUT', name='Output', sub='the rota, published', colour='#2E6F5E'),
  'ovr':  dict(x=1020, y=620, short='!', name='Override', sub='email, 48 hours', colour='#A8372E'),
  'aud':  dict(x=1360, y=440, short='LOG', name='Audit trail', sub='who changed what', colour='#D9A441')},
 edges=[dict(a='in', b='alg', label='raw data', sw=5),
        dict(a='thr', b='alg', label='the hard rule', sw=3),
        dict(a='alg', b='out', label='every Friday', sw=5),
        dict(a='out', b='ovr', label='if somebody objects', sw=2, dash='7 5'),
        dict(a='ovr', b='alg', label='manual change', sw=2, dash='7 5', colour='#A8372E'),
        dict(a='out', b='aud', label='logged', sw=3, colour='#D9A441'),
        dict(a='ovr', b='aud', label='not logged', sw=2, dash='4 6', colour='#9AA7AE')]),

"fig_b11_u05_p02_v07": dict(type='V7', height=840,
 title='The person who built it, and the person on it',
 sub='He is facing the screen. She is facing him.',
 alt='Two people in an office, one turned towards a wall screen and one turned towards him, with '
     'speech and thought bubbles.',
 bg='#EAEEF0',
 set=[dict(kind='table', x=620, y=690, s=2.0), dict(kind='sign', x=1420, y=690, s=.9, text='ROTA')],
 people=[dict(x=520, h=252, skin=0, cloth=0, hair='short', arm='point', facing='right',
              label='Tom', role='built it fourteen months ago',
              says=["It's working, actually.", 'Two changes a week, not twelve.'],
              thinks=['That is not what she asked.']),
         dict(x=1080, h=248, skin=2, cloth=3, hair='wrap', arm='folded', facing='left',
              label='Grace', role='four Sundays running',
              says=['I used to swap with Didier.'])]),

"fig_b11_u05_p03_v09": dict(type='V9', kind='branch', height=720,
 title='Three conditionals, side by side',
 sub='The past form in the third one is not about the past. It marks distance from reality.',
 alt='A branching diagram from one if-clause into zero, first and second conditionals with their '
     'forms and what each one claims about reality.',
 root='if …',
 branches=[dict(label='ZERO — present + present · a rule, always true', colour='#2E6F5E',
                example='If you work nights, you get two days off.'),
   dict(label='FIRST — present + will · a real possibility', colour='#1F4E5F',
        example="If she asks, I'll explain it to her."),
   dict(label='SECOND — past + would · not real, or very unlikely', colour='#8C6A9E', dash='7 5',
        example="If it were up to me, I'd let people swap.")],
 rule='"If we switch it off, we go back" puts it on the table. "If we switched it off, we\'d go '
      'back" takes it off. Same facts, different politics.'),

"fig_b11_u05_p03_v11": dict(type='V11', height=640,
 title='Why this sentence closes the door it meant to open',
 alt='Two panels contrasting a second conditional used for a real proposal against the first '
     'conditional that belongs there.',
 wrong=dict(sentence="If we built an override, it would solve this.",
            boundary=0.50, boundary_label='real / not real', event=0.20,
            event_label='placed outside reality',
            why='The second conditional marks the idea as hypothetical. In a meeting where you '
                'are actually proposing it, you have just told the room it is not on the table.'),
 right=dict(sentence="If we build an override, it will solve this.",
            boundary=0.50, boundary_label='real / not real', event=0.78,
            event_label='placed inside reality',
            why='The first conditional treats it as a live option with a cost and a date. The room '
                'now has something to agree or refuse.'),
 misconception='The writer thought the second conditional was the polite one. It is the distant '
               'one, and distance reads as "I am not seriously asking".'),

"fig_b11_u05_p04_v04": dict(type='V4', height=720,
 title='Six weeks of rota, before and after',
 sub='Learner A holds the rules. Learner B holds what happened. Neither sees the other.',
 alt='Two six-week rota grids side by side, one hand-changed many times and one stable but with '
     'one person repeatedly on Sundays.',
 differences=9, prompt='Find the case the rules did not foresee.',
 left=dict(label='before — the whiteboard', art=[
   dict(kind='block', x=110, y=0, w=40, bh=120, colour='#9AA7AE'),
   dict(kind='block', x=170, y=0, w=40, bh=150, colour='#9AA7AE'),
   dict(kind='block', x=230, y=0, w=40, bh=90, colour='#9AA7AE'),
   dict(kind='block', x=290, y=0, w=40, bh=170, colour='#9AA7AE'),
   dict(kind='block', x=350, y=0, w=40, bh=110, colour='#9AA7AE'),
   dict(kind='block', x=410, y=0, w=40, bh=140, colour='#9AA7AE'),
   dict(kind='label', x=300, y=230, text='12 changes a week · everybody could swap', colour='#A8372E')]),
 right=dict(label='after — the system', art=[
   dict(kind='block', x=110, y=0, w=40, bh=120, colour='#1F4E5F'),
   dict(kind='block', x=170, y=0, w=40, bh=122, colour='#1F4E5F'),
   dict(kind='block', x=230, y=0, w=40, bh=118, colour='#1F4E5F'),
   dict(kind='block', x=290, y=0, w=40, bh=200, colour='#A8372E'),
   dict(kind='block', x=350, y=0, w=40, bh=200, colour='#A8372E'),
   dict(kind='block', x=410, y=0, w=40, bh=200, colour='#A8372E'),
   dict(kind='label', x=300, y=250, text='2 changes a week · one person, four Sundays', colour='#A8372E')])),

"fig_b11_u05_p05_v05": dict(type='V5', height=1020,
 title='The rota specification',
 sub='Three pages, three rules. The word that matters is not in it.',
 alt='A technical specification for a shift allocation system, listing three rules, a tie-break, '
     'and a clause on manual changes requiring written authorisation.',
 rows=[dict(t='org', text='JENGO HOUSE · SHIFT ALLOCATION · SPEC v1.3'),
   dict(t='kv', k='Owner', v='T. Fraser'), dict(t='kv', k='Approved', v='4 October 2024', mono=True),
   dict(t='rule'),
   dict(t='head', text='1 — Allocation rules, in order'),
   dict(t='grid', cols=['#', 'RULE', 'TYPE', 'OVERRIDABLE'],
     data=[['1.1', 'No person works more than two nights consecutively', 'hard', 'no'],
           ['1.2', 'Weight allocation by declared availability', 'soft', 'no'],
           ['1.3', 'Break remaining ties by length of service', 'soft', 'no']]),
   dict(t='rule'),
   dict(t='head', text='2 — Manual changes'),
   dict(t='para', text='Any change to a published rota requires written authorisation from the '
        'space manager, submitted not less than 48 hours in advance, stating the reason. The '
        'system does not support changes made after publication without re-running allocation '
        'for the affected week.'),
   dict(t='rule'),
   dict(t='head', text='3 — Out of scope'),
   dict(t='para', text='Preference ranking, shift trading between individuals, and allocation by '
        'any criterion not listed at 1.1–1.3 are out of scope for this release.'),
   dict(t='rule'),
   dict(t='small', text='Approved by the space manager and the system owner. No consultation with '
        'rota participants was recorded. Review scheduled at twelve months; not yet held.')],
 callouts=[dict(at=0.24, text='A hard rule, and a good one'),
   dict(at=0.30, text='Availability weighted first — this is the whole problem'),
   dict(at=0.36, text='None of the three can be overridden'),
   dict(at=0.54, text='48 hours, in writing, with a reason'),
   dict(at=0.74, text='"Shift trading" — named, and ruled out'),
   dict(at=0.92, text='Nobody on the rota was asked'),
   dict(at=0.96, text='The review is a year overdue')]),

"fig_b11_u05_p06_v02": dict(type='V2', height=820,
 title='From a direct cause to a shrug',
 sub='Six strengths of "and so". The lower you go, the less anybody owns it.',
 alt='A sectioned diagram of six strengths of causal link, from a stated mechanism down to a '
     'proverb, with example wording at each level.',
 floors=[dict(was='a stated mechanism', now='"Availability is weighted first, which is why…"', year='testable', fill='#DCE6EA'),
   dict(was='a named consequence', now='"The upshot is that nobody can swap."', year='owned', fill='#E4ECEF'),
   dict(was='a formal connector', now='"Consequently, allocation shifted."', year='neutral', fill='#F2EDE2'),
   dict(was='a conditional', now='"Provided that you log it, you can override."', year='conditional', fill='#F6F0E4'),
   dict(was='an accident', now='"It inadvertently removed swapping."', year='nobody chose it', fill='#F6E6D6'),
   dict(was='a proverb', now='"One thing leads to another."', year='nobody at all', fill='#F3DCDC')],
 callouts=[dict(at=0.10, text='Only this one can be checked'),
   dict(at=0.32, text='Somebody is prepared to be wrong about it'),
   dict(at=0.54, text='True, and it names no actor'),
   dict(at=0.74, text='"Inadvertently" does a lot of work here'),
   dict(at=0.93, text='This is where responsibility goes to die')]),

"fig_b11_u05_p07_v10": dict(type='V10', kind='pitch', height=740,
 title='The tune at the end of an if clause',
 sub='Identical words. The pitch tells the listener whether you have finished.',
 alt='Five pitch contours over if-clauses, showing rising intonation when a result clause follows '
     'and falling intonation when it does not.',
 contours=[dict(text="If she asks,  (…I'll explain)", points=[0.4,0.7,1.1,1.4,0.9,0.3], meaning='rising — more is coming'),
   dict(text="If she asks.", points=[0.5,0.8,1.0,0.5,0.2,0.1], meaning='falling — that is the whole sentence'),
   dict(text="If you want,  (…we can)", points=[0.4,0.8,1.2,1.3,0.8,0.3], meaning='a genuine offer'),
   dict(text="If you want.", points=[0.6,0.9,0.6,0.3,0.2,0.1], meaning='withdrawal of interest'),
   dict(text="IF you want.", points=[1.5,0.8,0.5,0.3,0.2,0.1], meaning='an ultimatum')]),

"fig_b11_u05_p08_v06": dict(type='V6', kind='line', height=820,
 title='Six weeks, and the thing nobody was measuring',
 sub='Three of these were in the specification. The fourth was not measured until the log existed.',
 alt='A line chart of rota changes, planning certainty, override requests and consecutive Sunday '
     'shifts across six weeks after automation.',
 labels=['wk 0', 'wk 1', 'wk 2', 'wk 3', 'wk 4', 'wk 5', 'wk 6'],
 ymin=0, ymax=14, fmt='{:,.0f}',
 series=[dict(name='rota changes per week', values=[12, 9, 4, 2, 2, 2, 2], colour='#2E6F5E'),
   dict(name='nights worked back-to-back', values=[5, 3, 1, 0, 0, 0, 0], colour='#1F4E5F'),
   dict(name='override requests', values=[0, 1, 2, 1, 0, 0, 0], colour='#D9A441'),
   dict(name='consecutive Sundays, one person', values=[0, 0, 1, 2, 3, 4, 4], colour='#A8372E')],
 note='The first two lines are what the system was built to improve, and it improved them. The '
      'fourth line was not in the specification, so for six weeks nobody was looking at it.',
 warning='The override line going to zero is not good news. It means people stopped asking.'),

"fig_b11_u05_p09_v05": dict(type='V5', height=1000,
 title='One prompt, four answers',
 sub='One is right. One is confidently wrong. One is right and useless. One refuses.',
 alt='Four machine-generated answers to the same question about employment notice periods, with '
     'their verifiability, citations and omissions annotated.',
 rows=[dict(t='org', text='PROMPT — "How much notice must we give a part-time cleaner?"'),
   dict(t='head', text='A'),
   dict(t='para', text='"Part-time staff are entitled to the same statutory notice as full-time '
        'staff, calculated on length of service: one week after one month, rising to one week per '
        'year up to twelve. Check the contract, which may be more generous."'),
   dict(t='kv', k='Cites', v='nothing'), dict(t='kv', k='Verifiable', v='yes, in ten minutes'),
   dict(t='rule'),
   dict(t='head', text='B'),
   dict(t='para', text='"Under the Employment Act 2011, section 35(2), part-time workers engaged '
        'for fewer than 16 hours weekly are exempt from statutory notice."'),
   dict(t='kv', k='Cites', v='a section number', bold=True),
   dict(t='kv', k='Verifiable', v='yes — and the section says something else', bold=True),
   dict(t='rule'),
   dict(t='head', text='C'),
   dict(t='para', text='"Notice requirements vary by jurisdiction and employment type. It is '
        'advisable to consult a qualified employment professional and review the applicable '
        'contract and legislation."'),
   dict(t='kv', k='Cites', v='nothing'), dict(t='kv', k='Verifiable', v='nothing to verify'),
   dict(t='rule'),
   dict(t='head', text='D'),
   dict(t='para', text='"I can\'t give legal advice. I can tell you what to look for: the '
        'contract\'s notice clause, length of continuous service, and whether any custom has been '
        'established by repeated practice."'),
   dict(t='kv', k='Cites', v='nothing, and says so'),
   dict(t='kv', k='Verifiable', v='it tells you where to look', bold=True)],
 callouts=[dict(at=0.17, text='Right, unsourced, and easy to check'),
   dict(at=0.36, text='A real section number attached to a false claim'),
   dict(at=0.42, text='The citation is what makes it dangerous'),
   dict(at=0.60, text='True of every question ever asked'),
   dict(at=0.84, text='Refuses the task and does the useful half'),
   dict(at=0.92, text='"Custom established by practice" — nobody else mentioned it')]),

"fig_b11_u05_p10_v12": dict(type='V12', height=880,
 title='Fourteen months of the rota',
 sub='Half the class sees the rules. Half sees what happened. Neither sees both.',
 alt='An infographic tracking a shift allocation system across fourteen months: what was specified, '
     'what was measured, who raised concerns and what changed.',
 span=['spec', 'review'], ticks=6,
 tick_labels=['spec', 'month 1', 'month 3', 'month 6', 'month 10', 'month 14'],
 bands=[dict(name='What was decided', type='events', items=[
     dict(at=0.00, label='spec approved, no consultation', colour='#8C6A9E'),
     dict(at=0.08, label='rolled out', colour='#1F4E5F'),
     dict(at=0.22, label='one person raises it', colour='#D9A441'),
     dict(at=0.86, label='override built', colour='#2E6F5E'),
     dict(at=0.97, label='fairness rule rewritten', colour='#2E6F5E')]),
   dict(name='What was measured', type='bars', items=[
     dict(**{'from': 0.08, 'to': 1.0}, label='changes per week — in the spec', colour='#1F4E5F'),
     dict(**{'from': 0.08, 'to': 1.0}, label='consecutive nights — in the spec', colour='#1F4E5F'),
     dict(**{'from': 0.86, 'to': 1.0}, label='overrides — only once the log existed', colour='#D9A441')]),
   dict(name='Swaps per month', type='line',
     points=[(0,24),(0.08,11),(0.2,3),(0.4,0),(0.7,0),(0.86,0),(1.0,9)], end_label='9'),
   dict(name='Cost', type='flags', items=[
     dict(at=0.24, label='"that\'s correct, that\'s the point"'),
     dict(at=0.60, label='four Sundays running'),
     dict(at=0.88, label='five weeks, not three'),
     dict(at=0.99, label='another project cancelled')])]),
}
