"""B1.1 Unit 6 · The Rule Nobody Follows — the twelve figures, as data."""
FIGURES = {
"fig_b11_u06_p00_v01": dict(type='V1', height=900, storey_h=150,
 title='The notices in Jengo House',
 sub='Sixteen notices in this building. Three have been ignored for over a year.',
 alt='A building cut open across four floors showing fire doors, notices, a wedged-open door, a '
     'key box and people passing through.',
 sky='#E9EBE6', ground='#B4A994', ground_line=720,
 buildings=[dict(x=60, w=1480, storeys=4, colour='#F4EEE2', cutaway=True,
   floor_labels=['storage — one notice, 2014', 'studios — fire door propped',
                 'the workspace — kitchen rota', 'entrance — the rules notice'])],
 props=[dict(kind='sign', x=200, y=720, s=.8, text='RULES'),
        dict(kind='sign', x=1430, y=720, s=.7, text='KEYS'),
        dict(kind='box', x=420, y=720, s=1.0), dict(kind='box', x=490, y=720, s=1.0),
        dict(kind='table', x=900, y=720, s=1.4), dict(kind='crate', x=1240, y=720, s=1.0)],
 people=[dict(x=330, y=720, h=86, skin=4, cloth=0, hair='short', arm='point'),
         dict(x=640, y=720, h=84, skin=3, cloth=3, hair='long', arm='hold'),
         dict(x=1040, y=720, h=86, skin=1, cloth=2, hair='wrap', arm='down'),
         dict(x=1340, y=720, h=85, skin=0, cloth=5, hair='short', arm='hold')],
 names=[dict(x=200,t='the rules notice, 2019'), dict(x=455,t='stored against the door'),
        dict(x=640,t='Wanjiru'), dict(x=900,t='the desk'),
        dict(x=1240,t='extinguisher, used as a wedge'), dict(x=1430,t='key box, checked at nine')],
 markers=[dict(x=200,y=674),dict(x=455,y=692),dict(x=1240,y=694),dict(x=1430,y=672),
          dict(x=760,y=560),dict(x=320,y=420),dict(x=1090,y=300),dict(x=880,y=690)]),

"fig_b11_u06_p01_v08": dict(type='V8', height=820,
 title='Where a rule comes from, and where it goes',
 sub='Three of these arrows have never been used in this building.',
 alt='A network from statute through regulator, policy, procedure and notice to practice, with '
     'the enforcement and review arrows drawn dashed.',
 nodes={
  'stat': dict(x=200,  y=200, short='LAW', name='Statute', sub='parliament', colour='#1F4E5F'),
  'reg':  dict(x=560,  y=140, short='REG', name='Regulation', sub='in force 2021', colour='#1F4E5F'),
  'pol':  dict(x=560,  y=440, short='POL', name='Policy', sub='the landlord\'s agent, 2019', colour='#C86B2B'),
  'proc': dict(x=960,  y=300, short='PROC', name='Procedure', sub='what the notice says', colour='#8C6A9E'),
  'prac': dict(x=1340, y=440, short='DO', name='Practice', sub='what actually happens', r=58, colour='#A8372E'),
  'rev':  dict(x=960,  y=700, short='REV', name='Review', sub='scheduled 2020', colour='#9AA7AE')},
 edges=[dict(a='stat', b='reg', label='gives effect to', sw=4),
        dict(a='reg', b='pol', label='organisation must have one', sw=4),
        dict(a='pol', b='proc', label='written down', sw=4),
        dict(a='proc', b='prac', label='enforcement', sw=2, dash='7 5', colour='#9AA7AE'),
        dict(a='pol', b='prac', label='what people do instead', sw=5, colour='#A8372E'),
        dict(a='prac', b='rev', label='never fed back', sw=2, dash='4 6', colour='#9AA7AE'),
        dict(a='rev', b='pol', label='would amend it', sw=2, dash='4 6', colour='#9AA7AE')]),

"fig_b11_u06_p02_v07": dict(type='V7', height=840,
 title='Two people at a propped-open fire door',
 sub='Neither of them put the wedge there. Both of them have walked past it this week.',
 alt='Two people standing by a fire door held open with a fire extinguisher, with speech and '
     'thought bubbles.',
 bg='#ECEDE8',
 set=[dict(kind='sign', x=1380, y=690, s=.9, text='FIRE DOOR'), dict(kind='box', x=1180, y=690, s=1.1)],
 people=[dict(x=480, h=250, skin=3, cloth=3, hair='long', arm='point', facing='right',
              label='Wanjiru', role='runs the space',
              says=['It was brought in after something.'],
              thinks=['I have never been told what.']),
         dict(x=960, h=252, skin=4, cloth=0, hair='short', arm='folded', facing='left',
              label='Obi', role='second floor',
              says=["I didn't know it was a rule.", 'I knew it was a sign.'])]),

"fig_b11_u06_p03_v09": dict(type='V9', kind='mirror', height=640,
 title='The same event, two first words',
 sub='The passive is not politer. It is a decision about what the sentence is about.',
 alt='A mirrored diagram showing an active and a passive version of the same sentence, with the '
     'agent visible in one and absent in the other.',
 active=dict(parts=[dict(text='A tenant', w=1.2, role='agent'),
                    dict(text='wedged open', w=1.4, role='action'),
                    dict(text='the fire door', w=1.6, role='affected')]),
 passive=dict(parts=[dict(text='The fire door', w=1.6, role='affected'),
                     dict(text='was wedged open', w=1.8, role='action'),
                     dict(text='(by a tenant)', w=1.2, role='hidden')]),
 rule='by names the doer. with names the instrument. "Wedged open by a tenant with an '
      'extinguisher" — the extinguisher did not decide anything.'),

"fig_b11_u06_p03_v11": dict(type='V11', height=640,
 title='Why this sentence blames the extinguisher',
 alt='Two panels contrasting "by" used for an instrument against the correct "with".',
 wrong=dict(sentence='The door was wedged open by a fire extinguisher.',
            boundary=0.50, boundary_label='agent / instrument', event=0.24,
            event_label='extinguisher placed as the doer',
            why='by introduces the agent — the thing that decided. An extinguisher decides '
                'nothing. The sentence reads as though the object acted on its own, which is '
                'exactly what the person who propped it would prefer.'),
 right=dict(sentence='The door was wedged open with a fire extinguisher.',
            boundary=0.50, boundary_label='agent / instrument', event=0.76,
            event_label='extinguisher placed as the tool',
            why='with introduces the instrument. The agent is now absent rather than '
                'misassigned — and the reader notices the absence, which is the point.'),
 misconception='The writer thought by and with were interchangeable in the passive. They mark '
               'two different roles, and getting them round the wrong way can move the blame.'),

"fig_b11_u06_p04_v04": dict(type='V4', height=720,
 title='The procedure, and what people do',
 sub='Learner A has the written steps. Learner B has the observed steps. Find the three gaps.',
 alt='Two step sequences side by side, one from a written procedure and one observed in practice, '
     'differing in three places.',
 differences=8, prompt='Describe only. Do not show the page.',
 left=dict(label='what is written', art=[
   dict(kind='doc', x=120, y=30), dict(kind='arrow', x=230, y=80),
   dict(kind='doc', x=330, y=30), dict(kind='arrow', x=440, y=80),
   dict(kind='doc', x=540, y=30),
   dict(kind='label', x=330, y=230, text='check · lock · sign the book', colour='#1F4E5F')]),
 right=dict(label='what happens', art=[
   dict(kind='doc', x=120, y=30), dict(kind='arrow', x=230, y=80),
   dict(kind='gap', x=330, y=30, w=68, bh=88), dict(kind='arrow', x=440, y=80),
   dict(kind='doc', x=540, y=30), dict(kind='cross', x=330, y=150),
   dict(kind='label', x=330, y=250, text='check · (nobody locks) · sign the book', colour='#A8372E')])),

"fig_b11_u06_p05_v05": dict(type='V5', height=1020,
 title='The building rules notice',
 sub='Nine rules. One has teeth. One sentence at the bottom removes them.',
 alt='A building rules notice listing nine rules with their dates, only one of which names an '
     'enforcement mechanism, and a final sentence reserving the right not to enforce.',
 rows=[dict(t='org', text='JENGO HOUSE · CONDITIONS OF OCCUPATION'),
   dict(t='kv', k='Issued', v='March 2019', mono=True),
   dict(t='kv', k='Authority', v='The Management', bold=True),
   dict(t='rule'),
   dict(t='grid', cols=['#', 'RULE', 'SINCE', 'IF BREACHED'],
     data=[['1', 'Fire doors must not be propped open', '2019', '—'],
           ['2', 'Keys to be returned to the box by 18:00', '2019', 'replacement charged'],
           ['3', 'No cooking on the premises', '2014', '—'],
           ['4', 'Visitors to be signed in', '2019', '—'],
           ['5', 'No storage in common parts', '2014', '—'],
           ['6', 'Music audible outside a unit after 19:00', '2021', '—'],
           ['7', 'Bicycles not to be brought above ground floor', '2016', '—'],
           ['8', 'Waste separated into the three bins', '2022', '—'],
           ['9', 'The lift is not to be used during an alarm', '2019', '—']]),
   dict(t='rule'),
   dict(t='head', text='General'),
   dict(t='para', text='These conditions form part of the occupation agreement. Occupiers are '
        'reminded that the common parts are maintained for the benefit of all.'),
   dict(t='rule'),
   dict(t='small', text='The Management reserves the right to vary, waive or not enforce any of '
        'these conditions at its discretion, and no failure to enforce shall constitute a waiver '
        'of the right to enforce subsequently. Queries to the managing agent.')],
 callouts=[dict(at=0.22, text='Rule 1. No consequence of any kind'),
   dict(at=0.27, text='The only rule with teeth — and it is about money'),
   dict(at=0.32, text='2014. Nobody now in the building was here'),
   dict(at=0.46, text='2022, and already ignored'),
   dict(at=0.72, text='"Reminded" — the softest verb available'),
   dict(at=0.90, text='Here is the sentence that unmakes the notice'),
   dict(at=0.95, text='…and here is the one that keeps it alive anyway')]),

"fig_b11_u06_p06_v02": dict(type='V2', height=820,
 title='Six ways to not say who',
 sub='The same event, worded six ways. The doer gets further away each time.',
 alt='A sectioned diagram of six levels of agent-hiding, from a named actor down to a proverb.',
 floors=[dict(was='the agent named', now='"The agent brought the rule in."', year='answerable', fill='#DCE6EA'),
   dict(was='passive with by', now='"The rule was brought in by the agent."', year='still named', fill='#E4ECEF'),
   dict(was='passive, no agent', now='"The rule was brought in."', year='no name', fill='#F2EDE2'),
   dict(was='impersonal it', now='"It was decided that the rule would apply."', year='no name, no doer', fill='#F6F0E4'),
   dict(was='nominalised', now='"Steps have been taken."', year='no action either', fill='#F6E6D6'),
   dict(was='hedged report', now='"It is understood that steps were taken."', year='nobody is even claiming it', fill='#F3DCDC')],
 callouts=[dict(at=0.10, text='Somebody can be asked about this'),
   dict(at=0.30, text='Still answerable — the by phrase is the hook'),
   dict(at=0.52, text='A notice lives here'),
   dict(at=0.72, text='"Mistakes were made" is this layer'),
   dict(at=0.93, text='And this is a newspaper protecting a source')]),

"fig_b11_u06_p07_v10": dict(type='V10', kind='stress', height=720,
 title='Three endings, one spelling',
 sub='The sound before the -ed decides. Not the letter.',
 alt='Twelve past participles sorted into three groups by the sound of their -ed ending, with the '
     'stressed syllables marked.',
 items=[dict(syllables=['propped','/t/'], strong=[0], note='after an unvoiced sound: /t/'),
   dict(syllables=['en','FORCED','/t/'], strong=[1], note='after /s/: /t/'),
   dict(syllables=['re','VIEWED','/d/'], strong=[1], note='after a vowel: /d/'),
   dict(syllables=['SIGNED','/d/'], strong=[0], note='after /n/: /d/'),
   dict(syllables=['a','MEND','ed','/ɪd/'], strong=[1], note='after /d/: an extra syllable'),
   dict(syllables=['in','SPECT','ed','/ɪd/'], strong=[1], note='after /t/: an extra syllable')]),

"fig_b11_u06_p08_v06": dict(type='V6', kind='bar', height=820,
 title='What happens when a stranger follows your procedure',
 sub='Sixty procedures, each handed to one person who had never done the task.',
 alt='A bar chart comparing completion rates for procedures that name the reader, give reasons, '
     'and flag the common error, against those that do not.',
 labels=['names the reader', 'gives the reason', 'flags the common error',
         'admits what is broken', 'none of these'],
 ymin=0, ymax=100, fmt='{:,.0f}%',
 series=[dict(name='completed without asking', values=[71, 78, 84, 66, 23], colour='#2E6F5E')],
 note='Flagging the step people usually get wrong is worth more than any other single feature, '
      'and it is the one almost no written procedure contains — because the person writing it is '
      'the person who stopped getting it wrong years ago.',
 warning='Self-reported completion. Four people said they had finished and had not.'),

"fig_b11_u06_p10_v12": dict(type='V12', height=880,
 title='Nine rules, twelve years',
 sub='Half the class sees what is written. Half sees what happens. Neither sees both.',
 alt='An infographic tracking nine building rules from the year each was introduced to whether it '
     'is currently followed, with enforcement events and the incidents that created them.',
 span=['2014', '2026'], ticks=6,
 tick_labels=['2014', '2016', '2019', '2021', '2024', '2026'],
 bands=[dict(name='Rules brought in', type='events', items=[
     dict(at=0.00, label='no cooking · no storage', colour='#1F4E5F'),
     dict(at=0.18, label='no bicycles above ground', colour='#1F4E5F'),
     dict(at=0.42, label='fire doors · keys · visitors · lift', colour='#C86B2B'),
     dict(at=0.60, label='noise curfew', colour='#1F4E5F'),
     dict(at=0.84, label='waste separation', colour='#1F4E5F')]),
   dict(name='Still followed', type='bars', items=[
     dict(**{'from': 0.42, 'to': 1.0}, label='keys — the only one with a charge', colour='#2E6F5E'),
     dict(**{'from': 0.42, 'to': 0.70}, label='fire doors — until the corridor light failed', colour='#D9A441'),
     dict(**{'from': 0.84, 'to': 0.90}, label='waste — six weeks', colour='#A8372E')]),
   dict(name='Rules nobody follows', type='line',
     points=[(0,0),(0.18,1),(0.42,1),(0.6,3),(0.84,5),(1.0,6)], end_label='6 of 9'),
   dict(name='Why', type='flags', items=[
     dict(at=0.40, label='a fire somewhere else'),
     dict(at=0.70, label='corridor light fails, never fixed'),
     dict(at=0.88, label='third bin removed by the council'),
     dict(at=0.99, label='insurance renewal asks the question')])]),

"fig_b11_u06_p09_v05": dict(type='V5', height=960,
 title='The welcome email, and what it leaves out',
 sub='Everything written down is on the left. Everything that matters is on the right.',
 alt='A welcome email sent to new tenants alongside a handwritten list of the unwritten rules a '
     'colleague told them in the first week.',
 rows=[dict(t='org', text='WELCOME TO JENGO HOUSE — sent to every new tenant'),
   dict(t='para', text='Welcome! Here is everything you need. Your key opens the street door and '
        'your own unit. Keys go back in the box by six. Wifi password is on the board. Bins are '
        'in the yard, separated into three. Any problems, message the group.'),
   dict(t='sign', text='— The Management'),
   dict(t='rule'),
   dict(t='head', text='What Grace told me in week one'),
   dict(t='grid', cols=['#', 'THE UNWRITTEN RULE', 'WHO TELLS YOU', 'HOW YOU FIND OUT'],
     data=[['1', 'Never take the last desk by the window', 'a neighbour', 'a look'],
           ['2', 'The third bin went two years ago; use the second', 'the cleaner', 'after you use it'],
           ['3', 'The group chat is for problems, not chat', 'nobody', 'silence'],
           ['4', 'If you book the room you clear the room', 'the next person', 'passive aggression'],
           ['5', 'Mr Kamau is addressed as Mr Kamau', 'everybody, instantly', 'immediately'],
           ['6', 'Don\'t message the group after seven', 'nobody', 'nobody replies']]),
   dict(t='rule'),
   dict(t='small', text='None of the six is written anywhere. Five of the six are enforced by '
        'somebody with no authority at all. The one rule in the welcome email that is actually '
        'followed — keys by six — is the one with a charge attached to it.')],
 callouts=[dict(at=0.12, text='Six lines. Four of them are about objects'),
   dict(at=0.20, text='Signed by nobody in particular'),
   dict(at=0.40, text='The welcome email is wrong about the bins'),
   dict(at=0.50, text='"Nobody tells you" appears twice'),
   dict(at=0.62, text='This one is learned in a single afternoon'),
   dict(at=0.88, text='Authority and enforcement are in different hands')]),
}
