"""B1.1 Unit 8 - Four Hundred Kilometres - the twelve figures, as data."""
FIGURES = {
"fig_b11_u08_p00_v01": dict(type='V1', height=900, storey_h=130,
 title="Esther's eleven acres at Limuru, 06.40",
 sub='Two fields are in rotation. One is lying fallow. Twelve things here have names.',
 alt='A smallholding at dawn with terraced fields, drip irrigation, a water tank, shade netting, '
     'a drying rack, crate stacks and four people working.',
 sky='#E2EBE5', ground='#B09A74', ground_line=690,
 buildings=[dict(x=90, w=230, storeys=1, colour='#D8CDB6', label='the store'),
   dict(x=1240, w=200, storeys=2, colour='#CFC6B0', label='the cooperative shed')],
 props=[dict(kind='tree', x=420, y=690, s=1.1), dict(kind='tree', x=560, y=690, s=.9),
   dict(kind='tree', x=1120, y=690, s=1.0),
   dict(kind='crate', x=260, y=690, s=1.2), dict(kind='crate', x=350, y=690, s=1.2),
   dict(kind='bowser', x=760, y=690, s=.8), dict(kind='table', x=940, y=690, s=1.3),
   dict(kind='sign', x=640, y=690, s=.8, text='FALLOW'),
   dict(kind='van', x=1420, y=690, s=.7, colour='#2E6F5E')],
 people=[dict(x=330, y=690, h=72, skin=3, cloth=2, hair='wrap', arm='hold'),
   dict(x=700, y=690, h=70, skin=4, cloth=0, hair='short', arm='point'),
   dict(x=980, y=690, h=72, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=1340, y=690, h=71, skin=1, cloth=1, hair='short', arm='down')],
 names=[dict(x=330, t='Esther, picking'), dict(x=640, t='the fallow field'),
   dict(x=760, t='water tank'), dict(x=980, t='weighing and packing'),
   dict(x=1240, t='the cooperative shed'), dict(x=1420, t='the crate goes at seven')],
 markers=[dict(x=260, y=656), dict(x=640, y=612), dict(x=760, y=640), dict(x=980, y=652),
   dict(x=1420, y=650), dict(x=200, y=600), dict(x=1120, y=600), dict(x=460, y=640)]),

"fig_b11_u08_p01_v08": dict(type='V8', height=820,
 title='From the soil to the shelf',
 sub='Six stages. The dashed arrow is the one nobody can trace after it happens.',
 alt='A network from soil through grower, cooperative, transport, market and shelf, with an '
     'aggregation step where traceability is lost.',
 nodes={
  'soil': dict(x=180, y=420, short='SOIL', name='Eleven acres', sub='Limuru, 40 km', colour='#2E6F5E'),
  'grow': dict(x=520, y=240, short='EW', name='Esther', sub='Nov to June', r=56, colour='#1F4E5F'),
  'coop': dict(x=520, y=640, short='406', name='The cooperative', sub='406 members, one crate', colour='#C86B2B'),
  'meru': dict(x=900, y=700, short='MER', name='Meru', sub='400 km, all year', colour='#A8372E'),
  'mkt':  dict(x=980, y=340, short='MKT', name='The market', sub='crates mixed on the floor', colour='#8C6A9E'),
  'shelf':dict(x=1350, y=460, short='LBL', name='The label', sub='says LOCAL', r=56, colour='#D9A441')},
 edges=[dict(a='soil', b='grow', label='what she plants', sw=5),
  dict(a='grow', b='coop', label='her crates, marked', sw=4),
  dict(a='coop', b='mkt', label='406 members, one price', sw=5),
  dict(a='meru', b='mkt', label='July to October', sw=5, colour='#A8372E'),
  dict(a='mkt', b='shelf', label='traceability lost here', sw=3, dash='7 5', colour='#9AA7AE'),
  dict(a='grow', b='shelf', label='40 km, in season', sw=3, dash='6 5')]),

"fig_b11_u08_p02_v07": dict(type='V7', height=840,
 title='A grower and a buyer, with a crate between them',
 sub='One of them is looking at the crate. One of them is looking at the other.',
 alt='A grower and a market buyer standing either side of a crate of tomatoes, with speech and '
     'thought bubbles.',
 bg='#ECEFE8',
 set=[dict(kind='crate', x=760, y=690, s=1.6), dict(kind='table', x=1240, y=690, s=1.4)],
 people=[dict(x=520, h=250, skin=3, cloth=2, hair='wrap', arm='point', facing='right',
   label='Esther', role='forty kilometres',
   says=['The ones I sold you in March', 'were mine.'],
   thinks=['He knows about July.']),
  dict(x=1060, h=252, skin=1, cloth=0, hair='short', arm='folded', facing='left',
   label='the buyer', role='the stall',
   says=["I didn't know that."])]),

"fig_b11_u08_p03_v09": dict(type='V9', kind='scope', height=700,
 title='What you can leave out, and what you cannot',
 sub='You may drop the relative pronoun only when it is the object. Drop the subject and the '
     'sentence loses its spine.',
 alt='A sentence with brackets showing which relative pronoun can be removed and which cannot.',
 words=['the', 'grower', 'who', 'I', 'buy', 'from'],
 focus=[2],
 brackets=[dict(**{'from': 2, 'to': 5}, lane=0, label='who is the OBJECT of buy from - you may drop it', colour='#2E6F5E'),
  dict(**{'from': 1, 'to': 5}, lane=1, label='the grower I buy from - still complete', colour='#2E6F5E'),
  dict(**{'from': 0, 'to': 5}, lane=2, label='but: the grower WHO SUPPLIES me - subject, never droppable', colour='#A8372E')],
 rule='If dropping the pronoun leaves two verbs with nothing between them, you dropped the wrong '
      'one. And that never follows a preposition: of which, not of that.'),

"fig_b11_u08_p03_v11": dict(type='V11', height=640,
 title='Why this sentence has lost its subject',
 alt='Two panels contrasting a wrongly reduced relative clause with a correctly reduced one.',
 wrong=dict(sentence='The grower supplies us has eleven acres.',
   boundary=0.50, boundary_label='the clause boundary', event=0.24,
   event_label='subject pronoun dropped',
   why='who was the subject of supplies. Dropping it leaves supplies and has side by side with '
       'nothing to join them, so the reader has to reread to find out which verb belongs to the '
       'grower.'),
 right=dict(sentence='The grower supplying us has eleven acres.',
   boundary=0.50, boundary_label='the clause boundary', event=0.76,
   event_label='reduced to -ing instead',
   why='If you want the shorter version of a subject clause, you do not delete the pronoun - you '
       'turn the verb into -ing. Now the reader can see at a glance which verb is the main one.'),
 misconception='The writer thought the rule was that you can always drop who and which. You can '
               'drop them only when they are the object of their own clause.'),

"fig_b11_u08_p04_v04": dict(type='V4', height=720,
 title='The same tomato, two months apart',
 sub='Learner A has the farm record. Learner B has the shelf label. Find out whether it is true.',
 alt='Two crates of the same produce side by side, one in season from forty kilometres and one out '
     'of season from four hundred, with the same label on both.',
 differences=9, prompt='Describe only. The labels are identical.',
 left=dict(label='March', art=[
   dict(kind='block', x=140, y=0, w=120, bh=90, colour='#2E6F5E'),
   dict(kind='doc', x=360, y=20),
   dict(kind='label', x=300, y=200, text='Limuru - 40 km - Esther Wanjiku', colour='#2E6F5E'),
   dict(kind='tick', x=520, y=70)]),
 right=dict(label='July', art=[
   dict(kind='block', x=140, y=0, w=120, bh=90, colour='#A8372E'),
   dict(kind='doc', x=360, y=20),
   dict(kind='label', x=300, y=200, text='Meru - 400 km - 406 members', colour='#A8372E'),
   dict(kind='cross', x=520, y=70)])),

"fig_b11_u08_p05_v05": dict(type='V5', height=1020,
 title='Two labels on the same market floor',
 sub='Both are true. Only one of them tells you anything.',
 alt='Two produce labels reproduced at full size, one with four marketing phrases and one giving '
     'the grower, the distance, the picking date and the price split.',
 rows=[dict(t='org', text='LABEL A - THE STALL NEXT DOOR'),
   dict(t='head', text='PROUDLY LOCAL'),
   dict(t='para', text='Locally sourced produce. Supporting local farmers. Fresh from the farm to '
     'your table. Proudly local, every day.'),
   dict(t='kv', k='Grower', v='not stated'),
   dict(t='kv', k='Distance', v='not stated', bold=True),
   dict(t='kv', k='Picked', v='not stated'),
   dict(t='kv', k='Packed at', v='Ruiru - 10 km', mono=True),
   dict(t='rule'),
   dict(t='org', text='LABEL B - THIS STALL'),
   dict(t='kv', k='Grown by', v='Esther Wanjiku, Limuru', bold=True),
   dict(t='kv', k='Distance from this stall', v='40 km', mono=True, bold=True),
   dict(t='kv', k='Picked', v='Tuesday', mono=True),
   dict(t='kv', k='Packed', v='Tuesday, same day', mono=True),
   dict(t='kv', k='Available', v='November to June', bold=True),
   dict(t='kv', k='July to October', v='Meru, 400 km - we will say so'),
   dict(t='kv', k='Price difference', v='+11/kg, of which ~7 reaches the grower', mono=True),
   dict(t='rule'),
   dict(t='small', text='Label A is accurate. The produce is packed ten kilometres away, which '
     'several voluntary schemes permit to be described as locally packed, and the phrase on the '
     'label is locally sourced, which is not a defined term. Nothing on Label A is false.')],
 callouts=[dict(at=0.14, text='Four phrases, none of them measurable'),
   dict(at=0.26, text='The only number on the label is the packing distance'),
   dict(at=0.30, text='Ten kilometres - from wherever it was grown'),
   dict(at=0.48, text='A person, who could be visited'),
   dict(at=0.54, text='A number you can disagree with'),
   dict(at=0.70, text='The four months it is not available, volunteered'),
   dict(at=0.78, text='How much of the premium arrives'),
   dict(at=0.92, text='And none of Label A is a lie')]),

"fig_b11_u08_p06_v02": dict(type='V2', height=820,
 title='Six ways to attach the same clause',
 sub='The same information, six registers. Each layer is further from speech.',
 alt='A sectioned diagram of six relative structures from spoken English to formal written '
     'English, with the same content at each level.',
 floors=[dict(was='spoken', now='the co-op she is a member of', year='everyday', fill='#DCE6EA'),
   dict(was='neutral written', now='the co-op that she is a member of', year='most writing', fill='#E4ECEF'),
   dict(was='formal written', now='the co-op of which she is a member', year='reports', fill='#F2EDE2'),
   dict(was='reduced', now='the co-op, one of 406 members', year='labels, captions', fill='#F6F0E4'),
   dict(was='quantified', now='the co-op, most of whose members have under five acres', year='dense', fill='#F6E6D6'),
   dict(was='nominalised', now='co-operative membership', year='nobody and nothing', fill='#F3DCDC')],
 callouts=[dict(at=0.10, text='Say this. Do not write it in a report'),
   dict(at=0.30, text='The safe default for almost everything'),
   dict(at=0.52, text='of which - never of that'),
   dict(at=0.72, text='Shortest, and loses the relationship'),
   dict(at=0.93, text='No people left in the sentence at all')]),

"fig_b11_u08_p07_v10": dict(type='V10', kind='pitch', height=740,
 title='Where to breathe in a long noun phrase',
 sub='The same sentence twice. One of them a listener can follow.',
 alt='Pitch contours over a long noun phrase, showing chunk boundaries with short pauses against '
     'an unbroken reading.',
 contours=[dict(text='the cooperative of which the grower we buy from is a member',
     points=[0.6, 0.6, 0.6, 0.6, 0.6, 0.5], meaning='no chunking - unfollowable'),
   dict(text='the cooperative || of which || the grower we buy from || is a member',
     points=[0.9, 0.3, 1.0, 0.3, 1.1, 0.4], meaning='four chunks - followable'),
   dict(text='the field lying fallow this year || which was planted in 2023',
     points=[1.0, 0.4, 0.3, 1.1, 0.5, 0.2], meaning='the reduced clause is one chunk'),
   dict(text='belongs to a cooperative || most of whose members || have under five acres',
     points=[0.8, 0.3, 1.0, 0.3, 0.9, 0.2], meaning='three chunks, falling at the end')]),

"fig_b11_u08_p08_v06": dict(type='V6', kind='waterfall', height=820,
 title='Eleven shillings, and where they go',
 sub='The premium on a kilo of in-season tomatoes, traced to the end.',
 alt='A waterfall chart breaking an eleven-shilling price premium into transport, cooperative fee, '
     'market levy, stall margin and the amount reaching the grower.',
 labels=['the premium', 'transport', 'co-op fee', 'market levy', 'stall margin', 'reaches Esther'],
 ymin=0, ymax=13, fmt='{:,.0f}',
 totals=[0, 5],
 series=[dict(name='flow', values=[11, -1.4, -0.9, -0.8, -0.9, 7.0])],
 note='Seven of the eleven arrives. That is unusually high, and it is high because the crate goes '
      'forty kilometres on one vehicle and is handled twice. At four hundred kilometres the same '
      'premium would deliver about three.',
 warning='This is one stall, one crop, one season. It is not a benchmark.'),

"fig_b11_u08_p09_v05": dict(type='V5', height=960,
 title='Four note systems, one page each',
 sub='Match each to the kind of text it was designed for before you read the annotations.',
 alt='Four note-taking layouts reproduced side by side: linear, Cornell, mind map and matrix.',
 rows=[dict(t='org', text='FOUR WAYS OF TAKING THE SAME NOTES'),
   dict(t='head', text='1 - LINEAR'),
   dict(t='para', text='Heading. Point. Sub-point. Sub-point. Heading. Point. Follows the speaker '
     'exactly and records almost everything. Impossible to compare two sources in.'),
   dict(t='kv', k='Designed for', v='a lecture that is already well organised'),
   dict(t='rule'),
   dict(t='head', text='2 - CORNELL'),
   dict(t='para', text='Narrow left column for cues, wide right column for notes, strip at the '
     'foot for a summary written afterwards. The summary is the whole method and is the part '
     'people skip.'),
   dict(t='kv', k='Designed for', v='material you will be tested on'),
   dict(t='rule'),
   dict(t='head', text='3 - MIND MAP'),
   dict(t='para', text='One idea in the centre, branches outward. Excellent for a subject you '
     'already half know. Useless at speed, because you must decide where a thing goes before you '
     'can write it.'),
   dict(t='kv', k='Designed for', v='planning, not capturing'),
   dict(t='rule'),
   dict(t='head', text='4 - MATRIX'),
   dict(t='grid', cols=['', 'distance', 'grower', 'season', 'price'],
     data=[['Label A', 'no', 'no', 'no', 'no'], ['Label B', '40 km', 'named', 'Nov-Jun', '+11'],
           ['explainer', 'argues no', 'proposes', 'proposes', '-']]),
   dict(t='small', text='Claims across the top, sources down the side. The only one of the four '
     'built for comparing, and the only one that makes a gap visible as a blank cell.')],
 callouts=[dict(at=0.16, text='Records most - organises nothing'),
   dict(at=0.34, text='The summary strip is the method'),
   dict(at=0.40, text='…and it is written after, which is why it is skipped'),
   dict(at=0.58, text='You must know the shape before you start'),
   dict(at=0.80, text='A blank cell is a finding'),
   dict(at=0.92, text='Four sources, one question, one page')]),

"fig_b11_u08_p10_v12": dict(type='V12', height=880,
 title='One crate, one year',
 sub='Half the class sees the growing band. Half sees the price band. Neither sees both.',
 alt='An infographic tracking a crop across one year, showing the growing season, the source, the '
     'distance travelled, the shelf price and what the label said each month.',
 span=['Nov', 'Oct'], ticks=6,
 tick_labels=['Nov', 'Jan', 'Mar', 'Jun', 'Aug', 'Oct'],
 bands=[dict(name='Where it came from', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.62}, label='Esther, Limuru - 40 km', colour='#2E6F5E'),
   dict(**{'from': 0.62, 'to': 1.0}, label='Meru - 400 km', colour='#A8372E')]),
  dict(name='What the label said', type='flags', items=[
   dict(at=0.04, label='LOCAL'), dict(at=0.34, label='LOCAL'),
   dict(at=0.66, label='LOCAL - unchanged'), dict(at=0.90, label='LOCAL - still')]),
  dict(name='Price per kilo', type='line',
   points=[(0, 52), (0.2, 50), (0.4, 49), (0.62, 55), (0.8, 41), (1.0, 43)], end_label='43'),
  dict(name='What changed', type='events', items=[
   dict(at=0.62, label='season ends', colour='#D9A441'),
   dict(at=0.70, label='customers notice the price', colour='#C86B2B'),
   dict(at=0.84, label='the board goes up', colour='#2E6F5E'),
   dict(at=0.97, label='the next stall copies it', colour='#8C6A9E')])]),
}
