"""B1.2 Unit 1 - What the Canteen Buys - twelve figures, as data."""
FIGURES = {
"fig_b12_u01_p00_v01": dict(type='V1', height=840, storey_h=155,
 title='The canteen and the service yard, 13.40',
 sub='Twelve things to find. Four of them were not in a hospital canteen in 1994.',
 alt='A hospital canteen seen from the service yard with a steam counter, a tray rail, a salad '
     'bar, vending machines, a cold cabinet and a delivery van at the back.',
 sky='#DCE2E4', ground='#9CA3A4', ground_line=680,
 buildings=[dict(x=20, w=640, storeys=3, colour='#D2CEC4', label='the canteen'),
   dict(x=720, w=380, storeys=2, colour='#C9C5BA', label='the kitchen and stores'),
   dict(x=1160, w=420, storeys=4, colour='#C0BCB2', label='the main block')],
 props=[dict(kind='table', x=180, y=680, s=1.5), dict(kind='table', x=420, y=680, s=1.5),
   dict(kind='box', x=760, y=680, s=1.3), dict(kind='box', x=850, y=680, s=1.2),
   dict(kind='crate', x=960, y=680, s=1.1),
   dict(kind='van', x=1320, y=680, s=1.05, colour='#2E6F5E'),
   dict(kind='sign', x=120, y=680, s=.75, text='MENU'),
   dict(kind='sign', x=620, y=680, s=.7, text='1,850'),
   dict(kind='sign', x=1500, y=680, s=.7, text='13:40')],
 people=[dict(x=250, y=680, h=88, skin=2, cloth=1, hair='bun', arm='hold'),
   dict(x=340, y=680, h=87, skin=3, cloth=0, hair='short', arm='down'),
   dict(x=500, y=680, h=88, skin=1, cloth=2, hair='long', arm='hold'),
   dict(x=700, y=680, h=87, skin=4, cloth=3, hair='cap', arm='point'),
   dict(x=1020, y=680, h=88, skin=0, cloth=4, hair='grey', arm='folded'),
   dict(x=1230, y=680, h=87, skin=2, cloth=0, hair='short', arm='hold')],
 names=[dict(x=250, t='Rosa, reception, fourteen years'), dict(x=340, t='Matias, fifth year'),
   dict(x=500, t='Carla, eleven nights straight'), dict(x=700, t='Ignacio, twenty-two years'),
   dict(x=1020, t='Dr Herrera, emergency'), dict(x=1230, t='Dr Benitez, locum, week three'),
   dict(x=620, t='meals a day'), dict(x=120, t='four menus, two of them fresh')],
 markers=[dict(x=250, y=560), dict(x=340, y=560), dict(x=500, y=560), dict(x=700, y=560),
   dict(x=1020, y=560), dict(x=1230, y=560), dict(x=120, y=610), dict(x=620, y=612),
   dict(x=1500, y=612), dict(x=180, y=630), dict(x=760, y=624), dict(x=1320, y=620)]),

"fig_b12_u01_p01_v08": dict(type='V8', height=800,
 title='Why eleven became three',
 sub='Six nodes. The one everybody names is not the one that moved most.',
 alt='A network connecting price, working hours, who is at home in the afternoon, cooking time '
     'and fresh purchases, with the strength of each link shown.',
 nodes={
  'pri': dict(x=170, y=240, short='1', name='Price', sub='+40 % in real terms', colour='#C86B2B'),
  'shi': dict(x=170, y=560, short='2', name='Shift patterns', sub='the thing nobody names', colour='#1F4E5F'),
  'hom': dict(x=540, y=400, short='3', name='Who is at home at 3pm', sub='41 % down to 11 %', colour='#A8372E'),
  'tim': dict(x=900, y=230, short='4', name='Cooking time', sub='buy, cook and eat same day', colour='#8C6A9E'),
  'tin': dict(x=900, y=570, short='5', name='Tinned', sub='18 % up to 61 %', colour='#D9A441'),
  'fre': dict(x=1290, y=400, short='6', name='Fresh fish', sub='11 a month down to 3', r=54,
    colour='#2E6F5E')},
 edges=[dict(a='pri', b='fre', label='the explanation everybody gives', sw=3, dash='5 5'),
   dict(a='shi', b='hom', label='and this is the one that moved', sw=6),
   dict(a='hom', b='tim', label='nobody is in to cook it', sw=6),
   dict(a='hom', b='tin', label='so what keeps, wins', sw=6),
   dict(a='tim', b='fre', label='fresh is early, not expensive', sw=6),
   dict(a='tin', b='fre', label='and it took eight purchases a month', sw=5),
   dict(a='pri', b='tin', label='+34 %, barely different', sw=2, dash='6 6', colour='#9AA7AE')]),

"fig_b12_u01_p02_v07": dict(type='V7', height=820,
 title='The canteen budget',
 sub='One of them has eaten there every night for twenty-two years. One of them signs it off.',
 alt='A porter and a doctor talking across a canteen table with a menu board behind them, '
     'speech bubbles contrasting used to, would and be used to.',
 bg='#E9ECEC',
 set=[dict(kind='table', x=700, y=700, s=1.6), dict(kind='doc', x=700, y=630)],
 people=[dict(x=460, h=250, skin=4, cloth=3, hair='cap', arm='hold', facing='right',
   label='Ignacio', role='porter, 22 years', says=['We used to cook everything here.',
     'He would always come down at three in the morning.']),
  dict(x=980, h=248, skin=0, cloth=4, hair='grey', arm='folded', facing='left',
   label='Dr Herrera', role='emergency', says=["I'm used to the new menu now.",
     'You get used to it faster than you think.'])]),

"fig_b12_u01_p03_v09": dict(type='V9', kind='ladder', height=740,
 title='Four ways of saying what is normal',
 sub='Two of these are about a past that stopped. Two are about a present you have accepted.',
 alt='A ladder of habit forms from used to and would at the bottom through be used to and get '
     'used to at the top, with what each one can and cannot carry.',
 top_label='a present you have accepted', bottom_label='a past that stopped',
 steps=[dict(form="You'll GET USED TO it", meaning='the process. Not there yet, and on the way'),
   dict(form="I'm USED TO the night shift", meaning='a present familiarity. + noun or -ing'),
   dict(form='He WOULD come down at three', meaning='a repeated past action. Never a state'),
   dict(form='We USED TO have a bakery', meaning='a past state, and it has stopped'),
   dict(form="DIDN'T USE TO / DID YOU USE TO", meaning='no d in the negative or the question')],
 rule='In used to cook, to belongs to the infinitive. In used to the menu, to is a preposition, '
      'so what follows is a noun or an -ing form: I am used to cooking, never I am used to cook.'),

"fig_b12_u01_p03_v11": dict(type='V11', height=660,
 title='Why this sentence says the opposite of what the writer meant',
 alt='Two panels comparing a wrong and a right sentence about habit, with the state marker on '
     'the wrong form in the first.',
 wrong=dict(sentence='We would have a bakery in the basement.',
            boundary=0.50, boundary_label='would = a repeated action',
            event=0.78, event_label='have a bakery = a state',
            why='Would can only carry something that happened again and again. A bakery is not '
                'an event that repeats; it is a situation that lasted. The sentence asks the '
                'reader to imagine the hospital acquiring a bakery every Tuesday.'),
 right=dict(sentence='We used to have a bakery in the basement.',
            boundary=0.50, boundary_label='used to = a state or a habit',
            event=0.26, event_label='have a bakery = a state, and it has ended',
            why='Used to carries states as well as habits, so the bakery can simply have '
                'existed and then stopped existing, which is what happened.'),
 misconception='Learners are told that would and used to are interchangeable. They are '
               'interchangeable for repeated actions only. For states - have, be, know, own, '
               'live - only used to works.'),

"fig_b12_u01_p04_v04": dict(type='V4', height=740,
 title='The canteen in 1994, and this year',
 sub='Learner A has the 1994 menu and prices. Learner B has this year\'s. Neither sees the other.',
 alt='Two panels comparing a 1994 hospital canteen counter with the current one, with different '
     'equipment, staffing and signage.',
 differences=8, prompt='Three things cost less now and two cost more. Which?',
 left=dict(label='1994', art=[
   dict(kind='person', x=140, y=0, h=112, skin=2, cloth=1),
   dict(kind='person', x=215, y=0, h=110, skin=3, cloth=0),
   dict(kind='person', x=290, y=0, h=112, skin=1, cloth=2),
   dict(kind='person', x=365, y=0, h=110, skin=4, cloth=3),
   dict(kind='block', x=140, y=130, w=300, bh=36, colour='#C86B2B'),
   dict(kind='label', x=300, y=210, text='four cooks, six hot dishes, one till',
        colour='#C86B2B')]),
 right=dict(label='this year', art=[
   dict(kind='person', x=180, y=0, h=112, skin=2, cloth=1),
   dict(kind='person', x=260, y=0, h=110, skin=0, cloth=4),
   dict(kind='block', x=340, y=0, w=80, bh=110, colour='#9AA7AE'),
   dict(kind='block', x=140, y=130, w=180, bh=36, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='two cooks, four dishes, two machines',
        colour='#2E6F5E')])),

"fig_b12_u01_p05_v05": dict(type='V5', height=1060,
 title='Two canteen menus, thirty-one years apart',
 sub='Typed in 1994 and laminated now, and only one of them has a cost note on it.',
 alt='Two hospital canteen menus compared, listing hot dishes, prices, staff subsidy and a note '
     'about what a staff meal costs the hospital.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  COMEDOR  -  1994'),
   dict(t='grid', cols=['DISH', 'PRICE', 'SERVED'],
     data=[['Fish of the day', '340', 'lunch and supper'],
           ['Cazuela', '290', 'lunch and supper'],
           ['Beans and rice', '210', 'all day'],
           ['Bread (baked here)', '40', 'all day'],
           ['Fruit, in season', '60', 'all day'],
           ['Tinned fruit', '45', 'all day']]),
   dict(t='kv', k='Hot dishes', v='6', mono=True),
   dict(t='kv', k='Staff price', v='half', mono=False),
   dict(t='kv', k='Night service', v='22.00 - 06.00', mono=True),
   dict(t='rule'),
   dict(t='org', text='COMEDOR  -  THIS YEAR'),
   dict(t='grid', cols=['DISH', 'PRICE', 'SERVED'],
     data=[['Fish of the day', '2,950', 'lunch only'],
           ['Cazuela', '2,400', 'lunch and supper'],
           ['Beans and rice', '1,850', 'all day'],
           ['Bread (delivered)', '450', 'all day'],
           ['Tinned fruit', '600', 'all day'],
           ['Salad bar (per 100 g)', '390', 'lunch only']]),
   dict(t='kv', k='Hot dishes', v='4', mono=True),
   dict(t='kv', k='Staff price', v='subsidised 55 %', mono=False),
   dict(t='kv', k='Night service', v='22.00 - 06.00', mono=True),
   dict(t='rule'),
   dict(t='sign', text='COST NOTE, FOOT OF THE CURRENT MENU, STAFF COPIES ONLY:'),
   dict(t='para', text='"A subsidised staff meal costs the hospital 2,180. The subsidy is '
     'funded from the catering budget, which has fallen 19 % in real terms since 2019. The '
     'subsidy is reviewed each March."')],
 callouts=[dict(at=0.09, text='Six hot dishes, and the bread was baked downstairs'),
   dict(at=0.17, text='Fish twice a day, and it was the second cheapest hot dish'),
   dict(at=0.30, text='Half price for staff, with no percentage anywhere'),
   dict(at=0.56, text='Fish at lunch only - and the night shift is asleep at lunch'),
   dict(at=0.66, text='Bread is delivered now. The basement bakery closed in 1998'),
   dict(at=0.94, text='The only sentence on either menu with a budget in it')]),

"fig_b12_u01_p07_v10": dict(type='V10', kind='elision', height=660,
 title='Four phrases, one sound',
 sub='Used to is /ˈjuːstə/ in all four. The spelling changes and the sound does not.',
 alt='Five phrases containing used to shown written and spoken, with the d silent in every one.',
 pairs=[dict(written='used to cook', spoken='ˈjuːstəkʊk', dropped='d',
     note='to = the infinitive. A verb follows'),
   dict(written="I'm used to it", spoken='aɪmˈjuːstəwɪt', dropped='d',
     note='to = a preposition. A noun follows'),
   dict(written='get used to it', spoken='ɡetˈjuːstəwɪt', dropped='d',
     note='the process, not the state'),
   dict(written="didn't use to", spoken='ˈdɪdntjuːstə', dropped='',
     note='no d in the spelling either'),
   dict(written='I USED to', spoken='aɪˈjuːstuː', dropped='d',
     note='stressed, and it is the whole answer')]),

"fig_b12_u01_p08_v02": dict(type='V2', height=800,
 title='The hospital kitchen, in section',
 sub='Four levels, and the one that closed in 1998 is the one people still mention.',
 alt='A hospital kitchen drawn in section with the servery, the preparation kitchen, the cold '
     'store and the basement bakery, each labelled with its date and its state.',
 floors=[dict(was='the servery', now='Steam counter, salad bar, two machines. Open 06.00-22.00',
     year='', fill='#E4ECEF'),
   dict(was='the preparation kitchen', now='Two cooks. Four menus. Fresh on two of them',
     year='', fill='#E6EFE9'),
   dict(was='the cold store', now='Deliveries twice a week. Nothing is bought daily any more',
     year='2011', fill='#F6F0E4'),
   dict(was='the basement bakery', now='Closed 1998. Still has the ovens in it', year='1998',
     fill='#EFE2DD')],
 callouts=[dict(at=0.12, text='Where the four hundred meals are actually handed over'),
   dict(at=0.38, text='Four cooks in 1994. Two now, and the same number of meals'),
   dict(at=0.62, text='Twice a week is why fresh fish is lunch only'),
   dict(at=0.88, text='Twenty-seven years shut, and everybody over fifty mentions it')]),

"fig_b12_u01_p09_v05": dict(type='V5', height=1040,
 title='The annual review form',
 sub='Six boxes, two of them optional, and none of them is where Rosa\'s point goes.',
 alt='A staff annual review form with six sections covering objectives, achievement, development '
     'and any other matters, with notes on which boxes trigger action.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  ANNUAL REVIEW  -  FORM RH-2'),
   dict(t='kv', k='Employee', v='R. Fuentes, reception', mono=False),
   dict(t='kv', k='In post', v='14 years', mono=True),
   dict(t='kv', k='Reviewer', v='line manager', mono=False),
   dict(t='rule'),
   dict(t='head', text='THE SIX BOXES'),
   dict(t='grid', cols=['BOX', 'WHAT IT ASKS', 'TRIGGERS ACTION?'],
     data=[['1  Objectives set', 'last year\'s, listed', 'no'],
           ['2  Achievement', 'met / partly / not met', 'no'],
           ['3  Strengths', 'free text', 'no'],
           ['4  Development needs', 'free text', 'yes - training budget'],
           ['5  Objectives for next year', 'free text', 'yes - reviewed in Dec'],
           ['6  Any other matters (optional)', 'free text', 'no']]),
   dict(t='para', text='Box 6 is marked optional on the form and is not read by anybody above '
     'the line manager. Boxes 4 and 5 are extracted into a departmental summary each April.'),
   dict(t='rule'),
   dict(t='head', text='WHAT ROSA RAISED'),
   dict(t='para', text='That reception is the first point of contact for every complaint about '
     'waiting times, that nobody has ever recorded how many, and that she has been counting '
     'them herself since February.'),
   dict(t='kv', k='Her count, Feb-Sep', v='1,140', mono=True),
   dict(t='kv', k='Official figure', v='none held', mono=False),
   dict(t='rule'),
   dict(t='sign', text='WHERE IT WENT:'),
   dict(t='para', text='"Box 5. Objective for next year: establish a complaints log at '
     'reception. - agreed, both signed."')],
 callouts=[dict(at=0.22, text='Six boxes, and four of them go nowhere'),
   dict(at=0.44, text='Box 4 and box 5 are the only two that leave the room'),
   dict(at=0.52, text='Box 6 is optional, unread, and where this would naturally have gone'),
   dict(at=0.74, text='Eleven hundred and forty, counted by one person, unasked'),
   dict(at=0.80, text='And the official figure is that there is no figure'),
   dict(at=0.94, text='Box 5, because box 5 is extracted in April')]),

"fig_b12_u01_p10_v12": dict(type='V12', height=880,
 title='Thirty-five years of one region\'s plate',
 sub='Half the class sees 1990. Half sees now. Rebuild the whole change by speaking.',
 alt='An infographic of regional diet change from 1990 to the present showing fresh and tinned '
     'purchases, afternoon occupancy and the canteen decisions that followed.',
 span=['1990', 'now'], ticks=6,
 tick_labels=['1990', '1998', '2006', '2011', '2019', 'now'],
 bands=[dict(name='The hospital kitchen', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.24}, label='bakery and four cooks', colour='#2E6F5E'),
   dict(**{'from': 0.24, 'to': 0.62}, label='four cooks, no bakery', colour='#D9A441'),
   dict(**{'from': 0.62, 'to': 1.0}, label='two cooks, deliveries twice a week',
     colour='#C86B2B')]),
  dict(name='What changed outside', type='events', items=[
   dict(at=0.24, label='basement bakery closes', colour='#A8372E'),
   dict(at=0.46, label='afternoon occupancy falls below 20 %', colour='#8C6A9E'),
   dict(at=0.62, label='daily buying ends - two deliveries a week', colour='#C86B2B'),
   dict(at=0.84, label='catering budget falls 19 % in real terms', colour='#A8372E'),
   dict(at=0.98, label='portions cut 15 %, fresh line kept', colour='#2E6F5E')]),
  dict(name='Fresh fish purchases a month', type='line',
   points=[(0, 11), (0.3, 9), (0.5, 7), (0.7, 5), (0.9, 3.4), (1.0, 3)], end_label='3'),
  dict(name='The explanations people give', type='flags', items=[
   dict(at=0.18, label='over sixty: young people cannot cook'),
   dict(at=0.50, label='under thirty: fish is expensive'),
   dict(at=0.76, label='the figures: +40 % fresh, +34 % tinned'),
   dict(at=0.96, label='41 % at home at three, down to 11 %')])]),

"fig_b12_u01_p11_v06": dict(type='V6', kind='bar', height=800,
 title='What each option saves, and who pays for it',
 sub='Three ways of closing a nineteen per cent gap on a canteen that feeds four hundred.',
 alt='A bar chart of the percentage saved by each canteen option against the number of people '
     'affected by it.',
 labels=['processed line', 'smaller portions', 'close nights', 'do nothing'],
 ymin=0, ymax=30, fmt='{:,.0f}',
 series=[dict(name='% of budget saved', values=[11, 0, 22, 0], colour='#1F4E5F'),
   dict(name='people worse off (x0.05)', values=[20, 20, 7, 0], colour='#A8372E')],
 note='Closing the night service saves twice as much as the processed line and affects a third '
      'as many people, which is exactly why it keeps being proposed.',
 warning='Smaller portions save nothing on paper. They turned out to save thirty-one per cent of '
         'the waste, which nobody had modelled, because nobody weighs what goes in the bin.'),
}
