"""B1.2 Unit 2 - The Form Nobody Signs - twelve figures, as data."""
FIGURES = {
"fig_b12_u02_p00_v01": dict(type='V1', height=840, storey_h=155,
 title='Ward 4, 15.50',
 sub='Twelve things to find. Three of them exist to stop something, and two are being used wrong.',
 alt='A hospital ward corridor with a drug cupboard, a whiteboard of names, a crash trolley, a '
     'sharps bin, a near-miss form box and a wedged fire door.',
 sky='#E0E5E6', ground='#A3A8A8', ground_line=680,
 buildings=[dict(x=20, w=560, storeys=3, colour='#D4D0C6', label='ward 4'),
   dict(x=640, w=360, storeys=2, colour='#CBC7BC', label='the drug room'),
   dict(x=1060, w=520, storeys=3, colour='#C2BEB4', label='pharmacy, floor above')],
 props=[dict(kind='box', x=700, y=680, s=1.3), dict(kind='box', x=790, y=680, s=1.2),
   dict(kind='table', x=260, y=680, s=1.4), dict(kind='table', x=470, y=680, s=1.3),
   dict(kind='crate', x=1120, y=680, s=1.1),
   dict(kind='sign', x=120, y=680, s=.75, text='2 mg'),
   dict(kind='sign', x=620, y=680, s=.7, text='20 mg'),
   dict(kind='sign', x=1500, y=680, s=.7, text='15:50')],
 people=[dict(x=200, y=680, h=88, skin=1, cloth=2, hair='long', arm='hold'),
   dict(x=380, y=680, h=87, skin=2, cloth=0, hair='short', arm='point'),
   dict(x=560, y=680, h=88, skin=4, cloth=3, hair='cap', arm='hold'),
   dict(x=900, y=680, h=87, skin=3, cloth=1, hair='bun', arm='down'),
   dict(x=1200, y=680, h=88, skin=0, cloth=4, hair='grey', arm='folded')],
 names=[dict(x=200, t='Carla, who filed two of three'), dict(x=380, t='Dr Benitez, locum, week 3'),
   dict(x=560, t='Ignacio, reading a wristband'), dict(x=900, t='the drug cupboard, two locks'),
   dict(x=1200, t='the reversal agent, floor above'), dict(x=120, t='what was prescribed'),
   dict(x=620, t='what was prepared')],
 markers=[dict(x=200, y=560), dict(x=380, y=560), dict(x=560, y=560), dict(x=900, y=560),
   dict(x=1200, y=560), dict(x=120, y=612), dict(x=620, y=612), dict(x=1500, y=612),
   dict(x=260, y=632), dict(x=470, y=634), dict(x=700, y=624), dict(x=1120, y=628)]),

"fig_b12_u02_p01_v08": dict(type='V8', height=800,
 title='Six things that had to line up',
 sub='Remove any one of them and nothing reaches the bedside. All six were in place by March.',
 alt='A network of six contributing factors - labelling, a broken scanner, a locum, a rota, '
     'unread reports and a transcription - converging on one near miss.',
 nodes={
  'lab': dict(x=170, y=230, short='1', name='The labelling', sub='changed and changed back', colour='#C86B2B'),
  'sca': dict(x=170, y=560, short='2', name='The scanner', sub='broken since March', colour='#A8372E'),
  'loc': dict(x=540, y=180, short='3', name='A locum', sub='week three', colour='#8C6A9E'),
  'rot': dict(x=540, y=620, short='4', name='The rota', sub='forty minutes over', colour='#9AA7AE'),
  'rep': dict(x=900, y=400, short='5', name='Three reports', sub='same cupboard, filed', colour='#D9A441'),
  'bed': dict(x=1290, y=400, short='6', name='The bedside', sub='16.08, a wristband', r=54,
    colour='#2E6F5E')},
 edges=[dict(a='lab', b='rep', label='reported in March, April, June', sw=5),
   dict(a='sca', b='bed', label='nothing was checked on the way', sw=6),
   dict(a='loc', b='bed', label='three weeks in, and nobody told him', sw=5),
   dict(a='rot', b='rep', label='the third form was not filed', sw=4, dash='5 5'),
   dict(a='rep', b='bed', label='all three went to the same inbox', sw=4, dash='5 5'),
   dict(a='lab', b='bed', label='20 and 2 on adjacent shelves', sw=6)]),

"fig_b12_u02_p02_v07": dict(type='V7', height=820,
 title='Two milligrams',
 sub='One of them prepared it. One of them caught it, and was not supposed to be reading it.',
 alt='A night nurse and a porter in a ward corridor, with speech bubbles containing third '
     'conditionals.',
 bg='#E8EBEC',
 set=[dict(kind='table', x=700, y=700, s=1.4), dict(kind='box', x=1300, y=700, s=1.1)],
 people=[dict(x=470, h=250, skin=1, cloth=2, hair='long', arm='hold', facing='right',
   label='Carla', role='night nurse', says=["If I hadn't looked at the wristband, she would "
     'have had it.', "If only I'd said something in March."]),
  dict(x=980, h=248, skin=4, cloth=3, hair='cap', arm='point', facing='left',
   label='Ignacio', role='porter, 22 years', says=['But for the scanner being broken, none of '
     'this would have happened.'])]),

"fig_b12_u02_p03_v09": dict(type='V9', kind='branch', height=720,
 title='One Thursday, four unreal pasts',
 sub='Every branch is the opposite of what happened. That is what the form is for.',
 alt='A branching diagram from one near miss into four counterfactual outcomes, each with its '
     'conditional form.',
 root='at 16.08...',
 branches=[dict(label='IF HE HADN\'T READ THE WRISTBAND',
     example='she would have had twenty milligrams, and reversal is on the floor above',
     colour='#A8372E'),
   dict(label='HAD THE SCANNER BEEN WORKING',
     example='it would have been stopped at the cupboard, forty minutes earlier',
     colour='#1F4E5F'),
   dict(label='IF ANYBODY HAD ACTED IN MARCH',
     example='the cupboard would have been relabelled and we would not be here now',
     colour='#C86B2B'),
   dict(label='IF ONLY I HAD FILED THE THIRD ONE',
     example='a regret, not a consequence - it would probably have changed nothing',
     colour='#9AA7AE', dash='6 6')],
 rule='Everything in a third conditional is unreal. Both halves are the opposite of the facts. '
      'And would never appears in the if half.'),

"fig_b12_u02_p03_v11": dict(type='V11', height=680,
 title='The commonest conditional error in English',
 alt='Two panels comparing a sentence with would in the if-clause and the correct past perfect '
     'version, with the logic of each.',
 wrong=dict(sentence="If I wouldn't have looked, she would have had it.",
            boundary=0.46, boundary_label='the condition',
            event=0.76, event_label='would, twice',
            why='Would belongs to the result, not to the condition. Putting it in both halves '
                'makes the sentence say that the looking was itself a consequence of something '
                'else - and then the result has nothing to hang from.'),
 right=dict(sentence="If I hadn't looked, she would have had it.",
            boundary=0.46, boundary_label='the condition: past perfect',
            event=0.78, event_label='the result: would have',
            why='The past perfect carries the unreal condition and would have carries the unreal '
                'result. Each half does one job, and the sentence has somewhere to start.'),
 misconception='The two halves feel parallel, so learners make them look parallel. They are not '
               'parallel: one is a hypothesis and the other is its consequence, and English '
               'marks them with different machinery.'),

"fig_b12_u02_p04_v04": dict(type='V4', height=740,
 title='The timeline, and the three reports',
 sub='Learner A has the Thursday. Learner B has March, April and June. Neither sees the other.',
 alt='Two panels compared: a single-day incident timeline and a sequence of three earlier '
     'reports about the same cupboard.',
 differences=7, prompt='At which point did this stop being bad luck?',
 left=dict(label='Thursday, 15.50 - 16.08', art=[
   dict(kind='block', x=130, y=0, w=60, bh=60, colour='#A8372E'),
   dict(kind='block', x=210, y=0, w=60, bh=60, colour='#A8372E'),
   dict(kind='person', x=320, y=0, h=112, skin=4, cloth=3, arm='point'),
   dict(kind='label', x=300, y=210, text='eighteen minutes, and one wristband',
        colour='#A8372E')]),
 right=dict(label='March, April, June', art=[
   dict(kind='doc', x=150, y=0), dict(kind='doc', x=260, y=0), dict(kind='doc', x=370, y=0),
   dict(kind='cross', x=470, y=40),
   dict(kind='label', x=300, y=210, text='three forms, one inbox, 04.11',
        colour='#9AA7AE')])),

"fig_b12_u02_p05_v05": dict(type='V5', height=1060,
 title='The near-miss form, and the twelve-month summary',
 sub='Eleven fields, four compulsory, and one of them was added this year.',
 alt='A hospital near-miss reporting form and the annual summary of reports filed, showing the '
     'split between signed and anonymous reports and the action rate of each.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  NEAR-MISS REPORT  -  SF-7'),
   dict(t='head', text='THE FIELDS'),
   dict(t='grid', cols=['FIELD', 'COMPULSORY?', 'NOTE'],
     data=[['Date and time', 'yes', '-'],
           ['Location', 'yes', '-'],
           ['What happened', 'yes', 'free text, no limit'],
           ['What stopped it', 'yes', 'free text'],
           ['Your name', 'NO', 'see below'],
           ['Contact for follow-up', 'no', 'only if named'],
           ['Contributing factors', 'no', 'added this year'],
           ['Has this happened before?', 'no', 'added this year']]),
   dict(t='para', text='An anonymous report is accepted and logged. It cannot be followed up, '
     'because there is nobody to ask. A named report may be followed up and the reporter is '
     'protected under the disclosure policy, which has been in force since 2019 and has never '
     'been tested.'),
   dict(t='rule'),
   dict(t='head', text='TWELVE-MONTH SUMMARY'),
   dict(t='grid', cols=['', 'FILED', 'ACTION RECORDED'],
     data=[['Signed', '38', '23  (61 %)'], ['Anonymous', '17', '2  (9 %)'],
           ['Total', '55', '25  (45 %)']]),
   dict(t='kv', k='Filed six years ago', v='164', mono=True),
   dict(t='kv', k='Signatures introduced', v='2019', mono=True),
   dict(t='rule'),
   dict(t='sign', text='FREE-TEXT BOX, FOOT OF THE FORM, NOT SUMMARISED ANYWHERE:'),
   dict(t='para', text='"Anything else you want to say. This box is not reported on."')],
 callouts=[dict(at=0.20, text='Four compulsory fields, and none of them asks why'),
   dict(at=0.28, text='Your name is the only optional field that changes everything'),
   dict(at=0.36, text='Two new fields, both of them the useful kind'),
   dict(at=0.52, text='Protected since 2019, and never tested'),
   dict(at=0.72, text='Sixty-one per cent against nine. The whole argument'),
   dict(at=0.80, text='A hundred and sixty-four, before anybody had to sign'),
   dict(at=0.94, text='Not reported on - and it turned out to hold the useful part')]),

"fig_b12_u02_p07_v10": dict(type='V10', kind='elision', height=680,
 title='Four consonants in a row',
 sub='In wouldn\'t have there are four consonant sounds between the vowels, and nobody says all '
     'of them.',
 alt='Five conditional phrases shown written and spoken, with have reduced to a schwa and the '
     'consonant clusters simplified.',
 pairs=[dict(written='would have', spoken='ˈwʊdəv', dropped='ha', note="would've - never would of"),
   dict(written="wouldn't have", spoken='ˈwʊdntəv', dropped='ha',
     note='d-n-t-v, and the t usually goes'),
   dict(written="hadn't", spoken='ˈhædnt', dropped='o', note='the n and t run together'),
   dict(written="if I hadn't", spoken='ɪfaɪˈhædnt', dropped='o', note='three words, two beats'),
   dict(written='had it not been', spoken='hædɪtnɒtˈbɪn', dropped='',
     note='the formal one, and it is said in full')]),

"fig_b12_u02_p08_v02": dict(type='V2', height=800,
 title='The drug room, in section',
 sub='Four levels, and the two that matter are twenty centimetres apart.',
 alt='A hospital drug room drawn in section with the top shelf, two adjacent dose shelves, the '
     'bench and the locked controlled cupboard.',
 floors=[dict(was='the top shelf', now='Rarely used. Relabelled in April and back in May',
     year='May', fill='#EFE2DD'),
   dict(was='shelf 2', now='20 mg. Blue box, white label', year='', fill='#E4ECEF'),
   dict(was='shelf 3', now='2 mg. Blue box, white label, 20 cm below', year='',
     fill='#E6EFE9'),
   dict(was='the bench', now='Where it is drawn up, and where the scanner should be', year='',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Changed twice by two people who never spoke'),
   dict(at=0.38, text='The one that was taken'),
   dict(at=0.62, text='The one that was prescribed'),
   dict(at=0.88, text='The scanner has been broken since March and is still on the order list')]),

"fig_b12_u02_p09_v05": dict(type='V5', height=1040,
 title='The lecture handout',
 sub='Three models of error, and the hospital\'s form is built on the first one.',
 alt='A teaching handout comparing the person model, the system model and the resilience model '
     'of error, with what each one asks and what each one misses.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  TEACHING  -  WHY SAFE SYSTEMS FAIL'),
   dict(t='head', text='THREE MODELS'),
   dict(t='grid', cols=['MODEL', 'ASKS', 'MISSES'],
     data=[['1  The person model', 'who was careless?', 'why it was easy to do'],
           ['2  The system model', 'what made it likely?', 'why it usually does not happen'],
           ['3  The resilience model', 'why does it normally go right?',
            'nothing, but it is hard to fund']]),
   dict(t='para', text='Model 1 produces a name and a training requirement. Model 2 produces a '
     'change to a cupboard. Model 3 produces an interest in the porter who was reading a '
     'wristband he was not supposed to be reading.'),
   dict(t='rule'),
   dict(t='head', text='WHAT THE FORM ASKS'),
   dict(t='kv', k='What happened', v='model 1 and 2', mono=False),
   dict(t='kv', k='What stopped it', v='model 3', mono=False),
   dict(t='kv', k='Contributing factors', v='model 2 - added this year', mono=False),
   dict(t='kv', k='Your name', v='model 1', mono=False),
   dict(t='rule'),
   dict(t='head', text='THE SENTENCE SHE SAYS TWICE'),
   dict(t='para', text='"Every system that has not killed anybody is being held up by somebody '
     'doing something that is not in their job description."'),
   dict(t='rule'),
   dict(t='sign', text='LAST LINE OF THE HANDOUT:'),
   dict(t='para', text='"If you remember nothing else: the question is not who, and it is not '
     'even what. It is why it normally works."')],
 callouts=[dict(at=0.20, text='The model most investigations are built on'),
   dict(at=0.26, text='The model most policies claim to be built on'),
   dict(at=0.32, text='The model that explains the porter'),
   dict(at=0.46, text='One field of eight is a model 3 question, and it is compulsory'),
   dict(at=0.72, text='Said twice, deliberately, twenty minutes apart'),
   dict(at=0.94, text='The one-line takeaway, and the only line in bold')]),

"fig_b12_u02_p10_v12": dict(type='V12', height=880,
 title='From March to the Thursday',
 sub='Half the class sees the timeline. Half sees the reports. Rebuild the year by speaking.',
 alt='An infographic of a near miss showing three earlier reports, the labelling changes, the '
     'broken scanner and the eighteen minutes on the day itself.',
 span=['March', 'December'], ticks=6,
 tick_labels=['Mar', 'Apr', 'Jun', 'the Thursday', 'Sep', 'Dec'],
 bands=[dict(name='The cupboard', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.16}, label='labelled as built', colour='#9AA7AE'),
   dict(**{'from': 0.16, 'to': 0.30}, label='relabelled', colour='#2E6F5E'),
   dict(**{'from': 0.30, 'to': 0.82}, label='relabelled back - no one told pharmacy',
     colour='#A8372E'),
   dict(**{'from': 0.82, 'to': 1.0}, label='separated and recoded', colour='#2E6F5E')]),
  dict(name='The scanner', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='broken, and on the order list', colour='#C86B2B')]),
  dict(name='What was filed', type='events', items=[
   dict(at=0.04, label='report 1, signed', colour='#1F4E5F'),
   dict(at=0.36, label='report 2, signed - auto-reply at 04.11', colour='#1F4E5F'),
   dict(at=0.52, label='report 3, not filed', colour='#9AA7AE'),
   dict(at=0.66, label='20 mg prepared. Caught at 16.08', colour='#A8372E'),
   dict(at=0.90, label='both options kept, rates printed on the form', colour='#2E6F5E')]),
  dict(name='Reports a month', type='line',
   points=[(0, 4), (0.3, 4), (0.6, 5), (0.82, 5), (0.92, 7), (1.0, 7)], end_label='7'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.22, label='nobody told pharmacy why'),
   dict(at=0.48, label='nobody read the free-text box'),
   dict(at=0.72, label='nobody thanked the porter in writing'),
   dict(at=0.96, label='and now one person reads it on Fridays')])]),

"fig_b12_u02_p11_v06": dict(type='V6', kind='line', height=800,
 title='Reports filed, and actions taken, over six years',
 sub='Signatures were introduced in 2019. The two lines have not moved together since.',
 alt='A line chart of near-miss reports filed each year against recorded actions, with a marked '
     'fall in reports after signatures were introduced.',
 labels=['yr 1', 'yr 2', 'yr 3', 'yr 4', 'yr 5', 'this yr'],
 ymin=0, ymax=180, fmt='{:,.0f}',
 series=[dict(name='reports filed', values=[164, 151, 61, 58, 55, 77], colour='#1F4E5F'),
   dict(name='actions recorded', values=[14, 16, 21, 24, 25, 26], colour='#2E6F5E')],
 note='Reports fell by nearly two thirds when signatures were introduced. Actions rose, because '
      'a named report can be followed up and an anonymous one cannot.',
 warning='Both sides of this argument have been quoting one of these two lines for four years. '
         'Nobody had put them on the same chart.'),
}
