"""B1.2 Unit 3 - The Post That Ends on Friday - twelve figures, as data."""
FIGURES = {
"fig_b12_u03_p00_v01": dict(type='V1', height=840, storey_h=155,
 title='The staff corridor, Wednesday',
 sub='Eleven things to find. Four of them are about somebody\'s future.',
 alt='A hospital staff corridor with a vacancy notice, a rota, a shortlist pinned to a board, a '
     'coffee machine, a 1998 intake photograph and a leaving card going round.',
 sky='#DFE4E6', ground='#A1A6A6', ground_line=680,
 buildings=[dict(x=20, w=520, storeys=3, colour='#D3CFC5', label='the staff corridor'),
   dict(x=600, w=340, storeys=2, colour='#CAC6BA', label='the office'),
   dict(x=1000, w=580, storeys=3, colour='#C1BDB3', label='emergency')],
 props=[dict(kind='hoarding', x=240, y=680, s=1.0),
   dict(kind='table', x=680, y=680, s=1.4), dict(kind='doc', x=680, y=610),
   dict(kind='box', x=1060, y=680, s=1.2), dict(kind='crate', x=1150, y=680, s=1.1),
   dict(kind='sign', x=120, y=680, s=.7, text='VACANCY'),
   dict(kind='sign', x=560, y=680, s=.7, text='11 mo'),
   dict(kind='sign', x=1520, y=680, s=.7, text='FRI')],
 people=[dict(x=330, y=680, h=88, skin=0, cloth=4, hair='grey', arm='point'),
   dict(x=450, y=680, h=87, skin=2, cloth=0, hair='short', arm='hold'),
   dict(x=760, y=680, h=88, skin=3, cloth=1, hair='bun', arm='down'),
   dict(x=1120, y=680, h=87, skin=1, cloth=2, hair='long', arm='hold'),
   dict(x=1330, y=680, h=88, skin=4, cloth=3, hair='cap', arm='folded')],
 names=[dict(x=330, t='Dr Herrera, since 2007'), dict(x=450, t='Dr Benitez, locum, week three'),
   dict(x=760, t='Rosa, holding the leaving card'), dict(x=1120, t='Carla, off the rota at eight'),
   dict(x=1330, t='Ignacio, who knows every pipe'), dict(x=120, t='advertised four times'),
   dict(x=560, t='how long it has been empty')],
 markers=[dict(x=330, y=560), dict(x=450, y=560), dict(x=760, y=560), dict(x=1120, y=560),
   dict(x=1330, y=560), dict(x=120, y=612), dict(x=560, y=612), dict(x=1520, y=612),
   dict(x=240, y=624), dict(x=680, y=632), dict(x=1060, y=628)]),

"fig_b12_u03_p01_v08": dict(type='V8', height=800,
 title='A career, drawn as the things that were not decided',
 sub='Six nodes. Only two of the arrows were anybody\'s choice.',
 alt='A network of career stages from training through an interview, a rotation and a post to '
     'where somebody is now, with chance events marked on the links.',
 nodes={
  'tra': dict(x=170, y=400, short='1', name='Training', sub='and what you wanted then', colour='#2E6F5E'),
  'int': dict(x=520, y=200, short='2', name='The interview', sub='a Tuesday, in Temuco', colour='#D9A441'),
  'cha': dict(x=520, y=600, short='3', name='The cancellation', sub='one train, no decision', colour='#A8372E'),
  'rot': dict(x=900, y=400, short='4', name='The rotation', sub='the one still open', colour='#C86B2B'),
  'pos': dict(x=1250, y=240, short='5', name='The post', sub='eighteen years', r=54, colour='#1F4E5F'),
  'wou': dict(x=1250, y=580, short='6', name='Who you became', sub='and it is different', r=54,
    colour='#8C6A9E')},
 edges=[dict(a='tra', b='int', label='arranged a whole year around it', sw=6),
   dict(a='cha', b='int', label='no train, and a bus that was 40 min', sw=5, colour='#A8372E'),
   dict(a='int', b='rot', label='the decision on the platform', sw=4, dash='5 5'),
   dict(a='rot', b='pos', label='because it was the only one open', sw=6),
   dict(a='pos', b='wou', label='emergency changes what you are like', sw=6),
   dict(a='tra', b='wou', label='the paediatrician who does not exist', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_b12_u03_p02_v07": dict(type='V7', height=820,
 title='Three weeks and a Friday',
 sub='One of them runs the department. One of them has not been asked anything.',
 alt='A consultant and a locum doctor talking in a corridor, with speech bubbles containing '
     'mixed conditionals.',
 bg='#E8EBEC',
 set=[dict(kind='table', x=700, y=700, s=1.4), dict(kind='doc', x=700, y=630)],
 people=[dict(x=470, h=250, skin=0, cloth=4, hair='grey', arm='point', facing='right',
   label='Dr Herrera', role='emergency, 18 years',
   says=['If we had advertised in March, we would have somebody by now.',
     "If he hadn't come, we would be three doctors short tonight."]),
  dict(x=980, h=248, skin=2, cloth=0, hair='short', arm='folded', facing='left',
   label='Dr Benitez', role='locum, week three',
   says=['If I were a permanent member of staff, I would have said this in March.'])]),

"fig_b12_u03_p03_v09": dict(type='V9', kind='branch', height=740,
 title='Four conditionals, and two of them are mixed',
 sub='Ask what time each half is really in. English takes the if-half from one type and the '
     'result from another.',
 alt='A branching diagram from one situation into second, third and two mixed conditionals, each '
     'with its two time frames marked.',
 root='the post was not advertised in March...',
 branches=[dict(label='SECOND: unreal now -> unreal now',
     example='If we advertised more widely, we would get more applicants', colour='#2E6F5E'),
   dict(label='THIRD: unreal past -> unreal past',
     example='If we had advertised in March, we would have appointed in June', colour='#1F4E5F'),
   dict(label='MIXED A: unreal PAST -> unreal PRESENT',
     example='If we had advertised in March, we would have somebody BY NOW', colour='#C86B2B'),
   dict(label='MIXED B: unreal PRESENT -> unreal PAST',
     example='If I WERE permanent, I would have said something in March', colour='#8C6A9E')],
 rule='By now, today and at the moment in the result half are almost always signals for mixed A. '
      'A permanent state in the if half - if I were, if he spoke - is the signal for mixed B.'),

"fig_b12_u03_p03_v11": dict(type='V11', height=700,
 title='When the two halves are put in the same time by mistake',
 alt='Two panels comparing a third conditional and a mixed conditional about the same situation, '
     'with the time of the result half marked on each.',
 wrong=dict(sentence='If we had advertised in March, we would have had somebody by now.',
            boundary=0.48, boundary_label='the if-half: past',
            event=0.30, event_label='the result: ALSO past',
            why='Would have had puts the having in the past and finishes it there. With by now '
                'attached, the sentence says we would have had somebody at some earlier point '
                'and no longer do - which is not what anybody means. The result is about today.'),
 right=dict(sentence='If we had advertised in March, we would have somebody by now.',
            boundary=0.48, boundary_label='the if-half: past',
            event=0.80, event_label='the result: NOW',
            why='Would have, with no participle, puts the having in the present. The unreal past '
                'causes an unreal present, which is exactly the situation: no advertisement '
                'then, no doctor today.'),
 misconception='Learners match the two halves because they look like they should agree. The '
               'whole point of a mixed conditional is that they do not: one half names a time '
               'and the other names a different one.'),

"fig_b12_u03_p04_v04": dict(type='V4', height=740,
 title='The 1998 intake, and where they are now',
 sub='Learner A has the photograph. Learner B has what each of them said they wanted.',
 alt='Two panels comparing a group photograph of a 1998 medical intake with a list of where the '
     'same people are working now.',
 differences=8, prompt='Two of them got what they said. Which, and how can you tell?',
 left=dict(label='1998, what they wanted', art=[
   dict(kind='person', x=130, y=0, h=110, skin=0, cloth=1),
   dict(kind='person', x=200, y=0, h=112, skin=2, cloth=0),
   dict(kind='person', x=270, y=0, h=110, skin=1, cloth=2),
   dict(kind='person', x=340, y=0, h=112, skin=3, cloth=4),
   dict(kind='person', x=410, y=0, h=110, skin=4, cloth=3),
   dict(kind='label', x=300, y=210, text='five specialities, five answers', colour='#2E6F5E')]),
 right=dict(label='now, where they are', art=[
   dict(kind='person', x=150, y=0, h=112, skin=0, cloth=1),
   dict(kind='person', x=230, y=0, h=110, skin=2, cloth=0),
   dict(kind='gap', x=310, y=10, w=60, bh=90),
   dict(kind='person', x=390, y=0, h=112, skin=3, cloth=4),
   dict(kind='label', x=300, y=210, text='two matches, two moves, one gone',
        colour='#C86B2B')])),

"fig_b12_u03_p05_v05": dict(type='V5', height=1060,
 title='The vacancy notice, and one month of locum invoices',
 sub='Eleven months live, four advertisements, and a surcharge line nobody reads.',
 alt='A hospital vacancy notice for a consultant post alongside an agency locum invoice showing '
     'shift rates, agency margin and an out-of-hours surcharge.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  VACANCY  -  EM/4471'),
   dict(t='kv', k='Post', v='Consultant, emergency medicine', mono=False),
   dict(t='kv', k='Salary', v='4,160,000 / month', mono=True),
   dict(t='kv', k='First advertised', v='eleven months ago', mono=False),
   dict(t='kv', k='Times advertised', v='4', mono=True),
   dict(t='kv', k='Applicants, all rounds', v='4', mono=True),
   dict(t='kv', k='Appointed', v='none', mono=False),
   dict(t='para', text='"We are looking for the right fit for a busy and supportive '
     'department." The notice does not state the rota, the number of unfilled posts, or that '
     'the department has been running short since January.'),
   dict(t='rule'),
   dict(t='org', text='AGENCY INVOICE  -  ONE MONTH OF COVER'),
   dict(t='grid', cols=['LINE', 'RATE', 'TOTAL'],
     data=[['Day shifts  (14)', '248,000', '3,472,000'],
           ['Night shifts  (8)', '331,000', '2,648,000'],
           ['Agency margin  18 %', '-', '1,101,600'],
           ['Out-of-hours surcharge', '-', '1,120,000'],
           ['Month total', '-', '8,341,600']]),
   dict(t='kv', k='Ratio to permanent post', v='2.0', mono=True),
   dict(t='kv', k='Eleven months at this rate', v='91.7 m', mono=True),
   dict(t='rule'),
   dict(t='sign', text='THE SURCHARGE LINE, IN FULL:'),
   dict(t='para', text='"Applied where the booking is made with less than 72 hours notice. '
     'All bookings in this period were made with less than 72 hours notice."')],
 callouts=[dict(at=0.20, text='Four advertisements, four applicants, nobody appointed'),
   dict(at=0.28, text='The right fit - and the notice says nothing a candidate would want'),
   dict(at=0.52, text='Nights cost a third more than days'),
   dict(at=0.58, text='Eighteen per cent to the agency, before the surcharge'),
   dict(at=0.64, text='The surcharge is a seventh of the bill, and it is avoidable'),
   dict(at=0.94, text='All of them. Every single booking, for eleven months')]),

"fig_b12_u03_p07_v10": dict(type='V10', kind='pitch', height=700,
 title='Two halves that do not match',
 sub='The tune is identical. The grammar is reversed. That is why these are harder to hear than '
     'to read.',
 alt='Three pitch contours of mixed conditionals, each rising on the if-clause and falling on the '
     'result, with the time of each half marked.',
 contours=[dict(text="If we'd advertised in March, | we'd have somebody by now.",
     points=[.1, .3, .6, .9, .5, .2, -.2, -.6], meaning='past condition, present result'),
   dict(text='If I were permanent, | I would have said something in March.',
     points=[.2, .5, .8, .4, .2, 0, -.3, -.7], meaning='present condition, past result'),
   dict(text="We'd advertised by then. | We'd have somebody now.",
     points=[.3, .1, -.3, 0, .4, .2, -.2, -.6],
     meaning="both are /wi:d/ - one is had, one is would")]),

"fig_b12_u03_p08_v02": dict(type='V2', height=800,
 title='The department, in section',
 sub='Four levels, and the post that is empty is the one that holds the other three up.',
 alt='A hospital department drawn in section showing the consultant office, the registrar room, '
     'the shop floor and the student room, with staffing levels on each.',
 floors=[dict(was='the consultant office', now='Three posts. Two filled, one vacant eleven months',
     year='', fill='#EFE2DD'),
   dict(was='the registrars', now='Six posts, six filled, and two of them acting up', year='',
     fill='#E4ECEF'),
   dict(was='the shop floor', now='Where the locum actually works, and where he is good',
     year='', fill='#E6EFE9'),
   dict(was='the student room', now='Four fifth-years. Supervision is the vacant post\'s job',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='One empty desk, and ninety-one million pesos of cover'),
   dict(at=0.38, text='Acting up means doing it without the title or the pay'),
   dict(at=0.62, text='Nobody disputes that he is good. That has never been the question'),
   dict(at=0.88, text='Nobody has supervised them properly since January')]),

"fig_b12_u03_p09_v05": dict(type='V5', height=1040,
 title='The same request, six ways',
 sub='Ranked by directness, and separately by how likely each one is to get a yes.',
 alt='Six versions of one request arranged from direct to indirect, with notes on which are '
     'easiest to refuse and which are easiest to miss.',
 rows=[dict(t='org', text='ONE REQUEST  -  SIX VERSIONS  -  "WILL YOU STAY?"'),
   dict(t='grid', cols=['VERSION', 'DIRECTNESS', 'EASY TO MISS?'],
     data=[['"Stay."', '6 / 6', 'no'],
           ['"Would you stay?"', '5 / 6', 'no'],
           ['"We\'d like you to stay."', '4 / 6', 'no'],
           ['"It would be a shame if you left."', '3 / 6', 'yes'],
           ['"I don\'t suppose you\'d consider staying?"', '2 / 6', 'yes'],
           ['"Have you thought about after Friday?"', '1 / 6', 'yes - very']]),
   dict(t='rule'),
   dict(t='head', text='WHAT HE SAID AFTERWARDS'),
   dict(t='para', text='"The third one. Not because it was polite - because somebody had '
     'decided something before they opened their mouth. The last one is not a request. It is a '
     'way of finding out whether you have to make one."'),
   dict(t='rule'),
   dict(t='head', text='THE TRADE'),
   dict(t='kv', k='More direct', v='harder to refuse, harder to miss', mono=False),
   dict(t='kv', k='Less direct', v='easier to refuse, easier to miss', mono=False),
   dict(t='para', text='Indirectness protects the person being asked. It also protects the '
     'person asking, which is usually the reason it is chosen.'),
   dict(t='rule'),
   dict(t='sign', text='WHAT WAS ACTUALLY SAID, IN OCTOBER:'),
   dict(t='para', text='"Nothing. Nobody said any of the six."')],
 callouts=[dict(at=0.17, text='Direct, and in this hospital it would be read as rude'),
   dict(at=0.26, text='The one he says he would have accepted'),
   dict(at=0.33, text='Polite, and still unmistakably a request'),
   dict(at=0.42, text='Not a request at all. A question about his plans'),
   dict(at=0.72, text='Indirectness protects the asker more than the asked'),
   dict(at=0.93, text='Three months, and none of the six was used')]),

"fig_b12_u03_p10_v12": dict(type='V12', height=880,
 title='Eleven months of a vacant post',
 sub='Half the class sees the vacancy history. Half sees the invoices. Rebuild it by speaking.',
 alt='An infographic of a vacant consultant post across eleven months showing advertisements, '
     'locum cover, cost and the conversation that was never had.',
 span=['Jan', 'Jan'], ticks=6,
 tick_labels=['Jan', 'Mar', 'Jun', 'Sep', 'Dec', 'Jan'],
 bands=[dict(name='The post', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.92}, label='vacant - advertised four times', colour='#A8372E'),
   dict(**{'from': 0.92, 'to': 1.0}, label='filled', colour='#2E6F5E')]),
  dict(name='Cover', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.58}, label='rota gaps, registrars acting up', colour='#C86B2B'),
   dict(**{'from': 0.58, 'to': 1.0}, label='agency locum at 2.0x', colour='#D9A441')]),
  dict(name='What was said', type='events', items=[
   dict(at=0.12, label='advertisement 1', colour='#9AA7AE'),
   dict(at=0.34, label='advertisement 2 - "the right fit"', colour='#9AA7AE'),
   dict(at=0.58, label='locum starts. Says nothing, deliberately', colour='#8C6A9E'),
   dict(at=0.86, label='asked, on the Wednesday. Yes in ninety seconds', colour='#2E6F5E'),
   dict(at=0.94, label='re-advertised ten days - rules are rules', colour='#1F4E5F')]),
  dict(name='Cost, millions of pesos', type='line',
   points=[(0, 0), (0.3, 9), (0.58, 22), (0.78, 58), (0.92, 88), (1.0, 92)], end_label='92 m'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.22, label='nobody put the rota in the advertisement'),
   dict(at=0.50, label='every booking made inside 72 hours - surcharge every time'),
   dict(at=0.72, label='he had been waiting to be asked since October'),
   dict(at=0.97, label='and the ten days cost four million more')])]),

"fig_b12_u03_p11_v06": dict(type='V6', kind='bar', height=800,
 title='Three options over twelve months',
 sub='Cost in millions of pesos, against the number of months the department runs short.',
 alt='A bar chart comparing cost and months short for renewing a locum, recruiting from scratch '
     'and appointing the locum directly.',
 labels=['renew locum', 'recruit', 'appoint him', 'do nothing'],
 ymin=0, ymax=110, fmt='{:,.0f}',
 series=[dict(name='cost, millions', values=[100, 62, 54, 100], colour='#1F4E5F'),
   dict(name='months short (x10)', values=[0, 30, 3, 0], colour='#A8372E')],
 note='Appointing him is the cheapest option and the one with the least time short. It has been '
      'available for three months and nobody has spoken a sentence out loud.',
 warning='Recruiting is cheaper than renewing and costs three months of a department running '
         'three doctors short in its busiest quarter, which is not a number this chart can hold.'),
}
