"""B1.2 Unit 5 - Four Per Cent - twelve figures, as data."""
FIGURES = {
"fig_b12_u05_p00_v01": dict(type='V1', height=840, storey_h=155,
 title='The planning corridor, and the ward that is not open',
 sub='Eleven things to find. Three of them are predictions, and two were due last year.',
 alt='A hospital corridor with beds in it, a capacity board, a waiting-list whiteboard, a '
     'three-year plan on a screen, a building hoarding and a sign for an unopened ward.',
 sky='#DEE4E6', ground='#A0A6A6', ground_line=680,
 buildings=[dict(x=20, w=480, storeys=3, colour='#D3CFC5', label='the planning office'),
   dict(x=560, w=420, storeys=2, colour='#C9C5BA', label='the corridor'),
   dict(x=1040, w=540, storeys=4, colour='#C0BCB2', label='the new wing, 2024')],
 props=[dict(kind='hoarding', x=1140, y=680, s=1.1),
   dict(kind='scaffold', x=1380, y=680, s=1.0),
   dict(kind='table', x=180, y=680, s=1.4), dict(kind='doc', x=180, y=610),
   dict(kind='box', x=640, y=680, s=1.1), dict(kind='box', x=720, y=680, s=1.1),
   dict(kind='crate', x=820, y=680, s=1.1),
   dict(kind='sign', x=120, y=680, s=.7, text='7,420'),
   dict(kind='sign', x=500, y=680, s=.7, text='4 %'),
   dict(kind='sign', x=1010, y=680, s=.7, text='Q2')],
 people=[dict(x=280, y=680, h=88, skin=1, cloth=2, hair='bun', arm='point'),
   dict(x=420, y=680, h=87, skin=0, cloth=4, hair='grey', arm='hold'),
   dict(x=700, y=680, h=88, skin=2, cloth=0, hair='short', arm='down'),
   dict(x=900, y=680, h=87, skin=4, cloth=3, hair='cap', arm='hold'),
   dict(x=1240, y=680, h=88, skin=3, cloth=1, hair='long', arm='folded')],
 names=[dict(x=280, t='the finance lead, six plans'), dict(x=420, t='Dr Herrera, who signs it'),
   dict(x=700, t='Matias, fourth draft'), dict(x=900, t='Ignacio, counting trolleys'),
   dict(x=1240, t='the ward that was due last year'), dict(x=120, t='the baseline, 31 March'),
   dict(x=500, t='what the model assumes')],
 markers=[dict(x=280, y=560), dict(x=420, y=560), dict(x=700, y=560), dict(x=900, y=560),
   dict(x=1240, y=560), dict(x=120, y=612), dict(x=500, y=612), dict(x=1010, y=612),
   dict(x=180, y=632), dict(x=640, y=628), dict(x=1140, y=600)]),

"fig_b12_u05_p01_v08": dict(type='V8', height=800,
 title='How a plan survives being wrong',
 sub='Six nodes. The loop at the bottom is the one nobody writes down.',
 alt='A network from a baseline through an assumption to a plan, its approval and the real '
     'demand, with the revision loop shown as a dashed path.',
 nodes={
  'bas': dict(x=170, y=400, short='1', name='The baseline', sub='7,420 at 31 March', colour='#1F4E5F'),
  'ass': dict(x=520, y=200, short='2', name='The assumption', sub='4 %, unreviewed since 2019', colour='#C86B2B'),
  'pln': dict(x=520, y=600, short='3', name='The plan', sub='three years, approvable', colour='#D9A441'),
  'app': dict(x=900, y=400, short='4', name='Approval', sub='April, no discussion', colour='#2E6F5E'),
  'rea': dict(x=1250, y=240, short='5', name='Real demand', sub='9.1, 8.8, 8.4', r=54, colour='#A8372E'),
  'gap': dict(x=1250, y=580, short='6', name='No record of the gap', sub='and that is the cost',
    r=54, colour='#9AA7AE')},
 edges=[dict(a='bas', b='ass', label='choose a number', sw=5),
   dict(a='ass', b='pln', label='the one that produces an approvable plan', sw=6),
   dict(a='pln', b='app', label='six weeks, then April', sw=6),
   dict(a='app', b='gap', label='three years of running on it', sw=6),
   dict(a='rea', b='gap', label='and nothing connects these two', sw=5, colour='#A8372E'),
   dict(a='pln', b='ass', label='returned for revision: four months', sw=3, dash='5 5'),
   dict(a='bas', b='rea', label='what actually happened, every year', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_b12_u05_p02_v07": dict(type='V7', height=820,
 title='The three-year model',
 sub='One of them has submitted this plan six times. One of them has just put nine in the cell.',
 alt='A finance lead and a student at a screen showing a three-year model, with speech bubbles '
     'using the future perfect and future continuous.',
 bg='#E8EBEC',
 set=[dict(kind='table', x=700, y=700, s=1.5), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=1, cloth=2, hair='bun', arm='point', facing='right',
   label='the finance lead', role='six plans', says=['By March we will have passed eleven '
     'thousand.', 'By March we will be running at ninety per cent.']),
  dict(x=980, h=248, skin=2, cloth=0, hair='short', arm='hold', facing='left',
   label='Matias', role='fifth year', says=['By the time the ward opens, the list will have '
     'doubled.'])]),

"fig_b12_u05_p03_v09": dict(type='V9', kind='timeline', height=740,
 title='Finished by then, or still going then',
 sub='Three future forms, one deadline, and they answer three different questions.',
 alt='A timeline with a future point marked, showing a completed action before it, an ongoing '
     'action across it and a duration running up to it.',
 now=0.14, axis_y=500,
 bands=[dict(type='before', lane=1, **{'from': 0.20, 'to': 0.62},
     label='WILL HAVE + pp - finished by then',
     example='By March we will have passed eleven thousand.'),
   dict(type='reach', lane=3, **{'from': 0.56}, label='WILL BE + -ing - going on then',
     example='By March we will be running at ninety per cent.'),
   dict(type='before', lane=5, **{'from': 0.14, 'to': 0.72},
     label='WILL HAVE BEEN + -ing - how long by then',
     example='By June we will have been working on it for two years.')],
 rule='By means at or before. Until means up to and not after, and they are not '
      'interchangeable. By the time takes a present tense, like every other time clause.'),

"fig_b12_u05_p03_v11": dict(type='V11', height=700,
 title='The deadline word, and the one that is not',
 alt='Two panels comparing by and until with a completed future action, showing where each one '
     'puts the finishing.',
 wrong=dict(sentence='We will have finished until March.',
            boundary=0.64, boundary_label='March',
            event=0.30, event_label='finishing, continuously, up to March',
            why='Until marks the end of a continuing situation. Finishing is not a continuing '
                'situation, so the sentence asks the reader to imagine an act of finishing that '
                'goes on for months and then stops.'),
 right=dict(sentence='We will have finished by March.',
            boundary=0.64, boundary_label='March',
            event=0.40, event_label='finished, at some point before March',
            why='By marks a deadline: at or before. The finishing happens once, at an unnamed '
                'point, and March is the latest it can be - which is exactly what a projection '
                'wants to say.'),
 misconception='Both words translate to one word in many languages, so learners choose by sound. '
               'In English one marks a deadline and the other marks the end of a duration, and '
               'only one of them works with a completed event.'),

"fig_b12_u05_p04_v04": dict(type='V4', height=740,
 title='The modelled world, and the actual one',
 sub='Learner A has the assumptions. Learner B has six years of actuals. They agreed until 2022.',
 alt='Two panels comparing a modelled growth curve and the actual recorded figures, diverging '
     'after the second year.',
 differences=7, prompt='In which year did the two stop agreeing?',
 left=dict(label='the model, 4 %', art=[
   dict(kind='block', x=140, y=70, w=60, bh=50, colour='#D9A441'),
   dict(kind='block', x=220, y=60, w=60, bh=60, colour='#D9A441'),
   dict(kind='block', x=300, y=50, w=60, bh=70, colour='#D9A441'),
   dict(kind='block', x=380, y=40, w=60, bh=80, colour='#D9A441'),
   dict(kind='label', x=300, y=210, text='8,350 by year three', colour='#D9A441')]),
 right=dict(label='the actuals, 9 %', art=[
   dict(kind='block', x=140, y=70, w=60, bh=50, colour='#A8372E'),
   dict(kind='block', x=220, y=40, w=60, bh=80, colour='#A8372E'),
   dict(kind='block', x=300, y=10, w=60, bh=110, colour='#A8372E'),
   dict(kind='block', x=380, y=-20, w=60, bh=140, colour='#A8372E'),
   dict(kind='label', x=300, y=210, text='9,610 by year three', colour='#A8372E')])),

"fig_b12_u05_p05_v05": dict(type='V5', height=1060,
 title='The three-year model, and the actual figures',
 sub='One cell carries a footnote. It is the only place the real number appears.',
 alt='A three-year planning model showing baseline, assumed growth and projected totals '
     'alongside the recorded actual growth rates for the same years.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  THREE-YEAR MODEL  -  WAITING LIST'),
   dict(t='kv', k='Baseline, 31 March', v='7,420', mono=True),
   dict(t='kv', k='Assumed annual growth', v='4.0 %  *', mono=True),
   dict(t='kv', k='Assumption last reviewed', v='2019', mono=True),
   dict(t='rule'),
   dict(t='head', text='THE PROJECTION'),
   dict(t='grid', cols=['YEAR', 'AT 4 %', 'AT 9 %'],
     data=[['Year 1', '7,717', '8,088'], ['Year 2', '8,026', '8,816'],
           ['Year 3', '8,347', '9,610'], ['Difference', '-', '+1,263']]),
   dict(t='rule'),
   dict(t='head', text='WHAT ACTUALLY HAPPENED'),
   dict(t='grid', cols=['YEAR', 'ACTUAL GROWTH', 'VARIANCE'],
     data=[['Two years ago', '9.1 %', '+5.1'], ['Last year', '8.8 %', '+4.8'],
           ['This year, to date', '8.4 %', '+4.4']]),
   dict(t='kv', k='Cumulative variance', v='+14.3 points', mono=True),
   dict(t='kv', k='New ward opens', v='Q2, year 2', mono=True),
   dict(t='kv', k='New ward capacity', v='600', mono=True),
   dict(t='rule'),
   dict(t='sign', text='FOOTNOTE * ON THE GROWTH CELL, IN FULL:'),
   dict(t='para', text='"4.0 % is the planning assumption agreed in 2019. Observed growth over '
     'the last three years has averaged 8.8 %."')],
 callouts=[dict(at=0.12, text='The only hard number in the document'),
   dict(at=0.16, text='A working assumption, six years old'),
   dict(at=0.44, text='Twelve hundred and sixty-three people, by year three'),
   dict(at=0.66, text='Three years, three variances, all in the same direction'),
   dict(at=0.78, text='Six hundred of capacity against a gap of twelve hundred'),
   dict(at=0.94, text='Twenty-six words, in six point, and nobody has ever quoted them')]),

"fig_b12_u05_p07_v10": dict(type='V10', kind='stress', height=720,
 title='Four weak forms in a row',
 sub='In we will have been running, four words carry no stress at all and one does.',
 alt='Five future-perfect phrases with the stressed syllables drawn as large dots, showing long '
     'chains of unstressed function words.',
 items=[dict(syllables=['we', 'will', 'have', 'PASSED', 'it'], strong=[3],
     note="we'll've - three words, one beat"),
   dict(syllables=['we', 'will', 'have', 'been', 'RUN', 'ning'], strong=[4],
     note='four weak forms, then the stress'),
   dict(syllables=['by', 'the', 'TIME', 'it', 'O', 'pens'], strong=[2, 4],
     note='the time clause carries two'),
   dict(syllables=['by', 'THEN', 'we', 'will', 'KNOW'], strong=[1, 4],
     note='a state verb, so no continuous'),
   dict(syllables=['we', 'WILL', 'have', 'passed', 'it'], strong=[1],
     note='full will - somebody has just doubted it')]),

"fig_b12_u05_p08_v02": dict(type='V2', height=800,
 title='The new wing, in section',
 sub='Four floors, and the one that was due last year is the one the plan depends on.',
 alt='A hospital wing drawn in section showing the plant room, two finished floors, the ward '
     'that has not opened and the corridor beneath it.',
 floors=[dict(was='the plant room', now='Finished 2023. Running, and costing, since then',
     year='2023', fill='#E6EFE9'),
   dict(was='floors 3 and 4', now='Handed over. Occupied since March', year='2024',
     fill='#E4ECEF'),
   dict(was='floor 2 - the new ward', now='600 beds of capacity. Due Q2 last year. Empty',
     year='due 2024', fill='#EFE2DD'),
   dict(was='the corridor', now='Where the trolleys are, and have been since January', year='',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Complete, and heating an empty floor'),
   dict(at=0.38, text='The only part of the project that met its date'),
   dict(at=0.62, text='Six hundred of the twelve hundred the model needs'),
   dict(at=0.88, text='And this is where the variance actually lives')]),

"fig_b12_u05_p09_v05": dict(type='V5', height=1040,
 title='Four rounds of comments on one proposal',
 sub='Twenty-nine comments. One of them changed the project, and it is in round two.',
 alt='A summary of supervisor feedback across four drafts, classified into four kinds of comment '
     'with counts for each round.',
 rows=[dict(t='org', text='PROJECT PROPOSAL  -  M. SOTO  -  FEEDBACK LOG'),
   dict(t='grid', cols=['ROUND', 'WRONG', 'UNCLEAR'],
     data=[['1', '9', '4'], ['2', '3', '5'], ['3', '1', '6'], ['4', '0', '2']]),
   dict(t='grid', cols=['ROUND', 'OFF-BRIEF', 'FINE, BUT'],
     data=[['1', '1', '0'], ['2', '1', '0'], ['3', '0', '2'], ['4', '0', '3']]),
   dict(t='para', text='Factual corrections fall away. Clarity comments rise and then fall. '
     'Off-brief comments appear twice, both times early, and the second one is the only comment '
     'in twenty-nine that changed what the project was about.'),
   dict(t='rule'),
   dict(t='head', text='THE COMMENT THAT CHANGED IT  (ROUND 2)'),
   dict(t='para', text='"Your question was about capacity and this is about money. Decide which '
     'one you are writing, because the data you need is different."'),
   dict(t='rule'),
   dict(t='head', text='THE COMMENT REPEATED IN ALL FOUR'),
   dict(t='para', text='"Put the assumption before the number it produces."'),
   dict(t='kv', k='Acted on in round', v='4', mono=True),
   dict(t='rule'),
   dict(t='sign', text='LAST LINE OF ROUND FOUR:'),
   dict(t='para', text='"This works. I would still put the assumption first, and I notice I '
     'have now said that four times."')],
 callouts=[dict(at=0.16, text='Nine factual errors in round one, none by round four'),
   dict(at=0.26, text='Clarity comments peak in round three, when the content is settled'),
   dict(at=0.44, text='Off-brief twice, both early - and left late it wastes everything after'),
   dict(at=0.60, text='Twenty-six words, and the whole project turned on them'),
   dict(at=0.78, text='Repeated four times, acted on once'),
   dict(at=0.94, text='And the supervisor is counting too')]),

"fig_b12_u05_p10_v12": dict(type='V12', height=880,
 title='Six years of a four per cent assumption',
 sub='Half the class sees the model. Half sees the actuals. Rebuild the divergence by speaking.',
 alt='An infographic of a planning assumption across six years showing modelled and actual '
     'demand, the ward that did not open, and the eleven words in a minute.',
 span=['2019', 'year 3'], ticks=6,
 tick_labels=['2019', '2022', 'last yr', 'this yr', 'yr 2', 'yr 3'],
 bands=[dict(name='The assumption', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='4.0 %, agreed 2019, never reviewed',
     colour='#D9A441')]),
  dict(name='The new ward', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.54}, label='under construction', colour='#9AA7AE'),
   dict(**{'from': 0.54, 'to': 0.86}, label='complete, empty', colour='#A8372E'),
   dict(**{'from': 0.86, 'to': 1.0}, label='open - 600 beds', colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.00, label='assumption agreed', colour='#1F4E5F'),
   dict(at=0.42, label='9.1 % - first year of divergence', colour='#A8372E'),
   dict(at=0.60, label='8.8 % - second year, same direction', colour='#A8372E'),
   dict(at=0.70, label='plan submitted at 4 %, annex minuted in eleven words',
     colour='#2E6F5E'),
   dict(at=0.98, label='regional review asks who identified the risk', colour='#8C6A9E')]),
  dict(name='Waiting list', type='line',
   points=[(0.3, 7420), (0.5, 8088), (0.65, 8816), (0.8, 9100), (0.92, 9400), (1.0, 9610)],
   end_label='9,610'),
  dict(name='The documents', type='flags', items=[
   dict(at=0.34, label='a footnote in six point'),
   dict(at=0.56, label='no document saying what is needed'),
   dict(at=0.74, label='eleven words in a minute'),
   dict(at=0.99, label='quoted in the review\'s final report')])]),

"fig_b12_u05_p11_v06": dict(type='V6', kind='line', height=800,
 title='Modelled demand, and actual demand',
 sub='The two lines separate in the second year and never come back.',
 alt='A line chart of projected waiting-list size at four per cent growth against the actual '
     'recorded figures, with the gap widening each year.',
 labels=['baseline', 'yr 1', 'yr 2', 'yr 3', 'yr 4', 'yr 5'],
 ymin=7000, ymax=11000, fmt='{:,.0f}',
 series=[dict(name='model at 4 %', values=[7420, 7717, 8026, 8347, 8681, 9028],
   colour='#D9A441'),
   dict(name='actual / at 9 %', values=[7420, 8088, 8816, 9610, 10475, 11418],
     colour='#A8372E')],
 note='The gap is 371 after one year, 790 after two and 1,263 after three. The new ward adds '
      'capacity for 600.',
 warning='The two lines are drawn from the same baseline and differ only in one cell of one '
         'spreadsheet, which has not been reviewed since 2019.'),
}
