"""B1.2 Unit 7 - Eleven Nights - twelve figures, as data."""
FIGURES = {
"fig_b12_u07_p00_v01": dict(type='V1', height=840, storey_h=155,
 title='The nursing station, 04.40',
 sub='Eleven things to find. Four hold attention and three break it.',
 alt='A hospital nursing station at night with a screen, a drug chart, a coffee machine, a '
     'handover sheet, an amended rota and a chair somebody has slept in.',
 sky='#333E45', ground='#4E555B', ground_line=680,
 buildings=[dict(x=20, w=540, storeys=2, colour='#525A60', label='the nursing station'),
   dict(x=620, w=380, storeys=2, colour='#4C545A', label='the bays'),
   dict(x=1060, w=520, storeys=3, colour='#474E54', label='the corridor, lights at half')],
 props=[dict(kind='table', x=200, y=680, s=1.5), dict(kind='doc', x=200, y=608),
   dict(kind='doc', x=300, y=614),
   dict(kind='box', x=680, y=680, s=1.1), dict(kind='crate', x=780, y=680, s=1.1),
   dict(kind='table', x=1150, y=680, s=1.2),
   dict(kind='sign', x=120, y=680, s=.7, text='04:40'),
   dict(kind='sign', x=580, y=680, s=.7, text='N11'),
   dict(kind='sign', x=1500, y=680, s=.7, text='N12')],
 people=[dict(x=330, y=680, h=88, skin=1, cloth=2, hair='long', arm='hold'),
   dict(x=520, y=680, h=87, skin=3, cloth=0, hair='bun', arm='down'),
   dict(x=880, y=680, h=88, skin=4, cloth=3, hair='cap', arm='hold'),
   dict(x=1230, y=680, h=87, skin=0, cloth=4, hair='grey', arm='point')],
 names=[dict(x=330, t='Carla, night eleven'), dict(x=520, t='the colleague who said something'),
   dict(x=880, t='Ignacio, on his third'), dict(x=1230, t='Dr Herrera, reading the rota'),
   dict(x=120, t='the clock nobody looks at'), dict(x=580, t='which night this is'),
   dict(x=1500, t='what is on the rota tomorrow')],
 markers=[dict(x=330, y=560), dict(x=520, y=560), dict(x=880, y=560), dict(x=1230, y=560),
   dict(x=120, y=612), dict(x=580, y=612), dict(x=1500, y=612), dict(x=200, y=632),
   dict(x=300, y=636), dict(x=680, y=628), dict(x=1150, y=630)]),

"fig_b12_u07_p01_v08": dict(type='V8', height=800,
 title='Why a habit holds',
 sub='Six nodes. Five of them are in the situation and one is in the person.',
 alt='A network of habit maintenance from a trigger through the act, the reward and the '
     'substitute, with willpower shown as a small and poorly connected node.',
 nodes={
  'tri': dict(x=170, y=400, short='1', name='The trigger', sub='a situation, not a craving', colour='#C86B2B'),
  'act': dict(x=520, y=200, short='2', name='The act', sub='eleven times a day', colour='#1F4E5F'),
  'rew': dict(x=520, y=600, short='3', name='The reward', sub='and it is rarely the obvious one', colour='#D9A441'),
  'sub': dict(x=900, y=400, short='4', name='The substitute', sub='same trigger, different act', colour='#2E6F5E'),
  'wil': dict(x=1260, y=230, short='5', name='Willpower', sub='explains nothing afterwards', r=50, colour='#9AA7AE'),
  'rel': dict(x=1260, y=580, short='6', name='Relapse', sub='or a slip. Nobody agrees', r=54,
    colour='#A8372E')},
 edges=[dict(a='tri', b='act', label='without noticing', sw=6),
   dict(a='act', b='rew', label='going outside, not the cigarette', sw=6),
   dict(a='rew', b='tri', label='and it strengthens the trigger', sw=5),
   dict(a='tri', b='sub', label='keep the trigger, change the act', sw=6),
   dict(a='sub', b='rel', label='holds for about seven weeks', sw=4, dash='5 5'),
   dict(a='wil', b='rel', label='the explanation people reach for', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_b12_u07_p02_v07": dict(type='V7', height=820,
 title='Eleven nights',
 sub='One of them has not slept properly in a fortnight. One of them signs the rota.',
 alt='A night nurse and a consultant at a nursing station, with speech bubbles contrasting stop '
     'plus -ing and stop plus to.',
 bg='#3A4349',
 set=[dict(kind='table', x=700, y=700, s=1.5), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=1, cloth=2, hair='long', arm='hold', facing='right',
   label='Carla', role='night eleven', says=['I stopped to think about it.',
     'I stopped thinking about it.']),
  dict(x=980, h=248, skin=0, cloth=4, hair='grey', arm='point', facing='left',
   label='Dr Herrera', role='signs the rota', says=['I remember checking it.',
     'I remembered to check it.'])]),

"fig_b12_u07_p03_v09": dict(type='V9', kind='mirror', height=680,
 title='Backwards, and forwards',
 sub='The -ing form points at something already real. The to form points at a purpose.',
 alt='Two parallel sentences compared, one with stop plus -ing ending an activity and one with '
     'stop plus to naming a purpose.',
 active=dict(parts=[dict(w=0.8, role='agent', text='I'),
   dict(w=1.2, role='action', text='stopped'),
   dict(w=1.8, role='affected', text='THINKING - the activity ended')]),
 passive=dict(parts=[dict(w=0.8, role='agent', text='I'),
   dict(w=1.2, role='action', text='stopped'),
   dict(w=1.8, role='hidden', text='TO THINK - I paused, in order to')]),
 rule='The pattern covers stop, remember, forget, go on and regret well, try and mean '
      'adequately, and need not at all. The eight verbs have to be learned.'),

"fig_b12_u07_p03_v11": dict(type='V11', height=700,
 title='The two sentences a nursing note can contain',
 alt='Two panels comparing I did not remember to check and I do not remember checking, showing '
     'what each one claims about the past.',
 wrong=dict(sentence='I did not remember to check the chart.',
            boundary=0.50, boundary_label='the duty',
            event=0.80, event_label='and it was not discharged',
            why='This says the duty existed and was not carried out. It is a statement that the '
                'check did not happen, and in a note it is a confession of an omission - which '
                'may be true, and which she does not actually know.'),
 right=dict(sentence='I do not remember checking the chart.',
            boundary=0.50, boundary_label='the memory',
            event=0.22, event_label='the check may or may not have happened',
            why='This says only that the memory is absent. It leaves the fact open, which is '
                'where it honestly stands, and it is the sentence that sends an investigator to '
                'the chart rather than to the nurse.'),
 misconception='The two forms look like stylistic variants of one idea. One is about an act and '
               'the other is about a memory, and in a record the difference decides who gets '
               'investigated.'),

"fig_b12_u07_p04_v04": dict(type='V4', height=740,
 title='Her account, and the rota',
 sub='Learner A has Carla\'s account. Learner B has the rota and the incident log.',
 alt='Two panels compared: a spoken account of eleven nights and a printed rota with hand '
     'amendments and an incident log.',
 differences=7, prompt='On which night do the two accounts separate?',
 left=dict(label='her account', art=[
   dict(kind='person', x=250, y=0, h=130, skin=1, cloth=2),
   dict(kind='label', x=300, y=130, text='"around night six"', colour='#C86B2B'),
   dict(kind='label', x=300, y=210, text='no night on which she decided', colour='#C86B2B')]),
 right=dict(label='the rota', art=[
   dict(kind='doc', x=200, y=0),
   dict(kind='block', x=360, y=20, w=90, bh=70, colour='#A8372E'),
   dict(kind='label', x=300, y=210, text='four approved, seven added by hand',
        colour='#A8372E')])),

"fig_b12_u07_p05_v05": dict(type='V5', height=1060,
 title='The rota policy, and the rota',
 sub='A printed policy, a printed rota, and a clause added to the rota in biro.',
 alt='A hospital night rota policy showing consecutive-shift limits, approval requirements and '
     'rest periods, alongside the actual rota with handwritten amendments.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  NIGHT ROTA POLICY  -  HR-11'),
   dict(t='kv', k='Maximum consecutive nights', v='12', mono=True),
   dict(t='kv', k='Recommended maximum', v='7', mono=False),
   dict(t='kv', k='Minimum rest after a run', v='48 h', mono=True),
   dict(t='para', text='Voluntary additional nights above seven require the approval of the '
     'department lead. Approval may be given retrospectively. Nothing in this policy requires '
     'the department lead to be told in advance.'),
   dict(t='rule'),
   dict(t='head', text='THE ACTUAL ROTA'),
   dict(t='grid', cols=['NIGHTS', 'HOW ADDED', 'APPROVED'],
     data=[['1 - 4', 'printed rota', 'yes'],
           ['5 - 6', 'cover for absence', 'retrospectively'],
           ['7 - 9', 'added by hand', 'retrospectively'],
           ['10 - 11', 'added by hand', 'not recorded'],
           ['12', 'on the printed rota', 'yes']]),
   dict(t='kv', k='Rest taken between nights', v='9 h 20 avg', mono=True),
   dict(t='kv', k='Night rate premium', v='+33 %', mono=True),
   dict(t='rule'),
   dict(t='sign', text='ADDED TO THE ROTA IN BIRO, BESIDE NIGHT 8:'),
   dict(t='para', text='"C says she is fine. - asked 02.40"')],
 callouts=[dict(at=0.10, text='Twelve permitted, seven recommended, and nobody reads the second'),
   dict(at=0.22, text='Approval may be retrospective, which makes it a record and not a check'),
   dict(at=0.48, text='Four of the eleven were ever on a printed rota'),
   dict(at=0.56, text='Two nights with no approval recorded at all'),
   dict(at=0.72, text='Nine hours twenty between nights, including the journey'),
   dict(at=0.93, text='Somebody did ask, at twenty to three, and wrote it down')]),

"fig_b12_u07_p07_v10": dict(type='V10', kind='stress', height=720,
 title='Stress as the disambiguator',
 sub='Two letters in writing. In speech it is mostly rhythm that tells the two apart.',
 alt='Five sentence pairs with the stressed syllables drawn as large dots, distinguishing gerund '
     'and infinitive readings.',
 items=[dict(syllables=['I', 'stopped', 'THINK', 'ing'], strong=[2],
     note='the thinking ended'),
   dict(syllables=['I', 'STOPPED', 'to', 'think'], strong=[1],
     note='I paused, in order to'),
   dict(syllables=['I', 're', 'mem', 'ber', 'CHECK', 'ing'], strong=[4],
     note='the memory of doing it'),
   dict(syllables=['I', 're', 'MEM', 'bered', 'to', 'check'], strong=[2],
     note='the duty, then the act'),
   dict(syllables=['he', 'went', 'ON', 'to', 'SAY'], strong=[2, 4],
     note='a new thing, not the same one')]),

"fig_b12_u07_p08_v02": dict(type='V2', height=800,
 title='Eleven nights, in section',
 sub='Four stages, and the one that matters is the one with no decision in it.',
 alt='A diagram of eleven consecutive night shifts drawn as four stages, from a planned block '
     'through covering absence to a run with no decision point.',
 floors=[dict(was='nights 1-4', now='The printed rota. A block, planned, normal', year='',
     fill='#E6EFE9'),
   dict(was='nights 5-6', now='Cover for absence. A decision, and a reason', year='',
     fill='#E4ECEF'),
   dict(was='nights 7-9', now='Added by hand. "Around six I stopped thinking about it"', year='',
     fill='#EFE2DD'),
   dict(was='nights 10-11', now='No approval recorded. No decision on any night', year='',
     fill='#F0E2E0')],
 callouts=[dict(at=0.12, text='Nobody would describe this as a problem'),
   dict(at=0.38, text='The last point at which anybody chose anything'),
   dict(at=0.62, text='Not stopped caring. Stopped thinking'),
   dict(at=0.88, text='Nothing happened, and that is the thing that worries her')]),

"fig_b12_u07_p09_v05": dict(type='V5', height=1040,
 title='The process note',
 sub='Not an incident report, not a complaint, not a confession, and that is three things it is '
     'easier to write.',
 alt='A hospital process note template and a completed example about a system permitting '
     'eleven consecutive nights, with the contested sentence marked.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  PROCESS NOTE  -  PN-3'),
   dict(t='head', text='WHAT THIS FORM IS FOR'),
   dict(t='grid', cols=['IT IS', 'IT IS NOT', ''],
     data=[['a record that a system allowed something', 'an incident report', ''],
           ['a prompt to look at a rule', 'a complaint about a person', ''],
           ['readable by anybody', 'a confession', ''],
           ['filed whether or not harm occurred', 'evidence in a disciplinary', '']]),
   dict(t='para', text='Process notes are reviewed quarterly by the governance committee. They '
     'are not linked to an individual\'s record and are not disclosable in a disciplinary '
     'process. Four were filed last year.'),
   dict(t='rule'),
   dict(t='head', text='THE CONTESTED SENTENCE'),
   dict(t='para', text='"I do not remember checking the chart after four and I believe I did."'),
   dict(t='grid', cols=['VERSION', 'READS AS', ''],
     data=[['"I failed to check after four."', 'a confession', ''],
           ['"The chart was checked."', 'a defence', ''],
           ['"No second check is recorded."', 'a system observation', ''],
           ['"I do not remember, and I believe I did."', 'what she will sign', '']]),
   dict(t='rule'),
   dict(t='sign', text='WHAT WAS AGREED:'),
   dict(t='para', text='"Keep her sentence. Add one line: the rota permitted eleven '
     'consecutive nights and seven of them were added by hand."')],
 callouts=[dict(at=0.17, text='Four things it is, and four it is not, printed side by side'),
   dict(at=0.40, text='Not disclosable - which is the only reason anybody writes one'),
   dict(at=0.46, text='Four filed last year, in a hospital of two thousand staff'),
   dict(at=0.60, text='The sentence she wanted to leave out'),
   dict(at=0.80, text='Four versions, and only one of them is true and signable'),
   dict(at=0.94, text='Her sentence kept, and one line about the rota added beneath it')]),

"fig_b12_u07_p10_v12": dict(type='V12', height=880,
 title='Eleven nights, and the year after',
 sub='Half the class sees the rota. Half sees her account. Rebuild it by speaking.',
 alt='An infographic of eleven consecutive night shifts and the policy change that followed, '
     'showing approvals, rest, income and incidents.',
 span=['night 1', 'a year on'], ticks=6,
 tick_labels=['n1', 'n6', 'n11', 'the note', 'the cap', '+1 yr'],
 bands=[dict(name='The nights', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.18}, label='printed rota, approved', colour='#2E6F5E'),
   dict(**{'from': 0.18, 'to': 0.32}, label='cover for absence', colour='#D9A441'),
   dict(**{'from': 0.32, 'to': 0.50}, label='added by hand, approved retrospectively',
     colour='#C86B2B'),
   dict(**{'from': 0.50, 'to': 0.58}, label='no approval recorded', colour='#A8372E')]),
  dict(name='What was said', type='events', items=[
   dict(at=0.30, label='"around six I stopped thinking about it"', colour='#8C6A9E'),
   dict(at=0.44, label='"are you all right?" - 02.40, written on the rota', colour='#1F4E5F'),
   dict(at=0.56, label='"I do not remember checking it after four"', colour='#A8372E'),
   dict(at=0.70, label='process note filed - the fifth in two years', colour='#2E6F5E'),
   dict(at=0.84, label='cap agreed at nine, not seven', colour='#D9A441')]),
  dict(name='Hours of rest between nights', type='line',
   points=[(0, 11.5), (0.2, 10.4), (0.4, 9.6), (0.56, 8.8), (0.8, 11.0), (1.0, 11.5)],
   end_label='11.5'),
  dict(name='What it cost', type='flags', items=[
   dict(at=0.26, label='night rate: a third more'),
   dict(at=0.62, label='nothing happened, so there would have been no record'),
   dict(at=0.88, label='her income down eleven per cent'),
   dict(at=0.98, label='incidents nine to four, and nobody can say why')])]),

"fig_b12_u07_p11_v06": dict(type='V6', kind='line', height=800,
 title='Error rate by consecutive night',
 sub='The published literature, and this hospital\'s own figures, on the same axes.',
 alt='A line chart of error rate against number of consecutive night shifts, rising sharply '
     'after the seventh night in both the literature and local data.',
 labels=['n1-2', 'n3-4', 'n5-6', 'n7-8', 'n9-10', 'n11-12'],
 ymin=0, ymax=4, fmt='{:,.1f}',
 series=[dict(name='published literature', values=[1.0, 1.1, 1.3, 1.9, 2.6, 3.4],
   colour='#1F4E5F'),
   dict(name='this hospital', values=[1.0, 1.0, 1.2, 1.7, 2.9, 3.1], colour='#A8372E')],
 note='Both curves bend after the sixth night, which is also the night Carla says she stopped '
      'thinking about it. The local numbers are small and the shape is the same.',
 warning='The policy permits twelve. The recommendation is seven. The curve bends between them, '
         'and the recommendation is the sentence nobody reads.'),
}
