"""B1.2 Unit 8 - Which Patients, Exactly - twelve figures, as data."""
FIGURES = {
"fig_b12_u08_p00_v01": dict(type='V1', height=840, storey_h=155,
 title='The information floor, the fifth working day',
 sub='Eleven things to find. Four of them are counting the same people differently.',
 alt='A hospital administration floor with a dashboard screen, a bed state board, a monthly '
     'return, a coding manual, a printout taped to a wall and a sticky note correcting a number.',
 sky='#E0E5E6', ground='#A2A7A7', ground_line=680,
 buildings=[dict(x=20, w=500, storeys=3, colour='#D3CFC5', label='finance'),
   dict(x=580, w=420, storeys=2, colour='#CAC6BB', label='clinical coding'),
   dict(x=1060, w=520, storeys=3, colour='#C1BDB3', label='the wards, two floors up')],
 props=[dict(kind='table', x=180, y=680, s=1.5), dict(kind='doc', x=180, y=608),
   dict(kind='table', x=680, y=680, s=1.4), dict(kind='doc', x=680, y=612),
   dict(kind='hoarding', x=1150, y=680, s=.95),
   dict(kind='sign', x=120, y=680, s=.7, text='1,740'),
   dict(kind='sign', x=560, y=680, s=.7, text='1,340'),
   dict(kind='sign', x=1030, y=680, s=.7, text='41 d'),
   dict(kind='sign', x=1520, y=680, s=.7, text='58 d')],
 people=[dict(x=280, y=680, h=88, skin=1, cloth=2, hair='bun', arm='hold'),
   dict(x=430, y=680, h=87, skin=2, cloth=0, hair='short', arm='point'),
   dict(x=760, y=680, h=88, skin=3, cloth=1, hair='long', arm='down'),
   dict(x=900, y=680, h=87, skin=0, cloth=4, hair='grey', arm='hold'),
   dict(x=1280, y=680, h=88, skin=4, cloth=3, hair='cap', arm='folded')],
 names=[dict(x=280, t='finance - a bed number'), dict(x=430, t='Matias, reading the manual'),
   dict(x=760, t='coding - an overnight stay'), dict(x=900, t='the information manager, 2011'),
   dict(x=1280, t='the ward, counting by hand'), dict(x=120, t="finance's admissions"),
   dict(x=560, t="coding's admissions")],
 markers=[dict(x=280, y=560), dict(x=430, y=560), dict(x=760, y=560), dict(x=900, y=560),
   dict(x=1280, y=560), dict(x=120, y=612), dict(x=560, y=612), dict(x=1030, y=612),
   dict(x=1520, y=612), dict(x=180, y=632), dict(x=680, y=634)]),

"fig_b12_u08_p01_v08": dict(type='V8', height=800,
 title='One phrase, four populations',
 sub='Six nodes. The four hundred people in the middle are in two of them and not the others.',
 alt='A network from one phrase in a report into four departmental populations, with the '
     'disputed group of day cases shown at the centre.',
 nodes={
  'phr': dict(x=170, y=400, short='1', name='"the patients"', sub='no definition given', colour='#1F4E5F'),
  'fin': dict(x=520, y=180, short='2', name='Finance', sub='a bed number: 1,740', colour='#C86B2B'),
  'cod': dict(x=520, y=620, short='3', name='Coding', sub='an overnight stay: 1,340', colour='#2E6F5E'),
  'war': dict(x=900, y=180, short='4', name='The ward', sub='who was on the board: 1,610', colour='#D9A441'),
  'reg': dict(x=900, y=620, short='5', name='Regional', sub='whatever was sent: 1,340', colour='#8C6A9E'),
  'day': dict(x=1270, y=400, short='6', name='400 day cases', sub='in two, out of two', r=56,
    colour='#A8372E')},
 edges=[dict(a='phr', b='fin', label='for the purposes of the tariff', sw=6),
   dict(a='phr', b='cod', label='the national coding standard', sw=6),
   dict(a='phr', b='war', label='nobody asked the ward', sw=4, dash='5 5'),
   dict(a='cod', b='reg', label='sent on, unlabelled', sw=5),
   dict(a='fin', b='day', label='in', sw=6),
   dict(a='cod', b='day', label='out', sw=6, colour='#A8372E'),
   dict(a='war', b='day', label='in, informally', sw=3, dash='5 5')]),

"fig_b12_u08_p02_v07": dict(type='V7', height=820,
 title='The patients',
 sub='Both of them have the right number. They do not have the same number.',
 alt='A finance analyst and a clinical coder at adjacent desks, with speech bubbles showing four '
     'different generic and specific uses of articles.',
 bg='#E8EBEC',
 set=[dict(kind='table', x=700, y=700, s=1.5), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=1, cloth=2, hair='bun', arm='hold', facing='right',
   label='finance', role='a bed number', says=['The patients waited 41 days.',
     'Patients wait too long.']),
  dict(x=980, h=248, skin=3, cloth=1, hair='long', arm='point', facing='left',
   label='clinical coding', role='an overnight stay', says=['A patient waits 41 days.',
     'Which patients, exactly?'])]),

"fig_b12_u08_p03_v09": dict(type='V9', kind='scope', height=600,
 title='Four ways of saying everybody, and one of them is not',
 sub='The fourth is never generic. It always means those ones, and the reader has to know which.',
 alt='Four versions of one sentence with brackets marking the article in each and what it points '
     'at.',
 words=['Patients', '/', 'A', 'patient', '/', 'The', 'patient', '/', 'The patients'],
 focus=[0, 2, 5, 8],
 brackets=[dict(**{'from': 0, 'to': 0}, lane=0, label='all of them, as a class', colour='#2E6F5E'),
   dict(**{'from': 2, 'to': 3}, lane=0, label='any one, as a type', colour='#1F4E5F'),
   dict(**{'from': 5, 'to': 6}, lane=1, label='the category, formal', colour='#8C6A9E'),
   dict(**{'from': 8, 'to': 8}, lane=1, label='THOSE ones - never generic', colour='#A8372E')]),

"fig_b12_u08_p03_v11": dict(type='V11', height=700,
 title='The sentence that produces four reports',
 alt='Two panels comparing a sentence with an undefined definite plural and the same sentence '
     'with the population named.',
 wrong=dict(sentence='The patients waited an average of 41 days.',
            boundary=0.50, boundary_label='the reader',
            event=0.80, event_label='supplies their own population',
            why='The definite plural points at a group the reader is assumed to know. If the '
                'report has not named one, every reader supplies the group they work with, and '
                'all of them are reading in good faith.'),
 right=dict(sentence='The 1,740 patients admitted under the finance definition waited 41 days.',
            boundary=0.50, boundary_label='the report',
            event=0.22, event_label='supplies the population',
            why='The population is named and counted in the sentence that carries the figure. '
                'A reader can now tell whether their own patients are in it, which is the only '
                'thing that makes the number usable.'),
 misconception='The definite article feels like precision, so writers reach for it when they '
               'want to sound exact. It is precise only if the reader already knows which ones, '
               'and in a report they usually do not.'),

"fig_b12_u08_p04_v04": dict(type='V4', height=740,
 title="Finance's four hundred, and coding's",
 sub='Learner A has one definition. Learner B has the other. Four hundred people are in dispute.',
 alt='Two panels compared: two overlapping populations of patients, one including day cases and '
     'one excluding them.',
 differences=6, prompt='Who are the four hundred, and which list are they on?',
 left=dict(label='finance: a bed number', art=[
   dict(kind='block', x=140, y=0, w=200, bh=90, colour='#C86B2B'),
   dict(kind='block', x=350, y=20, w=90, bh=70, colour='#A8372E'),
   dict(kind='label', x=300, y=210, text='1,740 - overnight plus day cases',
        colour='#C86B2B')]),
 right=dict(label='coding: an overnight stay', art=[
   dict(kind='block', x=140, y=0, w=200, bh=90, colour='#2E6F5E'),
   dict(kind='gap', x=350, y=20, w=90, bh=70),
   dict(kind='label', x=300, y=210, text='1,340 - overnight only', colour='#2E6F5E')])),

"fig_b12_u08_p05_v05": dict(type='V5', height=1060,
 title='The report page, and the four departmental figures',
 sub='One sentence, no definition, and four numbers that are all correct.',
 alt='A hospital report page with a headline waiting-time figure and the four different '
     'departmental figures for the same month, with the sources of each.',
 rows=[dict(t='org', text='HOSPITAL REGIONAL  -  QUARTERLY REPORT  -  PAGE 11'),
   dict(t='head', text='THE SENTENCE'),
   dict(t='para', text='"The patients waited an average of 41 days from referral to first '
     'appointment."'),
   dict(t='kv', k='Definition given on this page', v='none', mono=False),
   dict(t='kv', k='Definition given anywhere in the report', v='none', mono=False),
   dict(t='rule'),
   dict(t='head', text='THE SAME MONTH, FOUR WAYS'),
   dict(t='grid', cols=['SOURCE', 'POPULATION', 'DAYS'],
     data=[['Finance', '1,740 - any bed number', '41'],
           ['Clinical coding', '1,340 - overnight only', '47'],
           ['The ward', '1,610 - on the board at 08.00', '38'],
           ['Regional return', '1,340 - as sent', '58']]),
   dict(t='para', text='The regional figure is higher because it counts from referral received '
     'rather than referral dated, which adds about eleven days and is documented in the regional '
     'guidance and nowhere here.'),
   dict(t='kv', k='Range', v='38 to 58 days', mono=True),
   dict(t='kv', k='Used in the headline', v='finance', mono=False),
   dict(t='rule'),
   dict(t='sign', text='STICKY NOTE ON THE PAGE, IN THE INFORMATION MANAGER\'S HAND:'),
   dict(t='para', text='"Which patients? - asked 2011, 2016, 2019, and now."')],
 callouts=[dict(at=0.12, text='The definite plural, and no antecedent anywhere'),
   dict(at=0.20, text='No definition on the page, or in the document'),
   dict(at=0.40, text='Four hundred people and six days between the first two rows'),
   dict(at=0.52, text='The ward counts at eight in the morning, which nobody else does'),
   dict(at=0.72, text='Eleven days, documented in a guidance nobody here has read'),
   dict(at=0.94, text='Four times in thirteen years, by the same person')]),

"fig_b12_u08_p07_v10": dict(type='V10', kind='elision', height=700,
 title='Two words, four sounds',
 sub='The and a each have a weak form, a strong form, and a stressed form that means something '
     'else.',
 alt='Five phrases showing the as a schwa, the as /i:/, stressed THE, a as a schwa and stressed '
     'A.',
 pairs=[dict(written='the patients', spoken='ðə ˈpeɪʃnts', dropped='',
     note='before a consonant: /ðə/'),
   dict(written='the only ones', spoken='ðiː ˈəʊnli wʌnz', dropped='',
     note='before a vowel sound: /ðiː/'),
   dict(written='THE definition', spoken='ðiː defɪˈnɪʃn', dropped='',
     note='stressed: and there is no other'),
   dict(written='a patient', spoken='ə ˈpeɪʃnt', dropped='', note='unstressed: /ə/'),
   dict(written='A patient, not two', spoken='eɪ ˈpeɪʃnt', dropped='',
     note='stressed: /eɪ/, and now it is a number')]),

"fig_b12_u08_p08_v02": dict(type='V2', height=800,
 title='One month of admissions, in section',
 sub='Four layers, and the dispute lives entirely in the second one.',
 alt='A diagram of one month of hospital admissions drawn in layers, from overnight stays '
     'through day cases to emergency attendances, with which definition includes each.',
 floors=[dict(was='overnight stays', now='1,340. In every definition. Nobody disputes these',
     year='', fill='#E6EFE9'),
   dict(was='day cases', now='400. A bed number, no night. In finance, out in coding', year='',
     fill='#EFE2DD'),
   dict(was='emergency, bed number', now='270. In finance. Out everywhere else', year='',
     fill='#F0E2E0'),
   dict(was='emergency, no bed', now='900. Out of all four, and nobody argues about them',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='The agreed core, and the only number four departments share'),
   dict(at=0.38, text='Four hundred people, thirteen years, two correct positions'),
   dict(at=0.62, text='Two hundred and seventy, and only finance has ever counted them'),
   dict(at=0.88, text='Nine hundred, excluded by everybody, and never mentioned')]),

"fig_b12_u08_p09_v05": dict(type='V5', height=1040,
 title='What the question is actually asking',
 sub='Six task words, six scope words, and thirty-six different questions.',
 alt='A decode sheet for exam questions showing task words ranked by how much judgement they '
     'require and scope words that set how much must be covered.',
 rows=[dict(t='org', text='EXAM DECODE  -  TASK WORDS AND SCOPE WORDS'),
   dict(t='head', text='THE TASK WORD'),
   dict(t='grid', cols=['WORD', 'ASKS FOR', 'YOUR JUDGEMENT?'],
     data=[['Outline', 'the shape, briefly', 'none'],
           ['Describe', 'what it is', 'none'],
           ['Explain', 'why or how', 'a little'],
           ['Compare', 'similarities AND differences', 'some'],
           ['Justify', 'reasons for a stated position', 'a lot'],
           ['Evaluate', 'the case both ways, then a verdict', 'all of it']]),
   dict(t='para', text='Describe and explain are treated as synonyms in about a third of all '
     'answers. They are not: one asks what, the other asks why, and an answer to the wrong one '
     'can be complete and score nothing.'),
   dict(t='rule'),
   dict(t='head', text='THE SCOPE WORD'),
   dict(t='grid', cols=['PHRASE', 'ASKS FOR', ''],
     data=[['the causes', 'all of them, or you must say why not', ''],
           ['a cause', 'one, chosen and defended', ''],
           ['the main causes', 'a ranking, and a reason for the ranking', ''],
           ['any two causes', 'two, and the choice is not assessed', '']]),
   dict(t='rule'),
   dict(t='sign', text='WHAT THE THIRD STUDENT NOTICED:'),
   dict(t='para', text='"It says evaluate, and there is no conclusion anywhere in my answer."')],
 callouts=[dict(at=0.17, text='Two words that ask for nothing of your own'),
   dict(at=0.28, text='Compare means both, and most answers give one'),
   dict(at=0.34, text='Evaluate needs a verdict, and the verdict is the marks'),
   dict(at=0.46, text='A third of answers treat these two as the same word'),
   dict(at=0.70, text='The definite article again, and here it means all of them'),
   dict(at=0.94, text='And this is the commonest way to lose a whole question')]),

"fig_b12_u08_p10_v12": dict(type='V12', height=880,
 title='Thirteen years of two definitions',
 sub='Half the class sees the 2011 minutes. Half sees the current report. Rebuild it by speaking.',
 alt='An infographic from 2011 to the present showing two admission definitions, the systems '
     'that used each, and the four occasions the question was asked.',
 span=['2011', 'now'], ticks=6,
 tick_labels=['2011', '2016', '2019', '2022', 'the report', 'now'],
 bands=[dict(name='Finance', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='a bed number - day cases in', colour='#C86B2B')]),
  dict(name='Clinical coding', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='overnight stay - national standard', colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.00, label='both positions agreed to be correct', colour='#1F4E5F'),
   dict(at=0.04, label='action: circulate both definitions', colour='#D9A441'),
   dict(at=0.08, label='note written. Nobody would own it', colour='#A8372E'),
   dict(at=0.52, label='single reporting system - uses finance, does not say so',
     colour='#8C6A9E'),
   dict(at=0.86, label='definition published, prior year restated', colour='#2E6F5E')]),
  dict(name='Times the question was asked', type='line',
   points=[(0.0, 1), (0.36, 2), (0.52, 3), (0.86, 4), (1.0, 4)], end_label='4'),
  dict(name='What it cost', type='flags', items=[
   dict(at=0.20, label='four hundred people, in two figures and out of two'),
   dict(at=0.60, label='a system that chose silently'),
   dict(at=0.90, label='this year 41 to 47, last year 39 to 46'),
   dict(at=0.99, label='and somebody now asks in half the meetings')])]),

"fig_b12_u08_p11_v06": dict(type='V6', kind='bar', height=800,
 title='The same month, four definitions',
 sub='Population counted, and average wait produced, by each of the four departments.',
 alt='A bar chart of four departmental populations and the average waiting time each produces '
     'for the same month.',
 labels=['the ward', 'finance', 'coding', 'regional'],
 ymin=0, ymax=2000, fmt='{:,.0f}',
 series=[dict(name='patients counted', values=[1610, 1740, 1340, 1340], colour='#1F4E5F'),
   dict(name='average days (x30)', values=[1140, 1230, 1410, 1740], colour='#A8372E')],
 note='The biggest population produces the second-shortest wait, and the smallest produces the '
      'longest. None of the four is wrong.',
 warning='The regional figure uses the same population as coding and a different start date. '
         'That difference is eleven days and is documented in a guidance nobody in this '
         'hospital has read.'),
}
