# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C14-1': ('case item C14-1', []),
    'C14-2': ('case item C14-2', []),
    'C14-3': ('case item C14-3', []),
    'C14-4': ('case item C14-4', []),
    'C14-5': ('case item C14-5', []),
    'C14-6': ('case item C14-6', []),
    'P14-01': ('practice item P14-01', []),
    'P14-02': ('practice item P14-02', []),
    'P14-03': ('practice item P14-03', []),
    'P14-04': ('practice item P14-04', []),
    'P14-05': ('practice item P14-05', []),
    'P14-06': ('practice item P14-06', []),
    'P14-07': ('practice item P14-07', []),
    'P14-08': ('practice item P14-08', []),
    'P14-09': ('practice item P14-09', []),
    'P14-10': ('practice item P14-10', []),
    'P14-11': ('practice item P14-11', []),
    'P14-12': ('practice item P14-12', []),
    'P14-13': ('practice item P14-13', []),
    'P14-14': ('practice item P14-14', []),
    'P14-15': ('practice item P14-15', []),
    'P14-16': ('practice item P14-16', []),
    'P14-17': ('practice item P14-17', []),
    'P14-18': ('practice item P14-18', []),
    'SC14-1': ('section-check item SC14-1', []),
    'SC14-10': ('section-check item SC14-10', []),
    'SC14-11': ('section-check item SC14-11', []),
    'SC14-2': ('section-check item SC14-2', []),
    'SC14-3': ('section-check item SC14-3', []),
    'SC14-4': ('section-check item SC14-4', []),
    'SC14-5': ('section-check item SC14-5', []),
    'SC14-6': ('section-check item SC14-6', []),
    'SC14-7': ('section-check item SC14-7', []),
    'SC14-8': ('section-check item SC14-8', []),
    'SC14-9': ('section-check item SC14-9', []),
    'term:finance lease': ("term-bridge row 'finance lease'", []),
    'term:incremental borrowing rate': ("term-bridge row 'incremental borrowing rate'", []),
    'term:lease': ("term-bridge row 'lease'", []),
    'term:lease liability': ("term-bridge row 'lease liability'", []),
    'term:lease term': ("term-bridge row 'lease term'", []),
    'term:lessee': ("term-bridge row 'lessee'", []),
    'term:lessor': ("term-bridge row 'lessor'", []),
    'term:operating lease': ("term-bridge row 'operating lease'", []),
    'term:residual value guarantee': ("term-bridge row 'residual value guarantee'", []),
    'term:right-of-use asset': ("term-bridge row 'right-of-use asset'", []),
    'term:sale and leaseback': ("term-bridge row 'sale and leaseback'", []),
    'term:short-term lease': ("term-bridge row 'short-term lease'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C14-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P14-09': 'it sends the reader to F14-06, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC14-7': 'it sends the reader to F14-06, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC14-8': 'it sends the reader to F14-07, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
