"""B1.3 Unit 1 - The Next Video - twelve figures, as data."""
FIGURES = {
"fig_b13_u01_p00_v01": dict(type='V1', height=840, storey_h=155,
 title='The arts building, Tuesday, 11.05',
 sub='Twelve things to find. Five of them are competing for one person\'s attention.',
 alt='A university campus with a half-empty lecture theatre, a library, a coffee queue, bicycles '
     'and a poster showing a pass rate.',
 sky='#DEE4E6', ground='#A0A6A6', ground_line=680,
 buildings=[dict(x=20, w=540, storeys=3, colour='#D4D0C6', label='lecture theatre 4'),
   dict(x=640, w=400, storeys=4, colour='#CAC6BB', label='the library, one lift'),
   dict(x=1120, w=460, storeys=2, colour='#C1BDB3', label='the student union')],
 props=[dict(kind='tree', x=600, y=680, s=1.0), dict(kind='tree', x=1090, y=680, s=.95),
   dict(kind='table', x=1240, y=680, s=1.3),
   dict(kind='hoarding', x=300, y=680, s=1.0),
   dict(kind='box', x=1420, y=680, s=1.1),
   dict(kind='sign', x=120, y=680, s=.7, text='22 %'),
   dict(kind='sign', x=1060, y=680, s=.7, text='LIFT'),
   dict(kind='sign', x=1510, y=680, s=.7, text='11:05')],
 people=[dict(x=200, y=680, h=88, skin=3, cloth=0, hair='short', arm='hold'),
   dict(x=430, y=680, h=87, skin=1, cloth=2, hair='bun', arm='down'),
   dict(x=760, y=680, h=88, skin=4, cloth=3, hair='cap', arm='point'),
   dict(x=960, y=680, h=87, skin=0, cloth=1, hair='long', arm='hold'),
   dict(x=1300, y=680, h=88, skin=2, cloth=4, hair='grey', arm='folded')],
 names=[dict(x=200, t='Thanh, who works Tue and Thu'), dict(x=430, t='Priya, marking participation'),
   dict(x=760, t='Josie, nine years of nights'), dict(x=960, t='Bec, student union'),
   dict(x=1300, t='Mr Okafor, library'), dict(x=120, t='attendance, this week'),
   dict(x=1060, t='the one working lift')],
 markers=[dict(x=200, y=560), dict(x=430, y=560), dict(x=760, y=560), dict(x=960, y=560),
   dict(x=1300, y=560), dict(x=120, y=612), dict(x=1060, y=612), dict(x=1510, y=612),
   dict(x=300, y=624), dict(x=1240, y=630), dict(x=600, y=616), dict(x=1420, y=628)]),

"fig_b13_u01_p01_v08": dict(type='V8', height=800,
 title='What an interface is actually optimising',
 sub='Six nodes. Everything on the surface serves the one at the far right.',
 alt='A network from a prompt and a notification through autoplay and the feed to dwell time and '
     'time on site, with the opt-out shown as a long dashed path.',
 nodes={
  'not': dict(x=170, y=230, short='1', name='Notification', sub='the way back in', colour='#C86B2B'),
  'fee': dict(x=170, y=570, short='2', name='The feed', sub='no end, by design', colour='#1F4E5F'),
  'aut': dict(x=540, y=400, short='3', name='Autoplay', sub='five seconds to decide', colour='#A8372E'),
  'dwe': dict(x=900, y=230, short='4', name='Dwell', sub='how long on one item', colour='#D9A441'),
  'tos': dict(x=1270, y=400, short='5', name='Time on site', sub='the metric everything serves', r=56, colour='#8C6A9E'),
  'opt': dict(x=900, y=600, short='6', name='Opt out', sub='four levels down', r=50, colour='#9AA7AE')},
 edges=[dict(a='not', b='fee', label='and you are back', sw=6),
   dict(a='fee', b='aut', label='the next one has already started', sw=6),
   dict(a='aut', b='dwe', label='eleven more seconds, every time', sw=6),
   dict(a='dwe', b='tos', label='this is what is being raised', sw=6),
   dict(a='aut', b='opt', label='exists, in a submenu', sw=2, dash='6 6', colour='#9AA7AE'),
   dict(a='opt', b='tos', label='and almost nobody finds it', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_b13_u01_p02_v07": dict(type='V7', height=820,
 title='Attendance and the pass rate',
 sub='One of them records the lectures. One of them has the survey nobody commissioned.',
 alt='A lecturer and a student union officer in a corridor with a screen of figures, speech '
     'bubbles using defining and non-defining relative clauses.',
 bg='#E8EBEC',
 set=[dict(kind='table', x=700, y=700, s=1.4), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=2, cloth=4, hair='grey', arm='point', facing='right',
   label='Dr Ahmadi', role='records his lectures',
   says=['The students who work have done better.',
     'Attendance has halved, which nobody disputes.']),
  dict(x=980, h=248, skin=0, cloth=1, hair='long', arm='hold', facing='left',
   label='Bec', role='student union',
   says=['Forty-one students, most of whom work, have done better.'])]),

"fig_b13_u01_p03_v09": dict(type='V9', kind='scope', height=600,
 title='Two commas, two populations',
 sub='The same eight words. One of them is about some students and the other about all of them.',
 alt='One sentence shown twice with brackets marking the relative clause, once without commas '
     'and once with.',
 words=['The', 'students', '(,)', 'who', 'work', '(,)', 'have', 'done', 'better'],
 focus=[2, 5],
 brackets=[dict(**{'from': 3, 'to': 4}, lane=0, label='no commas: ONLY the ones who work',
     colour='#A8372E'),
   dict(**{'from': 2, 'to': 5}, lane=1, label='commas: ALL of them, and they happen to work',
     colour='#2E6F5E'),
   dict(**{'from': 6, 'to': 8}, lane=1, label='the main clause, unchanged either way',
     colour='#9AA7AE')]),

"fig_b13_u01_p03_v11": dict(type='V11', height=700,
 title='The comma splice that looks like a relative clause',
 alt='Two panels comparing most of them work joined by a comma and most of whom work as a '
     'relative clause.',
 wrong=dict(sentence='Forty-one students, most of them work, have done better.',
            boundary=0.50, boundary_label='a comma',
            event=0.78, event_label='joining two main clauses',
            why='Most of them work is a complete sentence with its own subject and verb. Joined '
                'by commas it is a splice: the reader reaches have done better and has lost the '
                'subject it belongs to.'),
 right=dict(sentence='Forty-one students, most of whom work, have done better.',
            boundary=0.50, boundary_label='a relative clause',
            event=0.24, event_label='subordinate, and it hands the subject back',
            why='Of whom turns the insert into a subordinate clause. It cannot stand alone, so '
                'the reader holds the main subject across it and picks it up again at have.'),
 misconception='Them and whom look interchangeable because they mean the same people. Only one '
               'of them subordinates, and subordination is what lets a sentence carry an aside '
               'without breaking.'),

"fig_b13_u01_p04_v04": dict(type='V4', height=740,
 title='The room, and the recording',
 sub='Learner A has the attendance figures. Learner B has the viewing figures.',
 alt='Two panels compared: a half-empty lecture theatre at eleven in the morning and a screen of '
     'viewing figures peaking after midnight.',
 differences=7, prompt='Which four lectures were not recorded, and what happened to those?',
 left=dict(label='the room, 11.05', art=[
   dict(kind='person', x=140, y=0, h=110, skin=3, cloth=0),
   dict(kind='person', x=220, y=0, h=112, skin=1, cloth=2),
   dict(kind='gap', x=300, y=10, w=60, bh=90),
   dict(kind='gap', x=380, y=10, w=60, bh=90),
   dict(kind='label', x=300, y=210, text='22 per cent of a 180-seat theatre',
        colour='#A8372E')]),
 right=dict(label='the recording, 23.00-02.00', art=[
   dict(kind='block', x=140, y=60, w=50, bh=50, colour='#1F4E5F'),
   dict(kind='block', x=210, y=20, w=50, bh=90, colour='#1F4E5F'),
   dict(kind='block', x=280, y=0, w=50, bh=110, colour='#1F4E5F'),
   dict(kind='block', x=350, y=40, w=50, bh=70, colour='#1F4E5F'),
   dict(kind='label', x=300, y=210, text='peak at 00.40, every week',
        colour='#1F4E5F')])),

"fig_b13_u01_p05_v05": dict(type='V5', height=1060,
 title='Attendance and attainment since 2019',
 sub='Six years of one figure, and a footnote on the other one.',
 alt='A university data pack showing attendance, pass rates, viewing figures and the four '
     'lectures that were not recorded.',
 rows=[dict(t='org', text='UNIVERSITY  -  TEACHING DATA  -  UNIT ARTS 2104'),
   dict(t='grid', cols=['YEAR', 'ATTENDANCE', 'PASS RATE'],
     data=[['2019 (pre)', '45 %', '81 %'], ['2020', '31 %', '80 %'],
           ['2021', '27 %', '82 %'], ['2022', '24 %', '81 %'],
           ['2023', '23 %', '83 %'], ['this year', '22 %', '82 %']]),
   dict(t='para', text='Attendance has fallen by 23 points. The overall pass rate has moved by '
     'two points in six years, which is within the normal year-to-year range of four.'),
   dict(t='rule'),
   dict(t='head', text='THE DISPUTED FIGURE'),
   dict(t='kv', k='Pass rate, students in paid work', v='+11 points *', mono=True),
   dict(t='kv', k='Source', v='student union survey', mono=False),
   dict(t='kv', k='Responses', v='41', mono=True),
   dict(t='kv', k='Enrolment', v='214', mono=True),
   dict(t='rule'),
   dict(t='head', text='THE FOUR UNRECORDED LECTURES'),
   dict(t='grid', cols=['DATE', 'REASON', 'ATTENDANCE'],
     data=[['3 Mar', 'hardware fault', '38 %'], ['10 Mar', 'hardware fault', '41 %'],
           ['17 Mar', 'hardware fault', '36 %'], ['24 Mar', 'hardware fault', '34 %']]),
   dict(t='para', text='Attendance at the four unrecorded lectures averaged 37 per cent, against '
     '22 for the rest. Nobody has published this.'),
   dict(t='rule'),
   dict(t='sign', text='FOOTNOTE * ON THE DISPUTED FIGURE:'),
   dict(t='para', text='"Self-selected sample. The university does not collect employment data '
     'and has not done so since this was requested in 2019."')],
 callouts=[dict(at=0.20, text='Twenty-three points of attendance, and two of attainment'),
   dict(at=0.30, text='Two points in six years is noise, and it is the headline'),
   dict(at=0.46, text='Forty-one of two hundred and fourteen, and self-selected'),
   dict(at=0.70, text='Thirty-seven per cent when it was not recorded. Fifteen points more'),
   dict(at=0.78, text='Published nowhere, and it is the only experiment anybody ran'),
   dict(at=0.94, text='Requested in 2019. Still not collected')]),

"fig_b13_u01_p07_v10": dict(type='V10', kind='pitch', height=700,
 title='The reset after the comma',
 sub='Three units, two pauses, and the pitch starts lower after each.',
 alt='Three pitch contours comparing a sentence with a non-defining clause between pauses and '
     'the same sentence run together.',
 contours=[dict(text='The students, | who work, | have done better.',
     points=[.6, .3, .55, .35, .15, .4, .1, -.5],
     meaning='two resets, each lower than the last'),
   dict(text='The students who work have done better.',
     points=[.4, .35, .3, .3, .25, .2, .1, -.4], meaning='no pauses - and a smaller group'),
   dict(text='Forty-one students, | most of whom work, | completed the unit.',
     points=[.5, .25, .5, .3, .1, .35, .05, -.55],
     meaning='the aside is held, and the verb comes back')]),

"fig_b13_u01_p08_v02": dict(type='V2', height=800,
 title='The autoplay stack, in section',
 sub='Four layers, and each one is a decision somebody made and did not announce.',
 alt='An interface drawn in four layers from the visible player through the countdown and the '
     'recommendation engine to the settings menu.',
 floors=[dict(was='what you see', now='The video, the countdown, and nothing else', year='',
     fill='#E4ECEF'),
   dict(was='the countdown', now='Five seconds. Shorter than most decisions', year='',
     fill='#EFE2DD'),
   dict(was='what chose it', now='Optimised for dwell, not for what you came for', year='',
     fill='#F6F0E4'),
   dict(was='the settings', now='Autoplay: ON. Four levels down, not in the first search screen',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='The only layer anybody is shown'),
   dict(at=0.38, text='Five seconds, and it is the single most effective element'),
   dict(at=0.62, text='The thing you came for is not an input to this'),
   dict(at=0.88, text='It exists. It is not findable, and that is also a design choice')]),

"fig_b13_u01_p09_v05": dict(type='V5', height=1040,
 title='The call about the four lectures',
 sub='Twenty-two minutes, three time zones, and one name obtained at minute nineteen.',
 alt='A summary of a support call about four failed lecture recordings, marked with each move '
     'and what was and was not agreed.',
 rows=[dict(t='org', text='SUPPORT CALL  -  LECTURE CAPTURE  -  22 MINUTES'),
   dict(t='grid', cols=['MIN', 'WHO', 'MOVE'],
     data=[['0-4', 'us', 'describing the problem without dates'],
           ['4', 'us', '"Four lectures: the 3rd, 10th, 17th and 24th."'],
           ['6-11', 'them', 'asking for information we do not have'],
           ['11', 'us', '"I can see the schedule. I cannot see the hardware."'],
           ['13-18', 'both', 'circular - the same three questions, twice'],
           ['19', 'us', '"Who should I be emailing, by name?"'],
           ['20', 'us', '"Let me say back what I think we have agreed."'],
           ['22', 'both', '"You will tell me by Thursday whether the files exist."']]),
   dict(t='rule'),
   dict(t='head', text='WHAT WAS AGREED'),
   dict(t='kv', k='A name', v='yes, at minute 19', mono=False),
   dict(t='kv', k='A date', v='Thursday', mono=False),
   dict(t='kv', k='Whether the files exist', v='unknown', mono=False),
   dict(t='kv', k='Whether they can be recovered', v='not discussed', mono=False),
   dict(t='para', text='The two useful minutes are 19 and 20. The eighteen before them produced '
     'nothing that was not in the first four.'),
   dict(t='rule'),
   dict(t='sign', text='WHAT CAME ON THURSDAY:'),
   dict(t='para', text='"The files do not exist. The hardware did not respond on any of the four '
     'dates. This was logged at our end on 4 March."')],
 callouts=[dict(at=0.17, text='Four minutes before anybody says a date'),
   dict(at=0.26, text='What you can see and what you cannot - and this unblocks it'),
   dict(at=0.35, text='Five minutes of circling, and it is the normal part'),
   dict(at=0.44, text='A name. Not a department, not a ticket number'),
   dict(at=0.68, text='Two useful minutes out of twenty-two'),
   dict(at=0.94, text='Logged on 4 March, and nobody had asked for eleven weeks')]),

"fig_b13_u01_p10_v12": dict(type='V12', height=880,
 title='Six years of lecture capture',
 sub='Half the class sees the 2019 minutes. Half sees the data. Rebuild it by speaking.',
 alt='An infographic from 2019 to the present showing attendance, attainment, the data collected '
     'and the question that was never asked.',
 span=['2019', 'next year'], ticks=6,
 tick_labels=['2019', '2021', '2022', 'this yr', 'the form', '+1 yr'],
 bands=[dict(name='Recording', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.12}, label='pilot, two units', colour='#D9A441'),
   dict(**{'from': 0.12, 'to': 0.46}, label='two-year trial', colour='#C86B2B'),
   dict(**{'from': 0.46, 'to': 1.0}, label='permanent - Dean, without the committee',
     colour='#1F4E5F')]),
  dict(name='Data collected', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='attendance, every week, for six years',
     colour='#9AA7AE'),
   dict(**{'from': 0.80, 'to': 1.0}, label='employment, at last', colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.04, label='"employment data would be difficult"', colour='#A8372E'),
   dict(at=0.32, label='review due 2021. Did not happen', colour='#A8372E'),
   dict(at=0.46, label='made permanent by the Dean', colour='#8C6A9E'),
   dict(at=0.62, label='survey of 41, self-selected: +11 points', colour='#D9A441'),
   dict(at=0.94, label='enrolment question: students working 15 h+ are 4 points DOWN',
     colour='#2E6F5E')]),
  dict(name='Attendance, per cent', type='line',
   points=[(0, 45), (0.2, 31), (0.4, 27), (0.6, 24), (0.8, 23), (1.0, 22)], end_label='22 %'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.24, label='four unrecorded lectures: attendance 37 per cent'),
   dict(at=0.54, label='and that result is published nowhere'),
   dict(at=0.72, label='six years of the easy number'),
   dict(at=0.98, label='one question on a form, and it reversed the argument')])]),

"fig_b13_u01_p11_v06": dict(type='V6', kind='line', height=800,
 title='Attendance, attainment and the four unrecorded weeks',
 sub='Six years of one unit, with the four hardware failures marked.',
 alt='A line chart of attendance and pass rate over six years, with four weeks of hardware '
     'failure showing a sharp attendance spike.',
 labels=['2019', '2020', '2021', '2022', '2023', 'now'],
 ymin=0, ymax=100, fmt='{:,.0f}',
 series=[dict(name='attendance %', values=[45, 31, 27, 24, 23, 22], colour='#A8372E'),
   dict(name='pass rate %', values=[81, 80, 82, 81, 83, 82], colour='#2E6F5E')],
 note='Attendance has fallen 23 points. The pass rate has moved two, which is inside the normal '
      'year-to-year range.',
 warning='In the four weeks when the recording failed, attendance averaged 37 per cent. That is '
         'the only controlled comparison anybody has, it lasted a month, and it was an accident.'),
}
