"""B1.3 Unit 3 - The Best Voice in the Room - twelve figures, as data."""
FIGURES = {
"fig_b13_u03_p00_v01": dict(type='V1', height=840, storey_h=150,
 title='Seminar room 2.14, week nine, 11.52',
 sub='Twelve things to find. Four belong to the person speaking. Four belong to the people who '
     'are not.',
 alt='A humanities building with a seminar room, a clock at 11.52, a half-raised hand, a propped '
     'door and a tutor with a tally sheet.',
 sky='#DFE5E4', ground='#A4A9A4', ground_line=672,
 buildings=[dict(x=20, w=600, storeys=3, colour='#D0CCC2', cutaway=True,
     floor_labels=['seminar 2.14 - eleven chairs, two empty',
                   'the corridor, and a door propped open',
                   'the foyer, where people wait'],
     label='Arts - seminar rooms'),
   dict(x=700, w=420, storeys=3, colour='#C6C2B7', label='the library, and the unfinished reading'),
   dict(x=1190, w=390, storeys=2, colour='#BDB9AF', label='the faculty office, committee twice a year')],
 props=[dict(kind='tree', x=660, y=672, s=1.0),
   dict(kind='hoarding', x=1150, y=672, s=.95),
   dict(kind='table', x=1310, y=672, s=1.3),
   dict(kind='box', x=1500, y=672, s=1.0),
   dict(kind='sign', x=1060, y=672, s=.7, text='11:52'),
   dict(kind='sign', x=900, y=672, s=.7, text='15 %')],
 people=[dict(x=140, y=672, h=86, skin=4, cloth=3, hair='short', arm='point'),
   dict(x=265, y=672, h=86, skin=3, cloth=0, hair='cap', arm='down'),
   dict(x=390, y=672, h=86, skin=1, cloth=2, hair='bun', arm='hold'),
   dict(x=790, y=672, h=86, skin=0, cloth=1, hair='long', arm='folded'),
   dict(x=1400, y=672, h=86, skin=2, cloth=4, hair='grey', arm='hold')],
 names=[dict(x=140, t='Marcus, seventeen minutes of fifty'),
   dict(x=265, t='Thanh, a hand half-raised'),
   dict(x=390, t='Priya, with a tally sheet'),
   dict(x=790, t='the reading nobody finished'),
   dict(x=1400, t='the committee, November'),
   dict(x=1060, t='eight minutes left'),
   dict(x=900, t='participation, fifteen per cent'),
   dict(x=1310, t='a phone face down, a coffee gone cold')],
 markers=[dict(x=140, y=552), dict(x=265, y=552), dict(x=390, y=552), dict(x=790, y=552),
   dict(x=1400, y=552), dict(x=1060, y=606), dict(x=900, y=606), dict(x=1310, y=624),
   dict(x=1150, y=620), dict(x=1500, y=622), dict(x=660, y=610), dict(x=120, y=430)]),

"fig_b13_u03_p01_v08": dict(type='V8', height=800,
 title='What a disagreement is made of',
 sub='Six nodes. Two of them are the same move made at different volumes.',
 alt='A network from a position and a premise through an objection and a rebuttal to common '
     'ground, with shout down shown as a shortcut that skips the rebuttal.',
 nodes={
  'prm': dict(x=170, y=230, short='1', name='The premise', sub='what both sides accept',
              colour='#2E6F5E'),
  'pos': dict(x=170, y=570, short='2', name='The position', sub='what one side holds',
              colour='#1F4E5F'),
  'obj': dict(x=540, y=400, short='3', name='The objection', sub='what it does not account for',
              colour='#C86B2B'),
  'reb': dict(x=900, y=230, short='4', name='The rebuttal', sub='the answer to the objection',
              colour='#D9A441'),
  'cgr': dict(x=1270, y=400, short='5', name='Common ground', sub='found, not given',
              r=56, colour='#2E6F5E'),
  'shd': dict(x=900, y=600, short='6', name='Shout down', sub='volume instead of a rebuttal',
              r=50, colour='#A8372E')},
 edges=[dict(a='prm', b='obj', label='both sides stand here first', sw=6),
   dict(a='pos', b='obj', label='and here is where it is tested', sw=6),
   dict(a='obj', b='reb', label='answered, or it stands', sw=6),
   dict(a='reb', b='cgr', label='and the ground narrows to something real', sw=6),
   dict(a='obj', b='shd', label='the shortcut', sw=2, dash='6 6', colour='#A8372E'),
   dict(a='shd', b='cgr', label='which ends the argument and finds nothing', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_b13_u03_p02_v07": dict(type='V7', height=820,
 title='The seminar, minute thirty-one',
 sub='One of them has read everything. One of them has the tally sheet.',
 alt='A student speaking across a seminar table and a tutor listening with a tally sheet, their '
     'speech shown as concession clauses.',
 bg='#E9ECEA',
 set=[dict(kind='table', x=700, y=700, s=1.5), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=4, cloth=3, hair='short', arm='point', facing='right',
   label='Marcus', role='seventeen minutes of fifty',
   says=['Despite the quality of what he says, nobody else has said anything.',
     'He is right. However, so was the person he talked over.']),
  dict(x=980, h=248, skin=1, cloth=2, hair='bun', arm='hold', facing='left',
   label='Priya', role='marks participation',
   says=['Although he is right, he is right at everyone else\'s expense.'])]),

"fig_b13_u03_p03_v09": dict(type='V9', kind='scope', height=520,
 title='Which half survives the sentence?',
 sub='A concession clause is the half the writer is prepared to lose.',
 alt='One sentence with brackets marking the although clause as the concession and the main '
     'clause as the point that is kept.',
 words=['Although', 'he', 'is', 'right', ',', 'nobody', 'else', 'has', 'spoken'],
 focus=[0, 5],
 brackets=[dict(**{'from': 0, 'to': 3}, lane=0, label='given away on purpose, and it must be true',
     colour='#C86B2B'),
   dict(**{'from': 5, 'to': 8}, lane=0, label='the point. It is what the sentence is for',
     colour='#1F4E5F'),
   dict(**{'from': 4, 'to': 4}, lane=1, label='one concession word per sentence - no but after this comma',
     colour='#A8372E')]),

"fig_b13_u03_p03_v11": dict(type='V11', height=720,
 title='Although and but, doing the same job twice',
 alt='Two panels comparing although he is right but he is loud with although he is right he is '
     'loud.',
 wrong=dict(sentence='Although he is right, but he is loud.',
            boundary=0.44, boundary_label='the concession ends here',
            event=0.56, event_label='and but marks it as subordinate a second time',
            why='Although has already told the reader that the first clause is the one being '
                'given away. But does the same job. With both, neither clause is the main one, '
                'and the sentence has no independent half left to land on.'),
 right=dict(sentence='Although he is right, he is loud.',
            boundary=0.44, boundary_label='the concession ends here',
            event=0.70, event_label='and the main clause starts clean',
            why='Delete the second marker, not the first. The comma is doing the work that but '
                'was trying to do, and the clause after it is independent, which is what lets '
                'the sentence be about loudness rather than about rightness.'),
 misconception='Writers double the marker because they can hear the contrast twice and want to '
               'mark it twice. English marks a contrast once. The test is simple: cover the '
               'first clause. If what is left cannot stand alone as a sentence, one marker too '
               'many is in it.'),

"fig_b13_u03_p04_v04": dict(type='V4', height=760,
 title='Fifty minutes, two ways of counting them',
 sub='Learner A has who spoke. Learner B has what was said.',
 alt='Two panels compared: a bar of airtime dominated by one speaker and a list of the ideas the '
     'seminar actually produced.',
 differences=7, prompt='Where do the two accounts agree completely, and what does that one '
                       'agreement cost each side?',
 left=dict(label='airtime, week nine', art=[
   dict(kind='block', x=140, y=0, w=56, bh=170, colour='#A8372E'),
   dict(kind='block', x=216, y=118, w=56, bh=52, colour='#1F4E5F'),
   dict(kind='block', x=292, y=140, w=56, bh=30, colour='#1F4E5F'),
   dict(kind='block', x=368, y=162, w=56, bh=8, colour='#9AA7AE'),
   dict(kind='label', x=300, y=220, text='17 min · 5 · 3 · 40 sec between four',
        colour='#A8372E')]),
 right=dict(label='ideas the hour produced', art=[
   dict(kind='person', x=150, y=0, h=108, skin=4, cloth=3),
   dict(kind='person', x=250, y=0, h=106, skin=3, cloth=0),
   dict(kind='gap', x=340, y=14, w=56, bh=86),
   dict(kind='label', x=300, y=220, text='four ideas - and two of them were his',
        colour='#1F4E5F')])),

"fig_b13_u03_p05_v05": dict(type='V5', height=1080,
 title='The transcript and the airtime sheet',
 sub='Fifty minutes of seminar 2.14, week nine, recorded for the review.',
 alt='A seminar transcript extract beside an airtime tally sheet, with interruptions marked and '
     'one row left blank by the tutor.',
 rows=[dict(t='org', text='TEACHING QUALITY REVIEW  -  SEMINAR 2.14  -  WEEK 9  -  50 MIN'),
   dict(t='grid', cols=['STUDENT', 'SPOKE', 'INTERRUPTED BY / OTHERS'],
     data=[['Marcus', '17 min 10 s', 'interrupted 0 / interrupted 6'],
           ['Aoife', '5 min 40 s', 'interrupted 2 / interrupted 1'],
           ['Dilan', '3 min 05 s', 'interrupted 1 / interrupted 0'],
           ['Thanh', '0 min 11 s', 'interrupted 1 / interrupted 0'],
           ['four others', '0 min 29 s total', 'interrupted 2 / interrupted 0'],
           ['three others', 'did not speak', '-']]),
   dict(t='rule'),
   dict(t='head', text='TRANSCRIPT, MINUTES 30-33'),
   dict(t='para', text='MARCUS: ...which is exactly the premise the whole chapter rests on, and '
     'it does not survive the second table.'),
   dict(t='para', text='THANH: Can I just - the second table is a different sample, so it -'),
   dict(t='para', text='MARCUS: It is the same sample. Sorry, it is, I checked.'),
   dict(t='para', text='THANH: [inaudible]'),
   dict(t='para', text='MARCUS: Anyway. The point is that if you take the premise seriously -'),
   dict(t='para', text='AOIFE: I take your point about the table. I still think he is doing '
     'something different with it in chapter four.'),
   dict(t='para', text='MARCUS: ...Yes. All right, yes. In chapter four he is. I concede that.'),
   dict(t='rule'),
   dict(t='head', text='TUTOR NOTES, WRITTEN IN WEEK 12'),
   dict(t='kv', k='Marcus', v='excellent, as always', mono=False),
   dict(t='kv', k='Aoife', v='good, growing in confidence', mono=False),
   dict(t='kv', k='Dilan', v='solid', mono=False),
   dict(t='kv', k='Thanh', v='', mono=False),
   dict(t='rule'),
   dict(t='sign', text='THANH, WEEK 9, ELEVEN SECONDS:'),
   dict(t='para', text='"Can I just - the second table is a different sample, so it -". It was '
     'a different sample. He had the page open.')],
 callouts=[dict(at=0.12, text='Seventeen minutes, and interrupted by nobody'),
   dict(at=0.20, text='Eleven seconds, and interrupted once. That is all of it'),
   dict(at=0.33, text='Three students did not speak at all, and have a participation mark'),
   dict(at=0.52, text='The interruption, and the apology that keeps the floor'),
   dict(at=0.66, text='Aoife concedes the point and keeps her objection. It works'),
   dict(at=0.80, text='Written in week twelve, three weeks after anybody could remember'),
   dict(at=0.88, text='The blank row is the one student who was right')]),

"fig_b13_u03_p07_v10": dict(type='V10', kind='pitch', height=680,
 title='The rise that promises a disagreement',
 sub='Three versions. Only one of them means something is coming.',
 alt='Three pitch contours comparing admittedly with a rise, admittedly flat, and though in end '
     'position.',
 contours=[dict(text='Admittedly, | he is right.',
     points=[.2, .55, .6, .2, .1, .0, -.2, -.5],
     meaning='rise on admittedly - a but is coming'),
   dict(text='Admittedly he is right.',
     points=[.3, .25, .2, .15, .1, .0, -.2, -.5],
     meaning='no rise, no promise - this is just agreeing'),
   dict(text='He is right, though.',
     points=[.3, .25, .2, .1, .0, .3, .45, .3],
     meaning='rise at the end - and something is still coming')]),

"fig_b13_u03_p08_v02": dict(type='V2', height=820,
 title='An argument that concedes, in section',
 sub='Four layers. The top one is the other side, written by you, at its best.',
 alt='A cutaway of a written argument in four layers from the opposing case through the '
     'concession and the turn to the falsifier.',
 floors=[dict(was='the other side', now='Their best case, in your words, with nothing softened',
     year='', fill='#E4ECEF'),
   dict(was='the concession', now='Something true that costs you. If it costs nothing it is not one',
     year='', fill='#EFE2DD'),
   dict(was='the turn', now='Even so - and the evidence is inside the same sentence', year='',
     fill='#F6F0E4'),
   dict(was='the falsifier', now='What would change your mind, named before anybody asks',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='This is what buys you the right to the next three layers'),
   dict(at=0.38, text='A concession that costs nothing reads as a technique, and is one'),
   dict(at=0.62, text='The turn carries evidence, not volume'),
   dict(at=0.88, text='Without this last layer it is a position, not an argument')]),

"fig_b13_u03_p09_v05": dict(type='V5', height=1040,
 title='Four minutes late, five explanations',
 sub='The same four minutes, measured against four different things.',
 alt='A record of five people arriving four minutes after a meeting started, with what each one '
     'was measuring lateness against.',
 rows=[dict(t='org', text='CULTURE FILE  -  TIME, LATENESS AND WAITING'),
   dict(t='grid', cols=['PERSON', 'ARRIVED', 'MEASURED AGAINST'],
     data=[['Josie, night security', '11.04', 'the task - nothing had been decided yet'],
           ['Dr Ahmadi', '11.04', 'the clock - and he apologised twice'],
           ['Bec', '11.04', 'the room - the Dean was not in yet either'],
           ['Mr Okafor', '11.04', 'the host - the chair had not sat down'],
           ['Thanh', '11.04', 'the clock - and waited outside until 11.10']]),
   dict(t='para', text='Three of the five did not think they were late. Two did. Nobody in the '
     'room had said which of the four clocks the meeting was running on, and nobody ever does.'),
   dict(t='rule'),
   dict(t='head', text='WHY THANH WAITED OUTSIDE UNTIL 11.10'),
   dict(t='para', text='"If I go in at four minutes past, everybody looks up. If I go in at ten '
     'past, they are already arguing and nobody turns round. I have been doing it for two years '
     'and it costs me six minutes a week."'),
   dict(t='rule'),
   dict(t='head', text='WHO DOES THE WAITING'),
   dict(t='kv', k='Meetings starting before 09.00', v='41 of 60 this term', mono=True),
   dict(t='kv', k='Night shift ends', v='07.00', mono=True),
   dict(t='kv', k='Staff on night shift', v='9', mono=True),
   dict(t='kv', k='Night staff on the committee that sets times', v='0', mono=True),
   dict(t='rule'),
   dict(t='sign', text='JOSIE, NINE YEARS OF NIGHTS:'),
   dict(t='para', text='"Nobody has ever been rude about it. The nine o\'clock meeting is not a '
     'rule, it is just when everybody else is fresh. That is what makes it hard to raise."')],
 callouts=[dict(at=0.14, text='The same minute. Three of them were not late'),
   dict(at=0.26, text='He apologised, and the apology tells you about the room'),
   dict(at=0.44, text='Six minutes a week, spent avoiding being looked at'),
   dict(at=0.72, text='Forty-one of sixty, and the shift ends two hours before'),
   dict(at=0.82, text='Nobody who does the waiting sets the time'),
   dict(at=0.94, text='Not a rule. Which is exactly why it has lasted nine years')]),

"fig_b13_u03_p10_v12": dict(type='V12', height=900,
 title='One seminar, twelve weeks',
 sub='Half the class sees the report. Half sees the transcript. Rebuild the term by speaking.',
 alt='An infographic across twelve weeks showing airtime, the number of students speaking, the '
     'format change in week ten and the committee deadline.',
 span=['week 1', 'next year'], ticks=6,
 tick_labels=['wk 1', 'wk 3', 'wk 9', 'wk 10', 'wk 12', 'next yr'],
 bands=[dict(name='The format', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.66}, label='open discussion, as published', colour='#9AA7AE'),
   dict(**{'from': 0.66, 'to': 0.86}, label='two minutes writing, then round the table',
     colour='#2E6F5E'),
   dict(**{'from': 0.86, 'to': 1.0}, label='back to the published criterion', colour='#A8372E')]),
  dict(name='Marcus', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.14}, label='8 min', colour='#D9A441'),
   dict(**{'from': 0.14, 'to': 0.66}, label='rising to 17 min, every week', colour='#C86B2B'),
   dict(**{'from': 0.66, 'to': 0.86}, label='6 min, and did not notice', colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.10, label='week 3: the gap starts widening', colour='#D9A441'),
   dict(at=0.44, label='week 9: Thanh speaks for eleven seconds and is right', colour='#A8372E'),
   dict(at=0.68, label='week 10: format changed, nine of eleven speak', colour='#2E6F5E'),
   dict(at=0.80, label='week 12: notes written from memory, one row blank', colour='#8C6A9E'),
   dict(at=0.95, label='paper misses the November committee by four days', colour='#A8372E')]),
  dict(name='Students who spoke, of eleven', type='line',
   points=[(0, 9), (0.14, 7), (0.44, 4), (0.70, 9), (0.86, 11), (1.0, 4)], end_label='4'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.22, label='record anything during the class'),
   dict(at=0.50, label='ask the three who never spoke whether they had read it'),
   dict(at=0.76, label='write the format change down while it was working'),
   dict(at=0.98, label='put the paper in before the deadline')])]),

"fig_b13_u03_p11_v06": dict(type='V6', kind='bar', height=840,
 title='Airtime and essay marks, all eleven students',
 sub='The two numbers the seminar produces, side by side.',
 alt='A bar chart of minutes spoken and essay mark for eleven students, showing no relationship '
     'between the two.',
 labels=['Marcus', 'Aoife', 'Dilan', 'Thanh', 'Nia', 'Sam', 'Four others'],
 ymin=0, ymax=100, fmt='{:,.0f}',
 series=[dict(name='minutes spoken x5', values=[86, 28, 15, 1, 3, 2, 1], colour='#C86B2B'),
   dict(name='essay mark', values=[78, 71, 66, 84, 69, 58, 64], colour='#1F4E5F')],
 note='Airtime is multiplied by five so that it fits the same axis as the mark. Nothing else '
      'has been adjusted.',
 warning='The highest essay mark in the group belongs to the student who spoke for eleven '
         'seconds, and fifteen per cent of his unit mark is for participation.'),
}
