"""B1.3 Unit 4 - The Garden That Has Two Jobs - twelve figures, as data."""
FIGURES = {
"fig_b13_u04_p00_v01": dict(type='V1', height=840, storey_h=146,
 title='The teaching garden, March, 08.20',
 sub='Twelve things to find. Four exist for teaching. Four exist for food.',
 alt='A campus garden with forty metre-square beds, a greenhouse, a compost bay built from '
     'pallets, a water butt and a shed with two padlocks.',
 sky='#DFE7E2', ground='#9EA38E', ground_line=666,
 buildings=[dict(x=20, w=430, storeys=2, colour='#CFCBBF', label='the greenhouse, door open'),
   dict(x=540, w=320, storeys=1, colour='#C5C1B5', label='the teaching shed, two padlocks'),
   dict(x=1080, w=500, storeys=3, colour='#BCB8AE', label='the campus kitchen, four days of salad')],
 props=[dict(kind='tree', x=490, y=666, s=1.0), dict(kind='tree', x=960, y=666, s=.9),
   dict(kind='hoarding', x=900, y=666, s=.9),
   dict(kind='box', x=1020, y=666, s=1.2),
   dict(kind='table', x=700, y=666, s=1.3),
   dict(kind='sign', x=120, y=666, s=.7, text='94 kg'),
   dict(kind='sign', x=340, y=666, s=.7, text='1 m')],
 people=[dict(x=200, y=666, h=84, skin=3, cloth=0, hair='cap', arm='down'),
   dict(x=620, y=666, h=84, skin=1, cloth=2, hair='bun', arm='point'),
   dict(x=820, y=666, h=84, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=1250, y=666, h=84, skin=0, cloth=1, hair='long', arm='folded'),
   dict(x=1450, y=666, h=84, skin=2, cloth=4, hair='grey', arm='hold')],
 names=[dict(x=200, t='a student with one bed, one semester'),
   dict(x=620, t='the garden manager, six years'),
   dict(x=820, t='a tray of seedlings, labelled by hand'),
   dict(x=1250, t='the head chef, who put it on a board'),
   dict(x=1450, t='the School, which never specified food'),
   dict(x=120, t='94 kg last year, across forty beds'),
   dict(x=340, t='one metre, so you can reach the middle'),
   dict(x=1020, t='crates by a gate, going the wrong way')],
 markers=[dict(x=200, y=552), dict(x=620, y=552), dict(x=820, y=552), dict(x=1250, y=552),
   dict(x=1450, y=552), dict(x=120, y=602), dict(x=340, y=602), dict(x=1020, y=618),
   dict(x=900, y=612), dict(x=700, y=620), dict(x=490, y=606), dict(x=960, y=606)]),

"fig_b13_u04_p01_v08": dict(type='V8', height=800,
 title='From a brief to a thing that exists',
 sub='Six nodes. The one at the bottom is the one nobody writes down.',
 alt='A network from a design brief through requirements and constraints to a prototype and a '
     'trade-off, with use in practice as an unplanned path.',
 nodes={
  'brf': dict(x=170, y=230, short='1', name='The brief', sub='what somebody asked for',
              colour='#1F4E5F'),
  'req': dict(x=170, y=570, short='2', name='Requirements', sub='what it must do',
              colour='#2E6F5E'),
  'con': dict(x=540, y=400, short='3', name='Constraints', sub='what it cannot do',
              colour='#C86B2B'),
  'pro': dict(x=900, y=230, short='4', name='Prototype', sub='a question in physical form',
              colour='#D9A441'),
  'thi': dict(x=1270, y=400, short='5', name='The thing', sub='and the trade-off inside it',
              r=56, colour='#8C6A9E'),
  'prc': dict(x=900, y=600, short='6', name='In practice', sub='the second job, never specified',
              r=50, colour='#A8372E')},
 edges=[dict(a='brf', b='con', label='and here is where the wishing stops', sw=6),
   dict(a='req', b='con', label='both halves meet at the same wall', sw=6),
   dict(a='con', b='pro', label='built to be wrong, quickly', sw=6),
   dict(a='pro', b='thi', label='and what survives is the design', sw=6),
   dict(a='thi', b='prc', label='people use it for something else', sw=2, dash='6 6',
        colour='#A8372E'),
   dict(a='prc', b='brf', label='and the new use becomes the brief nobody wrote', sw=2,
        dash='6 6', colour='#9AA7AE')]),

"fig_b13_u04_p02_v07": dict(type='V7', height=820,
 title='At the gate, Tuesday morning',
 sub='One of them runs the curriculum. One of them runs a kitchen.',
 alt='A garden manager and a head chef talking by a garden gate, their speech shown as purpose '
     'and result clauses.',
 bg='#E6ECE6',
 set=[dict(kind='table', x=700, y=700, s=1.4), dict(kind='box', x=540, y=700, s=1.1)],
 people=[dict(x=470, h=250, skin=1, cloth=2, hair='bun', arm='point', facing='right',
   label='the garden manager', role='six years, twelve crops',
   says=['The beds are small so that twenty students can each have one.',
     'We grow twelve crops in order to show twelve growing cycles.']),
  dict(x=980, h=248, skin=0, cloth=1, hair='long', arm='hold', facing='left',
   label='the head chef', role='put it on the menu board',
   says=['The yield is so low that the kitchen gets about four days of salad a year.'])]),

"fig_b13_u04_p03_v09": dict(type='V9', kind='branch', height=700,
 title='Purpose looks forward. Result looks back.',
 sub='So that is the one word that does both, and the verb after it tells you which.',
 alt='A branching diagram separating purpose forms from reason forms and result forms, each with '
     'an example.',
 root='why is it like this?',
 branches=[dict(label='PURPOSE - what it is for', colour='#2E6F5E',
     example='The beds are small so that each student can reach the centre.'),
   dict(label='PURPOSE, same subject', colour='#1F4E5F',
     example='We grow twelve crops in order to show twelve cycles.'),
   dict(label='REASON - what caused it', colour='#C86B2B',
     example='Owing to the curriculum, the beds cannot be merged.'),
   dict(label='RESULT - what followed', colour='#A8372E',
     example='The yield is so low that nobody measures it.'),
   dict(label='RESULT, with a noun', colour='#D9A441',
     example='It is such a low yield that the kitchen hardly notices.')]),

"fig_b13_u04_p03_v11": dict(type='V11', height=720,
 title='In order to, and the subject it cannot change',
 alt='Two panels comparing in order to students can have one with so that students can have one.',
 wrong=dict(sentence='The beds are small in order to students can have one.',
            boundary=0.46, boundary_label='in order to ends here',
            event=0.62, event_label='and a new subject arrives, which it cannot take',
            why='In order to is followed by an infinitive, and an infinitive has no subject of '
                'its own. It borrows the subject of the main clause, which here is the beds. '
                'Students cannot be introduced after it, so the sentence has a subject with '
                'nowhere to attach.'),
 right=dict(sentence='The beds are small so that students can have one.',
            boundary=0.46, boundary_label='so that ends here',
            event=0.70, event_label='and a full clause follows, with its own subject',
            why='So that takes a clause, so a new subject is exactly what it is waiting for. '
                'The other repair keeps in order to and changes the main subject instead: we '
                'made the beds small in order to give each student one.'),
 misconception='Learners choose between in order to and so that by formality, because both are '
               'translated the same way. The choice is grammatical: if the second half has a '
               'different subject, only so that will carry it.'),

"fig_b13_u04_p04_v04": dict(type='V4', height=760,
 title='Forty small beds, or eight merged ones',
 sub='Learner A has the design brief. Learner B has last year\'s harvest.',
 alt='Two panels compared: a grid of forty metre-square beds and a field of eight long merged '
     'plots, with yield figures.',
 differences=7, prompt='Which requirement was met exactly, and what did meeting it cost?',
 left=dict(label='forty beds, twelve crops', art=[
   dict(kind='block', x=140, y=120, w=46, bh=46, colour='#2E6F5E'),
   dict(kind='block', x=200, y=120, w=46, bh=46, colour='#2E6F5E'),
   dict(kind='block', x=260, y=120, w=46, bh=46, colour='#2E6F5E'),
   dict(kind='block', x=320, y=120, w=46, bh=46, colour='#2E6F5E'),
   dict(kind='person', x=400, y=0, h=104, skin=3, cloth=0),
   dict(kind='label', x=300, y=220, text='94 kg · 12 cycles · 20 students',
        colour='#2E6F5E')]),
 right=dict(label='eight merged plots, four crops', art=[
   dict(kind='block', x=140, y=96, w=230, bh=70, colour='#C86B2B'),
   dict(kind='gap', x=400, y=20, w=50, bh=80),
   dict(kind='label', x=300, y=220, text='480 kg · 4 cycles · students visit',
        colour='#C86B2B')])),

"fig_b13_u04_p05_v05": dict(type='V5', height=1080,
 title='The design brief and the harvest sheet',
 sub='Written six years apart, by people who never met.',
 alt='A garden design brief listing five requirements beside a harvest record showing yield per '
     'bed and one crop that failed.',
 rows=[dict(t='org', text='SCHOOL OF AGRICULTURE  -  TEACHING GARDEN  -  DESIGN BRIEF, YEAR 1'),
   dict(t='grid', cols=['#', 'REQUIREMENT', 'WHY'],
     data=[['R1', 'one bed per student, 20 students', 'individual responsibility'],
           ['R2', 'reachable centre from any edge', 'nobody stands on soil'],
           ['R3', 'twelve crops, twelve cycles', 'one academic year, all stages'],
           ['R4', 'three crops that fail reliably', 'learning to read a plant'],
           ['R5', 'no requirement on yield', '-']]),
   dict(t='para', text='R2 fixes the bed at one metre square. R1 fixes the number at forty. '
     'Together they fix the yield, and nobody wrote that down because nobody was asked to.'),
   dict(t='rule'),
   dict(t='head', text='HARVEST RECORD  -  LAST YEAR'),
   dict(t='grid', cols=['CROP', 'BEDS', 'KG'],
     data=[['silverbeet', '6', '28'], ['beans', '4', '17'], ['carrots', '4', '11'],
           ['potatoes', '4', '14'], ['brassicas', '6', '9'],
           ['cauliflower', '3', '0  - failed, as specified'],
           ['seven others', '13', '15']]),
   dict(t='kv', k='Total', v='94 kg', mono=True),
   dict(t='kv', k='Yield per square metre', v='2.35 kg', mono=True),
   dict(t='kv', k='Commercial bed, same soil', v='11-13 kg', mono=True),
   dict(t='kv', k='Days of campus kitchen use', v='4', mono=True),
   dict(t='rule'),
   dict(t='sign', text='ADDED BY HAND, IN A DIFFERENT PEN, THREE YEARS LATER:'),
   dict(t='para', text='"R6 - the kitchen takes what there is. Not a requirement. Nobody has '
     'agreed to this. - D.O., garden manager"')],
 callouts=[dict(at=0.14, text='R2 is the only one with a number in it, and it decides everything'),
   dict(at=0.24, text='Met exactly - and it is what costs the yield'),
   dict(at=0.30, text='No requirement on yield. That is the sentence the argument rests on'),
   dict(at=0.62, text='A crop that produced nothing, and it was in the brief'),
   dict(at=0.78, text='2.35 against 11 - a fifth of what the soil can do'),
   dict(at=0.94, text='A sixth requirement that nobody agreed to, written in by the one person '
     'who noticed')]),

"fig_b13_u04_p07_v10": dict(type='V10', kind='stress', height=640,
 title='The purpose clause carries the news',
 sub='Same words. Move the stress and the sentence changes what it is about.',
 alt='Four phrases marked for stress, showing the difference between stressing the purpose '
     'clause and stressing the main clause.',
 items=[dict(syllables=['so', 'that', 'each', 'stu', 'dent', 'can', 'reach', 'the', 'CEN', 'tre'],
     strong=[8], note='the purpose is the news'),
   dict(syllables=['the', 'beds', 'are', 'SMALL', 'so', 'that', 'they', 'can', 'reach', 'it'],
     strong=[3], note='now the size is the news and the purpose is background'),
   dict(syllables=['we', 'built', 'it', 'SO', 'that', 'it', 'would', 'fail'],
     strong=[3], note='that was the plan'),
   dict(syllables=['we', 'built', 'it', 'so', 'that', 'it', 'would', 'FAIL'],
     strong=[7], note='and the failing is the point')]),

"fig_b13_u04_p08_v02": dict(type='V2', height=820,
 title='A design rationale, in section',
 sub='Four layers. The top one is a sentence anybody could argue with.',
 alt='A cutaway of a written design rationale in four layers from the decision and its purpose '
     'to the trade-off and what the writer would change.',
 floors=[dict(was='the decision', now='One metre square - and the purpose comes last in the sentence',
     year='', fill='#E4ECEF'),
   dict(was='the constraint', now='Twenty students, one semester. A number, not an adjective',
     year='', fill='#EFE2DD'),
   dict(was='the trade-off', now='4 kg a bed against 11. Both sides measured, or it is not one',
     year='', fill='#F6F0E4'),
   dict(was='what you would change', now='Two merged beds, so students can see what they give up',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Purpose last, so the reader finishes the sentence knowing why'),
   dict(at=0.38, text='Optimised and appropriate are what goes here when nobody measured'),
   dict(at=0.62, text='One number is a claim. Two is a trade-off'),
   dict(at=0.88, text='Changing the design is not conceding it was wrong')]),

"fig_b13_u04_p09_v05": dict(type='V5', height=1060,
 title='Four briefs, and what each one actually is',
 sub='A problem, a solution, a wish and a budget - and only one of them says so.',
 alt='Four client briefs transcribed with annotations identifying which are problems, solutions, '
     'wishes or budgets in disguise.',
 rows=[dict(t='org', text='WORK FILE  -  THE CLIENT PROBLEM  -  FOUR BRIEFINGS'),
   dict(t='head', text='BRIEF 1  -  THE LIBRARY'),
   dict(t='para', text='"Students cannot find anything on the third floor. We do not know why. '
     'Last year we moved the signage and it got worse."'),
   dict(t='kv', k='What it is', v='a problem, stated as one', mono=False),
   dict(t='kv', k='Useful', v='very - and it includes a failed attempt', mono=False),
   dict(t='rule'),
   dict(t='head', text='BRIEF 2  -  THE STUDENT UNION'),
   dict(t='para', text='"We need an app. It should have a map, a timetable, a chat function and '
     'push notifications for events."'),
   dict(t='kv', k='What it is', v='a solution wearing a requirement list', mono=False),
   dict(t='kv', k='The question to ask', v='what are people doing now instead', mono=False),
   dict(t='rule'),
   dict(t='head', text='BRIEF 3  -  THE FACULTY'),
   dict(t='para', text='"We want the foyer to feel welcoming. Open. Like somewhere you would '
     'bring your family."'),
   dict(t='kv', k='What it is', v='a wish, and it is not useless', mono=False),
   dict(t='kv', k='The question to ask', v='what would success look like in a year', mono=False),
   dict(t='rule'),
   dict(t='head', text='BRIEF 4  -  ESTATES'),
   dict(t='para', text='"Forty thousand dollars. Whatever you can do with the entrance for '
     'forty thousand dollars." [at minute 26: "and it has to be finished before semester two"]'),
   dict(t='kv', k='What it is', v='a budget, plus a constraint held back', mono=False),
   dict(t='kv', k='Why held back', v='because it is the one that cannot be negotiated', mono=False),
   dict(t='rule'),
   dict(t='sign', text='THE QUESTION THAT MOVED EACH BRIEF MOST:'),
   dict(t='para', text='"Who has to agree to this before it happens?" It moved briefs 2, 3 and '
     '4. It did nothing to brief 1, because the librarian had already asked it.')],
 callouts=[dict(at=0.10, text='A failed attempt is worth more than a requirement list'),
   dict(at=0.30, text='Four features, and not one sentence about what anybody is trying to do'),
   dict(at=0.52, text='A wish is a real brief. It just needs translating into a number'),
   dict(at=0.72, text='Held back to minute twenty-six, and it rules out three of four options'),
   dict(at=0.94, text='The question that works is the one about people, not about the thing')]),

"fig_b13_u04_p10_v12": dict(type='V12', height=900,
 title='Six years of a garden with two jobs',
 sub='Half the class sees the brief. Half sees the harvest. Rebuild it by speaking.',
 alt='An infographic across six years showing beds, yield, the kitchen taking produce and the '
     'two merged beds.',
 span=['year 1', 'year 8'], ticks=6,
 tick_labels=['yr 1', 'yr 3', 'yr 5', 'yr 6', 'yr 7', 'yr 8'],
 bands=[dict(name='What it was for', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.62}, label='a classroom. Specified, written down, agreed',
     colour='#2E6F5E'),
   dict(**{'from': 0.62, 'to': 0.80}, label='a classroom and a food source, by accident',
     colour='#D9A441'),
   dict(**{'from': 0.80, 'to': 1.0}, label='a classroom, written down again', colour='#2E6F5E')]),
  dict(name='Who took from it', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.56}, label='nobody - 94 kg composted or given away',
     colour='#9AA7AE'),
   dict(**{'from': 0.56, 'to': 0.80}, label='the campus kitchen, no decision anywhere',
     colour='#C86B2B')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.04, label='brief written: five requirements, none about yield', colour='#1F4E5F'),
   dict(at=0.58, label='kitchen starts taking. It goes on a menu board', colour='#C86B2B'),
   dict(at=0.70, label='"could you grow more of what people eat?"', colour='#A8372E'),
   dict(at=0.82, label='two merged beds built: 51 kg from two', colour='#2E6F5E'),
   dict(at=0.96, label='food-security grant declined, in one sentence', colour='#8C6A9E')]),
  dict(name='Yield, kg', type='line',
   points=[(0, 70), (0.3, 88), (0.56, 94), (0.8, 145), (0.9, 145), (1.0, 145)],
   end_label='145 kg'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.24, label='write down that yield was not a requirement'),
   dict(at=0.64, label='decide anything, at any point, about the kitchen'),
   dict(at=0.86, label='tell the chef what the garden was for, for two years'),
   dict(at=0.98, label='ask whether a third purpose would fit either')])]),

"fig_b13_u04_p11_v06": dict(type='V6', kind='bar', height=840,
 title='Yield and growing cycles, three options',
 sub='The same land, three ways, and the two columns do not move together.',
 alt='A bar chart comparing yield in kilograms, growing cycles taught and students with a bed '
     'for three garden options.',
 labels=['Classroom', 'Converted', 'Split 50/50', 'Classroom + 2 merged'],
 ymin=0, ymax=500, fmt='{:,.0f}',
 series=[dict(name='yield, kg', values=[94, 480, 287, 145], colour='#C86B2B'),
   dict(name='growing cycles x20', values=[240, 80, 240, 240], colour='#2E6F5E'),
   dict(name='students with a bed x10', values=[200, 0, 100, 200], colour='#1F4E5F')],
 note='Cycles and students are multiplied so that they fit the same axis as the kilograms. '
      'Nothing else has been adjusted.',
 warning='Converting the garden multiplies the yield by five and removes eight of the twelve '
         'growing cycles, which is the one thing the garden was specified to do.'),
}
