"""B1.3 Unit 5 - The Essay Nobody Heard - twelve figures, as data."""
FIGURES = {
"fig_b13_u05_p00_v01": dict(type='V1', height=840, storey_h=150,
 title='Tutorial room 1.07, the last Friday of term, 16.58',
 sub='Twelve things to find. Four are the story as it was planned. Four are the story as it '
     'came out.',
 alt='A university corridor and tutorial room with chairs in a circle, a mark sheet with a blank '
     'row, a noticeboard with a deadline and one person in the corridor.',
 sky='#DDE2E6', ground='#A3A6A6', ground_line=670,
 buildings=[dict(x=20, w=560, storeys=3, colour='#D1CDC3', cutaway=True,
     floor_labels=['tutorial 1.07, chairs in a circle',
                   'the corridor, one person in it',
                   'the library, where the gap is as long as you want'],
     label='Arts - tutorial rooms'),
   dict(x=680, w=400, storeys=3, colour='#C7C3B8', label='the office, and a deadline on Friday'),
   dict(x=1160, w=420, storeys=2, colour='#BEBAB0', label='the stairwell, where he timed it')],
 props=[dict(kind='tree', x=630, y=670, s=1.0), dict(kind='tree', x=1120, y=670, s=.9),
   dict(kind='hoarding', x=1040, y=670, s=.9),
   dict(kind='table', x=1290, y=670, s=1.3),
   dict(kind='box', x=1500, y=670, s=1.0),
   dict(kind='sign', x=880, y=670, s=.7, text='16:58'),
   dict(kind='sign', x=760, y=670, s=.7, text='4 s')],
 people=[dict(x=140, y=670, h=86, skin=3, cloth=0, hair='cap', arm='hold'),
   dict(x=270, y=670, h=86, skin=1, cloth=2, hair='bun', arm='point'),
   dict(x=390, y=670, h=86, skin=0, cloth=1, hair='long', arm='folded'),
   dict(x=960, y=670, h=86, skin=4, cloth=3, hair='short', arm='down'),
   dict(x=1380, y=670, h=86, skin=2, cloth=4, hair='grey', arm='hold')],
 names=[dict(x=140, t='Thanh, eleven sheets in a bag'),
   dict(x=270, t='Priya, a mark sheet with a blank row'),
   dict(x=390, t='Marguerite, four seconds in'),
   dict(x=960, t='an essay with a comment on page nine'),
   dict(x=1380, t='the handbook sentence, written in 2011'),
   dict(x=880, t='two minutes until the deadline'),
   dict(x=760, t='four seconds. He needed eleven'),
   dict(x=1290, t='a coffee cup with the name spelled wrong')],
 markers=[dict(x=140, y=550), dict(x=270, y=550), dict(x=390, y=550), dict(x=960, y=550),
   dict(x=1380, y=550), dict(x=880, y=604), dict(x=760, y=604), dict(x=1290, y=622),
   dict(x=1040, y=618), dict(x=1500, y=620), dict(x=630, y=608), dict(x=1120, y=608)]),

"fig_b13_u05_p01_v08": dict(type='V8', height=800,
 title='How a reveal is built',
 sub='Six nodes. The one at the far right was already in the listener\'s hand at node two.',
 alt='A network from a slow build through a planted detail and a withheld fact to the turn and '
     'the landing, with the surprise shown as a weaker path.',
 nodes={
  'bld': dict(x=170, y=230, short='1', name='The slow build', sub='and a wrong answer offered',
              colour='#1F4E5F'),
  'det': dict(x=170, y=570, short='2', name='The planted detail', sub='given plainly, as background',
              colour='#2E6F5E'),
  'wth': dict(x=540, y=400, short='3', name='What is withheld', sub='not the fact - the order',
              colour='#C86B2B'),
  'trn': dict(x=900, y=230, short='4', name='The turn', sub='and that is when', colour='#D9A441'),
  'rev': dict(x=1270, y=400, short='5', name='The reveal', sub='visible in hindsight, all of it',
              r=56, colour='#8C6A9E'),
  'sur': dict(x=900, y=600, short='6', name='A surprise', sub='new information, and it lands flat',
              r=50, colour='#A8372E')},
 edges=[dict(a='bld', b='wth', label='the reader is holding the wrong theory', sw=6),
   dict(a='det', b='wth', label='and the right one, without knowing it', sw=6),
   dict(a='wth', b='trn', label='held until it means something else', sw=6),
   dict(a='trn', b='rev', label='and the landing is short', sw=6),
   dict(a='wth', b='sur', label='nothing planted', sw=2, dash='6 6', colour='#A8372E'),
   dict(a='sur', b='rev', label='which the listener cannot re-read into the story', sw=2,
        dash='6 6', colour='#9AA7AE')]),

"fig_b13_u05_p02_v07": dict(type='V7', height=820,
 title='The office, Thursday, five to five',
 sub='One of them has to enter a number tomorrow. One of them wrote the sentence in 2011.',
 alt='A tutor and a senior lecturer in an office with a mark sheet between them, their speech '
     'shown as cleft sentences.',
 bg='#E8EAEC',
 set=[dict(kind='table', x=700, y=700, s=1.4), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=1, cloth=2, hair='bun', arm='point', facing='right',
   label='Priya', role='marks due Friday',
   says=['It was the criterion that failed, not the student.',
     'What I cannot do is mark him on something he was never given access to.']),
  dict(x=980, h=248, skin=2, cloth=4, hair='grey', arm='hold', facing='left',
   label='Dr Ahmadi', role='on the committee that owns the sentence',
   says=['The thing that worries me is not this mark. It is next year\'s.'])]),

"fig_b13_u05_p03_v09": dict(type='V9', kind='scope', height=540,
 title='One sentence, three ways to point at it',
 sub='The words do not move. The cleft decides which part the reader is to hold.',
 alt='A sentence shown with brackets marking the parts that an it-cleft, a wh-cleft and an '
     'all-cleft each put in the spotlight.',
 words=['The', 'criterion', 'failed', 'the', 'student'],
 focus=[1, 2],
 brackets=[dict(**{'from': 1, 'to': 1}, lane=0, label='it was the criterion that failed',
     colour='#C86B2B'),
   dict(**{'from': 2, 'to': 4}, lane=0, label='what the criterion did was fail the student',
     colour='#2E6F5E'),
   dict(**{'from': 0, 'to': 4}, lane=1,
     label='flat: no spotlight at all, and the reader chooses - which is the risk',
     colour='#9AA7AE')]),

"fig_b13_u05_p03_v11": dict(type='V11', height=720,
 title='A cleft with only one half',
 alt='Two panels comparing it was failed the criterion with it was the criterion that failed.',
 wrong=dict(sentence='It was failed the criterion.',
            boundary=0.40, boundary_label='it was - the spotlight opens',
            event=0.58, event_label='and a verb walks into it',
            why='A cleft has two parts: it was plus the thing in the spotlight, then a relative '
                'clause carrying everything else. A verb cannot stand in the spotlight slot, so '
                'the sentence opens a frame and then puts the wrong word class in it, and the '
                'relative clause never arrives.'),
 right=dict(sentence='It was the criterion that failed.',
            boundary=0.44, boundary_label='it was the criterion - the spotlight is filled',
            event=0.72, event_label='and that failed closes the frame',
            why='A noun phrase fills the slot and the that clause carries the verb. To spotlight '
                'the action instead, the frame changes: what the criterion did was fail the '
                'student. Each frame takes one kind of thing, and that is the only rule here.'),
 misconception='Learners hear a cleft as an emphasising phrase that can be dropped in front of '
               'anything. It is a two-part structure, and the second part is not optional: if '
               'nothing follows the spotlit phrase, there is no sentence yet.'),

"fig_b13_u05_p04_v04": dict(type='V4', height=760,
 title='The same four seconds, told two ways',
 sub='Learner A has the first half. Learner B has the last line.',
 alt='Two panels compared: a story that plants a detail early and one that explains everything '
     'at the end.',
 differences=7, prompt='Where does the second version tell the reader what to feel, and what '
                       'does the first one do instead?',
 left=dict(label='planted early, used late', art=[
   dict(kind='block', x=140, y=140, w=230, bh=26, colour='#2E6F5E'),
   dict(kind='block', x=140, y=96, w=70, bh=26, colour='#D9A441'),
   dict(kind='person', x=400, y=0, h=106, skin=3, cloth=0),
   dict(kind='label', x=300, y=220, text='four seconds, given as background in line 3',
        colour='#2E6F5E')]),
 right=dict(label='explained at the end', art=[
   dict(kind='block', x=140, y=140, w=230, bh=26, colour='#9AA7AE'),
   dict(kind='block', x=140, y=96, w=230, bh=26, colour='#A8372E'),
   dict(kind='gap', x=400, y=16, w=50, bh=84),
   dict(kind='label', x=300, y=220, text='"which was unfortunate, given that he was capable"',
        colour='#A8372E')])),

"fig_b13_u05_p05_v05": dict(type='V5', height=1080,
 title='The mark sheet and the handbook page',
 sub='One of them was written this week. One of them was written in 2011.',
 alt='A participation mark sheet with one row left blank beside the handbook page defining the '
     'criterion, with an audit note.',
 rows=[dict(t='org', text='FACULTY OF ARTS  -  UNIT ARTS 2104  -  PARTICIPATION, 15 %'),
   dict(t='head', text='HANDBOOK, SECTION 4.3  -  LAST AMENDED 2011'),
   dict(t='para', text='"Participation (15%). Students are assessed on the extent to which they '
     'contribute regularly to seminar discussion."'),
   dict(t='rule'),
   dict(t='head', text='MARK SHEET, WEEK 12'),
   dict(t='grid', cols=['STUDENT', 'SPOKE', 'ESSAY', 'PARTICIPATION'],
     data=[['Marguerite', '11 of 11 weeks', '74', '14'],
           ['Aoife', '9 of 11', '71', '13'],
           ['Dilan', '7 of 11', '66', '11'],
           ['Nia', '5 of 11', '69', '9'],
           ['Sam', '3 of 11', '58', '6'],
           ['Thanh', '2 of 11', '84', '4   13']]),
   dict(t='para', text='Every row but one is a straight line from the left column to the right. '
     'One row has two numbers in it and the first one is crossed out.'),
   dict(t='rule'),
   dict(t='head', text='AUDIT NOTE, APPENDED TO THE MARK SHEET'),
   dict(t='kv', k='Marks overridden, faculty, this year', v='7 of 2,140', mono=True),
   dict(t='kv', k='Grounds given', v='5 medical, 2 "format"', mono=False),
   dict(t='kv', k='Overridden marks held on file', v='3 years', mono=True),
   dict(t='kv', k='Overrides queried at audit', v='0', mono=True),
   dict(t='rule'),
   dict(t='sign', text='WHAT IS NOT ON THE SHEET:'),
   dict(t='para', text='Eleven sheets of A4, one for each week, each carrying an answer to every '
     'question asked in that session. They were on the tutor\'s desk by Friday and there is no '
     'column for them.')],
 callouts=[dict(at=0.10, text='Written in 2011. The verb is contributes, and that is the trouble'),
   dict(at=0.30, text='Six rows where the two columns agree, and one where they do not'),
   dict(at=0.46, text='The highest essay mark in the group, and the lowest participation mark'),
   dict(at=0.52, text='Two numbers, one crossed out. Somebody changed their mind'),
   dict(at=0.74, text='Seven overrides in two thousand, and none of them queried'),
   dict(at=0.94, text='There is no column for it, which is the whole decision')]),

"fig_b13_u05_p07_v10": dict(type='V10', kind='stress', height=640,
 title='The loudest word, and what it chooses',
 sub='Four versions of four words. Only the stress tells them apart.',
 alt='Four phrases marked for stress showing how nuclear stress placement changes which part of '
     'a sentence is the news.',
 items=[dict(syllables=['the', 'cri', 'TER', 'i', 'on', 'failed'], strong=[2],
     note='the criterion, not the student'),
   dict(syllables=['the', 'cri', 'ter', 'i', 'on', 'FAILED'], strong=[5],
     note='it failed - it did not merely apply badly'),
   dict(syllables=['THE', 'cri', 'ter', 'i', 'on', 'failed'], strong=[0],
     note='that one, the one we have been arguing about'),
   dict(syllables=['ALL', 'I', 'did', 'was', 'ask'], strong=[0],
     note='and nothing else - a defence')]),

"fig_b13_u05_p08_v02": dict(type='V2', height=820,
 title='A story with a reveal, in section',
 sub='Four layers. The reader has the bottom one before they know they need it.',
 alt='A cutaway of a written story in four layers from the slow build and the planted detail to '
     'the turn and the landing.',
 floors=[dict(was='the slow build', now='And a wrong explanation, offered on purpose', year='',
     fill='#E4ECEF'),
   dict(was='the planted detail', now='Four seconds. Given plainly, as if it were background',
     year='', fill='#EFE2DD'),
   dict(was='the turn', now='And that is when - three words, and then a short sentence',
     year='', fill='#F6F0E4'),
   dict(was='the landing', now='Shorter than the sentence before it. Then stop', year='',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='A wrong theory in the reader\'s hand is worth more than no theory'),
   dict(at=0.38, text='Plainly. The moment it is underlined it stops being a plant'),
   dict(at=0.62, text='Mark the turn out loud. The reader will not find it alone'),
   dict(at=0.88, text='If the last sentence is the longest, nothing lands')]),

"fig_b13_u05_p09_v05": dict(type='V5', height=1060,
 title='Four readers, forty pages, one chapter',
 sub='Same text, same week, four different jobs - and only one of them was the job set.',
 alt='A record of four students reading the same chapter at four speeds, with what each one '
     'retained and what the task actually required.',
 rows=[dict(t='org', text='STUDY FILE  -  READING AT SPEED  -  ONE CHAPTER, FOUR READERS'),
   dict(t='grid', cols=['READER', 'TIME', 'METHOD'],
     data=[['Aoife', '2 min', 'survey - contents, headings, first and last paragraph'],
           ['Dilan', '11 min', 'skim - every first sentence, two figures'],
           ['Nia', '46 min', 'read - start to finish, once, no notes'],
           ['Sam', '2 h 20', 'study - line by line, with a pen, from page one']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH COULD DO AFTERWARDS'),
   dict(t='grid', cols=['READER', 'STATE THE CLAIM', 'FIND A PAGE', 'ARGUE WITH IT'],
     data=[['Aoife', 'yes', 'yes', 'no'], ['Dilan', 'yes', 'yes', 'partly'],
           ['Nia', 'yes', 'no', 'partly'], ['Sam', 'yes', 'yes', 'pages 1-14 only']]),
   dict(t='para', text='Sam ran out of time on page fourteen of forty and could argue with '
     'nothing after it. Aoife spent two minutes and could not argue with any of it, which was '
     'not what the seminar needed either.'),
   dict(t='rule'),
   dict(t='head', text='WHAT THE SEMINAR ACTUALLY REQUIRED'),
   dict(t='kv', k='The task set', v='"read chapter 4"', mono=False),
   dict(t='kv', k='What was asked in the room', v='one question, on pages 28-31', mono=False),
   dict(t='kv', k='Reading job that would have served it', v='skim, then read 28-31',
        mono=False),
   dict(t='kv', k='Students who did that', v='0 of 11', mono=True),
   dict(t='rule'),
   dict(t='sign', text='THE STUDENT WHO DID NOT READ IT AT ALL:'),
   dict(t='para', text='"I read the introduction and the conclusion and the figure captions. '
     'Eight minutes. I knew what it claimed and I knew I disagreed. I could not have told you '
     'a single thing from the middle, and nobody asked."')],
 callouts=[dict(at=0.14, text='Two minutes against two hours and twenty, on the same forty pages'),
   dict(at=0.42, text='The slowest reader could argue with the least of it'),
   dict(at=0.56, text='Page fourteen of forty, and the question was on page twenty-eight'),
   dict(at=0.76, text='Read chapter 4 is not a job. It is four jobs with one name'),
   dict(at=0.86, text='None of the eleven did the one the task needed'),
   dict(at=0.95, text='Eight minutes, and it was enough for the question that came')]),

"fig_b13_u05_p10_v12": dict(type='V12', height=900,
 title='Eleven weeks, and two years afterwards',
 sub='Half the class sees the story. Half sees the mark sheet. Rebuild it by speaking.',
 alt='An infographic from week one to two years later showing times spoken, sheets written, the '
     'mark decision and the handbook change.',
 span=['week 1', '+2 years'], ticks=6,
 tick_labels=['wk 1', 'wk 5', 'wk 9', 'wk 12', '+1 yr', '+2 yr'],
 bands=[dict(name='What the rule said', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.88}, label='contributes regularly to seminar discussion - 2011',
     colour='#9AA7AE'),
   dict(**{'from': 0.88, 'to': 1.0}, label='in a form agreed with the tutor', colour='#2E6F5E')]),
  dict(name='Thanh', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.62}, label='eleven sheets written, none submitted',
     colour='#C86B2B'),
   dict(**{'from': 0.62, 'to': 0.70}, label='left on a desk, in silence', colour='#D9A441')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.06, label='week 2: he times the gap. Four seconds', colour='#1F4E5F'),
   dict(at=0.40, label='week 9: eleven seconds of silence, and he misses it by half',
     colour='#A8372E'),
   dict(at=0.62, label='the comment: why have I never heard any of this?', colour='#8C6A9E'),
   dict(at=0.70, label='12 of 15, with a note. Not audited, not queried', colour='#2E6F5E'),
   dict(at=0.80, label='cited by a tutor in another department, heard at a lunch',
     colour='#D9A441')]),
  dict(name='Times spoken, cumulative', type='line',
   points=[(0, 0), (0.2, 1), (0.4, 1), (0.62, 2), (0.8, 2), (1.0, 2)], end_label='2'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.26, label='ask why the quietest student wrote the most'),
   dict(at=0.52, label='leave eleven seconds of silence on purpose, ever again'),
   dict(at=0.76, label='write the precedent anywhere a tutor would find it'),
   dict(at=0.98, label='tell him the sentence had been changed')])]),

"fig_b13_u05_p11_v06": dict(type='V6', kind='bar', height=840,
 title='Essay mark against participation mark, eleven students',
 sub='Two columns that agree for ten people.',
 alt='A bar chart of essay marks and participation marks for eleven students, showing one '
     'student where the two diverge sharply.',
 labels=['Marguerite', 'Aoife', 'Dilan', 'Nia', 'Sam', 'Thanh'],
 ymin=0, ymax=100, fmt='{:,.0f}',
 series=[dict(name='essay mark', values=[74, 71, 66, 69, 58, 84], colour='#1F4E5F'),
   dict(name='participation x6', values=[84, 78, 66, 54, 36, 24], colour='#C86B2B')],
 note='Participation is multiplied by six so that it fits the same axis as the essay mark. '
      'Nothing else has been adjusted.',
 warning='For five of the six the two columns move together. For the sixth they cross, and the '
         'crossing is the only thing on this chart that the criterion cannot describe.'),
}
