"""B1.3 Unit 6 - The Clause on Page Nine - twelve figures, as data."""
FIGURES = {
"fig_b13_u06_p00_v01": dict(type='V1', height=840, storey_h=152,
 title='The day the letters went up',
 sub='Twelve things to find. Four are what the agreement says. Four are what people think it says.',
 alt='A campus with a new research wing under scaffolding, letters of a sponsor name going up, a '
     'photographer, a press release on a noticeboard and a sign still showing the old name.',
 sky='#DEE4E7', ground='#A5A8A5', ground_line=674,
 buildings=[dict(x=20, w=520, storeys=3, colour='#D3CFC5', label='the new wing, a name going up'),
   dict(x=620, w=400, storeys=3, colour='#C8C4B9', cutaway=True,
     floor_labels=['the meeting room, a long table',
                   'communications, two days to write it',
                   'the lobby, a model under glass'],
     label='Administration'),
   dict(x=1120, w=460, storeys=2, colour='#BFBBB1', label='the old labs, sign unchanged')],
 props=[dict(kind='tree', x=580, y=674, s=1.0), dict(kind='tree', x=1070, y=674, s=.9),
   dict(kind='hoarding', x=300, y=674, s=1.1),
   dict(kind='table', x=1300, y=674, s=1.3),
   dict(kind='box', x=1480, y=674, s=1.1),
   dict(kind='sign', x=120, y=674, s=.7, text='$4 M'),
   dict(kind='sign', x=1220, y=674, s=.7, text='9.4')],
 people=[dict(x=200, y=674, h=86, skin=3, cloth=0, hair='cap', arm='point'),
   dict(x=430, y=674, h=86, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=760, y=674, h=86, skin=0, cloth=1, hair='long', arm='folded'),
   dict(x=900, y=674, h=86, skin=1, cloth=2, hair='bun', arm='hold'),
   dict(x=1400, y=674, h=86, skin=2, cloth=4, hair='grey', arm='down')],
 names=[dict(x=200, t='two workers on a scaffold, fitting letters'),
   dict(x=430, t='a photographer, setting up'),
   dict(x=760, t='the lawyer, who read all nine pages'),
   dict(x=900, t='communications, two days'),
   dict(x=1400, t='a researcher carrying a box out'),
   dict(x=120, t='four million, fifteen years'),
   dict(x=1220, t='clause 9.4, thirty days'),
   dict(x=300, t='the press release, on a noticeboard')],
 markers=[dict(x=200, y=556), dict(x=430, y=556), dict(x=760, y=556), dict(x=900, y=556),
   dict(x=1400, y=556), dict(x=120, y=610), dict(x=1220, y=610), dict(x=300, y=622),
   dict(x=1300, y=626), dict(x=1480, y=624), dict(x=580, y=612), dict(x=1070, y=612)]),

"fig_b13_u06_p01_v08": dict(type='V8', height=800,
 title='Where a claim loses its owner',
 sub='Six nodes. The claim is the same at every one of them, and only one still has a name on it.',
 alt='A network from a claim made in a room through minutes and a press release to public '
     'understanding, with the owner dropping away at each step.',
 nodes={
  'rom': dict(x=170, y=230, short='1', name='In the room', sub='somebody says it, out loud',
              colour='#2E6F5E'),
  'doc': dict(x=170, y=570, short='2', name='The clause', sub='written, signed, dated',
              colour='#1F4E5F'),
  'min': dict(x=540, y=400, short='3', name='The minutes', sub='a name, if anyone wrote it down',
              colour='#D9A441'),
  'rel': dict(x=900, y=230, short='4', name='The release', sub='standard arrangements',
              colour='#C86B2B'),
  'pub': dict(x=1270, y=400, short='5', name='What people think', sub='no owner left at all',
              r=56, colour='#A8372E'),
  'arc': dict(x=900, y=600, short='6', name='The archive', sub='public, three clicks away',
              r=50, colour='#9AA7AE')},
 edges=[dict(a='rom', b='min', label='attached to a person, with a verb', sw=6),
   dict(a='doc', b='min', label='and to a clause number', sw=6),
   dict(a='min', b='rel', label='one adjective replaces both', sw=6),
   dict(a='rel', b='pub', label='heard as normal, which was the point', sw=6),
   dict(a='doc', b='arc', label='published the whole time', sw=2, dash='6 6', colour='#9AA7AE'),
   dict(a='arc', b='pub', label='and nobody looked for eighteen months', sw=2, dash='6 6',
        colour='#9AA7AE')]),

"fig_b13_u06_p02_v07": dict(type='V7', height=820,
 title='The meeting about page nine',
 sub='One of them wrote the clause. One of them read all nine pages.',
 alt='A company representative and a university lawyer across a meeting table, their speech '
     'shown as reported claims with their patterns.',
 bg='#E7EAEC',
 set=[dict(kind='table', x=700, y=700, s=1.6), dict(kind='doc', x=700, y=624)],
 people=[dict(x=470, h=250, skin=0, cloth=1, hair='long', arm='point', facing='right',
   label='the lawyer', role='read all nine pages',
   says=['She accused them of writing a veto and calling it a courtesy.',
     'She warned them against describing it as standard.']),
  dict(x=980, h=248, skin=4, cloth=3, hair='short', arm='hold', facing='left',
   label='the sponsor', role='four million, fifteen years',
   says=['He insisted on thirty days and denied that thirty days was a veto.'])]),

"fig_b13_u06_p03_v09": dict(type='V9', kind='branch', height=760,
 title='The preposition is part of the verb',
 sub='There is no rule behind this. Learn the verb with what follows it, or you have not '
     'learned the verb.',
 alt='A branching diagram of reporting verb patterns, each branch showing the preposition and an '
     'example sentence.',
 root='she reported it',
 branches=[dict(label='of + -ing', colour='#A8372E',
     example='accuse somebody of writing it · remind somebody of the date'),
   dict(label='to + infinitive', colour='#1F4E5F',
     example='persuade / urge / advise somebody to wait'),
   dict(label='for + -ing or noun', colour='#C86B2B',
     example='blame somebody for the delay'),
   dict(label='on + noun', colour='#D9A441',
     example='congratulate somebody on the gift · insist on seeing it'),
   dict(label='against + -ing', colour='#2E6F5E',
     example='warn somebody against saying it'),
   dict(label='bare -ing, no object', colour='#8C6A9E',
     example='deny writing it · admit writing it')]),

"fig_b13_u06_p03_v11": dict(type='V11', height=720,
 title='A verb with somebody else\'s preposition',
 alt='Two panels comparing accused them to write a veto with accused them of writing a veto.',
 wrong=dict(sentence='They accused them to write a veto.',
            boundary=0.48, boundary_label='accused them - the object lands',
            event=0.62, event_label='and to write arrives, which accuse cannot take',
            why='To plus infinitive after a verb of reporting means the speaker wanted the other '
                'person to do something: persuaded them to write, urged them to write. Accuse '
                'says the opposite - that they already did it. The pattern contradicts the verb, '
                'so the sentence reads as if somebody asked them to write a veto.'),
 right=dict(sentence='They accused them of writing a veto.',
            boundary=0.48, boundary_label='accused them - the object lands',
            event=0.70, event_label='and of writing names a completed act',
            why='Of plus -ing points backwards at something already done, which is what an '
                'accusation is about. The same -ing after a different preposition changes the '
                'claim again: blamed them for writing it says they did it and it caused harm.'),
 misconception='Learners treat the preposition as a small connecting word they can choose by '
               'ear. It is part of the verb\'s meaning: of looks back at a completed act, to '
               'looks forward at a wanted one, against points away from one. Change it and you '
               'change who did what.'),

"fig_b13_u06_p04_v04": dict(type='V4', height=760,
 title='The minutes, and the corridor',
 sub='Learner A has what was minuted. Learner B has what two people said on the way out.',
 alt='Two panels compared: formal meeting minutes and an informal corridor conversation, with '
     'one claim appearing in only one of them.',
 differences=7, prompt='Which claim appears in one and not the other, and which version would '
                       'you put in a report?',
 left=dict(label='the minutes, circulated', art=[
   dict(kind='block', x=140, y=20, w=230, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=140, y=58, w=200, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=140, y=96, w=215, bh=22, colour='#9AA7AE'),
   dict(kind='label', x=300, y=220, text='"a frank exchange of views"', colour='#9AA7AE')]),
 right=dict(label='the corridor, ninety seconds', art=[
   dict(kind='person', x=160, y=0, h=108, skin=0, cloth=1),
   dict(kind='person', x=270, y=0, h=106, skin=4, cloth=3),
   dict(kind='label', x=300, y=220, text='"we are not going to say that"', colour='#A8372E')])),

"fig_b13_u06_p05_v05": dict(type='V5', height=1080,
 title='Clause 9.4 and the sentence that covered it',
 sub='Nine pages, one paragraph, and eleven words that were not written.',
 alt='The text of a sponsorship review clause beside the press release sentence describing it, '
     'with four comparable agreements and a handwritten amendment.',
 rows=[dict(t='org', text='RESEARCH PARTNERSHIP AGREEMENT  -  PAGE 9 OF 9  -  EXTRACT'),
   dict(t='head', text='CLAUSE 9.4  -  PUBLICATION'),
   dict(t='para', text='"The Partner shall be given thirty (30) days\' sight of any publication '
     'arising from work undertaken in the Facility, and may request amendments. The University '
     'shall consider any such request in good faith."'),
   dict(t='kv', k='The two verbs', v='request · consider', mono=False),
   dict(t='kv', k='Not in the clause', v='require · approve · withhold', mono=False),
   dict(t='rule'),
   dict(t='head', text='PRESS RELEASE, PARAGRAPH 4'),
   dict(t='para', text='"The partnership includes standard arrangements for the review of '
     'research outputs prior to publication."'),
   dict(t='kv', k='Words in the sentence', v='16', mono=True),
   dict(t='kv', k='Words it would take to state the clause', v='11', mono=True),
   dict(t='kv', k='False statements in it', v='0', mono=True),
   dict(t='rule'),
   dict(t='head', text='FOUR COMPARABLE AGREEMENTS, CHECKED'),
   dict(t='grid', cols=['PARTNER', 'REVIEW CLAUSE', 'PERIOD'],
     data=[['A, engineering', 'none', '-'], ['B, medicine', 'none', '-'],
           ['C, computing', 'none', '-'], ['D, chemistry', 'notification only', '14 days']]),
   dict(t='para', text='One of four has anything at all, and it is notification rather than '
     'review. Standard means of a known type. It is heard as normal.'),
   dict(t='rule'),
   dict(t='sign', text='AMENDED IN HANDWRITING, PAGE 9, AND INITIALLED BY BOTH SIDES:'),
   dict(t='para', text='"shall consider" - struck through, "shall consider in good faith" '
     'written above it. Initialled 14/3. Nobody has ever been able to say which side asked '
     'for it.')],
 callouts=[dict(at=0.12, text='Request and consider. Neither of them is approve'),
   dict(at=0.22, text='And the three words that are not in it are the three people assume are'),
   dict(at=0.40, text='Sixteen words, and every one of them true'),
   dict(at=0.46, text='Eleven words would have stated the clause. They were not written'),
   dict(at=0.70, text='One of four, and that one is notification, not review'),
   dict(at=0.94, text='Four words added by hand, and they are the only softening in nine pages')]),

"fig_b13_u06_p07_v10": dict(type='V10', kind='stress', height=640,
 title='Stress the verb, and the report is the news',
 sub='Four versions. The words do not change and the story does.',
 alt='Four reported sentences marked for stress, showing how stressing the reporting verb, the '
     'object or the complement changes what is new.',
 items=[dict(syllables=['she', 'ac', 'CUSED', 'them', 'of', 'writ', 'ing', 'it'], strong=[2],
     note='an accusation, and that is the news'),
   dict(syllables=['she', 'ac', 'cused', 'THEM', 'of', 'writ', 'ing', 'it'], strong=[3],
     note='those people, not the ones you assumed'),
   dict(syllables=['he', 'ad', 'MIT', 'ted', 'writ', 'ing', 'it'], strong=[2],
     note='he admitted it - a surprise'),
   dict(syllables=['he', 'ad', 'mit', 'ted', 'WRIT', 'ing', 'it'], strong=[4],
     note='writing it, not approving or circulating it')]),

"fig_b13_u06_p08_v02": dict(type='V2', height=820,
 title='A report of a meeting, in section',
 sub='Four layers. Every claim in the top two has a name on it.',
 alt='A cutaway of a meeting report in four layers from the claims and the counter-claims to the '
     'sticking point and the silences.',
 floors=[dict(was='the claims', now='Each with a named owner and the verb\'s own preposition',
     year='', fill='#E4ECEF'),
   dict(was='the counter-claims', now='Same treatment, same precision, no softening',
     year='', fill='#EFE2DD'),
   dict(was='the sticking point', now='One word: request, not suggest. Not "publication"',
     year='', fill='#F6F0E4'),
   dict(was='what was not said', now='The comparable agreements were in the room, in a folder',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='A claim with no owner is the most dangerous line in a document'),
   dict(at=0.38, text='If one side is reported more precisely, the report has taken a side'),
   dict(at=0.62, text='They disagreed about publication is not a sticking point. It is a topic'),
   dict(at=0.88, text='A silence is reportable, and it is often the only thing that is')]),

"fig_b13_u06_p09_v05": dict(type='V5', height=1060,
 title='The same four seconds, four conversations',
 sub='A pause does not mean anything by itself. It means something against a local average.',
 alt='Four conversations with the same four-second pause annotated for whether it was '
     'comfortable, filled, or taken as a turn.',
 rows=[dict(t='org', text='CULTURE FILE  -  SILENCE, INTERRUPTION AND TURN-TAKING'),
   dict(t='grid', cols=['CONVERSATION', 'THE PAUSE', 'WHAT HAPPENED'],
     data=[['A, two friends', '4.0 s', 'nobody noticed. Neither mentioned it afterwards'],
           ['B, a job interview', '4.0 s', 'the interviewer filled it at 1.8 s'],
           ['C, a seminar', '4.0 s', 'three people started at once at 2.4 s'],
           ['D, a family kitchen', 'none at all', 'constant overlap, nobody offended']]),
   dict(t='para', text='Conversation D has no gaps. Every turn begins before the previous one '
     'ends, and all four speakers describe it afterwards as a good conversation.'),
   dict(t='rule'),
   dict(t='head', text='THREE WAYS A TURN CAN END'),
   dict(t='kv', k='A gap', v='stop, a beat, the next begins', mono=False),
   dict(t='kv', k='An overlap', v='the next begins early, as agreement', mono=False),
   dict(t='kv', k='A competitive interruption', v='the next begins early, to take the floor',
        mono=False),
   dict(t='para', text='The second and the third look identical on a recording. What separates '
     'them is what the second speaker does with the floor once they have it.'),
   dict(t='rule'),
   dict(t='head', text='REPORTED AVERAGE GAP BETWEEN TURNS'),
   dict(t='grid', cols=['SETTING', 'TYPICAL GAP'],
     data=[['much of northern Europe', 'about 0.2 s'],
           ['some conversational cultures', 'noticeably longer'],
           ['others again', 'longer still, and unremarked']]),
   dict(t='rule'),
   dict(t='sign', text='THE ONLY RULE THAT TRAVELS:'),
   dict(t='para', text='"A pause longer than your own average feels like a problem, and you '
     'will start talking to fix a problem that is not there."')],
 callouts=[dict(at=0.14, text='The same four seconds. Nobody noticed it once'),
   dict(at=0.20, text='Filled at 1.8 - less than half of it, and it read as a failure'),
   dict(at=0.34, text='No gaps at all, and every speaker calls it a good conversation'),
   dict(at=0.56, text='Identical on a recording. Only what follows separates them'),
   dict(at=0.80, text='The number is local. What it means is not'),
   dict(at=0.94, text='Whose silence have you filled this week?')]),

"fig_b13_u06_p10_v12": dict(type='V12', height=900,
 title='Four million dollars, eighteen months, four days',
 sub='Half the class sees the clause. Half sees the release. Rebuild it by speaking.',
 alt='An infographic from the signing to the second renewal showing the clause, the release, the '
     'discovery and the one request made.',
 span=['signing', '+18 years'], ticks=6,
 tick_labels=['sign', '+18 mo', '+3 yr', 'the request', '+5 yr', 'renewal'],
 bands=[dict(name='Where the clause was', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.26}, label='page 9 of 9, public, three clicks away',
     colour='#9AA7AE'),
   dict(**{'from': 0.26, 'to': 1.0}, label='front page of the wing\'s website, in full',
     colour='#2E6F5E')]),
  dict(name='Requests made under it', type='bars', items=[
   dict(**{'from': 0.26, 'to': 0.56}, label='none, for two years and eleven months',
     colour='#9AA7AE'),
   dict(**{'from': 0.56, 'to': 0.62}, label='one - refused, published', colour='#A8372E'),
   dict(**{'from': 0.62, 'to': 1.0}, label='none since', colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.03, label='release: "standard arrangements"', colour='#C86B2B'),
   dict(at=0.24, label='a researcher finds 9.4 and calls it hiding', colour='#A8372E'),
   dict(at=0.30, label='signed and published, with a requests page', colour='#1F4E5F'),
   dict(at=0.58, label='one sentence asked for. Refused in four days', colour='#D9A441'),
   dict(at=0.96, label='renewed for fifteen more years', colour='#8C6A9E')]),
  dict(name='Papers blocked', type='line',
   points=[(0, 0), (0.26, 0), (0.56, 0), (0.62, 0), (0.8, 0), (1.0, 0)], end_label='0'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.12, label='write eleven words into the press release'),
   dict(at=0.42, label='use the clause, in three years, once'),
   dict(at=0.70, label='ask the sponsor why they stopped asking'),
   dict(at=0.98, label='say in public which side wrote in good faith by hand')])]),

"fig_b13_u06_p11_v06": dict(type='V6', kind='bar', height=840,
 title='Review clauses in twelve comparable agreements',
 sub='How many have one, how long it runs, and what was ever requested under it.',
 alt='A bar chart of twelve comparable research agreements showing review periods in days and '
     'the number of amendment requests made.',
 labels=['None at all', 'Notify only', '14-day review', '30-day review', 'Longer'],
 ymin=0, ymax=12, fmt='{:,.0f}',
 series=[dict(name='agreements', values=[7, 2, 1, 2, 0], colour='#1F4E5F'),
   dict(name='requests ever made', values=[0, 0, 0, 1, 0], colour='#A8372E')],
 note='Twelve agreements across four faculties, over eleven years. One amendment has ever been '
      'requested under any of them.',
 warning='Seven of twelve have no review clause at all, which is what makes standard the wrong '
         'word - and one request in eleven years is what makes the clause harmless once it is '
         'public.'),
}
