"""B1.3 Unit 7 - Somebody Told Somebody - twelve figures, as data."""
FIGURES = {
"fig_b13_u07_p00_v01": dict(type='V1', height=840, storey_h=150,
 title='The third week, Tuesday, 11.10',
 sub='Twelve things to find. Four are the claim. Four are the machinery that should have '
     'handled it.',
 alt='A department building with a photocopier conversation, a pigeonhole with one envelope, a '
     'door with the nameplate removed and a procedure pinned to a noticeboard.',
 sky='#DCE1E4', ground='#A3A6A4', ground_line=672,
 buildings=[dict(x=20, w=560, storeys=3, colour='#D0CCC2', cutaway=True,
     floor_labels=['the office, blind down at eleven',
                   'the corridor, people not looking',
                   'the photocopier, two people talking'],
     label='the department'),
   dict(x=680, w=400, storeys=3, colour='#C6C2B7', label='HR, and a Stage 1 form'),
   dict(x=1180, w=400, storeys=2, colour='#BDB9AF', label='the registry, four lines long')],
 props=[dict(kind='tree', x=630, y=672, s=1.0), dict(kind='tree', x=1130, y=672, s=.9),
   dict(kind='hoarding', x=1090, y=672, s=.9),
   dict(kind='table', x=900, y=672, s=1.3),
   dict(kind='box', x=1500, y=672, s=1.0),
   dict(kind='sign', x=760, y=672, s=.7, text='STG 1'),
   dict(kind='sign', x=1000, y=672, s=.7, text='3 wks')],
 people=[dict(x=140, y=672, h=86, skin=0, cloth=1, hair='long', arm='point'),
   dict(x=265, y=672, h=86, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=400, y=672, h=86, skin=1, cloth=2, hair='bun', arm='folded'),
   dict(x=1280, y=672, h=86, skin=3, cloth=0, hair='cap', arm='down'),
   dict(x=1420, y=672, h=86, skin=2, cloth=4, hair='grey', arm='hold')],
 names=[dict(x=140, t='two at the photocopier, third week'),
   dict(x=265, t='the person it is about, told by a student'),
   dict(x=400, t='the head of department'),
   dict(x=1280, t='a printed email, one name blacked out'),
   dict(x=1420, t='the registry clerk'),
   dict(x=760, t='Concern - Stage 1, never opened'),
   dict(x=1000, t='three weeks, no complaint'),
   dict(x=900, t='a timetable with one slot greyed out')],
 markers=[dict(x=140, y=552), dict(x=265, y=552), dict(x=400, y=552), dict(x=1280, y=552),
   dict(x=1420, y=552), dict(x=760, y=606), dict(x=1000, y=606), dict(x=900, y=620),
   dict(x=1090, y=618), dict(x=1500, y=620), dict(x=630, y=610), dict(x=1130, y=610)]),

"fig_b13_u07_p01_v08": dict(type='V8', height=800,
 title='A claim with nobody holding it',
 sub='Six nodes. The one in the middle is the only one anybody could act on, and it is empty.',
 alt='A network from something said at a photocopier through repetition and belief, with the '
     'complaint and the record shown as empty nodes nothing reaches.',
 nodes={
  'sai': dict(x=170, y=230, short='1', name='Somebody said it', sub='first-hand, once, to one person',
              colour='#D9A441'),
  'rep': dict(x=170, y=570, short='2', name='Repeated', sub='and the source drops off',
              colour='#C86B2B'),
  'bel': dict(x=540, y=400, short='3', name='Widely believed', sub='two hundred separate conversations',
              colour='#A8372E'),
  'cmp': dict(x=900, y=600, short='4', name='A complaint', sub='nobody has made one',
              r=50, colour='#9AA7AE'),
  'rec': dict(x=900, y=230, short='5', name='The record', sub='four lines, and his name is not on it',
              colour='#1F4E5F'),
  'hrm': dict(x=1270, y=400, short='6', name='The harm', sub='a semester, already gone',
              r=56, colour='#8C6A9E')},
 edges=[dict(a='sai', b='bel', label='four people, then forty', sw=6),
   dict(a='rep', b='bel', label='and by now nobody heard it first-hand', sw=6),
   dict(a='bel', b='hrm', label='a timetable is quietly rearranged', sw=6),
   dict(a='bel', b='cmp', label='which nothing ever becomes', sw=2, dash='6 6', colour='#9AA7AE'),
   dict(a='cmp', b='rec', label='so nothing reaches the record either', sw=2, dash='6 6',
        colour='#9AA7AE'),
   dict(a='rec', b='hrm', label='and the record cannot clear what it never held', sw=2,
        dash='6 6', colour='#9AA7AE')]),

"fig_b13_u07_p02_v07": dict(type='V7', height=820,
 title='The head of department, week three',
 sub='One of them has heard three versions. One of them has heard one, from a student.',
 alt='A head of department and a colleague in a corridor, their speech shown as passive '
     'reporting structures.',
 bg='#E7EAEC',
 set=[dict(kind='table', x=700, y=700, s=1.4), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=1, cloth=2, hair='bun', arm='point', facing='right',
   label='the head of department', role='three weeks, no complaint',
   says=['It is said that he was asked to leave his last post.',
     'The claim is understood to have originated in a different department.']),
  dict(x=980, h=248, skin=4, cloth=3, hair='short', arm='folded', facing='left',
   label='a colleague', role='heard one version, once',
   says=['He is thought to have left for family reasons. None of which has been established.'])]),

"fig_b13_u07_p03_v09": dict(type='V9', kind='mirror', height=680,
 title='Where the people who say it go',
 sub='The same claim, twice. In the second one nobody is left to ask.',
 alt='Two sentence diagrams comparing people say he was asked to leave with he is said to have '
     'been asked to leave, with the claimers shown as a deleted element.',
 active=dict(parts=[dict(w=22, role='agent', text='Four people'),
   dict(w=16, role='action', text='say'),
   dict(w=34, role='affected', text='he was asked to leave'),
   dict(w=28, role='hidden', text='and you can ask which four')]),
 passive=dict(parts=[dict(w=34, role='affected', text='He'),
   dict(w=28, role='action', text='is said to have been asked'),
   dict(w=16, role='affected', text='to leave'),
   dict(w=22, role='hidden', text='by whom? deleted')]),
 rule='Both sentences report the same claim. The second one puts the person in the subject slot '
      'and removes the people making it, which is why it prints and why it does more damage. '
      'Reporting responsibly means putting the four back whenever you have them.'),

"fig_b13_u07_p03_v11": dict(type='V11', height=720,
 title='The passive report with two subjects',
 alt='Two panels comparing he is said that he left with he is said to have left.',
 wrong=dict(sentence='He is said that he left.',
            boundary=0.34, boundary_label='he - the subject is taken',
            event=0.62, event_label='and that he brings a second one',
            why='There are two shapes and this sentence has started one and finished the other. '
                'It is said that takes a dummy it, leaving the that clause free to carry its own '
                'subject. He is said has already used the subject slot, so the that clause has '
                'nowhere to attach and the sentence names the same person twice.'),
 right=dict(sentence='He is said to have left.',
            boundary=0.34, boundary_label='he - the subject is taken',
            event=0.66, event_label='and to have left needs no subject of its own',
            why='Once the person is in the subject slot, what follows must be an infinitive, '
                'which borrows that subject. The other repair restores the dummy: it is said '
                'that he left. Same claim, same distance from it, different first word.'),
 misconception='The two shapes feel interchangeable because they mean the same thing, so '
               'learners mix them halfway through. The first word decides the rest of the '
               'sentence: it opens a that clause, a person opens an infinitive, and there is '
               'no third option.'),

"fig_b13_u07_p04_v04": dict(type='V4', height=760,
 title='Three versions, and four lines of record',
 sub='Learner A has what is said. Learner B has what is written down.',
 alt='Two panels compared: three spoken versions of a claim and a four-line complaints register '
     'that does not contain it.',
 differences=7, prompt='Which single element appears in both, and is that element checkable?',
 left=dict(label='what is said, week three', art=[
   dict(kind='person', x=140, y=0, h=106, skin=0, cloth=1),
   dict(kind='person', x=230, y=0, h=104, skin=4, cloth=3),
   dict(kind='person', x=320, y=0, h=106, skin=3, cloth=0),
   dict(kind='label', x=300, y=220, text='three versions · nine people · no first-hand source',
        colour='#A8372E')]),
 right=dict(label='the 2019 register, in full', art=[
   dict(kind='block', x=140, y=40, w=230, bh=14, colour='#9AA7AE'),
   dict(kind='block', x=140, y=70, w=200, bh=14, colour='#9AA7AE'),
   dict(kind='block', x=140, y=100, w=215, bh=14, colour='#9AA7AE'),
   dict(kind='block', x=140, y=130, w=180, bh=14, colour='#9AA7AE'),
   dict(kind='label', x=300, y=220, text='four entries · none of them this · no name',
        colour='#1F4E5F')])),

"fig_b13_u07_p05_v05": dict(type='V5', height=1080,
 title='The three versions and the documentary record',
 sub='What is said, set against what can be looked up.',
 alt='Three versions of a circulating claim transcribed beside a panel record, a complaints '
     'register and an email correction.',
 rows=[dict(t='org', text='THREE VERSIONS, AS HEARD  -  WEEKS 1 TO 3'),
   dict(t='head', text='VERSION 1  -  HEARD AT A PHOTOCOPIER, WEEK 1'),
   dict(t='para', text='"It is said that he was asked to leave his last post. Apparently there '
     'was something, I do not know what."'),
   dict(t='head', text='VERSION 2  -  HEARD IN A GROUP CHAT, WEEK 2'),
   dict(t='para', text='"He is thought to have been interviewed by two people rather than four. '
     'The whole appointment was rushed."'),
   dict(t='head', text='VERSION 3  -  HEARD IN A SEMINAR CORRIDOR, WEEK 3'),
   dict(t='para', text='"According to sources, a complaint was made in 2019 and it was hushed '
     'up. There is no smoke without fire."'),
   dict(t='rule'),
   dict(t='head', text='WHAT CAN BE LOOKED UP'),
   dict(t='grid', cols=['CLAIM', 'RECORD', 'STATUS'],
     data=[['asked to leave last post', 'no record held by us', 'not checkable here'],
           ['interviewed by two people', 'panel record: three', 'FALSE as stated'],
           ['fourth panel member', 'withdrew, in writing, 8 days before', 'a matter of record'],
           ['complaint in 2019', 'register: 4 entries, none this', 'FALSE as stated'],
           ['hushed up', '-', 'unfalsifiable by design']]),
   dict(t='para', text='Two of the five are demonstrably false as stated. One is true and dull. '
     'One cannot be checked from here. One is built so that no evidence could ever settle it.'),
   dict(t='rule'),
   dict(t='head', text='THE 2019 COMPLAINTS REGISTER, IN FULL'),
   dict(t='kv', k='Entries', v='4', mono=True),
   dict(t='kv', k='Relating to this department', v='1 - a parking dispute', mono=False),
   dict(t='kv', k='Containing this name', v='0', mono=True),
   dict(t='rule'),
   dict(t='sign', text='EMAIL, WEEK 1, SENT TO NINE PEOPLE:'),
   dict(t='para', text='"Just to correct something going round - that was a different person, '
     'same surname, different university. I checked. Please pass on." It was forwarded by '
     'nobody.')],
 callouts=[dict(at=0.10, text='Version 1 has no content at all, and it is the one that travels'),
   dict(at=0.20, text='A number, at last - and it is wrong'),
   dict(at=0.30, text='Sources. Plural, unnamed, and nobody has ever met one'),
   dict(at=0.52, text='Three, not two. The only hard number in any version is false'),
   dict(at=0.62, text='Built so that no evidence could ever settle it'),
   dict(at=0.80, text='Four entries, one parking dispute, and no name'),
   dict(at=0.95, text='Nine people read the correction. None of them forwarded it')]),

"fig_b13_u07_p07_v10": dict(type='V10', kind='stress', height=640,
 title='Two stresses, six weak syllables',
 sub='A passive chain is almost all weak forms, and that is what makes it fast.',
 alt='Four passive reporting phrases marked for stress, showing the weak forms between the two '
     'stressed words.',
 items=[dict(syllables=['he', 'is', 'SAID', 'to', 'have', 'been', 'ASKED', 'to', 'leave'],
     strong=[2, 6], note='two stresses in nine syllables'),
   dict(syllables=['is', 'thought', 'to', 'BE', 'fif', 'ty'], strong=[3],
     note='to be - he is fifty now'),
   dict(syllables=['is', 'thought', 'to', 'have', 'BEEN', 'fif', 'ty'], strong=[4],
     note='to have been - he was, then'),
   dict(syllables=['is', 'un', 'der', 'STOOD', 'to', 'have', 'start', 'ed'], strong=[3],
     note='four weak syllables after the only stress')]),

"fig_b13_u07_p08_v02": dict(type='V2', height=820,
 title='A report of an unverified claim, in section',
 sub='Four layers, and the second one comes before any detail of the first.',
 alt='A cutaway of a written report in four layers from the claim and its status to the '
     'checkable record and the harm.',
 floors=[dict(was='the claim', now='Reported, with no owner - because there is no owner',
     year='', fill='#E4ECEF'),
   dict(was='the status', now='None of which has been established. Four flat clauses, early',
     year='', fill='#EFE2DD'),
   dict(was='what is on record', now='Smaller and duller than the rumour, and the only solid thing',
     year='', fill='#F6F0E4'),
   dict(was='the harm', now='A semester, carried by one person. The department carries nothing',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='Report it in full or you are reporting a version of it'),
   dict(at=0.38, text='Status before detail, or the detail does the work before the status lands'),
   dict(at=0.62, text='Dull is the point. A rumour is always more interesting than a record'),
   dict(at=0.88, text='The asymmetry is what makes rumours efficient. Name it')]),

"fig_b13_u07_p09_v05": dict(type='V5', height=1060,
 title='One safety brief, four deliveries',
 sub='The same four minutes, and only one of them produces a report of a near miss.',
 alt='Four versions of a workplace safety brief compared for compliance, recall, behaviour and '
     'whether anybody afterwards reported anything.',
 rows=[dict(t='org', text='WORK FILE  -  THE SAFETY BRIEF  -  SAME CONTENT, FOUR DELIVERIES'),
   dict(t='grid', cols=['VERSION', 'LENGTH', 'METHOD'],
     data=[['A', '4 min', 'read from the laminated card, start to finish'],
           ['B', '4 min', 'read, then "any questions?" (none)'],
           ['C', '90 s', 'walked: exits pointed at, hazards touched'],
           ['D', '4 min', 'one question asked of each person, by name']]),
   dict(t='rule'),
   dict(t='head', text='TESTED COLD, NEXT DAY'),
   dict(t='grid', cols=['VERSION', 'SIGNED', 'RECALLED 3 ITEMS', 'DID IT UNDER PRESSURE'],
     data=[['A', '12 of 12', '2 of 12', 'not tested'],
           ['B', '12 of 12', '3 of 12', 'not tested'],
           ['C', '12 of 12', '9 of 12', '8 of 12'],
           ['D', '12 of 12', '10 of 12', '9 of 12']]),
   dict(t='para', text='All four are legally complete. All four produce a signature. Version A '
     'is the one most often used, because it is the one that can be delivered by somebody who '
     'has not read the room.'),
   dict(t='rule'),
   dict(t='head', text='THE FOURTH THING A BRIEF IS FOR'),
   dict(t='kv', k='Near misses reported, the month after A', v='0', mono=True),
   dict(t='kv', k='after B', v='0', mono=True),
   dict(t='kv', k='after C', v='1', mono=True),
   dict(t='kv', k='after D', v='6', mono=True),
   dict(t='rule'),
   dict(t='sign', text='WHAT VERSION D DID THAT THE OTHERS DID NOT:'),
   dict(t='para', text='"She asked each of us one question, by name, and when somebody got it '
     'wrong she said so and moved on. Nothing happened to them. That is the whole thing. '
     'Nothing happened to them, in front of everybody."')],
 callouts=[dict(at=0.12, text='Ninety seconds, walked, beats four minutes read'),
   dict(at=0.36, text='Two of twelve. Legally complete, operationally nothing'),
   dict(at=0.44, text='Nine of twelve did it under pressure - from ninety seconds'),
   dict(at=0.58, text='Delivered by somebody who has not read the room. That is the appeal'),
   dict(at=0.78, text='Zero, zero, one, six - and only the last column is the real measure'),
   dict(at=0.94, text='Nothing happened to them, in front of everybody')]),

"fig_b13_u07_p10_v12": dict(type='V12', height=900,
 title='Three weeks, six weeks, two years',
 sub='Half the class sees the versions. Half sees the record. Rebuild it by speaking.',
 alt='An infographic from week one to two years later showing how three versions spread, the '
     'note, the Stage 1 process and the outcome.',
 span=['week 1', '+2 years'], ticks=6,
 tick_labels=['wk 1', 'wk 3', 'the note', 'wk 9', '+1 yr', '+2 yr'],
 bands=[dict(name='What was known', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.30}, label='three versions, no first-hand source',
     colour='#A8372E'),
   dict(**{'from': 0.30, 'to': 0.56}, label='Stage 1, opened by the person concerned',
     colour='#D9A441'),
   dict(**{'from': 0.56, 'to': 1.0}, label='found nothing, because there was nothing',
     colour='#2E6F5E')]),
  dict(name='What it cost him', type='bars', items=[
   dict(**{'from': 0.08, 'to': 0.56}, label='a teaching allocation, quietly rearranged',
     colour='#C86B2B'),
   dict(**{'from': 0.56, 'to': 0.90}, label='two more years, then a job he had already applied for',
     colour='#9AA7AE')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.04, label='the correction email: nine recipients, no forwards', colour='#8C6A9E'),
   dict(at=0.26, label='he finds out from a student, who is embarrassed', colour='#A8372E'),
   dict(at=0.32, label='a one-page note, the three versions in the words heard',
     colour='#1F4E5F'),
   dict(at=0.36, label='he asks to open it himself, so the file says so', colour='#2E6F5E'),
   dict(at=0.58, label='traced to a different person, same surname', colour='#D9A441')]),
  dict(name='People who heard it first-hand', type='line',
   points=[(0, 1), (0.2, 1), (0.3, 1), (0.56, 0), (0.8, 0), (1.0, 0)], end_label='0'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.14, label='forward an email that nine people had already read'),
   dict(at=0.46, label='ask, at any point in three weeks, who heard it first'),
   dict(at=0.70, label='tell the nine that the correction had been right'),
   dict(at=0.98, label='change what happens in week one, next time')])]),

"fig_b13_u07_p11_v06": dict(type='V6', kind='line', height=820,
 title='How three versions spread, week by week',
 sub='People who had heard each version, and people who had heard it first-hand.',
 alt='A line chart showing the number of people who had heard each of three versions of a '
     'rumour over three weeks, with first-hand hearers flat at one.',
 labels=['wk 1', 'wk 1.5', 'wk 2', 'wk 2.5', 'wk 3', 'wk 3.5'],
 ymin=0, ymax=80, fmt='{:,.0f}',
 series=[dict(name='heard version 1', values=[4, 14, 31, 52, 68, 71], colour='#A8372E'),
   dict(name='heard version 2', values=[0, 2, 11, 26, 44, 49], colour='#C86B2B'),
   dict(name='heard version 3', values=[0, 0, 0, 6, 22, 35], colour='#D9A441'),
   dict(name='heard it first-hand', values=[1, 1, 1, 1, 1, 1], colour='#1F4E5F')],
 note='Counted from a reconstruction afterwards, so the totals are low rather than high. Each '
      'version is counted once per person.',
 warning='Seventy-one people had heard the first version by week three. The number who had '
         'heard it from anybody who heard it first-hand never moved off one.'),
}
