"""B1.3 Unit 8 - Three People, Three Emails - twelve figures, as data."""
FIGURES = {
"fig_b13_u08_p00_v01": dict(type='V1', height=840, storey_h=150,
 title='The corridor with three doors, week twelve',
 sub='Twelve things to find. Four are a warning. Four are places a warning can stop.',
 alt='An administration building with three office doors, a pending tray, a flowchart on a '
     'noticeboard and a handover note under a keyboard.',
 sky='#DEE2E5', ground='#A4A7A5', ground_line=672,
 buildings=[dict(x=20, w=600, storeys=3, colour='#D1CDC3', cutaway=True,
     floor_labels=['three offices, three inboxes',
                   'the registry, a pending tray',
                   'the student centre, a missed call'],
     label='Administration'),
   dict(x=720, w=380, storeys=3, colour='#C7C3B8', label='the faculty, a flowchart from 2016'),
   dict(x=1200, w=380, storeys=2, colour='#BEBAB0', label='the shared drive, two years old')],
 props=[dict(kind='tree', x=670, y=672, s=1.0), dict(kind='tree', x=1150, y=672, s=.9),
   dict(kind='hoarding', x=1130, y=672, s=.9),
   dict(kind='table', x=950, y=672, s=1.3),
   dict(kind='box', x=1500, y=672, s=1.0),
   dict(kind='sign', x=820, y=672, s=.7, text='FYI'),
   dict(kind='sign', x=1060, y=672, s=.7, text='2114')],
 people=[dict(x=150, y=672, h=86, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=300, y=672, h=86, skin=0, cloth=1, hair='long', arm='down'),
   dict(x=440, y=672, h=86, skin=1, cloth=2, hair='bun', arm='point'),
   dict(x=1280, y=672, h=86, skin=3, cloth=0, hair='cap', arm='folded'),
   dict(x=1420, y=672, h=86, skin=2, cloth=4, hair='grey', arm='hold')],
 names=[dict(x=150, t='coordinator 1, left in week six'),
   dict(x=300, t='coordinator 2, arrived in week six'),
   dict(x=440, t='the personal tutor, week nine'),
   dict(x=1280, t='the student, withdrew in week eleven'),
   dict(x=1420, t='the review panel, week fourteen'),
   dict(x=820, t='an email marked FYI, read by one person'),
   dict(x=1060, t='2,114 unread'),
   dict(x=950, t='four crosses in a row, week three')],
 markers=[dict(x=150, y=552), dict(x=300, y=552), dict(x=440, y=552), dict(x=1280, y=552),
   dict(x=1420, y=552), dict(x=820, y=606), dict(x=1060, y=606), dict(x=950, y=620),
   dict(x=1130, y=618), dict(x=1500, y=620), dict(x=670, y=610), dict(x=1150, y=610)]),

"fig_b13_u08_p01_v08": dict(type='V8', height=800,
 title='Three warnings, and the place none of them met',
 sub='Six nodes. Every arrow is correct. The node in the middle does not exist.',
 alt='A network of three separate warnings each reaching one person, with the point where they '
     'would have been combined shown as an empty node.',
 nodes={
  'w03': dict(x=170, y=180, short='1', name='Week 3', sub='four absences, automatic',
              colour='#D9A441'),
  'w06': dict(x=170, y=400, short='2', name='Week 6', sub='the handover, eleven sections',
              colour='#C86B2B'),
  'w09': dict(x=170, y=620, short='3', name='Week 9', sub='a second flag, another system',
              colour='#A8372E'),
  'own': dict(x=620, y=400, short='4', name='Nobody owns this', sub='no role description has it',
              r=58, colour='#9AA7AE'),
  'ppl': dict(x=1030, y=250, short='5', name='Three people', sub='each did what the role said',
              colour='#1F4E5F'),
  'out': dict(x=1300, y=560, short='6', name='Week 11', sub='withdrew', r=54, colour='#8C6A9E')},
 edges=[dict(a='w03', b='ppl', label='to coordinator 1', sw=6),
   dict(a='w06', b='ppl', label='and the role changes hands', sw=6),
   dict(a='w09', b='ppl', label='to coordinator 2, who asks for context', sw=6),
   dict(a='w03', b='own', label='would have met here', sw=2, dash='6 6', colour='#9AA7AE'),
   dict(a='w09', b='own', label='and here', sw=2, dash='6 6', colour='#9AA7AE'),
   dict(a='ppl', b='out', label='three correct actions, one outcome', sw=6)]),

"fig_b13_u08_p02_v07": dict(type='V7', height=820,
 title='The review meeting, week fourteen',
 sub='One of them held the week-nine email. One of them is writing the finding.',
 alt='A coordinator and a review panel chair across a table, their speech shown as hypothetical '
     'past forms.',
 bg='#E8EAEC',
 set=[dict(kind='table', x=700, y=700, s=1.5), dict(kind='doc', x=700, y=626)],
 people=[dict(x=470, h=250, skin=0, cloth=1, hair='long', arm='hold', facing='right',
   label='coordinator 2', role='arrived in week six',
   says=['I could have asked, but there was nothing in front of me that said to.',
     'You needn\'t have carried that one - it was never yours.']),
  dict(x=980, h=248, skin=2, cloth=4, hair='grey', arm='point', facing='left',
   label='the panel chair', role='writing the finding',
   says=['Somebody should have put the three together, and nobody did.'])]),

"fig_b13_u08_p03_v09": dict(type='V9', kind='ladder', height=760,
 title='Did it happen, or not?',
 sub='Five of these say it did not. One says it did, and it is the one everybody gets wrong.',
 alt='A vertical ladder of hypothetical past forms arranged by whether the action happened, '
     'with needn\'t have at the top and should have below.',
 top_label='it DID happen',
 bottom_label='it did NOT happen',
 steps=[dict(form="needn't have done", meaning='it was done, and it was unnecessary'),
   dict(form='did not need to do', meaning='and it probably was not done at all'),
   dict(form='might have done', meaning='possible - and nobody has established which'),
   dict(form='could have done', meaning='it was possible. Not done. Not yet a criticism'),
   dict(form='would have done', meaning='the consequence of a condition that did not hold'),
   dict(form='ought to have done', meaning='a duty. Not done'),
   dict(form='should have done', meaning='the right thing. Not done')]),

"fig_b13_u08_p03_v11": dict(type='V11', height=720,
 title="needn't have, and the Thursday it describes",
 alt="Two panels comparing she needn't have come in with she did not need to come in.",
 wrong=dict(sentence="She needn't have come in, so she stayed at home.",
            boundary=0.40, boundary_label="needn't have come in",
            event=0.74, event_label='and the second half says she did not',
            why="needn't have plus past participle says the action happened and was "
                "unnecessary. The sentence then says she stayed at home, which contradicts the "
                "first half. Two people reading this will picture two different Thursdays, and "
                "in a post-mortem that is the difference between a wasted trip and no trip."),
 right=dict(sentence='She did not need to come in, so she stayed at home.',
            boundary=0.44, boundary_label='did not need to come in',
            event=0.76, event_label='and nothing happened, which is consistent',
            why='did not need to describes the absence of an obligation and says nothing about '
                'what was done, so it sits with either ending. Use it when the action did not '
                "happen, and needn't have only when it did and was wasted."),
 misconception='Both forms translate the same way in most languages, so learners choose by '
               'register and hear them as interchangeable. In English the choice reports a '
               'fact: one of them says the person turned up.'),

"fig_b13_u08_p04_v04": dict(type='V4', height=760,
 title='Three warnings, three job descriptions',
 sub='Learner A has what fired. Learner B has what each role says.',
 alt='Two panels compared: three dated warnings and three role descriptions, with the task that '
     'appears in neither marked.',
 differences=7, prompt='Which task appears in none of the three role descriptions, and who '
                       'removed it?',
 left=dict(label='what fired, and when', art=[
   dict(kind='block', x=140, y=30, w=60, bh=22, colour='#D9A441'),
   dict(kind='block', x=230, y=80, w=60, bh=22, colour='#C86B2B'),
   dict(kind='block', x=320, y=130, w=60, bh=22, colour='#A8372E'),
   dict(kind='label', x=300, y=220, text='wk 3 · wk 6 · wk 9 — three systems',
        colour='#A8372E')]),
 right=dict(label='what the roles say', art=[
   dict(kind='block', x=140, y=24, w=230, bh=18, colour='#1F4E5F'),
   dict(kind='block', x=140, y=56, w=210, bh=18, colour='#1F4E5F'),
   dict(kind='block', x=140, y=88, w=225, bh=18, colour='#1F4E5F'),
   dict(kind='gap', x=140, y=120, w=230, bh=18),
   dict(kind='label', x=300, y=220, text='eleven duties, and no line for case continuity',
        colour='#9AA7AE')])),

"fig_b13_u08_p05_v05": dict(type='V5', height=1080,
 title='The three warnings and the handover template',
 sub='Everything here was generated, delivered and filed correctly.',
 alt='Three automated warnings with their recipients and dates, beside an eleven-section '
     'handover template and an email reply asking for context.',
 rows=[dict(t='org', text='UNIT REVIEW  -  TWELVE WEEKS  -  THREE WARNINGS'),
   dict(t='grid', cols=['WK', 'TRIGGER', 'WENT TO', 'ACTION'],
     data=[['3', 'four consecutive absences (threshold 4)', 'unit coordinator 1', 'noted, filed'],
           ['6', 'handover, coordinator 1 to coordinator 2', 'both', 'completed, signed off'],
           ['9', 'personal tutor flag, separate system', 'unit coordinator 2',
            'replied same day'],
           ['11', 'withdrawal', 'registry', 'processed in 2 days']]),
   dict(t='para', text='Three warnings. Three recipients. The only person who received two of '
     'them received them eleven weeks apart and was a different person by the second one.'),
   dict(t='rule'),
   dict(t='head', text='HANDOVER TEMPLATE  -  ELEVEN SECTIONS, FOUR PAGES'),
   dict(t='para', text='1 unit outline · 2 assessment deadlines · 3 moderation · 4 marking '
     'allocation · 5 room bookings · 6 reading list · 7 guest lecturers · 8 online materials · '
     '9 budget codes · 10 staff contacts · 11 outstanding admin'),
   dict(t='kv', k='Sections mentioning students individually', v='0', mono=True),
   dict(t='kv', k='Last revised', v='2016 role review', mono=False),
   dict(t='kv', k='What the 2016 review removed', v='"case continuity" from the coordinator role',
        mono=False),
   dict(t='kv', k='Where it was moved to', v='nowhere', mono=False),
   dict(t='rule'),
   dict(t='head', text='THE WEEK-NINE EMAIL, AND THE REPLY'),
   dict(t='para', text='TUTOR: "Flagging a concern about [student], attendance and two missed '
     'submissions. Can you advise?"'),
   dict(t='para', text='COORDINATOR 2: "Happy to - is there any background on this one? I came '
     'in at week six and do not have anything on file."'),
   dict(t='kv', k='Reply to that', v='none', mono=False),
   dict(t='kv', k='Could it have been answered', v='yes - by coordinator 1, who had left',
        mono=False),
   dict(t='rule'),
   dict(t='sign', text='THE ATTENDANCE THRESHOLD:'),
   dict(t='para', text='"Four consecutive absences." At four, a third of a twelve-week semester '
     'is already gone. At a threshold of two it would have fired in week two, when coordinator '
     '1 was still in post.')],
 callouts=[dict(at=0.14, text='Three systems, three recipients, and no two of them met'),
   dict(at=0.26, text='Eleven weeks apart, and a different person by the second'),
   dict(at=0.44, text='Eleven sections. Rooms, budget codes, guest lecturers. No students'),
   dict(at=0.56, text='Removed in 2016 and put nowhere. That is the whole finding'),
   dict(at=0.74, text='She asked. The one person who could answer had left in week six'),
   dict(at=0.95, text='Four absences is a third of the semester. Two would have fired in week 2')]),

"fig_b13_u08_p07_v10": dict(type='V10', kind='stress', height=640,
 title="should've, could've, ought to've",
 sub='One stressed syllable, then a schwa. This is why the wrong spelling exists.',
 alt='Four hypothetical past phrases marked for stress, showing have reduced to a single weak '
     'syllable.',
 items=[dict(syllables=['she', 'SHOULD', 'uhv', 'asked'], strong=[1],
     note="/ʃʊdəv/ - never should of"),
   dict(syllables=['she', 'COULD', 'uhv', 'asked'], strong=[1], note='/kʊdəv/'),
   dict(syllables=['it', 'OUGHT', 'tuhv', 'fired'], strong=[1], note='/ɔːtəv/'),
   dict(syllables=['you', 'NEED', 'nt', 'uhv', 'come'], strong=[1],
     note='/niːdntəv/ - and she came')]),

"fig_b13_u08_p08_v02": dict(type='V2', height=820,
 title='A post-mortem, in section',
 sub='Four layers. There is no name in the third one, and that is the deliberate part.',
 alt='A cutaway of a written post-mortem in four layers from the dated sequence to the system '
     'fault and the withdrawal.',
 floors=[dict(was='the sequence', now='Dated, flat, and with no adjectives anywhere in it',
     year='', fill='#E4ECEF'),
   dict(was='what was possible', now='Could have - and why nothing in front of them said to',
     year='', fill='#EFE2DD'),
   dict(was='the system fault', now='Stated twice, with no person in either sentence', year='',
     fill='#F6F0E4'),
   dict(was='the withdrawal', now='One criticism taken back, and it costs the writer something',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='An adjective in the sequence is an argument hiding in a fact'),
   dict(at=0.38, text='Could have describes a system. Should have names a person'),
   dict(at=0.62, text='If the fault needs a name to be stated, it is not the fault yet'),
   dict(at=0.88, text='A post-mortem with nothing withdrawn was written before the evidence')]),

"fig_b13_u08_p09_v05": dict(type='V5', height=1060,
 title='Four literature reviews, one reading list',
 sub='The one who read the most wrote the worst of the four.',
 alt='Four students compared on how much they read, when they started writing and what their '
     'literature review did.',
 rows=[dict(t='org', text='STUDY FILE  -  THE LITERATURE REVIEW  -  SAME TASK, FOUR METHODS'),
   dict(t='grid', cols=['STUDENT', 'SOURCES READ', 'STARTED WRITING', 'SHAPE OF THE REVIEW'],
     data=[['A', '41', 'week 5 of 6', 'chronological. Everything, in order, no argument'],
           ['B', '12', 'week 1', 'five positions, two disagreements, question placed'],
           ['C', '23', 'week 3', 'thematic. Four themes, and the themes are the topic'],
           ['D', '9', 'week 1', 'one disagreement, tested against nine sources']]),
   dict(t='para', text='A read forty-one sources and produced a list. D read nine and produced '
     'a map. The difference is not reading speed and it is not diligence: it is whether '
     'anything was written down before most of the reading happened.'),
   dict(t='rule'),
   dict(t='head', text='D\'S METHOD, WHICH SOUNDS LAZY'),
   dict(t='para', text='"Read five. Write the disagreement between them in one sentence. Read '
     'five more and see whether the sentence survives. Mine did not survive the first time or '
     'the second. The third one is the review."'),
   dict(t='kv', k='Sentences written and discarded', v='2', mono=True),
   dict(t='kv', k='Sources read after the surviving sentence', v='4', mono=True),
   dict(t='kv', k='Hours', v='about 11', mono=True),
   dict(t='kv', k='A\'s hours', v='about 34', mono=True),
   dict(t='rule'),
   dict(t='sign', text='WHAT A SAID AFTERWARDS:'),
   dict(t='para', text='"I kept reading because I did not know what I was looking for, and I '
     'did not know what I was looking for because I had not written anything. I thought writing '
     'came after reading. It is the other way round, or at least it is both at once."')],
 callouts=[dict(at=0.14, text='Forty-one sources, and the review is a list'),
   dict(at=0.20, text='Nine sources, and the review is a map'),
   dict(at=0.34, text='Not speed, not diligence - what got written down first'),
   dict(at=0.52, text='Two sentences discarded. That is the method working'),
   dict(at=0.72, text='Eleven hours against thirty-four, for the better review'),
   dict(at=0.94, text='It is the other way round, or at least it is both at once')]),

"fig_b13_u08_p10_v12": dict(type='V12', height=900,
 title='Twelve weeks, and the July after',
 sub='Half the class sees the warnings. Half sees the template. Rebuild it by speaking.',
 alt='An infographic from week one to the following year showing the three warnings, the '
     'handover, the withdrawal, the review and the template change.',
 span=['week 1', 'next yr'], ticks=6,
 tick_labels=['wk 1', 'wk 3', 'wk 6', 'wk 9', 'wk 14', 'July'],
 bands=[dict(name='Who held the case', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.38}, label='coordinator 1', colour='#1F4E5F'),
   dict(**{'from': 0.38, 'to': 0.74}, label='coordinator 2 - with nothing on file',
     colour='#C86B2B'),
   dict(**{'from': 0.74, 'to': 1.0}, label='the review panel, then nobody', colour='#9AA7AE')]),
  dict(name='The template', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.92}, label='eleven sections, none about students, since 2016',
     colour='#A8372E'),
   dict(**{'from': 0.92, 'to': 1.0}, label='twelve: open student cases, with dates',
     colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.16, label='wk 3: four absences. Automatic alert, one recipient', colour='#D9A441'),
   dict(at=0.38, label='wk 6: handover signed off, four pages, no cases', colour='#C86B2B'),
   dict(at=0.56, label='wk 9: a second flag. "Is there any background?" No reply',
     colour='#A8372E'),
   dict(at=0.68, label='wk 11: withdrew', colour='#8C6A9E'),
   dict(at=0.96, label='July: one line added. It fires in the second week of term',
     colour='#2E6F5E')]),
  dict(name='People holding all three warnings', type='line',
   points=[(0, 0), (0.2, 0), (0.4, 0), (0.6, 0), (0.78, 1), (1.0, 1)], end_label='1'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.26, label='ask what the threshold of four actually buys'),
   dict(at=0.48, label='put case continuity anywhere after removing it in 2016'),
   dict(at=0.62, label='answer the question in the reply'),
   dict(at=0.86, label='ask the coordinator what the email had said')])]),

"fig_b13_u08_p11_v06": dict(type='V6', kind='bar', height=840,
 title='Absence thresholds and what each one would catch',
 sub='Students reaching each threshold last year, and how many of them withdrew.',
 alt='A bar chart of students reaching two, three, four and six consecutive absences and the '
     'number in each group who later withdrew.',
 labels=['2 absences', '3 absences', '4 (current)', '6 absences'],
 ymin=0, ymax=400, fmt='{:,.0f}',
 series=[dict(name='students reaching it', values=[361, 174, 88, 31], colour='#1F4E5F'),
   dict(name='of whom withdrew', values=[29, 27, 24, 19], colour='#A8372E'),
   dict(name='median week it fires x20', values=[40, 80, 120, 180], colour='#D9A441')],
 note='Last year, one faculty, 2,140 students. The median firing week is multiplied by twenty '
      'so that it fits the same axis.',
 warning='Dropping the threshold from four to three costs eighty-six more alerts and catches '
         'three more withdrawals three weeks earlier, while the coordinator is still in post.'),
}
