"""B1.3 Unit 9 - Perfectly Clear - twelve figures, as data."""
FIGURES = {
"fig_b13_u09_p00_v01": dict(type='V1', height=840, storey_h=150,
 title='The science building and the canteen, one o\'clock',
 sub='Twelve things to find. Four of them are one register. Four are another.',
 alt='A science building with a lab bench and a marked report, beside a canteen table with six '
     'people and four languages, and two signs saying the same thing differently.',
 sky='#DDE3E4', ground='#A4A7A4', ground_line=672,
 buildings=[dict(x=20, w=560, storeys=3, colour='#D1CDC3', cutaway=True,
     floor_labels=['the lab, a labelled rack',
                   'the marking office, four red brackets',
                   'the canteen, four languages at one table'],
     label='Science'),
   dict(x=680, w=400, storeys=3, colour='#C7C3B8', label='the office, hours on the door'),
   dict(x=1180, w=400, storeys=2, colour='#BEBAB0', label='the library, dictionaries unopened')],
 props=[dict(kind='tree', x=630, y=672, s=1.0), dict(kind='tree', x=1130, y=672, s=.9),
   dict(kind='hoarding', x=1090, y=672, s=1.0),
   dict(kind='table', x=900, y=672, s=1.3),
   dict(kind='box', x=1500, y=672, s=1.0),
   dict(kind='sign', x=760, y=672, s=.7, text='84'),
   dict(kind='sign', x=1000, y=672, s=.7, text='-4')],
 people=[dict(x=140, y=672, h=86, skin=3, cloth=0, hair='cap', arm='hold'),
   dict(x=270, y=672, h=86, skin=0, cloth=1, hair='long', arm='point'),
   dict(x=400, y=672, h=86, skin=1, cloth=2, hair='bun', arm='folded'),
   dict(x=1280, y=672, h=86, skin=4, cloth=3, hair='short', arm='down'),
   dict(x=1420, y=672, h=86, skin=2, cloth=4, hair='grey', arm='hold')],
 names=[dict(x=140, t='the student, soil respiration, 84'),
   dict(x=270, t='the marker, nine years on the unit'),
   dict(x=400, t='the unit chair, eleven cases'),
   dict(x=1280, t='a conference lanyard, a translation tab'),
   dict(x=1420, t='the style guide, on a shelf'),
   dict(x=760, t='the mark, before expression'),
   dict(x=1000, t='four marks, criterion not on the sheet'),
   dict(x=1090, t='"Please do not leave glassware in the sink"')],
 markers=[dict(x=140, y=552), dict(x=270, y=552), dict(x=400, y=552), dict(x=1280, y=552),
   dict(x=1420, y=552), dict(x=760, y=606), dict(x=1000, y=606), dict(x=1090, y=620),
   dict(x=900, y=620), dict(x=1500, y=620), dict(x=630, y=610), dict(x=1130, y=610)]),

"fig_b13_u09_p01_v08": dict(type='V8', height=800,
 title='Four ways English can exclude somebody',
 sub='Six nodes. Two of them are the same mechanism with different social standing.',
 alt='A network from jargon, slang, idiom and register to who is excluded, with code-switching '
     'shown as the escape route.',
 nodes={
  'jar': dict(x=170, y=200, short='1', name='Jargon', sub='excludes outside the field',
              colour='#1F4E5F'),
  'sla': dict(x=170, y=600, short='2', name='Slang', sub='excludes outside the group',
              colour='#C86B2B'),
  'idi': dict(x=540, y=400, short='3', name='Idiom', sub='excludes outside the first language',
              colour='#A8372E'),
  'reg': dict(x=900, y=200, short='4', name='Register', sub='a choice, and it has to be taught',
              colour='#2E6F5E'),
  'csw': dict(x=900, y=600, short='5', name='Code-switch', sub='doing it on purpose, both ways',
              colour='#D9A441'),
  'rea': dict(x=1270, y=400, short='6', name='The reader', sub='who is in and who is out',
              r=56, colour='#8C6A9E')},
 edges=[dict(a='jar', b='idi', label='one is respected, the other is not', sw=6),
   dict(a='sla', b='idi', label='and the mechanism is identical', sw=6),
   dict(a='idi', b='reg', label='nobody teaches this, everybody marks it', sw=6),
   dict(a='reg', b='rea', label='and the reader decides what counts', sw=6),
   dict(a='idi', b='csw', label='the way out', sw=2, dash='6 6', colour='#D9A441'),
   dict(a='csw', b='rea', label='which is a skill, not an inconsistency', sw=6,
        colour='#D9A441')]),

"fig_b13_u09_p02_v07": dict(type='V7', height=820,
 title='The marking office, Thursday',
 sub='One of them took the four marks off. One of them has seen eleven of these.',
 alt='A marker and a unit chair in an office with a marked report between them, their speech '
     'shown with phrasal verbs.',
 bg='#E8EBEB',
 set=[dict(kind='table', x=700, y=700, s=1.4), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=0, cloth=1, hair='long', arm='hold', facing='right',
   label='the marker', role='nine years on the unit',
   says=['She got the idea across in every single paragraph.',
     'It is not wrong. It just is not how we say it.']),
  dict(x=980, h=248, skin=1, cloth=2, hair='bun', arm='point', facing='left',
   label='the unit chair', role='eleven cases this year',
   says=['What I cannot get away with is marking something I cannot name.'])]),

"fig_b13_u09_p03_v09": dict(type='V9', kind='branch', height=740,
 title='Where the object is allowed to stand',
 sub='One rule is absolute. The other three are about which group the verb belongs to.',
 alt='A branching diagram of four phrasal verb types showing where an object noun and an object '
     'pronoun can go in each.',
 root='she ___ it',
 branches=[dict(label='SEPARABLE - a noun goes either side', colour='#1F4E5F',
     example='mark the student down · mark down the student'),
   dict(label='SEPARABLE - a pronoun MUST split it', colour='#A8372E',
     example='mark her down · NEVER mark down her'),
   dict(label='INSEPARABLE - always after the particle', colour='#2E6F5E',
     example='look into it · come across it · get over it'),
   dict(label='THREE-PART - never splits, ever', colour='#C86B2B',
     example='put up with it · look forward to it · run out of it'),
   dict(label='NO OBJECT - nothing goes anywhere', colour='#9AA7AE',
     example='stand down · die down · look back')]),

"fig_b13_u09_p03_v11": dict(type='V11', height=720,
 title='Splitting the one that never splits',
 alt='Two panels comparing he could not put it up with and he could not put up with it.',
 wrong=dict(sentence='He could not put it up with.',
            boundary=0.46, boundary_label='put it - the object goes in',
            event=0.70, event_label='and up with is left with nothing to attach to',
            why='Put up with is a three-part verb and the two particles belong to it as a unit. '
                'Moving the object inside breaks the unit, and the sentence ends on a '
                'preposition with no object, which is why it sounds unfinished rather than '
                'merely wrong.'),
 right=dict(sentence='He could not put up with it.',
            boundary=0.56, boundary_label='put up with - all three, together',
            event=0.78, event_label='and the object follows the whole thing',
            why='Three-part verbs have no exceptions: the object always comes after both '
                'particles. This is why they are the easiest of the four groups, and why the '
                'rule worth memorising is the separable one - mark her down, never mark down '
                'her.'),
 misconception='Learners who have correctly learned that phrasal verbs can be split then apply '
               'it everywhere. Splitting belongs to one group of four. The pronoun rule inside '
               'that group is the only part of this that is absolute.'),

"fig_b13_u09_p04_v04": dict(type='V4', height=760,
 title='The same finding, two registers',
 sub='Learner A has the technical version. Learner B has the version for a newspaper.',
 alt='Two panels compared: a technical sentence with a measured range and a popular version in '
     'which the range has quietly disappeared.',
 differences=7, prompt='Which fact has quietly changed, and is the change an error or a '
                       'simplification?',
 left=dict(label='for the journal', art=[
   dict(kind='block', x=140, y=30, w=240, bh=20, colour='#1F4E5F'),
   dict(kind='block', x=140, y=66, w=200, bh=20, colour='#1F4E5F'),
   dict(kind='block', x=140, y=102, w=160, bh=20, colour='#2E6F5E'),
   dict(kind='label', x=300, y=220, text='Q10 of 2.1, across 8-24 °C', colour='#1F4E5F')]),
 right=dict(label='for a newspaper', art=[
   dict(kind='block', x=140, y=30, w=240, bh=20, colour='#C86B2B'),
   dict(kind='block', x=140, y=66, w=200, bh=20, colour='#C86B2B'),
   dict(kind='gap', x=140, y=102, w=160, bh=20),
   dict(kind='label', x=300, y=220, text='"doubles with every ten degrees" - and no range',
        colour='#A8372E')])),

"fig_b13_u09_p05_v05": dict(type='V5', height=1080,
 title='The rubric and the marked page',
 sub='Eleven criteria, none about language, and four brackets in a margin.',
 alt='A marking rubric with eleven criteria beside a marked report page with four margin '
     'brackets and a faculty style guide entry.',
 rows=[dict(t='org', text='SCIENCE 2210  -  LAB REPORT RUBRIC  -  ELEVEN CRITERIA, 100 MARKS'),
   dict(t='grid', cols=['#', 'CRITERION', 'MARKS'],
     data=[['1', 'aim and hypothesis', '8'], ['2', 'method, reproducible', '15'],
           ['3', 'controls', '10'], ['4', 'data presentation', '12'],
           ['5', 'figure labelling', '6'], ['6', 'statistical treatment', '12'],
           ['7', 'discussion of results', '15'], ['8', 'confounds identified', '8'],
           ['9', 'limitations', '6'], ['10', 'referencing', '5'],
           ['11', 'structure and length', '3']]),
   dict(t='kv', k='Criteria mentioning language', v='0', mono=True),
   dict(t='kv', k='Mark awarded', v='84', mono=True),
   dict(t='kv', k='Sheet comment', v='"expression - 4"', mono=False),
   dict(t='rule'),
   dict(t='head', text='THE FOUR MARGIN BRACKETS'),
   dict(t='grid', cols=['#', 'MARKED TEXT', 'WHAT IT IS'],
     data=[['1', '"the data permits us to affirm"', 'unidiomatic. Not an error'],
           ['2', '"the respiration rate augments"', 'unidiomatic. Not an error'],
           ['3', '"in function of temperature"', 'ERROR - as a function of'],
           ['4', '"we can conclude that it exists a relation"', 'unidiomatic. Not an error']]),
   dict(t='para', text='One of the four is an error. The other three are current-English '
     'preferences: allow, conclude, increase. A chemist in 1890 would have written all three.'),
   dict(t='rule'),
   dict(t='head', text='FACULTY STYLE GUIDE, ENTRY 4.2'),
   dict(t='para', text='"Prefer short Anglo-Saxon verbs where they exist: use rather than '
     'utilise, allow rather than permit, increase rather than augment. This is a preference, '
     'not a rule."'),
   dict(t='rule'),
   dict(t='sign', text='WHO HAS READ THE STYLE GUIDE:'),
   dict(t='para', text='It is on a shelf in the main office. It is not on the unit site, not in '
     'the handbook, and not referenced in any of the eleven criteria. Three of nineteen staff '
     'surveyed knew it existed.')],
 callouts=[dict(at=0.26, text='Fifteen marks for method, three for structure, none for language'),
   dict(at=0.34, text='Zero. And four marks came off for it'),
   dict(at=0.56, text='One real error in four brackets, and it is not the one that was noticed'),
   dict(at=0.68, text='Allow, conclude, increase - a preference, enforced as a rule'),
   dict(at=0.84, text='The guide itself says it is a preference, not a rule'),
   dict(at=0.95, text='Three of nineteen staff knew it existed. No student does')]),

"fig_b13_u09_p07_v10": dict(type='V10', kind='stress', height=640,
 title='The particle takes the stress',
 sub='This is the opposite of what most learners do, and it is the fastest thing to fix.',
 alt='Four phrases marked for stress comparing phrasal verbs, where the particle is stressed, '
     'with verb plus preposition, where the verb is.',
 items=[dict(syllables=['she', 'marked', 'it', 'DOWN'], strong=[3],
     note='phrasal verb - the particle is the word'),
   dict(syllables=['she', 'LOOKED', 'at', 'it'], strong=[1],
     note='verb plus preposition - at is weak'),
   dict(syllables=['I', 'could', 'not', 'put', 'UP', 'with', 'it'], strong=[4],
     note='three-part: the first particle takes it'),
   dict(syllables=['she', 'took', 'O', 'ver'], strong=[2],
     note='entirely - and nobody else has a say')]),

"fig_b13_u09_p08_v02": dict(type='V2', height=820,
 title='One idea, three registers, in section',
 sub='Four layers, and the same number is in all four.',
 alt='A cutaway of one finding written for a journal, a colleague and a child, with the measured '
     'limit kept in all three.',
 floors=[dict(was='for the journal', now='Q10 of 2.1 across 8-24 °C. Notation, and the number',
     year='', fill='#E4ECEF'),
   dict(was='for a colleague elsewhere', now='Roughly doubles for every ten degrees. Same number',
     year='', fill='#EFE2DD'),
   dict(was='for a twelve-year-old', now='Warmer soil, busier life, about twice as busy',
     year='', fill='#F6F0E4'),
   dict(was='the limit', now='Nothing above 24 °C was measured, and none of the three claims it',
     year='', fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='The notation is the only thing the top layer owns'),
   dict(at=0.38, text='Doubles is the number, in words. It has not been softened'),
   dict(at=0.62, text='Less precise, not less accurate. That is the whole distinction'),
   dict(at=0.88, text='Keeping the limit in the simplest version is the hard part')]),

"fig_b13_u09_p09_v05": dict(type='V5', height=1060,
 title='Four minutes, six people, four first languages',
 sub='Where the breakdowns were, and who repaired them.',
 alt='A transcript of a research meeting in English as a lingua franca, with four '
     'misunderstandings marked and their causes.',
 rows=[dict(t='org', text='CULTURE FILE  -  ENGLISH AS A LINGUA FRANCA  -  4 MIN, 6 SPEAKERS'),
   dict(t='kv', k='First languages in the room', v='Mandarin, Portuguese, Farsi, German',
        mono=False),
   dict(t='kv', k='First-language English speakers', v='0', mono=True),
   dict(t='kv', k='Breakdowns in four minutes', v='4', mono=True),
   dict(t='rule'),
   dict(t='grid', cols=['#', 'CAUSE', 'REPAIRED BY'],
     data=[['1', '"let us park that" - idiom', 'the speaker, who rephrased unprompted'],
           ['2', '"ballpark figure" - idiom', 'nobody. Two people nodded and did not know'],
           ['3', '"by Friday" - does it include Friday?', 'a listener, who asked'],
           ['4', '"quite good" - how good?', 'nobody. It is still ambiguous']]),
   dict(t='para', text='Three of the four come from idiom or from a word whose strength varies '
     'between varieties. None of them comes from grammar, and none from accent.'),
   dict(t='rule'),
   dict(t='head', text='WHO WAS EASIEST TO FOLLOW, AS RATED BY THE OTHER FIVE'),
   dict(t='grid', cols=['SPEAKER', 'IDIOMS USED', 'SIGNPOSTED STRUCTURE', 'RATED'],
     data=[['A', '0', 'yes - "three things, then a question"', '1st'],
           ['B', '2', 'yes', '2nd'], ['C', '5', 'no', '5th'],
           ['D', '1', 'no', '3rd']]),
   dict(t='para', text='The speaker rated easiest to follow used no idioms and announced the '
     'shape of each contribution before making it. Nobody rated anybody on accent.'),
   dict(t='rule'),
   dict(t='sign', text='WHAT SPEAKER C SAID AFTERWARDS:'),
   dict(t='para', text='"I learned those expressions on purpose. I was told they would make me '
     'sound natural. In this room they make me harder to understand, and this room is where I '
     'actually work."')],
 callouts=[dict(at=0.20, text='Four breakdowns, and three of them are idioms'),
   dict(at=0.32, text='Nobody repaired this one. Two people nodded'),
   dict(at=0.44, text='None from grammar. None from accent'),
   dict(at=0.66, text='Zero idioms, structure announced out loud, rated first of six'),
   dict(at=0.78, text='Five idioms, no signposting, rated last'),
   dict(at=0.94, text='Learned on purpose, to sound natural, in a room where it costs him')]),

"fig_b13_u09_p10_v12": dict(type='V12', height=900,
 title='Four marks, eleven reports, two years',
 sub='Half the class sees the rubric. Half sees the marked page. Rebuild it by speaking.',
 alt='An infographic from the marking to a paper two years later showing the eleven cases, the '
     'decision, the rubric change and the reviewer query.',
 span=['marking', '+2 years'], ticks=6,
 tick_labels=['marked', 'the ask', 'Friday', 'next yr', '+1 yr', '+2 yr'],
 bands=[dict(name='The criterion', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.56}, label='not on the rubric, and marked anyway',
     colour='#A8372E'),
   dict(**{'from': 0.56, 'to': 1.0}, label='expression, defined in 31 words, comment required',
     colour='#2E6F5E')]),
  dict(name='The eleven students', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.38}, label='marked down, no explanation', colour='#C86B2B'),
   dict(**{'from': 0.38, 'to': 1.0}, label='marks returned, comments written', colour='#2E6F5E')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.06, label='84, and "expression - 4" on the sheet', colour='#D9A441'),
   dict(at=0.22, label='the student asks what the rule is. Nobody can say', colour='#A8372E'),
   dict(at=0.40, label='marks returned; eleven comments written by the marker',
     colour='#2E6F5E'),
   dict(at=0.62, label='rubric rewritten: four drafts, thirty-one words', colour='#1F4E5F'),
   dict(at=0.94, label='a reviewer queries augments. She has the comment', colour='#8C6A9E')]),
  dict(name='Reports marked down with no comment', type='line',
   points=[(0, 11), (0.38, 0), (0.6, 0), (0.8, 0), (1.0, 0)], end_label='0'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.14, label='put the style guide anywhere a student would find it'),
   dict(at=0.30, label='notice that one of the four brackets was a real error'),
   dict(at=0.72, label='tell the markers out loud that they were right about the thing'),
   dict(at=0.98, label='teach any of this in week one, in any year')])]),

"fig_b13_u09_p11_v06": dict(type='V6', kind='bar', height=840,
 title='Marks lost for expression this year',
 sub='Eleven reports, by the writer\'s first language and by what was actually marked.',
 alt='A bar chart of marks lost for expression grouped by first language, with the number of '
     'cases containing an actual error shown alongside.',
 labels=['English first', 'Romance', 'Sinitic', 'Germanic', 'Other'],
 ymin=0, ymax=10, fmt='{:,.0f}',
 series=[dict(name='reports marked down', values=[0, 5, 3, 1, 2], colour='#C86B2B'),
   dict(name='containing an actual error', values=[0, 1, 1, 0, 0], colour='#A8372E'),
   dict(name='given a written comment', values=[0, 0, 0, 0, 0], colour='#1F4E5F')],
 note='One unit, one year, 214 reports. Eleven lost marks under a criterion the rubric does not '
      'contain.',
 warning='No report by a first-language writer lost a mark for expression, two of the eleven '
         'contained an actual error, and none of the eleven was told what had been noticed.'),
}
