"""B1.3 Unit 10 - Never Have I Been So - twelve figures, as data."""
FIGURES = {
"fig_b13_u10_p00_v01": dict(type='V1', height=840, storey_h=150,
 title='Forty chairs, and a corridor at four in the morning',
 sub='Twelve things to find. Four belong to the occasion. Four belong to the nine years before '
     'it.',
 alt='A campus at dusk with a function room set out with forty chairs and a podium, beside a '
     'dark corridor, a logbook and a set of worn keys.',
 sky='#D8DEE4', ground='#9FA3A3', ground_line=672,
 buildings=[dict(x=20, w=560, storeys=3, colour='#CFCBC1', cutaway=True,
     floor_labels=['the function room, forty chairs in rows',
                   'the corridor, four in the morning',
                   'the lodge, a logbook and a kettle'],
     label='the main building'),
   dict(x=680, w=400, storeys=3, colour='#C5C1B6', label='the library, locked at eleven'),
   dict(x=1180, w=400, storeys=2, colour='#BCB8AE', label='the office, where the paper was signed')],
 props=[dict(kind='tree', x=630, y=672, s=1.0), dict(kind='tree', x=1130, y=672, s=.9),
   dict(kind='hoarding', x=1090, y=672, s=.95),
   dict(kind='table', x=900, y=672, s=1.4),
   dict(kind='box', x=1500, y=672, s=1.0),
   dict(kind='sign', x=760, y=672, s=.7, text='04:12'),
   dict(kind='sign', x=1000, y=672, s=.7, text='9 yrs')],
 people=[dict(x=140, y=672, h=86, skin=4, cloth=3, hair='grey', arm='hold'),
   dict(x=270, y=672, h=86, skin=1, cloth=2, hair='bun', arm='point'),
   dict(x=400, y=672, h=86, skin=0, cloth=1, hair='long', arm='folded'),
   dict(x=1280, y=672, h=86, skin=3, cloth=0, hair='cap', arm='down'),
   dict(x=1420, y=672, h=86, skin=2, cloth=4, hair='short', arm='hold')],
 names=[dict(x=140, t='Josie, four nights a week, nine years'),
   dict(x=270, t='her manager, "a step up", eleven times'),
   dict(x=400, t='the eight others on the night rota'),
   dict(x=1280, t='a student locked out, 23.40'),
   dict(x=1420, t='the author of the restructure paper'),
   dict(x=760, t='the corridor at four in the morning'),
   dict(x=1000, t='the logbook, nine years of entries'),
   dict(x=900, t='a table with glasses and nothing else')],
 markers=[dict(x=140, y=552), dict(x=270, y=552), dict(x=400, y=552), dict(x=1280, y=552),
   dict(x=1420, y=552), dict(x=760, y=606), dict(x=1000, y=606), dict(x=900, y=620),
   dict(x=1090, y=618), dict(x=1500, y=620), dict(x=630, y=610), dict(x=1130, y=610)]),

"fig_b13_u10_p01_v08": dict(type='V8', height=800,
 title='What an occasion is made of',
 sub='Six nodes. The one at the bottom is the only one the speaker controls.',
 alt='A network from the occasion and the audience through the address and its cadence to the '
     'applause, with what is actually said shown as the one controllable node.',
 nodes={
  'occ': dict(x=170, y=230, short='1', name='The occasion', sub='and it is in the room too',
              colour='#1F4E5F'),
  'aud': dict(x=170, y=570, short='2', name='The audience', sub='forty chairs, in rows',
              colour='#9AA7AE'),
  'add': dict(x=540, y=400, short='3', name='The address', sub='a few words, meaning four minutes',
              colour='#C86B2B'),
  'cad': dict(x=900, y=230, short='4', name='Cadence', sub='audible in a language you do not speak',
              colour='#D9A441'),
  'app': dict(x=1270, y=400, short='5', name='Applause', sub='which measures nothing',
              r=50, colour='#9AA7AE'),
  'sai': dict(x=900, y=600, short='6', name='What is said', sub='the only part you decide',
              r=56, colour='#2E6F5E')},
 edges=[dict(a='occ', b='add', label='the occasion requires one', sw=6),
   dict(a='aud', b='add', label='and sets the length nobody states', sw=6),
   dict(a='add', b='cad', label='rhythm, before meaning', sw=6),
   dict(a='cad', b='app', label='and it will come whatever you say', sw=2, dash='6 6',
        colour='#9AA7AE'),
   dict(a='add', b='sai', label='one number, written down', sw=6, colour='#2E6F5E'),
   dict(a='sai', b='app', label='and this is the part still there in two years', sw=6,
        colour='#2E6F5E')]),

"fig_b13_u10_p02_v07": dict(type='V7', height=820,
 title='The lodge, two days before the event',
 sub='One of them has the keys. One of them signed the paper.',
 alt='A night supervisor and a manager in a lodge with a logbook between them, their speech '
     'shown as inverted sentences.',
 bg='#E6E9EC',
 set=[dict(kind='table', x=700, y=700, s=1.4), dict(kind='doc', x=700, y=628)],
 people=[dict(x=470, h=250, skin=4, cloth=3, hair='grey', arm='point', facing='right',
   label='Josie', role='four nights a week, nine years',
   says=['Never have I been so clear about what I want and so unable to say it.',
     'Not until the email went out did anybody ask me.']),
  dict(x=980, h=248, skin=1, cloth=2, hair='bun', arm='hold', facing='left',
   label='her manager', role='signed off in March',
   says=['No sooner had the restructure been signed off than my name was on it.'])]),

"fig_b13_u10_p03_v09": dict(type='V9', kind='mirror', height=700,
 title='The question operation, used for emphasis',
 sub='Front the negative and the sentence inverts exactly as a question does.',
 alt='Two sentence diagrams comparing I have never been so clear with never have I been so '
     'clear, showing the auxiliary moving in front of the subject.',
 active=dict(parts=[dict(w=14, role='agent', text='I'),
   dict(w=20, role='action', text='have never been'),
   dict(w=28, role='affected', text='so clear'),
   dict(w=24, role='hidden', text='ordinary order - no emphasis')]),
 passive=dict(parts=[dict(w=16, role='affected', text='Never'),
   dict(w=16, role='action', text='have'),
   dict(w=14, role='agent', text='I'),
   dict(w=20, role='action', text='been so clear'),
   dict(w=20, role='hidden', text='and a pause after Never')]),
 rule='The auxiliary moves in front of the subject, exactly as in a question. If there is no '
      'auxiliary, English supplies do or did: nobody asked becomes not until Friday did anybody '
      'ask. No sooner takes than, never when.'),

"fig_b13_u10_p03_v11": dict(type='V11', height=720,
 title='No sooner, and the conjunction it borrowed',
 alt='Two panels comparing no sooner had it been signed when my name was on it with the same '
     'sentence using than.',
 wrong=dict(sentence='No sooner had it been signed when my name was on it.',
            boundary=0.52, boundary_label='no sooner had it been signed',
            event=0.60, event_label='and when arrives, which belongs to hardly',
            why='No sooner is a comparative - sooner than - so the second clause is introduced '
                'by than. When belongs to the neighbouring structure, hardly had it been signed '
                'when, and learners borrow it because the two patterns mean the same thing and '
                'sit side by side on every list.'),
 right=dict(sentence='No sooner had it been signed than my name was on it.',
            boundary=0.52, boundary_label='no sooner had it been signed',
            event=0.62, event_label='and than completes the comparison',
            why='Sooner is a comparative form and every comparative in English takes than. Once '
                'you hear no sooner as not any sooner than, the conjunction stops being '
                'arbitrary and there is nothing left to remember.'),
 misconception='This is the single most common error with inversion, and it is not really about '
               'inversion at all: it is a comparative that has stopped looking like one. Hardly '
               'and scarcely take when. No sooner takes than, because sooner is a comparative.'),

"fig_b13_u10_p04_v04": dict(type='V4', height=760,
 title='The speech as written, and the speech as given',
 sub='Learner A has the draft. Learner B has the recording.',
 alt='Two panels compared: a written address with five inversions and the delivered version with '
     'two, and the sentences cut in the room.',
 differences=7, prompt='Which two sentences were cut, and what did the speaker hear in the room '
                       'that told her to cut them?',
 left=dict(label='as written, the night before', art=[
   dict(kind='block', x=140, y=20, w=230, bh=18, colour='#C86B2B'),
   dict(kind='block', x=140, y=52, w=230, bh=18, colour='#C86B2B'),
   dict(kind='block', x=140, y=84, w=230, bh=18, colour='#C86B2B'),
   dict(kind='block', x=140, y=116, w=230, bh=18, colour='#C86B2B'),
   dict(kind='block', x=140, y=148, w=230, bh=18, colour='#C86B2B'),
   dict(kind='label', x=300, y=220, text='five inversions in four minutes', colour='#A8372E')]),
 right=dict(label='as given, on the Friday', art=[
   dict(kind='block', x=140, y=36, w=230, bh=18, colour='#2E6F5E'),
   dict(kind='gap', x=140, y=68, w=230, bh=18),
   dict(kind='block', x=140, y=100, w=230, bh=18, colour='#2E6F5E'),
   dict(kind='gap', x=140, y=132, w=230, bh=18),
   dict(kind='label', x=300, y=220, text='two inversions, and a number', colour='#2E6F5E')])),

"fig_b13_u10_p05_v05": dict(type='V5', height=1080,
 title='The restructure paper and the night log',
 sub='One week of entries, set against the paragraph that describes the job.',
 alt='A restructure paper paragraph on night cover beside a week of night log entries sorted by '
     'category, with one line appearing in both.',
 rows=[dict(t='org', text='ESTATES RESTRUCTURE  -  PAPER 3  -  NIGHT COVER'),
   dict(t='para', text='"Night cover will be maintained through a revised rota and, from March, '
     'a contracted out-of-hours service. The current night establishment (9 FTE) will reduce to '
     '4 FTE, with supervisory capacity transferred to the day team. Consultation has taken '
     'place with the Estates management group."'),
   dict(t='kv', k='Night establishment now', v='9', mono=True),
   dict(t='kv', k='From March', v='4, plus a contract', mono=True),
   dict(t='kv', k='Consulted', v='the Estates management group', mono=False),
   dict(t='kv', k='Night staff on that group', v='0', mono=True),
   dict(t='rule'),
   dict(t='head', text='NIGHT LOG  -  ONE WEEK, 209 ENTRIES'),
   dict(t='grid', cols=['CATEGORY', 'ENTRIES', 'IN THE JOB DESCRIPTION?'],
     data=[['locked out of a building', '41', 'no'],
           ['locked out of an office', '18', 'no'],
           ['directions, lost on site', '26', 'no'],
           ['someone distressed, talked to', '11', 'no'],
           ['alarm, checked, no cause', '34', 'yes'],
           ['door or window insecure', '29', 'yes'],
           ['contractor access', '22', 'yes'],
           ['patrol, nothing to report', '28', 'yes']]),
   dict(t='para', text='Ninety-six of two hundred and nine are not in the job description. They '
     'are what happens when the person with the keys is the only person awake.'),
   dict(t='rule'),
   dict(t='sign', text='ONE LINE OF THE LOG, REWORDED, APPEARS IN THE PAPER:'),
   dict(t='para', text='Log: "23.40 student locked out of Menzies, let in, upset about results, '
     'sat with for 20 min." Paper: "Out-of-hours access requests will be handled by the '
     'contracted service."')],
 callouts=[dict(at=0.10, text='Maintained through a revised rota. Nine to four'),
   dict(at=0.20, text='Consultation with a group that contains nobody who works nights'),
   dict(at=0.44, text='Forty-one lockouts in one week, and not in anybody\'s job description'),
   dict(at=0.56, text='Eleven conversations with somebody distressed. Also not in it'),
   dict(at=0.74, text='Ninety-six of two hundred and nine. Nearly half the week'),
   dict(at=0.95, text='Twenty minutes becomes an access request. Both sentences are true')]),

"fig_b13_u10_p07_v10": dict(type='V10', kind='pitch', height=680,
 title='The fronted word, and the pause after it',
 sub='Three deliveries. The grammar is identical in all three.',
 alt='Three pitch contours comparing never have I been so clear with and without a pause after '
     'the fronted word.',
 contours=[dict(text='NEVER | have I been so clear.',
     points=[.75, .4, .3, .25, .2, .1, .0, -.45],
     meaning='stress, then a pause - and it is a moment'),
   dict(text='Never have I been so clear.',
     points=[.4, .35, .3, .3, .25, .15, .05, -.4],
     meaning='no pause - grammatically identical, and it is just a sentence'),
   dict(text='I did not ASK for this.',
     points=[.3, .25, .3, .7, .4, .2, .1, -.5],
     meaning='stress on ask - it was given, and I had no part in it')]),

"fig_b13_u10_p08_v02": dict(type='V2', height=820,
 title='A formal address, in section',
 sub='Four layers. There are exactly two inversions and both are in the middle two.',
 alt='A cutaway of a formal address in four layers from the opening and the acknowledgement to '
     'the turn and the landing.',
 floors=[dict(was='the opening', now='Names the occasion, and does one small true thing',
     year='', fill='#E4ECEF'),
   dict(was='the acknowledgement', now='Somebody specific, something specific, and a number',
     year='', fill='#EFE2DD'),
   dict(was='the turn', now='The second inversion, and it concedes something', year='',
     fill='#F6F0E4'),
   dict(was='the landing', now='Ordinary word order. Two short sentences. Then stop', year='',
     fill='#F2EDE2')],
 callouts=[dict(at=0.12, text='One true thing buys the next three minutes'),
   dict(at=0.38, text='A number is the only part of a tribute that survives the week'),
   dict(at=0.62, text='A turn that concedes nothing is a complaint with better grammar'),
   dict(at=0.88, text='End on an inversion and the room hears the structure, not the sentence')]),

"fig_b13_u10_p09_v05": dict(type='V5', height=1060,
 title='Fifty minutes, four decisions, one of them real',
 sub='A restructure meeting, with what each item actually was.',
 alt='A record of a fifty-minute meeting with four agenda items annotated as decide, announce, '
     'consult or be seen to consult.',
 rows=[dict(t='org', text='WORK FILE  -  THE MEETING  -  ESTATES RESTRUCTURE, 50 MIN'),
   dict(t='grid', cols=['ITEM', 'MIN', 'WHAT IT WAS'],
     data=[['1 contract award', '0-6', 'announce - the contract was signed in February'],
           ['2 night establishment', '6-28', 'be seen to consult - paper already with the Board'],
           ['3 supervisory structure', '28-41', 'consult - and it moved'],
           ['4 event arrangements', '41-50', 'decide - and it was decided in the room']]),
   dict(t='para', text='Items 1 and 2 were already settled. Item 3 moved, and item 4 was the '
     'only one on which anybody present had both the authority and the information to decide.'),
   dict(t='rule'),
   dict(t='head', text='HOW TO TELL ITEM 2 FROM ITEM 3'),
   dict(t='para', text='Somebody asked the same question at both: "What would have to be true '
     'for this to change?"'),
   dict(t='kv', k='Answer at item 2', v='a pause, then a restatement of the benefits',
        mono=False),
   dict(t='kv', k='Answer at item 3', v='"a costed alternative by the 14th"', mono=False),
   dict(t='kv', k='Did anything change at item 2', v='no', mono=False),
   dict(t='kv', k='Did anything change at item 3', v='yes - two posts', mono=False),
   dict(t='rule'),
   dict(t='head', text='ELEVEN SECONDS THAT CHANGED AN OUTCOME'),
   dict(t='para', text='"If the supervisor is on days, who signs the contractor in at two in '
     'the morning?" Nobody had an answer. One post was added back at item 3 as a result, and it '
     'is in the minutes as a technical amendment.'),
   dict(t='rule'),
   dict(t='sign', text='WHAT THE MINUTES SAY ABOUT ITEM 2:'),
   dict(t='para', text='"The group discussed the revised night establishment and noted the '
     'proposals." Twenty-two minutes, and that is the whole record of them.')],
 callouts=[dict(at=0.16, text='Signed in February. The meeting is in April'),
   dict(at=0.22, text='Twenty-two minutes on something already with the Board'),
   dict(at=0.30, text='Thirteen minutes, and this is the one that moved'),
   dict(at=0.60, text='A pause and a restatement. That is the tell, every time'),
   dict(at=0.82, text='Eleven seconds, one question, one post added back'),
   dict(at=0.95, text='Twenty-two minutes become seven words in the minutes')]),

"fig_b13_u10_p10_v12": dict(type='V12', height=900,
 title='Nine years, four minutes, and the number that survived',
 sub='Half the class sees the paper. Half sees the log. Rebuild it by speaking.',
 alt='An infographic from nine years ago to the first semester under the contract, showing night '
     'staffing, lockouts and what was recorded.',
 span=['9 yrs ago', 'next yr'], ticks=6,
 tick_labels=['-9 yr', '-1 yr', 'the paper', 'the event', 'March', 'sem 1'],
 bands=[dict(name='Night establishment', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.72}, label='9 staff, four nights each', colour='#1F4E5F'),
   dict(**{'from': 0.72, 'to': 1.0}, label='4 staff, plus a contracted service',
     colour='#C86B2B')]),
  dict(name='Who held the keys', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.72}, label='a person who was awake and knew the building',
     colour='#2E6F5E'),
   dict(**{'from': 0.72, 'to': 1.0}, label='a telephone number, and a logged callout',
     colour='#9AA7AE')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.46, label='paper signed. Her name on a list, between two strangers',
     colour='#A8372E'),
   dict(at=0.54, label='two questions asked. Eleven days for an answer', colour='#D9A441'),
   dict(at=0.62, label='four minutes, forty chairs, and one number read out',
     colour='#8C6A9E'),
   dict(at=0.76, label='March: contract starts. Lockouts have to be logged', colour='#1F4E5F'),
   dict(at=0.94, label='19 callouts a week, against an estimated 7', colour='#2E6F5E')]),
  dict(name='Lockouts recorded per week', type='line',
   points=[(0, 0), (0.4, 0), (0.62, 0), (0.76, 19), (0.9, 19), (1.0, 19)], end_label='19'),
  dict(name='What nobody did', type='flags', items=[
   dict(at=0.24, label='write down what the person with the keys actually did'),
   dict(at=0.50, label='ask anybody who works nights, before the list'),
   dict(at=0.84, label='put lockouts in the contract'),
   dict(at=0.98, label='notice that the number only exists because it is now a cost')])]),

"fig_b13_u10_p11_v06": dict(type='V6', kind='bar', height=840,
 title='What the night log actually records',
 sub='One week, 209 entries, sorted by whether anybody is paid to do it.',
 alt='A bar chart of one week of night log entries by category, split into those in the job '
     'description and those not.',
 labels=['Lockouts', 'Directions', 'Distress', 'Alarms', 'Insecure', 'Patrol'],
 ymin=0, ymax=70, fmt='{:,.0f}',
 series=[dict(name='entries this week', values=[59, 26, 11, 34, 29, 28], colour='#1F4E5F'),
   dict(name='in the job description', values=[0, 0, 0, 34, 29, 28], colour='#2E6F5E'),
   dict(name='in the restructure paper', values=[0, 0, 0, 34, 29, 28], colour='#D9A441')],
 note='One week, 209 entries. Lockouts combines buildings (41) and offices (18).',
 warning='Ninety-six of two hundred and nine entries are in neither the job description nor the '
         'restructure paper, and all ninety-six stop in March.'),
}
