# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C7-1': ('case item C7-1', []),
    'C7-2': ('case item C7-2', []),
    'C7-3': ('case item C7-3', []),
    'C7-4': ('case item C7-4', []),
    'C7-5': ('case item C7-5', []),
    'C7-6': ('case item C7-6', []),
    'P7-01': ('practice item P7-01', []),
    'P7-02': ('practice item P7-02', []),
    'P7-03': ('practice item P7-03', []),
    'P7-04': ('practice item P7-04', []),
    'P7-05': ('practice item P7-05', []),
    'P7-06': ('practice item P7-06', []),
    'P7-07': ('practice item P7-07', []),
    'P7-08': ('practice item P7-08', []),
    'P7-09': ('practice item P7-09', []),
    'P7-10': ('practice item P7-10', []),
    'P7-11': ('practice item P7-11', []),
    'P7-12': ('practice item P7-12', []),
    'P7-13': ('practice item P7-13', []),
    'P7-14': ('practice item P7-14', []),
    'P7-15': ('practice item P7-15', []),
    'P7-16': ('practice item P7-16', []),
    'P7-17': ('practice item P7-17', []),
    'SC7-1': ('section-check item SC7-1', []),
    'SC7-2': ('section-check item SC7-2', []),
    'SC7-3': ('section-check item SC7-3', []),
    'SC7-4': ('section-check item SC7-4', []),
    'SC7-5': ('section-check item SC7-5', []),
    'SC7-6': ('section-check item SC7-6', []),
    'SC7-7': ('section-check item SC7-7', []),
    'SC7-8': ('section-check item SC7-8', []),
    'SC7-9': ('section-check item SC7-9', []),
    'term:abnormal waste': ("term-bridge row 'abnormal waste'", []),
    'term:consignee': ("term-bridge row 'consignee'", []),
    'term:consignment': ("term-bridge row 'consignment'", []),
    'term:consignor': ("term-bridge row 'consignor'", []),
    'term:cost flow assumption': ("term-bridge row 'cost flow assumption'", []),
    'term:cost of goods sold': ("term-bridge row 'cost of goods sold'", []),
    'term:counterbalancing error': ("term-bridge row 'counterbalancing error'", []),
    'term:fifo (first-in, first-out)': ("term-bridge row 'FIFO (first-in, first-out)'", []),
    'term:fob destination': ("term-bridge row 'FOB destination'", []),
    'term:fob shipping point': ("term-bridge row 'FOB shipping point'", []),
    'term:freight-in': ("term-bridge row 'freight-in'", []),
    'term:freight-out': ("term-bridge row 'freight-out'", []),
    'term:goods available for sale': ("term-bridge row 'goods available for sale'", []),
    'term:goods in transit': ("term-bridge row 'goods in transit'", []),
    'term:gross profit': ("term-bridge row 'gross profit'", []),
    'term:inventoriable cost': ("term-bridge row 'inventoriable cost'", []),
    'term:inventory': ("term-bridge row 'inventory'", []),
    'term:lifo (last-in, first-out)': ("term-bridge row 'LIFO (last-in, first-out)'", []),
    'term:lifo conformity rule': ("term-bridge row 'LIFO conformity rule'", []),
    'term:lifo liquidation': ("term-bridge row 'LIFO liquidation'", []),
    'term:lifo reserve': ("term-bridge row 'LIFO reserve'", []),
    'term:moving average': ("term-bridge row 'moving average'", []),
    'term:normal capacity': ("term-bridge row 'normal capacity'", []),
    'term:period cost': ("term-bridge row 'period cost'", []),
    'term:periodic inventory system': ("term-bridge row 'periodic inventory system'", []),
    'term:perpetual inventory system': ("term-bridge row 'perpetual inventory system'", []),
    'term:physical count': ("term-bridge row 'physical count'", []),
    'term:purchase discount': ("term-bridge row 'purchase discount'", []),
    'term:specific identification': ("term-bridge row 'specific identification'", []),
    'term:weighted-average cost': ("term-bridge row 'weighted-average cost'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C7-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
}
