"""A1.2 Unit 1 - Nine Days In - fifteen figures, as data."""
FIGURES = {
"fig_a12_u01_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='Four cars, ten past two in the morning',
 sub='Fourteen things to find. One berth has a bag in it and nobody in it.',
 alt='Four cars of a long-distance train drawn in section at two in the morning: a sleeping car '
     'with eleven berths and one light on, a dark dining car with one person doing paperwork, a '
     'lit kitchen with the cook awake, and a small service cubicle at the end.',
 sky='#2F3B45', ground='#6B6256', ground_line=700,
 buildings=[dict(x=20, w=420, storeys=3, colour='#7E8B93', cutaway=True,
     floor_labels=['the upper berths - nine asleep',
                   'the lower berths - one light on',
                   'the corridor'],
     label='the sleeping car - eleven berths'),
   dict(x=500, w=380, storeys=2, colour='#6F7B84', cutaway=True,
     floor_labels=['the luggage rack', 'one table in use'],
     label='the dining car - closed at nine'),
   dict(x=940, w=320, storeys=2, colour='#D7C27E', cutaway=True,
     floor_labels=['the store', 'the kitchen'],
     label='the kitchen - lit, at two in the morning'),
   dict(x=1320, w=260, storeys=2, colour='#8A949A', cutaway=True,
     floor_labels=['the roof', 'the log'],
     label='the service manager')],
 props=[dict(kind='table', x=620, y=700, s=1.1), dict(kind='chair', x=580, y=700, s=1.0),
   dict(kind='cup', x=700, y=654, s=1.4),
   dict(kind='box', x=300, y=700, s=1.0),
   dict(kind='crate', x=1020, y=700, s=1.0),
   dict(kind='sign', x=460, y=700, s=.7, text='2:10'),
   dict(kind='doc', x=1400, y=700, s=1.0) if False else dict(kind='box', x=1400, y=700, s=.8)],
 people=[dict(x=200, y=700, h=86, skin=2, cloth=4, hair='long', arm='down'),
   dict(x=660, y=700, h=86, skin=4, cloth=3, hair='short', arm='hold'),
   dict(x=1060, y=700, h=86, skin=1, cloth=0, hair='bun', arm='point'),
   dict(x=1180, y=700, h=86, skin=3, cloth=2, hair='cap', arm='hold'),
   dict(x=1420, y=700, h=86, skin=0, cloth=1, hair='grey', arm='folded')],
 names=[dict(x=200, t='one berth with a bag and nobody in it'),
   dict(x=660, t='Dev - nine days in, doing paperwork'),
   dict(x=1060, t='Ruth - twenty-three years, already awake'),
   dict(x=1180, t='the second cook - the third sitting is where you learn things'),
   dict(x=1420, t='Nadia - on shift since six'),
   dict(x=460, t='the clock: ten past two'),
   dict(x=300, t='the luggage nobody claimed at Winnipeg'),
   dict(x=700, t='the only cup still warm on the train')],
 markers=[dict(x=200, y=582), dict(x=660, y=582), dict(x=1060, y=582), dict(x=1180, y=582),
   dict(x=1420, y=582), dict(x=460, y=636), dict(x=300, y=652), dict(x=700, y=656),
   dict(x=620, y=656), dict(x=580, y=664), dict(x=1020, y=660), dict(x=1400, y=652),
   dict(x=200, y=466), dict(x=200, y=350)]),

"fig_a12_u01_p01_v08": dict(type='V8', height=780,
 title='Who tells whom',
 sub='Five people on one train. Two of the lines only go one way, and that is where the trouble '
     'starts.',
 alt='The crew drawn as a network - service manager, sleeping-car attendant, cook, guard and '
     'engineer - with labelled lines showing who passes information to whom, two of them drawn '
     'with a single arrow.',
 nodes={
  'nad': dict(x=800, y=180, short='N', name='Nadia', sub='service manager, 11 years', r=56,
              colour='#1F4E5F'),
  'dev': dict(x=380, y=400, short='D', name='Dev', sub='attendant, 9 days', colour='#C86B2B'),
  'rut': dict(x=800, y=620, short='R', name='Ruth', sub='cook, 23 years', colour='#D9A441'),
  'gua': dict(x=1240, y=400, short='G', name='the guard', sub='never sees a passenger',
              colour='#2E6F5E'),
  'eng': dict(x=1420, y=180, short='E', name='the engineer', sub='at the front, alone',
              colour='#8C6A9E'),
  'pas': dict(x=640, y=700, short='192', name='the passengers', sub='192 of them', r=50,
              colour='#9AA7AE')},
 edges=[dict(a='eng', b='nad', label='why we stopped', sw=4),
   dict(a='nad', b='dev', label='what to tell people', sw=6),
   dict(a='dev', b='pas', label='the announcement', sw=6),
   dict(a='dev', b='rut', label='we need two hundred sandwiches', sw=5),
   dict(a='gua', b='nad', label='one way only - he reports, nobody tells him', sw=3,
        dash='7 6', colour='#A8372E'),
   dict(a='pas', b='nad', label='one way only - they ask, and he answers', sw=3, dash='7 6',
        colour='#A8372E')]),

"fig_a12_u01_p01_v02a": dict(type='V2', height=780,
 title='One shift, in section',
 sub='Eleven events. Eleven words. The thickest band is between midnight and two.',
 alt='A cutaway of one twelve-hour shift from six in the evening to six in the morning, with '
     'what happened in each band and empty labels.',
 floors=[dict(was='18.00 to 19.00', now='start the shift · check the tickets · the train does not move',
     year='', fill='#E8EEF0'),
   dict(was='19.00 to 23.00', now='the delay · the dining car closes · 192 people wait',
     year='', fill='#F3EADA'),
   dict(was='23.00 to 02.00', now='the kitchen · 200 sandwiches · the announcement',
     year='', fill='#EFE6DC'),
   dict(was='02.00 to 06.00', now='the report · one line · NO INCIDENTS', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The hour before the train leaves is the whole job'),
   dict(at=0.38, text='Four hours in which the only thing anybody did was wait'),
   dict(at=0.62, text='Three hours that are not in any document'),
   dict(at=0.88, text='Eleven words, and they will outlive everybody on this train')]),

"fig_a12_u01_p02_v07": dict(type='V7', height=820,
 title='The corridor, two in the morning',
 sub='Nine days against eleven years, and a notebook between them.',
 alt='A service manager and a new attendant standing in a train corridor at two in the morning '
     'with a notebook on a folding table between them, each with two speech balloons and a '
     'thought balloon.',
 bg='#DDE3E4',
 set=[dict(kind='table', x=760, y=660, s=1.6), dict(kind='cup', x=820, y=614, s=1.4),
   dict(kind='box', x=1340, y=660, s=1.0)],
 people=[dict(x=520, h=240, skin=4, cloth=3, hair='short', arm='hold', facing='right',
   label='Dev', role='nine days on the job',
   says=['We left at eleven. I went to the kitchen.',
         'Ruth got up. We made two hundred sandwiches.'],
   thinks=['Do I say I was frightened?']),
  dict(x=1080, h=240, skin=0, cloth=1, hair='grey', arm='point', facing='left',
   label='Nadia', role='eleven years, and four hundred reports',
   says=['Nobody said anything. Nobody complained.',
         'What happened at half past eleven?'],
   thinks=['There is no box on the form for this.'])]),

"fig_a12_u01_p03_v09a": dict(type='V9', kind='weight', height=520,
 title='Bolted on, or changed inside',
 sub='A regular verb grows a piece at the end. An irregular one changes in the middle.',
 alt='Two rows of word boxes: regular verbs with -ed drawn as a separate piece bolted on the '
     'end, and irregular verbs with the vowel in the middle drawn in a different colour.',
 parts=[dict(w=20, role='regular', text='arriv', colour='#1F4E5F'),
   dict(w=12, role='bolted on', text='+ ed', colour='#9AA7AE'),
   dict(w=16, role='irregular', text='c', colour='#2E6F5E'),
   dict(w=12, role='the vowel moves', text='a', colour='#C86B2B'),
   dict(w=16, role='and the rest stays', text='me', colour='#2E6F5E'),
   dict(w=24, role='no pattern at all', text='go → went', colour='#A8372E')],
 note='Regular: the word is untouched and something is added. Irregular: nothing is added and '
      'the inside changes. About 180 verbs do the second thing, and they are the 180 you will '
      'use most often.'),

"fig_a12_u01_p03_v09b": dict(type='V9', kind='timeline', height=760,
 title='The words that hold a story together',
 sub='Five on the line, one above it, and one drawn as a bracket over two things at once.',
 alt='A timeline with the sequence words first, then, next, after that and finally placed in '
     'order, suddenly marked above the line as an interruption, and while drawn as a bracket '
     'over two simultaneous events.',
 now=0.94,
 bands=[dict(**{'from': 0.04, 'to': 0.04}, type='event', lane=1, label='first',
     example='We left at eleven'),
   dict(**{'from': 0.24, 'to': 0.24}, type='event', lane=1, label='then',
     example='the dining car closed'),
   dict(**{'from': 0.44, 'to': 0.44}, type='event', lane=1, label='next',
     example='I went to the kitchen'),
   dict(**{'from': 0.62, 'to': 0.62}, type='event', lane=1, label='after that',
     example='Ruth got up'),
   dict(**{'from': 0.86, 'to': 0.86}, type='event', lane=1, label='finally',
     example='Nadia made the announcement'),
   dict(**{'from': 0.16, 'to': 0.16}, type='event', lane=4, label='SUDDENLY',
     example='nobody planned this one'),
   dict(**{'from': 0.44, 'to': 0.72}, type='span', lane=3, label='WHILE',
     example='two things at once, and the long one takes while')]),

"fig_a12_u01_p03_v11": dict(type='V11', height=700,
 title='The ending on a word that had already changed',
 alt='Two panels comparing goed with went, the first showing the regular ending bolted on to a '
     'verb that has already changed inside.',
 wrong=dict(sentence='He goed to the kitchen.',
            boundary=0.34, boundary_label='go',
            event=0.62, event_label='+ ed, on a word that does not take it',
            why='The -ed rule is real and it covers most verbs, so the ear reaches for it. But '
                'go has already made its past by replacing itself completely. Adding the ending '
                'is like paying twice: the listener hears the correction before they hear the '
                'meaning.'),
 right=dict(sentence='He went to the kitchen.',
            boundary=0.34, boundary_label='went',
            event=0.50, event_label='one word, and no ending at all',
            why='Went is the past of go and it shares no letters with it. There is no rule to '
                'learn here and nothing to work out - it is one of about ten verbs in English '
                'whose past is a different word, and all ten are among the commonest words in '
                'the language.'),
 misconception='Irregular verbs feel like exceptions to be memorised later. They are not the '
               'edge of the language, they are the middle of it: the twenty commonest verbs in '
               'English are almost all irregular, because the words people use most often are '
               'the ones that resist tidying up.'),

"fig_a12_u01_p04_v04a": dict(type='V4', height=720,
 title='The same four hours, told twice',
 sub='On the left, the order things happened. On the right, the order they were remembered.',
 alt='Two accounts of the same four hours side by side, one in chronological order and one in '
     'the order the speaker recalled the events.',
 differences=6, prompt='Find the six. One of the two can be followed by somebody who was not '
                       'there. Which, and what is it that the other one is missing?',
 left=dict(label='in order', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='19.00 · 21.00 · 23.00 · 00.30 — four times, in order',
        colour='#2E6F5E')]),
 right=dict(label='as remembered', art=[
   dict(kind='block', x=150, y=130, w=160, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='block', x=150, y=66, w=220, bh=22, colour='#C86B2B'),
   dict(kind='label', x=300, y=210,
        text='the sandwiches · oh and before that · no wait — no times at all',
        colour='#C86B2B')])),

"fig_a12_u01_p05_v05": dict(type='V5', height=860,
 title='The crew log for that night',
 sub='Nine boxes. Eight of them are numbers and the ninth says NONE.',
 alt='The company crew log for one night, showing the date, train number, scheduled and actual '
     'departure, the delay in hours, a reason code, an incidents box containing the word NONE, '
     'and a signature.',
 rows=[dict(t='org', text='PRAIRIE LINE  -  CREW LOG  -  TRAIN 062'),
   dict(t='grid', cols=['FIELD', 'ENTRY', 'BY'],
     data=[['DATE', '14 MAY', 'N.O.'],
           ['SCHEDULED DEP.', '19.00', '--'],
           ['ACTUAL DEP.', '23.04', 'N.O.'],
           ['DELAY', '4 H 04', 'AUTO'],
           ['REASON CODE', 'F3 - FREIGHT', 'N.O.'],
           ['ARRIVAL', '+3 H 51', 'AUTO'],
           ['CREW ON DUTY', '6', 'AUTO'],
           ['PASSENGERS', '192', 'AUTO']]),
   dict(t='rule'),
   dict(t='head', text='INCIDENTS'),
   dict(t='sign', text='NONE'),
   dict(t='rule'),
   dict(t='kv', k='Signed', v='N. Okafor, Service Manager', mono=False),
   dict(t='kv', k='Time signed', v='02.41', mono=True),
   dict(t='rule'),
   dict(t='para', text='Reason code F3 means the delay was caused by a freight movement. It '
     'records the cause and not the fault, which is deliberate: the company has twenty-two '
     'reason codes and none of them names anybody.')],
 callouts=[dict(at=0.14, text='Four hours and four minutes, measured by a machine'),
   dict(at=0.26, text='F3. A cause, and carefully not a person'),
   dict(at=0.46, text='A hundred and ninety-two, counted automatically'),
   dict(at=0.62, text='The one box a human had to think about, and it says NONE'),
   dict(at=0.80, text='Signed at twenty to three, after a twelve-hour shift')]),

"fig_a12_u01_p06_v03a": dict(type='V3',
 title='Four hours, six panels',
 sub='Each panel carries its own sequence word. Only one of them was planned by nobody.',
 alt='Six panels showing the four hours of the delay in order, each labelled with the sequence '
     'word that belongs to it, with the fourth marked suddenly.',
 panels=[
  dict(caption='FIRST - 19.00, the train does not move',
       art=[dict(kind='block', x=160, y=0, w=130, bh=46, colour='#9AA7AE')]),
  dict(caption='THEN - 21.00, the dining car closes',
       art=[dict(kind='cross', x=160, y=40)]),
  dict(caption='NEXT - 23.00, Dev goes to the kitchen',
       art=[dict(kind='person', x=160, y=0, h=110, skin=4, cloth=3)]),
  dict(caption='SUDDENLY - Ruth gets up',
       art=[dict(kind='person', x=160, y=0, h=110, skin=1, cloth=0, arm='point')]),
  dict(caption='AFTER THAT - 200 sandwiches',
       art=[dict(kind='block', x=160, y=0, w=140, bh=80, colour='#D9A441')]),
  dict(caption='FINALLY - the announcement',
       art=[dict(kind='tick', x=160, y=50)])]),

"fig_a12_u01_p07_v10": dict(type='V10', kind='groups', height=700,
 title='The vowel in the middle',
 sub='The consonants do not move. One sound in the middle does all the work.',
 alt='Three columns of irregular verbs grouped by the vowel change between present and past, '
     'with the rule for each group written underneath.',
 groups=[
  dict(ipa='i → a', colour='#1F4E5F', rule='the commonest change of all',
       words=['begin → began', 'sit → sat', 'give → gave', 'drink → drank',
              'swim → swam'],
       before='the consonants on both sides are identical in every pair'),
  dict(ipa='ee → e', colour='#2E6F5E', rule='the vowel gets shorter, not different',
       words=['meet → met', 'feel → felt', 'keep → kept', 'read → read',
              'sleep → slept'],
       before='read is spelled the same twice - only the length tells you which'),
  dict(ipa='a new word', colour='#A8372E', rule='no pattern, and no help',
       words=['go → went', 'be → was / were', 'put → put', 'cut → cut',
              'let → let'],
       before='the last three change nothing at all, which is the hardest kind to hear')]),

"fig_a12_u01_p09_v02b": dict(type='V2', height=780,
 title='What a notebook records',
 sub='Four layers. The thickest one is the one nobody writes down.',
 alt='A cutaway of a learner\'s month showing corrected errors at the top, looked-up words below '
     'that, then things that have become automatic, and at the bottom a thick layer labelled not '
     'recorded anywhere.',
 floors=[dict(was='corrected in class', now='about 40 errors, in red, in the margin', year='',
     fill='#E8EEF0'),
   dict(was='looked up', now='about 60 words, in a list, in order of accident', year='',
     fill='#F3EADA'),
   dict(was='hard in week 1', now='about 15 things, and all of them are automatic now',
     year='', fill='#EFE6DC'),
   dict(was='not recorded anywhere', now='every single one of those fifteen', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='A full page of what you are bad at'),
   dict(at=0.38, text='A list you will not open again'),
   dict(at=0.62, text='The only layer that is actually progress'),
   dict(at=0.88, text='And there is no box on the form for it')]),

"fig_a12_u01_p09_v03b": dict(type='V3',
 title='Five panels, and the fifth is empty',
 sub='Everything up to panel four gets written down. Panel five is the one that matters.',
 alt='Five panels: making a mistake, being corrected, writing the correction down, not making '
     'the mistake again, and nobody noticing - the last panel left empty.',
 panels=[
  dict(caption='1 You make the mistake',
       art=[dict(kind='cross', x=150, y=50)]),
  dict(caption='2 Somebody corrects it',
       art=[dict(kind='person', x=150, y=0, h=110, skin=0, cloth=1, arm='point')]),
  dict(caption='3 You write it down',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='4 Three weeks later: no mistake',
       art=[dict(kind='tick', x=150, y=50)]),
  dict(caption='5 And nobody writes that down',
       art=[dict(kind='gap', x=150, y=20, w=120, bh=70)])]),

"fig_a12_u01_p10_v12": dict(type='V12',
 title='Four hours, four records',
 sub='The band at the bottom is almost empty, and it is the only one that survived the night.',
 alt='An infographic of the four-hour delay with bands for where the train was, what the crew '
     'did, what the passengers knew and what the log recorded.',
 span=['19.00', '23.30'], ticks=4,
 tick_labels=['19.00', '20.30', '22.00', '23.30'],
 bands=[dict(name='The train', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.86}, label='stationary, 80 km behind a broken freight train',
        colour='#9AA7AE'),
   dict(**{'from': 0.88, 'to': 1.0}, label='moving', colour='#2E6F5E')]),
  dict(name='The crew', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.26}, label='tickets, and then nothing to do', colour='#1F4E5F'),
   dict(**{'from': 0.28, 'to': 0.46}, label='the dining car closes', colour='#A8372E'),
   dict(**{'from': 0.48, 'to': 0.56}, label='Dev wakes Ruth', colour='#C86B2B'),
   dict(**{'from': 0.58, 'to': 0.92}, label='200 sandwiches in 90 minutes', colour='#D9A441')]),
  dict(name='The passengers knew', type='events', items=[
   dict(at=0.04, label='nothing', colour='#9AA7AE'),
   dict(at=0.30, label='nothing', colour='#9AA7AE'),
   dict(at=0.56, label='nothing', colour='#A8372E'),
   dict(at=0.80, label='everything Nadia knew, which was not much', colour='#2E6F5E')]),
  dict(name='People asking', type='line',
   points=[(0, 0), (0.3, 9), (0.55, 31), (0.8, 4), (1.0, 0)], end_label='0'),
  dict(name='What the log recorded', type='flags', items=[
   dict(at=0.10, label='the departure time'),
   dict(at=0.46, label='the reason code'),
   dict(at=0.70, label='and the word NONE')])]),

"fig_a12_u01_p11_v04b": dict(type='V4', height=720,
 title='The same form, twice',
 sub='On the left, the log as it is. On the right, three lines longer.',
 alt='Two drawings of the same crew log page, one with a single incidents box reading NONE and '
     'one with three extra handwritten lines beneath it.',
 differences=6, prompt='Find the six. One of them is the time at the bottom, and it is the '
                       'argument against the whole idea.',
 left=dict(label='as it is', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#9AA7AE'),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='8 numbers · 1 word: NONE · signed 02.41',
        colour='#9AA7AE')]),
 right=dict(label='three lines longer', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='8 numbers · 3 lines of handwriting · signed 02.43',
        colour='#2E6F5E')])),
}
