"""A1.2 Unit 2 - Forty Seconds at Mirror Lake - fifteen figures, as data."""
FIGURES = {
"fig_a12_u02_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='Mirror Lake, twenty past six, minus eleven',
 sub='Fourteen things to find. Four of the times on the timetable are crossed out in pen.',
 alt='A small prairie railway station before dawn in winter, with one wooden platform, a single '
     'lamp, a three-sided shelter, a station building with the ticket window closed, and four '
     'people waiting with bags.',
 sky='#35414C', ground='#9DA3A0', ground_line=700,
 buildings=[dict(x=20, w=400, storeys=2, colour='#8B7C62', cutaway=True,
     floor_labels=['the office', 'the ticket window'],
     label='the station building - closed'),
   dict(x=520, w=300, storeys=1, colour='#7E8B8E',
     label='the shelter - three sides, and the fourth is the weather'),
   dict(x=900, w=680, storeys=1, colour='#6F7C84',
     label='the platform - one, and 406 at Toronto Union')],
 props=[dict(kind='sign', x=470, y=700, s=.7, text='6:20'),
   dict(kind='hoarding', x=200, y=700, s=.8, w=160, notice=True),
   dict(kind='box', x=1000, y=700, s=1.0),
   dict(kind='crate', x=1080, y=700, s=1.0),
   dict(kind='chair', x=600, y=700, s=1.0), dict(kind='chair', x=680, y=700, s=1.0),
   dict(kind='sign', x=1480, y=700, s=.7, text='WEST'),
   dict(kind='tree', x=860, y=700, s=.8)],
 people=[dict(x=960, y=700, h=86, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=1140, y=700, h=86, skin=4, cloth=3, hair='cap', arm='down'),
   dict(x=1260, y=700, h=86, skin=0, cloth=1, hair='short', arm='folded'),
   dict(x=1380, y=700, h=86, skin=3, cloth=2, hair='bun', arm='hold'),
   dict(x=240, y=700, h=88, skin=1, cloth=0, hair='grey', arm='point')],
 names=[dict(x=960, t='Marie-Claire - a suitcase, four times a year'),
   dict(x=1140, t='a backpack, and a single ticket'),
   dict(x=1260, t='somebody with no luggage at all'),
   dict(x=1380, t='two bags, and both of them heavy'),
   dict(x=240, t='Tom Wong - thirty-one years here'),
   dict(x=470, t='the clock: twenty past six'),
   dict(x=200, t='the timetable - four times crossed out'),
   dict(x=1480, t='the sign: WEST')],
 markers=[dict(x=960, y=582), dict(x=1140, y=582), dict(x=1260, y=582), dict(x=1380, y=582),
   dict(x=240, y=580), dict(x=470, y=636), dict(x=200, y=644), dict(x=1480, y=636),
   dict(x=1000, y=652), dict(x=1080, y=660), dict(x=600, y=664), dict(x=860, y=640),
   dict(x=200, y=584), dict(x=640, y=640)]),

"fig_a12_u02_p01_v08": dict(type='V8', height=800,
 title='Five stops, thirty-five years',
 sub='The distance and the time on every leg, and under each stop the population then and now.',
 alt='The rail line drawn as a network of five stops with distance and journey time on each leg '
     'and the population in 1991 and now under each stop.',
 nodes={
  'tor': dict(x=180, y=400, short='T', name='Toronto', sub='2.3 m → 2.9 m', r=56,
              colour='#1F4E5F'),
  'win': dict(x=560, y=260, short='W', name='Winnipeg', sub='652 k → 749 k',
              colour='#2E6F5E'),
  'mir': dict(x=800, y=620, short='M', name='Mirror Lake', sub='1,100 → 310', r=52,
              colour='#A8372E'),
  'sas': dict(x=1040, y=260, short='S', name='Saskatoon', sub='186 k → 266 k',
              colour='#2E6F5E'),
  'jas': dict(x=1280, y=560, short='J', name='Jasper', sub='4,000 → 4,100',
              colour='#D9A441'),
  'van': dict(x=1460, y=280, short='V', name='Vancouver', sub='472 k → 662 k',
              colour='#1F4E5F')},
 edges=[dict(a='tor', b='win', label='2,100 km · 36 h', sw=7),
   dict(a='win', b='mir', label='240 km · 3 h · stops 40 seconds', sw=3, dash='7 6',
        colour='#A8372E'),
   dict(a='mir', b='sas', label='470 km · 6 h', sw=5),
   dict(a='sas', b='jas', label='860 km · 13 h', sw=6),
   dict(a='jas', b='van', label='880 km · 17 h', sw=6)]),

"fig_a12_u02_p01_v02a": dict(type='V2', height=780,
 title='One station, in section',
 sub='Eleven things. Eleven words. Only two of the four layers are ever used now.',
 alt='A cutaway of a small station from the track up through the platform, the shelter and the '
     'waiting room to the closed office above, with empty labels.',
 floors=[dict(was='the office, upstairs', now='closed in 2009 · the window is boarded',
     year='', fill='#F1EDE2'),
   dict(was='the waiting room', now='locked · the timetable is on the outside wall now',
     year='', fill='#EFE6DC'),
   dict(was='the shelter', now='three sides · two benches · one lamp', year='',
     fill='#E8EEF0'),
   dict(was='the platform', now='suitcase · backpack · luggage · and forty seconds',
     year='', fill='#F3EADA')],
 callouts=[dict(at=0.12, text='Nobody has been up here since the school closed'),
   dict(at=0.38, text='Locked, and the key is in Winnipeg'),
   dict(at=0.62, text='The only part of the station that is still a station'),
   dict(at=0.88, text='Forty seconds, twice a week, each way')]),

"fig_a12_u02_p02_v07": dict(type='V7', height=820,
 title='Through the glass',
 sub='The window is closed. They have had this conversation about forty times.',
 alt='A station agent behind a closed ticket window and a woman on the platform with a suitcase, '
     'talking through the glass, each with two speech balloons and a thought balloon.',
 bg='#DCE1E0',
 set=[dict(kind='crate', x=760, y=660, s=1.2), dict(kind='box', x=1340, y=660, s=1.0),
   dict(kind='chair', x=1430, y=660, s=1.1)],
 people=[dict(x=520, h=240, skin=1, cloth=0, hair='grey', arm='point', facing='right',
   label='Tom Wong', role='station agent, thirty-one years',
   says=['Did you travel last summer?', 'When did you buy it?'],
   thinks=['I already know why she is going.']),
  dict(x=1080, h=238, skin=2, cloth=4, hair='long', arm='hold', facing='left',
   label='Marie-Claire', role='four times a year, for nine years',
   says=['I didn\'t book it. I bought it this morning.',
         'A single. She didn\'t come back.'],
   thinks=['Do I tell him, or does he know?'])]),

"fig_a12_u02_p03_v09a": dict(type='V9', kind='mirror', height=680,
 title='One weight, and it moves to the front',
 sub='In the positive the past sits on the verb. In a question it has moved onto did.',
 alt='Two sentence diagrams. In the first, the past ending sits on the verb; in the second, did '
     'carries the past at the front and the verb is bare.',
 labels=['POSITIVE', 'QUESTION'],
 between='↕ the past is marked once, and did takes it when did is there',
 active=dict(parts=[dict(w=16, role='agent', text='You'),
   dict(w=26, role='action', text='bought'),
   dict(w=22, role='affected', text='the ticket')]),
 passive=dict(parts=[dict(w=18, role='hidden', text='Did'),
   dict(w=16, role='agent', text='you'),
   dict(w=20, role='action', text='buy'),
   dict(w=26, role='affected', text='the ticket ?')]),
 rule='Did and didn\'t are the same for every person - did I, did you, did she, did they. The '
      'verb after them is the plain dictionary form, including irregular verbs: Did you go, '
      'never Did you went.'),

"fig_a12_u02_p03_v09b": dict(type='V9', kind='timeline', height=740,
 title='Counting backwards from now',
 sub='Ago measures. The other markers name. They are two different jobs.',
 alt='A timeline running back from NOW with two days ago, last night, last summer and a long '
     'time ago placed along it, and the day before shown hanging off a point already in the past.',
 now=0.92,
 bands=[dict(**{'from': 0.84, 'to': 0.92}, type='reach', lane=1, label='two days ago',
     example='the number comes first'),
   dict(**{'from': 0.70, 'to': 0.70}, type='event', lane=2, label='last night',
     example='names a time - no the, no on'),
   dict(**{'from': 0.34, 'to': 0.34}, type='event', lane=1, label='last summer',
     example='names a season that has finished'),
   dict(**{'from': 0.06, 'to': 0.26}, type='before', lane=3, label='a long time ago',
     example='refuses to give a number, on purpose'),
   dict(**{'from': 0.26, 'to': 0.26}, type='event', lane=4, label='the day before',
     example='before a day that was already in the past')]),

"fig_a12_u02_p03_v11": dict(type='V11', height=700,
 title='The past marked twice, again',
 alt='Two panels comparing Did you bought it with Did you buy it, the first showing the past '
     'marked on both did and the verb.',
 wrong=dict(sentence='Did you bought it?',
            boundary=0.30, boundary_label='Did',
            event=0.60, event_label='bought - and did is already past',
            why='Did is the past of do. Once it is at the front of the sentence, the listener '
                'knows when this happened before they reach the verb at all. Marking it again '
                'is the same error as Does she checks, one unit of the last book, in a new '
                'costume.'),
 right=dict(sentence='Did you buy it?',
            boundary=0.30, boundary_label='Did',
            event=0.56, event_label='buy - plain, and that is not a present tense',
            why='The bare form after did is not the present. It is the dictionary form, which '
                'English uses whenever a helper has already said when. The same applies after '
                'didn\'t: I didn\'t buy it, never I didn\'t bought it.'),
 misconception='Irregular verbs make this worse, because bought feels like a different word '
               'rather than an ending - so it does not feel like doubling up. It is. Buy and '
               'bought are the same verb wearing two labels, and only one label is allowed.'),

"fig_a12_u02_p04_v04a": dict(type='V4', height=720,
 title='Two interviews, one traveller',
 sub='Four questions each. One of the two found out why she was going.',
 alt='Two written interviews with the same traveller side by side, one asking only factual did '
     'questions and one asking why and how long questions.',
 differences=6, prompt='Find the six. Which set of questions produced a story, and what kind of '
                       'word does every one of them start with?',
 left=dict(label='four facts', art=[
   dict(kind='block', x=150, y=130, w=140, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=150, y=98, w=120, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=150, y=66, w=150, bh=22, colour='#9AA7AE'),
   dict(kind='label', x=300, y=210, text='Did you? · yes · no · yes · a single',
        colour='#9AA7AE')]),
 right=dict(label='four questions', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='Why? · How long? · and a story about a daughter',
        colour='#2E6F5E')])),

"fig_a12_u02_p05_v05": dict(type='V5', height=1080,
 title='The timetable on the station wall',
 sub='Two columns, seven days, and four times crossed out in pen.',
 alt='The timetable on a station wall showing westbound and eastbound columns, the days across '
     'the top, the Mirror Lake row picked out, four times crossed out in pen with a date beside '
     'one of them, and a printed line about winter request stops.',
 rows=[dict(t='org', text='PRAIRIE LINE  -  MIRROR LAKE  -  TIMETABLE'),
   dict(t='head', text='WESTBOUND'),
   dict(t='grid', cols=['DAY', 'ARR', 'STATUS'],
     data=[['MONDAY', '06.24', 'RUNS'],
           ['TUESDAY', '06.24', 'CROSSED OUT'],
           ['THURSDAY', '06.24', 'RUNS'],
           ['SATURDAY', '06.24', 'CROSSED OUT']]),
   dict(t='rule'),
   dict(t='head', text='EASTBOUND'),
   dict(t='grid', cols=['DAY', 'ARR', 'STATUS'],
     data=[['MONDAY', '21.08', 'CROSSED OUT'],
           ['WEDNESDAY', '21.08', 'RUNS'],
           ['FRIDAY', '21.08', 'CROSSED OUT'],
           ['SUNDAY', '21.08', 'RUNS']]),
   dict(t='rule'),
   dict(t='kv', k='Date written in pen', v='04 / 11', mono=True),
   dict(t='kv', k='Trains a week now', v='4', mono=True),
   dict(t='kv', k='Trains a week before', v='8', mono=True),
   dict(t='rule'),
   dict(t='sign', text='AND AT THE BOTTOM, PRINTED:'),
   dict(t='para', text='"Winter: this stop is by request only. Requests must be made at least '
     '12 hours in advance." Printed, not written - so it was in the design, not added later.')],
 callouts=[dict(at=0.16, text='Two of the four westbound times are gone'),
   dict(at=0.42, text='Two of the four eastbound ones too - the service halved'),
   dict(at=0.62, text='The fourth of November, and no year'),
   dict(at=0.72, text='Eight became four, and nobody printed a new timetable'),
   dict(at=0.92, text='Printed, so somebody decided this before the sign was made')]),

"fig_a12_u02_p06_v03a": dict(type='V3',
 title='One view, six times',
 sub='The same view from the platform. Each panel has one thing fewer in it.',
 alt='Six panels showing the same view from the station platform in 1991, 2001, 2009, 2015, last '
     'summer and this morning, with one fewer feature in each.',
 panels=[
  dict(caption='1991 - 1,100 people, a school, two shops',
       art=[dict(kind='block', x=160, y=0, w=150, bh=120, colour='#2E6F5E')]),
  dict(caption='2001 - one shop closes',
       art=[dict(kind='block', x=160, y=0, w=150, bh=96, colour='#2E6F5E')]),
  dict(caption='2009 - the school closes',
       art=[dict(kind='block', x=160, y=0, w=150, bh=66, colour='#D9A441')]),
  dict(caption='2015 - the station office closes',
       art=[dict(kind='block', x=160, y=0, w=150, bh=46, colour='#C86B2B')]),
  dict(caption='last summer - 310 people',
       art=[dict(kind='block', x=160, y=0, w=150, bh=30, colour='#A8372E')]),
  dict(caption='this morning - four people on the platform',
       art=[dict(kind='person', x=160, y=0, h=108, skin=2, cloth=4)])]),

"fig_a12_u02_p07_v10": dict(type='V10', kind='elision', height=680,
 title='Two words that became one',
 sub='The d and the y collide and make a new sound. This is not lazy speech. It is the speech.',
 alt='Four question openings written in full and then as they are actually said, with the '
     'letters that disappear shaded out.',
 pairs=[
  dict(written='did you', spoken='didja', dropped='yu', note='the commonest two words in '
       'any question about the past'),
  dict(written='what did you', spoken='whaddja', dropped='tdyu', note='three words, one beat'),
  dict(written='did he', spoken='didee', dropped='h', note='the h disappears completely'),
  dict(written='did it', spoken='didit', dropped='', note='and this one survives intact'),
  dict(written='how long ago', spoken='howlongago', dropped='', note='no collisions at all - '
       'say it slowly and you will still sound natural')]),

"fig_a12_u02_p09_v02b": dict(type='V2', height=780,
 title='Four starts and one habit',
 sub='Three of the four layers are courses. The bottom one is not, and it is the only one '
     'still running.',
 alt='A cutaway of a learner\'s year in four layers: a course finished, a course started and '
     'stopped, a course bought and never opened, and one daily thing never called study.',
 floors=[dict(was='January', now='a course, bought · used for 11 days', year='',
     fill='#E8EEF0'),
   dict(was='March', now='a different course · used for 11 days', year='', fill='#F3EADA'),
   dict(was='June', now='a third course · never opened', year='', fill='#EFE6DC'),
   dict(was='all year', now='one song, one podcast, one person you message · 365 days',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Eleven days is not nothing. It is eleven days'),
   dict(at=0.38, text='And again. Which is twenty-two'),
   dict(at=0.62, text='This is the one that makes people say they never finish anything'),
   dict(at=0.88, text='Nobody counts this layer, and it is bigger than the other three')]),

"fig_a12_u02_p09_v03b": dict(type='V3',
 title='Eleven days, twice',
 sub='Five panels. The fifth is identical to the second, and that is the finding.',
 alt='Five panels: buying a course in January, using it for eleven days, stopping, buying '
     'another in March, and the same eleven days again.',
 panels=[
  dict(caption='January - a course is bought',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='Days 1 to 11 - it works',
       art=[dict(kind='block', x=150, y=0, w=110, bh=80, colour='#2E6F5E')]),
  dict(caption='Day 12 - nothing',
       art=[dict(kind='gap', x=150, y=10, w=110, bh=70)]),
  dict(caption='March - a different course',
       art=[dict(kind='doc', x=150, y=0), dict(kind='arrow', x=150, y=130)]),
  dict(caption='Days 1 to 11 - exactly the same',
       art=[dict(kind='block', x=150, y=0, w=110, bh=80, colour='#2E6F5E')])]),

"fig_a12_u02_p10_v12": dict(type='V12',
 title='Mirror Lake, thirty-five years',
 sub='The services band falls before the population band, not after it.',
 alt='An infographic of Mirror Lake across thirty-five years with bands for population, '
     'services, trains a week and people picked up and put down.',
 span=['1991', 'now'], ticks=5,
 tick_labels=['1991', '2000', '2009', '2018', 'now'],
 bands=[dict(name='Population', type='line',
   points=[(0, 1100), (0.3, 840), (0.55, 620), (0.8, 410), (1.0, 310)], end_label='310'),
  dict(name='Services', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.28}, label='school · 2 shops · elevator · station office',
        colour='#2E6F5E'),
   dict(**{'from': 0.30, 'to': 0.52}, label='one shop closes', colour='#D9A441'),
   dict(**{'from': 0.54, 'to': 0.76}, label='the school closes', colour='#C86B2B'),
   dict(**{'from': 0.78, 'to': 1.0}, label='one shop, four days a week', colour='#A8372E')]),
  dict(name='Trains a week', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.56}, label='8', colour='#1F4E5F'),
   dict(**{'from': 0.58, 'to': 1.0}, label='4, and by request in winter', colour='#9AA7AE')]),
  dict(name='Picked up / put down', type='events', items=[
   dict(at=0.10, label='1991: nobody counted', colour='#9AA7AE'),
   dict(at=0.50, label='2009: 980 / 1,020', colour='#C86B2B'),
   dict(at=0.90, label='last year: 511 / 496', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.24, label='the shop closed while the population was still over 800'),
   dict(at=0.58, label='fifteen more people get on than get off, every year')])]),

"fig_a12_u02_p11_v04b": dict(type='V4', height=720,
 title='The platform at twenty past six',
 sub='The scheduled stop on the left. The winter request stop on the right.',
 alt='Two drawings of the same platform at the same hour, one at a scheduled stop with four '
     'people waiting and one in winter with a single person and the train passing in the '
     'background.',
 differences=6, prompt='Find the six. One of them is on the station wall, and it is the reason '
                       'the right-hand picture looks like that.',
 left=dict(label='the scheduled stop', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=140, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='4 people · 3 bags · lamp on · the train stops',
        colour='#2E6F5E')]),
 right=dict(label='the winter request stop', art=[
   dict(kind='block', x=150, y=130, w=70, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210,
        text='1 person · 1 bag · lamp off · the train goes past',
        colour='#A8372E')])),
}
