"""A1.2 Unit 3 - One Thousand Four Hundred Seats - fifteen figures, as data."""
FIGURES = {
"fig_a12_u03_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The maintenance shed at Winnipeg, half past four',
 sub='Fourteen things to find. One of the new seats is already torn, and it has never been sat on.',
 alt='A railway maintenance shed with two coaches and two rows of seats laid out on the floor '
     'between them, one row of worn cloth seats and one row of new synthetic seats still in '
     'plastic, with four people standing between them.',
 sky='#C4CCCE', ground='#8E8A80', ground_line=700,
 buildings=[dict(x=20, w=420, storeys=2, colour='#8E9AA0', cutaway=True,
     floor_labels=['the roof light', 'coach 4 - seats out'],
     label='the 1998 coach'),
   dict(x=520, w=520, storeys=1, colour='#B2A88E',
     label='the shed floor - two rows, twenty-two seats'),
   dict(x=1120, w=460, storeys=2, colour='#9AA6AC', cutaway=True,
     floor_labels=['the store', 'the new covers - still wrapped'],
     label='the delivery, from Tuesday')],
 props=[dict(kind='chair', x=560, y=700, s=1.2), dict(kind='chair', x=640, y=700, s=1.2),
   dict(kind='chair', x=720, y=700, s=1.2),
   dict(kind='chair', x=880, y=700, s=1.2), dict(kind='chair', x=960, y=700, s=1.2),
   dict(kind='crate', x=1180, y=700, s=1.1), dict(kind='box', x=1280, y=700, s=1.0),
   dict(kind='sign', x=480, y=700, s=.7, text='4:30')],
 people=[dict(x=800, y=700, h=88, skin=0, cloth=1, hair='grey', arm='hold'),
   dict(x=1040, y=700, h=86, skin=3, cloth=2, hair='bun', arm='point'),
   dict(x=200, y=700, h=86, skin=4, cloth=3, hair='cap', arm='down'),
   dict(x=320, y=700, h=86, skin=2, cloth=4, hair='short', arm='folded'),
   dict(x=1400, y=700, h=86, skin=1, cloth=0, hair='long', arm='hold')],
 names=[dict(x=800, t='the old row - 1998, repaired four times'),
   dict(x=1040, t='Nadia - she asked how long they last'),
   dict(x=200, t='a fitter - he has to put them in'),
   dict(x=320, t='the procurement officer - this year\'s budget'),
   dict(x=1400, t='the new row - and one is already torn'),
   dict(x=480, t='the clock: half past four'),
   dict(x=1180, t='the delivery crate, from Tuesday'),
   dict(x=1280, t='the plastic the new covers came in')],
 markers=[dict(x=800, y=580), dict(x=1040, y=582), dict(x=200, y=582), dict(x=320, y=582),
   dict(x=1400, y=582), dict(x=480, y=636), dict(x=1180, y=656), dict(x=1280, y=652),
   dict(x=560, y=664), dict(x=880, y=664), dict(x=720, y=664), dict(x=960, y=664),
   dict(x=200, y=584), dict(x=1300, y=584)]),

"fig_a12_u03_p01_v08": dict(type='V8', height=780,
 title='One seat, five materials',
 sub='Every line carries two numbers: what the part costs and how long it lasts.',
 alt='A seat at the centre joined by labelled lines to five materials - metal frame, wooden arm, '
     'plastic shell, cloth cover and foam - each line showing the cost and the lifetime of that '
     'part.',
 nodes={
  'sea': dict(x=800, y=400, short='S', name='one seat', sub='fourteen hundred of them', r=60,
              colour='#1C2B33'),
  'met': dict(x=340, y=220, short='M', name='the metal frame', sub='$96 · 30 years',
              colour='#1F4E5F'),
  'woo': dict(x=300, y=580, short='W', name='the wooden arm', sub='$22 · 20 years',
              colour='#8C6A9E'),
  'pla': dict(x=800, y=700, short='P', name='the plastic shell', sub='$34 · 12 years',
              colour='#2E6F5E'),
  'clo': dict(x=1280, y=230, short='C', name='the cloth cover', sub='$41 · 7 years',
              colour='#C86B2B'),
  'foa': dict(x=1300, y=600, short='F', name='the foam', sub='$17 · 5 years',
              colour='#D9A441')},
 edges=[dict(a='met', b='sea', label='it holds everything', sw=7),
   dict(a='woo', b='sea', label='the only part people touch', sw=4),
   dict(a='pla', b='sea', label='it holds the shape', sw=5),
   dict(a='clo', b='sea', label='the only part anybody sees', sw=6, colour='#C86B2B'),
   dict(a='foa', b='sea', label='the shortest life, and the cheapest', sw=3, dash='6 5',
        colour='#D9A441')]),

"fig_a12_u03_p01_v02a": dict(type='V2', height=780,
 title='One seat, in section',
 sub='Eleven parts. Eleven words. The price of each part is beside it.',
 alt='A cutaway of a single train seat showing the cover, the foam, the plastic shell, the metal '
     'frame and the floor fixing, with empty labels and a price against each layer.',
 floors=[dict(was='the cover - $41', now='cloth · the only part a passenger ever touches',
     year='', fill='#F3EADA'),
   dict(was='the foam - $17', now='five years · and nobody inspects it', year='',
     fill='#EFE6DC'),
   dict(was='the shell - $34', now='plastic · it holds the shape and cracks in the cold',
     year='', fill='#E8EEF0'),
   dict(was='the frame and fixing - $118', now='metal and wood · thirty years · nobody '
     'has ever replaced one', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The cheapest visible part, and the whole argument'),
   dict(at=0.38, text='Five years, and it is replaced with the cover whether it needs it or not'),
   dict(at=0.62, text='Twelve years, and the cold is what kills it'),
   dict(at=0.88, text='More than half the money, and it will outlive the company')]),

"fig_a12_u03_p02_v07": dict(type='V7', height=820,
 title='Between the two rows',
 sub='Each of them is holding a seat cover. They are not holding the same argument.',
 alt='A service manager and a procurement officer standing between two rows of seats, each '
     'holding a seat cover, with two speech balloons each and a thought balloon.',
 bg='#DFE2DE',
 set=[dict(kind='chair', x=760, y=660, s=1.4), dict(kind='chair', x=860, y=660, s=1.4),
   dict(kind='crate', x=1360, y=660, s=1.1)],
 people=[dict(x=520, h=240, skin=2, cloth=4, hair='short', arm='hold', facing='right',
   label='the procurement officer', role='he signs for it this year',
   says=['It\'s cheaper. Nineteen against forty-one.',
         'This one is more expensive than that one.'],
   thinks=['My budget is twelve months long.']),
  dict(x=1080, h=240, skin=3, cloth=2, hair='bun', arm='point', facing='left',
   label='Nadia', role='she will still be here in year four',
   says=['It\'s much stronger. And it can be repaired.',
         'It isn\'t as good as the old one.'],
   thinks=['Who signs for it in 2029?'])]),

"fig_a12_u03_p03_v09a": dict(type='V9', kind='ladder', height=760,
 title='How long is the adjective?',
 sub='The length of the word decides the method. Nothing else does.',
 alt='A vertical ladder of adjectives arranged by syllable count, showing -er for short '
     'adjectives, more for long ones, and a shaded band in the middle where both are accepted.',
 top_label='short', bottom_label='long',
 steps=[dict(form='cheap → cheaper', meaning='1 syllable · add -er'),
   dict(form='strong → stronger', meaning='1 syllable · add -er'),
   dict(form='heavy → heavier', meaning='2 syllables ending in y · add -ier'),
   dict(form='useful → more useful', meaning='2 syllables, no y · usually more'),
   dict(form='expensive → more expensive', meaning='3 syllables · more'),
   dict(form='good → better', meaning='no rule at all · learn it'),
   dict(form='bad → worse', meaning='no rule at all · learn it')]),

"fig_a12_u03_p03_v09b": dict(type='V9', kind='weight', height=520,
 title='as … as, and not as … as',
 sub='Two brackets of the same height mean equal. A shorter second bracket means less.',
 alt='Two sets of brackets drawn around pairs of objects, the first pair equal in height and the '
     'second with a shorter second bracket.',
 parts=[dict(w=14, role='as', text='as', colour='#2E6F5E'),
   dict(w=22, role='the adjective, plain', text='strong', colour='#1F4E5F'),
   dict(w=14, role='as', text='as', colour='#2E6F5E'),
   dict(w=22, role='= equal', text='cloth', colour='#2E6F5E'),
   dict(w=18, role='not as', text='NOT as', colour='#A8372E'),
   dict(w=26, role='< less', text='good as cloth', colour='#A8372E')],
 note='Two as-words, every time: as strong as, not as good as. One as on its own is not a '
      'comparison, and the adjective between them never takes -er.'),

"fig_a12_u03_p03_v11": dict(type='V11', height=700,
 title='The comparison marked twice',
 alt='Two panels comparing more cheaper with cheaper, the first showing the comparison marked '
     'both by more and by the -er ending.',
 wrong=dict(sentence='It is more cheaper than cloth.',
            boundary=0.30, boundary_label='more',
            event=0.60, event_label='cheaper - and it is already comparative',
            why='Cheap is one syllable, so it takes -er, and once it has taken it the word is '
                'already a comparison. More in front says the same thing a second time. The '
                'sentence is not wrong because it is ungrammatical; it is wrong because it is '
                'paying twice for one idea.'),
 right=dict(sentence='It is cheaper than cloth.',
            boundary=0.30, boundary_label='cheaper',
            event=0.56, event_label='one marker, and the sentence is shorter',
            why='One comparative marker, chosen by the length of the adjective: -er for short '
                'words, more for long ones. Never both. The only words that break this are good, '
                'bad and far, and they break it by changing shape entirely.'),
 misconception='More feels like an intensifier - like very - so it seems harmless to add. It is '
               'not an intensifier. It is the comparative itself, doing exactly the job that '
               '-er does, which is why the two cannot share a word.'),

"fig_a12_u03_p04_v04a": dict(type='V4', height=720,
 title='The same numbers, two presentations',
 sub='One compares on price. One compares on cost over ten years. They recommend opposite things.',
 alt='Two presentations of the same two seat covers side by side, one comparing them on purchase '
     'price and one on ten-year cost, each recommending a different cover.',
 differences=6, prompt='Find the six. Both are honest and both use the same figures. What has '
                       'been changed is not a number - what is it?',
 left=dict(label='on price', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#C86B2B'),
   dict(kind='block', x=150, y=98, w=110, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='$57,400 vs $26,600 — buy synthetic',
        colour='#C86B2B')]),
 right=dict(label='over ten years', art=[
   dict(kind='block', x=150, y=130, w=230, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210, text='$86,100 vs $88,700 — buy cloth',
        colour='#2E6F5E')])),

"fig_a12_u03_p05_v05": dict(type='V5', height=900,
 title='The supplier\'s comparison sheet',
 sub='Eight rows. Six of them favour one column. Two of them are blank, and both blanks are in '
     'the same column.',
 alt='A supplier comparison sheet with two columns and eight rows, six favouring the synthetic '
     'cover, two rows left blank, and a green tick at the bottom of one column.',
 rows=[dict(t='org', text='NORTHFIELD TEXTILES  -  SEAT COVER COMPARISON'),
   dict(t='grid', cols=['', 'CLOTH', 'SYNTHETIC'],
     data=[['PRICE EACH', '$41.00', '$19.00'],
           ['WEIGHT', '940 g', '610 g'],
           ['CLEANING TIME', '14 min', '4 min'],
           ['STAIN RESISTANCE', 'MEDIUM', 'HIGH'],
           ['COLOURS AVAILABLE', '4', '11'],
           ['DELIVERY', '9 WEEKS', '2 WEEKS'],
           ['SERVICE LIFE', '7 YEARS', '(blank)'],
           ['REPAIRABLE', 'YES, 3-4x', '(blank)']]),
   dict(t='rule'),
   dict(t='head', text='AND AT THE BOTTOM'),
   dict(t='kv', k='Recommended', v='SYNTHETIC', mono=True),
   dict(t='kv', k='Saving on this order', v='$30,800', mono=True),
   dict(t='kv', k='Saving over ten years', v='(not shown)', mono=False),
   dict(t='rule'),
   dict(t='para', text='The two blank rows are SERVICE LIFE and REPAIRABLE. The synthetic '
     'figures are three years and no. Both are known, both were asked for, and neither is on '
     'the sheet.')],
 callouts=[dict(at=0.12, text='Less than half the price. This is the row the sheet is built on'),
   dict(at=0.26, text='Four minutes against fourteen - real, and worth money'),
   dict(at=0.40, text='Eleven colours. Nobody has ever chosen a seat cover for its colour'),
   dict(at=0.56, text='Two blanks, and they are the only two rows about time'),
   dict(at=0.86, text='The saving over ten years is three thousand, and it is the other way')]),

"fig_a12_u03_p06_v03a": dict(type='V3',
 title='Saying by how much',
 sub='The same two objects, six times. The words carry the size of the gap.',
 alt='Six panels comparing the same two objects with the gap between them drawn wider in each '
     'panel, labelled with the phrase that matches the size.',
 panels=[
  dict(caption='the same as', art=[dict(kind='block', x=120, y=0, w=70, bh=80,
     colour='#1F4E5F'), dict(kind='block', x=200, y=0, w=70, bh=80, colour='#1F4E5F')]),
  dict(caption='a bit cheaper', art=[dict(kind='block', x=120, y=0, w=70, bh=80,
     colour='#1F4E5F'), dict(kind='block', x=200, y=0, w=70, bh=70, colour='#2E6F5E')]),
  dict(caption='cheaper', art=[dict(kind='block', x=120, y=0, w=70, bh=80, colour='#1F4E5F'),
     dict(kind='block', x=200, y=0, w=70, bh=54, colour='#2E6F5E')]),
  dict(caption='much cheaper', art=[dict(kind='block', x=120, y=0, w=70, bh=80,
     colour='#1F4E5F'), dict(kind='block', x=200, y=0, w=70, bh=34, colour='#D9A441')]),
  dict(caption='far cheaper', art=[dict(kind='block', x=120, y=0, w=70, bh=80,
     colour='#1F4E5F'), dict(kind='block', x=200, y=0, w=70, bh=16, colour='#C86B2B')]),
  dict(caption='not in the same world', art=[dict(kind='block', x=120, y=0, w=70, bh=80,
     colour='#1F4E5F'), dict(kind='gap', x=200, y=0, w=70, bh=16)])]),

"fig_a12_u03_p07_v10": dict(type='V10', kind='stress', height=820,
 title='The small words stay small',
 sub='Than, as, a and the are never the loud word. Six phrases, and the pattern never breaks.',
 alt='Six phrases drawn as beats, with the strong syllables as large circles and than, as, a and '
     'the always drawn small.',
 items=[
  dict(syllables=['CHEAP-er', 'than', 'THAT'], strong=[0, 2],
       note='than is small, between two big ones'),
  dict(syllables=['as', 'STRONG', 'as', 'CLOTH'], strong=[1, 3],
       note='both as-words small'),
  dict(syllables=['not', 'as', 'GOOD', 'as', 'THIS'], strong=[2, 4], note='three small, two big'),
  dict(syllables=['a', 'BIT', 'CHEAP-er'], strong=[1, 2], note='a is almost silent'),
  dict(syllables=['MUCH', 'BET-ter', 'than', 'THAT'], strong=[0, 1, 3],
       note='much is big - it is carrying size'),
  dict(syllables=['the', 'SAME', 'as', 'the', 'O-ther'], strong=[1, 4],
       note='the twice, as once, and none of them heard')]),

"fig_a12_u03_p09_v02b": dict(type='V2', height=780,
 title='Cheap practice and expensive practice',
 sub='The time each one costs on the left, and what it produces on the right.',
 alt='A cutaway of four kinds of study with the time each costs and what each produces, from '
     'rereading notes to saying something uncertain to a person.',
 floors=[dict(was='rereading notes', now='20 min · produces the feeling of having studied',
     year='', fill='#E8EEF0'),
   dict(was='watching a video', now='25 min · produces recognition, which is not knowledge',
     year='', fill='#F3EADA'),
   dict(was='doing exercises', now='20 min · produces accuracy in the shape of the exercise',
     year='', fill='#EFE6DC'),
   dict(was='saying it to a person', now='4 min · produces the thing itself', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Comfortable, and almost free'),
   dict(at=0.38, text='You will recognise it tomorrow and not be able to say it'),
   dict(at=0.62, text='Useful, and it stops working outside the exercise'),
   dict(at=0.88, text='Four minutes, and it is the expensive one')]),

"fig_a12_u03_p09_v03b": dict(type='V3',
 title='One uncertain sentence',
 sub='Panel three is the expensive one. Panel five is what it bought.',
 alt='Five panels on a single sentence: thinking it, deciding it might be wrong, saying it '
     'anyway, being corrected, and using it correctly three days later.',
 panels=[
  dict(caption='1 You think of the sentence',
       art=[dict(kind='person', x=150, y=0, h=110, skin=3, cloth=2)]),
  dict(caption='2 You think it might be wrong',
       art=[dict(kind='block', x=150, y=10, w=100, bh=70, colour='#D9A441')]),
  dict(caption='3 You say it anyway',
       art=[dict(kind='person', x=150, y=0, h=110, skin=3, cloth=2, arm='point')]),
  dict(caption='4 Somebody corrects it',
       art=[dict(kind='cross', x=150, y=50)]),
  dict(caption='5 Three days later, right',
       art=[dict(kind='tick', x=150, y=50)])]),

"fig_a12_u03_p10_v12": dict(type='V12',
 title='Two covers, fifteen years',
 sub='The totals are almost identical. The shape is completely different, and the shape is who '
     'signs.',
 alt='An infographic comparing the two seat covers over fifteen years with bands for total money '
     'spent, money spent each year, seats out of service and who signed the cheque.',
 span=['year 1', 'year 15'], ticks=4,
 tick_labels=['year 1', 'year 5', 'year 10', 'year 15'],
 bands=[dict(name='Cloth - spend', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.10}, label='$57,400', colour='#2E6F5E'),
   dict(**{'from': 0.46, 'to': 0.56}, label='$57,400', colour='#2E6F5E'),
   dict(**{'from': 0.92, 'to': 1.0}, label='$57,400', colour='#2E6F5E')]),
  dict(name='Synthetic - spend', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.08}, label='$26,600', colour='#C86B2B'),
   dict(**{'from': 0.20, 'to': 0.28}, label='$26,600', colour='#C86B2B'),
   dict(**{'from': 0.40, 'to': 0.48}, label='$26,600', colour='#C86B2B'),
   dict(**{'from': 0.60, 'to': 0.68}, label='$26,600', colour='#C86B2B'),
   dict(**{'from': 0.80, 'to': 0.88}, label='$26,600', colour='#C86B2B')]),
  dict(name='Seats out of service', type='line',
   points=[(0, 0), (0.25, 4), (0.45, 31), (0.7, 12), (1.0, 44)], end_label='44'),
  dict(name='Who signed', type='events', items=[
   dict(at=0.10, label='the officer who is there now', colour='#1F4E5F'),
   dict(at=0.30, label='somebody else', colour='#9AA7AE'),
   dict(at=0.62, label='somebody else again', colour='#9AA7AE'),
   dict(at=0.90, label='and nobody remembers the first decision', colour='#A8372E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.12, label='the total over fifteen years differs by about three per cent'),
   dict(at=0.52, label='the cheap option is bought five times by four different people')])]),

"fig_a12_u03_p11_v04b": dict(type='V4', height=720,
 title='Two seats in year four',
 sub='Both have been in service for four years. One of them is still in service.',
 alt='Two seats photographed in year four, one cloth with two visible repairs and still in use, '
     'the other synthetic, torn once and withdrawn.',
 differences=6, prompt='Find the six. One of them is a small label under the seat, and it is the '
                       'one the accountant will want.',
 left=dict(label='cloth, year 4', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=140, bh=22, colour='#D9A441'),
   dict(kind='label', x=300, y=210, text='2 repairs, both visible · in service · $41 + $22',
        colour='#2E6F5E')]),
 right=dict(label='synthetic, year 4', art=[
   dict(kind='block', x=150, y=130, w=120, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='1 tear · withdrawn · $19 + $19 + $19',
        colour='#A8372E')])),
}
