"""A1.2 Unit 4 - Two Adults and Three Children - fifteen figures, as data."""
FIGURES = {
"fig_a12_u04_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='Coach 6, the second evening, half past eight',
 sub='Fourteen things to find. The booking system made four groups and the people made five.',
 alt='A train coach in the evening with eleven passengers sitting in four groups and one person '
     'alone, bags in the racks and a coat laid over somebody asleep.',
 sky='#4A535B', ground='#8C8578', ground_line=700,
 buildings=[dict(x=20, w=480, storeys=2, colour='#9EA9AE', cutaway=True,
     floor_labels=['the rack - one bag, four rows from its owner', 'seats 1 to 8'],
     label='the front of coach 6'),
   dict(x=560, w=480, storeys=2, colour='#A7B0B2', cutaway=True,
     floor_labels=['the rack', 'seats 9 to 16 - the two sisters, four children'],
     label='the middle'),
   dict(x=1100, w=480, storeys=2, colour='#9EA9AE', cutaway=True,
     floor_labels=['the rack', 'seats 17 to 24 - and one person alone'],
     label='the back')],
 props=[dict(kind='table', x=620, y=700, s=1.1), dict(kind='table', x=860, y=700, s=1.1),
   dict(kind='cup', x=680, y=654, s=1.4), dict(kind='cup', x=920, y=654, s=1.4),
   dict(kind='box', x=120, y=700, s=1.0), dict(kind='crate', x=1180, y=700, s=1.0),
   dict(kind='sign', x=1500, y=700, s=.7, text='8:30'),
   dict(kind='chair', x=1280, y=700, s=1.1)],
 people=[dict(x=220, y=700, h=88, skin=1, cloth=0, hair='grey', arm='hold'),
   dict(x=360, y=700, h=70, skin=1, cloth=2, hair='short', arm='down'),
   dict(x=700, y=700, h=86, skin=3, cloth=4, hair='bun', arm='point'),
   dict(x=900, y=700, h=86, skin=3, cloth=2, hair='long', arm='hold'),
   dict(x=1380, y=700, h=86, skin=4, cloth=3, hair='cap', arm='folded')],
 names=[dict(x=220, t='a grandmother - three full fares'),
   dict(x=360, t='one of her two grandchildren'),
   dict(x=700, t='two sisters, four children between them'),
   dict(x=900, t='and one of the four paid full price'),
   dict(x=1380, t='Sam - seventeen, alone, and not lost'),
   dict(x=1500, t='the clock: half past eight'),
   dict(x=120, t='a bag, four rows from its owner'),
   dict(x=1180, t='a coat over somebody asleep, and not theirs')],
 markers=[dict(x=220, y=580), dict(x=360, y=598), dict(x=700, y=582), dict(x=900, y=582),
   dict(x=1380, y=582), dict(x=1500, y=636), dict(x=120, y=652), dict(x=1180, y=660),
   dict(x=620, y=656), dict(x=680, y=610), dict(x=1280, y=664), dict(x=860, y=656),
   dict(x=200, y=584), dict(x=1200, y=584)]),

"fig_a12_u04_p01_v08": dict(type='V8', height=800,
 title='Eleven people, and what each is to each',
 sub='Four of the lines are dotted. Those are the ones the booking system does not know about.',
 alt='Eleven passengers drawn as a network with labelled lines saying what each is to the other, '
     'four of the lines dotted to show relationships the booking system has no record of.',
 nodes={
  'gra': dict(x=240, y=200, short='G', name='the grandmother', sub='3 full fares',
              colour='#1F4E5F'),
  'gc1': dict(x=180, y=520, short='1', name='grandchild', sub='age 9', colour='#9AA7AE'),
  'gc2': dict(x=400, y=640, short='2', name='grandchild', sub='age 6', colour='#9AA7AE'),
  's1':  dict(x=760, y=200, short='S', name='sister one', sub='two children', colour='#2E6F5E'),
  's2':  dict(x=760, y=640, short='S', name='sister two', sub='two children', colour='#2E6F5E'),
  'man': dict(x=1160, y=200, short='M', name='the man in seat 9', sub="his wife's mother",
              colour='#D9A441'),
  'mil': dict(x=1160, y=620, short='81', name='she is 81', sub='cannot travel alone',
              colour='#D9A441'),
  'sam': dict(x=1460, y=400, short='17', name='Sam', sub='alone, and not lost', r=52,
              colour='#C86B2B')},
 edges=[dict(a='gra', b='gc1', label='grandmother', sw=6),
   dict(a='gra', b='gc2', label='grandmother', sw=6),
   dict(a='s1', b='s2', label='sisters', sw=6),
   dict(a='man', b='mil', label="his wife's mother - and his wife is not here", sw=4,
        dash='7 6', colour='#D9A441'),
   dict(a='sam', b='man', label='met on Tuesday', sw=2, dash='5 6', colour='#9AA7AE'),
   dict(a='gc1', b='s1', label='cousins - and nobody has told them', sw=2, dash='5 6',
        colour='#9AA7AE'),
   dict(a='sam', b='s2', label='she lent him the coat', sw=2, dash='5 6', colour='#9AA7AE')]),

"fig_a12_u04_p01_v02a": dict(type='V2', height=780,
 title='One house, four generations',
 sub='Eleven people. Eleven words. The top floor has two names in the same years.',
 alt='A cutaway of one house drawn as the people who lived in it, four generations on four '
     'floors with the years each was there, and empty labels.',
 floors=[dict(was='1954 - 1979', now='a grandmother and her sister · two names, same years',
     year='', fill='#F1EDE2'),
   dict(was='1979 - 1998', now='a mother, a father, an aunt who stayed', year='',
     fill='#EFE6DC'),
   dict(was='1998 - 2016', now='a son, a daughter, a cousin for three of those years',
     year='', fill='#E8EEF0'),
   dict(was='2016 - now', now='one person, and a room kept for somebody who visits', year='',
     fill='#F3EADA')],
 callouts=[dict(at=0.12, text='Two women, the same twenty-five years, and no word for it'),
   dict(at=0.38, text='The aunt is on none of the documents and in all of the photographs'),
   dict(at=0.62, text='Three of these four grew up here. One was brought up here'),
   dict(at=0.88, text='A room kept for somebody is a relationship too')]),

"fig_a12_u04_p02_v07": dict(type='V7', height=820,
 title='The corridor of coach 6',
 sub='There is a bag on the floor and it belongs to neither of them.',
 alt='A sleeping-car attendant and a seventeen-year-old passenger in a train corridor with a '
     'backpack on the floor between them, each with two speech balloons and a thought balloon.',
 bg='#DFE4E2',
 set=[dict(kind='box', x=780, y=660, s=1.2), dict(kind='chair', x=1360, y=660, s=1.1),
   dict(kind='crate', x=1440, y=660, s=1.0)],
 people=[dict(x=520, h=240, skin=4, cloth=3, hair='short', arm='point', facing='right',
   label='Dev', role='he has to put a name on the bag',
   says=['Whose coat is that?', 'Is this bag yours?'],
   thinks=['Does seventeen count as alone?']),
  dict(x=1080, h=238, skin=2, cloth=1, hair='cap', arm='hold', facing='left',
   label='Sam', role='seventeen, and going to his aunt',
   says=['It\'s not mine. It\'s my sister\'s.', 'That one\'s ours. The blue one.'],
   thinks=['Do I tell him who I\'m going to?'])]),

"fig_a12_u04_p03_v09a": dict(type='V9', kind='weight', height=540,
 title='Holding a noun, or standing alone',
 sub='The left-hand words need a noun after them. The right-hand ones refuse one.',
 alt='Two groups of word boxes: possessive adjectives each drawn holding a noun, and possessive '
     'pronouns each standing alone with an empty space where the noun was.',
 parts=[dict(w=14, role='needs a noun', text='my', colour='#1F4E5F'),
   dict(w=18, role='and here it is', text='bag', colour='#9AA7AE'),
   dict(w=14, role='needs a noun', text='her', colour='#1F4E5F'),
   dict(w=18, role='and here it is', text='coat', colour='#9AA7AE'),
   dict(w=18, role='stands alone', text='mine', colour='#C86B2B'),
   dict(w=18, role='stands alone', text='hers', colour='#C86B2B'),
   dict(w=20, role='does both, and only this one', text='his', colour='#2E6F5E')],
 note='My, your, his, her, our, their go in front of a noun. Mine, yours, his, hers, ours, '
      'theirs go on their own. His is in both lists and it is the only word that is.'),

"fig_a12_u04_p03_v09b": dict(type='V9', kind='mirror', height=660,
 title='The hook attaches to the owner',
 sub="'s goes on the person who owns, never on the thing owned. Of does the same job backwards.",
 alt='Two sentence diagrams, the first showing the possessive s attached to the owner and the '
     'second showing of doing the same job with the order reversed.',
 labels=["WITH 'S", 'WITH OF'],
 between='↕ same meaning, opposite order, and the hook is always on the owner',
 active=dict(parts=[dict(w=24, role='agent', text="my sister's"),
   dict(w=22, role='affected', text='coat'),
   dict(w=34, role='hidden', text='the owner comes first')]),
 passive=dict(parts=[dict(w=16, role='hidden', text='the'),
   dict(w=20, role='affected', text='door'),
   dict(w=12, role='action', text='of'),
   dict(w=26, role='agent', text='the coach')]),
 rule='People take ’s: my sister’s coat, the guard’s keys. Things usually take '
      'of: the door of the coach, the end of the line. Both are correct with either, and the '
      'wrong choice sounds foreign rather than wrong.'),

"fig_a12_u04_p03_v11": dict(type='V11', height=700,
 title='The word that reached for a noun that was not there',
 alt='Two panels comparing It\'s not my with It\'s not mine, the first showing my reaching '
     'forward to an empty box.',
 wrong=dict(sentence="It's not my.",
            boundary=0.34, boundary_label='not',
            event=0.62, event_label='my - and then nothing',
            why='My is a word that holds something. It cannot be the last word in a sentence '
                'any more than the can. The listener hears my and waits for the noun, and the '
                'sentence stops, so they assume they missed something and ask you to repeat it.'),
 right=dict(sentence="It's not mine.",
            boundary=0.34, boundary_label='not',
            event=0.58, event_label='mine - a word built to stand alone',
            why='English keeps two sets of these words: one for in front of a noun and one for '
                'on its own. Six and six, and only his belongs to both. Once you have the pairs '
                '- my/mine, your/yours, her/hers, our/ours, their/theirs - the rest is automatic.'),
 misconception='Many languages have one form and let the noun disappear. English kept two, '
               'which is why this error survives into C1 in speech even in learners who would '
               'never write it.'),

"fig_a12_u04_p04_v04a": dict(type='V4', height=720,
 title='One photograph, two descriptions',
 sub='The left names relationships. The right names what people are doing.',
 alt='Two written descriptions of the same photograph side by side, one listing relationships '
     'and one listing actions.',
 differences=6, prompt='Find the six. Only one of the two lets you pick this photograph out of '
                       'six similar ones. Which, and why?',
 left=dict(label='relationships', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=180, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='her brother · my cousin’s son · not related to any of them',
        colour='#2E6F5E')]),
 right=dict(label='actions', art=[
   dict(kind='block', x=150, y=130, w=200, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='block', x=150, y=66, w=150, bh=22, colour='#C86B2B'),
   dict(kind='label', x=300, y=210,
        text='smiling · holding a cup · looking away — and so is everybody',
        colour='#C86B2B')])),

"fig_a12_u04_p05_v05": dict(type='V5', height=900,
 title='The family fare page',
 sub='It defines child. It defines adult. It never defines family.',
 alt='The family fare page from the company website showing the offer, four conditions, '
     'definitions of child and adult, and a line about proof of relationship, with no definition '
     'of family anywhere.',
 rows=[dict(t='org', text='PRAIRIE LINE  -  FAMILY FARE'),
   dict(t='sign', text='TWO ADULTS AND UP TO THREE CHILDREN FOR THE PRICE OF TWO ADULTS'),
   dict(t='rule'),
   dict(t='head', text='CONDITIONS'),
   dict(t='grid', cols=['NO.', 'CONDITION', ''],
     data=[['1', 'ALL TRAVEL ON ONE BOOKING', ''],
           ['2', 'ALL TRAVEL TOGETHER, BOTH WAYS', ''],
           ['3', 'MAXIMUM THREE CHILDREN', ''],
           ['4', 'NOT VALID 20 DEC - 4 JAN', '']]),
   dict(t='rule'),
   dict(t='head', text='DEFINITIONS'),
   dict(t='kv', k='Child', v='2 to 15 inclusive', mono=True),
   dict(t='kv', k='Infant (free)', v='under 2', mono=True),
   dict(t='kv', k='Adult', v='16 and over', mono=True),
   dict(t='kv', k='Family', v='(not defined)', mono=False),
   dict(t='rule'),
   dict(t='para', text='"Proof of relationship may be requested." One line, at the bottom, in '
     'the same size as the rest. It is the only sentence on the page that puts a person at a '
     'counter in charge of the answer.')],
 callouts=[dict(at=0.12, text='Two and three. The numbers are the only thing that is certain'),
   dict(at=0.34, text='Four conditions, and all four are about the booking, not the people'),
   dict(at=0.60, text='Two ages for child because under-twos are free and sixteen is an adult'),
   dict(at=0.70, text='The word in the title, and it is not defined anywhere'),
   dict(at=0.92, text='May be requested. By whom, and on what grounds?')]),

"fig_a12_u04_p06_v03a": dict(type='V3',
 title='Whose is this?',
 sub='One bag, six answers. Each one tells you something different about the speaker.',
 alt='Six panels showing six different answers to the question whose is this, from a name with '
     'an apostrophe s to a shrug.',
 panels=[
  dict(caption="1 \"It's Sam's.\" - a name",
       art=[dict(kind='doc', x=160, y=0)]),
  dict(caption='2 "It\'s mine." - standing alone',
       art=[dict(kind='person', x=160, y=0, h=110, skin=2, cloth=1)]),
  dict(caption='3 "It\'s my sister\'s." - a relationship',
       art=[dict(kind='person', x=160, y=0, h=110, skin=3, cloth=4)]),
  dict(caption='4 "It belongs to him." - formal',
       art=[dict(kind='arrow', x=160, y=50)]),
  dict(caption='5 "A friend of mine." - one of several',
       art=[dict(kind='person', x=160, y=0, h=110, skin=4, cloth=3)]),
  dict(caption='6 A shrug - and that is an answer too',
       art=[dict(kind='gap', x=160, y=20, w=100, bh=60)])]),

"fig_a12_u04_p07_v10": dict(type='V10', kind='groups', height=700,
 title='One apostrophe, three sounds',
 sub='Exactly the rule you learned for plurals, and for he-she-it. The third time it is free.',
 alt='Three columns of possessive forms sorted by the sound the ending makes, with the rule '
     'written under each.',
 groups=[
  dict(ipa='/s/', colour='#1F4E5F', rule='after a quiet sound',
       words=["Dev's", "Kate's", "the guard's", "my aunt's", "the cat's"],
       before='the same rule as cats and works and asked - three units, one rule'),
  dict(ipa='/z/', colour='#2E6F5E', rule='after a loud sound',
       words=["Sam's", "Ruth's", "my brother's", "the children's", "the dog's"],
       before='a vowel or /m/ /n/ /l/ /r/ before it, and your voice stays on'),
  dict(ipa='/ɪz/', colour='#C86B2B', rule='after a hissing sound',
       words=["Ross's", "the nurse's", "George's", "my niece's", "the horse's"],
       before='the word already ends in a hiss, so a vowel has to come between')]),

"fig_a12_u04_p09_v02b": dict(type='V2', height=780,
 title='Where your English came from',
 sub='Four layers. The thin one at the bottom is the only one that is yours.',
 alt='A cutaway of one learner\'s English by source: the school layer, the song layer, the one '
     'person they message, and a thin layer labelled invented.',
 floors=[dict(was='the school layer', now='the shapes · the tenses · permission to be wrong',
     year='', fill='#E8EEF0'),
   dict(was='the song layer', now='about forty words you will never lose, and no grammar',
     year='', fill='#F3EADA'),
   dict(was='one person', now='almost everything you actually say out loud', year='',
     fill='#EFE6DC'),
   dict(was='invented', now='the sentences nobody said to you first', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The only layer anybody is paid to give you'),
   dict(at=0.38, text='Free, involuntary, and extremely sticky'),
   dict(at=0.62, text='The thickest layer, and most learners do not have one'),
   dict(at=0.88, text='Thin, and growing, and nobody can take it off you')]),

"fig_a12_u04_p09_v03b": dict(type='V3',
 title='One phrase, five meetings',
 sub='Nobody taught it. By panel five the learner owns it.',
 alt='Five panels on one phrase: hearing it in a song, not understanding it, hearing it again in '
     'conversation, using it wrongly, and using it correctly.',
 panels=[
  dict(caption='1 In a song. You hear it',
       art=[dict(kind='block', x=150, y=10, w=110, bh=80, colour='#8C6A9E')]),
  dict(caption='2 You do not understand it',
       art=[dict(kind='gap', x=150, y=20, w=110, bh=60)]),
  dict(caption='3 In a conversation, three weeks later',
       art=[dict(kind='person', x=150, y=0, h=110, skin=3, cloth=2)]),
  dict(caption='4 You use it, and it is wrong',
       art=[dict(kind='cross', x=150, y=50)]),
  dict(caption='5 You use it, and it is yours',
       art=[dict(kind='tick', x=150, y=50)])]),

"fig_a12_u04_p10_v12": dict(type='V12',
 title='Coach 6, four bands',
 sub='The bookings, the actual groups, who is looking after whom, and who got the discount. '
     'They do not line up anywhere.',
 alt='An infographic of one train coach with bands for the bookings, the real groups, who is '
     'caring for whom, and which booking received the family fare.',
 span=['seat 1', 'seat 24'], ticks=4,
 tick_labels=['seat 1', 'seat 8', 'seat 16', 'seat 24'],
 bands=[dict(name='The bookings', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.22}, label='booking A - 3 people', colour='#1F4E5F'),
   dict(**{'from': 0.24, 'to': 0.62}, label='booking B - 6 people', colour='#2E6F5E'),
   dict(**{'from': 0.64, 'to': 0.84}, label='booking C - 2 people', colour='#D9A441'),
   dict(**{'from': 0.86, 'to': 1.0}, label='booking D - 1 person', colour='#C86B2B')]),
  dict(name='The real groups', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.22}, label='a grandmother and two grandchildren',
        colour='#1F4E5F'),
   dict(**{'from': 0.24, 'to': 0.44}, label='sister one and two children', colour='#2E6F5E'),
   dict(**{'from': 0.46, 'to': 0.62}, label='sister two and two children', colour='#2E6F5E'),
   dict(**{'from': 0.64, 'to': 0.84}, label='a man and his wife\'s mother', colour='#D9A441'),
   dict(**{'from': 0.86, 'to': 1.0}, label='Sam, and a borrowed coat', colour='#C86B2B')]),
  dict(name='Looking after', type='events', items=[
   dict(at=0.10, label='one adult, two children', colour='#1F4E5F'),
   dict(at=0.40, label='two adults, four children', colour='#2E6F5E'),
   dict(at=0.72, label='one adult, one adult of 81', colour='#D9A441'),
   dict(at=0.92, label='nobody', colour='#9AA7AE')]),
  dict(name='Got the discount', type='bars', items=[
   dict(**{'from': 0.24, 'to': 0.62}, label='booking B - and one child paid full price',
        colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='three of the four bookings are doing care work and paying full fare'),
   dict(at=0.52, label='the only discount went to the booking with the most adults')])]),

"fig_a12_u04_p11_v04b": dict(type='V4', height=720,
 title='The same ticket counter, two rules',
 sub='The current rule on the left, the household rule on the right. The same three people.',
 alt='Two drawings of the same ticket counter, one under the current family-fare rule with a '
     'grandmother paying full fare, and one under a household rule with a document on the counter '
     'and a queue behind.',
 differences=6, prompt='Find the six. One of them is a clock, and it is the cost nobody put in '
                       'the business case.',
 left=dict(label='the rule as it is', art=[
   dict(kind='block', x=150, y=130, w=200, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='block', x=150, y=66, w=90, bh=22, colour='#9AA7AE'),
   dict(kind='label', x=300, y=210,
        text='3 people · 3 full fares · 40 seconds · 1 apology',
        colour='#A8372E')]),
 right=dict(label='the household rule', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#D9A441'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#D9A441'),
   dict(kind='block', x=150, y=66, w=200, bh=22, colour='#D9A441'),
   dict(kind='label', x=300, y=210,
        text='3 people · 1 discount · 1 document · 90 seconds · 4 waiting',
        colour='#D9A441')])),
}
