"""A1.2 Unit 5 - Is There a Doctor on Board? - fifteen figures, as data."""
FIGURES = {
"fig_a12_u05_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The kitchen car, the third morning, quarter past five',
 sub='Fourteen things to find. The floor under the mat is worn in the shape of two feet.',
 alt='A narrow galley kitchen on a moving train before dawn, with a stove, two sinks, a rubber '
     'mat on a worn floor, a handrail, and a cupboard with a green cross and a padlock.',
 sky='#2E3A42', ground='#7D7568', ground_line=700,
 buildings=[dict(x=20, w=440, storeys=2, colour='#A8ADA6', cutaway=True,
     floor_labels=['the shelf', 'the stove and the two sinks'],
     label='the galley - two metres wide'),
   dict(x=520, w=400, storeys=2, colour='#9FA7A4', cutaway=True,
     floor_labels=['the rail', 'the mat, and the floor under it'],
     label='where Ruth stands'),
   dict(x=980, w=600, storeys=2, colour='#8F9A9E', cutaway=True,
     floor_labels=['the cupboard with the green cross', 'the door to the dining car'],
     label='the end of the car')],
 props=[dict(kind='sign', x=480, y=700, s=.7, text='5:15'),
   dict(kind='cup', x=200, y=700, s=1.6), dict(kind='table', x=260, y=700, s=1.1),
   dict(kind='crate', x=1060, y=700, s=1.0), dict(kind='box', x=1160, y=700, s=1.0),
   dict(kind='chair', x=1420, y=700, s=1.1),
   dict(kind='hoarding', x=1240, y=700, s=.7, w=140)],
 people=[dict(x=700, y=700, h=88, skin=1, cloth=0, hair='grey', arm='hold'),
   dict(x=1340, y=700, h=86, skin=3, cloth=2, hair='bun', arm='point'),
   dict(x=380, y=700, h=86, skin=4, cloth=3, hair='cap', arm='down'),
   dict(x=900, y=700, h=86, skin=2, cloth=4, hair='short', arm='folded'),
   dict(x=1500, y=700, h=86, skin=0, cloth=1, hair='long', arm='hold')],
 names=[dict(x=700, t='Ruth - twenty-three years in this spot'),
   dict(x=1340, t='Nadia - as far into the galley as anybody gets'),
   dict(x=380, t='the second cook, washing up'),
   dict(x=900, t='the handrail, and one hand always on it'),
   dict(x=1500, t='the door to the dining car'),
   dict(x=480, t='the clock: quarter past five'),
   dict(x=1240, t='the cupboard with the green cross, padlocked'),
   dict(x=200, t='the first coffee of the day')],
 markers=[dict(x=700, y=580), dict(x=1340, y=582), dict(x=380, y=582), dict(x=900, y=582),
   dict(x=1500, y=582), dict(x=480, y=636), dict(x=1240, y=644), dict(x=200, y=650),
   dict(x=260, y=656), dict(x=1060, y=660), dict(x=1160, y=652), dict(x=1420, y=664),
   dict(x=200, y=584), dict(x=1100, y=584)]),

"fig_a12_u05_p01_v08": dict(type='V8', height=800,
 title='One body, eight movements, nine hours',
 sub='The number on each line is how many times that movement happens in one shift. The largest '
     'is the one nobody counts.',
 alt='A body at the centre joined by labelled lines to eight movements - stand, bend, lift, '
     'carry, stretch, breathe, turn and hold - each line carrying the number of times it occurs '
     'in a nine-hour shift.',
 nodes={
  'bod': dict(x=800, y=400, short='9h', name='one shift', sub='nine hours', r=60,
              colour='#1C2B33'),
  'sta': dict(x=320, y=180, short='S', name='stand', sub='9 hours of it', colour='#A8372E'),
  'ben': dict(x=240, y=460, short='B', name='bend', sub='about 340 times', colour='#C86B2B'),
  'lif': dict(x=400, y=680, short='L', name='lift', sub='about 120 times', colour='#C86B2B'),
  'car': dict(x=800, y=720, short='C', name='carry', sub='about 90 times', colour='#D9A441'),
  'str': dict(x=1200, y=680, short='X', name='stretch', sub='about 6 times', colour='#2E6F5E'),
  'tur': dict(x=1360, y=440, short='T', name='turn', sub='about 1,100 times', colour='#8C6A9E'),
  'hol': dict(x=1280, y=180, short='H', name='hold the rail', sub='every time it moves',
              colour='#1F4E5F')},
 edges=[dict(a='sta', b='bod', label='nine hours, on one square metre', sw=7, colour='#A8372E'),
   dict(a='ben', b='bod', label='340 - and the knees are the question', sw=6),
   dict(a='lif', b='bod', label='120 - a second each', sw=5),
   dict(a='car', b='bod', label='90 - a minute each', sw=5),
   dict(a='str', b='bod', label='6, and all six in the last hour', sw=2, dash='6 5',
        colour='#2E6F5E'),
   dict(a='tur', b='bod', label='1,100 - nobody has ever counted this one', sw=4,
        colour='#8C6A9E'),
   dict(a='hol', b='bod', label='every curve, every point, for 23 years', sw=4)]),

"fig_a12_u05_p01_v02a": dict(type='V2', height=780,
 title='Nine hours, in section',
 sub='Eleven movements. Eleven words. Hour six has two minutes in it that are not like the rest.',
 alt='A cutaway of one nine-hour shift showing what the body does in each block of hours, with '
     'empty labels.',
 floors=[dict(was='hours 1 to 3', now='stand · bend · lift · the first sitting',
     year='', fill='#E8EEF0'),
   dict(was='hours 4 to 5', now='carry · turn · the second sitting · no water drunk',
     year='', fill='#F3EADA'),
   dict(was='hour 6', now='two minutes sitting down · the only two in the shift', year='',
     fill='#EFE6DC'),
   dict(was='hours 7 to 9', now='stand · the third sitting · the back · and the mat',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Three hours before anybody notices they have not sat down'),
   dict(at=0.38, text='There is a tap two metres away and nobody uses it'),
   dict(at=0.62, text='Two minutes. It is in no document and it is the most important part'),
   dict(at=0.88, text='Hour seven is where the pain starts, every day, for twenty-three years')]),

"fig_a12_u05_p02_v07": dict(type='V7', height=820,
 title='The galley doorway',
 sub='One of them is in the kitchen. The other cannot come further in than the door.',
 alt='A cook at a stove in a narrow galley and a service manager standing in the doorway, each '
     'with two speech balloons and a thought balloon.',
 bg='#E2E3DC',
 set=[dict(kind='table', x=740, y=660, s=1.4), dict(kind='cup', x=800, y=614, s=1.4),
   dict(kind='crate', x=1360, y=660, s=1.0)],
 people=[dict(x=520, h=242, skin=1, cloth=0, hair='grey', arm='hold', facing='right',
   label='Ruth', role='twenty-three years at this stove',
   says=['It\'s nothing. It\'s my back.', 'I\'m fine. I\'ve got four hundred breakfasts.'],
   thinks=['If I say yes, what happens to me?']),
  dict(x=1080, h=238, skin=3, cloth=2, hair='bun', arm='point', facing='left',
   label='Nadia', role='she has to decide what this conversation is',
   says=['You should sit down. You shouldn\'t lift that.',
         'Why don\'t you see a doctor in Winnipeg?'],
   thinks=['Is this a conversation or a report?'])]),

"fig_a12_u05_p03_v09a": dict(type='V9', kind='ladder', height=780,
 title='Five rungs of the same advice',
 sub='The advice does not change. The rung decides whether it is taken.',
 alt='A vertical ladder of five ways to give the same advice, from You must at the top down to '
     'It might help at the bottom, getting softer at each rung.',
 top_label='hardest', bottom_label='softest',
 steps=[dict(form='You must sit down.', meaning='an order · and it will be resented'),
   dict(form='You should sit down.', meaning='advice · clear, and still from above'),
   dict(form="Why don't you sit?", meaning='a suggestion · the one people use'),
   dict(form='You could sit down.', meaning='an option · no pressure at all'),
   dict(form='It might help.',
        meaning='barely advice · and sometimes the only one that works')]),

"fig_a12_u05_p03_v09b": dict(type='V9', kind='scope', height=660,
 title="Why don't you, taken apart",
 sub='A negative question in form. A suggestion in meaning. The answer is not a reason.',
 alt='A sentence drawn as words with brackets marking the question shape above and the meaning '
     'below, showing that the expected reply is not an explanation.',
 words=['Why', "don't", 'you', 'see', 'a', 'doctor', '?'],
 focus=[0, 1, 3],
 brackets=[dict(**{'from': 0, 'to': 2}, lane=0, colour='#C86B2B',
     label='the FORM: a negative question, as if asking for a reason'),
   dict(**{'from': 3, 'to': 6}, lane=0, colour='#1F4E5F',
     label='the VERB: plain, as after should and can'),
   dict(**{'from': 0, 'to': 6}, lane=1, colour='#2E6F5E',
     label='the MEANING: a suggestion. The expected answer is yes or no, never because.')]),

"fig_a12_u05_p03_v11": dict(type='V11', height=700,
 title='The to with nowhere to stand',
 alt='Two panels comparing You should to sit with You should sit, the first showing to wedged '
     'between a helper and its verb.',
 wrong=dict(sentence='You should to sit down.',
            boundary=0.34, boundary_label='should',
            event=0.56, event_label='to - and there is no room for it',
            why='Should is a helper, and a helper and its verb touch. Nothing goes between them: '
                'not to, not an ending, not another helper. This is the third time you have met '
                'this rule - it was true of can in the last book and it is true of must in two '
                'units\' time.'),
 right=dict(sentence='You should sit down.',
            boundary=0.34, boundary_label='should',
            event=0.52, event_label='sit - touching, and plain',
            why='Helper, verb, nothing in between. The test is simple: if you can put a verb '
                'straight after it with no to, it is one of this family - can, could, should, '
                'must, will, might - and they all behave the same way.'),
 misconception='Want, need, try and like all take to: I want to sit, I need to rest. So to feels '
               'like the normal way to join two verbs, and it is - except after this one small '
               'family of about ten words, which happen to be the ten you use most.'),

"fig_a12_u05_p04_v04a": dict(type='V4', height=720,
 title='The same advice, two openings',
 sub='Left: You should. Right: a question. Everything after the first three words is identical.',
 alt='Two versions of the same piece of advice side by side, one opening with you should and one '
     'opening with a question, with the outcome of each.',
 differences=6, prompt='Find the six. One of them was followed. Which, and what did the opening '
                       'do to the rest of the conversation?',
 left=dict(label='You should', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='"You should see a doctor." — "I\'m fine."',
        colour='#C86B2B')]),
 right=dict(label='a question', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=220, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=160, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='"You\'re in Winnipeg Thursday. Why don\'t you?" — she went',
        colour='#2E6F5E')])),

"fig_a12_u05_p05_v05": dict(type='V5', height=900,
 title='Inside the cupboard door',
 sub='Nine items, a date, a signature, and a telephone number.',
 alt='The contents list taped inside the door of a first-aid cupboard, with nine items, two of '
     'them crossed off, a date checked nineteen months earlier, a signature, and a telephone '
     'number for medical advice.',
 rows=[dict(t='org', text='PRAIRIE LINE  -  CAR 5  -  MEDICAL CUPBOARD'),
   dict(t='grid', cols=['NO.', 'ITEM', 'PRESENT'],
     data=[['1', 'BANDAGES, LARGE', 'YES'],
           ['2', 'BANDAGES, SMALL', 'YES'],
           ['3', 'BLANKET', 'YES'],
           ['4', 'GLOVES', 'YES'],
           ['5', 'SCISSORS', 'YES'],
           ['6', 'ICE PACK', 'CROSSED OFF'],
           ['7', 'GLUCOSE GEL', 'CROSSED OFF'],
           ['8', 'TORCH', 'YES'],
           ['9', 'CONTENTS LIST', 'YES']]),
   dict(t='rule'),
   dict(t='kv', k='Last checked', v='19 months ago', mono=True),
   dict(t='kv', k='Checked by', v='signature, illegible', mono=False),
   dict(t='kv', k='Padlock key held by', v='service manager', mono=False),
   dict(t='rule'),
   dict(t='sign', text='AND THE LAST LINE:'),
   dict(t='para', text='"For medical advice telephone 1-800-555-0199." The number answers in '
     'nine seconds. The train is up to eleven hours from a town with a hospital.')],
 callouts=[dict(at=0.14, text='Five of the nine are for cuts. Almost nothing here is'),
   dict(at=0.40, text='The ice pack went and was not replaced'),
   dict(at=0.46, text='The glucose gel is the one item here for an emergency'),
   dict(at=0.68, text='Nineteen months. The list says the list is present'),
   dict(at=0.92, text='A telephone number, and eleven hours of track')]),

"fig_a12_u05_p06_v03a": dict(type='V3',
 title='Picking a box up off the floor',
 sub='Six panels. The difference between the first and the last is where the knees are.',
 alt='Six panels showing the same movement of lifting a box from the floor, from the common way '
     'to the way that does not hurt.',
 panels=[
  dict(caption='1 Bend at the waist - everybody does this',
       art=[dict(kind='person', x=150, y=0, h=90, skin=1, cloth=0)]),
  dict(caption='2 The back takes all of it',
       art=[dict(kind='cross', x=150, y=50)]),
  dict(caption='3 Stand closer to the box',
       art=[dict(kind='person', x=150, y=0, h=110, skin=1, cloth=0)]),
  dict(caption='4 Bend the knees, not the back',
       art=[dict(kind='person', x=150, y=0, h=96, skin=1, cloth=0, arm='hold')]),
  dict(caption='5 Lift with the legs, breathe out',
       art=[dict(kind='arrow', x=150, y=60)]),
  dict(caption='6 Turn with the feet, not the waist',
       art=[dict(kind='tick', x=150, y=50)])]),

"fig_a12_u05_p07_v10": dict(type='V10', kind='mouth', height=680,
 title='Two oo sounds',
 sub='Both are rounded. The difference is length, and in should the l is not there at all.',
 alt='Two mouth cross-sections for the short oo of should and the long oo of food, with minimal '
     'pairs under each.',
 sounds=[
  dict(ipa='/ʊ/', desc='short, and the tongue is lower and further back',
       examples='should · could · good · book · foot', length='short',
       tongue=dict(high=.68, front=.26), lips='round'),
  dict(ipa='/uː/', desc='long, high and far back - the lips push forward',
       examples='food · soon · move · blue · two', length='long',
       tongue=dict(high=.90, front=.14), lips='round')]),

"fig_a12_u05_p09_v02b": dict(type='V2', height=780,
 title='Four kinds of advice, and one behaviour',
 sub='The bottom layer matches none of the three above it, and it is the one that is working.',
 alt='A cutaway of a learner\'s study advice in four layers - the teacher, the internet, a '
     'friend, and what the learner actually does.',
 floors=[dict(was='what the teacher said', now='study every day · read aloud · make cards',
     year='', fill='#E8EEF0'),
   dict(was='what the internet said', now='six apps · four methods · one of them is a lie',
     year='', fill='#F3EADA'),
   dict(was='what a friend said', now='just watch things · it worked for them', year='',
     fill='#EFE6DC'),
   dict(was='what you actually do', now='one thing, three days a week, badly - and it is working',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Correct, complete, and designed for somebody with more hours'),
   dict(at=0.38, text='The layer that produces the most guilt per minute read'),
   dict(at=0.62, text='True for one person, and that person is not you'),
   dict(at=0.88, text='Nobody gave you this one. It is the only one with evidence behind it')]),

"fig_a12_u05_p09_v03b": dict(type='V3',
 title='What advice actually costs',
 sub='Five panels. Panel four costs more than panels one to three together.',
 alt='Five panels showing advice being given, agreed with, not done, felt bad about, and then '
     'something else being done that works.',
 panels=[
  dict(caption='1 You are given advice',
       art=[dict(kind='person', x=150, y=0, h=110, skin=0, cloth=1, arm='point')]),
  dict(caption='2 You agree with it',
       art=[dict(kind='tick', x=150, y=50)]),
  dict(caption='3 You do not do it',
       art=[dict(kind='gap', x=150, y=20, w=110, bh=70)]),
  dict(caption='4 You feel bad for three weeks',
       art=[dict(kind='block', x=150, y=0, w=110, bh=110, colour='#A8372E')]),
  dict(caption='5 You do something else, and it works',
       art=[dict(kind='block', x=150, y=0, w=110, bh=60, colour='#2E6F5E'),
            dict(kind='tick', x=150, y=130)])]),

"fig_a12_u05_p10_v12": dict(type='V12',
 title='Forty-one events, one year',
 sub='The band with the most activity in it is the one with no training behind it.',
 alt='An infographic of forty-one medical events on the line showing where the train was, how '
     'far from a hospital, whether a doctor answered, and what the crew did.',
 span=['0 h', '11 h from a hospital'], ticks=4,
 tick_labels=['in a city', '3 h', '7 h', '11 h'],
 bands=[dict(name='Where it happened', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.24}, label='9 events, near a city', colour='#2E6F5E'),
   dict(**{'from': 0.26, 'to': 0.58}, label='14 events', colour='#D9A441'),
   dict(**{'from': 0.60, 'to': 1.0}, label='18 events, on the prairie', colour='#A8372E')]),
  dict(name='A doctor answered', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.24}, label='8 of 9', colour='#2E6F5E'),
   dict(**{'from': 0.26, 'to': 0.58}, label='11 of 14', colour='#D9A441'),
   dict(**{'from': 0.60, 'to': 1.0}, label='11 of 18', colour='#A8372E')]),
  dict(name='What it actually needed', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.52}, label='26 - a chair, water, and somebody calm',
        colour='#1F4E5F'),
   dict(**{'from': 0.54, 'to': 0.80}, label='11 - a nurse or a doctor', colour='#C86B2B'),
   dict(**{'from': 0.82, 'to': 1.0}, label='4 - an unscheduled stop', colour='#A8372E')]),
  dict(name='Minutes to first response', type='line',
   points=[(0, 2), (0.3, 4), (0.65, 4), (1.0, 6)], end_label='6 min'),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='most events needed a chair and a calm voice, not a doctor'),
   dict(at=0.44, label='the crew did all forty-one and were trained for none of them')])]),

"fig_a12_u05_p11_v04b": dict(type='V4', height=720,
 title='The same event, two systems',
 sub='Left: as it happens now. Right: with somebody on the train who has been trained.',
 alt='Two drawings of the same medical event, one with an announcement and a hundred and '
     'ninety-two heads turning, the other with no announcement and one person walking.',
 differences=6, prompt='Find the six. One of them is the number of passengers looking, and it is '
                       'the one the training was not bought for.',
 left=dict(label='as it happens now', art=[
   dict(kind='block', x=150, y=130, w=250, bh=22, colour='#A8372E'),
   dict(kind='block', x=150, y=98, w=250, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=66, w=250, bh=22),
   dict(kind='label', x=300, y=210,
        text='1 announcement · 192 heads turn · 4 minutes · 1 untrained voice',
        colour='#A8372E')]),
 right=dict(label='with a trained responder', art=[
   dict(kind='block', x=150, y=130, w=120, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=250, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=180, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='0 announcements · 3 heads turn · 40 seconds · 1 trained one',
        colour='#2E6F5E')])),
}
