"""A1.2 Unit 6 - The Dining Car in 2035 - fifteen figures, as data."""
FIGURES = {
"fig_a12_u06_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The dining car, seven in the evening, second sitting',
 sub='Fourteen things to find. Four tables have people at them who did not arrive together.',
 alt='A train dining car in the evening with eleven tables and thirty-eight people, a serving '
     'hatch with the cook visible behind it, and four tables of strangers.',
 sky='#3B4752', ground='#8A8278', ground_line=700,
 buildings=[dict(x=20, w=380, storeys=3, colour='#C2B08A', cutaway=True,
     floor_labels=['the roof vent', 'the hatch', 'the galley, through the hatch'],
     label='the kitchen end'),
   dict(x=460, w=620, storeys=3, colour='#A9AFA8', cutaway=True,
     floor_labels=['the roof', 'the luggage rack', 'tables 1 to 7'],
     label='the dining car - eleven tables'),
   dict(x=1140, w=440, storeys=3, colour='#A9AFA8', cutaway=True,
     floor_labels=['the roof', 'the window line', 'tables 8 to 11'],
     label='the far end')],
 props=[dict(kind='table', x=520, y=700, s=1.1), dict(kind='table', x=700, y=700, s=1.1),
   dict(kind='table', x=880, y=700, s=1.1), dict(kind='table', x=1200, y=700, s=1.1),
   dict(kind='cup', x=560, y=654, s=1.4), dict(kind='cup', x=1240, y=654, s=1.4),
   dict(kind='chair', x=640, y=700, s=1.0), dict(kind='chair', x=1160, y=700, s=1.0),
   dict(kind='sign', x=420, y=700, s=.7, text='7:00')],
 people=[dict(x=200, y=700, h=88, skin=1, cloth=0, hair='grey', arm='hold'),
   dict(x=760, y=700, h=86, skin=4, cloth=3, hair='cap', arm='down'),
   dict(x=820, y=700, h=86, skin=2, cloth=4, hair='long', arm='hold'),
   dict(x=1280, y=700, h=86, skin=3, cloth=2, hair='bun', arm='point'),
   dict(x=1340, y=700, h=86, skin=0, cloth=1, hair='short', arm='folded')],
 names=[dict(x=200, t='Ruth, through the hatch'),
   dict(x=760, t='two people who booked together'),
   dict(x=820, t='and both of them are looking at a phone'),
   dict(x=1280, t='table nine - four strangers'),
   dict(x=1340, t='and they have been talking for an hour'),
   dict(x=420, t='the clock: seven o\'clock'),
   dict(x=560, t='the second sitting, thirty-eight people'),
   dict(x=1240, t='two bottles, and nobody counting')],
 markers=[dict(x=200, y=580), dict(x=760, y=582), dict(x=820, y=582), dict(x=1280, y=582),
   dict(x=1340, y=582), dict(x=420, y=636), dict(x=560, y=610), dict(x=1240, y=610),
   dict(x=520, y=656), dict(x=640, y=664), dict(x=880, y=656), dict(x=1200, y=656),
   dict(x=200, y=584), dict(x=1200, y=584)]),

"fig_a12_u06_p01_v08": dict(type='V8', height=800,
 title='Eight things, and the year each one changes',
 sub='Seven of the eight have a year on them. The eighth has a question mark, and it is the one '
     'the plan is really about.',
 alt='Eight features of the train joined to the year each is expected to change - the engine, '
     'the tickets, the beds, the windows, the food, the staff, the route and the reason people '
     'book - with one marked by a question mark.',
 nodes={
  'tra': dict(x=800, y=400, short='T', name='the train', sub='one object, eight answers', r=58,
              colour='#1C2B33'),
  'eng': dict(x=340, y=180, short='E', name='the engine', sub='electric by 2031',
              colour='#2E6F5E'),
  'tic': dict(x=240, y=440, short='$', name='the tickets', sub='no paper by 2027',
              colour='#2E6F5E'),
  'bed': dict(x=380, y=680, short='B', name='the beds', sub='refitted 2029', colour='#1F4E5F'),
  'win': dict(x=800, y=720, short='W', name='the windows', sub='unchanged since 1985',
              colour='#9AA7AE'),
  'foo': dict(x=1240, y=660, short='F', name='the food', sub='machine, 2035', colour='#C86B2B'),
  'sta': dict(x=1340, y=400, short='S', name='the staff', sub='six to four, 2033',
              colour='#A8372E'),
  'rea': dict(x=1180, y=160, short='?', name='why people book', sub='no year, no plan', r=52,
              colour='#D9A441')},
 edges=[dict(a='eng', b='tra', label='2031 · the order is signed', sw=6),
   dict(a='tic', b='tra', label='2027 · already begun', sw=5),
   dict(a='bed', b='tra', label='2029 · costed', sw=5),
   dict(a='win', b='tra', label='no plan, and no complaints either', sw=3, dash='6 5',
        colour='#9AA7AE'),
   dict(a='foo', b='tra', label='2035 · saves 400,000 a year', sw=6, colour='#C86B2B'),
   dict(a='sta', b='tra', label='2033 · two fewer people', sw=5, colour='#A8372E'),
   dict(a='rea', b='tra', label='61 per cent say the dining car', sw=3, dash='7 6',
        colour='#D9A441')]),

"fig_a12_u06_p01_v02a": dict(type='V2', height=780,
 title='One dining car, four versions',
 sub='Eleven features. Eleven words. The 2035 drawing has the fewest objects and the most text.',
 alt='A cutaway of the same dining car in 1955, 1985, now and as the 2035 plan draws it, with '
     'empty labels.',
 floors=[dict(was='1955', now='white cloth · silver · three sittings · nine staff',
     year='', fill='#F1EDE2'),
   dict(was='1985', now='plastic · two sittings · six staff · the same windows',
     year='', fill='#EFE6DC'),
   dict(was='now', now='eleven tables · two sittings · six staff · the same windows',
     year='', fill='#E8EEF0'),
   dict(was='2035, as drawn', now='a machine · no sittings · four staff · the same windows',
     year='', fill='#F3EADA')],
 callouts=[dict(at=0.12, text='Nine staff, and the train carried fewer people'),
   dict(at=0.38, text='The last time anything in this car was replaced'),
   dict(at=0.62, text='Forty years with no change at all, and no complaints'),
   dict(at=0.88, text='Fewer objects, more words - which is what a plan looks like')]),

"fig_a12_u06_p02_v07": dict(type='V7', height=820,
 title='After the second sitting',
 sub='A laptop between them. One of them has been in this car for eleven years.',
 alt='A service manager and a planner from head office sitting in an empty dining car with a '
     'laptop open between them, each with two speech balloons and a thought balloon.',
 bg='#E3E5E0',
 set=[dict(kind='table', x=760, y=660, s=1.9), dict(kind='cup', x=820, y=614, s=1.4),
   dict(kind='chair', x=1380, y=660, s=1.1)],
 people=[dict(x=520, h=240, skin=2, cloth=4, hair='short', arm='hold', facing='right',
   label='the planner', role='he has the 2035 plan',
   says=['The engine will be electric by 2031.',
         'It\'ll probably close. Seventy per cent.'],
   thinks=['The dining car is one line on page nine.']),
  dict(x=1080, h=238, skin=3, cloth=2, hair='bun', arm='point', facing='left',
   label='Nadia', role='eleven years, and she has eaten here',
   says=['I\'ll send you the booking figures.', 'I\'ll have the fish, then.'],
   thinks=['Table nine. He has never seen table nine.'])]),

"fig_a12_u06_p03_v09a": dict(type='V9', kind='branch', height=700,
 title='One word, three jobs',
 sub='Will does not change. The situation decides which of the three you have just done.',
 alt='A branching diagram from the single word will to three destinations: prediction, offer and '
     'instant decision, each with an example.',
 root='will',
 branches=[dict(label='PREDICTION - what you believe about the future', colour='#1F4E5F',
     example='The engine will be electric. -- you did not decide this; you expect it'),
   dict(label='OFFER - you are volunteering, now', colour='#2E6F5E',
     example="I'll send you the figures. -- nobody asked; you chose"),
   dict(label='INSTANT DECISION - chosen half a second ago', colour='#C86B2B',
     example="I'll have the fish, then. -- you did not know this when you sat down")]),

"fig_a12_u06_p03_v09b": dict(type='V9', kind='ladder', height=800,
 title='How sure, and where the word stands',
 sub='Two of these go at the front of the sentence and the rest go after will.',
 alt='A vertical certainty scale from definitely at the top through probably, maybe and perhaps '
     'down to definitely not, with the position each word takes in a sentence marked beside it.',
 top_label='certain', bottom_label='certain not',
 steps=[dict(form='definitely', meaning='100% · goes AFTER will: it will definitely close'),
   dict(form='certainly', meaning='95% · after will'),
   dict(form='probably', meaning='about 70% · after will: it will probably close'),
   dict(form='maybe', meaning='about 40% · at the FRONT: maybe it will close'),
   dict(form='perhaps', meaning='about 40% · at the front, and a little more formal'),
   dict(form="I don't think", meaning='about 20% · the negative goes on think, not on will'),
   dict(form="definitely won't", meaning='0% · and the negative is on will after all')]),

"fig_a12_u06_p03_v11": dict(type='V11', height=700,
 title='To, in the same gap, a second time',
 alt='Two panels comparing will to be with will be, the first showing to wedged between a helper '
     'and its verb.',
 wrong=dict(sentence='The engine will to be electric.',
            boundary=0.34, boundary_label='will',
            event=0.56, event_label='to - and the gap is not big enough',
            why='You met this gap with can in the first book and with should two units ago. '
                'Will is the same kind of word, and the rule has not changed: helper, verb, '
                'nothing in between. The family is small and now closed: can, could, should, '
                'must, will, might.'),
 right=dict(sentence='The engine will be electric.',
            boundary=0.34, boundary_label='will',
            event=0.52, event_label='be - plain, and touching',
            why='One helper, one plain verb. The same is true of the negative and the question: '
                'It won\'t be electric. Will it be electric? Nothing is ever added to the verb '
                'and nothing is ever put in front of it.'),
 misconception='Going to is the other way of talking about the future and it does take to - I am '
               'going to be late. The to belongs to going, not to the future, and learners who '
               'have met going to first carry the to across.'),

"fig_a12_u06_p04_v04a": dict(type='V4', height=720,
 title='The same forecast, twice',
 sub='The left one has a certainty word on every line. The right one has none.',
 alt='Two written forecasts side by side, one marking how confident each prediction is and one '
     'stating every prediction flatly.',
 differences=6, prompt='Find the six. Only one of the two can be argued with. Which, and why is '
                       'that a good thing?',
 left=dict(label='with certainty words', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=150, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='certain · 70% · maybe · no idea — four claims you can test',
        colour='#2E6F5E')]),
 right=dict(label='without them', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#C86B2B'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#C86B2B'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#C86B2B'),
   dict(kind='label', x=300, y=210,
        text='will · will · will · will — four claims you cannot test',
        colour='#C86B2B')])),

"fig_a12_u06_p05_v05": dict(type='V5', height=900,
 title='One page of the 2035 plan',
 sub='Five predictions, five confidence figures, one saving column, and a risks line with one '
     'word in it.',
 alt='A page of a corporate plan showing five predictions each with a date and a confidence '
     'percentage, a column of cost savings, and a risks line containing a single word.',
 rows=[dict(t='org', text='PRAIRIE LINE  -  PLAN 2035  -  PAGE 9 OF 61'),
   dict(t='grid', cols=['PREDICTION', 'BY', 'CONF.'],
     data=[['ELECTRIC TRACTION', '2031', '96%'],
           ['PAPERLESS TICKETING', '2027', '99%'],
           ['BERTH REFIT', '2029', '92%'],
           ['CREW 6 TO 4', '2033', '74%'],
           ['DINING CAR REPLACED', '2035', '70%']]),
   dict(t='rule'),
   dict(t='head', text='SAVINGS'),
   dict(t='kv', k='Crew reduction', v='$1.1 m / year', mono=True),
   dict(t='kv', k='Dining car', v='$0.4 m / year', mono=True),
   dict(t='kv', k='Ticketing', v='$0.2 m / year', mono=True),
   dict(t='kv', k='Total', v='$1.7 m / year', mono=True),
   dict(t='rule'),
   dict(t='sign', text='RISKS:'),
   dict(t='para', text='"Reputational." One word, on a page with eleven numbers on it. The '
     'booking survey is in a different document, in a different department, and nobody has ever '
     'printed the two pages next to each other.')],
 callouts=[dict(at=0.12, text='Ninety-six per cent, and the order really is signed'),
   dict(at=0.34, text='Seventy-four. The first number on this page that anybody argued about'),
   dict(at=0.42, text='Seventy, and it is the lowest confidence on the page'),
   dict(at=0.72, text='One point seven million. That is what this page is for'),
   dict(at=0.92, text='One word. The survey says sixty-one per cent')]),

"fig_a12_u06_p06_v03a": dict(type='V3',
 title='One prediction, six strengths',
 sub='The sentence is identical in all six. One word changes and the meaning moves from end to '
     'end.',
 alt='Six panels showing the same prediction with a different certainty word in each, from it '
     'will definitely close to it definitely will not close.',
 panels=[
  dict(caption='It will DEFINITELY close',
       art=[dict(kind='block', x=160, y=0, w=120, bh=120, colour='#A8372E')]),
  dict(caption='It will PROBABLY close',
       art=[dict(kind='block', x=160, y=0, w=120, bh=90, colour='#C86B2B')]),
  dict(caption='MAYBE it will close',
       art=[dict(kind='block', x=160, y=0, w=120, bh=58, colour='#D9A441')]),
  dict(caption="I DON'T THINK it will close",
       art=[dict(kind='block', x=160, y=0, w=120, bh=34, colour='#2E6F5E')]),
  dict(caption='It PROBABLY WON\'T close',
       art=[dict(kind='block', x=160, y=0, w=120, bh=18, colour='#1F4E5F')]),
  dict(caption='It DEFINITELY won\'t close',
       art=[dict(kind='gap', x=160, y=10, w=120, bh=50)])]),

"fig_a12_u06_p07_v10": dict(type='V10', kind='elision', height=720,
 title='The word that shrank to one sound',
 sub='Written in full above, said below. In every one, the wi has gone.',
 alt='Six pronouns with will attached, written at full length and then as spoken, with the wi '
     'shaded out in each.',
 pairs=[
  dict(written='I will', spoken='Ill', dropped='w', note='one sound left of a four-letter word'),
  dict(written='he will', spoken='heell', dropped='wi', note='the l joins the pronoun'),
  dict(written='it will', spoken='itll', dropped='wi', note='two beats become one'),
  dict(written='they will', spoken='thayll', dropped='wi', note='same again'),
  dict(written='that will', spoken='thatll', dropped='wi', note='and this one too'),
  dict(written='will not', spoken='wohnt', dropped='ln',
       note='the only one that changes the vowel instead')]),

"fig_a12_u06_p09_v02b": dict(type='V2', height=780,
 title='Three years, in section',
 sub='Three of these layers are measured. The bottom one is a guess, and it is the furthest away.',
 alt='A cutaway of three years of a learner\'s English: last year, now, next year at the current '
     'rate, and where the learner thinks they will be.',
 floors=[dict(was='last year', now='A1 · and you cannot remember being here', year='',
     fill='#E8EEF0'),
   dict(was='now', now='A2 · and it does not feel like a whole level', year='',
     fill='#F3EADA'),
   dict(was='next year, at this rate', now='B1 · which is a working level', year='',
     fill='#EFE6DC'),
   dict(was='where you think you will be', now='fluent · and that is four years away, not one',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Measured. You have the recording, if you made it'),
   dict(at=0.38, text='Measured. The distance from the layer above is one whole level'),
   dict(at=0.62, text='Predicted, from the only two measurements you have'),
   dict(at=0.88, text='Guessed, and the gap between this and the layer above it is the problem')]),

"fig_a12_u06_p09_v03b": dict(type='V3',
 title='The curve nobody draws',
 sub='Five panels. The fifth is the only measurement in the set.',
 alt='Five panels showing the fast start, the flat middle, the moment of doubt, the quiet '
     'improvement nobody notices, and an old recording.',
 panels=[
  dict(caption='1 Months 1 to 3 - fast, and visible',
       art=[dict(kind='block', x=150, y=0, w=110, bh=70, colour='#2E6F5E')]),
  dict(caption='2 Months 4 to 8 - flat, and the same effort',
       art=[dict(kind='block', x=150, y=0, w=110, bh=76, colour='#D9A441')]),
  dict(caption='3 Month 9 - "this is not working"',
       art=[dict(kind='person', x=150, y=0, h=110, skin=2, cloth=4)]),
  dict(caption='4 Months 10 to 12 - and it is working',
       art=[dict(kind='block', x=150, y=0, w=110, bh=100, colour='#1F4E5F')]),
  dict(caption='5 The recording from last year',
       art=[dict(kind='tick', x=150, y=50)])]),

"fig_a12_u06_p10_v12": dict(type='V12',
 title='The dining car as four numbers',
 sub='The first two bands are in the plan. The second two are in a different document.',
 alt='An infographic of the dining car showing what it costs, what it earns, what it causes '
     'passengers to spend elsewhere, and why people say they booked.',
 span=['0', '$2 m'], ticks=4,
 tick_labels=['0', '$0.7 m', '$1.4 m', '$2 m'],
 bands=[dict(name='What it costs', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.52}, label='staff, food and the car itself - $1.04 m',
        colour='#A8372E')]),
  dict(name='What it earns', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.32}, label='meals sold - $0.64 m', colour='#D9A441')]),
  dict(name='What it causes', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.92}, label='fares from people who booked for it - $1.84 m',
        colour='#2E6F5E')]),
  dict(name='Why people booked', type='events', items=[
   dict(at=0.30, label='61% - the dining car', colour='#2E6F5E'),
   dict(at=0.62, label='22% - the scenery', colour='#1F4E5F'),
   dict(at=0.86, label='17% - price, or fear of flying', colour='#9AA7AE')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.06, label='the loss is real and it is in the plan'),
   dict(at=0.46, label='the third band is larger than the first two together, and is in no plan')])]),

"fig_a12_u06_p11_v04b": dict(type='V4', height=720,
 title='Table nine at nine in the evening',
 sub='As it is, and as the 2035 plan draws it. Same table, same four people.',
 alt='Two drawings of the same table at nine in the evening, one with four strangers talking over '
     'two bottles and one with four people eating packaged sandwiches and looking at phones.',
 differences=6, prompt='Find the six. One of them is how many people are still there at ten, and '
                       'that is the number nobody has forecast.',
 left=dict(label='as it is', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=180, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='4 strangers · 2 bottles · 0 phones · 4 still there at ten',
        colour='#2E6F5E')]),
 right=dict(label='2035, as drawn', art=[
   dict(kind='block', x=150, y=130, w=140, bh=22, colour='#9AA7AE'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#9AA7AE'),
   dict(kind='label', x=300, y=210,
        text='4 strangers · 4 wrappers · 4 phones · 0 still there at ten',
        colour='#9AA7AE')])),
}
