"""A1.2 Unit 7 - Twenty-Two Red Handles - fifteen figures, as data."""
FIGURES = {
"fig_a12_u07_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The vestibule, eleven at night',
 sub='Fourteen things to find. Three of the four signs are about what you must not do.',
 alt='The narrow vestibule between two railway cars at night, with two doors, a red emergency '
     'handle in a yellow box, four signs, a notice about the brake, and one person standing '
     'alone.',
 sky='#333E48', ground='#7A7468', ground_line=700,
 buildings=[dict(x=20, w=420, storeys=3, colour='#8F9A9E', cutaway=True,
     floor_labels=['the roof', 'the door to car 6', 'the step - and it is not level'],
     label='car 6'),
   dict(x=520, w=520, storeys=3, colour='#A2A8A4', cutaway=True,
     floor_labels=['the four signs', 'the red handle in its yellow box',
                   'the floor - one and a half metres square'],
     label='the vestibule'),
   dict(x=1120, w=460, storeys=3, colour='#8F9A9E', cutaway=True,
     floor_labels=['the roof', 'the door to car 7', 'the window in the door'],
     label='car 7')],
 props=[dict(kind='sign', x=480, y=700, s=.7, text='11:00'),
   dict(kind='hoarding', x=600, y=700, s=.7, w=160, notice=True),
   dict(kind='box', x=900, y=700, s=.9),
   dict(kind='crate', x=1180, y=700, s=1.0),
   dict(kind='chair', x=1420, y=700, s=1.0),
   dict(kind='sign', x=1500, y=700, s=.7, text='EXIT')],
 people=[dict(x=800, y=700, h=88, skin=2, cloth=4, hair='long', arm='folded'),
   dict(x=300, y=700, h=86, skin=4, cloth=3, hair='cap', arm='hold'),
   dict(x=1000, y=700, h=86, skin=3, cloth=2, hair='bun', arm='point'),
   dict(x=1260, y=700, h=86, skin=1, cloth=0, hair='grey', arm='down'),
   dict(x=1360, y=700, h=86, skin=0, cloth=1, hair='short', arm='hold')],
 names=[dict(x=800, t='the only place on the train you can be alone'),
   dict(x=300, t='Dev - he checks these every trip'),
   dict(x=1000, t='Nadia - six cars away, in February'),
   dict(x=1260, t='a passenger going through to car 7'),
   dict(x=1360, t='the safety inspector, with a clipboard'),
   dict(x=480, t='the clock: eleven at night'),
   dict(x=600, t='four signs - three of them say must not'),
   dict(x=900, t='the yellow box, and the red handle in it')],
 markers=[dict(x=800, y=580), dict(x=300, y=582), dict(x=1000, y=582), dict(x=1260, y=582),
   dict(x=1360, y=582), dict(x=480, y=636), dict(x=600, y=644), dict(x=900, y=654),
   dict(x=1180, y=660), dict(x=1420, y=664), dict(x=1500, y=636), dict(x=760, y=584),
   dict(x=300, y=466), dict(x=1240, y=584)]),

"fig_a12_u07_p01_v08": dict(type='V8', height=800,
 title='Four rules, four authors',
 sub='Each line carries what happens if you break it. Two of the lines end in nothing at all.',
 alt='Four rules on the train joined to who made each one - the government, the company, the '
     'crew and nobody - with labels showing the consequence of breaking each.',
 nodes={
  'tra': dict(x=800, y=400, short='V', name='the vestibule', sub='1.5 metres square', r=56,
              colour='#1C2B33'),
  'gov': dict(x=300, y=200, short='G', name='the government', sub='the law', colour='#A8372E'),
  'com': dict(x=260, y=600, short='C', name='the company', sub='the rules', colour='#C86B2B'),
  'cre': dict(x=1240, y=200, short='K', name='the crew', sub='what is actually done',
              colour='#2E6F5E'),
  'nob': dict(x=1300, y=600, short='—', name='nobody', sub='and everybody follows it',
              colour='#9AA7AE'),
  'r1':  dict(x=800, y=120, short='1', name='do not open the door', sub='while moving',
              colour='#A8372E'),
  'r2':  dict(x=800, y=700, short='4', name='stand on the right', sub='nobody wrote this',
              colour='#9AA7AE')},
 edges=[dict(a='gov', b='r1', label='illegal · a fine of $500', sw=6, colour='#A8372E'),
   dict(a='r1', b='tra', label='sign 1, printed 2011', sw=5),
   dict(a='com', b='tra', label='sign 2 and 3 · an email could change them', sw=5,
        colour='#C86B2B'),
   dict(a='cre', b='tra', label='checked every trip · and that is a rule too', sw=5,
        colour='#2E6F5E'),
   dict(a='nob', b='r2', label='no sign, no penalty, no exceptions', sw=3, dash='6 5',
        colour='#9AA7AE'),
   dict(a='r2', b='tra', label='and everybody does it', sw=3, dash='6 5', colour='#9AA7AE')]),

"fig_a12_u07_p01_v02a": dict(type='V2', height=780,
 title='One vestibule, in section',
 sub='Eleven features. Eleven words. Each sign has the year it went up.',
 alt='A cutaway of the vestibule showing the floor, the two doors, the handle in its yellow box '
     'and the four signs, with the year of each and empty labels.',
 floors=[dict(was='above eye level', now='sign 1, 2011 · the law · the largest type',
     year='', fill='#F1EDE2'),
   dict(was='at eye level', now='sign 2 and 3 · company rules · 2016 and 2019',
     year='', fill='#EFE6DC'),
   dict(was='below eye level', now='the handle · the yellow box · sign 4, the smallest',
     year='', fill='#E8EEF0'),
   dict(was='the floor', now='the step, which is not level, and is in no sign at all', year='',
     fill='#F3EADA')],
 callouts=[dict(at=0.12, text='The only one with a fine on it, and the only one from outside'),
   dict(at=0.38, text='Two signs, both changeable by an email'),
   dict(at=0.62, text='The smallest sign is the one that tells you when to act'),
   dict(at=0.88, text='Nine people have fallen on this step. It has no sign')]),

"fig_a12_u07_p02_v07": dict(type='V7', height=820,
 title='The vestibule, with the handle between them',
 sub='He has three numbers. She has a night in February.',
 alt='A service manager and a safety inspector standing in a train vestibule with a red emergency '
     'handle between them, each with two speech balloons and a thought balloon.',
 bg='#DEE2E3',
 set=[dict(kind='box', x=780, y=660, s=1.0), dict(kind='crate', x=1360, y=660, s=1.0),
   dict(kind='chair', x=1440, y=660, s=1.0)],
 people=[dict(x=520, h=240, skin=0, cloth=1, hair='short', arm='point', facing='right',
   label='the safety inspector', role='he has eleven years of data',
   says=['You must not touch it. That is the law.',
         'Three of the four were mistakes.'],
   thinks=['Fifty minutes, three times, is two and a half hours.']),
  dict(x=1080, h=238, skin=3, cloth=2, hair='bun', arm='hold', facing='left',
   label='Nadia', role='she was six cars away in February',
   says=['We have to check them every trip.', 'You don\'t have to sign it.'],
   thinks=['Eight seconds. In February, eight seconds.'])]),

"fig_a12_u07_p03_v09a": dict(type='V9', kind='weight', height=540,
 title='Three of these four mean the same thing',
 sub='The fourth is drawn in a different colour because it means something else entirely.',
 alt='A two-by-two arrangement of must, have to, mustn\'t and don\'t have to, with the last one '
     'coloured differently because its meaning is not a prohibition.',
 parts=[dict(w=20, role='compulsory', text='must', colour='#1F4E5F'),
   dict(w=22, role='compulsory', text='have to', colour='#1F4E5F'),
   dict(w=22, role='forbidden', text="mustn't", colour='#A8372E'),
   dict(w=30, role='NOT NECESSARY - an open door', text="don't have to", colour='#2E6F5E')],
 note='Must and have to are both a wall in front of you. Mustn\'t is a wall in the other '
      'direction. Don\'t have to is not a wall at all - it is a door you may walk through or not, '
      'and swapping it with mustn\'t changes freedom into prohibition.'),

"fig_a12_u07_p03_v09b": dict(type='V9', kind='mirror', height=680,
 title='Inside the rule, or outside it',
 sub='The grammar is nearly identical. Who is making the rule is not.',
 alt='Two sentence diagrams, the first with must and the speaker inside the rule, the second with '
     'have to and an arrow arriving from outside the page.',
 labels=['MUST - the speaker', 'HAVE TO - the world'],
 between='↕ same obligation, different author',
 active=dict(parts=[dict(w=14, role='agent', text='I'),
   dict(w=18, role='action', text='must'),
   dict(w=40, role='affected', text='get more sleep'),
   dict(w=28, role='hidden', text='nobody told me this')]),
 passive=dict(parts=[dict(w=14, role='agent', text='I'),
   dict(w=22, role='action', text='have to'),
   dict(w=34, role='affected', text='wear a helmet'),
   dict(w=30, role='hidden', text='somebody else decided')]),
 rule='Have to behaves like an ordinary verb: he HAS to, did you HAVE to, I HAD to. Must has no '
      'past and no s, so had to does the past for both of them.'),

"fig_a12_u07_p03_v11": dict(type='V11', height=720,
 title='The open door where a wall was meant',
 alt='Two panels comparing You don\'t have to touch it used as a prohibition with You mustn\'t '
     'touch it, the first showing an open door where a wall was intended.',
 wrong=dict(sentence="You don't have to touch it.",
            boundary=0.36, boundary_label="don't have to",
            event=0.66, event_label='an open door - you may, if you like',
            why='The speaker meant a prohibition and produced permission. To an English ear this '
                'sentence means: it is not necessary, but go ahead if you want to. On an '
                'emergency handle that is the opposite of the intended meaning, and the listener '
                'has no way of knowing it was a mistake.'),
 right=dict(sentence="You mustn't touch it.",
            boundary=0.36, boundary_label="mustn't",
            event=0.62, event_label='a wall - this is forbidden',
            why='Mustn\'t is the prohibition. The test that never fails: don\'t have to can '
                'always be replaced by it is not necessary, and mustn\'t can always be replaced '
                'by it is forbidden. Try both on your sentence before you say it.'),
 misconception='In most languages the negative of must is the prohibition, so don\'t have to '
               'looks like it ought to be one. English split the two about four hundred years '
               'ago and kept both halves, and this is the single most consequential vocabulary '
               'error at A2.'),

"fig_a12_u07_p04_v04a": dict(type='V4', height=720,
 title='The same rules, posted twice',
 sub='The left list says what you must not do. The right list says what you must do.',
 alt='Two posted sets of rules side by side, one phrased entirely as prohibitions and one '
     'entirely as requirements, covering identical behaviour.',
 differences=6, prompt='Find the six. The two lists require exactly the same behaviour. Which '
                       'one would you put on a door, and why?',
 left=dict(label='what not to do', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#A8372E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#A8372E'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#A8372E'),
   dict(kind='label', x=300, y=210,
        text='DO NOT · DO NOT · DO NOT · NO — and a fine on each',
        colour='#A8372E')]),
 right=dict(label='what to do', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=160, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='sign in · keep right · use this door — and one reason each',
        colour='#2E6F5E')])),

"fig_a12_u07_p05_v05": dict(type='V5', height=900,
 title='The safety notice beside the handle',
 sub='The largest line on it is the penalty. The smallest is when to use it.',
 alt='The emergency safety notice beside the handle, with four numbered instructions, a penalty '
     'line in large type, a printing year and a three-part diagram.',
 rows=[dict(t='org', text='EMERGENCY DOOR RELEASE  -  CAR 6/7 VESTIBULE'),
   dict(t='sign', text='IMPROPER USE: FINE UP TO $500'),
   dict(t='rule'),
   dict(t='head', text='INSTRUCTIONS'),
   dict(t='grid', cols=['NO.', 'INSTRUCTION', 'TYPE SIZE'],
     data=[['1', 'LIFT THE YELLOW COVER', '14 pt'],
           ['2', 'PULL THE RED HANDLE DOWN', '14 pt'],
           ['3', 'STAND CLEAR OF THE DOOR', '14 pt'],
           ['4', 'USE ONLY IN AN EMERGENCY', '7 pt']]),
   dict(t='rule'),
   dict(t='kv', k='Penalty line', v='24 pt', mono=True),
   dict(t='kv', k='Printed', v='2011', mono=True),
   dict(t='kv', k='Diagram', v='3 parts, no words', mono=False),
   dict(t='kv', k='Who to tell afterwards', v='not stated', mono=False),
   dict(t='rule'),
   dict(t='para', text='Nothing on this notice says what counts as an emergency. The only '
     'sentence that mentions emergencies is the smallest line on the page, and it is an '
     'instruction not to act rather than a description of when to.')],
 callouts=[dict(at=0.12, text='Twenty-four point. It is the first thing anybody reads'),
   dict(at=0.36, text='Three instructions about the mechanism'),
   dict(at=0.48, text='Seven point. The only line about when'),
   dict(at=0.70, text='Printed in 2011, and the handle is from 1985'),
   dict(at=0.92, text='A frightened person has about two seconds to read all of this')]),

"fig_a12_u07_p06_v03a": dict(type='V3',
 title='Wear a helmet, in six places',
 sub='The same instruction. In two it is the law, in two a company rule, in one advice, in one '
     'nothing.',
 alt='Six panels showing the instruction wear a helmet on a building site, a bicycle, a '
     'motorbike, in a factory, in a sport and in a playground, with who made the rule in each.',
 panels=[
  dict(caption='Building site - the law',
       art=[dict(kind='block', x=160, y=0, w=110, bh=110, colour='#A8372E')]),
  dict(caption='Motorbike - the law',
       art=[dict(kind='block', x=160, y=0, w=110, bh=110, colour='#A8372E')]),
  dict(caption='Factory - a company rule',
       art=[dict(kind='block', x=160, y=0, w=110, bh=76, colour='#C86B2B')]),
  dict(caption='Sport - a club rule',
       art=[dict(kind='block', x=160, y=0, w=110, bh=76, colour='#C86B2B')]),
  dict(caption='Bicycle - advice, in most places',
       art=[dict(kind='block', x=160, y=0, w=110, bh=42, colour='#D9A441')]),
  dict(caption='Playground - nothing at all',
       art=[dict(kind='gap', x=160, y=10, w=110, bh=60)])]),

"fig_a12_u07_p07_v10": dict(type='V10', kind='elision', height=700,
 title='Two words that became one, again',
 sub='Written in full above, said below. In have to, the v turns into an f.',
 alt='Four obligation phrases written at full length and then as they are said, with the letters '
     'that disappear shaded out.',
 pairs=[
  dict(written='have to', spoken='hafta', dropped='ve', note='the v becomes an f'),
  dict(written='has to', spoken='hasta', dropped='s', note='same change, same reason'),
  dict(written='must not', spoken='mussnt', dropped='t', note='no t in the middle'),
  dict(written='got to', spoken='gotta', dropped='t', note='not in the exam, in every street'),
  dict(written='had to', spoken='hadta', dropped='', note='and this one survives')]),

"fig_a12_u07_p09_v02b": dict(type='V2', height=780,
 title='The study rules you did not choose',
 sub='Four layers, each labelled by who made it. The oldest is the thickest.',
 alt='A cutaway of a learner\'s study rules in four layers, each labelled with its author: a '
     'teacher in 2009, an app, a parent, and the learner.',
 floors=[dict(was='a teacher, 2009', now='write every new word down · never guess · finish the book',
     year='', fill='#F1EDE2'),
   dict(was='an app, 2021', now='a streak · ten minutes a day · never miss', year='',
     fill='#EFE6DC'),
   dict(was='a parent', now='you must not speak until you are sure', year='', fill='#E8EEF0'),
   dict(was='you', now='one rule, made this year, and it is the only one that fits', year='',
     fill='#F3EADA')],
 callouts=[dict(at=0.12, text='Fifteen years old. That teacher taught thirty children, not you'),
   dict(at=0.38, text='Designed to keep you opening an app, which is not the same goal'),
   dict(at=0.62, text='The most expensive rule on this page, and nobody said it out loud'),
   dict(at=0.88, text='One rule, yours, and checkable')]),

"fig_a12_u07_p09_v03b": dict(type='V3',
 title='A rule that outlived its reason',
 sub='Five panels. Only the fifth contains a question.',
 alt='Five panels showing a rule being given at school, followed, becoming useless, being '
     'followed anyway, and finally questioned.',
 panels=[
  dict(caption='1 A teacher gives you the rule',
       art=[dict(kind='person', x=150, y=0, h=110, skin=0, cloth=1, arm='point')]),
  dict(caption='2 You follow it, and it works',
       art=[dict(kind='tick', x=150, y=50)]),
  dict(caption='3 Your level changes. It stops working',
       art=[dict(kind='block', x=150, y=10, w=110, bh=50, colour='#D9A441')]),
  dict(caption='4 You follow it anyway, for nine years',
       art=[dict(kind='block', x=150, y=0, w=110, bh=110, colour='#9AA7AE')]),
  dict(caption='5 Somebody asks why',
       art=[dict(kind='cross', x=150, y=50)])]),

"fig_a12_u07_p10_v12": dict(type='V12',
 title='Twenty-two handles, eleven years',
 sub='The last band has one event in it that no amount of data can weigh.',
 alt='An infographic of the twenty-two emergency handles showing how many exist, how many have '
     'been used, what each use cost, and what the proposed cover would change.',
 span=['0', '22'], ticks=4,
 tick_labels=['0', '7', '14', '22'],
 bands=[dict(name='Handles', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.82}, label='18 in areas with no crew', colour='#9AA7AE'),
   dict(**{'from': 0.84, 'to': 1.0}, label='4 near the crew cars', colour='#2E6F5E')]),
  dict(name='Pulled in 11 years', type='events', items=[
   dict(at=0.06, label='2016: a child reached one', colour='#C86B2B'),
   dict(at=0.26, label='2019: somebody leaned on one', colour='#C86B2B'),
   dict(at=0.48, label='2022: mistaken for a light switch', colour='#C86B2B'),
   dict(at=0.74, label='February: a seizure in car 7', colour='#A8372E')]),
  dict(name='What each cost', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.56}, label='3 mistakes × 50 minutes = 2 h 30',
        colour='#C86B2B'),
   dict(**{'from': 0.58, 'to': 1.0}, label='1 real · the crew arrived · he is alive',
        colour='#A8372E')]),
  dict(name='What the cover changes', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.56}, label='stops all three mistakes', colour='#2E6F5E'),
   dict(**{'from': 0.58, 'to': 0.74}, label='costs 8 seconds', colour='#D9A441'),
   dict(**{'from': 0.76, 'to': 1.0}, label='$11,000 to fit', colour='#9AA7AE')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='three of the four events were in uncrewed areas'),
   dict(at=0.44, label='the one that was not is the one the data cannot weigh')])]),

"fig_a12_u07_p11_v04b": dict(type='V4', height=720,
 title='The handle, with and without a cover',
 sub='The same handle. One of them a child can reach and one of them needs a hammer.',
 alt='Two drawings of the same emergency handle, one open and reachable and one behind a clear '
     'breakable panel with a small hammer on a chain.',
 differences=6, prompt='Find the six. One of them is how far away the nearest crew member is, '
                       'and it is not drawn on either picture.',
 left=dict(label='as it is', art=[
   dict(kind='block', x=150, y=130, w=200, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='block', x=150, y=66, w=120, bh=22, colour='#A8372E'),
   dict(kind='label', x=300, y=210,
        text='open · 0 seconds · a child can reach it · 3 mistakes in 11 years',
        colour='#A8372E')]),
 right=dict(label='with the cover', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=140, bh=22, colour='#D9A441'),
   dict(kind='label', x=300, y=210,
        text='BREAK GLASS · 8 seconds · a hammer on a chain · 0 mistakes',
        colour='#2E6F5E')])),
}
