"""A1.2 Unit 8 - Twenty-Three Years and Two - fifteen figures, as data."""
FIGURES = {
"fig_a12_u08_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The crew room, half past six in the morning',
 sub='Fourteen things to find. One of the two people has written a number and stopped.',
 alt='A railway depot crew room early in the morning with a long table, nine chairs, a '
     'noticeboard with four notices and two people at opposite ends of the table filling in the '
     'same form.',
 sky='#4F5A61', ground='#8B8477', ground_line=700,
 buildings=[dict(x=20, w=420, storeys=3, colour='#AEA893', cutaway=True,
     floor_labels=['the window', 'the noticeboard - four notices', 'the lockers'],
     label='the end wall'),
   dict(x=520, w=560, storeys=3, colour='#B5B0A0', cutaway=True,
     floor_labels=['the strip light', 'the long table - nine chairs', 'the floor'],
     label='the crew room'),
   dict(x=1160, w=420, storeys=3, colour='#AEA893', cutaway=True,
     floor_labels=['the clock', 'the door to the yard', 'the step'],
     label='the way out')],
 props=[dict(kind='table', x=640, y=700, s=1.8),
   dict(kind='chair', x=600, y=700, s=1.1), dict(kind='chair', x=940, y=700, s=1.1),
   dict(kind='cup', x=700, y=654, s=1.4),
   dict(kind='hoarding', x=160, y=700, s=.7, w=160, notice=True),
   dict(kind='box', x=1220, y=700, s=1.0),
   dict(kind='sign', x=1420, y=700, s=.7, text='6:30'),
   dict(kind='crate', x=1500, y=700, s=1.0)],
 people=[dict(x=560, y=700, h=88, skin=1, cloth=0, hair='grey', arm='hold'),
   dict(x=1000, y=700, h=86, skin=4, cloth=3, hair='short', arm='down'),
   dict(x=300, y=700, h=86, skin=3, cloth=2, hair='bun', arm='point'),
   dict(x=1120, y=700, h=86, skin=2, cloth=4, hair='cap', arm='folded'),
   dict(x=1340, y=700, h=86, skin=0, cloth=1, hair='long', arm='hold')],
 names=[dict(x=560, t='Ruth - twenty-three years, writing 23'),
   dict(x=1000, t='the applicant - two years, and he has stopped'),
   dict(x=300, t='Nadia - she wrote the twelve-item list'),
   dict(x=1120, t='somebody waiting for the 07.10 out'),
   dict(x=1340, t='Dev, two years on now, at the door'),
   dict(x=1420, t='the clock: half past six'),
   dict(x=160, t='the noticeboard - four notices, one of them new'),
   dict(x=700, t='the only cup on a nine-chair table')],
 markers=[dict(x=560, y=580), dict(x=1000, y=582), dict(x=300, y=582), dict(x=1120, y=582),
   dict(x=1340, y=582), dict(x=1420, y=636), dict(x=160, y=644), dict(x=700, y=610),
   dict(x=640, y=656), dict(x=600, y=664), dict(x=1220, y=652), dict(x=1500, y=660),
   dict(x=300, y=466), dict(x=1250, y=584)]),

"fig_a12_u08_p01_v08": dict(type='V8', height=800,
 title='One job, nine things it needs',
 sub='Each line says where that skill is learned. Only two of the nine are learned on this job.',
 alt='One job at the centre joined to nine things it actually requires, with each line labelled '
     'by where that skill is learned.',
 nodes={
  'job': dict(x=800, y=400, short='J', name='the job', sub='sleeping-car attendant', r=58,
              colour='#1C2B33'),
  's1':  dict(x=300, y=180, short='1', name='speak to a frightened person', sub='learned anywhere',
              colour='#C86B2B'),
  's2':  dict(x=220, y=440, short='2', name='nine hours standing', sub='learned here',
              colour='#2E6F5E'),
  's3':  dict(x=330, y=690, short='3', name='decide alone at 03.00', sub='learned anywhere',
              colour='#C86B2B'),
  's4':  dict(x=800, y=730, short='4', name='work in a second language', sub='learned elsewhere',
              colour='#8C6A9E'),
  's5':  dict(x=1280, y=690, short='5', name='run a kitchen alone', sub='learned elsewhere',
              colour='#8C6A9E'),
  's6':  dict(x=1380, y=430, short='6', name='the paperwork', sub='learned here',
              colour='#2E6F5E'),
  's7':  dict(x=1260, y=180, short='7', name='carry on in year nineteen', sub='learned nowhere',
              colour='#D9A441')},
 edges=[dict(a='s1', b='job', label='a hospital, a bar, a family', sw=5, colour='#C86B2B'),
   dict(a='s2', b='job', label='here, and it takes about four months', sw=6, colour='#2E6F5E'),
   dict(a='s3', b='job', label='anywhere nobody was watching', sw=5, colour='#C86B2B'),
   dict(a='s4', b='job', label='before you arrived', sw=5, colour='#8C6A9E'),
   dict(a='s5', b='job', label='eleven weeks when the chef left', sw=5, colour='#8C6A9E'),
   dict(a='s6', b='job', label='here, in about three weeks', sw=4, colour='#2E6F5E'),
   dict(a='s7', b='job', label='nobody teaches this and the form cannot see it', sw=3,
        dash='7 6', colour='#D9A441')]),

"fig_a12_u08_p01_v02a": dict(type='V2', height=780,
 title='One working life, in section',
 sub='Eleven skills. Eleven words. The first band is the thickest.',
 alt='A cutaway of one working life in four bands - the first year, years two to five, six to '
     'fifteen, sixteen onwards - with what is learned in each, and empty labels.',
 floors=[dict(was='year 1', now='almost everything · the job, the people, the hours',
     year='', fill='#F3EADA'),
   dict(was='years 2 to 5', now='the exceptions · the nights · what to do when it goes wrong',
     year='', fill='#E8EEF0'),
   dict(was='years 6 to 15', now='judgement · and almost nothing you could write down',
     year='', fill='#EFE6DC'),
   dict(was='years 16 onwards', now='very little new · and carrying on, which is not nothing',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The steepest learning anybody on this train will ever do'),
   dict(at=0.38, text='Four years, and this is where most people leave'),
   dict(at=0.62, text='Ten years of things that cannot go in a box on a form'),
   dict(at=0.88, text='Nineteen of the twenty-three years were the same year')]),

"fig_a12_u08_p02_v07": dict(type='V7', height=820,
 title='Opposite ends of the same table',
 sub='The same form in front of both of them. One box, and it measures time.',
 alt='Two applicants at opposite ends of a long crew-room table with the same form in front of '
     'each, with two speech balloons each and a thought balloon.',
 bg='#E5E2D8',
 set=[dict(kind='table', x=700, y=660, s=2.2), dict(kind='cup', x=780, y=614, s=1.4),
   dict(kind='chair', x=1420, y=660, s=1.1)],
 people=[dict(x=520, h=240, skin=1, cloth=0, hair='grey', arm='hold', facing='right',
   label='Ruth', role='twenty-three years on the line',
   says=["I've done this for twenty-three years.",
         "I haven't done the new test yet."],
   thinks=['Nineteen of them were the same year.']),
  dict(x=1080, h=238, skin=4, cloth=3, hair='short', arm='down', facing='left',
   label='the applicant', role='two years, and four languages',
   says=['Have you ever worked abroad?', "I've never been out of the country."],
   thinks=['Is two years a number or an answer?'])]),

"fig_a12_u08_p03_v09a": dict(type='V9', kind='timeline', height=720,
 title='A band with no dot in it',
 sub='The present perfect shades your whole life. The past simple puts a dot in it.',
 alt='A timeline with the whole of a life shaded as one band with no point marked, beside a '
     'second timeline with a single dot labelled last Tuesday.',
 now=0.90,
 bands=[dict(**{'from': 0.04, 'to': 0.90}, type='reach', lane=4,
     label='PRESENT PERFECT - somewhere in all of this',
     example='I have worked abroad. She has done this for 23 years.'),
   dict(**{'from': 0.52, 'to': 0.52}, type='event', lane=1,
     label='PAST SIMPLE - here, on this day',
     example='I worked there last year. She started in 2002.')]),

"fig_a12_u08_p03_v09b": dict(type='V9', kind='weight', height=540,
 title='Three kinds of participle, and one pair that matters',
 sub='Been and gone are the same journey and they end in different places.',
 alt='Three groups of past participles - identical to the past, different from it, and identical '
     'to the infinitive - with been and gone drawn separately.',
 parts=[dict(w=24, role='same as the past', text='worked · bought', colour='#1F4E5F'),
   dict(w=24, role='different', text='done · seen', colour='#C86B2B'),
   dict(w=20, role='same as the plain verb', text='come · run', colour='#2E6F5E'),
   dict(w=16, role='and back', text='BEEN', colour='#D9A441'),
   dict(w=16, role='and not back', text='GONE', colour='#A8372E')],
 note='She has been to Jasper - the journey is over and she is here. She has gone to Jasper - '
      'the journey is over and she is there. Same verb, same tense, opposite locations.'),

"fig_a12_u08_p03_v11": dict(type='V11', height=720,
 title='A date on a tense that refuses dates',
 alt='Two panels comparing I have worked there last year with I worked there last year, the '
     'first showing a date attached to a tense built to avoid dates.',
 wrong=dict(sentence='I have worked there last year.',
            boundary=0.36, boundary_label='have worked',
            event=0.70, event_label='last year - a date, and now the tense is wrong',
            why='The present perfect says: somewhere in my life, and I am not telling you when. '
                'Adding a date contradicts the tense you have just chosen. English hears this as '
                'two different sentences stuck together, and it is one of the few errors that '
                'makes a listener stop and reparse.'),
 right=dict(sentence='I worked there last year.',
            boundary=0.36, boundary_label='worked',
            event=0.66, event_label='last year - and the past simple was built for this',
            why='The moment a date appears, use the past simple. The rule is mechanical and it '
                'never fails: no date, present perfect; any date at all, past simple. This is '
                'also why a conversation always starts in one and moves into the other.'),
 misconception='The present perfect has have in it, which looks present, and a past participle, '
               'which looks past - so it feels like a tense that can do both. It cannot. What it '
               'does is leave the time out on purpose, and a date puts it back in.'),

"fig_a12_u08_p04_v04a": dict(type='V4', height=720,
 title='Two interviews for one job',
 sub='The left asks about years. The right asks what the person has done.',
 alt='Two written interviews for the same job side by side, one asking about length of service '
     'and one asking have you ever questions.',
 differences=6, prompt='Find the six. One of the two found out that the candidate had run a '
                       'kitchen alone for eleven weeks. Which, and what did it cost in minutes?',
 left=dict(label='how long?', art=[
   dict(kind='block', x=150, y=130, w=120, bh=22, colour='#9AA7AE'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='"Two years." — 4 minutes · one number',
        colour='#9AA7AE')]),
 right=dict(label='have you ever?', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=180, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='4 languages · 11 weeks alone · twice at 02.00 — 9 minutes',
        colour='#2E6F5E')])),

"fig_a12_u08_p05_v05": dict(type='V5', height=920,
 title='The application form',
 sub='Eleven boxes. Nine of them are about dates and documents.',
 alt='A job application form with eleven boxes, nine about dates and documents, one about years '
     'of experience, and a four-line OTHER box at the bottom of page two with a note saying it '
     'will not be scored.',
 rows=[dict(t='org', text='PRAIRIE LINE  -  INTERNAL APPLICATION  -  FORM HR/14'),
   dict(t='grid', cols=['BOX', 'ASKS FOR', 'SCORED'],
     data=[['1-3', 'NAME, NUMBER, DEPOT', 'NO'],
           ['4', 'DATE JOINED', 'YES'],
           ['5', 'YEARS OF EXPERIENCE', 'YES'],
           ['6', 'CURRENT GRADE', 'YES'],
           ['7', 'SAFETY CERTIFICATE DATE', 'YES'],
           ['8', 'FIRST AID CERTIFICATE', 'YES'],
           ['9', 'DAYS ABSENT, 24 MONTHS', 'YES'],
           ['10', 'LANGUAGES (TICK BOX)', 'YES'],
           ['11', 'OTHER - 4 LINES', 'NO']]),
   dict(t='rule'),
   dict(t='kv', k='Boxes about dates or documents', v='9 of 11', mono=True),
   dict(t='kv', k='Boxes about what you can do', v='1 of 11', mono=True),
   dict(t='kv', k='Size of the OTHER box', v='4 lines', mono=True),
   dict(t='rule'),
   dict(t='sign', text='UNDER THE OTHER BOX, IN 7 POINT:'),
   dict(t='para', text='"Information provided here will be read but does not form part of the '
     'score." The only box on the form that could hold eleven weeks of running a kitchen alone, '
     'and it has been declared worthless in advance.')],
 callouts=[dict(at=0.16, text='Box 5. One line, and it asks for a number of years'),
   dict(at=0.34, text='Days absent is scored. Nobody has explained what it measures'),
   dict(at=0.40, text='Languages is a tick box, so four languages and one look the same'),
   dict(at=0.62, text='Nine boxes a computer can read. One a person would have to'),
   dict(at=0.92, text='Read but not scored - which means read by nobody')]),

"fig_a12_u08_p06_v03a": dict(type='V3',
 title='Six participles, six small scenes',
 sub='The first two are the same journey. They end in different places.',
 alt='Six panels illustrating been, gone, done, seen, had and made, with been and gone drawn as '
     'the same journey ending in different places.',
 panels=[
  dict(caption='BEEN - the journey is over, she is here',
       art=[dict(kind='person', x=160, y=0, h=110, skin=1, cloth=0),
            dict(kind='tick', x=160, y=128)]),
  dict(caption='GONE - the journey is over, she is there',
       art=[dict(kind='gap', x=160, y=10, w=90, bh=70),
            dict(kind='arrow', x=160, y=120)]),
  dict(caption='DONE - finished, and it stays finished',
       art=[dict(kind='tick', x=160, y=50)]),
  dict(caption='SEEN - you were there when it happened',
       art=[dict(kind='person', x=160, y=0, h=110, skin=3, cloth=2, arm='point')]),
  dict(caption='HAD - it was yours, at some point',
       art=[dict(kind='box', x=160, y=0, w=90, bh=60)] if False else
           [dict(kind='block', x=160, y=0, w=90, bh=60, colour='#C9A97A')]),
  dict(caption='MADE - it did not exist and now it does',
       art=[dict(kind='block', x=160, y=0, w=110, bh=86, colour='#2E6F5E')])]),

"fig_a12_u08_p07_v10": dict(type='V10', kind='elision', height=720,
 title='The have that is almost not there',
 sub='Written in full above, said below. In two of these the word disappears completely.',
 alt='Five present perfect phrases written at full length and then as they are said, with have '
     'and has shaded almost away.',
 pairs=[
  dict(written='I have done it', spoken='Ivdunit', dropped='ha',
       note='have is one consonant'),
  dict(written='he has gone', spoken='heezgon', dropped='ha', note='has becomes a z'),
  dict(written='you have seen', spoken='yoovseen', dropped='ha', note='same as the first'),
  dict(written='have you ever', spoken='avyoo-evva', dropped='h', note='the h goes first'),
  dict(written='has she been', spoken='uzshee-bin', dropped='ha', note='two words, one sound')]),

"fig_a12_u08_p09_v02b": dict(type='V2', height=780,
 title='Your English as experience, not as a level',
 sub='Four layers. The bottom one predicts the other three.',
 alt='A cutaway of one learner\'s English as experience: conversations had, things read, times '
     'understood, and times not understood and carried on anyway.',
 floors=[dict(was='conversations you have had', now='about 400, and you remember six of them',
     year='', fill='#E8EEF0'),
   dict(was='things you have read', now='about 90,000 words, almost none of it on purpose',
     year='', fill='#F3EADA'),
   dict(was='times you were understood', now='most of them · and you noticed none',
     year='', fill='#EFE6DC'),
   dict(was='times you were not, and carried on', now='about 40 · and this is the layer that '
     'predicts everything above it', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Four hundred. No test has ever asked you this'),
   dict(at=0.38, text='Ninety thousand words, and you would say you never read in English'),
   dict(at=0.62, text='The successes are invisible because nothing happens'),
   dict(at=0.88, text='Forty failures you survived. That is the whole of the method')]),

"fig_a12_u08_p09_v03b": dict(type='V3',
 title='Five firsts, four with no date',
 sub='Every one of these is a present perfect sentence, and nobody wrote any of them down.',
 alt='Five panels showing the first time a learner understood a sentence, was understood, made a '
     'joke, argued, and stopped translating.',
 panels=[
  dict(caption='1 The first whole sentence you understood',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='2 The first time you were understood',
       art=[dict(kind='person', x=150, y=0, h=110, skin=4, cloth=3)]),
  dict(caption='3 The first time you made somebody laugh',
       art=[dict(kind='tick', x=150, y=50)]),
  dict(caption='4 The first time you argued',
       art=[dict(kind='person', x=150, y=0, h=110, skin=2, cloth=4, arm='point')]),
  dict(caption='5 The first time you stopped translating',
       art=[dict(kind='gap', x=150, y=20, w=110, bh=60)])]),

"fig_a12_u08_p10_v12": dict(type='V12',
 title='Twenty-three years and two',
 sub='The fourth band is almost empty, and it is the one that decides.',
 alt='An infographic comparing two applicants across four bands: years served, things done, '
     'things done alone, and what the application form can see.',
 span=['0', 'all'], ticks=4,
 tick_labels=['none', 'some', 'most', 'all'],
 bands=[dict(name='Years served', type='events', items=[
   dict(at=0.09, label='the applicant: 2', colour='#C86B2B'),
   dict(at=0.90, label='Ruth: 23', colour='#1F4E5F')]),
  dict(name='Things done, of 12', type='events', items=[
   dict(at=0.72, label='the applicant: 9', colour='#C86B2B'),
   dict(at=0.94, label='Ruth: 11', colour='#1F4E5F')]),
  dict(name='Done alone, of 12', type='events', items=[
   dict(at=0.48, label='Ruth: 7', colour='#1F4E5F'),
   dict(at=0.78, label='the applicant: 8 - two of them Ruth has not', colour='#C86B2B')]),
  dict(name='What the form sees', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.14}, label='one number each', colour='#9AA7AE')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='twenty-three years and two years differ by two items on a twelve-item list'),
   dict(at=0.46, label='the form can see none of it')])]),

"fig_a12_u08_p11_v04b": dict(type='V4', height=720,
 title='Two forms, side by side',
 sub='The years box on the left, the twelve-item checklist on the right.',
 alt='Two application forms drawn side by side, one showing only the years box with 23 and 2 and '
     'the rest blank, the other showing a twelve-item checklist with eleven and nine ticks.',
 differences=6, prompt='Find the six. One of them is how long each form took to fill in, and it '
                       'is the argument that will decide this.',
 left=dict(label='the years box', art=[
   dict(kind='block', x=150, y=130, w=90, bh=22, colour='#9AA7AE'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210, text='23 · 2 · everything else blank · 40 seconds',
        colour='#9AA7AE')]),
 right=dict(label='the twelve-item list', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=220, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='11 ticks · 9 ticks · 2 of them Ruth has never done · 4 minutes',
        colour='#2E6F5E')])),
}
