"""A1.2 Unit 9 - Forty Below - fifteen figures, as data."""
FIGURES = {
"fig_a12_u09_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='The prairie, ten past eight in January, minus thirty-eight',
 sub='Fourteen things to find. One of the four came out for forty seconds and it has been nine '
     'minutes.',
 alt='A prairie in January with a straight line of track, an enormous pale sky, one grain '
     'elevator and a stopped train with four people standing beside it.',
 sky='#C9D6DE', ground='#E4E7E6', ground_line=700,
 buildings=[dict(x=20, w=200, storeys=4, colour='#A79B84',
     label='the grain elevator'),
   dict(x=420, w=620, storeys=2, colour='#8E9AA0', cutaway=True,
     floor_labels=['the roof, under snow', 'the stopped train'],
     label='train 062, stopped at 07.51'),
   dict(x=1180, w=400, storeys=1, colour='#B9C4C7',
     label='the track, straight for eleven kilometres')],
 props=[dict(kind='sign', x=330, y=700, s=.7, text='8:10'),
   dict(kind='sign', x=1500, y=700, s=.7, text='-38'),
   dict(kind='box', x=1120, y=700, s=1.0),
   dict(kind='crate', x=1260, y=700, s=1.0),
   dict(kind='tree', x=380, y=700, s=.7),
   dict(kind='hoarding', x=1340, y=700, s=.7, w=140)],
 people=[dict(x=560, y=700, h=86, skin=3, cloth=2, hair='bun', arm='folded'),
   dict(x=680, y=700, h=86, skin=1, cloth=0, hair='grey', arm='hold'),
   dict(x=800, y=700, h=86, skin=4, cloth=3, hair='cap', arm='down'),
   dict(x=920, y=700, h=86, skin=2, cloth=4, hair='short', arm='folded'),
   dict(x=1060, y=700, h=86, skin=0, cloth=1, hair='long', arm='point')],
 names=[dict(x=560, t='Nadia - she has to decide what to tell them'),
   dict(x=680, t='Tom Wong - he is looking at the sky'),
   dict(x=800, t='the fitter, in a coat made for this'),
   dict(x=920, t='no coat - out for forty seconds, nine minutes ago'),
   dict(x=1060, t='a passenger who wanted to see the prairie'),
   dict(x=330, t='the clock: ten past eight'),
   dict(x=1500, t='the gauge: minus thirty-eight'),
   dict(x=1340, t='the sign nobody has read since October')],
 markers=[dict(x=560, y=582), dict(x=680, y=582), dict(x=800, y=582), dict(x=920, y=582),
   dict(x=1060, y=582), dict(x=330, y=636), dict(x=1500, y=636), dict(x=1340, y=644),
   dict(x=1120, y=652), dict(x=1260, y=660), dict(x=380, y=640), dict(x=120, y=584),
   dict(x=120, y=466), dict(x=1280, y=690)]),

"fig_a12_u09_p01_v08": dict(type='V8', height=800,
 title='Four seasons, and what each one does to a railway',
 sub='Each line has the days lost beside it. The season with the fewest is the one nobody plans '
     'for.',
 alt='The four seasons drawn as a ring with the effect of each on the railway written on the '
     'lines between them and the number of days lost beside each.',
 nodes={
  'lin': dict(x=800, y=400, short='062', name='the line', sub='4,400 km', r=58,
              colour='#1C2B33'),
  'win': dict(x=320, y=220, short='W', name='winter', sub='Nov to Mar', colour='#1F4E5F'),
  'spr': dict(x=280, y=580, short='S', name='spring', sub='Apr to May', colour='#2E6F5E'),
  'sum': dict(x=1240, y=220, short='J', name='summer', sub='Jun to Aug', colour='#D9A441'),
  'aut': dict(x=1300, y=580, short='A', name='autumn', sub='Sep to Oct', colour='#C86B2B'),
  'ice': dict(x=560, y=120, short='41', name='ice and frost heave', sub='41 days lost',
              colour='#1F4E5F'),
  'flo': dict(x=560, y=700, short='12', name='flooding', sub='12 days lost', colour='#2E6F5E'),
  'fir': dict(x=1040, y=120, short='6', name='fire near the line', sub='6 days lost',
              colour='#A8372E')},
 edges=[dict(a='win', b='ice', label='minus forty, and the rail shortens', sw=7,
        colour='#1F4E5F'),
   dict(a='ice', b='lin', label='41 of the 59 lost days', sw=7),
   dict(a='spr', b='flo', label='the thaw, and the culverts', sw=5, colour='#2E6F5E'),
   dict(a='flo', b='lin', label='12 days, and always the same four places', sw=5),
   dict(a='sum', b='fir', label='dry grass and a spark', sw=4, colour='#A8372E'),
   dict(a='aut', b='lin', label='no days lost at all - and no plan for it either', sw=2,
        dash='6 5', colour='#9AA7AE')]),

"fig_a12_u09_p01_v02a": dict(type='V2', height=780,
 title='One year, in section',
 sub='Eleven conditions. Eleven words. The January band is the thinnest and the most expensive.',
 alt='A cutaway of one year month by month showing what the weather does to the timetable in '
     'each band, with empty labels.',
 floors=[dict(was='November to March', now='ice · snow · forty below · 41 days lost',
     year='', fill='#E8EEF0'),
   dict(was='April and May', now='the thaw · wet · flooding · 12 days', year='',
     fill='#F3EADA'),
   dict(was='June to August', now='dry · sun · storm · fire · 6 days', year='',
     fill='#EFE6DC'),
   dict(was='September and October', now='cool · clear · nothing lost at all', year='',
     fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Five months. Seventy per cent of everything that goes wrong'),
   dict(at=0.38, text='Two months, and always the same four culverts'),
   dict(at=0.62, text='Six days, and they are the only ones that make the news'),
   dict(at=0.88, text='Two perfect months, and no timetable has ever used them')]),

"fig_a12_u09_p02_v07": dict(type='V7', height=820,
 title='On the platform, both looking up',
 sub='He is working out whether it will run. She is working out when to say so.',
 alt='A service manager and a station agent standing on a platform in deep cold, both looking at '
     'the sky, with two speech balloons each and a thought balloon.',
 bg='#DCE5EA',
 set=[dict(kind='crate', x=760, y=660, s=1.1), dict(kind='box', x=1340, y=660, s=1.0),
   dict(kind='sign', x=1440, y=660, s=.8, text='-38')],
 people=[dict(x=520, h=240, skin=1, cloth=0, hair='grey', arm='point', facing='right',
   label='Tom Wong', role='thirty-one winters here',
   says=["It's going to get colder. Minus forty-four tonight.",
         "We're leaving at six tomorrow, not tonight."],
   thinks=['Will it run at all, at minus forty-four?']),
  dict(x=1080, h=238, skin=3, cloth=2, hair='bun', arm='folded', facing='left',
   label='Nadia', role='a hundred and ninety-two people on board',
   says=["I'm going to check again at four.", "I'll tell them. Not yet."],
   thinks=['If I tell them now, they will all come out here.'])]),

"fig_a12_u09_p03_v09a": dict(type='V9', kind='timeline', height=780,
 title='Three futures, three starting points',
 sub='The arrow starts where the decision was made, not where the thing happens.',
 alt='A timeline with three arrows, each beginning at a different point: will at the moment of '
     'speaking, going to earlier at the decision or the evidence, and the present continuous '
     'earlier still at the arrangement.',
 now=0.56,
 bands=[dict(**{'from': 0.56, 'to': 0.90}, type='future', lane=1, label='WILL',
     example='I\'ll tell them. -- decided as the words leave your mouth'),
   dict(**{'from': 0.30, 'to': 0.90}, type='before', lane=3, label='BE GOING TO',
     example="I'm going to check at four. -- decided this morning, or the sky says so"),
   dict(**{'from': 0.08, 'to': 0.90}, type='before', lane=5, label='PRESENT CONTINUOUS',
     example="We're leaving at six. -- arranged, and other people were told")]),

"fig_a12_u09_p03_v09b": dict(type='V9', kind='branch', height=720,
 title='Four questions, four futures',
 sub='Most learners only ever use the fourth. Ask the first three before you reach it.',
 alt='A branching diagram with four questions - is there evidence, did you decide before now, is '
     'it arranged with others, are you deciding now - each leading to a different future form.',
 root='the future',
 branches=[dict(label='Is the evidence in front of you? — GOING TO', colour='#1F4E5F',
     example="Look at that sky. It's going to snow."),
   dict(label='Did you decide before now? — GOING TO', colour='#2E6F5E',
     example="I'm going to check again at four. -- decided this morning"),
   dict(label='Is it arranged with other people? — PRESENT CONTINUOUS',
     colour='#C86B2B',
     example="We're leaving at six tomorrow. -- it is on the board"),
   dict(label='Are you deciding as you speak? — WILL', colour='#D9A441',
     example="The phone is ringing - I'll get it.")]),

"fig_a12_u09_p03_v11": dict(type='V11', height=720,
 title='The decision arrow that started too late',
 alt='Two panels comparing I will check it at four, said about a decision made that morning, '
     'with I am going to check it at four.',
 wrong=dict(sentence="I'll check it again at four.",
            boundary=0.30, boundary_label='decided this morning',
            event=0.66, event_label="will - but will starts HERE, as you speak",
            why='Will says the decision is being made right now. If you decided eight hours ago, '
                'the listener hears a sudden idea where there was a plan. Nothing is '
                'ungrammatical - what has happened is that you have made yourself sound '
                'unprepared.'),
 right=dict(sentence="I'm going to check it again at four.",
            boundary=0.30, boundary_label='decided this morning',
            event=0.42, event_label='going to - the arrow starts where you decided',
            why='Going to reaches back to the moment of the decision, or to the evidence you can '
                'see. It is the ordinary future for anything you have thought about, which is '
                'most things, and it is the one learners use least.'),
 misconception='Will is taught first and taught as THE future, so it becomes the default. In '
               'real speech going to and the present continuous between them do most of the '
               'work, and will is reserved for offers, promises and things decided mid-sentence.'),

"fig_a12_u09_p04_v04a": dict(type='V4', height=720,
 title='The same Saturday, planned twice',
 sub='The left plan has a condition on every item. The right has none.',
 alt='Two plans for the same Saturday side by side, one with a condition attached to every item '
     'and one with none, with the point at which they diverge marked.',
 differences=6, prompt='Find the six. The two plans are identical until half past eleven on '
                       'Saturday morning. What happens then?',
 left=dict(label='with conditions', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='if it rains · if the road is closed · if he can\'t come — still a day',
        colour='#2E6F5E')]),
 right=dict(label='no conditions', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210,
        text='one plan · one road · one person — and it rained at 11.30',
        colour='#C86B2B')])),

"fig_a12_u09_p05_v05": dict(type='V5', height=920,
 title='The crew forecast sheet',
 sub='Everything on it is a number except the last line.',
 alt='The winter forecast sheet the crew receive each morning, showing temperature and wind at '
     'four points, expected delay in minutes, a confidence figure, and a line saying not for '
     'passenger distribution.',
 rows=[dict(t='org', text='PRAIRIE LINE  -  WINTER OPS  -  06.00 FORECAST'),
   dict(t='grid', cols=['POINT', 'TEMP / WIND', 'DELAY'],
     data=[['WINNIPEG', '-31 / 40 km/h', '160 min'],
           ['MIRROR LAKE', '-38 / 22 km/h', '45 min'],
           ['SASKATOON', '-34 / 51 km/h', '90 min'],
           ['JASPER', '-19 / 8 km/h', '0 min']]),
   dict(t='rule'),
   dict(t='head', text='TONIGHT'),
   dict(t='kv', k='Forecast low', v='-44', mono=True),
   dict(t='kv', k='Confidence', v='81%', mono=True),
   dict(t='kv', k='Rail temperature limit', v='-42', mono=True),
   dict(t='kv', k='Decision point', v='16.00', mono=True),
   dict(t='rule'),
   dict(t='head', text='AGAINST THE PRINTED TIMETABLE'),
   dict(t='kv', k='Total expected delay', v='295 min', mono=True),
   dict(t='kv', k='Allowed in the timetable', v='0 min', mono=True),
   dict(t='rule'),
   dict(t='sign', text='AND AT THE FOOT OF THE PAGE:'),
   dict(t='para', text='"Not for passenger distribution." The sheet is accurate, it is produced '
     'every morning at six, and the people whose day it describes are the only people who are '
     'not allowed to see it.')],
 callouts=[dict(at=0.12, text='A hundred and sixty minutes, before the train has moved'),
   dict(at=0.26, text='Jasper: nothing. The mountains are warmer than the prairie'),
   dict(at=0.48, text='Minus forty-four against a rail limit of minus forty-two'),
   dict(at=0.76, text='Two hundred and ninety-five minutes against nought'),
   dict(at=0.94, text='Accurate, daily, and confidential')]),

"fig_a12_u09_p06_v03a": dict(type='V3',
 title='One plan, six weathers',
 sub='In the first four the plan survives. In the fifth it moves. In the sixth it stops being a '
     'plan.',
 alt='Six panels showing one plan under six weather conditions, from clear to forty below, with '
     'the plan surviving, moving and ending.',
 panels=[
  dict(caption='clear - nothing changes',
       art=[dict(kind='block', x=160, y=0, w=120, bh=110, colour='#2E6F5E')]),
  dict(caption='a bit of rain - nothing changes',
       art=[dict(kind='block', x=160, y=0, w=120, bh=104, colour='#2E6F5E')]),
  dict(caption='heavy rain - you take a coat',
       art=[dict(kind='block', x=160, y=0, w=120, bh=90, colour='#1F4E5F')]),
  dict(caption='wind - you change where, not whether',
       art=[dict(kind='block', x=160, y=0, w=120, bh=70, colour='#D9A441')]),
  dict(caption='snow - you put it off to Tuesday',
       art=[dict(kind='arrow', x=160, y=50)]),
  dict(caption='forty below - it is not a plan',
       art=[dict(kind='gap', x=160, y=10, w=120, bh=60)])]),

"fig_a12_u09_p07_v10": dict(type='V10', kind='elision', height=720,
 title='Three syllables in one',
 sub='Before a verb, going to always shrinks. Before a place name it never does.',
 alt='Five future phrases written at full length and then as they are said, with the letters that '
     'disappear shaded out.',
 pairs=[
  dict(written='going to', spoken='gonna', dropped='ito', note='only before a verb'),
  dict(written='I am going to', spoken='umunuh', dropped='amgito', note='four words, two beats'),
  dict(written='are you going to', spoken='ayugunna', dropped='reito', note='same again'),
  dict(written='want to', spoken='wanna', dropped='to', note='the same shrinking'),
  dict(written='going to Winnipeg', spoken='going to Winnipeg', dropped='',
       note='before a place it keeps every syllable')]),

"fig_a12_u09_p09_v02b": dict(type='V2', height=780,
 title='One study month, in section',
 sub='The bottom layer is the only one still standing on the thirtieth.',
 alt='A cutaway of one study month showing the plan made on the first, the first week, the week '
     'when something went wrong, and the plan that had a bad week built into it.',
 floors=[dict(was='the 1st', now='thirty days · forty minutes · no exceptions', year='',
     fill='#E8EEF0'),
   dict(was='week 1', now='seven days out of seven · it is working', year='',
     fill='#F3EADA'),
   dict(was='week 3', now='a cold, a deadline, a visitor · and nothing at all', year='',
     fill='#EFE6DC'),
   dict(was='the bad-week version', now='eight minutes a day · written in advance · '
     'still running', year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='Made on a good day, for a person who will not have one every day'),
   dict(at=0.38, text='Seven for seven. This is where people decide the plan works'),
   dict(at=0.62, text='The week nobody planned, and it arrives about once a month'),
   dict(at=0.88, text='A fifth of the size, and it is the only part that survives')]),

"fig_a12_u09_p09_v03b": dict(type='V3',
 title='The first of next month',
 sub='Five panels. The fifth is identical to the first, and that is the problem.',
 alt='Five panels showing a study plan, a good week, a bad week, the decision to restart on the '
     'first of next month, and the first of next month.',
 panels=[
  dict(caption='1 The plan, on the 1st',
       art=[dict(kind='doc', x=150, y=0)]),
  dict(caption='2 Week 1 - seven out of seven',
       art=[dict(kind='tick', x=150, y=50)]),
  dict(caption='3 Week 3 - nothing',
       art=[dict(kind='gap', x=150, y=20, w=110, bh=60)]),
  dict(caption='4 "I\'ll start again on the 1st"',
       art=[dict(kind='person', x=150, y=0, h=110, skin=2, cloth=4)]),
  dict(caption='5 The 1st. The same plan',
       art=[dict(kind='doc', x=150, y=0), dict(kind='arrow', x=150, y=130)])]),

"fig_a12_u09_p10_v12": dict(type='V12',
 title='One year on the line',
 sub='Three of these bands move with the year. The fourth is a straight line across all of it.',
 alt='An infographic of one year showing temperature, days lost, cost, and what the printed '
     'timetable says, with the last band unchanging.',
 span=['January', 'December'], ticks=5,
 tick_labels=['Jan', 'Apr', 'Jul', 'Oct', 'Dec'],
 bands=[dict(name='Temperature', type='line',
   points=[(0, -31), (0.25, 4), (0.5, 24), (0.75, 6), (1.0, -27)], end_label='-27'),
  dict(name='Days lost', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.20}, label='Jan-Mar: 33', colour='#1F4E5F'),
   dict(**{'from': 0.22, 'to': 0.42}, label='Apr-May: 12', colour='#2E6F5E'),
   dict(**{'from': 0.44, 'to': 0.70}, label='Jun-Aug: 6', colour='#D9A441'),
   dict(**{'from': 0.72, 'to': 0.84}, label='Sep-Oct: 0', colour='#9AA7AE'),
   dict(**{'from': 0.86, 'to': 1.0}, label='Nov-Dec: 8', colour='#1F4E5F')]),
  dict(name='Cost of delay', type='events', items=[
   dict(at=0.08, label='$1.9 m', colour='#A8372E'),
   dict(at=0.32, label='$0.6 m', colour='#C86B2B'),
   dict(at=0.58, label='$0.3 m', colour='#D9A441'),
   dict(at=0.90, label='$0.5 m', colour='#C86B2B')]),
  dict(name='The printed timetable', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='identical in all twelve months · 0 minutes allowed',
        colour='#9AA7AE')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.06, label='the two months with no days lost are in no plan either'),
   dict(at=0.46, label='one document in this figure does not know what month it is')])]),

"fig_a12_u09_p11_v04b": dict(type='V4', height=720,
 title='The arrivals board at Vancouver, a January morning',
 sub='The same train, the same arrival. Two different printed times.',
 alt='Two drawings of the arrivals board at Vancouver on a January morning, one showing the '
     'summer time with eleven people at the information desk and one showing the winter time '
     'with nobody.',
 differences=6, prompt='Find the six. One of them is how many people are at the information '
                       'desk, and it is the only one that costs a wage.',
 left=dict(label='the printed time', art=[
   dict(kind='block', x=150, y=130, w=140, bh=22, colour='#A8372E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#A8372E'),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210,
        text='09.40 printed · 12.20 actual · 11 at the desk · 2 complaints',
        colour='#A8372E')]),
 right=dict(label='the winter time', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=160, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='12.30 printed · 12.20 actual · 0 at the desk · 0 complaints',
        colour='#2E6F5E')])),
}
