"""A1.2 Unit 10 - Four Thousand One Hundred Cards - fifteen figures, as data."""
FIGURES = {
"fig_a12_u10_p00_v01": dict(type='V1', height=980, storey_h=116,
 title='A storeroom at Toronto Union',
 sub='Fourteen things to find. Eight boxes have a year on them. The ninth has nothing, and it is '
     'the fullest.',
 alt='A railway storeroom with shelves and nine grey boxes, one open with comment cards spilling '
     'out, and two people standing in front of it with a platform visible through the window.',
 sky='#B8C0C4', ground='#8C867B', ground_line=700,
 buildings=[dict(x=20, w=520, storeys=3, colour='#A7A396', cutaway=True,
     floor_labels=['shelf 3 - 2014 to 2016', 'shelf 2 - 2017 to 2020', 'shelf 1 - 2021 to now'],
     label='nine boxes, eleven years'),
   dict(x=620, w=440, storeys=2, colour='#B5B2A4', cutaway=True,
     floor_labels=['the open box', 'the table, and one card on it'],
     label='where they are standing'),
   dict(x=1140, w=440, storeys=3, colour='#9FAAAE', cutaway=True,
     floor_labels=['the window', 'the platform beyond it', 'the door'],
     label='the window on to platform 11')],
 props=[dict(kind='box', x=120, y=700, s=1.1), dict(kind='box', x=220, y=700, s=1.1),
   dict(kind='box', x=320, y=700, s=1.1), dict(kind='crate', x=680, y=700, s=1.1),
   dict(kind='table', x=800, y=700, s=1.2), dict(kind='chair', x=760, y=700, s=1.0),
   dict(kind='sign', x=1480, y=700, s=.7, text='11'),
   dict(kind='cup', x=860, y=654, s=1.4)],
 people=[dict(x=920, y=700, h=88, skin=3, cloth=2, hair='bun', arm='hold'),
   dict(x=1020, y=700, h=86, skin=2, cloth=4, hair='short', arm='down'),
   dict(x=440, y=700, h=86, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=1260, y=700, h=86, skin=4, cloth=3, hair='cap', arm='folded'),
   dict(x=1400, y=700, h=86, skin=0, cloth=1, hair='long', arm='hold')],
 names=[dict(x=920, t='Nadia - holding a card from 2016'),
   dict(x=1020, t='the marketing manager - a report due Friday'),
   dict(x=440, t='the ninth box, with no year on it'),
   dict(x=1260, t='somebody passing on platform 11'),
   dict(x=1400, t='and somebody waiting for the 14.05'),
   dict(x=1480, t='platform 11, through the window'),
   dict(x=680, t='the open box - cards spilling out of it'),
   dict(x=860, t='the only cup in a room of paper')],
 markers=[dict(x=920, y=580), dict(x=1020, y=582), dict(x=440, y=582), dict(x=1260, y=582),
   dict(x=1400, y=582), dict(x=1480, y=636), dict(x=680, y=656), dict(x=860, y=610),
   dict(x=120, y=652), dict(x=220, y=652), dict(x=320, y=652), dict(x=800, y=656),
   dict(x=200, y=584), dict(x=200, y=466)]),

"fig_a12_u10_p01_v08": dict(type='V8', height=800,
 title='Four thousand one hundred cards, seven kinds',
 sub='The biggest group is not the one the company expected. The smallest is the one it reads.',
 alt='The comment cards sorted into seven kinds, each joined to the number of cards in it, with '
     'the largest group being stories and the smallest being complaints.',
 nodes={
  'box': dict(x=800, y=400, short='4100', name='the cards', sub='eleven years', r=60,
              colour='#1C2B33'),
  'sto': dict(x=320, y=200, short='1100', name='a story', sub='the largest group', r=54,
              colour='#2E6F5E'),
  'tha': dict(x=250, y=520, short='940', name='a thank you', sub='', colour='#D9A441'),
  'nam': dict(x=420, y=700, short='400', name='a name', sub='somebody else\'s',
              colour='#8C6A9E'),
  'jok': dict(x=900, y=720, short='310', name='a joke', sub='', colour='#C86B2B'),
  'dra': dict(x=1300, y=620, short='150', name='a drawing', sub='', colour='#9AA7AE'),
  'com': dict(x=1340, y=220, short='210', name='a complaint', sub='all 210 answered',
              colour='#A8372E'),
  'not': dict(x=900, y=120, short='990', name='nothing at all', sub='blank, and returned',
              colour='#9AA7AE')},
 edges=[dict(a='sto', b='box', label='1,100 · and nobody has read one', sw=7,
        colour='#2E6F5E'),
   dict(a='tha', b='box', label='940', sw=6, colour='#D9A441'),
   dict(a='not', b='box', label='990 blank · somebody took the card and put it back', sw=6,
        colour='#9AA7AE'),
   dict(a='nam', b='sto', label='400 of the stories name a passenger', sw=4, colour='#8C6A9E'),
   dict(a='jok', b='box', label='310', sw=4, colour='#C86B2B'),
   dict(a='dra', b='box', label='150', sw=3, colour='#9AA7AE'),
   dict(a='com', b='box', label='210 · the only group with a process behind it', sw=4,
        colour='#A8372E')]),

"fig_a12_u10_p01_v02a": dict(type='V2', height=780,
 title='One story, in four layers',
 sub='Eleven features. Eleven words. The bottom layer is the shortest and the only one anybody '
     'remembers.',
 alt='A cutaway of one story in four layers: what happened, the first telling, the tenth telling, '
     'and what is left after ten years, with empty labels.',
 floors=[dict(was='what happened', now='six hours · a man in seat 14 · a book not read',
     year='', fill='#F3EADA'),
   dict(was='the first telling', now='four minutes · every detail · no ending yet',
     year='', fill='#E8EEF0'),
   dict(was='the tenth telling', now='ninety seconds · one number · and now it has an ending',
     year='', fill='#EFE6DC'),
   dict(was='ten years later', now='two sentences · a person · a number · that is all',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The only layer that is entirely true'),
   dict(at=0.38, text='Longest, and nobody retold it from this version'),
   dict(at=0.62, text='The ending was not there at the time. It was built in the retellings'),
   dict(at=0.88, text='A person and a number. Everything else has gone')]),

"fig_a12_u10_p02_v07": dict(type='V7', height=820,
 title='In front of the open box',
 sub='He has eleven minutes. She has been reading the same card for four of them.',
 alt='A service manager and a marketing manager standing in a storeroom with an open box of '
     'comment cards between them, each holding a card, with two speech balloons each and a '
     'thought balloon.',
 bg='#E4E2D9',
 set=[dict(kind='crate', x=760, y=660, s=1.2), dict(kind='table', x=1320, y=660, s=1.2),
   dict(kind='box', x=1440, y=660, s=1.0)],
 people=[dict(x=520, h=240, skin=3, cloth=2, hair='bun', arm='hold', facing='right',
   label='Nadia', role='she has read about forty of them',
   says=["It's the strangest thing in the box.", "That's the best part."],
   thinks=['Nine times I have told this one.']),
  dict(x=1080, h=238, skin=2, cloth=4, hair='short', arm='point', facing='left',
   label='the marketing manager', role='a report due on Friday',
   says=["There isn't enough time.", "It's too long to read - four thousand cards."],
   thinks=['What do I put in the report?'])]),

"fig_a12_u10_p03_v09a": dict(type='V9', kind='ladder', height=800,
 title='The same ruler, one mark further along',
 sub='Short adjectives take -est. Long ones take the most. And every superlative takes the.',
 alt='A vertical ladder of adjectives by syllable count showing -est for short adjectives and the '
     'most for long ones, with the always in front.',
 top_label='short', bottom_label='long',
 steps=[dict(form='long → the longest', meaning='1 syllable · the + -est'),
   dict(form='hard → the hardest', meaning='1 syllable · the + -est'),
   dict(form='easy → the easiest', meaning='2 syllables in y · the + -iest'),
   dict(form='amazing → the most amazing', meaning='3 syllables · the most'),
   dict(form='interesting → the most interesting', meaning='4 syllables · the most'),
   dict(form='good → the best', meaning='no rule · learn it'),
   dict(form='bad → the worst', meaning='no rule · learn it')]),

"fig_a12_u10_p03_v09b": dict(type='V9', kind='weight', height=540,
 title='Too much, enough, and not enough',
 sub='Enough goes after an adjective and before a noun. Nothing else in English does this.',
 alt='A line with a comfortable band in the middle, not enough below it, enough inside it and too '
     'above it, with the word order marked for each.',
 parts=[dict(w=22, role='less than you need', text='not enough', colour='#A8372E'),
   dict(w=18, role='right', text='enough', colour='#2E6F5E'),
   dict(w=18, role='more than you want', text='too', colour='#C86B2B'),
   dict(w=24, role='BEFORE a noun', text='enough time', colour='#1F4E5F'),
   dict(w=24, role='AFTER an adjective', text='long enough', colour='#1F4E5F')],
 note='Too long is a complaint. Very long is a description. Not enough time is less than you '
      'need. The word enough changes sides depending on what it is next to, and reversing it - '
      'enough long - is the commonest error in this unit.'),

"fig_a12_u10_p03_v11": dict(type='V11', height=720,
 title='The end of the scale, marked twice',
 alt='Two panels comparing the most strangest with the strangest, the first showing the '
     'superlative marked both by the most and by the -est ending.',
 wrong=dict(sentence='It\'s the most strangest thing.',
            boundary=0.34, boundary_label='the most',
            event=0.64, event_label='strangest - and it is already superlative',
            why='You met this exact error in Unit 3 as more cheaper. Strange is one syllable '
                'plus one, so it takes -est, and once it has taken it the word is already at the '
                'end of the scale. The most says the same thing again, and a scale has only one '
                'end.'),
 right=dict(sentence='It\'s the strangest thing.',
            boundary=0.34, boundary_label='the',
            event=0.58, event_label='strangest - one marker, and the is still required',
            why='One superlative marker, chosen by the length of the adjective, and the in front '
                'of it every time. The is not optional: there is only one strangest thing in the '
                'box, and the says so.'),
 misconception='The most feels like an intensifier, the way more did. It is not. It is the '
               'superlative itself. The test is the same as in Unit 3: if the adjective has '
               'changed shape, do not put a word in front of it.'),

"fig_a12_u10_p04_v04a": dict(type='V4', height=720,
 title='The same story, two cards',
 sub='The left card has a number, a place and an ending. The right has three adjectives.',
 alt='Two comment cards side by side with the same story, one giving a number, a place and an '
     'ending and the other giving only adjectives.',
 differences=6, prompt='Find the six. One of the two was retold by somebody who was not there. '
                       'Which, and what is in it that made that possible?',
 left=dict(label='a number and an ending', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='block', x=150, y=66, w=200, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='seat 14 · six hours · 31 years · I didn\'t read my book',
        colour='#2E6F5E')]),
 right=dict(label='three adjectives', art=[
   dict(kind='block', x=150, y=130, w=160, bh=22, colour='#C86B2B'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='gap', x=150, y=66, w=240, bh=22),
   dict(kind='label', x=300, y=210,
        text='amazing · beautiful · wonderful — and 900 others like it',
        colour='#C86B2B')])),

"fig_a12_u10_p05_v05": dict(type='V5', height=880,
 title='One card, at full size',
 sub='Four ruled lines were provided. The writing went up the side and over the address.',
 alt='A single comment card reproduced at full size with the printed question, four ruled lines, '
     'a seat number box, and handwriting that fills the lines and continues up the side and over '
     'the address on the back.',
 rows=[dict(t='org', text='PRAIRIE LINE  -  COMMENT CARD'),
   dict(t='sign', text='THE BEST THING ABOUT YOUR JOURNEY?'),
   dict(t='rule'),
   dict(t='kv', k='Lines provided', v='4', mono=True),
   dict(t='kv', k='Lines used', v='4', mono=True),
   dict(t='kv', k='Then continued', v='up the right margin', mono=False),
   dict(t='kv', k='And then', v='across the back, over the address', mono=False),
   dict(t='kv', k='Seat number box', v='14', mono=True),
   dict(t='kv', k='Date', v='2016', mono=True),
   dict(t='kv', k='Signed', v='first name only', mono=False),
   dict(t='rule'),
   dict(t='head', text='WHAT IT IS ABOUT'),
   dict(t='para', text='A man the writer sat next to for two hours. He is described by his '
     'coat, by what he said about a bridge, and by the fact that he got off before the writer '
     'had finished asking him something.'),
   dict(t='rule'),
   dict(t='para', text='The company\'s address is printed on the back. The writing goes over '
     'it, which means the card could not have been posted. It was left on the table.')],
 callouts=[dict(at=0.12, text='The question asks for the best thing about the journey'),
   dict(at=0.26, text='Four lines. Somebody decided four lines was the right number'),
   dict(at=0.38, text='And then two more surfaces'),
   dict(at=0.62, text='A first name. They were not asking for anything'),
   dict(at=0.92, text='Written over the address, so it was never going to be sent')]),

"fig_a12_u10_p06_v03a": dict(type='V3',
 title='One story, six lengths',
 sub='At two minutes other people retell it. At half an hour nobody does.',
 alt='Six panels showing the same story told at six different lengths, from thirty seconds to '
     'half an hour, with the point at which it stops being retold.',
 panels=[
  dict(caption='30 seconds - not enough',
       art=[dict(kind='block', x=160, y=0, w=110, bh=24, colour='#A8372E')]),
  dict(caption='90 seconds - and it travels',
       art=[dict(kind='block', x=160, y=0, w=110, bh=60, colour='#2E6F5E')]),
  dict(caption='2 minutes - the best length',
       art=[dict(kind='block', x=160, y=0, w=110, bh=78, colour='#2E6F5E'),
            dict(kind='tick', x=160, y=128)]),
  dict(caption='10 minutes - still good, not retold',
       art=[dict(kind='block', x=160, y=0, w=110, bh=100, colour='#D9A441')]),
  dict(caption='half an hour - too long',
       art=[dict(kind='block', x=160, y=0, w=110, bh=120, colour='#C86B2B')]),
  dict(caption='and twice more - nobody is listening',
       art=[dict(kind='gap', x=160, y=10, w=110, bh=60)])]),

"fig_a12_u10_p07_v10": dict(type='V10', kind='stress', height=800,
 title='Which word you push',
 sub='The same four words, five times. Each push answers a different question.',
 alt='One sentence drawn five times as circles with a different circle enlarged each time, and '
     'the question each version answers beside it.',
 items=[
  dict(syllables=["THAT'S", 'the', 'best', 'part'], strong=[0],
       note='not the other bit - this bit'),
  dict(syllables=["that's", 'THE', 'best', 'part'], strong=[1],
       note='the one and only best part'),
  dict(syllables=["that's", 'the', 'BEST', 'part'], strong=[2],
       note='not just good. Best'),
  dict(syllables=["that's", 'the', 'best', 'PART'], strong=[3],
       note='and there is more of it coming'),
  dict(syllables=["it's", 'a', 'TRUE', 'sto-ry'], strong=[2],
       note='you are defending it against doubt'),
  dict(syllables=["it's", 'a', 'true', 'STO-ry'], strong=[3],
       note='a story, not a report')]),

"fig_a12_u10_p09_v02b": dict(type='V2', height=780,
 title='Two books, in section',
 sub='The bottom layer is the thinnest and it is what the two books were for.',
 alt='A cutaway of two coursebooks showing the twenty units, the seven hundred words, the '
     'seventy decisions and the four or five moments the learner will still describe in ten '
     'years.',
 floors=[dict(was='the units', now='20 of them · about 280 hours · and you did them',
     year='', fill='#E8EEF0'),
   dict(was='the words', now='700 taught · about 400 yours · and you cannot name them',
     year='', fill='#F3EADA'),
   dict(was='the decisions', now='20 of them · and you have an opinion about every one',
     year='', fill='#EFE6DC'),
   dict(was='what you will keep', now='four or five scenes · and all of them have a person in them',
     year='', fill='#F1EDE2')],
 callouts=[dict(at=0.12, text='The part that can be counted, and it is the least interesting'),
   dict(at=0.38, text='Four hundred words you now own and could not list'),
   dict(at=0.62, text='The lift, the stall, the dining car, the red handles'),
   dict(at=0.88, text='Thin, and it is what you actually bought')]),

"fig_a12_u10_p09_v03b": dict(type='V3',
 title='Five recordings, one year',
 sub='The fifth panel is the only one with a face in it.',
 alt='Five panels showing the four thirty-second recordings made across the two books and the '
     'moment of listening to all of them in order.',
 panels=[
  dict(caption='A1.1 Unit 1 - thirty seconds',
       art=[dict(kind='block', x=150, y=0, w=110, bh=20, colour='#9AA7AE')]),
  dict(caption='A1.1 Unit 9',
       art=[dict(kind='block', x=150, y=0, w=110, bh=46, colour='#D9A441')]),
  dict(caption='A1.2 Unit 6',
       art=[dict(kind='block', x=150, y=0, w=110, bh=80, colour='#C86B2B')]),
  dict(caption='Today',
       art=[dict(kind='block', x=150, y=0, w=110, bh=110, colour='#2E6F5E')]),
  dict(caption='All four, in order',
       art=[dict(kind='person', x=150, y=0, h=112, skin=2, cloth=4, arm='hold')])]),

"fig_a12_u10_p10_v12": dict(type='V12',
 title='Four thousand one hundred cards',
 sub='The last band is almost entirely empty, and that is the finding.',
 alt='An infographic of the comment cards showing what the company expected, what is there, what '
     'the cards are about, and what was done with each kind.',
 span=['0', '4,100'], ticks=4,
 tick_labels=['0', '1,400', '2,700', '4,100'],
 bands=[dict(name='What was expected', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.74}, label='complaints and praise - about 3,000',
        colour='#9AA7AE')]),
  dict(name='What is there', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.27}, label='stories - 1,100', colour='#2E6F5E'),
   dict(**{'from': 0.28, 'to': 0.51}, label='thank yous - 940', colour='#D9A441'),
   dict(**{'from': 0.52, 'to': 0.76}, label='blank - 990', colour='#9AA7AE'),
   dict(**{'from': 0.77, 'to': 0.88}, label='jokes - 310', colour='#C86B2B'),
   dict(**{'from': 0.89, 'to': 0.94}, label='complaints - 210', colour='#A8372E'),
   dict(**{'from': 0.95, 'to': 1.0}, label='drawings', colour='#8C6A9E')]),
  dict(name='About another passenger', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.22}, label='by description - 900', colour='#1F4E5F'),
   dict(**{'from': 0.23, 'to': 0.32}, label='by name - 400', colour='#8C6A9E')]),
  dict(name='What was done', type='bars', items=[
   dict(**{'from': 0.89, 'to': 0.94}, label='the 210 complaints were answered',
        colour='#A8372E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.06, label='the company planned for the fifth largest group'),
   dict(at=0.44, label='990 people took a card, read it, and put it back blank')])]),

"fig_a12_u10_p11_v04b": dict(type='V4', height=720,
 title='The storeroom shelf, twice',
 sub='As it is, and after the stories have been typed up.',
 alt='Two drawings of the same storeroom shelf, one with nine closed boxes and one with three '
     'boxes, a half-empty shelf and a screen on a dining car wall.',
 differences=6, prompt='Find the six. One of them is who is standing in front of it, and that is '
                       'the one nobody forecast.',
 left=dict(label='as it is', art=[
   dict(kind='block', x=150, y=130, w=240, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=150, y=98, w=240, bh=22, colour='#9AA7AE'),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#9AA7AE'),
   dict(kind='label', x=300, y=210,
        text='9 boxes · closed · 0 read · 370 new cards a year',
        colour='#9AA7AE')]),
 right=dict(label='after', art=[
   dict(kind='block', x=150, y=130, w=140, bh=22, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=98, w=240, bh=22),
   dict(kind='block', x=150, y=66, w=240, bh=22, colour='#2E6F5E'),
   dict(kind='label', x=300, y=210,
        text='3 boxes · 1,100 typed · 1 screen · 900 new cards a year',
        colour='#2E6F5E')])),
}
