# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C5-1': ('case item C5-1', []),
    'C5-2': ('case item C5-2', []),
    'C5-3': ('case item C5-3', []),
    'C5-4': ('case item C5-4', []),
    'C5-5': ('case item C5-5', []),
    'C5-6': ('case item C5-6', []),
    'P5-01': ('practice item P5-01', []),
    'P5-02': ('practice item P5-02', []),
    'P5-03': ('practice item P5-03', []),
    'P5-04': ('practice item P5-04', []),
    'P5-05': ('practice item P5-05', []),
    'P5-06': ('practice item P5-06', []),
    'P5-07': ('practice item P5-07', []),
    'P5-08': ('practice item P5-08', []),
    'P5-09': ('practice item P5-09', []),
    'P5-10': ('practice item P5-10', []),
    'P5-11': ('practice item P5-11', []),
    'P5-12': ('practice item P5-12', []),
    'P5-13': ('practice item P5-13', []),
    'P5-14': ('practice item P5-14', []),
    'P5-15': ('practice item P5-15', []),
    'P5-16': ('practice item P5-16', []),
    'P5-17': ('practice item P5-17', []),
    'P5-18': ('practice item P5-18', []),
    'P5-19': ('practice item P5-19', []),
    'P5-20': ('practice item P5-20', []),
    'P5-21': ('practice item P5-21', []),
    'P5-22': ('practice item P5-22', []),
    'P5-23': ('practice item P5-23', []),
    'P5-24': ('practice item P5-24', []),
    'SC5-1': ('section-check item SC5-1', []),
    'SC5-2': ('section-check item SC5-2', []),
    'SC5-3': ('section-check item SC5-3', []),
    'SC5-4': ('section-check item SC5-4', []),
    'SC5-5': ('section-check item SC5-5', []),
    'SC5-6': ('section-check item SC5-6', []),
    'SC5-7': ('section-check item SC5-7', []),
    'SC5-8': ('section-check item SC5-8', []),
    'SC5-9': ('section-check item SC5-9', []),
    'term:cash equivalents': ("term-bridge row 'cash equivalents'", []),
    'term:direct method': ("term-bridge row 'direct method'", []),
    'term:financing activities': ("term-bridge row 'financing activities'", []),
    'term:indirect method': ("term-bridge row 'indirect method'", []),
    'term:investing activities': ("term-bridge row 'investing activities'", []),
    'term:noncash investing and financing activities': ("term-bridge row 'noncash investing and financing activities'", []),
    'term:operating activities': ("term-bridge row 'operating activities'", []),
    'term:statement of cash flows': ("term-bridge row 'statement of cash flows'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C5-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'C5-6': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P5-10': 'it sends the reader to F05-02, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'P5-23': 'it sends the reader to F05-08, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
