"""B2.2 Unit 1 - Less Than Ideal - ten figures, as data."""
FIGURES = {
"fig_b22_u01_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The terminal office, ten past seven',
 sub='Twelve things to find. Two of them say the same thing and one says it out loud.',
 alt='A port terminal office at dawn with a draft review on a screen, a printed copy with the '
     'hedges underlined, an on-time chart and a window onto the quay with a tug at the berth.',
 sky='#CFD6D8', ground='#7F8A8E', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#A8B0B2', cutaway=True,
     floor_labels=['the draft review, on screen', 'the printed version, hedges underlined',
                   'the scale'],
     label='the review desk'),
   dict(x=560, w=480, storeys=3, colour='#B2B9BA', cutaway=True,
     floor_labels=['the on-time chart, 96 to 88', 'the near-miss log, three entries',
                   'the contract'],
     label='the evidence'),
   dict(x=1120, w=460, storeys=3, colour='#A6AEB0', cutaway=True,
     floor_labels=['the customer\'s email, unopened', 'the window onto the quay',
                   'the tug'],
     label='the quayside')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='07:10'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=115, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=200, y=700, h=92, skin=2, cloth=0, hair='bun', arm='point'),
   dict(x=300, y=700, h=88, skin=4, cloth=2, hair='short', arm='hold'),
   dict(x=660, y=700, h=86, skin=1, cloth=3, hair='grey', arm='folded'),
   dict(x=1250, y=700, h=86, skin=5, cloth=4, hair='cap', arm='hold'),
   dict(x=1350, y=700, h=86, skin=3, cloth=1, hair='long', arm='down')],
 names=[dict(x=200, t='Saskia - operations, and the contract is hers'),
   dict(x=300, t='Tomas - standards, and he counted the hedges'),
   dict(x=660, t='the near-miss log: three in eleven months'),
   dict(x=1250, t='the sticky note that says SAY IT ONCE'),
   dict(x=1350, t='the coffee, going cold since six'),
   dict(x=520, t='the clock: ten past seven'),
   dict(x=1075, t='the tug, moored at the berth'),
   dict(x=115, t='the whiteboard, with a 1-to-5 scale on it')],
 markers=[dict(x=200, y=570), dict(x=300, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=115, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b22_u01_p01_v02": dict(type='V2', height=820,
 title='One criticism, in section',
 sub='Twelve words, and the layer each one lives on. The reader meets the top one first.',
 alt='A cutaway of a written criticism in four layers, from the fault in the thing through the '
     'reviewer\'s feeling and the document produced, to the manner it is written in.',
 floors=[dict(was='the fault in the thing', now='shortcoming',
     year='', fill='#EDF1EC'),
   dict(was='what the reviewer is holding', now='reservation · misgiving · caveat',
     year='', fill='#E8EEF0'),
   dict(was='the document produced', now='appraisal · critique · endorsement · commendation · rebuke',
     year='', fill='#F3EADA'),
   dict(was='the manner it is written in', now='candour · diplomacy · tact',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='The only word here that is about the thing and not the reader'),
   dict(at=0.38, text='Three feelings, and a caveat is the only one you write down'),
   dict(at=0.62, text='Five documents, and two of them can end a contract'),
   dict(at=0.88, text='Candour is one of these three and the enemy of the other two')]),

"fig_b22_u01_p02_v07": dict(type='V7', height=840,
 title='Ten past seven, and the review goes on Friday',
 sub='She has the relationship. He has counted the hedges.',
 alt='An operations director and a standards officer at a desk with a printed review between '
     'them, each with two speech balloons and a thought balloon.',
 bg='#E2E6E6',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=2, cloth=0, hair='bun', arm='point', facing='right',
   label='Saskia', role='operations, and she cannot replace them in ninety days',
   says=['Performance has been less than ideal.',
         'I take your point.'],
   thinks=['Eighty-eight per cent and three near misses.']),
  dict(x=1080, h=240, skin=4, cloth=2, hair='short', arm='hold', facing='left',
   label='Tomas', role='standards, and he counted forty-one of them',
   says=['Performance has fallen markedly.',
         'That is one way of putting it.'],
   thinks=['Nine of eleven could not say what we asked them to change.'])]),

"fig_b22_u01_p03_v09": dict(type='V9', kind='ladder', height=800,
 title='The strength dial',
 sub='Six settings on one claim. The words change; the eight points do not.',
 alt='A vertical ladder of hedged and boosted versions of one statement, from utterly '
     'unacceptable at the top to a distanced frame at the bottom.',
 top_label='no room left', bottom_label='nothing asserted',
 steps=[dict(form='utterly', meaning='also without question - no room left to disagree'),
   dict(form='markedly', meaning='also by some margin - the figures must carry it'),
   dict(form='considerably', meaning='large, and defensible without being quoted'),
   dict(form='rather', meaning='up or down, and only the tune decides which'),
   dict(form='somewhat', meaning='also slightly - the claim shrinks, you still make it'),
   dict(form='it would seem', meaning='full size, and you have stepped back from asserting it')]),

"fig_b22_u01_p04_v04": dict(type='V4', height=740,
 title='The same year, two reviews',
 sub='Both true. One of them can be acted on.',
 alt='Two annual reviews of the same contractor side by side, one fully hedged and one with a '
     'single unhedged sentence and a score.',
 differences=6, prompt='Find the six. One of the two contains a sentence that could be read out '
                       'at a board meeting. Which, and how long is it?',
 left=dict(label='as drafted', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#9AA7AE'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#9AA7AE'),
   dict(kind='block', x=150, y=72, w=240, bh=24, colour='#9AA7AE'),
   dict(kind='label', x=300, y=218,
        text='600 words · 41 hedges · 0 numbers · 0 quotable sentences',
        colour='#9AA7AE')]),
 right=dict(label='as sent', art=[
   dict(kind='block', x=150, y=140, w=180, bh=24, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=106, w=250, bh=24),
   dict(kind='block', x=150, y=72, w=230, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='600 words · 9 hedges · 4 numbers · 1 unhedged sentence',
        colour='#2E6F5E')])),

"fig_b22_u01_p05_v05": dict(type='V5', height=1140,
 title='The draft, every hedge marked',
 sub='Six hundred words, forty-one hedges, and an appendix nobody opens.',
 alt='A draft annual review annotated to show every hedge, the figure each hedged claim stands '
     'for, and what the review calls it instead.',
 rows=[dict(t='org', text='CONTRACTOR REVIEW  -  TOWAGE  -  DRAFT 3'),
   dict(t='para', text='"Broadly speaking, performance over the year has on the whole been less '
     'than ideal in certain respects. The port would wish to record a minor reservation '
     'regarding night cover."'),
   dict(t='para', text='"It would seem that occasional difficulties have arisen. The port notes '
     'with appreciation the contractor\'s continued commitment and records its continued '
     'confidence."'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT THE APPENDIX SAYS', 'FIGURE', 'WHAT THE REVIEW CALLS IT'],
     data=[['ON-TIME ARRIVALS', '96% TO 88%', 'LESS THAN IDEAL'],
           ['NEAR MISSES', '3 IN 11 MONTHS', 'OCCASIONAL DIFFICULTIES'],
           ['NEAR MISSES, 4 YEARS BEFORE', '0', 'NOT MENTIONED'],
           ['NIGHT SHIFT SHARE OF DECLINE', '100%', 'A MINOR RESERVATION'],
           ['NIGHT COVER BELOW ESTABLISHMENT', '2', 'NOT MENTIONED'],
           ['HEDGES IN 600 WORDS', '41', '--'],
           ['NUMBERS IN THE REVIEW BODY', '0', '--'],
           ['CONTRACTOR REPLY, LINES', '2', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH HEDGE IS STANDING IN FRONT OF'),
   dict(t='kv', k='"less than ideal"', v='eight percentage points', mono=False),
   dict(t='kv', k='"a minor reservation"', v='the whole of the decline', mono=False),
   dict(t='kv', k='"occasional difficulties"', v='three near misses against none', mono=False),
   dict(t='kv', k='"continued confidence"', v='a ninety-day notice clause, unused', mono=False),
   dict(t='rule'),
   dict(t='para', text='Every sentence in this review is true and the figures are all in the '
     'appendix. What is missing is the one sentence everybody in the port has said out loud.')],
 callouts=[dict(at=0.08, text='Nine hedges before the first full stop'),
   dict(at=0.22, text='A commendation, a confidence, and no verb anybody can act on'),
   dict(at=0.52, text='Four rows the review does not mention at all'),
   dict(at=0.78, text='Each hedge is standing exactly where a number would go'),
   dict(at=0.95, text='Nobody is lying, and nothing has been communicated')]),

"fig_b22_u01_p07_v10": dict(type='V10', kind='pitch', height=860,
 title='The same words, two ranges',
 sub='A narrow range lowers a claim. A wide one raises it. Neither changes a word.',
 alt='Four pitch contours over hedged and boosted sentences, showing a narrow range on a hedge, '
     'a wide range on a boost, a flat delivery and a rising concession.',
 contours=[
  dict(text='It was rather good.',
       points=[0.2, 0.3, 0.2, 0.1, 0.0, -0.1, -0.3],
       meaning='narrow range - rather lowers it'),
  dict(text='It was RATHER good.',
       points=[0.3, 0.6, 0.95, 0.5, 0.1, -0.4, -0.9],
       meaning='wide range - rather raises it'),
  dict(text='Performance has been less than ideal.',
       points=[0.0, 0.0, 0.05, 0.0, -0.05, 0.0, -0.1],
       meaning='flat - and the flatness is the message'),
  dict(text='I take your point...',
       points=[0.2, 0.3, 0.2, 0.3, 0.5, 0.7, 0.9],
       meaning='rising tail - the but has not arrived yet')]),

"fig_b22_u01_p09_v05": dict(type='V5', height=940,
 title='Four hedges on a claim nobody would dispute',
 sub='A hedge is a price. Spend them where you would defend the unhedged version.',
 alt='A study sheet of learner sentences with multiple hedges, what each hedge costs, and the '
     'single hedge worth keeping in each.',
 rows=[dict(t='org', text='STUDY FILE  -  THE HEDGE THAT IS A HABIT'),
   dict(t='para', text='Learners hedge because a hedged claim is easier to defend in a language '
     'still being built. After a while the listener stops hearing them.'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT WAS SAID', 'HEDGES', 'THE ONE WORTH KEEPING'],
     data=[['I THINK IT IS MAYBE A LITTLE HARD', '3', 'A LITTLE'],
           ['SOMETIMES I MAYBE FORGET A BIT', '3', 'SOMETIMES'],
           ['PERHAPS IT IS KIND OF SLOW', '2', 'NONE - SAY IT'],
           ['I THINK MAYBE SHE IS RIGHT', '2', 'NONE - SAY IT'],
           ['IT IS A LITTLE BIT WRONG', '2', 'NONE - IT IS WRONG']]),
   dict(t='rule'),
   dict(t='head', text='WHAT A SPARE HEDGE COSTS YOU'),
   dict(t='kv', k='on an undisputed claim', v='nothing is bought, and one is spent', mono=False),
   dict(t='kv', k='on every sentence', v='the listener stops hearing them', mono=False),
   dict(t='kv', k='when you finally need one', v='there is nothing left to lower', mono=False),
   dict(t='kv', k='one per sentence', v='and only where you would defend the full version',
        mono=False),
   dict(t='rule'),
   dict(t='para', text='Give a thirty-second opinion and ask a partner to repeat back the one '
     'sentence that had no hedge in it. If there was not one, that is the finding.')],
 callouts=[dict(at=0.12, text='Three hedges on a sentence nobody was going to argue with'),
   dict(at=0.44, text='Five sentences, twelve hedges, two of them doing work'),
   dict(at=0.74, text='The right-hand column is the whole exercise'),
   dict(at=0.95, text='The unhedged sentence is the one they will repeat')]),

"fig_b22_u01_p10_v12": dict(type='V12',
 title='Six hundred words, forty-one hedges, eight points',
 sub='What the year did, what the review said, and what eleven contractors took away.',
 alt='An infographic of a contractor review showing the performance decline, the hedges in the '
     'review, what the appendix contained and what contractors understood.',
 span=['0', '600 words'], ticks=4,
 tick_labels=['0', '200', '400', '600'],
 bands=[dict(name='The review', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='600 words, 41 hedges, 0 numbers', colour='#9AA7AE')]),
  dict(name='What the year did', type='events', items=[
   dict(at=0.14, label='on-time: 96% to 88%', colour='#A8372E'),
   dict(at=0.50, label='near misses: 3, against 0', colour='#A8372E'),
   dict(at=0.84, label='night shift: all of the decline', colour='#C86B2B')]),
  dict(name='Where the numbers are', type='bars', items=[
   dict(**{'from': 0.86, 'to': 1.0}, label='the appendix', colour='#2E6F5E')]),
  dict(name='What contractors took away', type='events', items=[
   dict(at=0.18, label='could state the change asked for: 2 of 11', colour='#A8372E'),
   dict(at=0.76, label='described the relationship as good: 11 of 11', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='every hedge is standing exactly where a number would go'),
   dict(at=0.56, label='the relationship survived and the information did not')])]),

"fig_b22_u01_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four ways of writing the same review',
 sub='Eleven contractors, one year, four registers tested on the same findings.',
 alt='A bar chart comparing four review registers on the share of contractors who stated the '
     'required change correctly and the share who said the relationship was damaged.',
 labels=['fully hedged', 'plain', 'hedged + top line', 'score only'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='stated the change (%)', values=[23, 81, 76, 58], colour='#2E6F5E'),
   dict(name='relationship damaged (%)', values=[4, 44, 11, 19], colour='#A8372E')],
 note='Plain writing communicates best and costs most. The hedged review with one unhedged '
      'sentence at the top gets within five points of it for a quarter of the damage.',
 warning='The score-only column is the cheapest to produce and the easiest to argue with, '
         'because a number with no sentence beside it invites a negotiation about the number '
         'rather than about the performance.'),
}
