"""B2.2 Unit 2 - The Goods Were Released - ten figures, as data."""
FIGURES = {
"fig_b22_u02_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The gatehouse, twenty to three in the morning',
 sub='Twelve things to find. Two record the same thirty-eight minutes and one of them is blank.',
 alt='A port gatehouse at night with a bank of camera screens, a chain-of-custody sheet, a '
     'signed haulier docket and a stopped gantry visible through the window.',
 sky='#2E3A42', ground='#5E6468', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#7E868A', cutaway=True,
     floor_labels=['the gate camera feed, 02.40', 'the shift handover log, with a gap',
                   'the radio'],
     label='the gatehouse'),
   dict(x=560, w=480, storeys=3, colour='#868E92', cutaway=True,
     floor_labels=['the chain-of-custody sheet, seven lines',
                   'the manifest, on the clipboard', 'the stamp'],
     label='the desk'),
   dict(x=1120, w=460, storeys=3, colour='#7C8488', cutaway=True,
     floor_labels=['the incident report, draft one', 'the haulier\'s docket, signed',
                   'the screens'],
     label='the office')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='02:40'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='box', x=160, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=200, y=700, h=92, skin=4, cloth=3, hair='cap', arm='point'),
   dict(x=300, y=700, h=88, skin=2, cloth=0, hair='bun', arm='folded'),
   dict(x=660, y=700, h=86, skin=5, cloth=2, hair='short', arm='hold'),
   dict(x=1250, y=700, h=86, skin=1, cloth=4, hair='grey', arm='hold'),
   dict(x=1350, y=700, h=86, skin=3, cloth=1, hair='long', arm='down')],
 names=[dict(x=200, t='the incoming supervisor, on since 02.00'),
   dict(x=300, t='Aicha - nineteen years on this quay'),
   dict(x=660, t='line five, blank'),
   dict(x=1250, t='the chair, pushed back from the desk'),
   dict(x=1350, t='the gantry, stopped since midnight'),
   dict(x=520, t='the clock: twenty to three'),
   dict(x=1075, t='the eastern gate, open at 02.02'),
   dict(x=160, t='the camera feed nobody has requested')],
 markers=[dict(x=200, y=570), dict(x=300, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=160, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b22_u02_p01_v02": dict(type='V2', height=820,
 title='One operation, in section',
 sub='Twelve words, and the layer each one lives on. Only two of them contain people.',
 alt='A cutaway of a port operation in four layers, from the goods and the place through the '
     'people who move them and the permissions, to who answers for it.',
 floors=[dict(was='the goods and the place', now='consignment · manifest · berth · quay · gantry',
     year='', fill='#EDF1EC'),
   dict(was='who moves them', now='stevedore · haulier',
     year='', fill='#E8EEF0'),
   dict(was='the permissions', now='clearance · custody',
     year='', fill='#F3EADA'),
   dict(was='who answers for it', now='liability · oversight · escalation',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Five words, no people, and the whole report is about this layer'),
   dict(at=0.38, text='The only layer with hands in it, and it appears twice in 1,100 words'),
   dict(at=0.62, text='Two words, and a blank line in one of them started all of this'),
   dict(at=0.88, text='Three words for the thing nobody in the report is said to have')]),

"fig_b22_u02_p02_v07": dict(type='V7', height=840,
 title='The handover gap',
 sub='She has nineteen years. He has a sheet with a blank line on it.',
 alt='A shift supervisor and an operations director at a desk with a chain-of-custody sheet '
     'between them, each with two speech balloons and a thought balloon.',
 bg='#DDE2E3',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=2, cloth=0, hair='bun', arm='folded', facing='right',
   label='Aicha', role='nineteen years, and two hundred of these',
   says=['The gate was opened at 02.02.',
         'That is above my pay grade.'],
   thinks=['I have never been afraid of being named.']),
  dict(x=1080, h=240, skin=4, cloth=3, hair='cap', arm='point', facing='left',
   label='the incoming supervisor', role='on duty since 02.00, nine minutes before',
   says=['It was decided to release the consignment.',
         'Nobody has been named.'],
   thinks=['Line five is blank and I signed the one above it.'])]),

"fig_b22_u02_p03_v09": dict(type='V9', kind='mirror', height=700,
 title='The same event, and where the agent goes',
 sub='Active, passive with the agent, passive without. Nothing is added and one name disappears.',
 alt='Two sentence diagrams of the same event, the first active with the agent in subject '
     'position and the second passive with the agent removed entirely.',
 labels=['ACTIVE', 'PASSIVE'],
 between='the agent can be kept and placed last, or removed - and the grammar looks the same',
 active=dict(parts=[dict(w=26, role='agent', text='The night supervisor'),
   dict(w=16, role='action', text='opened'),
   dict(w=20, role='affected', text='the gate'),
   dict(w=16, role='hidden', text='at 02.02')]),
 passive=dict(parts=[dict(w=20, role='affected', text='The gate'),
   dict(w=24, role='action', text='was opened'),
   dict(w=18, role='hidden', text='at 02.02'),
   dict(w=26, role='hidden', text='(by whom?)')])),

"fig_b22_u02_p04_v04": dict(type='V4', height=740,
 title='The same thirty-eight minutes, two reports',
 sub='Both accurate. One of them can be acted on by a named person.',
 alt='Two incident reports side by side, one entirely in agentless passives and one with a '
     'narrative passive and an actions table.',
 differences=6, prompt='Find the six. One report contains a line somebody could be asked about. '
                       'Which, and how many such lines are there?',
 left=dict(label='as filed', art=[
   dict(kind='block', x=150, y=140, w=260, bh=24, colour='#9AA7AE'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#9AA7AE'),
   dict(kind='block', x=150, y=72, w=240, bh=24, colour='#9AA7AE'),
   dict(kind='label', x=300, y=218,
        text='1,100 words · 26 passives · 2 names, both external · 0 owners',
        colour='#9AA7AE')]),
 right=dict(label='with an actions table', art=[
   dict(kind='block', x=150, y=140, w=240, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=72, w=200, bh=24),
   dict(kind='label', x=300, y=218,
        text='1,100 words · 26 passives · 8 table lines · 6 owners, 2 systems',
        colour='#2E6F5E')])),

"fig_b22_u02_p05_v05": dict(type='V5', height=1140,
 title='The report, every agent accounted for',
 sub='Eleven hundred words, twenty-six passives, and two names from other companies.',
 alt='An incident report annotated to show each passive construction, whether the agent is '
     'unknown, obvious or protected, and the four findings with no owner.',
 rows=[dict(t='org', text='INCIDENT REPORT  -  EASTERN GATE  -  14 MARCH'),
   dict(t='para', text='"The gate was opened at 02.02. The consignment was released. A '
     'procedural failure occurred during the shift handover. The matter is being reviewed."'),
   dict(t='para', text='"It was decided that documentation would be completed retrospectively. '
     'No individual has been identified."'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT THE SENTENCE SAYS', 'AGENT', 'WHICH KIND'],
     data=[['THE GATE WAS OPENED', 'NOT NAMED', 'ON CAMERA - KNOWABLE'],
           ['THE CONSIGNMENT WAS RELEASED', 'NOT NAMED', 'OBVIOUS'],
           ['A PROCEDURAL FAILURE OCCURRED', 'NONE POSSIBLE', 'A SYSTEM'],
           ['THE MATTER IS BEING REVIEWED', 'NOT NAMED', 'PROTECTED'],
           ['IT WAS DECIDED', 'NOT NAMED', 'PROTECTED'],
           ['PASSIVES IN 1,100 WORDS', '26', '--'],
           ['NAMES IN THE REPORT', '2', 'BOTH EXTERNAL'],
           ['CAMERA FEED REQUESTED', 'NO', '--']]),
   dict(t='rule'),
   dict(t='head', text='THE SEVEN LINES OF THE CHAIN OF CUSTODY'),
   dict(t='kv', k='lines 1 to 4', v='logged, inspected, sealed, staged - all signed', mono=False),
   dict(t='kv', k='line 5: authorising supervisor', v='blank', mono=False),
   dict(t='kv', k='line 6: gate release', v='signed, 02.31', mono=False),
   dict(t='kv', k='line 7: haulier receipt', v='signed, 02.40', mono=False),
   dict(t='rule'),
   dict(t='para', text='The report was written from the sheet. The sheet has a blank line. '
     'Nothing in the report is false, and nothing in it is answerable.')],
 callouts=[dict(at=0.08, text='Four sentences, four passives, nought people'),
   dict(at=0.22, text='A decision with no decider and a finding with nobody in it'),
   dict(at=0.48, text='Three of the five agents were knowable at the time'),
   dict(at=0.78, text='Lines 6 and 7 are signed either side of the blank one'),
   dict(at=0.95, text='Written from the sheet, so the gap became the account')]),

"fig_b22_u02_p07_v10": dict(type='V10', kind='stress', height=840,
 title='Where the voice falls when the agent arrives late',
 sub='A by-phrase takes the nuclear stress unless you take it away from it.',
 alt='One passive sentence drawn five times as beats with the nuclear stress in a different '
     'place each time and the reading that follows.',
 items=[
  dict(syllables=['the', 'gate', 'was', 'O-pened'], strong=[3],
       note='the event is the news, and nobody is in it'),
  dict(syllables=['the', 'gate', 'was', 'o-pened', 'by', 'the', 'su-per-VI-sor'], strong=[9],
       note='the agent is last, and last is the point'),
  dict(syllables=['the', 'GATE', 'was', 'o-pened', 'by', 'him'], strong=[1],
       note='and something else was opened by somebody else'),
  dict(syllables=['it', 'was', 'de-CI-ded'], strong=[3],
       note='a decision is reported'),
  dict(syllables=['it', 'WAS', 'de-ci-ded'], strong=[1],
       note='and somebody has just denied that one was')]),

"fig_b22_u02_p09_v05": dict(type='V5', height=940,
 title='Four paragraphs that change subject every sentence',
 sub='A learner taught to avoid the passive writes a paragraph about four different things.',
 alt='A study sheet showing learner paragraphs whose subject changes in every sentence, the '
     'topic each paragraph is actually about, and the passive that would hold it.',
 rows=[dict(t='org', text='STUDY FILE  -  THE PASSIVE YOU WERE TAUGHT TO AVOID'),
   dict(t='para', text='You were told the passive is weak writing, and then you met it on every '
     'page of everything you read professionally. Both of those are true.'),
   dict(t='rule'),
   dict(t='grid', cols=['THE PARAGRAPH IS ABOUT', 'SUBJECTS USED', 'WHAT WOULD HOLD IT'],
     data=[['THE SAMPLE', 'WE, I, THE LAB, IT', 'THE SAMPLE WAS ...'],
           ['THE APPLICATION', 'YOU, THEY, THE OFFICE', 'THE APPLICATION IS ...'],
           ['THE MACHINE', 'SOMEBODY, WE, IT', 'THE MACHINE IS ...'],
           ['THE RULE', 'PEOPLE, THEY, ONE', 'THE RULE IS ...'],
           ['THE STORY', 'HE, SHE, THEY', 'KEEP THE ACTIVE - IT IS A STORY']]),
   dict(t='rule'),
   dict(t='head', text='WHERE EACH PIECE OF ADVICE IS TRUE'),
   dict(t='kv', k='use the active', v='in a story about people doing things', mono=False),
   dict(t='kv', k='the passive is weak', v='when the agent matters and is hidden', mono=False),
   dict(t='kv', k='the passive is right', v='in a method, a rule or a specification', mono=False),
   dict(t='kv', k='the test', v='what is this paragraph about? Keep it in subject position',
        mono=False),
   dict(t='rule'),
   dict(t='para', text='Underline the subject of every sentence in a paragraph you have written. '
     'If it changes more than once, the paragraph is about more than one thing.')],
 callouts=[dict(at=0.12, text='Two true pieces of advice that contradict each other'),
   dict(at=0.44, text='Four subjects in four sentences, and one topic throughout'),
   dict(at=0.74, text='The last row is the one where the advice you were given holds'),
   dict(at=0.95, text='One underline per sentence is the whole diagnosis')]),

"fig_b22_u02_p10_v12": dict(type='V12',
 title='Thirty-eight minutes, seven lines, twenty-six passives',
 sub='What happened, what was written down, and where the agent went.',
 alt='An infographic of a port incident showing the timeline of the release, the chain-of-custody '
     'signatures, the passives in the report and what the camera covered.',
 span=['02.00', '02.40'], ticks=5,
 tick_labels=['02.00', '02.10', '02.20', '02.30', '02.40'],
 bands=[dict(name='The handover', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.30}, label='02.00 to 02.12 - nobody formally responsible',
        colour='#C86B2B')]),
  dict(name='What happened', type='events', items=[
   dict(at=0.12, label='gate opened: 02.02', colour='#A8372E'),
   dict(at=0.48, label='loaded: 02.19', colour='#9AA7AE'),
   dict(at=0.93, label='released: 02.40', colour='#A8372E')]),
  dict(name='The seven lines', type='events', items=[
   dict(at=0.18, label='lines 1-4 signed', colour='#2E6F5E'),
   dict(at=0.56, label='line 5: blank', colour='#A8372E'),
   dict(at=0.88, label='lines 6-7 signed', colour='#2E6F5E')]),
  dict(name='The camera', type='bars', items=[
   dict(**{'from': 0.05, 'to': 1.0}, label='covers all of it - not requested',
        colour='#9AA7AE')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='three of the five hidden agents were knowable at the time'),
   dict(at=0.56, label='the report was written from the sheet, so the gap became the account')])]),

"fig_b22_u02_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four ways of writing an incident report',
 sub='Two years of the port\'s own reports, scored on two things that pull against each other.',
 alt='A bar chart comparing four incident-report formats on whether a reader could name an owner '
     'and how many reports were filed each month.',
 labels=['all passive', 'all named', 'passive + owners', 'anonymous summary'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='reader could name an owner (%)', values=[8, 94, 88, 21], colour='#2E6F5E'),
   dict(name='reports filed per month', values=[31, 12, 36, 28], colour='#C86B2B')],
 note='Naming everybody answers the first question and destroys the second: filings fall by '
      'nearly two thirds. The actions table gets within six points of it and filings rise.',
 warning='The second series is a count, not a percentage; it is drawn on the same axis because '
         'both happen to run from nought to a hundred, and the two should not be compared with '
         'each other, only each with itself across the four formats.'),
}
