"""B2.2 Unit 3 - Fourteen Words, One Noun - ten figures, as data."""
FIGURES = {
"fig_b22_u03_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The tender room, five past two',
 sub='Twelve things to find. Three of them are the same requirement, priced three ways.',
 alt='A port tender room with a 340-page document, a highlighted clause, three bid summaries and '
     'a whiteboard with one noun phrase broken into brackets.',
 sky='#D5DADC', ground='#86888A', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#AFB4B6', cutaway=True,
     floor_labels=['the tender, 340 pages', 'clause 7.4.2, highlighted',
                   'the brackets'],
     label='the document'),
   dict(x=560, w=480, storeys=3, colour='#B7BCBE', cutaway=True,
     floor_labels=['the clarification log, 212 questions',
                   'three bid summaries, three prices', 'the berth 4 drawing'],
     label='the evidence'),
   dict(x=1120, w=460, storeys=3, colour='#ACB1B3', cutaway=True,
     floor_labels=['the remote-operation console', 'the stacking yard, beyond the window',
                   'the diagram'],
     label='the terminal')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='14:05'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=160, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=250, y=700, h=92, skin=2, cloth=0, hair='bun', arm='point'),
   dict(x=350, y=700, h=88, skin=1, cloth=2, hair='short', arm='hold'),
   dict(x=660, y=700, h=86, skin=5, cloth=3, hair='cap', arm='folded'),
   dict(x=1250, y=700, h=86, skin=4, cloth=4, hair='long', arm='hold'),
   dict(x=1350, y=700, h=86, skin=3, cloth=1, hair='grey', arm='down')],
 names=[dict(x=250, t='Saskia - she signed the tender off'),
   dict(x=350, t='Gunnar - bid manager, six per cent of margin'),
   dict(x=660, t='the ruler, used as a pointer'),
   dict(x=1250, t='the diagram, with one word circled'),
   dict(x=1350, t='the box of highlighters, all dead'),
   dict(x=520, t='the clock: five past two'),
   dict(x=1075, t='berth 4, rail-served, deep water'),
   dict(x=160, t='the whiteboard, one phrase in brackets')],
 markers=[dict(x=250, y=570), dict(x=350, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=160, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b22_u03_p01_v02": dict(type='V2', height=820,
 title='One system, in section',
 sub='Twelve words, and the layer each one lives on. Only two layers appear in a tender.',
 alt='A cutaway of a logistics system in four layers, from what moves through it and what limits '
     'it to how well it holds together and how it is shaped and supplied.',
 floors=[dict(was='what moves through it', now='throughput · inventory · cadence',
     year='', fill='#EDF1EC'),
   dict(was='what limits it', now='bottleneck · capacity · headroom',
     year='', fill='#E8EEF0'),
   dict(was='how well it holds', now='resilience · interoperability · latency',
     year='', fill='#F3EADA'),
   dict(was='how it is shaped and supplied', now='topology · utilisation · provisioning',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Three words, and only the first ever reaches a press release'),
   dict(at=0.38, text='Capacity and headroom are the same number from opposite ends'),
   dict(at=0.62, text='The layer a specification is about, and the hardest to write'),
   dict(at=0.88, text='Decided years earlier, by people who have left')]),

"fig_b22_u03_p02_v07": dict(type='V7', height=840,
 title='Clause 7.4.2',
 sub='She wrote the tender. He priced it, with a margin for being wrong.',
 alt='An operations director and a supplier\'s bid manager at a table with a tender document and '
     'three bid summaries between them, each with two speech balloons and a thought balloon.',
 bg='#E1E5E6',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=2, cloth=0, hair='bun', arm='point', facing='right',
   label='Saskia', role='three engineers, nine weeks, proofread for spelling',
   says=['Automated modifies the crane.',
         'That is the constraint.'],
   thinks=['Sixty-one questions were all the same question.']),
  dict(x=1080, h=240, skin=1, cloth=2, hair='short', arm='hold', facing='left',
   label='Gunnar', role='he priced what he thought you meant',
   says=['All three readings are grammatical.',
         'Read it backwards.'],
   thinks=['Six per cent of the bid is margin for being wrong.'])]),

"fig_b22_u03_p03_v09": dict(type='V9', kind='scope', height=560,
 title='Everything to the left, one word in the middle',
 sub='Four pre-modifiers, one head, one post-modifier. Read it from the head backwards.',
 alt='A fourteen-word noun phrase drawn as chunks with brackets marking the pre-modifiers, the '
     'head noun and the post-modifier.',
 words=['the', 'automated', 'crane', 'handover', 'latency', 'REQUIREMENTS', 'for berth 4'],
 focus=[5],
 brackets=[dict(**{'from': 1, 'to': 4}, lane=0, colour='#C86B2B',
     label='FOUR PRE-MODIFIERS: each may attach to any noun on its right'),
   dict(**{'from': 5, 'to': 5}, lane=0, colour='#1F4E5F', label='THE HEAD'),
   dict(**{'from': 6, 'to': 6}, lane=0, colour='#2E6F5E', label='POST-MODIFIER'),
   dict(**{'from': 0, 'to': 0}, lane=1, colour='#9AA7AE', label='the phrase starts here')]),

"fig_b22_u03_p04_v04": dict(type='V4', height=740,
 title='The same requirement, two ways',
 sub='One of them was priced three ways. The other could only be priced once.',
 alt='Two versions of the same specification clause side by side, one as a long pre-modified '
     'noun phrase and one as a sentence with a verb and a number.',
 differences=6, prompt='Find the six. One version contains a number. Which, and how many words '
                       'does it take to get to it?',
 left=dict(label='clause 7.4.2, as issued', art=[
   dict(kind='block', x=150, y=140, w=270, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=250, bh=24, colour='#A8372E'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='14 words · 0 verbs · 0 numbers · 3 readings',
        colour='#A8372E')]),
 right=dict(label='as rewritten', art=[
   dict(kind='block', x=150, y=140, w=200, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=230, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=72, w=180, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='17 words · 1 verb · 1 number · 1 reading',
        colour='#2E6F5E')])),

"fig_b22_u03_p05_v05": dict(type='V5', height=1000,
 title='Clause 7.4.2, every modifier traced',
 sub='Fourteen words, one head, and three defensible readings of the same sentence.',
 alt='A tender clause annotated to show its head noun, each pre-modifier and what it could '
     'attach to, and the three prices that followed.',
 rows=[dict(t='org', text='BERTH 4 AUTOMATION PACKAGE  -  CLAUSE 7.4.2'),
   dict(t='para', text='"The automated rail-mounted gantry crane remote operation handover '
     'latency requirements for berth 4 shall be met in full."'),
   dict(t='para', text='Annex C, test method: "console input to confirmed crane response, '
     'measured end to end." No figure is given in the clause itself.'),
   dict(t='rule'),
   dict(t='grid', cols=['SUPPLIER', 'WHAT THEY READ AS THE HEAD', 'PRICED'],
     data=[['A', 'CRANE REQUIREMENTS', 'NEW CONTROL HARDWARE'],
           ['B', 'HANDOVER REQUIREMENTS', 'A SOFTWARE LAYER'],
           ['C', 'AUTOMATED HANDOVER', 'NEITHER - ALREADY DONE'],
           ['SPREAD BETWEEN BIDS', 'EUR 2.3M', '--'],
           ['WORDS IN THE PHRASE', '14', '--'],
           ['NUMBERS IN THE CLAUSE', '0', '--'],
           ['CLARIFICATIONS, THIS TENDER', '212', '--'],
           ['OF THOSE, ABOUT MODIFICATION', '61', 'NONE PUBLISHED']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH PRE-MODIFIER COULD ATTACH TO'),
   dict(t='kv', k='automated', v='crane, operation, handover or latency', mono=False),
   dict(t='kv', k='rail-mounted', v='crane only - a physical fact saves it', mono=False),
   dict(t='kv', k='remote', v='operation or handover', mono=False),
   dict(t='kv', k='for berth 4', v='requirements - post-modifiers do not stray', mono=False),
   dict(t='rule'),
   dict(t='para', text='Three engineers wrote this over nine weeks. It was proofread for '
     'spelling, and every word in it is spelled correctly.')],
 callouts=[dict(at=0.08, text='Fourteen words, no verb, and the head is the twelfth'),
   dict(at=0.22, text='The number is in an annex and the requirement is in the clause'),
   dict(at=0.48, text='Three readings, three scopes, and two point three million euros'),
   dict(at=0.80, text='Only two of the modifiers are pinned, and both by physics'),
   dict(at=0.95, text='Proofread for spelling is the whole sentence')]),

"fig_b22_u03_p07_v10": dict(type='V10', kind='pitch', height=860,
 title='One phrase, one tune - and where you break it',
 sub='A pause inside a noun phrase is a bracket the listener can hear.',
 alt='Four pitch contours over a long noun phrase, said as one tone unit and then broken in '
     'different places, with the reading each break produces.',
 contours=[
  dict(text='the automated gantry crane handover latency requirements',
       points=[0.3, 0.3, 0.35, 0.3, 0.3, 0.25, -0.8],
       meaning='one unit, level, falling on the head'),
  dict(text='automated | gantry crane handover',
       points=[0.6, 0.3, 0.45, 0.4, 0.3, 0.2, -0.6],
       meaning='automated modifies the whole of it'),
  dict(text='automated gantry crane | handover',
       points=[0.4, 0.4, 0.3, 0.6, 0.4, 0.1, -0.7],
       meaning='and now it modifies the crane only'),
  dict(text='handover latency | shall not exceed | 400 ms',
       points=[0.4, 0.2, 0.5, 0.3, 0.6, 0.2, -0.9],
       meaning='three units, and the number lands last')]),

"fig_b22_u03_p09_v05": dict(type='V5', height=940,
 title='Five phrases a learner unpacks and a field packs',
 sub='Correct, longer, and instantly identifiable as not written by somebody in the industry.',
 alt='A study sheet comparing learner of-phrases with the pre-modified noun phrases used in the '
     'field, and the word count saved by each.',
 rows=[dict(t='org', text='STUDY FILE  -  THE PHRASE YOU CAN READ AND CANNOT WRITE'),
   dict(t='para', text='Reading a four-noun phrase is easy. Building one is not, because you '
     'cannot hear whether the order is right, so you unpack instead.'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT YOU WRITE', 'WHAT THE FIELD WRITES', 'SAVED'],
     data=[['THE SYSTEM FOR MANAGING CONTAINERS', 'THE CONTAINER MANAGEMENT SYSTEM', '2 WORDS'],
           ['DELAYS IN THE CLEARANCE OF CUSTOMS', 'CUSTOMS CLEARANCE DELAYS', '3 WORDS'],
           ['THE TIME TAKEN TO TURN A SHIP ROUND', 'TURNAROUND TIME', '6 WORDS'],
           ['THE NETWORK OF WATERWAYS INLAND', 'THE INLAND WATERWAY NETWORK', '1 WORD'],
           ['THE INTEGRITY OF THE COLD CHAIN', 'COLD-CHAIN INTEGRITY', '3 WORDS']]),
   dict(t='rule'),
   dict(t='head', text='HOW TO CHECK ONE YOU HAVE BUILT'),
   dict(t='kv', k='read it backwards', v='requirements - latency - handover - crane', mono=False),
   dict(t='kv', k='find the head', v='the last noun before of, for or at', mono=False),
   dict(t='kv', k='three at a time', v='four-noun phrases are learned, not derived', mono=False),
   dict(t='kv', k='the five-second rule', v='if it takes longer to parse, unpack it', mono=False),
   dict(t='rule'),
   dict(t='para', text='Collect five phrases of four words or more from real documents in your '
     'field, mark the head of each, and bring one you cannot parse.')],
 callouts=[dict(at=0.12, text='Nothing on the left is wrong. All of it is longer'),
   dict(at=0.44, text='Five phrases, fifteen words saved, same information'),
   dict(at=0.76, text='Reading backwards is the whole technique'),
   dict(at=0.95, text='The one you cannot parse is next week\'s lesson')]),

"fig_b22_u03_p10_v12": dict(type='V12',
 title='Three hundred and forty pages, one clause',
 sub='Where the questions were, where the money was, and what the clause actually said.',
 alt='An infographic of a port tender showing the length of the document, the clarification '
     'questions, the three bids and the spread between them.',
 span=['0', '340 pages'], ticks=4,
 tick_labels=['0', '113', '227', '340'],
 bands=[dict(name='The tender', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='340 pages, three engineers, nine weeks',
        colour='#9AA7AE')]),
  dict(name='Where clause 7.4.2 is', type='events', items=[
   dict(at=0.21, label='page 71, fourteen words, no number', colour='#A8372E')]),
  dict(name='Clarifications', type='events', items=[
   dict(at=0.22, label='212 questions in all', colour='#C86B2B'),
   dict(at=0.68, label='61 of them: does X modify Y or Z', colour='#A8372E')]),
  dict(name='The three bids', type='events', items=[
   dict(at=0.16, label='A: control hardware', colour='#1F4E5F'),
   dict(at=0.50, label='B: a software layer', colour='#C86B2B'),
   dict(at=0.84, label='C: neither', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='all three readings are grammatical and two of them are wrong'),
   dict(at=0.58, label='the spread between the bids was 2.3m euros, all in one clause')])]),

"fig_b22_u03_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four specification styles, one requirement',
 sub='The same requirement issued four ways to the same three bidders.',
 alt='A bar chart comparing four specification styles on the share of suppliers reading a clause '
     'the same way and the number of clarification questions per hundred pages.',
 labels=['dense phrases', 'one sentence each', 'dense + diagram', 'plain prose'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='same reading (%)', values=[38, 89, 84, 71], colour='#2E6F5E'),
   dict(name='questions per 100 pages', values=[62, 18, 21, 34], colour='#C86B2B')],
 note='One sentence per requirement wins on both measures and doubles the length of the document. '
      'The diagram gets within five points of it for one line a clause.',
 warning='The second series is a count, not a percentage. It shares the axis because both happen '
         'to run from nought to a hundred here; compare each series with itself across the four '
         'styles, and not with the other.'),
}
