"""B2.2 Unit 4 - Nine Thousand Words and One Hundred and Eighty - ten figures, as data."""
FIGURES = {
"fig_b22_u04_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The finance floor, twenty-five past four',
 sub='Twelve things to find. Two describe the same finding and one is fifty times shorter.',
 alt='A port finance office with a commissioned paper, a short note from the annual report, a '
     'provision schedule and a window onto the inland quay with a cabled berth.',
 sky='#D4D9DB', ground='#858C8E', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#AEB4B6', cutaway=True,
     floor_labels=['the paper, 9,400 words', 'the note, 180 words',
                   'the reference list'],
     label='the two documents'),
   dict(x=560, w=480, storeys=3, colour='#B6BCBE', cutaway=True,
     floor_labels=['the barge-call log, 1,140 entries', 'the berth list, four of nine ringed',
                   'the audit file'],
     label='the evidence'),
   dict(x=1120, w=460, storeys=3, colour='#ABB1B3', cutaway=True,
     floor_labels=['the provision schedule, 8.4m', 'the board secretary\'s email',
                   'the quay'],
     label='the accounts')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='16:25'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=160, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=250, y=700, h=92, skin=1, cloth=0, hair='long', arm='point'),
   dict(x=350, y=700, h=88, skin=3, cloth=2, hair='short', arm='hold'),
   dict(x=660, y=700, h=86, skin=5, cloth=3, hair='cap', arm='folded'),
   dict(x=1250, y=700, h=86, skin=2, cloth=4, hair='bun', arm='hold'),
   dict(x=1350, y=700, h=86, skin=4, cloth=1, hair='grey', arm='down')],
 names=[dict(x=250, t='Ilse - she wrote the nine thousand words'),
   dict(x=350, t='the board secretary, who added three sentences'),
   dict(x=660, t='the highlighter, on a single paragraph'),
   dict(x=1250, t='the shore-power cable, berth 6'),
   dict(x=1350, t='the window onto the inland quay'),
   dict(x=520, t='the clock: twenty-five past four'),
   dict(x=1075, t='the cabled berth, one of four'),
   dict(x=160, t='the 112 references, none in the note')],
 markers=[dict(x=250, y=570), dict(x=350, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=160, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b22_u04_p01_v02": dict(type='V2', height=820,
 title='One finding, in section',
 sub='Twelve words, and the layer each one lives on. One of them appears on two floors.',
 alt='A cutaway of a commissioned study and its accounting treatment in four layers, from the '
     'design through the results and the examination to the figures in the accounts.',
 floors=[dict(was='what you set up', now='methodology · sample · variable · hypothesis',
     year='', fill='#EDF1EC'),
   dict(was='what comes out', now='findings · corollary',
     year='', fill='#E8EEF0'),
   dict(was='what is checked', now='audit · disclosure',
     year='', fill='#F3EADA'),
   dict(was='what reaches the accounts', now='valuation · amortisation · provision · accrual',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Four decisions taken before any number exists'),
   dict(at=0.38, text='Two words, and a corollary is the one nobody reads'),
   dict(at=0.62, text='Disclosure is here and also two floors up, meaning something else'),
   dict(at=0.88, text='The only layer the board is required to approve')]),

"fig_b22_u04_p02_v07": dict(type='V7', height=840,
 title='Twenty-five past four',
 sub='She wrote nine thousand four hundred words. He wrote the hundred and eighty they read.',
 alt='A researcher and a board secretary at a desk with a thick paper and a single printed note '
     'between them, each with two speech balloons and a thought balloon.',
 bg='#E0E5E6',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=1, cloth=0, hair='long', arm='point', facing='right',
   label='Ilse', role='she has been summarised accurately twice in nine years',
   says=['At the four cabled berths, sixty-two per cent.',
         'Across all 1,140 calls, eight.'],
   thinks=['Significant appears eleven times and means one thing.']),
  dict(x=1080, h=240, skin=3, cloth=2, hair='short', arm='hold', facing='left',
   label='the board secretary', role='a hundred and eighty words, no references',
   says=['A significant reduction has been achieved.',
         'For the avoidance of doubt.'],
   thinks=['Three of these sentences came out of a meeting.'])]),

"fig_b22_u04_p03_v09": dict(type='V9', kind='branch', height=820,
 title='One noun, six clauses hanging off it',
 sub='The same berths, six ways, and two of the six claim a different number.',
 alt='A branching diagram from one noun phrase into six clause types, each with the quantity it '
     'claims and an example.',
 root='the berths',
 branches=[dict(label='that were cabled', colour='#1F4E5F',
     example='DEFINING: some of them were, and these are those'),
   dict(label=', which were cabled,', colour='#A8372E',
     example='NON-DEFINING: all nine of them were'),
   dict(label='cabled in 2021', colour='#C86B2B',
     example='REDUCED: the pronoun and be have gone, and so has the signal'),
   dict(label='serving the fleet', colour='#2E6F5E',
     example='PRESENT PARTICIPLE: active, and happening at the same time'),
   dict(label=', having been cabled,', colour='#D9A441',
     example='PERFECT PARTICIPLE: and this one happened first'),
   dict(label='referred to above', colour='#9AA7AE',
     example='POINTING BACK: defined somewhere else in the document')]),

"fig_b22_u04_p04_v04": dict(type='V4', height=740,
 title='The same finding, two documents',
 sub='Nine thousand four hundred words, and the hundred and eighty the board read.',
 alt='A research paper and a note in an annual report side by side, with their lengths, '
     'references and the scopes each one states.',
 differences=6, prompt='Find the six. One of the two states the scope of its percentage. Which, '
                       'and how many scopes does it state?',
 left=dict(label='the paper', art=[
   dict(kind='block', x=150, y=140, w=270, bh=24, colour='#1F4E5F'),
   dict(kind='block', x=150, y=106, w=260, bh=24, colour='#1F4E5F'),
   dict(kind='block', x=150, y=72, w=250, bh=24, colour='#1F4E5F'),
   dict(kind='label', x=300, y=218,
        text='9,400 words · 112 references · 2 scopes · 62% and 8%',
        colour='#1F4E5F')]),
 right=dict(label='the note', art=[
   dict(kind='block', x=150, y=140, w=130, bh=24, colour='#A8372E'),
   dict(kind='gap', x=150, y=106, w=250, bh=24),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='180 words · 0 references · 0 scopes · "significant"',
        colour='#A8372E')])),

"fig_b22_u04_p05_v05": dict(type='V5', height=1060,
 title='The abstract and the note, every clause marked',
 sub='Four relative clauses, three reduced, and one comma worth five berths.',
 alt='A research abstract and an annual-report note annotated to show each relative and '
     'participle clause, whether it is defining, and which sentences have no source.',
 rows=[dict(t='org', text='SHORE POWER AT INLAND BERTHS  -  ABSTRACT AND NOTE 14'),
   dict(t='para', text='ABSTRACT: "Of the nine inland berths, four, cabled in 2021, are equipped '
     'for shore power. Calls using shore power at those berths produce 62% less at-berth '
     'emission than comparable calls that do not."'),
   dict(t='para', text='NOTE 14: "A significant reduction in at-berth emissions has been '
     'achieved at the berths, which have been cabled. A provision of EUR 8.4m is held in respect '
     'of the remaining berths."'),
   dict(t='rule'),
   dict(t='grid', cols=['FEATURE', 'THE PAPER', 'THE NOTE'],
     data=[['WORDS', '9,400', '180'],
           ['REFERENCES', '112', '0'],
           ['RELATIVE CLAUSES', '41', '2'],
           ['PARTICIPLE CLAUSES', '63', '1'],
           ['SCOPES STATED', '2', '0'],
           ['"SIGNIFICANT", MEANING', 'NOT CHANCE (x11)', 'LARGE (x1)'],
           ['BERTHS CLAIMED CABLED', '4 OF 9', '9 OF 9'],
           ['SENTENCES WITH NO SOURCE', '--', '3']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH CLAUSE CLAIMS'),
   dict(t='kv', k='"four, cabled in 2021,"', v='non-defining - those four, all cabled',
        mono=False),
   dict(t='kv', k='"calls using shore power"', v='reduced, defining - only those calls',
        mono=False),
   dict(t='kv', k='"calls that do not"', v='defining - the comparison group', mono=False),
   dict(t='kv', k='"the berths, which have..."', v='non-defining - all nine of them',
        mono=False),
   dict(t='rule'),
   dict(t='para', text='Two commas in note 14 claim five berths that do not exist. Nothing else '
     'in either document is inaccurate.')],
 callouts=[dict(at=0.08, text='The quantity is stated twice before any percentage appears'),
   dict(at=0.24, text='Two commas, and the note now claims nine cabled berths'),
   dict(at=0.52, text='Two scopes in one document and none in the other'),
   dict(at=0.84, text='One word, two meanings, eleven uses and one'),
   dict(at=0.96, text='Two commas are worth five berths')]),

"fig_b22_u04_p07_v10": dict(type='V10', kind='stress', height=580,
 title='Forty words, three beats',
 sub='A long formal sentence has as many beats as it has clauses, and no more.',
 alt='Formal sentences drawn as beats, with the main stresses marked and the reduced clauses '
     'shown as unstressed runs between them.',
 items=[
  dict(syllables=['of', 'the', 'NINE', 'berths', 'FOUR', 'are', 'CA-bled'], strong=[2, 4, 6],
       note='three beats in seven words'),
  dict(syllables=['the', 'BERTHS', 'ca-bled', 'in', '2021', 'are', 'USED'], strong=[1, 6],
       note='the reduced clause gets no beat'),
  dict(syllables=['the', 'BERTHS', 'ca-bled', 'in', '2021', 'are', 'used'], strong=[1],
       note='no pauses: only some were cabled'),
  dict(syllables=['the', 'BERTHS', '(pause)', 'ca-bled', '(pause)', 'are', 'USED'],
       strong=[1, 6], note='pauses each side: all nine were')]),

"fig_b22_u04_p09_v05": dict(type='V5', height=940,
 title='Four paragraphs and the sentence where each one slipped',
 sub='Almost every learner can open in formal register. The third sentence is where it goes.',
 alt='A study sheet of four learner paragraphs showing the sentence at which the formal register '
     'slipped and what gave it away.',
 rows=[dict(t='org', text='STUDY FILE  -  THE REGISTER THAT WILL NOT HOLD'),
   dict(t='para', text='Opening formally is easy: the first sentence is planned. Holding it is '
     'not, because by the third sentence you are thinking about content.'),
   dict(t='rule'),
   dict(t='grid', cols=['IT SLIPPED AT', 'WHAT GAVE IT AWAY', 'THE SUBSTITUTION'],
     data=[['SENTENCE 3', 'HAD A LOOK AT', 'EXAMINED'],
           ['SENTENCE 3', 'A LOT OF', 'A SUBSTANTIAL NUMBER OF'],
           ['SENTENCE 4', 'DIDN\'T', 'DID NOT'],
           ['SENTENCE 2', 'SO WE', 'ACCORDINGLY'],
           ['SENTENCE 4', 'GOT', 'OBTAINED']]),
   dict(t='rule'),
   dict(t='head', text='WHY THE THIRD SENTENCE'),
   dict(t='kv', k='sentence one', v='planned before you started writing', mono=False),
   dict(t='kv', k='sentence two', v='still inside the plan', mono=False),
   dict(t='kv', k='sentence three', v='the first one you are composing live', mono=False),
   dict(t='kv', k='the fix', v='four substitutions learned as pairs, not as a rule', mono=False),
   dict(t='rule'),
   dict(t='para', text='Raise the register of a paragraph you wrote informally, changing nothing '
     'else, and count the words you added. The usual answer is nine to fourteen per cent.')],
 callouts=[dict(at=0.12, text='The opening is never the problem'),
   dict(at=0.44, text='Three of the five slips are in the third sentence'),
   dict(at=0.74, text='Pairs are learned; rules are derived, and derivation is slow'),
   dict(at=0.95, text='Formality costs about twelve per cent more words')]),

"fig_b22_u04_p10_v12": dict(type='V12',
 title='Nine thousand four hundred words, and the hundred and eighty',
 sub='What the study found, what the note said, and where the two stopped matching.',
 alt='An infographic comparing a commissioned study with the note that summarised it, showing '
     'lengths, scopes, references and the sentences with no source.',
 span=['0', '9,400 words'], ticks=4,
 tick_labels=['0', '3,133', '6,267', '9,400'],
 bands=[dict(name='The paper', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='9,400 words, 112 references, 2 scopes',
        colour='#1F4E5F')]),
  dict(name='The note', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.02}, label='', colour='#A8372E')]),
  dict(name='What the finding is', type='events', items=[
   dict(at=0.18, label='62% at cabled berths', colour='#2E6F5E'),
   dict(at=0.62, label='8% across all 1,140 calls', colour='#C86B2B')]),
  dict(name='What the note says', type='events', items=[
   dict(at=0.22, label='"a significant reduction"', colour='#A8372E'),
   dict(at=0.70, label='three sentences with no source', colour='#A8372E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='the note is 1.9 per cent of the paper and carries no scope at all'),
   dict(at=0.58, label='two commas in the note claim five berths that are not cabled')])]),

"fig_b22_u04_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four ways of publishing one study',
 sub='Two hundred readers, the same finding, four publication formats.',
 alt='A bar chart comparing four publication formats on the share of readers who could state the '
     'finding and the share of claims traceable to a paragraph of the paper.',
 labels=['summary only', 'paper only', 'both, uncited', 'both, cited'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='stated the finding (%)', values=[64, 19, 58, 71], colour='#2E6F5E'),
   dict(name='claims traceable (%)', values=[0, 100, 41, 96], colour='#1F4E5F')],
 note='Publishing the paper alone is unimpeachable and unread. Citing the summary is the only '
      'format where both numbers are high, and it is also the only one that works on the writer.',
 warning='The "both, uncited" column is what most organisations already do, and its traceability '
         'figure of forty-one per cent is a measure of how many summary sentences happen to '
         'survive a check nobody performs.'),
}
