"""B2.2 Unit 5 - That He Be Present - ten figures, as data."""
FIGURES = {
"fig_b22_u05_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The board room, ten o\'clock',
 sub='Twelve things to find. Two say the same requirement and one is seventy-seven years old.',
 alt='A port authority board room with the 1948 regulation open at article 9, the 2019 amendment '
     'loose inside it, a quorum sheet and an empty chair with a nameplate.',
 sky='#D2D8DA', ground='#8A8578', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#B0B2AC', cutaway=True,
     floor_labels=['the 1948 regulation, article 9', 'the 2019 amendment, loose inside it',
                   'the gavel'],
     label='the law'),
   dict(x=560, w=480, storeys=3, colour='#B8BAB4', cutaway=True,
     floor_labels=['the agenda, item four highlighted', 'the quorum sheet, seven of eleven',
                   'the minute book'],
     label='the table'),
   dict(x=1120, w=460, storeys=3, colour='#ADAFA9', cutaway=True,
     floor_labels=['the inspectorate\'s letter', 'the draft resolution, two-thirds',
                   'the screen'],
     label='the papers')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='10:00'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=210, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=250, y=700, h=92, skin=1, cloth=0, hair='grey', arm='point'),
   dict(x=350, y=700, h=88, skin=4, cloth=2, hair='short', arm='hold'),
   dict(x=660, y=700, h=86, skin=2, cloth=3, hair='bun', arm='folded'),
   dict(x=1250, y=700, h=86, skin=5, cloth=4, hair='cap', arm='hold'),
   dict(x=1350, y=700, h=86, skin=3, cloth=1, hair='long', arm='down')],
 names=[dict(x=250, t='the chair - the gavel is unused since 1996'),
   dict(x=350, t='Tomas - standards, and he counted the subjunctives'),
   dict(x=660, t='the empty chair, with a nameplate on it'),
   dict(x=1250, t='the jug of water and eleven glasses'),
   dict(x=1350, t='the vessel position, North Sea'),
   dict(x=520, t='the clock: ten o\'clock'),
   dict(x=1075, t='article 9, unamended since 1948'),
   dict(x=210, t='nine of eleven present, eight votes needed')],
 markers=[dict(x=250, y=570), dict(x=350, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=210, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b22_u05_p01_v02": dict(type='V2', height=820,
 title='One rule, in section',
 sub='Twelve words, and the layer each one lives on. Two of them are the same escape.',
 alt='A cutaway of a regulation in four layers, from what requires a thing through what releases '
     'you from it and who checks, to what the meeting itself does.',
 floors=[dict(was='what requires it', now='mandate · directive · stipulation · protocol',
     year='', fill='#EDF1EC'),
   dict(was='what releases you', now='derogation · exemption',
     year='', fill='#E8EEF0'),
   dict(was='who checks', now='compliance · inspectorate · accreditation',
     year='', fill='#F3EADA'),
   dict(was='what the room does', now='quorum · resolution · ratification',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Four words, and only one of them ever carries a date'),
   dict(at=0.38, text='One granted in advance, one granted after the fact'),
   dict(at=0.62, text='The layer that finds out whether the top layer was real'),
   dict(at=0.88, text='Three words, and all three are about who was in the room')]),

"fig_b22_u05_p02_v07": dict(type='V7', height=840,
 title='Item four, ten o\'clock',
 sub='Nine of eleven present. Eight votes needed. The harbourmaster is at sea.',
 alt='A board chair and a standards officer at a table with a 1948 regulation and a quorum sheet '
     'between them, each with two speech balloons and a thought balloon.',
 bg='#E2E4DF',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=1, cloth=0, hair='grey', arm='point', facing='right',
   label='the chair', role='the gavel has not been used since 1996',
   says=['It is essential that he be present.',
         'Be it resolved.'],
   thinks=['Nobody has tested this article since 1961.']),
  dict(x=1080, h=240, skin=4, cloth=2, hair='short', arm='hold', facing='left',
   label='Tomas', role='thirty-one subjunctives, six ever enforced',
   says=['Were he to attend remotely, the article would be satisfied.',
         'Far be it from me.'],
   thinks=['Twenty-five rules kept by accident for seventy-seven years.'])]),

"fig_b22_u05_p03_v09": dict(type='V9', kind='mirror', height=680,
 title='The form with no tense',
 sub='The same clause, twice. One of them agrees with its subject and one refuses to.',
 alt='Two sentence diagrams of the same subordinate clause, the first in the ordinary present '
     'and the second in the mandative subjunctive with the bare verb.',
 labels=['PRESENT', 'SUBJUNCTIVE'],
 between='no -s, no tense, no number: the form is about a state of affairs, not a moment',
 active=dict(parts=[dict(w=26, role='hidden', text='It is essential'),
   dict(w=14, role='action', text='that'),
   dict(w=16, role='agent', text='he'),
   dict(w=22, role='affected', text='is present')]),
 passive=dict(parts=[dict(w=26, role='hidden', text='It is essential'),
   dict(w=14, role='action', text='that'),
   dict(w=16, role='agent', text='he'),
   dict(w=22, role='affected', text='be present')])),

"fig_b22_u05_p04_v04": dict(type='V4', height=740,
 title='The same requirement, two regulations',
 sub='Article 9 of 1948 and the amendment of 2019, on the same shelf.',
 alt='Two regulation texts side by side, one using the subjunctive and one using shall, with '
     'their dates and the number of requirements each contains.',
 differences=6, prompt='Find the six. One of the two tells a reader what happens if they do not '
                       'comply. Which, and in how many words?',
 left=dict(label='article 9, 1948', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#9AA7AE'),
   dict(kind='gap', x=150, y=106, w=250, bh=24),
   dict(kind='block', x=150, y=72, w=200, bh=24, colour='#9AA7AE'),
   dict(kind='label', x=300, y=218,
        text='subjunctive · no consequence · no deputy · unamended',
        colour='#9AA7AE')]),
 right=dict(label='the 2019 amendment', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=240, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=72, w=230, bh=24, colour='#2E6F5E'),
   dict(kind='label', x=300, y=218,
        text='shall · a consequence · a deputy, in writing · 28 days',
        colour='#2E6F5E')])),

"fig_b22_u05_p05_v05": dict(type='V5', height=1060,
 title='Article 9, every requirement weighed',
 sub='Two hundred and fourteen requirements, thirty-one subjunctives, six ever enforced.',
 alt='A port regulation annotated to show which of its requirements use the subjunctive, which '
     'have been enforced, and which were quietly rewritten in a later amendment.',
 rows=[dict(t='org', text='PORT REGULATION 1948  -  ARTICLE 9  -  WITH 2019 AMENDMENT'),
   dict(t='para', text='1948: "It is essential that the harbourmaster be present at any meeting '
     'at which an inspection regime is ratified. It is advisable that notice be given."'),
   dict(t='para', text='2019: "The harbourmaster shall attend or shall appoint a deputy in '
     'writing. Failing attendance or appointment, the ratification shall be void."'),
   dict(t='rule'),
   dict(t='grid', cols=['IN THE REGULATION', 'COUNT', 'ENFORCED'],
     data=[['REQUIREMENTS IN TOTAL', '214', '--'],
           ['USING THE SUBJUNCTIVE', '31', '6'],
           ['ALSO IN THE 2019 TEXT', '4', '4'],
           ['NEVER TESTED', '25', '0'],
           ['DEROGATIONS SOUGHT SINCE 1961', '0', '--'],
           ['ARTICLE 9: REQUIREMENTS', '2', '0'],
           ['ARTICLE 9: CONSEQUENCES STATED', '0', '--'],
           ['2019: CONSEQUENCES STATED', '1', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH SENTENCE ACTUALLY REQUIRES'),
   dict(t='kv', k='"it is essential that ... be"', v='absolute in tone, untested in fact',
        mono=False),
   dict(t='kv', k='"it is advisable that ... be"', v='same verb form, no force at all',
        mono=False),
   dict(t='kv', k='"shall attend"', v='written-in, with a consequence', mono=False),
   dict(t='kv', k='"shall be void"', v='the only sentence here a court could use', mono=False),
   dict(t='rule'),
   dict(t='para', text='Two sentences in article 9 share a verb form and share nothing else. '
     'The 2019 text uses one verb form for both and says which is which.')],
 callouts=[dict(at=0.08, text='Two requirements, one verb form, two different forces'),
   dict(at=0.24, text='A consequence, in eleven words, and article 9 has none'),
   dict(at=0.52, text='Twenty-five rules kept by accident for seventy-seven years'),
   dict(at=0.82, text='The subjunctive marks the register and not the force'),
   dict(at=0.96, text='Only the last line could be used by anybody')]),

"fig_b22_u05_p07_v10": dict(type='V10', kind='elision', height=660,
 title='A formula is one word long',
 sub='Written in full above, said at a third of the length below.',
 alt='Five procedural formulae written out and then transcribed as they are said at speed, with '
     'their single stress marked.',
 pairs=[
  dict(written='be it resolved', spoken='biː ɪt rɪˈzɒlvd', dropped='',
       note='one stress, at the end'),
  dict(written='the chair rules that', spoken='ðə ˈtʃeə ruːlz ðət', dropped='',
       note='one stress, at the front'),
  dict(written='it is essential that', spoken='ɪts ɪˈsenʃl̩ ðət', dropped='',
       note='four words, two syllables of content'),
  dict(written='far be it from me', spoken='ˈfɑː biːt frəm ˈmiː', dropped='',
       note='and what follows is always exactly that'),
  dict(written='come what may', spoken='kʌm wɒt ˈmeɪ', dropped='',
       note='three words, one beat, no tense anywhere')]),

"fig_b22_u05_p09_v05": dict(type='V5', height=940,
 title='Four sentences that start formal and do not stay',
 sub='Formal English learned as vocabulary and used as grammar.',
 alt='A study sheet of learner sentences showing a formal opening, the point at which the '
     'register drops, and the whole formula that would have held it.',
 rows=[dict(t='org', text='STUDY FILE  -  THE FORMALITY YOU CAN READ AND NOT WRITE'),
   dict(t='para', text='You recognise all of this and produce it in two registers at once. The '
     'result reads as translated, which it usually is not.'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT WAS WRITTEN', 'WHAT DROPPED IT', 'THE WHOLE FORMULA'],
     data=[['IT IS ESSENTIAL THAT HE COMES', 'THE -S', 'THAT HE COME'],
           ['WE RECOMMEND THAT HE WILL GO', 'THE WILL', 'THAT HE GO'],
           ['IF HE WOULD ATTEND, IT IS OK', 'WOULD + OK', 'WERE HE TO ATTEND'],
           ['IT IS NECESSARY HE IS THERE', 'NO THAT', 'THAT HE BE THERE'],
           ['...AND ANYWAY WE THINK SO', 'ANYWAY', 'IT IS SUBMITTED THAT']]),
   dict(t='rule'),
   dict(t='head', text='WHY EIGHT FORMULAE AND NOT A RULE'),
   dict(t='kv', k='a rule has to be applied', v='and application is slow under pressure',
        mono=False),
   dict(t='kv', k='a formula is retrieved', v='whole, with its verb form attached', mono=False),
   dict(t='kv', k='eight is enough', v='for a minute, a letter and a submission', mono=False),
   dict(t='kv', k='the test', v='can you say it without pausing before the verb?', mono=False),
   dict(t='rule'),
   dict(t='para', text='Translate three requirements from a real regulation in your own language '
     'and mark each one absolute, written-in or recommended.')],
 callouts=[dict(at=0.12, text='Nothing here is unintelligible. All of it is mixed'),
   dict(at=0.44, text='Five sentences, and four of them fail at the verb'),
   dict(at=0.76, text='A formula is retrieved; a rule has to be applied'),
   dict(at=0.95, text='The pause before the verb is the whole diagnosis')]),

"fig_b22_u05_p10_v12": dict(type='V12',
 title='Two hundred and fourteen requirements, six enforced',
 sub='What the regulation says, what has ever been tested, and what the amendment rewrote.',
 alt='An infographic of a port regulation showing its requirements, how many use the '
     'subjunctive, how many have been enforced and how many were rewritten in 2019.',
 span=['0', '214 requirements'], ticks=4,
 tick_labels=['0', '71', '143', '214'],
 bands=[dict(name='All requirements', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='214, in a regulation of 1948', colour='#9AA7AE')]),
  dict(name='Using the subjunctive', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.145}, label='31', colour='#C86B2B')]),
  dict(name='Ever enforced', type='events', items=[
   dict(at=0.12, label='six, of which four are also in the 2019 text', colour='#A8372E'),
   dict(at=0.62, label='never tested: 25', colour='#A8372E')]),
  dict(name='Article 9', type='events', items=[
   dict(at=0.16, label='two requirements, no consequence', colour='#D9A441'),
   dict(at=0.74, label='derogations sought since 1961: none', colour='#9AA7AE')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='the subjunctive marks the register and not the force'),
   dict(at=0.56, label='twenty-five rules kept by accident for seventy-seven years')])]),

"fig_b22_u05_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four ways of writing a requirement',
 sub='Two hundred readers shown the same obligation in four forms.',
 alt='A bar chart comparing four ways of writing a requirement on whether readers judged it '
     'mandatory correctly and how many such requirements have ever been enforced.',
 labels=['subjunctive', 'shall', 'must', 'plain + consequence'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='judged mandatory correctly (%)', values=[34, 61, 78, 93], colour='#2E6F5E'),
   dict(name='ever enforced (%)', values=[19, 44, 52, 81], colour='#A8372E')],
 note='The two series move together, which is the finding: a requirement people cannot classify '
      'is a requirement nobody enforces, and the form of words decides both.',
 warning='The subjunctive column is not a verdict on the form. It is a verdict on using one verb '
         'form for both requirements and recommendations, which is what article 9 does twice in '
         'two sentences.'),
}
