"""B2.2 Unit 6 - Ninety-Four Posts and Thirty-Two Injuries - ten figures, as data."""
FIGURES = {
"fig_b22_u06_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The committee room, twenty to two',
 sub='Twelve things to find. Two count the same programme and reach opposite conclusions.',
 alt='A port ethics committee room with an injury board, a staffing schedule, two studies and a '
     'window onto an automated yard with an unmanned crane.',
 sky='#D3D9DA', ground='#878C8A', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#AFB3B1', cutaway=True,
     floor_labels=['the injury board, 41 down to 9', 'the staffing schedule, 94 ringed',
                   'the retraining list'],
     label='the numbers'),
   dict(x=560, w=480, storeys=3, colour='#B7BBB9', cutaway=True,
     floor_labels=['the port\'s study, 22 per cent', 'the union\'s counter-study, 9 per cent',
                   'the draft position'],
     label='the two studies'),
   dict(x=1120, w=460, storeys=3, colour='#ACB0AE', cutaway=True,
     floor_labels=['the terms of reference', 'the 1991 quay gang, framed',
                   'the boots'],
     label='the wall')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='13:40'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=210, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=250, y=700, h=92, skin=2, cloth=0, hair='bun', arm='point'),
   dict(x=350, y=700, h=88, skin=1, cloth=3, hair='grey', arm='folded'),
   dict(x=660, y=700, h=86, skin=5, cloth=2, hair='cap', arm='hold'),
   dict(x=1250, y=700, h=86, skin=4, cloth=4, hair='short', arm='hold'),
   dict(x=1350, y=700, h=86, skin=3, cloth=1, hair='long', arm='down')],
 names=[dict(x=250, t='the committee chair, with the draft'),
   dict(x=350, t='Piet - thirty-four years, two men carried off'),
   dict(x=660, t='the crane with nobody in the cab'),
   dict(x=1250, t='the box of safety boots, unopened'),
   dict(x=1350, t='the automated yard, beyond the window'),
   dict(x=520, t='the clock: twenty to two'),
   dict(x=1075, t='94 posts of 310, 61 placed'),
   dict(x=210, t='32 fewer serious injuries a year')],
 markers=[dict(x=250, y=570), dict(x=350, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=210, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b22_u06_p01_v02": dict(type='V2', height=820,
 title='One trade-off, in section',
 sub='Twelve words, and the layer each one lives on. One of them is in nobody\'s accounts.',
 alt='A cutaway of an ethical trade-off in four layers, from the shape of the problem through '
     'who carries the cost and what is done about it, to who watches.',
 floors=[dict(was='the shape of the problem', now='trade-off · dilemma · proportionality',
     year='', fill='#EDF1EC'),
   dict(was='who carries the cost', now='externality · equity · welfare',
     year='', fill='#E8EEF0'),
   dict(was='what you do about it', now='mitigation · precaution · remediation · stewardship',
     year='', fill='#F3EADA'),
   dict(was='who watches', now='scrutiny · transparency',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Three words for the thing nobody in the room disputes'),
   dict(at=0.38, text='An externality is entirely real and appears in no accounts'),
   dict(at=0.62, text='Four verbs made into nouns, and only one happens before the harm'),
   dict(at=0.88, text='Two words, and the only layer that is not inside the organisation')]),

"fig_b22_u06_p02_v07": dict(type='V7', height=840,
 title='Twenty to two, and the draft is four lines',
 sub='She has the injury figures. He has carried two men off this quay.',
 alt='An ethics committee chair and a long-serving stevedore at a table with two studies and a '
     'four-line draft between them, each with two speech balloons and a thought balloon.',
 bg='#E2E5E3',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=2, cloth=0, hair='bun', arm='point', facing='right',
   label='the chair', role='forty-one per million hours down to nine',
   says=['While the programme costs 94 posts, injuries have fallen.',
         'Granted, the cost is concentrated.'],
   thinks=['Thirty-two fewer serious injuries a year.']),
  dict(x=1080, h=240, skin=1, cloth=3, hair='grey', arm='folded', facing='left',
   label='Piet', role='thirty-four years on the quay',
   says=['For all the safety gain, ninety-four posts go.',
         'That is in the wrong clause.'],
   thinks=['Nobody expects me to argue with the injury figures.'])]),

"fig_b22_u06_p03_v09": dict(type='V9', kind='weight', height=540,
 title='Which half the reader is left holding',
 sub='Identical information, two orders, and the main clause is what survives the sentence.',
 alt='A proportional bar showing a concessive clause and a main clause, with the share of the '
     'sentence each occupies and the fact the reader keeps.',
 parts=[dict(w=16, role='the connector', text='While', colour='#9AA7AE'),
   dict(w=34, role='conceded - the reader lets it go', text='the programme costs 94 posts',
        colour='#C86B2B'),
   dict(w=50, role='the main clause - this is what they keep',
        text='injuries have fallen by 78 per cent', colour='#2E6F5E')],
 note='Reverse the two and the information is identical and the reader walks away with the '
      'opposite fact. Choosing which half goes in the subordinate clause is a moral choice '
      'before it is a grammatical one.'),

"fig_b22_u06_p04_v04": dict(type='V4', height=740,
 title='The same two facts, two positions',
 sub='One of them was quoted by the union unaltered. The other was not.',
 alt='Two drafts of a committee position side by side, one with the job losses in the '
     'subordinate clause and one with them in the main clause.',
 differences=6, prompt='Find the six. One draft leaves the reader holding the job losses. Which, '
                       'and which connector does the work?',
 left=dict(label='draft one', art=[
   dict(kind='block', x=150, y=140, w=200, bh=24, colour='#9AA7AE'),
   dict(kind='block', x=150, y=106, w=260, bh=24, colour='#2E6F5E'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='"while ... regrettably" · cost subordinate · 0 numbers in the concession',
        colour='#9AA7AE')]),
 right=dict(label='as published', art=[
   dict(kind='block', x=150, y=140, w=140, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=260, bh=24, colour='#C86B2B'),
   dict(kind='block', x=150, y=72, w=230, bh=24, colour='#C86B2B'),
   dict(kind='label', x=300, y=218,
        text='"for all the gain" · cost in the main clause · 33 named as a number',
        colour='#C86B2B')])),

"fig_b22_u06_p05_v05": dict(type='V5', height=1100,
 title='Four drafts, and which half each one keeps',
 sub='The same two facts, four orders, and one concession that costs the port nothing.',
 alt='Four drafts of a committee position annotated to show the connector used, what follows it, '
     'and which fact ends up in the main clause.',
 rows=[dict(t='org', text='ETHICS COMMITTEE  -  STANDING POSITION  -  DRAFTS 1 TO 4'),
   dict(t='para', text='1. "While the programme regrettably entails some reduction in headcount, '
     'the safety benefits are substantial."'),
   dict(t='para', text='2. "The safety benefits are substantial, albeit at a cost in headcount."'),
   dict(t='para', text='3. "For all the safety gain, ninety-four posts go, of which the scheme '
     'places sixty-one."'),
   dict(t='para', text='4. "Granted, the safety gain is real. Nonetheless, thirty-three people '
     'will not be placed."'),
   dict(t='rule'),
   dict(t='grid', cols=['DRAFT', 'WHAT FOLLOWS THE CONNECTOR', 'READER KEEPS'],
     data=[['1  WHILE', 'A FULL CLAUSE', 'THE SAFETY GAIN'],
           ['2  ALBEIT', 'A PHRASE, NO VERB', 'THE SAFETY GAIN'],
           ['3  FOR ALL', 'A NOUN PHRASE', 'THE 94 POSTS'],
           ['4  GRANTED ... NONETHELESS', 'TWO SENTENCES', 'THE 33'],
           ['NUMBERS IN THE CONCESSION, 1', '0', '--'],
           ['NUMBERS IN THE CONCESSION, 3', '2', '--'],
           ['QUOTED BY THE UNION', 'DRAFT 3', '--'],
           ['RETRAINING TAKE-UP AFTER', '51% TO 84%', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH CONNECTOR TAKES'),
   dict(t='kv', k='while / whilst', v='a full clause, with a subject and a verb', mono=False),
   dict(t='kv', k='albeit', v='a phrase only - never a clause', mono=False),
   dict(t='kv', k='for all', v='a noun phrase, and it concedes a quantity', mono=False),
   dict(t='kv', k='notwithstanding', v='a noun phrase, before or after it', mono=False),
   dict(t='rule'),
   dict(t='para', text='Draft 1 concedes "some reduction in headcount", which has no number in '
     'it and therefore costs the port nothing to say.')],
 callouts=[dict(at=0.08, text='A concession with no number is not a concession'),
   dict(at=0.20, text='Albeit takes a phrase, and a learner writing albeit it has been caught'),
   dict(at=0.30, text='Two numbers inside the concession, and the cost in the main clause'),
   dict(at=0.62, text='Draft 3 is the one the other side quoted unaltered'),
   dict(at=0.95, text='The concession that costs you something is the one believed')]),

"fig_b22_u06_p07_v10": dict(type='V10', kind='pitch', height=860,
 title='The concession rises; the position falls',
 sub='A rising concession is a run-up. A falling one is finished.',
 alt='Four pitch contours over concessive sentences showing a rising subordinate clause, a '
     'falling main clause, and the difference between a finished and an unfinished concession.',
 contours=[
  dict(text='While the cost is real, the case stands.',
       points=[0.3, 0.5, 0.8, 0.9, 0.4, 0.0, -0.8],
       meaning='the rise promises a main clause'),
  dict(text='Granted.',
       points=[0.5, 0.2, -0.2, -0.5, -0.7, -0.8, -0.9],
       meaning='finished: nothing is coming'),
  dict(text='Granted...',
       points=[0.2, 0.3, 0.4, 0.5, 0.7, 0.85, 0.95],
       meaning='a run-up: everybody waits for the but'),
  dict(text='I accept that - up to a point.',
       points=[0.3, 0.1, -0.2, 0.1, 0.4, 0.7, 0.9],
       meaning='accepted, and here comes the limit')]),

"fig_b22_u06_p09_v05": dict(type='V5', height=940,
 title='Four concessions, all of them with but',
 sub='The right move, made four times in a paragraph, until nobody can find the position.',
 alt='A study sheet of learner paragraphs that concede repeatedly with but, showing what the '
     'listener hears and the single structured concession that would replace them.',
 rows=[dict(t='org', text='STUDY FILE  -  THE CONCESSION YOU MAKE BY ACCIDENT'),
   dict(t='para', text='Conceding with but is correct and puts the halves the right way round. '
     'Doing it four times in a paragraph leaves eight halves and no position.'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT WAS SAID', 'BUTS', 'WHAT WOULD REPLACE IT'],
     data=[['GOOD BUT EXPENSIVE BUT IT WORKS', '2', 'ALBEIT EXPENSIVE'],
           ['I AGREE BUT ALSO I DISAGREE', '1', 'UP TO A POINT'],
           ['IT IS TRUE BUT NOT ALWAYS TRUE', '1', 'WHILE IT IS TRUE'],
           ['HE IS RIGHT BUT SO IS SHE', '1', 'BOTH THINGS ARE TRUE'],
           ['IN A 90-SECOND TURN', '7', 'THREE, ONE EACH']]),
   dict(t='rule'),
   dict(t='head', text='THE THREE STRUCTURES WORTH OWNING'),
   dict(t='kv', k='although / while', v='a clause: the full, writeable concession', mono=False),
   dict(t='kv', k='albeit', v='a phrase: the cheapest concession in English', mono=False),
   dict(t='kv', k='granted / admittedly', v='a whole move in one word, spoken', mono=False),
   dict(t='kv', k='up to a point', v='concede the fact, refuse the conclusion', mono=False),
   dict(t='rule'),
   dict(t='para', text='Concede the same real objection three times in three structures, and say '
     'which one you would write and which you would say.')],
 callouts=[dict(at=0.12, text='Nothing here is wrong. All of it is the same move'),
   dict(at=0.44, text='Seven buts in ninety seconds, and no position survives'),
   dict(at=0.76, text='Three structures, used once each, is the whole fix'),
   dict(at=0.95, text='The last one concedes the fact and refuses the conclusion')]),

"fig_b22_u06_p10_v12": dict(type='V12',
 title='Three hundred and ten posts, forty-one injuries',
 sub='What the programme costs, what it saves, and who ends up carrying each.',
 alt='An infographic of a port automation programme showing posts removed, posts placed, injuries '
     'prevented and the two productivity studies.',
 span=['0', '310 posts'], ticks=4,
 tick_labels=['0', '103', '207', '310'],
 bands=[dict(name='The workforce', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='310 stevedore posts', colour='#9AA7AE')]),
  dict(name='What the programme does', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.303}, label='94 posts go', colour='#A8372E'),
   dict(**{'from': 0.32, 'to': 0.52}, label='61 placed by the scheme', colour='#2E6F5E')]),
  dict(name='Who is not placed', type='events', items=[
   dict(at=0.14, label='33, named in the scheme\'s own documents', colour='#A8372E')]),
  dict(name='Injuries, per million hours', type='events', items=[
   dict(at=0.22, label='41 before', colour='#A8372E'),
   dict(at=0.74, label='9 after - about 32 fewer a year', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='the people not injured next year are the people leaving this year'),
   dict(at=0.58, label='both studies are correct about what they measured')])]),

"fig_b22_u06_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four ways of stating one position',
 sub='Four hundred readers, the same two facts, four orders.',
 alt='A bar chart comparing four ways of stating a contested position on whether readers could '
     'state both halves and whether they judged the organisation honest.',
 labels=['safety only', 'jobs only', 'jobs then safety', 'one concessive sentence'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='stated both halves (%)', values=[12, 14, 58, 84], colour='#2E6F5E'),
   dict(name='judged the port honest (%)', values=[31, 38, 61, 72], colour='#C86B2B')],
 note='Stating one fact well produces readers who know one fact. The concessive sentence is the '
      'only version where most readers can state the cost and the gain in the same breath.',
 warning='Honesty here is a judgement, not a measurement: it rises with the second series because '
         'readers who can state both halves conclude that somebody told them both, which is a '
         'different thing from its being true.'),
}
