"""B2.2 Unit 7 - Twenty-Four Words at a Gate - ten figures, as data."""
FIGURES = {
"fig_b22_u07_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The east gate, ten to six',
 sub='Twelve things to find. Two give the same instruction and one of them is read.',
 alt='A port gate kiosk lane before dawn with the instruction screen, a redesigned screen, a '
     'queue of trucks and a card taped to the kiosk by a driver.',
 sky='#3B4752', ground='#6A7074', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#8A9196', cutaway=True,
     floor_labels=['the kiosk screen, in full', 'the redesigned screen, four words',
                   'the taped card'],
     label='the kiosk'),
   dict(x=560, w=480, storeys=3, colour='#929AA0', cutaway=True,
     floor_labels=['the error log, fourteen per cent', 'the six-screen flow, printed out',
                   'the help button'],
     label='the office'),
   dict(x=1120, w=460, storeys=3, colour='#888F94', cutaway=True,
     floor_labels=['a transport order, on a clipboard', 'the lane camera',
                   'the queue'],
     label='the lane')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='05:50'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='box', x=210, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=250, y=700, h=92, skin=5, cloth=3, hair='cap', arm='point'),
   dict(x=350, y=700, h=88, skin=2, cloth=0, hair='bun', arm='hold'),
   dict(x=660, y=700, h=86, skin=1, cloth=2, hair='short', arm='folded'),
   dict(x=1250, y=700, h=86, skin=4, cloth=4, hair='long', arm='hold'),
   dict(x=1350, y=700, h=86, skin=3, cloth=1, hair='grey', arm='down')],
 names=[dict(x=250, t='the driver, whose hand is on the keypad'),
   dict(x=350, t='the designer, who has seen the card'),
   dict(x=660, t='the prefix sticker, added by a driver'),
   dict(x=1250, t='the trucks, back to the roundabout'),
   dict(x=1350, t='the clipboard, with the transport order'),
   dict(x=520, t='the clock: ten to six'),
   dict(x=1075, t='screen three: 14% error rate'),
   dict(x=210, t='2,900 trucks a day, six screens each')],
 markers=[dict(x=250, y=570), dict(x=350, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=210, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b22_u07_p01_v02": dict(type='V2', height=820,
 title='One screen, in section',
 sub='Twelve words, and the layer each one lives on. One of them measures the other eleven.',
 alt='A cutaway of an interface in four layers, from what the user is trying to do through what '
     'the screen offers and how easy it is to read, to what comes back.',
 floors=[dict(was='what the user is doing', now='workflow · navigation · onboarding',
     year='', fill='#EDF1EC'),
   dict(was='what the screen offers', now='interface · affordance · prompt · default',
     year='', fill='#E8EEF0'),
   dict(was='how easy it is to see', now='hierarchy · legibility · discoverability',
     year='', fill='#F3EADA'),
   dict(was='what comes back', now='friction · confirmation',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Three words, and the driver is thinking about none of them'),
   dict(at=0.38, text='A default is what happens when nobody reads anything'),
   dict(at=0.62, text='Three words about whether the layer above can be seen at all'),
   dict(at=0.88, text='Friction is the measure of how badly the other eleven are doing')]),

"fig_b22_u07_p02_v07": dict(type='V7', height=840,
 title='Ten to six at the east gate',
 sub='He has a queue behind him. She designed the screen.',
 alt='A driver at a kiosk and an interface designer with a printed screen flow between them, '
     'each with two speech balloons and a thought balloon.',
 bg='#DCE1E3',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=5, cloth=3, hair='cap', arm='point', facing='right',
   label='the driver', role='four hundred trucks a day leave this queue',
   says=['Two letters first.', 'Nothing told me that.'],
   thinks=['By the fifth word the gate arm has started to move.']),
  dict(x=1080, h=240, skin=2, cloth=0, hair='bun', arm='hold', facing='left',
   label='the designer', role='six screens, twenty-four words on screen three',
   says=['It ends on the prefix, which is the point.',
         'Where do I click?'],
   thinks=['The card is four words and it is at the top.'])]),

"fig_b22_u07_p03_v09": dict(type='V9', kind='scope', height=560,
 title='The two positions that do the work',
 sub='The first position says where you are. The last one says what to do.',
 alt='One instruction drawn as chunks with brackets marking the theme at the front, the middle '
     'and the focus position at the end.',
 words=['Including the prefix,', 'enter', 'the booking', 'reference', 'in', 'FULL'],
 focus=[0, 5],
 brackets=[dict(**{'from': 0, 'to': 0}, lane=0, colour='#C86B2B',
     label='THEME: where the reader starts'),
   dict(**{'from': 1, 'to': 4}, lane=0, colour='#9AA7AE', label='the middle: least attended to'),
   dict(**{'from': 5, 'to': 5}, lane=0, colour='#1F4E5F', label='FOCUS: the last fall'),
   dict(**{'from': 0, 'to': 5}, lane=1, colour='#A8372E',
     label='fronted and ended on different things: the sentence promises one point and delivers another')]),

"fig_b22_u07_p04_v04": dict(type='V4', height=740,
 title='Screen three, two versions',
 sub='One of them has a fourteen per cent error rate. One of them is a card taped to the kiosk.',
 alt='Two versions of a kiosk instruction screen side by side, one a single long sentence and '
     'one split into two short ones with the critical element last.',
 differences=6, prompt='Find the six. One version ends its first sentence on the thing the '
                       'driver gets wrong. Which, and in how many words?',
 left=dict(label='as installed', art=[
   dict(kind='block', x=150, y=140, w=270, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=260, bh=24, colour='#A8372E'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='24 words · 1 sentence · 3 falls · 14% errors',
        colour='#A8372E')]),
 right=dict(label='as rewritten', art=[
   dict(kind='block', x=150, y=140, w=120, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=106, w=150, bh=24, colour='#2E6F5E'),
   dict(kind='block', x=150, y=72, w=230, bh=24, colour='#9AA7AE'),
   dict(kind='label', x=300, y=218,
        text='9 words · 2 sentences · 2 falls · 3% errors',
        colour='#2E6F5E')])),

"fig_b22_u07_p05_v05": dict(type='V5', height=1100,
 title='Six screens, and where each one ends',
 sub='The critical action on each, and the word the driver is left holding.',
 alt='A six-screen kiosk flow annotated with the critical action on each screen, the last word '
     'of each instruction and the error rate.',
 rows=[dict(t='org', text='EAST GATE KIOSK  -  SIX SCREENS  -  2,900 ARRIVALS A DAY'),
   dict(t='para', text='SCREEN 3: "Please ensure that the booking reference, which can be found '
     'on your transport order, is entered in full including the prefix."'),
   dict(t='para', text='THE CARD, TAPED TO THE SAME KIOSK, IN MARKER PEN: "2 LETTERS FIRST."'),
   dict(t='rule'),
   dict(t='grid', cols=['SCREEN', 'ENDS ON', 'ERROR RATE'],
     data=[['1  VEHICLE PLATE', 'PLATE', '1%'],
           ['2  HAULIER CODE', 'SYSTEM', '4%'],
           ['3  BOOKING REFERENCE', 'PREFIX', '14%'],
           ['4  TRAILER NUMBER', 'CAB', '2%'],
           ['5  CONFIRMATION', 'DISPLAYED', '--'],
           ['6  LANE ALLOCATION', 'ALLOCATED', '--'],
           ['THE TAPED CARD', 'FIRST', '3%'],
           ['WORDS ON SCREEN 3', '24', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHY SCREEN 3 FAILS THOUGH IT ENDS ON THE POINT'),
   dict(t='kv', k='three falls, not one', v='three corrections, and only one applies', mono=False),
   dict(t='kv', k='the heavy clause', v='sits in the middle, where nobody reads', mono=False),
   dict(t='kv', k='twenty-four words', v='the gate arm moves at about the fifth', mono=False),
   dict(t='kv', k='the card: four words', v='at the top, where the hand already is', mono=False),
   dict(t='rule'),
   dict(t='para', text='Screens 5 and 6 end on verbs that describe what the system does. Nobody '
     'has ever measured those two, because nothing visibly goes wrong on them.')],
 callouts=[dict(at=0.08, text='Twenty-four words, and the first five are a politeness'),
   dict(at=0.18, text='Four words, in marker pen, with a three per cent error rate'),
   dict(at=0.46, text='One screen in six carries three quarters of the errors'),
   dict(at=0.80, text='Ending on the right word is not enough if you end three times'),
   dict(at=0.95, text='The two unmeasured screens are the two with no visible failure')]),

"fig_b22_u07_p07_v10": dict(type='V10', kind='stress', height=580,
 title='One fall, and it names the error',
 sub='The last stressed word is the mistake you are correcting.',
 alt='One instruction drawn four times as beats with the nuclear stress in a different place and '
     'the error each placement corrects.',
 items=[
  dict(syllables=['en-ter', 'the', 'ref', 'in', 'FULL'], strong=[4],
       note='somebody entered part of it'),
  dict(syllables=['en-ter', 'the', 'REF', 'in', 'full'], strong=[2],
       note='somebody entered something else'),
  dict(syllables=['two', 'let-ters', 'FIRST'], strong=[2],
       note='three words, one fall, hand already there'),
  dict(syllables=['please', 'en-sure', 'that', 'the', 'REF'], strong=[4],
       note='five words before the instruction starts')]),

"fig_b22_u07_p09_v05": dict(type='V5', height=940,
 title='Five sentences that end on nothing',
 sub='A filler at the end occupies the one position a listener is attending to.',
 alt='A study sheet of learner sentences ending in fillers, what the listener hears, and the '
     'same sentence ending on its last real item.',
 rows=[dict(t='org', text='STUDY FILE  -  THE SENTENCE THAT ENDS ON NOTHING'),
   dict(t='para', text='Every one of these is understandable. Every one of them spends the final '
     'position, which is the only position a listener reliably keeps.'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT WAS SAID', 'ENDS ON', 'WHAT THEY KEPT'],
     data=[['REPORTS, PLANNING AND SO ON', 'SO ON', 'NOTHING'],
           ['IT IS QUICK, EASY, THINGS LIKE THAT', 'THAT', 'NOTHING'],
           ['WE MET ON TUESDAY OR SOMETHING', 'SOMETHING', 'NOTHING'],
           ['I STUDY LAW, ECONOMICS, ETC', 'ETC', 'NOTHING'],
           ['WE MET ON TUESDAY', 'TUESDAY', 'TUESDAY']]),
   dict(t='rule'),
   dict(t='head', text='WHAT THE FINAL POSITION IS FOR'),
   dict(t='kv', k='the listener keeps it', v='whatever it is', mono=False),
   dict(t='kv', k='the voice falls there', v='and a fall marks what is new', mono=False),
   dict(t='kv', k='a filler is not new', v='so the fall marks nothing', mono=False),
   dict(t='kv', k='the fix', v='end on the last real item, and stop', mono=False),
   dict(t='rule'),
   dict(t='para', text='Write six sentences about your work and underline the last word of each. '
     'Ask somebody to guess the topic from the six words alone.')],
 callouts=[dict(at=0.12, text='Nothing here is wrong. Four of the five end on nothing'),
   dict(at=0.44, text='The fifth is the same sentence with three words removed'),
   dict(at=0.74, text='A fall marks what is new, and a filler is never new'),
   dict(at=0.95, text='Six last words should read like a summary')]),

"fig_b22_u07_p10_v12": dict(type='V12',
 title='Two thousand nine hundred trucks, six screens',
 sub='Where the errors are, what the instruction says, and what one driver did about it.',
 alt='An infographic of a gate kiosk showing arrivals per day, the error rate on each screen, '
     'the length of the instruction and the effect of the taped card.',
 span=['0', '2,900 arrivals'], ticks=4,
 tick_labels=['0', '967', '1,933', '2,900'],
 bands=[dict(name='Arrivals a day', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='2,900, six screens each', colour='#9AA7AE')]),
  dict(name='Errors on screen 3', type='bars', items=[
   dict(**{'from': 0.0, 'to': 0.14}, label='14% - about 400 trucks', colour='#A8372E')]),
  dict(name='Where the sentence falls', type='events', items=[
   dict(at=0.18, label='fall 1: reference', colour='#9AA7AE'),
   dict(at=0.50, label='fall 2: order', colour='#9AA7AE'),
   dict(at=0.82, label='fall 3: prefix - the only instruction', colour='#A8372E')]),
  dict(name='After the card', type='events', items=[
   dict(at=0.12, label='errors: 3%', colour='#2E6F5E'),
   dict(at=0.66, label='line two read: 4% to 61%', colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='one screen in six carries three quarters of the errors'),
   dict(at=0.58, label='four words at the top beat twenty-four words on the screen')])]),

"fig_b22_u07_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four instruction styles at one kiosk',
 sub='Four weeks each, same lane, same drivers, same booking system.',
 alt='A bar chart comparing four instruction styles on the error rate at the kiosk and the share '
     'of drivers observed reading the second line.',
 labels=['one long sentence', 'action first', 'action first + end-weight', 'bullets'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='error rate (%)', values=[14, 6, 3, 8], colour='#A8372E'),
   dict(name='read line two (%)', values=[4, 22, 61, 31], colour='#2E6F5E')],
 note='Putting the action first halves the errors. Ending the first sentence where it should end '
      'halves them again and multiplies second-line reading by fifteen.',
 warning='Bullets perform worse than the sentence that uses them, which is the result nobody '
         'expects: four bullets are four first positions and no last one, so nothing in the set '
         'carries a final fall.'),
}
