"""B2.2 Unit 8 - One Word Changed - ten figures, as data."""
FIGURES = {
"fig_b22_u08_p00_v01": dict(type='V1', height=900, storey_h=130,
 title='The hearing room, quarter past eleven',
 sub='Twelve things to find. Two contain the same sentence and one word is different.',
 alt='A port inquiry room with a transcript of a hundred and eighteen pages, a draft report, a '
     'recorder still running and a redacted page with three lines blacked out.',
 sky='#D1D4D8', ground='#8A857C', ground_line=700,
 buildings=[dict(x=20, w=460, storeys=3, colour='#AFAEA8', cutaway=True,
     floor_labels=['the transcript, 118 pages', 'page 61, flagged',
                   'the recorder'],
     label='the record'),
   dict(x=560, w=480, storeys=3, colour='#B6B5AF', cutaway=True,
     floor_labels=['the inquiry report, draft', 'the witness list, fourteen names',
                   'the chair\'s notebook'],
     label='the inquiry'),
   dict(x=1120, w=460, storeys=3, colour='#ABAAA4', cutaway=True,
     floor_labels=['the deposition folder', 'a redacted page, three lines blacked',
                   'the exhibits'],
     label='the file')],
 props=[dict(kind='sign', x=520, y=700, s=.8, text='11:15'),
   dict(kind='table', x=800, y=700, s=1.8), dict(kind='chair', x=740, y=700, s=1.1),
   dict(kind='cup', x=880, y=662, s=1.3),
   dict(kind='box', x=210, y=700, s=1.0), dict(kind='crate', x=1170, y=700, s=1.0),
   dict(kind='hoarding', x=1075, y=700, s=.7, w=150, notice=True)],
 people=[dict(x=250, y=700, h=92, skin=3, cloth=0, hair='grey', arm='point'),
   dict(x=350, y=700, h=88, skin=5, cloth=3, hair='cap', arm='folded'),
   dict(x=660, y=700, h=86, skin=1, cloth=2, hair='short', arm='hold'),
   dict(x=1250, y=700, h=86, skin=2, cloth=4, hair='bun', arm='hold'),
   dict(x=1350, y=700, h=86, skin=4, cloth=1, hair='long', arm='down')],
 names=[dict(x=250, t='the chair - eleven years of these'),
   dict(x=350, t='the shift supervisor, who asked for page 61'),
   dict(x=660, t='the jug of water and one glass'),
   dict(x=1250, t='the hearing room door, closed'),
   dict(x=1350, t='the box file marked EXHIBITS'),
   dict(x=520, t='the clock: quarter past eleven'),
   dict(x=1075, t='31 quotations, 4 of them paraphrases'),
   dict(x=210, t='three days, fourteen witnesses')],
 markers=[dict(x=250, y=570), dict(x=350, y=574), dict(x=660, y=574), dict(x=1250, y=574),
   dict(x=1350, y=578), dict(x=520, y=630), dict(x=1075, y=644), dict(x=210, y=650),
   dict(x=800, y=652), dict(x=1170, y=656), dict(x=300, y=444), dict(x=860, y=444)]),

"fig_b22_u08_p01_v02": dict(type='V2', height=820,
 title='One account, in section',
 sub='Twelve words, and the layer each one lives on. One of them is a rule, not evidence.',
 alt='A cutaway of a witness account in four layers, from what was said through how it was '
     'captured and what it is worth, to what is done with it.',
 floors=[dict(was='what somebody says', now='testimony · deposition · affidavit · allegation',
     year='', fill='#EDF1EC'),
   dict(was='how it is captured', now='transcript · verbatim · redaction',
     year='', fill='#E8EEF0'),
   dict(was='what it is worth', now='hearsay · privilege · qualification',
     year='', fill='#F3EADA'),
   dict(was='what is done with it', now='rebuttal · sourcing',
     year='', fill='#F6E2DC')],
 callouts=[dict(at=0.12, text='Four words, and only one of them carries a penalty for untruth'),
   dict(at=0.38, text='Verbatim is the only one of the three that is a promise'),
   dict(at=0.62, text='Hearsay is not evidence; it is a rule about evidence'),
   dict(at=0.88, text='Two words, and both of them belong to whoever writes the report')]),

"fig_b22_u08_p02_v07": dict(type='V7', height=840,
 title='Quarter past eleven, and the draft is out',
 sub='She has chaired eleven years of these. He has read page sixty-one.',
 alt='An inquiry chair and a shift supervisor at a table with a transcript and a draft report '
     'between them, each with two speech balloons and a thought balloon.',
 bg='#E2E3E0',
 set=[dict(kind='table', x=760, y=680, s=2.2), dict(kind='cup', x=840, y=634, s=1.4),
   dict(kind='box', x=1380, y=680, s=1.0)],
 people=[dict(x=520, h=250, skin=3, cloth=0, hair='grey', arm='point', facing='right',
   label='the chair', role='fourteen witnesses, three days, 118 pages',
   says=['He maintained that the gantry was clear.',
         'Words to that effect.'],
   thinks=['Give them a page number and they will come back.']),
  dict(x=1080, h=240, skin=5, cloth=3, hair='cap', arm='folded', facing='left',
   label='the supervisor', role='he accepts the finding and disputes one word',
   says=['According to the transcript, I assumed.',
         'No such claim was made.'],
   thinks=['Assumed and knew are two different men.'])]),

"fig_b22_u08_p03_v09": dict(type='V9', kind='branch', height=820,
 title='One sentence, six verbs, six distances',
 sub='The attribution verb is a claim by the reporter, not by the speaker.',
 alt='A branching diagram from one reported statement into six attribution verbs, each with what '
     'the reporter is committing to.',
 root='"the gantry was clear"',
 branches=[dict(label='said', colour='#9AA7AE',
     example='NEUTRAL: the reporter takes no position at all'),
   dict(label='claimed', colour='#A8372E',
     example='DOUBT: the reporter signals they do not endorse it'),
   dict(label='conceded', colour='#C86B2B',
     example='GROUND GIVEN: the speaker lost something by saying it'),
   dict(label='maintained', colour='#1F4E5F',
     example='GROUND HELD: the speaker was under pressure and held'),
   dict(label='is said to have', colour='#D9A441',
     example='TWO REMOVES: somebody unnamed is the source'),
   dict(label='stopped short of', colour='#2E6F5E',
     example='AN ABSENCE: nothing was said, and that is the news')]),

"fig_b22_u08_p04_v04": dict(type='V4', height=740,
 title='Page sixty-one and the finding',
 sub='Both about the same moment and the same belief. One word apart.',
 alt='A transcript page and an inquiry finding side by side, with the quotation marks, the page '
     'references and the single word that differs.',
 differences=6, prompt='Find the six. One of the two can be checked in a single move. Which, and '
                       'what makes it checkable?',
 left=dict(label='the transcript, p.61', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#1F4E5F'),
   dict(kind='block', x=150, y=106, w=230, bh=24, colour='#1F4E5F'),
   dict(kind='gap', x=150, y=72, w=250, bh=24),
   dict(kind='label', x=300, y=218,
        text='"I assumed the gantry was clear" · verbatim · p.61',
        colour='#1F4E5F')]),
 right=dict(label='the finding', art=[
   dict(kind='block', x=150, y=140, w=250, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=106, w=240, bh=24, colour='#A8372E'),
   dict(kind='block', x=150, y=72, w=200, bh=24, colour='#A8372E'),
   dict(kind='label', x=300, y=218,
        text='"I knew the gantry was clear" · in marks · no page',
        colour='#A8372E')])),

"fig_b22_u08_p05_v05": dict(type='V5', height=1100,
 title='Thirty-one quotations, four of them not',
 sub='What is inside the marks, where it came from, and what each verb commits the inquiry to.',
 alt='An inquiry report page annotated to show which quoted passages are verbatim, which are '
     'paraphrases, and what each attribution verb claims.',
 rows=[dict(t='org', text='INQUIRY INTO THE GANTRY INCIDENT  -  FINDING 4  -  DRAFT'),
   dict(t='para', text='TRANSCRIPT, P.61: "I assumed the gantry was clear. I had not walked the '
     'lane that morning."'),
   dict(t='para', text='FINDING 4: "The supervisor stated: \'I knew the gantry was clear.\' He '
     'is understood to have told colleagues the same. He would not be drawn on the handover."'),
   dict(t='rule'),
   dict(t='grid', cols=['IN THE REPORT', 'COUNT', 'CHECKABLE'],
     data=[['PASSAGES IN QUOTATION MARKS', '31', '--'],
           ['OF THOSE, VERBATIM', '27', 'YES'],
           ['OF THOSE, PARAPHRASE', '4', 'NO'],
           ['WITH A PAGE REFERENCE', '0', '--'],
           ['WORDS CHANGED ON P.61', '1', '--'],
           ['WITNESSES HEARD', '14', '--'],
           ['TRANSCRIPT PAGES', '118', '--'],
           ['CORRECTIONS REQUESTED, YEAR 1', '2%', '--']]),
   dict(t='rule'),
   dict(t='head', text='WHAT EACH VERB IN FINDING 4 COMMITS THE INQUIRY TO'),
   dict(t='kv', k='"stated"', v='these are the exact words - and they are not', mono=False),
   dict(t='kv', k='"is understood to have"', v='an unnamed source, and none was heard',
        mono=False),
   dict(t='kv', k='"would not be drawn"', v='an absence, accurately reported', mono=False),
   dict(t='kv', k='no page reference', v='nothing here can be checked in one move', mono=False),
   dict(t='rule'),
   dict(t='para', text='The drafter understood quotation marks as a courtesy to the reader. They '
     'are a claim about the words, and four of thirty-one make a claim that is false.')],
 callouts=[dict(at=0.08, text='Two sentences, both of them the witness\'s own'),
   dict(at=0.22, text='Three borrowed sentences, three different distances, one page reference short'),
   dict(at=0.50, text='Twenty-seven exact and four not, and nothing marks which is which'),
   dict(at=0.82, text='The absence is the only one of the three reported correctly'),
   dict(at=0.95, text='Quotation marks are a claim, not a courtesy')]),

"fig_b22_u08_p07_v10": dict(type='V10', kind='pitch', height=860,
 title='Quotation marks you can hear',
 sub='Two pauses and a flatter, faster run: that is what a quotation sounds like.',
 alt='Four pitch contours over reported speech showing audible quotation marks, an unmarked '
     'report, a stressed quoted word and a two-remove report.',
 contours=[
  dict(text='He said - I assumed the gantry was clear - and stopped.',
       points=[0.4, 0.2, 0.15, 0.15, 0.15, 0.3, -0.7],
       meaning='two pauses, and the quoted run is flat'),
  dict(text='He said he assumed the gantry was clear.',
       points=[0.4, 0.35, 0.3, 0.2, 0.1, -0.2, -0.7],
       meaning='no pauses: the words are yours now'),
  dict(text='He said he KNEW.',
       points=[0.3, 0.2, 0.3, 0.6, 0.95, 0.4, -0.5],
       meaning='stressing a quoted word is an argument'),
  dict(text='He is understood to have told them so.',
       points=[0.3, 0.25, 0.2, 0.2, 0.1, -0.1, -0.6],
       meaning='two removes, and the tune flattens with it')]),

"fig_b22_u08_p09_v05": dict(type='V5', height=940,
 title='Nine reports, two verbs',
 sub='Accurate, flat, and carrying none of the reporter\'s own position.',
 alt='A study sheet showing learner reports using only say and tell, what each moment actually '
     'was, and the verb that would have carried it.',
 rows=[dict(t='org', text='STUDY FILE  -  HE SAID, SHE SAID, THEY SAID'),
   dict(t='para', text='Reporting with say and tell is correct in every case here. It is also the '
     'only information the listener gets about what kind of moment each one was.'),
   dict(t='rule'),
   dict(t='grid', cols=['WHAT YOU SAID', 'WHAT THE MOMENT WAS', 'THE VERB'],
     data=[['HE SAID HE HAD NOT CHECKED', 'HE LOST SOMETHING', 'CONCEDED'],
           ['SHE SAID IT WAS CLEAR, AGAIN', 'SHE WAS UNDER PRESSURE', 'MAINTAINED'],
           ['HE SAID IT WAS NOT HIS FAULT', 'YOU DO NOT BELIEVE IT', 'CLAIMED'],
           ['SHE SAID NO', 'A FLAT REFUSAL', 'DENIED'],
           ['HE SAID SOMETHING BACK', 'THERE WAS SOMETHING TO ANSWER', 'COUNTERED']]),
   dict(t='rule'),
   dict(t='head', text='WHAT THE VERB CARRIES THAT SAID CANNOT'),
   dict(t='kv', k='who gave ground', v='conceded, acknowledged', mono=False),
   dict(t='kv', k='who held it', v='maintained, insisted, asserted, denied', mono=False),
   dict(t='kv', k='what you think of it', v='claimed - and it is actionable if unfair',
        mono=False),
   dict(t='kv', k='that there was an exchange', v='countered, responded', mono=False),
   dict(t='rule'),
   dict(t='para', text='Report one real conversation in eight sentences with at least five '
     'different verbs, and ask somebody who won it from the verbs alone.')],
 callouts=[dict(at=0.12, text='Every row on the left is correct English'),
   dict(at=0.44, text='Five moments, one verb, and the listener learns nothing about any of them'),
   dict(at=0.76, text='Claimed is the only one of the six that can be unfair'),
   dict(at=0.95, text='The verbs alone should say who won')]),

"fig_b22_u08_p10_v12": dict(type='V12',
 title='A hundred and eighteen pages, thirty-one quotations',
 sub='What was said, what was printed, and what happened when witnesses were sent the pages.',
 alt='An infographic of an inquiry showing the transcript length, the quotations in the report, '
     'how many were verbatim and the correction requests before and after.',
 span=['0', '118 pages'], ticks=4,
 tick_labels=['0', '39', '79', '118'],
 bands=[dict(name='The transcript', type='bars', items=[
   dict(**{'from': 0.0, 'to': 1.0}, label='118 pages, fourteen witnesses, three days',
        colour='#9AA7AE')]),
  dict(name='Quoted in the report', type='events', items=[
   dict(at=0.20, label='27 verbatim', colour='#2E6F5E'),
   dict(at=0.62, label='4 paraphrases, in quotation marks', colour='#A8372E')]),
  dict(name='Page 61', type='events', items=[
   dict(at=0.52, label='"I assumed" becomes "I knew"', colour='#A8372E')]),
  dict(name='Corrections requested', type='events', items=[
   dict(at=0.16, label='before: 2% of witnesses', colour='#9AA7AE'),
   dict(at=0.70, label='after page refs: 24%, four fifths of them paraphrases',
        colour='#2E6F5E')]),
  dict(name='What this shows', type='flags', items=[
   dict(at=0.08, label='quotation marks are a claim about the words, not a courtesy'),
   dict(at=0.58, label='witnesses came back about sentences they had not said')])]),

"fig_b22_u08_p11_v06": dict(type='V6', kind='bar', height=820,
 title='Four quotation policies, one inquiry service',
 sub='Four years, the same inquiry team, the same kinds of hearing.',
 alt='A bar chart comparing four quotation policies on the share of quoted passages traceable to '
     'a transcript page and the share of witnesses who asked to correct the draft.',
 labels=['paraphrase in marks', 'verbatim, no refs', 'verbatim + page refs', 'marked paraphrase'],
 ymin=0, ymax=100, fmt='{:.0f}',
 series=[dict(name='traceable in one move (%)', values=[13, 56, 97, 94], colour='#2E6F5E'),
   dict(name='witnesses asking to correct (%)', values=[2, 6, 19, 24], colour='#C86B2B')],
 note='Correction requests rise with traceability, which is the cost everybody predicts. Four '
      'fifths of the requests are to sentences the inquiry wrote, not sentences witnesses said.',
 warning='The last column scores slightly lower on traceability and highest on corrections, '
         'because a marked paraphrase invites a witness to argue with the inquiry\'s summary - '
         'which is an argument worth having before publication rather than after.'),
}
