# -*- coding: utf-8 -*-
"""The content inventory of Chapter 1, lifted from the approved plan.

Generated from CMA_Book1_Handout_Plan.md section 7, so the plan and the
build cannot drift apart. A unit that no handout claims fails the chapter
build; the planned handout is recorded beside each unit so a reallocation
is visible in the diff.
"""
LEDGER = {
    'C1-A': ('Chapter LOS table: 5 rows, code / objective / level / depth',
             [12]),
    'C1-B': ('Chapter key terms: 16 rows, English and Arabic (French not used)',
             [12]),
    'C1-C': ('What you already know: the three new things',
             [12]),
    '1.1-a': ('The four main statements, named',
             [1]),
    '1.1-b': ('General-purpose statements: many readers, not one special reader',
             [1]),
    '1.1-c': ('Primary users: who they are, that they give resources, that they cannot demand special reports',
             [1]),
    '1.1-d': ('Figure F01-02: 7 users × decision, key question, statements used most',
             [1]),
    '1.1-e': ('Other groups; managers not primary; management accounting',
             [1]),
    '1.1-f': ('The three user questions and the statement answering each',
             [1]),
    '1.1-g': ('Stewardship',
             [1]),
    '1.1-h': ('Relevance: predictive value, confirmatory value, materiality',
             [1]),
    '1.1-i': ('Faithful representation: complete, neutral, free from error',
             [1]),
    '1.1-j': ('The four enhancing qualities; the cost constraint',
             [1]),
    '1.1-k': ('Exam trap: primary users; fundamental vs enhancing',
             [1]),
    '1.1-l': ('Language focus: the five verbs; the Orontes sentence',
             [1]),
    '1.1-m': ('Term bridge: 8 rows',
             [1]),
    '1.1-n': ('Section checks SC1-1, SC1-2',
             [1]),
    '1.2-a': ('Ten FASB elements; three describe the balance sheet',
             [2]),
    '1.2-b': ('Asset, liability, equity: definitions and examples',
             [2]),
    '1.2-c': ('Revenues and expenses: central, ongoing',
             [2]),
    '1.2-d': ('Gains and losses: peripheral, incidental; the truck example',
             [2]),
    '1.2-e': ('Investments by owners; distributions to owners',
             [2]),
    '1.2-f': ('Comprehensive income',
             [2]),
    '1.2-g': ('IFRS contrast: the IFRS asset definition; income covers revenue and gains; three IFRS names',
             [2]),
    '1.2-h': ('False friends: stock, income/revenue, résultat/charges, balance',
             [2]),
    '1.2-i': ('A = L + E; why it always holds',
             [3]),
    '1.2-j': ('Contributed capital: common stock at par, APIC',
             [3]),
    '1.2-k': ('Retained earnings; what raises and lowers it; dividends are not an expense',
             [3]),
    '1.2-l': ('Term bridge: 14 rows',
             [2, 3]),
    '1.2-m': ('Section checks SC2-1, SC2-2',
             [2, 3]),
    '1.3-a': ('Double entry; at least two accounts; debits equal credits',
             [4]),
    '1.3-b': ('Debit is left, credit is right; neither means good or increase; normal balance',
             [4]),
    '1.3-c': ('Figure F01-04: the six account types and the expanded equation',
             [4]),
    '1.3-d': ('Contra accounts: accumulated depreciation, allowance for credit losses',
             [4]),
    '1.3-e': ('Worked example: the six January journal entries and the 4,070 totals',
             [5]),
    '1.3-f': ('Figure F01-05: the effect grid, the three exam points, the equation totals',
             [6]),
    '1.3-g': ('Exam trap: three classic mistakes',
             [5, 6]),
    '1.3-h': ('Your turn: the six February transactions, entries and effects',
             [7]),
    '1.3-i': ('Language focus: describing the effect of a transaction',
             [7]),
    '1.3-j': ('False friends: استهلاك, مخصص, credit',
             [4]),
    '1.3-k': ('Term bridge: 15 rows',
             [4, 5]),
    '1.3-l': ('Section checks SC3-1, SC3-2',
             [4]),
    '1.4-a': ('Accrual basis; cash basis; cash timing does not decide the period',
             [8]),
    '1.4-b': ('Figure F01-07: the December sale collected in January, 90 / 54 / 36',
             [8]),
    '1.4-c': ('Matching principle; the three ways to apply it',
             [8]),
    '1.4-d': ('The four adjustment types, what each creates, the Orontes examples',
             [8]),
    '1.4-e': ('Exam trap: cash is not the trigger',
             [8]),
    '1.4-f': ('Term bridge: 5 rows; section checks SC4-1, SC4-2',
             [8]),
    '1.5-a': ('U.S. GAAP, FASB, the ASC, topic numbers, the ASU',
             [9]),
    '1.5-b': ('The SEC: what it is and what it does',
             [9]),
    '1.5-c': ('The PCAOB: auditing, not accounting',
             [9]),
    '1.5-d': ('IFRS, the IASB, the IFRS Foundation, MENA adoption, Cedar Retail',
             [9]),
    '1.5-e': ('The exam tests U.S. GAAP and the main differences; the conceptual framework',
             [9]),
    '1.5-f': ('IFRS contrast: the six name pairs',
             [9]),
    '1.5-g': ('Exam trap: four bodies, four jobs',
             [9]),
    '1.5-h': ('Term bridge: 7 rows; section checks SC5-1, SC5-2',
             [9]),
    '1.6-a': ('The four statements: question, time, chapter',
             [10]),
    '1.6-b': ('Figure F01-09: net income into retained earnings; cash into the balance sheet',
             [10]),
    '1.6-c': ('January: net income 80, dividend 50, RE +30, cash +1,060 and its three parts',
             [10]),
    '1.6-d': ('Net income and the change in cash are different numbers',
             [10]),
    '1.6-e': ('Figure F01-10: the Barada trial balance, 20 accounts, 9,750 totals',
             [11]),
    '1.6-f': ('Language focus: reading exam questions',
             [12]),
    '1.6-g': ('Term bridge: 5 rows; section checks SC6-1, SC6-2',
             [10, 11]),
    'CS': ('Chapter summary: the eight rules',
             [12]),
    'C': ('Case set C1-1 to C1-5: categories, net income, total assets, RE, total liabilities',
             [11]),
    'W': ('Written task W1: why a dividend is not an expense',
             [3, 12]),
}
