# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C11-1': ('case item C11-1', []),
    'C11-2': ('case item C11-2', []),
    'C11-3': ('case item C11-3', []),
    'C11-4': ('case item C11-4', []),
    'C11-5': ('case item C11-5', []),
    'C11-6': ('case item C11-6', []),
    'P11-01': ('practice item P11-01', []),
    'P11-02': ('practice item P11-02', []),
    'P11-03': ('practice item P11-03', []),
    'P11-04': ('practice item P11-04', []),
    'P11-05': ('practice item P11-05', []),
    'P11-06': ('practice item P11-06', []),
    'P11-07': ('practice item P11-07', []),
    'P11-08': ('practice item P11-08', []),
    'P11-09': ('practice item P11-09', []),
    'P11-10': ('practice item P11-10', []),
    'P11-11': ('practice item P11-11', []),
    'P11-12': ('practice item P11-12', []),
    'P11-13': ('practice item P11-13', []),
    'P11-14': ('practice item P11-14', []),
    'P11-15': ('practice item P11-15', []),
    'P11-16': ('practice item P11-16', []),
    'P11-17': ('practice item P11-17', []),
    'P11-18': ('practice item P11-18', []),
    'P11-19': ('practice item P11-19', []),
    'P11-20': ('practice item P11-20', []),
    'P11-21': ('practice item P11-21', []),
    'P11-22': ('practice item P11-22', []),
    'SC11-1': ('section-check item SC11-1', []),
    'SC11-10': ('section-check item SC11-10', []),
    'SC11-11': ('section-check item SC11-11', []),
    'SC11-2': ('section-check item SC11-2', []),
    'SC11-3': ('section-check item SC11-3', []),
    'SC11-4': ('section-check item SC11-4', []),
    'SC11-5': ('section-check item SC11-5', []),
    'SC11-6': ('section-check item SC11-6', []),
    'SC11-7': ('section-check item SC11-7', []),
    'SC11-8': ('section-check item SC11-8', []),
    'SC11-9': ('section-check item SC11-9', []),
    'term:agent': ("term-bridge row 'agent'", []),
    'term:bill-and-hold arrangement': ("term-bridge row 'bill-and-hold arrangement'", []),
    'term:breakage': ("term-bridge row 'breakage'", []),
    'term:consideration payable to a customer': ("term-bridge row 'consideration payable to a customer'", []),
    'term:constraint on variable consideration': ("term-bridge row 'constraint on variable consideration'", []),
    'term:contract asset': ("term-bridge row 'contract asset'", []),
    'term:incremental costs of obtaining a contract': ("term-bridge row 'incremental costs of obtaining a contract'", []),
    'term:input method': ("term-bridge row 'input method'", []),
    'term:matching principle': ("term-bridge row 'matching principle'", []),
    'term:material right': ("term-bridge row 'material right'", []),
    'term:output method': ("term-bridge row 'output method'", []),
    'term:over time': ("term-bridge row 'over time'", []),
    'term:performance obligation': ("term-bridge row 'performance obligation'", []),
    'term:point in time': ("term-bridge row 'point in time'", []),
    'term:principal': ("term-bridge row 'principal'", []),
    'term:refund liability': ("term-bridge row 'refund liability'", []),
    'term:revenue': ("term-bridge row 'revenue'", []),
    'term:significant financing component': ("term-bridge row 'significant financing component'", []),
    'term:standalone selling price': ("term-bridge row 'standalone selling price'", []),
    'term:transaction price': ("term-bridge row 'transaction price'", []),
    'term:variable consideration': ("term-bridge row 'variable consideration'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C11-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P11-16': 'it sends the reader to F11-07, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC11-5': 'it sends the reader to F11-04, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC11-9': 'it sends the reader to F11-08, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
