# -*- coding: utf-8 -*-
"""Handout 4.2, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '4.2',
 'n': 2,
 'pages': 5,
 'title': 'Issuing and buying back shares',
 'sub': 'section 4.2 of the book',
 'covers': ['sec:4.2',
            'p:P4-07',
            'p:P4-08',
            'p:P4-09',
            'p:P4-10',
            'sc:P4-07',
            'p:P4-11',
            'p:P4-12',
            'term:contributed capital',
            'term:appropriated retained earnings',
            'term:declaration date'],
 'skills': [('read2', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['Issuing and buying back shares',
             'a figure to read · Account',
             'A company declares a stock dividend on December 20 and '
             'distributes the shares on January 10. How does it present the '
             'stock dividend distributable at December 31?'],
            ['The words this section uses precisely',
             'The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['',
                       17,
                       ' is recorded in the same way, in its own account. A '
                       'company may buy back its own shares and hold them '
                       'as ',
                       16,
                       '. Under the ',
                       13,
                       ', treasury stock is recorded at the price paid and '
                       'deducted from equity. Shares held as treasury stock '
                       'are ',
                       15,
                       ' but not ',
                       20,
                       ': they receive no dividends and have no votes.'],
             'bank': ['treasury stock',
                      'stock split',
                      'issued shares',
                      'declaration date',
                      'outstanding shares',
                      'Preferred stock',
                      'cost method'],
             'a': 'Preferred stock · treasury stock · cost method · issued '
                  'shares · outstanding shares',
             'one': True,
             'why': 'The book writes: “Preferred stock is recorded in the '
                    'same way, in its own account. A company may buy back '
                    'its own shares and hold them as treasury stock. Under '
                    'the cost method, treasury stock is recorded at the '
                    'price paid and deducted from equity. Shares held as '
                    'treasury stock are issued shares but not outstanding '
                    'shares: they receive no dividends and have no votes.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['Shares held as ',
                       16,
                       ' are ',
                       15,
                       ' but not ',
                       20,
                       ': they receive no dividends and have no votes. A '
                       'company never records a gain or loss on its own '
                       'shares in net income. Treasury stock under the ',
                       13,
                       ': buy back, reissue or retire.'],
             'bank': ['declaration date',
                      'treasury stock',
                      'cost method',
                      'issued shares',
                      'preferred stock',
                      'outstanding shares'],
             'a': 'treasury stock · issued shares · outstanding shares · '
                  'cost method',
             'one': True,
             'why': 'The book writes: “Shares held as treasury stock are '
                    'issued shares but not outstanding shares: they receive '
                    'no dividends and have no votes. A company never records '
                    'a gain or loss on its own shares in net income. '
                    'Treasury stock under the cost method: buy back, reissue '
                    'or retire.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['A company may buy back its own shares and hold them '
                       'as ',
                       16,
                       '. Under the ',
                       13,
                       ', treasury stock is recorded at the price paid and '
                       'deducted from equity. Shares held as treasury stock '
                       'are ',
                       15,
                       ' but not ',
                       20,
                       ': they receive no dividends and have no votes.'],
             'bank': ['declaration date',
                      'preferred stock',
                      'treasury stock',
                      'issued shares',
                      'outstanding shares',
                      'cost method'],
             'a': 'treasury stock · cost method · issued shares · '
                  'outstanding shares',
             'one': True,
             'why': 'The book writes: “A company may buy back its own shares '
                    'and hold them as treasury stock. Under the cost method, '
                    'treasury stock is recorded at the price paid and '
                    'deducted from equity. Shares held as treasury stock are '
                    'issued shares but not outstanding shares: they receive '
                    'no dividends and have no votes.”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['contributed capital', ''],
              ['appropriated retained earnings', ''],
              ['declaration date', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', 'Issuing and buying back shares'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'The book gives the category of APIC–treasury stock as '
                  '“Contributed capital”.',
             'a': 'T',
             'why': 'The book pairs APIC–treasury stock with “Contributed '
                    'capital”.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f2'),
          ('panel',
           'Account — the book’s own table',
           [['Account', 'Category'],
            ['APIC–treasury stock', 'Contributed capital'],
            ['Retained earnings', 'Earned capital'],
            ['Treasury stock', 'Deduction from equity'],
            ['Dividends payable', 'Current liability'],
            ['Common stock', 'Contributed capital']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which category does the book give for APIC–treasury '
                  'stock?',
             'o': ['Earned capital',
                   'Deduction from equity',
                   'Contributed capital',
                   'Current liability'],
             'a': 'C',
             'why': 'The book’s own table gives Contributed capital as the '
                    'category of APIC–treasury stock.'},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Retained earnings?',
             'o': ['Earned capital',
                   'Contributed capital',
                   'Current liability',
                   'Deduction from equity'],
             'a': 'A',
             'why': 'The book’s own table gives Earned capital as the '
                    'category of Retained earnings.'},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Treasury stock?',
             'o': ['Contributed capital',
                   'Current liability',
                   'Earned capital',
                   'Deduction from equity'],
             'a': 'D',
             'why': 'The book’s own table gives Deduction from equity as the '
                    'category of Treasury stock.'},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Dividends payable?',
             'o': ['Current liability',
                   'Earned capital',
                   'Deduction from equity',
                   'Contributed capital'],
             'a': 'A',
             'why': 'The book’s own table gives Current liability as the '
                    'category of Dividends payable.'},
            {'t': 'TF',
             'q': 'The book gives the category of APIC–treasury stock as '
                  '“Contributed capital”.',
             'a': 'T',
             'why': 'The book pairs APIC–treasury stock with “Contributed '
                    'capital”.'},
            {'t': 'TF',
             'q': 'The book gives the category of Retained earnings as '
                  '“Contributed capital”.',
             'a': 'F',
             'why': 'The book pairs Retained earnings with “Earned capital”, '
                    'not with “Contributed capital”.'},
            {'t': 'SORT',
             'q': 'Write each one under its category. Every item belongs to '
                  'exactly one group.',
             'regions': ['Contributed capital',
                         'Current liability',
                         'Deduction from equity',
                         'Earned capital'],
             'items': ['APIC–treasury stock',
                       'Retained earnings',
                       'Treasury stock',
                       'Dividends payable',
                       'Common stock'],
             'a': ['Contributed capital: APIC–treasury stock, Common stock',
                   'Current liability: Dividends payable',
                   'Deduction from equity: Treasury stock',
                   'Earned capital: Retained earnings'],
             'whys': ['', '', '', '']}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company declares a stock dividend on December 20 and '
                  'distributes the shares on January 10. How does it present '
                  'the stock dividend distributable at December 31?',
             'o': ['As a current liability',
                   "In stockholders' equity",
                   'As a long-term liability',
                   'In the notes only'],
             'a': 'B',
             'why': 'No assets will be paid, so it is equity. A is wrong: '
                    'Only a cash dividend creates a liability. C is wrong: '
                    'Nothing is owed to anyone.',
             'src': 'P4-07'},
            {'t': 'MCQ',
             'q': 'Which item is part of contributed capital?',
             'o': ['Retained earnings',
                   'Accumulated other comprehensive income',
                   'Appropriated retained earnings',
                   'Additional paid-in capital'],
             'a': 'D',
             'why': "APIC comes from owners' payments. A is wrong: Retained "
                    'earnings are earned capital. B is wrong: AOCI is earned '
                    'capital.',
             'src': 'P4-08'},
            {'t': 'MCQ',
             'q': 'In a statement of changes in equity, in which column does '
                  'an OCI loss on AFS debt securities appear?',
             'o': ['Retained earnings',
                   'Additional paid-in capital',
                   'Accumulated other comprehensive income',
                   'Treasury stock'],
             'a': 'C',
             'why': 'OCI goes to AOCI, not retained earnings. A is wrong: '
                    'Only net income goes to retained earnings. B is wrong: '
                    'APIC is for owner contributions.',
             'src': 'P4-09'},
            {'t': 'MCQ',
             'q': "A company's retained earnings were $800,000 on January 1. "
                  'Net income was $250,000, cash dividends declared were '
                  '$60,000, and a 5% stock dividend was measured at $90,000. '
                  'What are retained earnings at December 31?',
             'o': ['$900,000', '$960,000', '$990,000', '$1,050,000'],
             'a': 'A',
             'why': 'Opening + net income − cash dividends − stock dividend. '
                    'B is wrong: This leaves out the cash dividend. C is '
                    'wrong: This leaves out the stock dividend.',
             'src': 'P4-10'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'A company declares a stock dividend on December 20 and '
           'distributes the shares on January 10. How does it present the '
           'stock dividend distributable at December 31?',
           ['As a current liability',
            "In stockholders' equity",
            'As a long-term liability',
            'In the notes only'],
           'B',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'No assets will be paid, so it is equity. A is wrong: Only a cash '
           'dividend creates a liability. C is wrong: Nothing is owed to '
           'anyone.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['contributed capital', 'رأس المال المساهم به (المدفوع)'],
            ['appropriated retained earnings', 'أرباح مبقاة مخصصة'],
            ['declaration date', 'تاريخ الإعلان']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A glossary term and its translation are a pair the book '
                  'itself gives.',
             'a': 'T',
             'why': 'The term tables in each section are the book’s own.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company pays $50,000 of legal and underwriting costs to '
                  'issue new common shares. How does it record the costs?',
             'o': ['As an expense',
                   'As a reduction of additional paid-in capital',
                   'As an intangible asset',
                   'As a reduction of retained earnings'],
             'a': 'B',
             'why': 'Direct equity issuance costs reduce the proceeds, so '
                    'they reduce APIC. A is wrong: Equity issuance costs are '
                    'not expensed. C is wrong: They are not an asset.',
             'src': 'P4-11'},
            {'t': 'MCQ',
             'q': 'A company issues common shares in exchange for land. The '
                  'shares are actively traded. The land is recorded at:',
             'o': ['the par value of the shares',
                   "the seller's carrying amount of the land",
                   'the fair value of the shares',
                   'zero, because no cash was paid'],
             'a': 'C',
             'why': 'Use the more reliable fair value; a traded share price '
                    'is reliable. A is wrong: Par value is only a legal '
                    "amount. B is wrong: The seller's book value is not the "
                    'exchange value.',
             'src': 'P4-12'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f2',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['contributed capital',
            'appropriated retained earnings',
            'declaration date'],
           'When a company issues shares for cash, it credits common stock '
           'with the par value and APIC with the rest. If the shares have no '
           'par and no stated value, the whole amount goes to common stock. '
           'Direct costs of issuing shares, such as underwriting fees, '
           'reduce APIC; they are not expenses.')]}
