# -*- coding: utf-8 -*-
"""Handout 4.6, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '4.6',
 'n': 6,
 'pages': 7,
 'title': 'The whole chapter',
 'sub': 'every section, shuffled, and the chapter’s own case set',
 'covers': ['sec:summary',
            'p:P4-11',
            'p:P4-12',
            'p:P4-13',
            'p:P4-15',
            'p:P4-17',
            'p:P4-18',
            'p:P4-19',
            'p:P4-21',
            'p:P4-22',
            'p:P4-24',
            'p:P4-25',
            'sc:SC4-5',
            'sc:SC4-6',
            'sc:SC4-7',
            'sc:SC4-8',
            'sc:SC4-9',
            'term:statement of changes in equity',
            'term:contributed capital',
            'term:outstanding shares',
            'term:treasury stock',
            'term:stock dividend',
            'term:stock split',
            'term:appropriated retained earnings',
            'term:prior-period adjustment',
            'term:preferred stock',
            'term:issued shares',
            'term:cost method',
            'term:declaration date',
            'term:date of record',
            'term:property dividend',
            'term:liquidating dividend',
            'case:C4-1',
            'case:C4-2',
            'case:C4-3',
            'case:C4-4',
            'case:C4-5',
            'case:C4-6'],
 'skills': [('review', 0)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this chapter, in the book’s own words, with '
           'words taken out. Read all three first: together they are the '
           'whole chapter. Then fill the gaps.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['The whole chapter, in order',
             'a figure to read · Suppose: Orontes, 8,100,000 shares',
             'A company pays $50,000 of legal and underwriting costs to '
             'issue new common shares. How does it record the costs?'],
            ['The chapter’s case set',
             'The chapter’s case set, item by item · Suppose: Orontes, '
             '8,100,000 shares',
             'What has to be settled before any figure in a case set is '
             'worked out?'],
            ['The words it uses precisely',
             'statement of changes in equity · contributed capital · '
             'outstanding shares · treasury stock · stock dividend · stock '
             'split',
             'matching, at the end of cycle B']],
           [{'t': 'FILL',
             'q': 'Where the chapter starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['A company may buy back its own shares and hold them '
                       'as ',
                       16,
                       '. Under the ',
                       13,
                       ', treasury stock is recorded at the price paid and '
                       'deducted from equity. Shares held as treasury stock '
                       'are ',
                       15,
                       ' but not ',
                       20,
                       ': they receive no dividends and have no votes.'],
             'bank': ['treasury stock',
                      'outstanding shares',
                      'property dividend',
                      'issued shares',
                      'cost method',
                      'preferred stock'],
             'a': 'treasury stock · cost method · issued shares · '
                  'outstanding shares',
             'one': True,
             'why': 'The book writes: “A company may buy back its own shares '
                    'and hold them as treasury stock. Under the cost method, '
                    'treasury stock is recorded at the price paid and '
                    'deducted from equity. Shares held as treasury stock are '
                    'issued shares but not outstanding shares: they receive '
                    'no dividends and have no votes.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['A ',
                       22,
                       ' returns ',
                       21,
                       ', so it reduces APIC rather than retained earnings. '
                       'A ',
                       16,
                       ' gives shareholders more shares instead of cash. For '
                       'a small stock dividend, below about 20% to 25% of '
                       'the ',
                       20,
                       ', the company moves the fair value of the new shares '
                       'from retained earnings to common stock and APIC.'],
             'bank': ['contributed capital',
                      'cost method',
                      'outstanding shares',
                      'issued shares',
                      'liquidating dividend',
                      'stock dividend'],
             'a': 'liquidating dividend · contributed capital · stock '
                  'dividend · outstanding shares',
             'one': True,
             'why': 'The book writes: “A liquidating dividend returns '
                    'contributed capital, so it reduces APIC rather than '
                    'retained earnings. A stock dividend gives shareholders '
                    'more shares instead of cash. For a small stock '
                    'dividend, below about 20% to 25% of the outstanding '
                    'shares, the company moves the fair value of the new '
                    'shares from retained earnings to common stock and '
                    'APIC.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['On a U.S. exam, separate APIC, retained earnings (',
                       14,
                       ' or not) and AOCI. French report à nouveau is only '
                       'the ',
                       17,
                       ' part of retained earnings. Total equity is a book '
                       'value: assets minus ',
                       13,
                       ', as measured by the accounting rules.'],
             'bank': ['issued shares',
                      'carried-forward',
                      'appropriated',
                      'cost method',
                      'liabilities'],
             'a': 'appropriated · carried-forward · liabilities',
             'one': True,
             'why': 'The book writes: “On a U.S. exam, separate APIC, '
                    'retained earnings (appropriated or not) and AOCI. '
                    'French report à nouveau is only the carried-forward '
                    'part of retained earnings. Total equity is a book '
                    'value: assets minus liabilities, as measured by the '
                    'accounting rules.”'}]),
          ('page',),
          ('cycle', 'A', 'The whole chapter, in order'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'The sections of a chapter have to be taken in order, '
                  'because each one uses what the one before it settled.',
             'a': 'T',
             'why': 'The map shows the order the decisions have to be taken '
                    'in.'}]),
          ('move', 'MODEL', ''),
          ('fig', 'chmap'),
          ('fig', 'frev'),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which part of this chapter is section 4.1?',
             'o': ['Limitations and links to the other statements',
                   'Components of equity and the statement of changes in '
                   'equity',
                   'Issuing and buying back shares',
                   'Dividends, stock dividends and stock splits'],
             'a': 'B',
             'why': 'The book numbers “Components of equity and the '
                    'statement of changes in equity” as section 4.1.'},
            {'t': 'MATCH',
             'q': 'Write the letter of the section number beside each '
                  'section title. Every number is used once.',
             'left': ['Components of equity and the statement of changes in '
                      'equity',
                      'Issuing and buying back shares',
                      'Dividends, stock dividends and stock splits',
                      'Retained earnings',
                      'Limitations and links to the other statements'],
             'right': ['4.1', '4.2', '4.3', '4.4', '4.5'],
             'a': ['A', 'B', 'C', 'D', 'E'],
             'whys': ['', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('panel',
           'Suppose: Orontes, 8,100,000 shares — the extract for the '
           'question that follows',
           [['Suppose: Orontes, 8,100,000 shares',
             '4% stock dividend',
             '50% stock dividend',
             '2-for-1 split'],
            ['New shares issued', '324,000', '4,050,000', '8,100,000'],
            ['Measured at', 'fair value $15', 'par $1', 'no entry'],
            ['Retained earnings', '(4,860,000)', '(4,050,000)', 'no change'],
            ['Common stock', '324,000', '4,050,000', 'no change'],
            ['Additional paid-in capital',
             '4,536,000',
             'no change',
             'no change'],
            ["Total stockholders' equity",
             'no change',
             'no change',
             'no change'],
            ['Par value per share afterward', '$1', '$1', '$0.50']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. By how '
                  "much does the 50% stock dividend reduce Orontes's "
                  'retained earnings (whole USD)?',
             'o': ['0', '4,050,000', '4,860,000', '60,750,000'],
             'a': 'B',
             'why': 'A large stock dividend moves only par: 4,050,000 shares '
                    '× $1. A is wrong: A large stock dividend is still '
                    'recorded; only a split has no entry. C is wrong: This '
                    'is the small stock dividend.',
             'src': 'P4-17'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company with 500,000 shares of $2 par stock declares a '
                  '2-for-1 stock split. What happens?',
             'o': ['Retained earnings decrease by $1,000,000',
                   'Common stock increases by $1,000,000',
                   'Total equity doubles',
                   '1,000,000 shares of $1 par; no entry and no change in '
                   'any equity account'],
             'a': 'D',
             'why': 'A split changes the number of shares and the par per '
                    'share only. A is wrong: A split does not move retained '
                    'earnings. B is wrong: Common stock stays the same in '
                    'total.',
             'src': 'P4-18'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company has issued 1,000,000 shares, of which 100,000 '
                  'are held in treasury. It declares a 10% stock dividend. '
                  'How many new shares does it issue?',
             'o': ['10,000', '90,000', '100,000', '110,000'],
             'a': 'B',
             'why': 'Stock dividends are based on outstanding shares. A is '
                    'wrong: This applies the rate to the treasury shares '
                    'only. C is wrong: This includes the treasury shares.',
             'src': 'P4-19'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which is a limitation of the equity section of the '
                  'balance sheet?',
             'o': ['It includes all internally built intangibles',
                   'It shows the market value of the company',
                   'It is prepared on a cash basis',
                   'Treasury stock is shown at its cost, not at the current '
                   'share price'],
             'a': 'D',
             'why': 'Historical cost measures limit what equity tells users. '
                    'A is wrong: Internally built intangibles are not '
                    'recorded. B is wrong: Equity is a book amount.',
             'src': 'P4-21'}]),
          ('items',
           [{'t': 'MCQ',
             'q': "Why may a company's retained earnings not show how much "
                  'it can legally pay as dividends?',
             'o': ['Legal capital rules and loan covenants can restrict '
                   'distributions',
                   'Retained earnings include share premium',
                   'Retained earnings are measured at fair value',
                   'Dividends are paid from AOCI'],
             'a': 'A',
             'why': 'Restrictions are disclosed, not deducted from the '
                    'balance. B is wrong: Share premium is APIC, not '
                    'retained earnings. C is wrong: Retained earnings are '
                    'not a fair value.',
             'src': 'P4-22'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company pays a dividend of $300,000, but its retained '
                  'earnings are only $200,000. The extra $100,000 is:',
             'o': ['an expense',
                   'a liquidating dividend that reduces APIC',
                   'a reduction of treasury stock',
                   'shown as negative OCI'],
             'a': 'B',
             'why': 'Amounts beyond retained earnings return contributed '
                    'capital. A is wrong: Dividends are never expenses. C is '
                    'wrong: Treasury stock is not involved.',
             'src': 'P4-24'}]),
          ('pair',
           'Compare every answer with your partner first.',
           'name the section each question belongs to. Most disagreements '
           'turn out to be about the section, not the answer.'),
          ('check',
           'A company pays $50,000 of legal and underwriting costs to issue '
           'new common shares. How does it record the costs?',
           ['As an expense',
            'As a reduction of additional paid-in capital',
            'As an intangible asset',
            'As a reduction of retained earnings'],
           'B',
           'go back to the MODEL move of cycle A and find the section this '
           'question belongs to.',
           'Direct equity issuance costs reduce the proceeds, so they reduce '
           'APIC. A is wrong: Equity issuance costs are not expensed. C is '
           'wrong: They are not an asset.'),
          ('cycle', 'B', 'The chapter’s case set'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'In a case question, the exhibit has to be read and '
                  'adjusted before any figure is worked out.',
             'a': 'T',
             'why': 'Every later answer depends on the adjusted exhibit.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The chapter’s case set, item by item',
           [['Item', 'What it asks'],
            ['C4-1',
             'Classify each account at the end of 2026. (On the exam screen '
             'you would drag each account into a box.)'],
            ['C4-2',
             'Enter the balance of APIC–treasury stock at December 31, '
             '2026.'],
            ['C4-3',
             'Enter the amount transferred out of retained earnings for the '
             'stock dividend (E4).'],
            ['C4-4', 'Enter the cash dividend declared on December 15 (E5).'],
            ['C4-5', 'Enter retained earnings at December 31, 2026.'],
            ['C4-6',
             "Enter total stockholders' equity at December 31, 2026."]],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MATCH',
             'q': 'The tasks of a case set have to be worked in one order, '
                  'because each one uses the result of the one before it. '
                  'Write the letter of its place beside each task.',
             'left': ['Enter the balance of APIC–treasury stock at December '
                      '31, 2026.',
                      "Enter total stockholders' equity at December 31, "
                      '2026.',
                      'Enter the amount transferred out of retained earnings '
                      'for the stock dividend (E4).',
                      'Classify each account at the end of 2026. (On the '
                      'exam screen you would drag each account into a box.)',
                      'Enter retained earnings at December 31, 2026.',
                      'Enter the cash dividend declared on December 15 '
                      '(E5).'],
             'right': ['first',
                       'second',
                       'third',
                       'fourth',
                       'fifth',
                       'sixth'],
             'a': ['B', 'F', 'C', 'A', 'E', 'D'],
             'whys': ['', '', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company retires treasury shares that cost more than '
                  'their par value and original APIC. For the exam today, '
                  'the excess is charged to:',
             'o': ['retained earnings, or split between APIC and retained '
                   'earnings',
                   'APIC only, as ASU 2025-12 requires',
                   'net income as a loss',
                   'OCI'],
             'a': 'A',
             'why': 'These are the current rules; ASU 2025-12 adds an '
                    'optional APIC-only method from 2027. B is wrong: The '
                    'APIC-only method is optional and not yet testable. C is '
                    'wrong: Transactions in own shares do not affect net '
                    'income.',
             'src': 'P4-25'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company declares a 5% stock dividend. It is measured '
                  'at:',
             'o': ['the par value of the new shares',
                   'zero, because no assets leave the company',
                   'the fair value of the new shares',
                   'the book value per share'],
             'a': 'C',
             'why': 'A small stock dividend is measured at fair value. A is '
                    'wrong: Par value is used for large stock dividends. B '
                    'is wrong: No entry is made only for a stock split.',
             'src': 'SC4-5'}]),
          ('panel',
           'Suppose: Orontes, 8,100,000 shares — the extract for the '
           'question that follows',
           [['Suppose: Orontes, 8,100,000 shares',
             '4% stock dividend',
             '50% stock dividend',
             '2-for-1 split'],
            ['New shares issued', '324,000', '4,050,000', '8,100,000'],
            ['Measured at', 'fair value $15', 'par $1', 'no entry'],
            ['Retained earnings', '(4,860,000)', '(4,050,000)', 'no change'],
            ['Common stock', '324,000', '4,050,000', 'no change'],
            ['Additional paid-in capital',
             '4,536,000',
             'no change',
             'no change'],
            ["Total stockholders' equity",
             'no change',
             'no change',
             'no change'],
            ['Par value per share afterward', '$1', '$1', '$0.50']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. By how '
                  "much does the 4% stock dividend reduce Orontes's retained "
                  'earnings (whole USD)?',
             'o': ['0', '324,000', '4,536,000', '4,860,000'],
             'a': 'D',
             'why': '324,000 new shares × fair value of $15. A is wrong: A '
                    'stock dividend is recorded; only a split needs no '
                    'entry. B is wrong: This uses par, the rule for large '
                    'stock dividends.',
             'src': 'SC4-6'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'In 2026 a company finds that it overstated its 2024 '
                  'depreciation expense. How does it correct the error?',
             'o': ['It reports a gain in 2026 net income',
                   'It reduces 2026 depreciation expense',
                   'It records the correction in OCI',
                   'It restates prior years and increases opening retained '
                   'earnings, net of tax'],
             'a': 'D',
             'why': 'Error corrections are prior-period adjustments to '
                    'opening retained earnings. A is wrong: Errors are not '
                    'corrected through current net income. B is wrong: This '
                    'would misstate 2026 as well.',
             'src': 'SC4-7'}]),
          ('check',
           'What has to be settled before any figure in a case set is worked '
           'out?',
           ['the exhibit, adjusted for every note that goes with it',
            'the method the company uses',
            'the tax rate',
            'the order of the items'],
           'A',
           'reread the case panel in the MODEL move of cycle B.',
           'Every later answer depends on the adjusted exhibit.'),
          ('build',
           'chmap',
           'Rebuild the chapter map. Write every section in order and what '
           'each one settles.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a student starting this chapter tomorrow',
           'In four or five sentences, write what the whole chapter settles, '
           'section by section.',
           ['statement of changes in equity',
            'contributed capital',
            'outstanding shares',
            'treasury stock'],
           '4.1: Components of equity and the statement of changes in '
           'equity. 4.2: Issuing and buying back shares. 4.3: Dividends, '
           'stock dividends and stock splits. 4.4: Retained earnings. 4.5: '
           'Limitations and links to the other statements.')]}
