# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C10-1': ('case item C10-1', []),
    'C10-2': ('case item C10-2', []),
    'C10-3': ('case item C10-3', []),
    'C10-4': ('case item C10-4', []),
    'C10-5': ('case item C10-5', []),
    'C10-6': ('case item C10-6', []),
    'P10-01': ('practice item P10-01', []),
    'P10-02': ('practice item P10-02', []),
    'P10-03': ('practice item P10-03', []),
    'P10-04': ('practice item P10-04', []),
    'P10-05': ('practice item P10-05', []),
    'P10-06': ('practice item P10-06', []),
    'P10-07': ('practice item P10-07', []),
    'P10-08': ('practice item P10-08', []),
    'P10-09': ('practice item P10-09', []),
    'P10-10': ('practice item P10-10', []),
    'P10-11': ('practice item P10-11', []),
    'P10-12': ('practice item P10-12', []),
    'P10-13': ('practice item P10-13', []),
    'P10-14': ('practice item P10-14', []),
    'P10-15': ('practice item P10-15', []),
    'P10-16': ('practice item P10-16', []),
    'SC10-1': ('section-check item SC10-1', []),
    'SC10-2': ('section-check item SC10-2', []),
    'SC10-3': ('section-check item SC10-3', []),
    'SC10-4': ('section-check item SC10-4', []),
    'SC10-5': ('section-check item SC10-5', []),
    'SC10-6': ('section-check item SC10-6', []),
    'SC10-7': ('section-check item SC10-7', []),
    'SC10-8': ('section-check item SC10-8', []),
    'SC10-9': ('section-check item SC10-9', []),
    'term:amortization': ("term-bridge row 'amortization'", []),
    'term:asset group': ("term-bridge row 'asset group'", []),
    'term:capital expenditure': ("term-bridge row 'capital expenditure'", []),
    'term:capitalized interest': ("term-bridge row 'capitalized interest'", []),
    'term:carrying amount': ("term-bridge row 'carrying amount'", []),
    'term:change in accounting estimate': ("term-bridge row 'change in accounting estimate'", []),
    'term:commercial substance': ("term-bridge row 'commercial substance'", []),
    'term:depreciable base': ("term-bridge row 'depreciable base'", []),
    'term:double-declining-balance method': ("term-bridge row 'double-declining-balance method'", []),
    'term:goodwill': ("term-bridge row 'goodwill'", []),
    'term:held for sale': ("term-bridge row 'held for sale'", []),
    'term:impairment': ("term-bridge row 'impairment'", []),
    'term:indefinite-lived intangible asset': ("term-bridge row 'indefinite-lived intangible asset'", []),
    'term:involuntary conversion': ("term-bridge row 'involuntary conversion'", []),
    'term:property, plant and equipment (pp&e)': ("term-bridge row 'property, plant and equipment (PP&E)'", []),
    'term:recoverability test': ("term-bridge row 'recoverability test'", []),
    'term:reporting unit': ("term-bridge row 'reporting unit'", []),
    'term:research and development (r&d)': ("term-bridge row 'research and development (R&D)'", []),
    'term:revenue expenditure': ("term-bridge row 'revenue expenditure'", []),
    'term:salvage value': ("term-bridge row 'salvage value'", []),
    'term:straight-line method': ("term-bridge row 'straight-line method'", []),
    "term:sum-of-the-years'-digits method": ('term-bridge row "sum-of-the-years\'-digits method"', []),
    'term:units-of-production method': ("term-bridge row 'units-of-production method'", []),
    'term:useful life': ("term-bridge row 'useful life'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C10-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
}
