# -*- coding: utf-8 -*-
"""Handout 5.4, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '5.4',
 'n': 4,
 'pages': 4,
 'title': 'The direct method and required disclosures',
 'sub': 'section 5.4 of the book',
 'covers': ['sec:5.4',
            'p:P5-19',
            'p:P5-20',
            'p:P5-21',
            'p:P5-22',
            'sc:P5-19',
            'p:P5-24',
            'term:investing activities'],
 'skills': [('read4', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['The direct method and required disclosures',
             'a figure to read · Orontes, 2025, direct method (whole USD)',
             'Two companies make the same interest payments. One reports '
             'under U.S. GAAP, the other under IFRS and classifies interest '
             'as financing. Which limitation does this show?'],
            ['The words this section uses precisely',
             'The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['The direct method shows the main classes of ',
                       11,
                       ' receipts and payments, such as cash from ',
                       11,
                       ' and cash paid to suppliers. The FASB ',
                       12,
                       ' it, but few companies use it.'],
             'bank': ['investing activities',
                      'encourages',
                      'operating',
                      'customers',
                      'direct method'],
             'a': 'operating · customers · encourages',
             'one': True,
             'why': 'The book writes: “The direct method shows the main '
                    'classes of operating receipts and payments, such as '
                    'cash from customers and cash paid to suppliers. The '
                    'FASB encourages it, but few companies use it.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['A company that uses it must still show the ',
                       16,
                       ' of net income to ',
                       11,
                       ' cash flow. Cash from customers is sales adjusted '
                       'for the change in ',
                       13,
                       ' and customer deposits.'],
             'bank': ['reconciliation',
                      'investing activities',
                      'direct method',
                      'receivables',
                      'operating'],
             'a': 'reconciliation · operating · receivables',
             'one': True,
             'why': 'The book writes: “A company that uses it must still '
                    'show the reconciliation of net income to operating cash '
                    'flow. Cash from customers is sales adjusted for the '
                    'change in receivables and customer deposits.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['A company using the ',
                       11,
                       ' method must ',
                       11,
                       ' ',
                       11,
                       ' paid and income taxes paid. SC5-8 A company uses '
                       'the indirect method.'],
             'bank': ['indirect',
                      'disclose',
                      'investing activities',
                      'interest',
                      'direct method'],
             'a': 'indirect · disclose · interest',
             'one': True,
             'why': 'The book writes: “A company using the indirect method '
                    'must disclose interest paid and income taxes paid. '
                    'SC5-8 A company uses the indirect method.”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['investing activities', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', 'The direct method and required disclosures'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f4'),
          ('panel',
           'Orontes, 2025, direct method (whole USD) — the book’s own table',
           [['Orontes, 2025, direct method (whole USD)', '2025'],
            ['Cash received from customers', '41,598,000'],
            ['Cash paid to suppliers and employees', '(32,911,000)'],
            ['Interest and dividends received', '73,800'],
            ['Interest paid', '(390,000)'],
            ['Income taxes paid', '(839,700)'],
            ['Net cash provided by operating activities', '7,531,100']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.1?',
             'o': ['Purpose and structure of the statement of cash flows',
                   'Classifying cash flows',
                   'The direct method and required disclosures',
                   'Limitations and links between the four statements'],
             'a': 'A',
             'why': 'The book numbers “Purpose and structure of the '
                    'statement of cash flows” as section 5.1.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.2?',
             'o': ['Classifying cash flows',
                   'Limitations and links between the four statements',
                   'The indirect method',
                   'The direct method and required disclosures'],
             'a': 'A',
             'why': 'The book numbers “Classifying cash flows” as section '
                    '5.2.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.3?',
             'o': ['The direct method and required disclosures',
                   'The indirect method',
                   'Classifying cash flows',
                   'Limitations and links between the four statements'],
             'a': 'B',
             'why': 'The book numbers “The indirect method” as section 5.3.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.4?',
             'o': ['Classifying cash flows',
                   'The direct method and required disclosures',
                   'Limitations and links between the four statements',
                   'Purpose and structure of the statement of cash flows'],
             'a': 'B',
             'why': 'The book numbers “The direct method and required '
                    'disclosures” as section 5.4.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Two companies make the same interest payments. One '
                  'reports under U.S. GAAP, the other under IFRS and '
                  'classifies interest as financing. Which limitation does '
                  'this show?',
             'o': ['Classification differences reduce comparability',
                   'Cash flows depend on estimates',
                   'Noncash items are omitted',
                   'The statement uses historical cost'],
             'a': 'A',
             'why': 'The same payment can land in different sections. B is '
                    'wrong: No estimate is involved. C is wrong: Interest '
                    'paid is a cash flow.',
             'src': 'P5-19'},
            {'t': 'MCQ',
             'q': 'A company stops replacing its old machines. What is the '
                  'likely short-term effect on its statement of cash flows?',
             'o': ['Operating cash flow falls immediately',
                   'Financing inflows rise',
                   'Investing outflows fall, so total cash looks strong even '
                   'though the future may be weaker',
                   'Nothing changes'],
             'a': 'C',
             'why': 'One year of cash flows can hide underinvestment. A is '
                    'wrong: Operations are not directly affected at first. B '
                    'is wrong: No financing is involved.',
             'src': 'P5-20'},
            {'t': 'MCQ',
             'q': 'Orontes declared dividends of $450,000 in 2025, and '
                  'dividends payable rose by $400,000. What are dividends '
                  'paid in the financing section (whole USD)?',
             'o': ['50,000', '400,000', '450,000', '850,000'],
             'a': 'A',
             'why': 'Declared minus the increase in the unpaid amount. B is '
                    'wrong: This is only the unpaid part. C is wrong: This '
                    'uses dividends declared, not paid.',
             'src': 'P5-21'},
            {'t': 'MCQ',
             'q': "Orontes's net accounts receivable rose by $384,000 on its "
                  'balance sheet. Where does this change appear?',
             'o': ['As an investing outflow',
                   'In the statement of changes in equity',
                   'Nowhere; balance sheet changes are not used',
                   'As a deduction in operating activities (indirect '
                   'method)'],
             'a': 'D',
             'why': 'Balance sheet changes in operating items drive the '
                    'indirect method. A is wrong: Trade receivables are '
                    'operating. B is wrong: Receivables are not an equity '
                    'account.',
             'src': 'P5-22'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Two companies make the same interest payments. One reports under '
           'U.S. GAAP, the other under IFRS and classifies interest as '
           'financing. Which limitation does this show?',
           ['Classification differences reduce comparability',
            'Cash flows depend on estimates',
            'Noncash items are omitted',
            'The statement uses historical cost'],
           'A',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'The same payment can land in different sections. B is wrong: No '
           'estimate is involved. C is wrong: Interest paid is a cash flow.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['investing activities', 'الأنشطة الاستثمارية']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A glossary term and its translation are a pair the book '
                  'itself gives.',
             'a': 'T',
             'why': 'The term tables in each section are the book’s own.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company using the direct method must also:',
             'o': ['present a reconciliation of net income to operating cash '
                   'flow',
                   'stop disclosing noncash activities',
                   'classify interest paid as financing',
                   'present an income statement by nature'],
             'a': 'A',
             'why': 'The reconciliation is still required. B is wrong: '
                    'Noncash disclosures are always required. C is wrong: '
                    'Interest paid stays operating.',
             'src': 'P5-24'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f4',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['investing activities'],
           'The direct method shows the main classes of operating receipts '
           'and payments, such as cash from customers and cash paid to '
           'suppliers. The FASB encourages it, but few companies use it. A '
           'company that uses it must still show the reconciliation of net '
           'income to operating cash flow.')]}
