# -*- coding: utf-8 -*-
"""Handout 5.6, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '5.6',
 'n': 6,
 'pages': 5,
 'title': 'The whole chapter',
 'sub': 'every section, shuffled, and the chapter’s own case set',
 'covers': ['sec:summary',
            'sc:SC5-5',
            'sc:SC5-6',
            'sc:SC5-7',
            'sc:SC5-8',
            'sc:SC5-9',
            'term:statement of cash flows',
            'term:cash equivalents',
            'term:operating activities',
            'term:investing activities',
            'term:financing activities',
            'term:indirect method',
            'term:direct method',
            'term:noncash investing and financing activities',
            'case:C5-1',
            'case:C5-2',
            'case:C5-3',
            'case:C5-4',
            'case:C5-5',
            'case:C5-6'],
 'skills': [('review', 0)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Answer every one of these now. They come from every part of the '
           'chapter, in no particular order.',
           [['This handout settles', 'where it is answered'],
            ['every section of the chapter, shuffled', 'cycle A'],
            ['the chapter’s own case set', 'cycle B'],
            ['and you mark your own answers', 'at every checkpoint']],
           [{'t': 'MCQ',
             'q': 'Under the indirect method, how does Orontes treat the '
                  '384,000 increase in net accounts receivable?',
             'o': ['Adds it to net income',
                   'Shows it in investing activities',
                   'Subtracts it from net income',
                   'Ignores it'],
             'a': 'C',
             'why': 'Revenue was recorded but not yet collected. A is wrong: '
                    'An increase in an operating asset is subtracted. B is '
                    'wrong: Trade receivables are operating.',
             'src': 'SC5-5'},
            {'t': 'MCQ',
             'q': 'A company sells equipment with a carrying amount of '
                  '$40,000 for $55,000. How is the sale shown under the '
                  'indirect method?',
             'o': ['Add $15,000 in operating; show $55,000 in investing',
                   'Subtract the $15,000 gain in operating; show $55,000 in '
                   'investing',
                   'Show $15,000 in investing only',
                   'Show $55,000 in operating'],
             'a': 'B',
             'why': 'The gain is removed from operating; the full proceeds '
                    'are investing. A is wrong: A gain is subtracted, not '
                    'added. C is wrong: Investing shows the full proceeds, '
                    'not the gain.',
             'src': 'SC5-6'},
            {'t': 'MCQ',
             'q': "A company's sales were $500,000, all on credit. Accounts "
                  'receivable increased by $40,000. How much cash was '
                  'received from customers?',
             'o': ['$40,000', '$460,000', '$500,000', '$540,000'],
             'a': 'B',
             'why': 'Part of the sales has not yet been collected. A is '
                    'wrong: This is only the change in receivables. C is '
                    'wrong: Sales are not all collected in cash.',
             'src': 'SC5-7'},
            {'t': 'MCQ',
             'q': 'A company uses the indirect method. Which amounts must it '
                  'disclose?',
             'o': ['Interest paid and income taxes paid',
                   'Cash received from customers',
                   'Cash paid to suppliers',
                   'Gross profit in cash terms'],
             'a': 'A',
             'why': 'These are required supplemental disclosures under the '
                    'indirect method. B is wrong: This is part of the direct '
                    'method, not a required disclosure. C is wrong: This is '
                    'part of the direct method.',
             'src': 'SC5-8'},
            {'t': 'MCQ',
             'q': 'How can a company increase its operating cash flow at '
                  'year-end without improving its business?',
             'o': ['By recording more depreciation',
                   'By issuing new shares',
                   'By revaluing its land',
                   'By delaying payments to suppliers until January'],
             'a': 'D',
             'why': 'Timing of payments shifts operating cash between years. '
                    'A is wrong: Depreciation is noncash; it does not change '
                    'cash flow. B is wrong: Share issues are financing '
                    'inflows.',
             'src': 'SC5-9'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.1?',
             'o': ['Purpose and structure of the statement of cash flows',
                   'The direct method and required disclosures',
                   'The indirect method',
                   'Classifying cash flows'],
             'a': 'A',
             'why': 'The book numbers “Purpose and structure of the '
                    'statement of cash flows” as section 5.1.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.2?',
             'o': ['Classifying cash flows',
                   'The direct method and required disclosures',
                   'Purpose and structure of the statement of cash flows',
                   'The indirect method'],
             'a': 'A',
             'why': 'The book numbers “Classifying cash flows” as section '
                    '5.2.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.3?',
             'o': ['Classifying cash flows',
                   'The indirect method',
                   'Purpose and structure of the statement of cash flows',
                   'The direct method and required disclosures'],
             'a': 'B',
             'why': 'The book numbers “The indirect method” as section 5.3.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.4?',
             'o': ['The indirect method',
                   'The direct method and required disclosures',
                   'Purpose and structure of the statement of cash flows',
                   'Classifying cash flows'],
             'a': 'B',
             'why': 'The book numbers “The direct method and required '
                    'disclosures” as section 5.4.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 5.5?',
             'o': ['The indirect method',
                   'Classifying cash flows',
                   'Limitations and links between the four statements',
                   'Purpose and structure of the statement of cash flows'],
             'a': 'C',
             'why': 'The book numbers “Limitations and links between the '
                    'four statements” as section 5.5.'}]),
          ('page',),
          ('cycle', 'A', 'The whole chapter, in order'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'The sections of a chapter have to be taken in order, '
                  'because each one uses what the one before it settled.',
             'a': 'T',
             'why': 'The map shows the order the decisions have to be taken '
                    'in.'}]),
          ('move', 'MODEL', ''),
          ('fig', 'chmap'),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': '“section 5.1” — which part of the chapter is this?',
             'o': ['The direct method and required disclosures',
                   'Classifying cash flows',
                   'Purpose and structure of the statement of cash flows',
                   'The indirect method'],
             'a': 'C',
             'why': 'The book numbers it 5.1.'},
            {'t': 'MCQ',
             'q': '“section 5.2” — which part of the chapter is this?',
             'o': ['The direct method and required disclosures',
                   'Classifying cash flows',
                   'The indirect method',
                   'Purpose and structure of the statement of cash flows'],
             'a': 'B',
             'why': 'The book numbers it 5.2.'},
            {'t': 'MCQ',
             'q': '“section 5.3” — which part of the chapter is this?',
             'o': ['The direct method and required disclosures',
                   'The indirect method',
                   'Classifying cash flows',
                   'Purpose and structure of the statement of cash flows'],
             'a': 'B',
             'why': 'The book numbers it 5.3.'},
            {'t': 'MATCH',
             'q': 'Write the letter of the section number beside each '
                  'section title. Every number is used once.',
             'left': ['Purpose and structure of the statement of cash flows',
                      'Classifying cash flows',
                      'The indirect method',
                      'The direct method and required disclosures',
                      'Limitations and links between the four statements'],
             'right': ['5.1', '5.2', '5.3', '5.4', '5.5'],
             'a': ['A', 'B', 'C', 'D', 'E'],
             'whys': ['', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'How can a company increase its operating cash flow at '
                  'year-end without improving its business?',
             'o': ['By recording more depreciation',
                   'By issuing new shares',
                   'By revaluing its land',
                   'By delaying payments to suppliers until January'],
             'a': 'D',
             'why': 'Timing of payments shifts operating cash between years. '
                    'A is wrong: Depreciation is noncash; it does not change '
                    'cash flow. B is wrong: Share issues are financing '
                    'inflows.',
             'src': 'SC5-9'}]),
          ('pair',
           'Compare every answer with your partner first.',
           'name the section each question belongs to. Most disagreements '
           'turn out to be about the section, not the answer.'),
          ('check',
           'Under the indirect method, how does Orontes treat the 384,000 '
           'increase in net accounts receivable?',
           ['Adds it to net income',
            'Shows it in investing activities',
            'Subtracts it from net income',
            'Ignores it'],
           'C',
           'go back to the MODEL move of cycle A and find the section this '
           'question belongs to.',
           'Revenue was recorded but not yet collected. A is wrong: An '
           'increase in an operating asset is subtracted. B is wrong: Trade '
           'receivables are operating.'),
          ('cycle', 'B', 'The chapter’s case set'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'In a case question, the exhibit has to be read and '
                  'adjusted before any figure is worked out.',
             'a': 'T',
             'why': 'Every later answer depends on the adjusted exhibit.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'The chapter’s case set, item by item',
           [['Item', 'What it asks'],
            ['C5-1',
             'Classify each 2026 cash flow. (On the exam screen you would '
             'drag each item into a box.)'],
            ['C5-2',
             "Enter Barada's net cash provided by operating activities for "
             '2026 (indirect method).'],
            ['C5-3',
             "Enter Barada's net cash from investing activities for 2026."],
            ['C5-4',
             "Enter Barada's net cash used in financing activities for 2026 "
             '(as a positive number).'],
            ['C5-5', "Enter Barada's cash at December 31, 2026."],
            ['C5-6',
             'Where does Barada show the 2026 dividend declared on December '
             '15 and payable in January 2027? [select]']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which of these does item C5-1 ask for?',
             'o': ["Enter Barada's net cash from investing activities for "
                   '2026.',
                   'Classify each 2026 cash flow. (On the exam screen you '
                   'would drag each ',
                   "Enter Barada's net cash used in financing activities for "
                   '2026 (as a po',
                   "Enter Barada's net cash provided by operating activities "
                   'for 2026 (ind'],
             'a': 'B',
             'why': 'The book states item C5-1 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C5-2 ask for?',
             'o': ['Classify each 2026 cash flow. (On the exam screen you '
                   'would drag each ',
                   "Enter Barada's net cash used in financing activities for "
                   '2026 (as a po',
                   "Enter Barada's net cash provided by operating activities "
                   'for 2026 (ind',
                   "Enter Barada's net cash from investing activities for "
                   '2026.'],
             'a': 'C',
             'why': 'The book states item C5-2 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C5-3 ask for?',
             'o': ["Enter Barada's net cash used in financing activities for "
                   '2026 (as a po',
                   "Enter Barada's net cash from investing activities for "
                   '2026.',
                   "Enter Barada's net cash provided by operating activities "
                   'for 2026 (ind',
                   'Classify each 2026 cash flow. (On the exam screen you '
                   'would drag each '],
             'a': 'B',
             'why': 'The book states item C5-3 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C5-4 ask for?',
             'o': ['Classify each 2026 cash flow. (On the exam screen you '
                   'would drag each ',
                   "Enter Barada's net cash provided by operating activities "
                   'for 2026 (ind',
                   "Enter Barada's net cash from investing activities for "
                   '2026.',
                   "Enter Barada's net cash used in financing activities for "
                   '2026 (as a po'],
             'a': 'D',
             'why': 'The book states item C5-4 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C5-5 ask for?',
             'o': ['Classify each 2026 cash flow. (On the exam screen you '
                   'would drag each ',
                   "Enter Barada's net cash provided by operating activities "
                   'for 2026 (ind',
                   "Enter Barada's cash at December 31, 2026.",
                   "Enter Barada's net cash from investing activities for "
                   '2026.'],
             'a': 'C',
             'why': 'The book states item C5-5 in those words.'},
            {'t': 'MCQ',
             'q': 'Which of these does item C5-6 ask for?',
             'o': ['Where does Barada show the 2026 dividend declared on '
                   'December 15 and p',
                   'Classify each 2026 cash flow. (On the exam screen you '
                   'would drag each ',
                   "Enter Barada's net cash from investing activities for "
                   '2026.',
                   "Enter Barada's net cash provided by operating activities "
                   'for 2026 (ind'],
             'a': 'A',
             'why': 'The book states item C5-6 in those words.'}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'Under the indirect method, how does Orontes treat the '
                  '384,000 increase in net accounts receivable?',
             'o': ['Adds it to net income',
                   'Shows it in investing activities',
                   'Subtracts it from net income',
                   'Ignores it'],
             'a': 'C',
             'why': 'Revenue was recorded but not yet collected. A is wrong: '
                    'An increase in an operating asset is subtracted. B is '
                    'wrong: Trade receivables are operating.',
             'src': 'SC5-5'}]),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company sells equipment with a carrying amount of '
                  '$40,000 for $55,000. How is the sale shown under the '
                  'indirect method?',
             'o': ['Add $15,000 in operating; show $55,000 in investing',
                   'Subtract the $15,000 gain in operating; show $55,000 in '
                   'investing',
                   'Show $15,000 in investing only',
                   'Show $55,000 in operating'],
             'a': 'B',
             'why': 'The gain is removed from operating; the full proceeds '
                    'are investing. A is wrong: A gain is subtracted, not '
                    'added. C is wrong: Investing shows the full proceeds, '
                    'not the gain.',
             'src': 'SC5-6'}]),
          ('check',
           'What has to be settled before any figure in a case set is worked '
           'out?',
           ['the exhibit, adjusted for every note that goes with it',
            'the method the company uses',
            'the tax rate',
            'the order of the items'],
           'A',
           'reread the case panel in the MODEL move of cycle B.',
           'Every later answer depends on the adjusted exhibit.'),
          ('build',
           'chmap',
           'Rebuild the chapter map. Write every section in order and what '
           'each one settles.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a student starting this chapter tomorrow',
           'In four or five sentences, write what the whole chapter settles, '
           'section by section.',
           ['statement of cash flows',
            'cash equivalents',
            'operating activities',
            'investing activities'],
           '5.1: Purpose and structure of the statement of cash flows. 5.2: '
           'Classifying cash flows. 5.3: The indirect method. 5.4: The '
           'direct method and required disclosures. 5.5: Limitations and '
           'links between the four statements.')]}
