# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C13-1': ('case item C13-1', []),
    'C13-2': ('case item C13-2', []),
    'C13-3': ('case item C13-3', []),
    'C13-4': ('case item C13-4', []),
    'C13-5': ('case item C13-5', []),
    'C13-6': ('case item C13-6', []),
    'P13-01': ('practice item P13-01', []),
    'P13-02': ('practice item P13-02', []),
    'P13-03': ('practice item P13-03', []),
    'P13-04': ('practice item P13-04', []),
    'P13-05': ('practice item P13-05', []),
    'P13-06': ('practice item P13-06', []),
    'P13-07': ('practice item P13-07', []),
    'P13-08': ('practice item P13-08', []),
    'P13-09': ('practice item P13-09', []),
    'P13-10': ('practice item P13-10', []),
    'P13-11': ('practice item P13-11', []),
    'P13-12': ('practice item P13-12', []),
    'P13-13': ('practice item P13-13', []),
    'P13-14': ('practice item P13-14', []),
    'P13-15': ('practice item P13-15', []),
    'P13-16': ('practice item P13-16', []),
    'P13-17': ('practice item P13-17', []),
    'P13-18': ('practice item P13-18', []),
    'P13-19': ('practice item P13-19', []),
    'P13-20': ('practice item P13-20', []),
    'SC13-1': ('section-check item SC13-1', []),
    'SC13-2': ('section-check item SC13-2', []),
    'SC13-3': ('section-check item SC13-3', []),
    'SC13-4': ('section-check item SC13-4', []),
    'SC13-5': ('section-check item SC13-5', []),
    'SC13-6': ('section-check item SC13-6', []),
    'SC13-7': ('section-check item SC13-7', []),
    'SC13-8': ('section-check item SC13-8', []),
    'SC13-9': ('section-check item SC13-9', []),
    'term:current tax expense': ("term-bridge row 'current tax expense'", []),
    'term:deductible temporary difference': ("term-bridge row 'deductible temporary difference'", []),
    'term:deferred tax asset': ("term-bridge row 'deferred tax asset'", []),
    'term:deferred tax expense': ("term-bridge row 'deferred tax expense'", []),
    'term:deferred tax liability': ("term-bridge row 'deferred tax liability'", []),
    'term:effective tax rate': ("term-bridge row 'effective tax rate'", []),
    'term:enacted tax rate': ("term-bridge row 'enacted tax rate'", []),
    'term:interperiod tax allocation': ("term-bridge row 'interperiod tax allocation'", []),
    'term:intraperiod tax allocation': ("term-bridge row 'intraperiod tax allocation'", []),
    'term:net operating loss carryforward': ("term-bridge row 'net operating loss carryforward'", []),
    'term:permanent difference': ("term-bridge row 'permanent difference'", []),
    'term:tax basis': ("term-bridge row 'tax basis'", []),
    'term:taxable income': ("term-bridge row 'taxable income'", []),
    'term:taxable temporary difference': ("term-bridge row 'taxable temporary difference'", []),
    'term:temporary difference': ("term-bridge row 'temporary difference'", []),
    'term:uncertain tax position': ("term-bridge row 'uncertain tax position'", []),
    'term:valuation allowance': ("term-bridge row 'valuation allowance'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C13-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'C13-6': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'SC13-7': 'it sends the reader to F13-08, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
