# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C15-1': ('case item C15-1', []),
    'C15-2': ('case item C15-2', []),
    'C15-3': ('case item C15-3', []),
    'C15-4': ('case item C15-4', []),
    'C15-5': ('case item C15-5', []),
    'C15-6': ('case item C15-6', []),
    'P15-01': ('practice item P15-01', []),
    'P15-02': ('practice item P15-02', []),
    'P15-03': ('practice item P15-03', []),
    'P15-04': ('practice item P15-04', []),
    'P15-05': ('practice item P15-05', []),
    'P15-06': ('practice item P15-06', []),
    'P15-07': ('practice item P15-07', []),
    'P15-08': ('practice item P15-08', []),
    'P15-09': ('practice item P15-09', []),
    'P15-10': ('practice item P15-10', []),
    'P15-11': ('practice item P15-11', []),
    'P15-12': ('practice item P15-12', []),
    'P15-13': ('practice item P15-13', []),
    'P15-14': ('practice item P15-14', []),
    'P15-15': ('practice item P15-15', []),
    'P15-16': ('practice item P15-16', []),
    'SC15-1': ('section-check item SC15-1', []),
    'SC15-10': ('section-check item SC15-10', []),
    'SC15-11': ('section-check item SC15-11', []),
    'SC15-2': ('section-check item SC15-2', []),
    'SC15-3': ('section-check item SC15-3', []),
    'SC15-4': ('section-check item SC15-4', []),
    'SC15-5': ('section-check item SC15-5', []),
    'SC15-6': ('section-check item SC15-6', []),
    'SC15-7': ('section-check item SC15-7', []),
    'SC15-8': ('section-check item SC15-8', []),
    'SC15-9': ('section-check item SC15-9', []),
    'term:component of an entity': ("term-bridge row 'component of an entity'", []),
    'term:comprehensive income': ("term-bridge row 'comprehensive income'", []),
    'term:discontinued operation': ("term-bridge row 'discontinued operation'", []),
    'term:disposal group': ("term-bridge row 'disposal group'", []),
    'term:fair value less cost to sell': ("term-bridge row 'fair value less cost to sell'", []),
    'term:gain': ("term-bridge row 'gain'", []),
    'term:held for sale': ("term-bridge row 'held for sale'", []),
    'term:holding gain or loss': ("term-bridge row 'holding gain or loss'", []),
    'term:loss': ("term-bridge row 'loss'", []),
    'term:period cost': ("term-bridge row 'period cost'", []),
    'term:reclassification adjustment': ("term-bridge row 'reclassification adjustment'", []),
    'term:strategic shift': ("term-bridge row 'strategic shift'", []),
    'term:systematic and rational allocation': ("term-bridge row 'systematic and rational allocation'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C15-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'SC15-10': 'it sends the reader to F15-07, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC15-6': 'it sends the reader to F15-04, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
