# -*- coding: utf-8 -*-
"""Handout 6.3, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '6.3',
 'n': 3,
 'pages': 6,
 'title': 'Transferring receivables: sale or secured borrowing?',
 'sub': 'section 6.3 of the book',
 'covers': ['sec:6.3',
            'p:P6-14',
            'p:P6-15',
            'p:P6-16',
            'sc:P6-14',
            'term:current expected credit losses (cecl)',
            'term:write-off',
            'term:secured borrowing',
            'term:notes receivable',
            'term:direct write-off method',
            'term:holdback (due from factor)',
            'term:legal isolation'],
 'skills': [('read3', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Answer every one of these now, from what you already know or by '
           'guessing. You are not expected to get them right: you are about '
           'to be shown where each answer comes from.',
           [['This handout settles', 'where it is answered'],
            ['Transferring receivables: sale or secured borrowing?',
             'cycle A'],
            ['Transfer and what goes with it', 'cycle B'],
            ['and you mark your own answers', 'at every checkpoint']],
           [{'t': 'MCQ',
             'q': 'Which item does the book pair with “Current: 250,000 at '
                  'an expected loss rate of 2%”?',
             'o': ['Aging',
                   'Transfer T4',
                   'Transfer T1',
                   'Allowance account'],
             'a': 'A',
             'why': 'The book’s own table pairs Aging with “Current: 250,000 '
                    'at an expected loss rate of 2%”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “1–60 days past due: '
                  '90,000 at an expected loss rate of 10%”?',
             'o': ['Transfer T4',
                   'Allowance account',
                   'Aging',
                   'Transfer T2 details'],
             'a': 'C',
             'why': 'The book’s own table pairs Aging with “1–60 days past '
                    'due: 90,000 at an expected loss rate of 10%”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Over 60 days past '
                  'due: 40,000 at an expected loss rate of 40%”?',
             'o': ['Aging', 'Transfer T3', 'Transfer T1', 'Transfer T4'],
             'a': 'A',
             'why': 'The book’s own table pairs Aging with “Over 60 days '
                    'past due: 40,000 at an expected loss rate of 40%”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Beginning balance '
                  '18,000 (credit). Write-offs during 2025: 24,000. '
                  'Recoveries: 1,000.”?',
             'o': ['Transfer T1',
                   'Transfer T3',
                   'Allowance account',
                   'Aging'],
             'a': 'C',
             'why': 'The book’s own table pairs Allowance account with '
                    '“Beginning balance 18,000 (credit). Write-offs during '
                    '2025: 24,000. Recoveries: 1,000.”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Receivables '
                  'transferred to a bank, but Orontes must repurchase them '
                  'before they mature.”?',
             'o': ['Transfer T3',
                   'Aging',
                   'Transfer T2 details',
                   'Allowance account'],
             'a': 'A',
             'why': 'The book’s own table pairs Transfer T3 with '
                    '“Receivables transferred to a bank, but Orontes must '
                    'repurchase them before they mature.”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Receivables pledged '
                  'as collateral for a bank loan; Orontes still collects '
                  'them.”?',
             'o': ['Aging',
                   'Transfer T4',
                   'Transfer T2 details',
                   'Transfer T1'],
             'a': 'B',
             'why': 'The book’s own table pairs Transfer T4 with '
                    '“Receivables pledged as collateral for a bank loan; '
                    'Orontes still collects them.”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Carrying amount '
                  "200,000; factor's fee 2%; holdback 4%; fair value of the "
                  'recourse obligation 3,000.”?',
             'o': ['Transfer T1',
                   'Transfer T3',
                   'Transfer T4',
                   'Transfer T2 details'],
             'a': 'D',
             'why': 'The book’s own table pairs Transfer T2 details with '
                    "“Carrying amount 200,000; factor's fee 2%; holdback 4%; "
                    'fair value of the recourse obligation 3,000.”.'},
            {'t': 'TF',
             'q': 'The book gives the Details (whole USD) of Aging as '
                  '“Current: 250,000 at an expected loss rate of 2%”.',
             'a': 'T',
             'why': 'The book pairs Aging with “Current: 250,000 at an '
                    'expected loss rate of 2%”.'},
            {'t': 'TF',
             'q': 'The book gives the Details (whole USD) of Aging as '
                  '“Receivables transferred to a bank, but Orontes must '
                  'repurchase them before they mature.”.',
             'a': 'F',
             'why': 'The book pairs Aging with “1–60 days past due: 90,000 '
                    'at an expected loss rate of 10%”, not with “Receivables '
                    'transferred to a bank, but Orontes must repurchase them '
                    'before they mature.”.'},
            {'t': 'TF',
             'q': 'The book gives the Details (whole USD) of Aging as “Over '
                  '60 days past due: 40,000 at an expected loss rate of '
                  '40%”.',
             'a': 'T',
             'why': 'The book pairs Aging with “Over 60 days past due: '
                    '40,000 at an expected loss rate of 40%”.'}]),
          ('page',),
          ('cycle',
           'A',
           'Transferring receivables: sale or secured borrowing?'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'The book gives the Details (whole USD) of Aging as '
                  '“Current: 250,000 at an expected loss rate of 2%”.',
             'a': 'T',
             'why': 'The book pairs Aging with “Current: 250,000 at an '
                    'expected loss rate of 2%”.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f3'),
          ('panel',
           'Item — the book’s own table',
           [['Item', 'Details (whole USD)'],
            ['Aging', 'Current: 250,000 at an expected loss rate of 2%'],
            ['Aging',
             '1–60 days past due: 90,000 at an expected loss rate of 10%'],
            ['Aging',
             'Over 60 days past due: 40,000 at an expected loss rate of 40%'],
            ['Allowance account',
             'Beginning balance 18,000 (credit). Write-offs during 2025: '
             '24,000. Recoveries: 1,000.'],
            ['Transfer T1',
             'Receivables sold to a factor without recourse. The factor may '
             'resell them. Orontes has no right or duty to buy them back.'],
            ['Transfer T2',
             'Receivables transferred with recourse. They are legally '
             'isolated from Orontes, the factor may pledge them, and Orontes '
             'cannot buy them back.'],
            ['Transfer T3',
             'Receivables transferred to a bank, but Orontes must repurchase '
             'them before they mature.'],
            ['Transfer T4',
             'Receivables pledged as collateral for a bank loan; Orontes '
             'still collects them.'],
            ['Transfer T2 details',
             "Carrying amount 200,000; factor's fee 2%; holdback 4%; fair "
             'value of the recourse obligation 3,000.']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which item does the book pair with “Current: 250,000 at '
                  'an expected loss rate of 2%”?',
             'o': ['Transfer T2',
                   'Allowance account',
                   'Aging',
                   'Transfer T3'],
             'a': 'C',
             'why': 'The book’s own table pairs Aging with “Current: 250,000 '
                    'at an expected loss rate of 2%”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “1–60 days past due: '
                  '90,000 at an expected loss rate of 10%”?',
             'o': ['Transfer T2',
                   'Transfer T2 details',
                   'Aging',
                   'Transfer T4'],
             'a': 'C',
             'why': 'The book’s own table pairs Aging with “1–60 days past '
                    'due: 90,000 at an expected loss rate of 10%”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Over 60 days past '
                  'due: 40,000 at an expected loss rate of 40%”?',
             'o': ['Transfer T4',
                   'Transfer T2 details',
                   'Transfer T3',
                   'Aging'],
             'a': 'D',
             'why': 'The book’s own table pairs Aging with “Over 60 days '
                    'past due: 40,000 at an expected loss rate of 40%”.'},
            {'t': 'MCQ',
             'q': 'Which item does the book pair with “Beginning balance '
                  '18,000 (credit). Write-offs during 2025: 24,000. '
                  'Recoveries: 1,000.”?',
             'o': ['Transfer T2',
                   'Allowance account',
                   'Transfer T1',
                   'Transfer T3'],
             'a': 'B',
             'why': 'The book’s own table pairs Allowance account with '
                    '“Beginning balance 18,000 (credit). Write-offs during '
                    '2025: 24,000. Recoveries: 1,000.”.'},
            {'t': 'TF',
             'q': 'The book gives the Details (whole USD) of Aging as '
                  '“Current: 250,000 at an expected loss rate of 2%”.',
             'a': 'T',
             'why': 'The book pairs Aging with “Current: 250,000 at an '
                    'expected loss rate of 2%”.'},
            {'t': 'TF',
             'q': 'The book gives the Details (whole USD) of Aging as '
                  '“Beginning balance 18,000 (credit). Write-offs during '
                  '2025: 24,000. Recoveries: 1,000.”.',
             'a': 'F',
             'why': 'The book pairs Aging with “1–60 days past due: 90,000 '
                    'at an expected loss rate of 10%”, not with “Beginning '
                    'balance 18,000 (credit). Write-offs during 2025: '
                    '24,000. Recoveries: 1,000.”.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Receivables are factored with substantial recourse. The '
                  'transfer meets the three ASC 860 conditions. Which '
                  'statement is MOST likely correct?',
             'o': ['Both frameworks treat it as a borrowing.',
                   'U.S. GAAP treats it as a sale; IFRS 9 may treat it as a '
                   'borrowing.',
                   'Both frameworks treat it as a sale with no liability.',
                   'IFRS treats it as a sale; U.S. GAAP treats it as a '
                   'borrowing.'],
             'a': 'B',
             'why': 'IFRS 9 focuses on risks and rewards; substantial '
                    'recourse often keeps the risk with the seller. A is '
                    'wrong: Under U.S. GAAP the ASC 860 conditions decide, '
                    'and they are met. C is wrong: A U.S. GAAP sale with '
                    'recourse records a recourse liability.',
             'src': 'P6-14'},
            {'t': 'MCQ',
             'q': 'Spiral review (Chapter 1). Where is the allowance for '
                  'credit losses reported?',
             'o': ['As a liability',
                   'As an expense',
                   'As a contra-asset, deducted from accounts receivable',
                   'As a reduction of equity'],
             'a': 'C',
             'why': 'It reduces receivables to the amount expected to be '
                    'collected. A is wrong: It is a contra-asset, not a '
                    'liability. B is wrong: The expense is a separate '
                    'account; the allowance is the balance sheet total.',
             'src': 'P6-15'},
            {'t': 'MCQ',
             'q': 'Spiral review (Chapter 1). Recording credit loss expense '
                  'in the period of the sale, before any customer defaults, '
                  'is an example of:',
             'o': ['the cash basis',
                   'the direct write-off method',
                   'immediate recognition',
                   'the matching principle'],
             'a': 'D',
             'why': 'The expected loss is matched with the revenue of the '
                    'same period. A is wrong: No cash moves when the expense '
                    'is recorded. B is wrong: The direct method waits until '
                    'a balance is written off.',
             'src': 'P6-16'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Receivables are factored with substantial recourse. The transfer '
           'meets the three ASC 860 conditions. Which statement is MOST '
           'likely correct?',
           ['Both frameworks treat it as a borrowing.',
            'U.S. GAAP treats it as a sale; IFRS 9 may treat it as a '
            'borrowing.',
            'Both frameworks treat it as a sale with no liability.',
            'IFRS treats it as a sale; U.S. GAAP treats it as a borrowing.'],
           'B',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'IFRS 9 focuses on risks and rewards; substantial recourse often '
           'keeps the risk with the seller. A is wrong: Under U.S. GAAP the '
           'ASC 860 conditions decide, and they are met. C is wrong: A U.S. '
           'GAAP sale with recourse records a recourse liability.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Transfer — the book’s own table',
           [['Transfer', 'Category'],
            ['T1', ''],
            ['T2', ''],
            ['T3', ''],
            ['T4', '']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['current expected credit losses (CECL)',
             'الخسائر الائتمانية المتوقعة الحالية'],
            ['write-off', 'شطب (إعدام) الدين'],
            ['secured borrowing', 'اقتراض مضمون'],
            ['notes receivable', 'أوراق القبض'],
            ['direct write-off method', 'طريقة الشطب المباشر'],
            ['holdback (due from factor)',
             'المبلغ المحتجز (مستحق من شركة التخصيم)'],
            ['legal isolation', 'العزل القانوني']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MATCH',
             'q': 'Write the letter of the Arabic term beside each English '
                  'term. Every term is used once.',
             'left': ['secured borrowing',
                      'holdback (due from factor)',
                      'direct write-off method',
                      'notes receivable',
                      'legal isolation',
                      'write-off'],
             'right': ['المبلغ المحتجز (مستحق من شركة التخصيم)',
                       'طريقة الشطب المباشر',
                       'شطب (إعدام) الدين',
                       'أوراق القبض',
                       'العزل القانوني',
                       'اقتراض مضمون'],
             'a': ['F', 'A', 'B', 'D', 'E', 'C'],
             'whys': ['', '', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'TF',
             'q': 'Writing a term in English is part of answering the '
                  'question, not an extra.',
             'a': 'T',
             'why': 'The exam marks the term, so the English word is the '
                    'answer.'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f3',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['current expected credit losses (CECL)',
            'write-off',
            'secured borrowing',
            'notes receivable'],
           'A company that needs cash before its customers pay can use its '
           'receivables in two ways. It can use them as collateral for a '
           'loan (pledging), or it can transfer them to a finance company '
           'called a factor. This is factoring. The accounting question is '
           'simple: is the transfer a sale, or is it really a loan?')]}
