# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C4-1': ('case item C4-1', []),
    'C4-2': ('case item C4-2', []),
    'C4-3': ('case item C4-3', []),
    'C4-4': ('case item C4-4', []),
    'C4-5': ('case item C4-5', []),
    'C4-6': ('case item C4-6', []),
    'P4-01': ('practice item P4-01', []),
    'P4-02': ('practice item P4-02', []),
    'P4-03': ('practice item P4-03', []),
    'P4-04': ('practice item P4-04', []),
    'P4-05': ('practice item P4-05', []),
    'P4-06': ('practice item P4-06', []),
    'P4-07': ('practice item P4-07', []),
    'P4-08': ('practice item P4-08', []),
    'P4-09': ('practice item P4-09', []),
    'P4-10': ('practice item P4-10', []),
    'P4-11': ('practice item P4-11', []),
    'P4-12': ('practice item P4-12', []),
    'P4-13': ('practice item P4-13', []),
    'P4-14': ('practice item P4-14', []),
    'P4-15': ('practice item P4-15', []),
    'P4-16': ('practice item P4-16', []),
    'P4-17': ('practice item P4-17', []),
    'P4-18': ('practice item P4-18', []),
    'P4-19': ('practice item P4-19', []),
    'P4-20': ('practice item P4-20', []),
    'P4-21': ('practice item P4-21', []),
    'P4-22': ('practice item P4-22', []),
    'P4-23': ('practice item P4-23', []),
    'P4-24': ('practice item P4-24', []),
    'P4-25': ('practice item P4-25', []),
    'P4-26': ('practice item P4-26', []),
    'SC4-1': ('section-check item SC4-1', []),
    'SC4-2': ('section-check item SC4-2', []),
    'SC4-3': ('section-check item SC4-3', []),
    'SC4-4': ('section-check item SC4-4', []),
    'SC4-5': ('section-check item SC4-5', []),
    'SC4-6': ('section-check item SC4-6', []),
    'SC4-7': ('section-check item SC4-7', []),
    'SC4-8': ('section-check item SC4-8', []),
    'SC4-9': ('section-check item SC4-9', []),
    'term:appropriated retained earnings': ("term-bridge row 'appropriated retained earnings'", []),
    'term:contributed capital': ("term-bridge row 'contributed capital'", []),
    'term:cost method': ("term-bridge row 'cost method'", []),
    'term:date of record': ("term-bridge row 'date of record'", []),
    'term:declaration date': ("term-bridge row 'declaration date'", []),
    'term:issued shares': ("term-bridge row 'issued shares'", []),
    'term:liquidating dividend': ("term-bridge row 'liquidating dividend'", []),
    'term:outstanding shares': ("term-bridge row 'outstanding shares'", []),
    'term:preferred stock': ("term-bridge row 'preferred stock'", []),
    'term:prior-period adjustment': ("term-bridge row 'prior-period adjustment'", []),
    'term:property dividend': ("term-bridge row 'property dividend'", []),
    'term:statement of changes in equity': ("term-bridge row 'statement of changes in equity'", []),
    'term:stock dividend': ("term-bridge row 'stock dividend'", []),
    'term:stock split': ("term-bridge row 'stock split'", []),
    'term:treasury stock': ("term-bridge row 'treasury stock'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C4-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P4-23': 'it sends the reader to F04-09, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC4-2': 'it sends the reader to F04-02, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
