# -*- coding: utf-8 -*-
"""Book 1 chapter 2 as Workshop handouts, generated by wsgen.

Every item here is multiple choice, true/false, matching,
sorting or a table to complete. The chapter's own section
checks and practice items supply the stems, the options and a
reason for every wrong answer; the chapter's own tables supply
the rest, so no distractor is invented and no stem points at
anything that is not printed beside it.
"""
WORKSHOP = True
GENERATED = True
BK = 1
CH = '2'
BOOK = 'CMA Part 1 \u00b7 Book 1 \u00b7 Financial Reporting'
TITLE = 'CMA Part 1 \u00b7 Book 1 \u00b7 Chapter 2'
SUB = 'The Balance Sheet'
FIGS = 'w1_ch02.figs'
HANDOUTS = [1, 2, 3, 4, 5, 6]
OUT_H = 'CMA_W_B1_Ch02_Handouts.docx'
OUT_K = 'CMA_W_B1_Ch02_AnswerKeys.docx'
SOURCE = 'src/b1_ch02.txt'
OMIT = {'p:P2-12': 'the stem works from the facts of another numbered item, so it cannot be answered from its own page'}
