# -*- coding: utf-8 -*-
"""Handout 2.1, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '2.1',
 'n': 1,
 'pages': 9,
 'title': 'Purpose and structure of the balance sheet',
 'sub': 'section 2.1 of the book',
 'covers': ['sec:2.1',
            'p:P2-01',
            'p:P2-02',
            'p:P2-03',
            'p:P2-04',
            'sc:P2-01',
            'p:P2-05',
            'p:P2-06',
            'term:balance sheet',
            'term:working capital',
            'term:liquidity',
            'term:covenant',
            'term:right of setoff'],
 'skills': [('read1', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['Purpose and structure of the balance sheet',
             'a figure to read · Orontes Foods Inc. (whole USD)',
             'Which question does the balance sheet help users answer MOST '
             'directly?'],
            ['The words this section uses precisely',
             'Account · The English the exam uses, and what it translates · '
             'Orontes Foods Inc. (whole USD)',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['The ',
                       15,
                       " reports a company's assets, liabilities and equity "
                       'at one point in time. It answers three questions for '
                       'investors and lenders. Can the company pay its bills '
                       'in the coming months? This is ',
                       11,
                       '. Can it pay all its debts over time? This is ',
                       11,
                       '.'],
             'bank': ['solvency',
                      'working capital',
                      'current assets',
                      'balance sheet',
                      'liquidity'],
             'a': 'balance sheet · liquidity · solvency',
             'one': True,
             'why': "The book writes: “The balance sheet reports a company's "
                    'assets, liabilities and equity at one point in time. It '
                    'answers three questions for investors and lenders. Can '
                    'the company pay its bills in the coming months? This is '
                    'liquidity. Can it pay all its debts over time? This is '
                    'solvency.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['Some companies, such as banks, list items in order '
                       'of ',
                       11,
                       ' instead, without a current subtotal. All the '
                       'amounts come from the same records as the earlier '
                       'chapters on receivables, inventory, investments and '
                       'long-lived assets. For example, the equity-method '
                       'investments include Jordan Glass Co. ',
                       16,
                       ' come first, from cash down to assets held for '
                       'sale.'],
             'bank': ['Current assets',
                      'working capital',
                      'solvency',
                      'liquidity'],
             'a': 'liquidity · Current assets',
             'one': True,
             'why': 'The book writes: “Some companies, such as banks, list '
                    'items in order of liquidity instead, without a current '
                    'subtotal. All the amounts come from the same records as '
                    'the earlier chapters on receivables, inventory, '
                    'investments and long-lived assets. For example, the '
                    'equity-method investments include Jordan Glass Co. '
                    'Current assets come first, from cash down to assets '
                    'held for sale.”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['Can the company pay its bills in the coming months? '
                       'This is ',
                       11,
                       '. Can it pay all its debts over time? This is ',
                       11,
                       '. Can it raise cash or change its plans if something '
                       'unexpected happens? This is ',
                       23,
                       '.'],
             'bank': ['liquidity',
                      'current assets',
                      'financial flexibility',
                      'solvency',
                      'working capital'],
             'a': 'liquidity · solvency · financial flexibility',
             'one': True,
             'why': 'The book writes: “Can the company pay its bills in the '
                    'coming months? This is liquidity. Can it pay all its '
                    'debts over time? This is solvency. Can it raise cash or '
                    'change its plans if something unexpected happens? This '
                    'is financial flexibility.”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['balance sheet', ''],
              ['working capital', ''],
              ['liquidity', ''],
              ['covenant', ''],
              ['right of setoff', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle', 'A', 'Purpose and structure of the balance sheet'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'Every number in a financial statement belongs to an '
                  'element the framework defines.',
             'a': 'T',
             'why': 'The framework defines the elements, and every amount '
                    'belongs to one of them.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'f1'),
          ('panel',
           'Orontes Foods Inc. (whole USD) — the book’s own table',
           [['Orontes Foods Inc. (whole USD)',
             'Dec 31, 2025',
             'Dec 31, 2024'],
            ['ASSETS', '', ''],
            ['Current assets', '', ''],
            ['Cash', '7,302,100', '2,100,000'],
            ['Trading securities', '42,000', '40,000'],
            ['Accounts receivable, net of allowance (2025: 156,000; 2024: '
             '140,000)',
             '4,144,000',
             '3,760,000'],
            ['Inventory', '2,450,000', '2,300,000'],
            ['Prepaid expenses', '204,000', '180,000'],
            ['Assets held for sale', '46,000', '—'],
            ['Total current assets', '14,188,100', '8,380,000'],
            ['Noncurrent assets', '', ''],
            ['Debt securities (held-to-maturity and available-for-sale)',
             '88,500',
             '90,000'],
            ['Equity securities', '27,000', '25,000'],
            ['Equity-method investments', '1,807,000', '500,000'],
            ['Property, plant and equipment, net of accumulated depreciation '
             '(2025: 11,988,000; 2024: 8,000,000)',
             '14,802,000',
             '16,000,000'],
            ['Brand (indefinite-lived)', '260,000', '300,000'],
            ['Goodwill', '300,000', '950,000'],
            ['Other noncurrent assets', '200,000', '200,000'],
            ['TOTAL ASSETS', '31,672,600', '26,445,000'],
            ["LIABILITIES AND STOCKHOLDERS' EQUITY", '', ''],
            ['Current liabilities', '', ''],
            ['Accounts payable', '2,050,000', '1,900,000'],
            ['Accrued liabilities', '900,000', '850,000'],
            ['Income taxes payable', '350,000', '300,000'],
            ['Contract liabilities', '180,000', '120,000'],
            ['Dividends payable', '400,000', '—'],
            ['Current portion of long-term debt', '400,000', '400,000'],
            ['Total current liabilities', '4,280,000', '3,570,000'],
            ['Long-term debt, less current portion',
             '6,000,000',
             '5,600,000'],
            ['Deferred tax liability', '999,625', '900,000'],
            ['Total liabilities', '11,279,625', '10,070,000'],
            ['Commitments and contingencies (Note 12)', '', ''],
            ["Stockholders' equity", '', ''],
            ['Common stock, $1 par; shares issued and outstanding: 2025 '
             '8,100,000, 2024 8,000,000',
             '8,100,000',
             '8,000,000'],
            ['Additional paid-in capital', '5,400,000', '4,000,000'],
            ['Retained earnings', '6,894,100', '4,375,000'],
            ['Accumulated other comprehensive income (loss)', '(1,125)', '—'],
            ["Total stockholders' equity", '20,392,975', '16,375,000'],
            ["TOTAL LIABILITIES AND STOCKHOLDERS' EQUITY",
             '31,672,600',
             '26,445,000']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which part of this chapter is section 2.1?',
             'o': ['Purpose and structure of the balance sheet',
                   'Classifying debt',
                   'Current and noncurrent items',
                   'Other presentation matters'],
             'a': 'A',
             'why': 'The book numbers “Purpose and structure of the balance '
                    'sheet” as section 2.1.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 2.2?',
             'o': ['Classifying debt',
                   'Other presentation matters',
                   'Current and noncurrent items',
                   'Purpose and structure of the balance sheet'],
             'a': 'C',
             'why': 'The book numbers “Current and noncurrent items” as '
                    'section 2.2.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 2.3?',
             'o': ['Purpose and structure of the balance sheet',
                   'Classifying debt',
                   'Other presentation matters',
                   'Current and noncurrent items'],
             'a': 'B',
             'why': 'The book numbers “Classifying debt” as section 2.3.'},
            {'t': 'MCQ',
             'q': 'Which part of this chapter is section 2.4?',
             'o': ['Current and noncurrent items',
                   'Purpose and structure of the balance sheet',
                   'Other presentation matters',
                   'Classifying debt'],
             'a': 'C',
             'why': 'The book numbers “Other presentation matters” as '
                    'section 2.4.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which question does the balance sheet help users answer '
                  'MOST directly?',
             'o': ['How profitable was the company this year?',
                   'How much cash did operations produce this year?',
                   'What is the market value of the company?',
                   'Can the company pay its debts as they fall due?'],
             'a': 'D',
             'why': 'The balance sheet shows resources and obligations for '
                    'judging liquidity and solvency. A is wrong: '
                    'Profitability is shown on the income statement. B is '
                    'wrong: Operating cash flow is on the statement of cash '
                    'flows.',
             'src': 'P2-01'},
            {'t': 'MCQ',
             'q': 'The ability of a company to take effective action to '
                  'change the amounts and timing of cash flows is called:',
             'o': ['liquidity.',
                   'financial flexibility.',
                   'solvency.',
                   'working capital.'],
             'a': 'B',
             'why': 'Financial flexibility is the ability to respond to '
                    'unexpected needs and opportunities. A is wrong: '
                    'Liquidity is about meeting short-term obligations. C is '
                    'wrong: Solvency is about meeting all obligations over '
                    'time.',
             'src': 'P2-02'},
            {'t': 'MCQ',
             'q': 'Why do U.S. SEC registrants present a classified balance '
                  'sheet?',
             'o': ['So users can separate short-term resources and '
                   'obligations from long-term ones',
                   'So assets are shown at fair value',
                   'So equity equals the market value of the shares',
                   'So the balance sheet can be prepared without notes'],
             'a': 'A',
             'why': 'Classification shows the short-term position clearly. B '
                    'is wrong: Classification does not change measurement. C '
                    'is wrong: Equity is a book amount.',
             'src': 'P2-03'},
            {'t': 'MCQ',
             'q': 'Which item is a noncurrent asset?',
             'o': ['Prepaid rent for the next six months',
                   'Trading securities',
                   'Inventory',
                   'Cash surrender value of a life insurance policy'],
             'a': 'D',
             'why': 'Cash surrender value is excluded from current assets. A '
                    'is wrong: Prepaid rent for six months will be used up '
                    'within a year. B is wrong: Trading securities are held '
                    'for sale soon.',
             'src': 'P2-04'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Which question does the balance sheet help users answer MOST '
           'directly?',
           ['How profitable was the company this year?',
            'How much cash did operations produce this year?',
            'What is the market value of the company?',
            'Can the company pay its debts as they fall due?'],
           'D',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           'The balance sheet shows resources and obligations for judging '
           'liquidity and solvency. A is wrong: Profitability is shown on '
           'the income statement. B is wrong: Operating cash flow is on the '
           'statement of cash flows.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Account — the book’s own table',
           [['Account', 'Category'],
            ['Prepaid rent', 'Current asset'],
            ['Land', 'Noncurrent asset'],
            ['Allowance for credit losses', 'Current asset'],
            ['Dividends payable', 'Current liability'],
            ['Additional paid-in capital', 'Equity']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['balance sheet', 'الميزانية العمومية'],
            ['working capital', 'رأس المال العامل'],
            ['liquidity', 'السيولة'],
            ['covenant', 'تعهد (شرط) في اتفاقية القرض'],
            ['right of setoff', 'حق المقاصة']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MATCH',
             'q': 'Write the letter of the Arabic term beside each English '
                  'term. Every term is used once.',
             'left': ['right of setoff',
                      'liquidity',
                      'balance sheet',
                      'working capital',
                      'covenant'],
             'right': ['تعهد (شرط) في اتفاقية القرض',
                       'حق المقاصة',
                       'رأس المال العامل',
                       'الميزانية العمومية',
                       'السيولة'],
             'a': ['B', 'E', 'D', 'C', 'A'],
             'whys': ['', '', '', '', '']},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Prepaid rent?',
             'o': ['Equity',
                   'Current liability',
                   'Noncurrent asset',
                   'Current asset'],
             'a': 'D',
             'why': 'The book’s own table gives Current asset as the '
                    'category of Prepaid rent.'},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Land?',
             'o': ['Equity',
                   'Current liability',
                   'Current asset',
                   'Noncurrent asset'],
             'a': 'D',
             'why': 'The book’s own table gives Noncurrent asset as the '
                    'category of Land.'},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Allowance for '
                  'credit losses?',
             'o': ['Equity',
                   'Current liability',
                   'Noncurrent asset',
                   'Current asset'],
             'a': 'D',
             'why': 'The book’s own table gives Current asset as the '
                    'category of Allowance for credit losses.'}]),
          ('move', 'APPLY', ''),
          ('panel',
           'Orontes Foods Inc. (whole USD) — the extract for the question '
           'that follows',
           [['Orontes Foods Inc. (whole USD)',
             'Dec 31, 2025',
             'Dec 31, 2024'],
            ['ASSETS', '', ''],
            ['Current assets', '', ''],
            ['Cash', '7,302,100', '2,100,000'],
            ['Trading securities', '42,000', '40,000'],
            ['Accounts receivable, net of allowance (2025: 156,000; 2024: '
             '140,000)',
             '4,144,000',
             '3,760,000'],
            ['Inventory', '2,450,000', '2,300,000'],
            ['Prepaid expenses', '204,000', '180,000'],
            ['Assets held for sale', '46,000', '—'],
            ['Total current assets', '14,188,100', '8,380,000'],
            ['Noncurrent assets', '', ''],
            ['Debt securities (held-to-maturity and available-for-sale)',
             '88,500',
             '90,000'],
            ['Equity securities', '27,000', '25,000'],
            ['Equity-method investments', '1,807,000', '500,000'],
            ['Property, plant and equipment, net of accumulated depreciation '
             '(2025: 11,988,000; 2024: 8,000,000)',
             '14,802,000',
             '16,000,000'],
            ['Brand (indefinite-lived)', '260,000', '300,000'],
            ['Goodwill', '300,000', '950,000'],
            ['Other noncurrent assets', '200,000', '200,000'],
            ['TOTAL ASSETS', '31,672,600', '26,445,000'],
            ["LIABILITIES AND STOCKHOLDERS' EQUITY", '', ''],
            ['Current liabilities', '', ''],
            ['Accounts payable', '2,050,000', '1,900,000'],
            ['Accrued liabilities', '900,000', '850,000'],
            ['Income taxes payable', '350,000', '300,000'],
            ['Contract liabilities', '180,000', '120,000'],
            ['Dividends payable', '400,000', '—'],
            ['Current portion of long-term debt', '400,000', '400,000'],
            ['Total current liabilities', '4,280,000', '3,570,000'],
            ['Long-term debt, less current portion',
             '6,000,000',
             '5,600,000'],
            ['Deferred tax liability', '999,625', '900,000'],
            ['Total liabilities', '11,279,625', '10,070,000'],
            ['Commitments and contingencies (Note 12)', '', ''],
            ["Stockholders' equity", '', ''],
            ['Common stock, $1 par; shares issued and outstanding: 2025 '
             '8,100,000, 2024 8,000,000',
             '8,100,000',
             '8,000,000'],
            ['Additional paid-in capital', '5,400,000', '4,000,000'],
            ['Retained earnings', '6,894,100', '4,375,000'],
            ['Accumulated other comprehensive income (loss)', '(1,125)', '—'],
            ["Total stockholders' equity", '20,392,975', '16,375,000'],
            ["TOTAL LIABILITIES AND STOCKHOLDERS' EQUITY",
             '31,672,600',
             '26,445,000']],
           ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'The extract for this question is printed with it. What is '
                  "Orontes's working capital at December 31, 2025 (whole "
                  'USD)?',
             'o': ['2,908,475', '9,908,100', '10,064,100', '10,308,100'],
             'a': 'B',
             'why': '$14,188,100 − $4,280,000 = $9,908,100. A is wrong: This '
                    'subtracts total liabilities. C is wrong: This adds back '
                    'the allowance; receivables are included net.',
             'src': 'P2-05'},
            {'t': 'MCQ',
             'q': 'The extract for this question is printed with it. What is '
                  "Orontes's current ratio at December 31, 2025?",
             'o': ['0.30', '2.35', '3.31', '3.62'],
             'a': 'C',
             'why': '$14,188,100 ÷ $4,280,000. A is wrong: This divides '
                    'current liabilities by current assets. B is wrong: This '
                    'is the 2024 ratio.',
             'src': 'P2-06'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'f1',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['balance sheet', 'working capital', 'liquidity', 'covenant'],
           "The balance sheet reports a company's assets, liabilities and "
           'equity at one point in time. It answers three questions for '
           'investors and lenders. Can the company pay its bills in the '
           'coming months? This is liquidity. Can it pay all its debts over '
           'time? This is solvency. Can it raise cash or change its plans if '
           'something unexpected happens? This is financial f')]}
