# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C8-1': ('case item C8-1', []),
    'C8-2': ('case item C8-2', []),
    'C8-3': ('case item C8-3', []),
    'C8-4': ('case item C8-4', []),
    'C8-5': ('case item C8-5', []),
    'C8-6': ('case item C8-6', []),
    'P8-01': ('practice item P8-01', []),
    'P8-02': ('practice item P8-02', []),
    'P8-03': ('practice item P8-03', []),
    'P8-04': ('practice item P8-04', []),
    'P8-05': ('practice item P8-05', []),
    'P8-06': ('practice item P8-06', []),
    'P8-07': ('practice item P8-07', []),
    'P8-08': ('practice item P8-08', []),
    'P8-09': ('practice item P8-09', []),
    'P8-10': ('practice item P8-10', []),
    'P8-11': ('practice item P8-11', []),
    'P8-12': ('practice item P8-12', []),
    'P8-13': ('practice item P8-13', []),
    'P8-14': ('practice item P8-14', []),
    'P8-15': ('practice item P8-15', []),
    'P8-16': ('practice item P8-16', []),
    'P8-17': ('practice item P8-17', []),
    'SC8-1': ('section-check item SC8-1', []),
    'SC8-2': ('section-check item SC8-2', []),
    'SC8-3': ('section-check item SC8-3', []),
    'SC8-4': ('section-check item SC8-4', []),
    'SC8-5': ('section-check item SC8-5', []),
    'SC8-6': ('section-check item SC8-6', []),
    'SC8-7': ('section-check item SC8-7', []),
    'SC8-8': ('section-check item SC8-8', []),
    'SC8-9': ('section-check item SC8-9', []),
    'term:ceiling': ("term-bridge row 'ceiling'", []),
    'term:conventional retail method': ("term-bridge row 'conventional retail method'", []),
    'term:cost-to-retail ratio': ("term-bridge row 'cost-to-retail ratio'", []),
    'term:floor': ("term-bridge row 'floor'", []),
    'term:gross profit method': ("term-bridge row 'gross profit method'", []),
    'term:item-by-item basis': ("term-bridge row 'item-by-item basis'", []),
    'term:lower of cost and net realizable value (lcnrv)': ("term-bridge row 'lower of cost and net realizable value (LCNRV)'", []),
    'term:lower of cost or market (lcm)': ("term-bridge row 'lower of cost or market (LCM)'", []),
    'term:markdown': ("term-bridge row 'markdown'", []),
    'term:markup': ("term-bridge row 'markup'", []),
    'term:net realizable value (nrv)': ("term-bridge row 'net realizable value (NRV)'", []),
    'term:normal profit margin': ("term-bridge row 'normal profit margin'", []),
    'term:purchase commitment': ("term-bridge row 'purchase commitment'", []),
    'term:replacement cost': ("term-bridge row 'replacement cost'", []),
    'term:retail inventory method': ("term-bridge row 'retail inventory method'", []),
    'term:shrinkage': ("term-bridge row 'shrinkage'", []),
    'term:write-down': ("term-bridge row 'write-down'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C8-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P8-03': 'it sends the reader to F08-05, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'P8-06': 'it sends the reader to F08-06, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
    'SC8-3': 'it sends the reader to F08-05, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
