# -*- coding: utf-8 -*-
"""Handout 1.2, generated by wsgen. Do not edit by hand."""

HANDOUT = {'id': '1.2',
 'n': 2,
 'pages': 5,
 'title': 'The building blocks: elements and the accounting equation',
 'sub': 'section 1.2 of the book',
 'covers': ['sec:1.2',
            'p:P02',
            'p:P15',
            'p:P16',
            'sc:SC2-1',
            'sc:SC2-2',
            'sc:SC2-1',
            'sc:SC2-2',
            'term:primary users',
            'term:retained earnings',
            'term:matching principle',
            'term:materiality',
            'term:common stock',
            'term:t-account',
            'term:accounts payable',
            'term:contract liability (unearned revenue)',
            'term:balance sheet'],
 'skills': [('read2', 3)],
 'derived': {},
 'flow': [('preview',
           'Before you start',
           'Three summaries of this handout, in the book’s own words. Read '
           'all three first: together they are the whole session. Then fill '
           'the gaps, guessing where you have to.',
           [['In this handout', 'What you will read', 'How you check it'],
            ['The building blocks: elements and the accounting equation',
             'a figure to read · Account',
             'Which item is an expense?'],
            ['The words this section uses precisely',
             'Row · The English the exam uses, and what it translates',
             'What is the safest way to settle a disagreement about an '
             'answer on this sheet?']],
           [{'t': 'FILL',
             'q': 'Where the section starts — Fill every gap. The list holds '
                  'more words than there are gaps, so one or two of them are '
                  'not used.',
             'parts': ['Three of them describe the ',
                       15,
                       ' at one date. An ',
                       11,
                       ' is a present right of an entity to an economic '
                       'benefit. Examples: cash, ',
                       21,
                       ', ',
                       11,
                       ' and equipment. A ',
                       11,
                       ' is a present obligation of an entity to transfer an '
                       'economic benefit.'],
             'bank': ['balance sheet',
                      'inventory',
                      'revenue',
                      'asset',
                      'dividend',
                      'accounts receivable',
                      'liability'],
             'a': 'balance sheet · asset · accounts receivable · inventory · '
                  'liability',
             'one': True,
             'why': 'The book writes: “Three of them describe the balance '
                    'sheet at one date. An asset is a present right of an '
                    'entity to an economic benefit. Examples: cash, accounts '
                    'receivable, inventory and equipment. A liability is a '
                    'present obligation of an entity to transfer an economic '
                    'benefit.”'},
            {'t': 'FILL',
             'q': 'What it settles in the middle — Fill every gap. The list '
                  'holds more words than there are gaps, so one or two of '
                  'them are not used.',
             'parts': ['You will meet it in Chapters 3 and 15. The equation '
                       'always holds, because creditors (liabilities) or '
                       'owners (',
                       11,
                       ') finance every ',
                       11,
                       '. Contributed capital is what owners paid in: ',
                       14,
                       ' at its ',
                       11,
                       ', plus ',
                       28,
                       ' (APIC).'],
             'bank': ['revenue',
                      'dividend',
                      'common stock',
                      'asset',
                      'additional paid-in capital',
                      'par value',
                      'equity'],
             'a': 'equity · asset · common stock · par value · additional '
                  'paid-in capital',
             'one': True,
             'why': 'The book writes: “You will meet it in Chapters 3 and '
                    '15. The equation always holds, because creditors '
                    '(liabilities) or owners (equity) finance every asset. '
                    'Contributed capital is what owners paid in: common '
                    'stock at its par value, plus additional paid-in capital '
                    '(APIC).”'},
            {'t': 'FILL',
             'q': 'Where it ends — Fill every gap. The list holds more words '
                  'than there are gaps, so one or two of them are not used.',
             'parts': ['IFRS also uses the word income for both revenue and '
                       'gains, while ',
                       11,
                       ' keeps revenues and gains apart. You may also know '
                       'these IFRS names: ',
                       33,
                       ' (',
                       15,
                       '), share capital (',
                       14,
                       ') and share premium (',
                       28,
                       ').'],
             'bank': ['balance sheet',
                      'statement of financial position',
                      'common stock',
                      'U.S. GAAP',
                      'dividend',
                      'additional paid-in capital',
                      'revenue'],
             'a': 'U.S. GAAP · statement of financial position · balance '
                  'sheet · common stock · additional paid-in capital',
             'one': True,
             'why': 'The book writes: “IFRS also uses the word income for '
                    'both revenue and gains, while U.S. GAAP keeps revenues '
                    'and gains apart. You may also know these IFRS names: '
                    'statement of financial position (balance sheet), share '
                    'capital (common stock) and share premium (additional '
                    'paid-in capital).”'}],
           [('Words this handout uses precisely',
             [['Words this handout uses precisely',
               'tick it if you could already use it in a sentence'],
              ['primary users', ''],
              ['retained earnings', ''],
              ['matching principle', ''],
              ['materiality', ''],
              ['common stock', ''],
              ['T-account', ''],
              ['accounts payable', '']]),
            ('How every cycle on this sheet works',
             [['How a cycle works', 'what you do'],
              ['MODEL',
               'read the figure or the table before you answer anything'],
              ['READ THE MODEL', 'every answer is printed on the same page'],
              ['INVENT THE RULE',
               'write the rule yourself, then compare with the book'],
              ['APPLY', 'no help on this move'],
              ['CHECKPOINT',
               'mark it yourself; if you miss it, the sheet says what to '
               'redo']])]),
          ('page',),
          ('cycle',
           'A',
           'The building blocks: elements and the accounting equation'),
          ('move',
           'ORIENT',
           'One claim. Decide now; you will check it in a moment.'),
          ('items',
           [{'t': 'TF',
             'q': 'The book gives the category of Accumulated depreciation '
                  'as “Contra-asset”.',
             'a': 'T',
             'why': 'The book pairs Accumulated depreciation with '
                    '“Contra-asset”.'}]),
          ('move', 'MODEL', 'Read it before you answer anything below it.'),
          ('fig', 'beam'),
          ('panel',
           'Account — the book’s own table',
           [['Account', 'Category'],
            ['Prepaid rent', 'Asset'],
            ['Land', 'Asset'],
            ['Dividends payable', 'Liability'],
            ['Additional paid-in capital', 'Equity'],
            ['Sales revenue', 'Revenue'],
            ['Interest expense', 'Expense'],
            ['Allowance for credit losses', 'Contra-asset'],
            ['Accumulated depreciation', 'Contra-asset']],
           ''),
          ('move',
           'READ THE MODEL',
           'Every answer is printed above. Find it, do not recall it.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'Which category does the book give for Prepaid rent?',
             'o': ['Equity', 'Revenue', 'Asset', 'Expense'],
             'a': 'C',
             'why': 'The book’s own table gives Asset as the category of '
                    'Prepaid rent.'}]),
          ('move', 'APPLY', 'No help on this move.'),
          ('items',
           [{'t': 'MCQ',
             'q': 'A bank is deciding whether to renew a five-year loan to '
                  'Orontes. Which information will the bank find MOST '
                  'useful?',
             'o': ['The highest and lowest share price during the year',
                   "The company's ability to generate cash to pay interest "
                   'and repay principal',
                   'The number of products the company sells',
                   "The names of the company's major shareholders"],
             'a': 'B',
             'why': "A lender's main question is repayment: can the borrower "
                    'pay interest and principal on time? A is wrong: Share '
                    'prices interest investors more than lenders and do not '
                    'show repayment ability. C is wrong: The product count '
                    'does not show whether the company can repay the loan.',
             'src': 'P02'},
            {'t': 'MCQ',
             'q': 'Which statement is TRUE?',
             'o': ['The PCAOB writes U.S. GAAP for public companies.',
                   'The IASB writes U.S. GAAP for companies that also report '
                   'under IFRS.',
                   'The ASC contains IFRS for U.S. companies.',
                   'The SEC has legal authority over public company '
                   'reporting and recognizes the FASB as the standard '
                   'setter.'],
             'a': 'D',
             'why': 'The SEC has the legal authority; the FASB sets the '
                    'standards; the ASC holds U.S. GAAP. A is wrong: The '
                    'PCAOB sets auditing standards. B is wrong: The IASB '
                    'writes IFRS only.',
             'src': 'P15'},
            {'t': 'MCQ',
             'q': "A Jordanian company's IFRS statements show share premium "
                  'of 400. Under U.S. GAAP, the same item is called:',
             'o': ['retained earnings.',
                   'common stock.',
                   'additional paid-in capital.',
                   'treasury stock.'],
             'a': 'C',
             'why': 'Share premium and additional paid-in capital both mean '
                    'the amount received above par value. A is wrong: '
                    'Retained earnings come from profits, not from issuing '
                    'shares. B is wrong: Common stock holds only the par '
                    'value.',
             'src': 'P16'}]),
          ('pair',
           'Compare every answer on this page with your partner before you '
           'read any key.',
           'go back to the model and find the row that settles it. The row '
           'decides, not the louder voice.'),
          ('check',
           'Which item is an expense?',
           ['A cash dividend paid to shareholders',
            'Wages paid to plant workers',
            'Repayment of a bank loan',
            'Purchase of a new bottling line'],
           'B',
           'redo the READ THE MODEL questions of cycle A with the model in '
           'front of you.',
           "Wages are a cost of the company's central operations, so they "
           'are an expense. A is wrong: A dividend is a distribution to '
           'owners. It reduces retained earnings but is not an expense. C is '
           'wrong: Repaying principal reduces a liability and an asset. No '
           'expense arises.'),
          ('cycle', 'B', 'The words this section uses precisely'),
          ('move', 'ORIENT', ''),
          ('items',
           [{'t': 'TF',
             'q': 'A term in the exam means exactly what the book defines it '
                  'to mean, whatever it means in ordinary English.',
             'a': 'T',
             'why': 'CMA questions use exact terms, and one word can change '
                    'the answer.'}]),
          ('move', 'MODEL', ''),
          ('panel',
           'Row — the book’s own table',
           [['Row', 'Transaction', 'Journal entry', 'Effects'],
            ['4',
             'A Dubai hotel group paid cash in advance for pastries that '
             'Orontes will deliver in March.',
             'Dr Cash 60; Cr Contract liability (unearned revenue) 60',
             'Assets +60, liabilities +60, equity 0, net income 0; cash '
             'flow: operating +60.'],
            ['5',
             'Paid the dividend declared on January 31.',
             'Dr Dividends payable 50; Cr Cash 50',
             'Assets (50), liabilities (50), equity 0, net income 0; cash '
             'flow: financing (50).'],
            ['6',
             'Recorded one month of interest on the bank note. Orontes has '
             'not paid it yet.',
             'Dr Interest expense 4; Cr Interest payable 4',
             'Assets 0, liabilities +4, equity (4), net income (4); cash '
             'flow: none.']],
           ''),
          ('panel',
           'The English the exam uses, and what it translates',
           [['English (exam term)', 'the Arabic it translates'],
            ['primary users', 'المستخدمون الرئيسيون'],
            ['retained earnings', 'الأرباح المحتجزة'],
            ['matching principle', 'مبدأ مقابلة الإيرادات بالمصروفات'],
            ['materiality', 'الأهمية النسبية'],
            ['common stock', 'الأسهم العادية'],
            ['T-account', 'حساب على شكل حرف T'],
            ['accounts payable', 'الذمم الدائنة (الدائنون)'],
            ['contract liability (unearned revenue)',
             'التزام العقد (إيراد مقبوض مقدماً)'],
            ['balance sheet', 'الميزانية العمومية']],
           ''),
          ('move', 'READ THE MODEL', ''),
          ('items',
           [{'t': 'MATCH',
             'q': 'Write the letter of the Arabic term beside each English '
                  'term. Every term is used once.',
             'left': ['common stock',
                      'T-account',
                      'primary users',
                      'matching principle',
                      'accounts payable',
                      'retained earnings'],
             'right': ['الأرباح المحتجزة',
                       'الذمم الدائنة (الدائنون)',
                       'حساب على شكل حرف T',
                       'المستخدمون الرئيسيون',
                       'مبدأ مقابلة الإيرادات بالمصروفات',
                       'الأسهم العادية'],
             'a': ['F', 'C', 'D', 'E', 'B', 'A'],
             'whys': ['', '', '', '', '', '']}]),
          ('move', 'APPLY', ''),
          ('items',
           [{'t': 'MCQ',
             'q': 'A company has total assets of 500 and total liabilities '
                  'of 320. What is its equity?',
             'o': ['180', '320', '500', '820'],
             'a': 'A',
             'why': 'Equity = assets − liabilities = 500 − 320 = 180. B is '
                    'wrong: This is the liabilities figure, not equity. C is '
                    'wrong: This is total assets, not equity.',
             'src': 'SC2-2'},
            {'t': 'MCQ',
             'q': 'Which item is an expense?',
             'o': ['A cash dividend paid to shareholders',
                   'Wages paid to plant workers',
                   'Repayment of a bank loan',
                   'Purchase of a new bottling line'],
             'a': 'B',
             'why': "Wages are a cost of the company's central operations, "
                    'so they are an expense. A is wrong: A dividend is a '
                    'distribution to owners. It reduces retained earnings '
                    'but is not an expense. C is wrong: Repaying principal '
                    'reduces a liability and an asset. No expense arises.',
             'src': 'SC2-1'},
            {'t': 'MCQ',
             'q': 'Which category does the book give for Accumulated '
                  'depreciation?',
             'o': ['Revenue', 'Liability', 'Expense', 'Contra-asset'],
             'a': 'D',
             'why': 'The book’s own table gives Contra-asset as the category '
                    'of Accumulated depreciation.'}]),
          ('check',
           'What is the safest way to settle a disagreement about an answer '
           'on this sheet?',
           ['find the row of the model that decides it',
            'take the answer of whoever is more confident',
            'leave it until the lecturer says',
            'choose the longer option'],
           'A',
           'redo the READ THE MODEL questions of cycle B.',
           'Every item on a Workshop sheet is settled by something printed '
           'on the same sheet.'),
          ('build',
           'beam',
           'Rebuild the figure from this handout. Label every part and fill '
           'in every box.',
           'Compare with the model earlier in this handout.'),
          ('teach',
           'a classmate who missed this session',
           'In three or four sentences, write what this section settles and '
           'the one rule a reader has to take away.',
           ['primary users',
            'retained earnings',
            'matching principle',
            'materiality'],
           'Every amount in the financial statements belongs to an element. '
           'The FASB conceptual framework defines ten elements. Three of '
           'them describe the balance sheet at one date.')]}
