# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C6-1': ('case item C6-1', []),
    'C6-2': ('case item C6-2', []),
    'C6-3': ('case item C6-3', []),
    'C6-4': ('case item C6-4', []),
    'C6-5': ('case item C6-5', []),
    'C6-6': ('case item C6-6', []),
    'P6-01': ('practice item P6-01', []),
    'P6-02': ('practice item P6-02', []),
    'P6-03': ('practice item P6-03', []),
    'P6-04': ('practice item P6-04', []),
    'P6-05': ('practice item P6-05', []),
    'P6-06': ('practice item P6-06', []),
    'P6-07': ('practice item P6-07', []),
    'P6-08': ('practice item P6-08', []),
    'P6-09': ('practice item P6-09', []),
    'P6-10': ('practice item P6-10', []),
    'P6-11': ('practice item P6-11', []),
    'P6-12': ('practice item P6-12', []),
    'P6-13': ('practice item P6-13', []),
    'P6-14': ('practice item P6-14', []),
    'P6-15': ('practice item P6-15', []),
    'P6-16': ('practice item P6-16', []),
    'SC6-1': ('section-check item SC6-1', []),
    'SC6-2': ('section-check item SC6-2', []),
    'SC6-3': ('section-check item SC6-3', []),
    'SC6-4': ('section-check item SC6-4', []),
    'SC6-5': ('section-check item SC6-5', []),
    'term:accounts receivable': ("term-bridge row 'accounts receivable'", []),
    'term:aging schedule': ("term-bridge row 'aging schedule'", []),
    'term:allowance for credit losses': ("term-bridge row 'allowance for credit losses'", []),
    'term:amortized cost': ("term-bridge row 'amortized cost'", []),
    'term:cash discount': ("term-bridge row 'cash discount'", []),
    'term:contract asset': ("term-bridge row 'contract asset'", []),
    'term:credit loss expense': ("term-bridge row 'credit loss expense'", []),
    'term:current expected credit losses (cecl)': ("term-bridge row 'current expected credit losses (CECL)'", []),
    'term:direct write-off method': ("term-bridge row 'direct write-off method'", []),
    'term:effective control': ("term-bridge row 'effective control'", []),
    'term:factor': ("term-bridge row 'factor'", []),
    'term:factoring': ("term-bridge row 'factoring'", []),
    'term:holdback (due from factor)': ("term-bridge row 'holdback (due from factor)'", []),
    'term:legal isolation': ("term-bridge row 'legal isolation'", []),
    'term:notes receivable': ("term-bridge row 'notes receivable'", []),
    'term:pledging': ("term-bridge row 'pledging'", []),
    'term:recourse': ("term-bridge row 'recourse'", []),
    'term:recourse liability': ("term-bridge row 'recourse liability'", []),
    'term:recovery': ("term-bridge row 'recovery'", []),
    'term:secured borrowing': ("term-bridge row 'secured borrowing'", []),
    'term:write-off': ("term-bridge row 'write-off'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C6-4': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'P6-03': 'it sends the reader to F06-04, which is a box, or a table too long to carry on a four-page sheet beside its own questions',
}
