# -*- coding: utf-8 -*-
"""Derived from the chapter itself by gen.py. Do not edit."""
LEDGER = {
    'C18-1': ('case item C18-1', []),
    'C18-2': ('case item C18-2', []),
    'C18-3': ('case item C18-3', []),
    'C18-4': ('case item C18-4', []),
    'C18-5': ('case item C18-5', []),
    'C18-6': ('case item C18-6', []),
    'P18-01': ('practice item P18-01', []),
    'P18-02': ('practice item P18-02', []),
    'P18-03': ('practice item P18-03', []),
    'P18-04': ('practice item P18-04', []),
    'P18-05': ('practice item P18-05', []),
    'P18-06': ('practice item P18-06', []),
    'P18-07': ('practice item P18-07', []),
    'P18-08': ('practice item P18-08', []),
    'P18-09': ('practice item P18-09', []),
    'P18-10': ('practice item P18-10', []),
    'P18-11': ('practice item P18-11', []),
    'P18-12': ('practice item P18-12', []),
    'P18-13': ('practice item P18-13', []),
    'P18-14': ('practice item P18-14', []),
    'P18-15': ('practice item P18-15', []),
    'P18-16': ('practice item P18-16', []),
    'SC18-1': ('section-check item SC18-1', []),
    'SC18-10': ('section-check item SC18-10', []),
    'SC18-11': ('section-check item SC18-11', []),
    'SC18-2': ('section-check item SC18-2', []),
    'SC18-3': ('section-check item SC18-3', []),
    'SC18-4': ('section-check item SC18-4', []),
    'SC18-5': ('section-check item SC18-5', []),
    'SC18-6': ('section-check item SC18-6', []),
    'SC18-7': ('section-check item SC18-7', []),
    'SC18-8': ('section-check item SC18-8', []),
    'SC18-9': ('section-check item SC18-9', []),
    'term:capitals': ("term-bridge row 'capitals'", []),
    'term:content elements': ("term-bridge row 'content elements'", []),
    'term:financial capital': ("term-bridge row 'financial capital'", []),
    'term:guiding principles': ("term-bridge row 'guiding principles'", []),
    'term:human capital': ("term-bridge row 'human capital'", []),
    'term:integrated report': ("term-bridge row 'integrated report'", []),
    'term:integrated reporting': ("term-bridge row 'integrated reporting'", []),
    'term:integrated thinking': ("term-bridge row 'integrated thinking'", []),
    'term:intellectual capital': ("term-bridge row 'intellectual capital'", []),
    'term:manufactured capital': ("term-bridge row 'manufactured capital'", []),
    'term:natural capital': ("term-bridge row 'natural capital'", []),
    'term:outcomes': ("term-bridge row 'outcomes'", []),
    'term:outputs': ("term-bridge row 'outputs'", []),
    'term:social and relationship capital': ("term-bridge row 'social and relationship capital'", []),
    'term:value creation process': ("term-bridge row 'value creation process'", []),
}

# Units that cannot be converted faithfully, and why. They
# are recorded rather than dropped quietly, so the gap is
# visible in the build and in the diff.
OMIT = {
    'C18-1': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
    'C18-4': 'the book answers it with a drag-and-drop or a worked table rather than a single value',
}
